### ISSUE TITLE
VOS7: Virtuoso sesame provider 2.6.10: hasStatement returns incorrect value

### ISSUE THREAD

**Issue by nvdk** [openlink/virtuoso-opensource#100]
The virtuoso 2.6.10 provider available on http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VOSDownload does not work correctly with VOS 7 (Version 7.0.0.3203-pthreads as of Sep  5 2013).

Given that the provided graph contains a few triples, the following code should print out true 3 times.

```
boolean  test = repository.getConnection().hasStatement(null, null, null, false, graph)
System.out.print(test);
test = repository.getConnection().prepareBooleanQuery(QueryLanguage.SPARQL, "ASK  {?s ?p ?o}").evaluate();
System.out.print(test);
test = repository.getConnection().prepareTupleQuery(QueryLanguage.SPARQL, "SELECT * where  {?s ?p ?o}").evaluate().hasNext();
System.out.print(test);
```

However it results in:

```
false
false
true
```

**Comment by Rahien** [comment]
I have a related issue:

I am using Virtuoso 07.00.3203 on Linux with the virtuoso driver for sesame 2.7.3 build 1.12 and the virtuoso jdbc4 driver build 3.62

I run the following queries from java:

```
StringBuilder builder = new StringBuilder();
            builder.append("ASK { { <").append(uri).append("> ?p ?o. Bind( <").append(uri).append("> as ?s ). } UNION ");
            builder.append("{ ?s ?p <"+uri+"> . Bind( <"+uri+"> as ?o ) . } UNION ");
            builder.append("{ ?s <" +uri+ "> ?o . Bind( <"+uri+"> as ?p ) . } UNION ");
            builder.append("{ GRAPH <"+uri+"> {?s ?p ?o} }}");
boolean first = this.connection.prepareBooleanQuery(QueryLanguage.SPARQL,builder.toString()).evaluate();

builder = new StringBuilder();
            builder.append("SELECT * { { <").append(uri).append("> ?p ?o. Bind( <").append(uri).append("> as ?s ). } UNION ");
            builder.append("{ ?s ?p <"+uri+"> . Bind( <"+uri+"> as ?o ) . } UNION ");
            builder.append("{ ?s <" +uri+ "> ?o . Bind( <"+uri+"> as ?p ) . } UNION ");
            builder.append("{ GRAPH <"+uri+"> {?s ?p ?o} }} LIMIT ");

boolean second = this.connection.prepareTupleQuery(QueryLanguage.SPARQL,builder.toString()).evaluate().hasNext();

builder = new StringBuilder();
builder.append("ASK { <").append(uri).append("> ?p ?o. } ");
boolean third = this.connection.prepareBooleanQuery(QueryLanguage.SPARQL,builder.toString()).evaluate();

builder = new StringBuilder();
builder.append("SELECT * { <").append(uri).append("> ?p ?o. } LIMIT 1 ");
boolean fourth = this.connection.prepareTupleQuery(QueryLanguage.SPARQL,builder.toString()).evaluate().hasNext();

builder = new StringBuilder();
builder.append("SELECT * { <").append(uri).append("> ?p ?o. } LIMIT 2 ");
boolean fifth = this.connection.prepareTupleQuery(QueryLanguage.SPARQL,builder.toString()).evaluate().hasNext();
```

this results in:

```
first == false
second == false
thrid == false
fourth == false
fifth == true
```

all queries give the right results (true) in the conductor's html sparql endpoint

**Comment by HughWilliams** [comment]
What happens if you run the same queries from the isql command line tool ie SQL which is what method the Virtuoso Sesame provider uses to connect to the server ie via JDBC ?

Also, what are the actual queries being run against the sparql endpoint (and isql) ?

**Comment by Rahien** [comment]
The queries are all variants of the target query below:

```
SQL> SPARQL ASK { { <http://lod2.tenforce.com/wp8/dataset/testdataset> ?p ?o. 
   Bind( <http://lod2.tenforce.com/wp8/dataset/testdataset> as ?s ). } UNION
   { ?s ?p <http://lod2.tenforce.com/wp8/dataset/testdataset> .
      Bind( <http://lod2.tenforce.com/wp8/dataset/testdataset> as ?o ) . } UNION
   { ?s <http://lod2.tenforce.com/wp8/dataset/testdataset> ?o . 
      Bind( <http://lod2.tenforce.com/wp8/dataset/testdataset> as ?p ) . } UNION 
   { GRAPH <http://lod2.tenforce.com/wp8/dataset/testdataset> {?s ?p ?o} }};
__ask_retval
INTEGER NOT NULL
_______________________________________________________________________________

1

1 Rows. -- 10 msec.
```

As you can see, this query does return the expected result in the isql command line interface.

The other query results are:

```
first == example above == true
second == http://www.w3.org/1999/02/22-rdf-syntax-ns#type  http://www.w3.org/ns/dcat#Dataset http://lod2.tenforce.com/wp8/dataset/testdataset
third == true
fourth == http://www.w3.org/1999/02/22-rdf-syntax-ns#type                                   http://www.w3.org/ns/dcat#Dataset
fifth == http://www.w3.org/1999/02/22-rdf-syntax-ns#type                                   http://www.w3.org/ns/dcat#Dataset
            http://purl.org/dc/terms/modified                                                 2013-10-30 14:37:00
```

(In fact, the 'Bind's in the target query should not be necessary, but it triggered a sesame bug in an earlier version of sesame if they were left out.)

**Comment by HughWilliams** [comment]
HI Karel, OK, are you able to provide a sample program I an compile from commandline to recreate this issue locally and have development look into it ?

**Comment by Rahien** [comment]
Hi Hugh,
The problem seems to be that if a tuplequeryresultset contains only one triple, hasNext on its iterator returns false. (it should return true, as an iterator should start on the index right before the first element).

```
[connect to virtuoso store here and get a connection]
TupleQueryResult result=this.connection.prepareTupleQuery(QueryLanguage.SPARQL,
 "SELECT * WHERE {?s ?p ?o } LIMIT 1").evaluate();

if(result.hasNext()){
    System.out.print("success");
}else{
    System.out.print("fail");
}
```

That is, this is the reason for my problem, I think Niels' original problem is then after all not related to this, so now I feel somewhat bad for hijacking his thread.

**Comment by Rahien** [comment]
Also, I checked with the debugger, and the internals of the resultset do indeed contain the right values...

**Comment by HughWilliams** [comment]
Hi Karel,

I see what you mean and have reported to development to look into. Will let you know when a fix is available ...

**Comment by nvdk** [comment]
To get back to my original bug. It seems these statements are covered in the test suite and are in fact failing at the moment. 
https://github.com/openlink/virtuoso-opensource/blob/develop/6/binsrc/sesame2/virtuoso_driver/VirtuosoTest.java

**Comment by smalinin** [comment]
Worked properly with last version of Sesame2 provider and JDBC driver from develop/7 branch.

The current version of Sesame2 provider is 2.7.3, also it is better to use JDBC driver ver 3.66 (everything from develop/7 branch)
The example:

```
    VirtuosoRepository repository = new VirtuosoRepository("jdbc:virtuoso://localhost:1111", "dba", "dba");

    try {
        repository.initialize();            
    c = repository.getConnection();

        TupleQueryResult tr = c.prepareTupleQuery(QueryLanguage.SPARQL, "select ?s ?p ?o where { ?s ?p ?o } limit 1").evaluate();
        System.out.println("==================");
        while (tr.hasNext()) {
            System.out.println(tr.next());
        }
        System.out.println("==================");

    }
    catch (Exception e) {
    System.out.println("ERROR Test Failed.");
    e.printStackTrace();
    }
    finally {
    if (c != null) try {
        c.close();
    }
    catch (RepositoryException e) {
        e.printStackTrace();
    }
    }
```

Output log:

```
==================
[s=http://www.openlinksw.com/virtrdf-data-formats#default-iid;p=http://www.w3.org/1999/02/22-rdf-syntax-ns#type;o=http://www.openlinksw.com/schemas/virtrdf#QuadMapFormat]
==================
```

**Comment by nvdk** [comment]
@smalinin , that one works just fine (as I posted in my initial report), the others did/do not.

**Comment by jacekkopecky** [comment]
Hi, I seem to have run in the same problem: VirtuosoTest.java fails because something swallows the first result in queries like SELECT \* WHERE {?s ?p ?o} limit 1.

Indeed, a little test program that just runs SELECT \* WHERE {?s ?p ?o} limit 10 shows me just 9 results, where isql properly shows 10.

Strangely enough, adding DISTINCT to the query is a (clumsy) workaround here. But hasStatement still fails because I can't add DISTINCT there.

I'm using Version 7.1.0.3207-pthreads for Darwin, and tried Sesame 2.7.12 and 2.6.10, both 2.7 and 2.6 virt_sesame2.jar, both virtjdbc3 and virtjdbs4, all downloaded today.

**Comment by neoflex** [comment]
Hi,

This issue is still not solved?
If not, did you find a workaround somehow?
Thanks

**Comment by HughWilliams** [comment]
The issue was reported as working in Dec 2013, if you are having a problem please provide details of specific version of components being used and sample program and compile/run instructions for recreation ...

**Comment by jacekkopecky** [comment]
Hi, when I had the problem in June of this year, the problem manifested
itself already with the test file bindled with the library.

**Comment by smalinin** [comment]
The problem with VirtuosoTest  fails is fixed already, it was fixed in June this year also, the problem(in June) was, because virt_sesame2.jar binary was not recompiled. For example on 02-jun-2014 the sources has version build:1.14, but the binary has version build:1.12 else.  

If you don't used latest version of Virtuoso7 server, use the latest version of Virtuoso JDBC driver and virt_sesame2,jar(build 1.15) from 11-jun-2014 to 04-aug-2014 commits.  

The latest version of virt_sesame2.jar uses new server side stored procedures, it may not work with old version of Virtuoso7 server.  
The new stored procedures, that are used by latest version of virt_sesame2.jar, are in file ~/libsrc/Wi/ttlpv.sql

**Comment by jacekkopecky** [comment]
Ah, super, thank you.
