### ISSUE TITLE
.db file not being read after crash

### ISSUE THREAD

**Issue by doogyb** [openlink/virtuoso-opensource#1002]
The `virtuoso-t` process crashed and now it seems as though the `virtuoso.db` file is not being read - none of the graphs or previously ingested triples are available. I've tried the [how to recover a database](http://wikis.openlinksw.com/VirtuosoWikiWeb/HowToRecoverADatabase) from the troubleshooting but no luck.

**Comment by pkleef** [comment]
To determine the problem, we require a bit more information.

Please answer the following questions, so we can help you figure out what went wrong.

Q: What version of Virtuoso did you use? 

Q: Was this a binary you built yourself from the source tree, or did you use one of the docker images?

Q: What method did you use to ingest triples into this database?

Q: Has the database been cleanly shutdown and restarted after ingestion of the triples, before the recent crash?

Q: What sort of operations (SQL/SPARQL) where you running when Virtuoso crashed?

**Comment by doogyb** [comment]
> Q: What version of Virtuoso did you use?
```
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.6.3233-pthreads as of Jun 22 2021 (111d17e5b)
Compiled for Linux (x86_64-generic_glibc25-linux-gnu)
Copyright (C) 1998-2021 OpenLink Software
```


> Q: Was this a binary you built yourself from the source tree, or did you use one of the docker images?

I used `virtuoso-opensource.x86_64-generic_glibc25-linux-gnu.tar.gz` found [here](https://github.com/openlink/virtuoso-opensource/releases/tag/v7.2.6.1)


> Q: What method did you use to ingest triples into this database?

I used the bulk loading method as described [here](http://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader#Related)


> Q: Has the database been cleanly shutdown and restarted after ingestion of the triples, before the recent crash?

Not entirely sure. If this is important I can re-examine the logs or post them to paste bin if that helps.


> Q: What sort of operations (SQL/SPARQL) where you running when Virtuoso crashed?

It was this query:
```rq
select ?class count(?s) as ?instancecount 
{ 
  ?s a ?class 
} 
group by ?class
```

**Comment by HughWilliams** [comment]
I downloaded the same VOS binary you used:

```pre
ubuntu@ip-172-30-0-77:~/vos/virtuoso-opensource/database$ ../bin/virtuoso-t -?
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.6.3233-pthreads as of Jun 22 2021 (111d17e5b)
Compiled for Linux (x86_64-generic_glibc25-linux-gnu)
Copyright (C) 1998-2021 OpenLink Software
```

— and loaded an arbitrary dataset —
 
```pre
SQL> ld_dir ('.', 'hugh.ttl.gz', 'hugh');

Done. -- 1 msec.
SQL> rdf_loader_run();

Done. -- 3431 msec.
SQL> sparql select count(*) from <hugh> where {?s ?p ?o};
callret-0
INTEGER
_______________________________________________________________________________

477809

1 Rows. -- 59 msec.
SQL>
```

— and ran the query you provided, which does not crash my database —

```pre
SQL> sparql select ?class count(?s) as ?instancecount  {    ?s a ?class  }  group by ?class; 
class                                                                             instancecount
LONG VARCHAR                                                                      LONG VARCHAR
_______________________________________________________________________________

http://www.openlinksw.com/schemas/virtrdf#array-of-QuadMap                        3
http://www.openlinksw.com/schemas/virtrdf#QuadMapFormat                           130
http://www.openlinksw.com/schemas/virtrdf#QuadMap    
.
.
.
http://www.w3.org/1999/02/22-rdf-syntax-ns#Property                               23
http://www.openlinksw.com/schemas/virtrdf#array-of-QuadMapColumn                  8
http://localhost/awt#ER                                               33074

20 Rows. -- 3 msec.
SQL>
```

If you start your Virtuoso instance with `ulimit -c unlimited` to enable core file creation, is a `core` file created from the crash, such that a `gdb` stack trace can be obtained for analysis?

If you can provide the dataset you are loading (if not private), we can attempt a load ourselves to try and recreate.

Also, when you performed the bulk load of the data, did you perform a `checkpoint` to commit the data to the database as detailed in the documentation?  A crash would typically only lose the data if a `checkpoint` had not been run following a bulk load of the data.
