### ISSUE TITLE
Double/float typed-literals are truncated in SPARQL results

### ISSUE THREAD

**Issue by Tomas2D** [openlink/virtuoso-opensource#1006]
When I retrieve values from the SPARQL endpoint via simple select, the typed-literals with datatype `xsd:double` are truncated.

The same issue has been reported on [StackOverflow](https://stackoverflow.com/questions/37380338/double-values-are-truncated-rounded-in-virtuoso-srarql-results).

Tested with `application/sparql-results+json`.

**Comment by HughWilliams** [comment]
Do you have a test case for recreating or live link to see the truncation being encountered with  `application/sparql-results+json` results ?

**Comment by Tomas2D** [comment]
Sure, here is one for `application/sparql-results+json` [DBPedia (JSON)](https://dbpedia.org/sparql?query=prefix%20geo%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23%3E%20%0D%0A%0D%0Aselect%20%3Flat%20%3Flong%20where%20%7B%0D%0A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLiberty_Tower_%28Manhattan%29%3E%20%20geo%3Along%20%3Flong%3B%20geo%3Alat%20%3Flat%20.%0D%0A%7D&format=application/sparql-results+json). 
With other formats like `text/html`, `application/csv` etc. values are still truncated / rounded.

When using `text/turtle`, no truncating occurs. 
Example [DBPedia - Turtle](https://dbpedia.org/sparql?query=prefix%20geo%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23%3E%20%0D%0A%0D%0Aselect%20%3Flat%20%3Flong%20where%20%7B%0D%0A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLiberty_Tower_%28Manhattan%29%3E%20%20geo%3Along%20%3Flong%3B%20geo%3Alat%20%3Flat%20.%0D%0A%7D&format=text/turtle).

It looks like that same problem applies to `xsd:float`.

**Comment by Tomas2D** [comment]
Just to mention that data are stored in the database correctly, only interpretation of results are wrong formats mentioned earlier.

**Comment by pkleef** [comment]
Development is looking into this issue

**Comment by Tomas2D** [comment]
Possible connection with #114

**Comment by Tomas2D** [comment]
When typed literal `xsd:decimal` is being used, no truncation happens. 
Tested on commit https://github.com/openlink/virtuoso-opensource/commit/15478c9b56ee8252d3e44d6578cfd06d3784b845

**Comment by Tomas2D** [comment]
Also want to mention, that next possible workaround would be to do something like this
```
BIND(xsd:decimal(STR(bif:st_x(?geometry))) as ?x)
```

because client will receive correctly typed literal which can be then converter to corresponding data type in a concrete programming language.

**Comment by Tomas2D** [comment]
This issue has been resolved in version [7.2.7](https://github.com/openlink/virtuoso-opensource/releases/tag/v7.2.7).

Thanks!
