### ISSUE TITLE
Is there any way to insert data into Virtuoso in real time, preferably Java or HTTP ?

### ISSUE THREAD

**Issue by chenkuncloud** [openlink/virtuoso-opensource#1007]
Hi,

I have finished installing virtuoso-opensource v7.2.6.1 through docker , in Linux , and can visit http://localhost:8890/sparql .

I want to UPDATE data . I already know how :	
	1. ``` GRANT SPARQL_UPDATE TO "SPARQL" ``` . However, /sparql is generally for external services, and the SPARQL_UPDATE permission may not be secure  
	2. ``` command or Quad Store Upload ``` . This can import RDF File , but this is only batch, may not be suitable for single

I was wondering if there is another way to insert data into Virtuoso in real time , preferably Java or http

Best Regards

**Comment by jakubklimek** [comment]
`http://localhost:8890/sparql-auth`?

**Comment by TallTed** [comment]
There are several...  See [this page of gradually evolving documentation](http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFInsert) and/or [section 16.9 of the Virtuoso product manual](http://docs.openlinksw.com/virtuoso/#:~:text=16.9.%20RDF%20Insert%20Methods%20in%20Virtuoso).

Please let us know whether any of these options are sufficient, or if you need further guidance.

**Comment by chenkuncloud** [comment]
Hi @jakubklimek ,

Thank you very much for your reply !

How should I use http://localhost:8890/sparql-auth ？
I create an account testdb/testdb , visit http://localhost:8890/sparql-auth , then  Execute Query ``` INSERT { <http://test.cn/> <http://test.cn/> 'test' } ``` :
```
Virtuoso 42000 Error SR186:SECURITY: No permission to execute procedure DB.DBA.SPARQL_INSERT_DICT_CONTENT with user ID 107, group ID 107

SPARQL query:
define sql:big-data-const 0
#output-format:text/html
define sql:signal-void-variables 1
define input:default-graph-uri <http://localhost:8890/sparql>
INSERT { <http://test.cn/> <http://test.cn/> 'test' }
```
Here is my user configuration , I ticked off all the options I thought I had  :

![OVZIGIPD}9N)_ U~J`S9YJD](https://user-images.githubusercontent.com/40781280/157305397-992b74be-9f53-49be-a420-bd1760d7cdcf.png)

Best Regard

**Comment by chenkuncloud** [comment]
Hi @TallTed ,

Thank you very much for your reply !

I want to use   [16.9.2. SPARQL endpoint REST](http://docs.openlinksw.com/virtuoso/rdfinsertmethodshttppost/)  to insert a rdf triple：
```
curl -i -d "INSERT in GRAPH <http://localhost:8890/sparql> { <http://test.cn/> <http://test.cn/> 'test' }" -u "testdb:testdb" -H "Content-Type: application/sparql-query" http://localhost:8890/DAV/
```
but failed , it shows that ' insufficient user permissions ' :
```
[root@centos7 ~]# curl -i -d "INSERT in GRAPH <http://localhost:8890/sparql> { <http://test.cn/> <http://test.cn/> 'test' }" -u "testdb:testdb" -H "Content-Type: application/sparql-query" http://localhost:8890/DAV/
HTTP/1.1 403 Forbidden: insufficient user permissions
Server: Virtuoso/07.20.3233 (Linux) x86_64-generic_glibc25-linux-gnu  
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
Date: Tue, 08 Mar 2022 18:55:40 GMT
Accept-Ranges: bytes
Content-Length: 0
```
I follow the example but do not know what http://localhost:8890/DAV/ means . I just want to insert a triple into the graph . Did I send the wrong request ?

**Comment by chenkuncloud** [comment]
I can now add through ISQL , but I want to call it in real time from a Java program OR http-sparql-update. Any recommendations? 

Best Regards

**Comment by chenkuncloud** [comment]
Dear @jakubklimek @TallTed ,

My problem is solved !

I was so stupid ! After I read the document carefully, I found  [16.18.1. Virtuoso Jena Provider](http://docs.openlinksw.com/virtuoso/rdfnativestorageprovidersjena/) is suitable for me .

For the above questions, I also found the answer in [HTTP POST](http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFInsert#HTTP%20POST)

Thank you very much for your patience ! @jakubklimek @TallTed 

If someone wants to call Virtuoso in an application, they are also advised to read the documentation:
	[http://docs.openlinksw.com/](http://docs.openlinksw.com/)

Best Regards

**Comment by TallTed** [comment]
I'm glad to hear you were able to find a suitable solution in the docs.

Given your last comments, I think your initial question here (and possibly the question answered by the Jena Provider) was an example of an [XY Problem](https://xyproblem.info/).

Hopefully next time, you'll include a bigger picture description of what you're trying to do, as we may then be able to save you some time and layers by answering the bigger picture instead of whatever segment you're focusing on.

**Comment by chenkuncloud** [comment]
Hi ,
Thanks a lot for your advice . I'm very sorry for the delay .
I studied [XY Problem](https://xyproblem.info/) carefully, and try to give you some useful advice in the future if I get the chance .

Best Regards
