### ISSUE TITLE
Add custom namespace prefixes for SPARQL Query Editor

### ISSUE THREAD

**Issue by Tomas2D** [openlink/virtuoso-opensource#1009]
I was wondering about possibility to add custom namespace prefixes for SPARQL Query. 
This would shorter query and also improve common mistakes as forgetting to write a prefix.

**Comment by TallTed** [comment]
I think your wish is answered by the [Namespaces subtab of the Linked Data tab](http://docs.openlinksw.com/virtuoso/rdfadm/#rdfadmnamesp) of the Conductor.

Please let us know whether that's sufficient....

**Comment by Tomas2D** [comment]
I probably overlooked it, thanks.
