### ISSUE TITLE
Missing DB.DBA.SPARQL_INS_OR_DEL_OR_MODIFY_CTOR_FIN permission for DELETE

### ISSUE THREAD

**Issue by davidshumway** [openlink/virtuoso-opensource#1012]
Logged in as user: dba.

Running via docker using the instructions from here: (https://hub.docker.com/r/openlink/virtuoso-opensource-7/).

And following along with delete examples from here: (http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksSPARQL11Delete).

The delete command, running through the conductor SPARQL query tab:

```sparql
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns>
prefix ex: <http://www.example.org/> 
WITH <http://www.example.org/>
DELETE { ?b ?c ?d } 
WHERE { 
?b a ex:Title ;
      ex:hasFeature ?f ;
      ex:hasItem ?t .
}
```

Results in the following error:
```bash
Virtuoso 42000 Error SR186:SECURITY: No permission to execute procedure DB.DBA.SPARQL_INS_OR_DEL_OR_MODIFY_CTOR_FIN with user ID 107, group ID 107

SPARQL query:
define sql:big-data-const 0
#output-format:text/html
define input:default-graph-uri 
prefix rdf: 
prefix ex:  

WITH 
DELETE { ?b ?c ?d } 
WHERE { 
?b a ex:Title ;
      ex:hasFeature ?f ;
      ex:hasItem ?t .
}
```

Thus far I've tried modifying permissions in isql and through conductor for user dba without success.

**Comment by kidehen** [comment]
> ```sparql
> prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns>
> prefix ex: <http://www.example.org/> 
> WITH <http://www.example.org/>
> DELETE { ?b ?c ?d } 
> WHERE { 
> ?b a ex:Title ;
>       ex:hasFeature ?f ;
>       ex:hasItem ?t .
> }
> ```

Please run the following.

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns>
PREFIX ex: <http://www.example.org/> 
WITH <http://www.example.org/>
DELETE { ?b ?c ?d } 
WHERE { 
                ?b a ex:Title ;
                    ex:hasFeature ?f ;
                    ex:hasItem ?t ;
                    ?c ?d . 
             }
```

**Comment by davidshumway** [comment]
@kidehen That query makes more sense, thanks. But still not working. Now there's a new permissions error, though:

```sparql
Virtuoso 42000 Error SR186:SECURITY: No permission to execute procedure DB.DBA.SPARQL_DELETE_DICT_CONTENT with user ID 107, group ID 107
```

**Comment by davidshumway** [comment]
Also forgot to mention:
```
Version: 07.20.3233
Build: Jun 22 2021
```

**Comment by davidshumway** [comment]
Perhaps the user in my permissions query was the issue?

This didn't work:
```
grant execute on DB.DBA.SPARQL_DELETE_DICT_CONTENT to "dba";
```

While this appears to have worked:
```
grant execute on DB.DBA.SPARQL_DELETE_DICT_CONTENT to "dba";
```

**Comment by HughWilliams** [comment]
@davidshumway: Your `grant ...` command is the same in both cases or should the second case have been as below?

```
grant execute on DB.DBA.SPARQL_DELETE_DICT_CONTENT to "SPARQL";
```

I presume you were connecting to the `~/sparql-auth` SPARQL endpoint and logging in as "`dba`" which has privileges to perform update operations?

But when you execute your query and encounter the error, is the URL still `~/sparql-auth` or now the `~/sparql` endpoint, owned by the `SPARQL` user, which only has read/select (`SPARQL_SELECT`) rights and so could not execute the `DELETE` query being attempted, until you gave it execute rights on the `DB.DBA.SPARQL_DELETE_DICT_CONTENT` function?

This is **NOT** advised, as you are then starting to make the default _read only_ `~/sparql` SPARQL endpoint able to perform updates without authentication.

We have a fix for this issue in the current git [`develop/7`](https://github.com/openlink/virtuoso-opensource/tree/develop/7) branch, and are soon to make a new Virtuoso Open Source `stable/7` release including an updated docker image which will also include this fix ...
