### ISSUE TITLE
ASK query with JSON output - missing procedure

### ISSUE THREAD

**Issue by Tomas2D** [openlink/virtuoso-opensource#1016]
When running following query from ISQL

```
SPARQL define output:format "JSON"
ASK {}
```

the following error occurs 
```
SQLState: 42001

Message: SR185: Undefined procedure DB.DBA.RDF_FORMAT_BOOL_RESULT_AS_JSON.
```

I investigated the error inside source code and find out that the definition of `DB.DBA.RDF_FORMAT_BOOL_RESULT_AS_JSON` really does not exist, but it should.

Compiled from commit [79ce054](https://github.com/openlink/virtuoso-opensource/tree/79ce0548d7e9b2df43a60271cd6f0331780acfa7) on MacOS 12.2.1.

**Comment by Tomas2D** [comment]
I was able to fix that issue by myself, I have created the missing procedure by following patterns applied at `libsrc/Wi/sparql.sql`.

```sql
--!AWK PUBLIC
create procedure DB.DBA.RDF_FORMAT_BOOL_RESULT_AS_JSON_INIT (inout _env any)
{
  _env := 0;
}
;

--!AWK PUBLIC
create procedure DB.DBA.RDF_FORMAT_BOOL_RESULT_AS_JSON_ACC (inout _env any, in one any array)
{
  _env := 1;
}
;

--!AWK PUBLIC
create function DB.DBA.RDF_FORMAT_BOOL_RESULT_AS_JSON_FIN (inout _env any) returns long varchar
{
  declare ses any;
  ses := string_output ();
  http (
    concat (
      '{  "head": { "link": [] }, "boolean": ',
      case (isinteger (_env)) when 0 then 'false' else 'true' end,
      '}'), 
  ses);
  return ses;
}
;

create aggregate DB.DBA.RDF_FORMAT_BOOL_RESULT_AS_JSON (in one any array) returns long varchar
from DB.DBA.RDF_FORMAT_BOOL_RESULT_AS_JSON_INIT, DB.DBA.RDF_FORMAT_BOOL_RESULT_AS_JSON_ACC, DB.DBA.RDF_FORMAT_BOOL_RESULT_AS_JSON_FIN ;
```

Shall I create a pull request or dev team will take care of that? Thanks.

**Comment by TallTed** [comment]
@pkleef @openlink @IvanMikhailov @HughWilliams 

Please take a look at this suggested patch for lack of `DB.DBA.RDF_FORMAT_BOOL_RESULT_AS_JSON()`.

**Comment by Tomas2D** [comment]
Thanks!
