### ISSUE TITLE
Inserting triples based on sparql query

### ISSUE THREAD

**Issue by davidshumway** [openlink/virtuoso-opensource#1018]
How to add triples for a new relation based on the results of another query? For example, add a new triple showing the number of features within 25km of a selected feature. The goal is to essentially cache the results of a long-running distance query when there could be millions of features, thus reducing the lookup time for this type of count query to a single select statement.

Prefixes:
```sparql
prefix sosa: <http://www.w3.org/ns/sosa/> 
prefix geo: <http://www.opengis.net/ont/geosparql#> 
prefix geof: <http://www.opengis.net/def/function/geosparql/>
prefix ex: <http://www.example.org/> 
prefix units: <http://www.opengis.net/def/uom/OGC/1.0/>
```

Count triples within 25km of `ex:b16`:
```sparql
select ?bFoiA count(?bFoiB) as ?countFoi where {
  ?bFoiA a sosa:featureOfInterest ;
      geo:hasGeometry ?bGeomA .
  FILTER(?bFoiA = ex:b16) .  
  ?bGeomA geo:asWKT ?bWktA .
  {select ?bFoiB where { 
    ?bFoiB a sosa:featureOfInterest ;
      geo:hasGeometry ?bGeomB .
    ?bGeomB geo:asWKT ?bWktB .
  }}
  FILTER(?bFoiA != ?bFoiB) .
  FILTER(geof:distance(?bWktA, ?bWktB, units:meter) <= 25000) .
}
```

Resulting in:
?bFoiA | ?countFoi
-- | --
http://www.example.org/b16 | 317

Thus, the new triple given a relation `ex:count25km` might look like this:

```sparql
ex:16 ex:count25km "317"^^xsd:integer .
```

The relevant documentation appears to be for example here: (http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksSPARQL11Insert). But how to take an existing query's results and add them back as new triples?

Something like this perhaps?

```sparql
insert { ?a ex:count25km ?b }
where {
  select ?bFoiA as ?a count(?bFoiB) as ?b where {
  ?bFoiA a sosa:featureOfInterest ;
      geo:hasGeometry ?bGeomA .
  FILTER(?bFoiA = ex:b16) .  
  ?bGeomA geo:asWKT ?bWktA .
  {select ?bFoiB where { 
    ?bFoiB a sosa:featureOfInterest ;
      geo:hasGeometry ?bGeomB .
    ?bGeomB geo:asWKT ?bWktB .
  }}
  FILTER(?bFoiA != ?bFoiB) .
  FILTER(geof:distance(?bWktA, ?bWktB, units:meter) <= 25000) .
  }
}
```

**Comment by davidshumway** [comment]
Perhaps like this?
```sparql
insert { ?a ex:count25km ?b }
where {
  select ?bFoiA as ?a count(?bFoiB) as ?b where {
  ?bFoiA a sosa:featureOfInterest ;
      geo:hasGeometry ?bGeomA .
  FILTER(?bFoiA = ex:b16) .  
  ?bGeomA geo:asWKT ?bWktA .
  {select ?bFoiB where { 
    ?bFoiB a sosa:featureOfInterest ;
      geo:hasGeometry ?bGeomB .
    ?bGeomB geo:asWKT ?bWktB .
  }}
  FILTER(?bFoiA != ?bFoiB) .
  FILTER(geof:distance(?bWktA, ?bWktB, units:meter) &lt;= 25000) .
  }
}
```

**Comment by davidshumway** [comment]
Perhaps like this?
```sparql
insert { graph <http://www.example.org> {
  ?a ex:count25km ?b .
}}
where { graph <http://www.example.org> {
  select ?bFoiA as ?a count(?bFoiB) as ?b where {
  ?bFoiA a sosa:featureOfInterest ;
      geo:hasGeometry ?bGeomA .
  FILTER(?bFoiA = ex:b16) .  
  ?bGeomA geo:asWKT ?bWktA .
  {select ?bFoiB where { 
    ?bFoiB a sosa:featureOfInterest ;
      geo:hasGeometry ?bGeomB .
    ?bGeomB geo:asWKT ?bWktB .
  }}
  FILTER(?bFoiA != ?bFoiB) .
  FILTER(geof:distance(?bWktA, ?bWktB, units:meter) <= 25000) .
  }
}}
```

**Comment by TallTed** [comment]
I'm guessing that you found a solution, since you closed this issue.  Would you mind sharing what you learned, to help others along the way?

One important note -- there's no `SELECT` in [SPARQL 1.1 Update `INSERT` syntax](https://www.w3.org/TR/2013/REC-sparql11-update-20130321/#insert).  It's either --
```sparql
INSERT { GRAPH <graph> { triple_patterns } }
WHERE { GRAPH <graph> { triple_patterns } }
```
-- or --
```sparql
INSERT { GRAPH <graph> { triple_patterns } }
USING <graph>
WHERE { triple_patterns } 
```

That may have played a part in your discovered solution...?

**Comment by davidshumway** [comment]
Interesting. I used the SELECT query included in my last reply.

**Comment by TallTed** [comment]
I think this works out because `SELECT` subquery within the `WHERE { GRAPH <graph> { SELECT ... } }` clause gets executed sooner (because SPARQL processing works from inside-out), so by the time the top-level subquery is processed, there's no SELECT within it, only the results obtained from the deeper subqueries.  Thanks for your clarification!
