### ISSUE TITLE
Re-import / overwrite triples using rdf_loader_run()

### ISSUE THREAD

**Issue by davidshumway** [openlink/virtuoso-opensource#1019]
Is there a simple way to re-import triples previously loaded using rdf_loader_run() without going through deleting the existing database or triples?

**Comment by davidshumway** [comment]
It appears when using the bulk upload with the same file, triples are added twice. Is there perhaps a parameter to set to disable this such that the original triple is overwritten?

**Comment by imitko** [comment]
@davidshumway

If you have unnamed  BNodes in the RDF dump, you will get every time new triple, solution is to use named IRIs or named BNodes, or use `sparql clear <graph-uri>` if you want to re-load the graph. 

HTH

**Comment by davidshumway** [comment]
With a big graph, it seems to be faster to start over from scratch. Using `docker` that's not a challenge. But similarly, what about deleting virtuoso.db?

Not sure about BNodes. Here's a sample of triples from the `.n3` file:

```notation3
ex:obs12 a sosa:Observation ;
sosa:result_time "2012-11-18T03:00:00"^^xsd:dateTime ;
sosa:observedProperty "water"^^xsd:string ;
sosa:hasResult [
  qudt-1-1:numericValue "4"^^xsd:float ;
  qudt-1-1:unit "m"^^xsd:string ] .
```

**Comment by imitko** [comment]
The following contains unlabeled  [blank node](https://www.w3.org/TR/turtle/#BNodes) :
```
> sosa:hasResult **[
>   qudt-1-1:numericValue "4"^^xsd:float ;
>   qudt-1-1:unit "m"^^xsd:string ] .**
> 
```

It could be written like that:

``` 
sosa:hasResult _: resultN .
_: resultN qudt-1-1:numericValue "4"^^xsd:float ;  qudt-1-1:unit "m"^^xsd:string .
```

**Comment by davidshumway** [comment]
Makes sense. Thanks!
