### ISSUE TITLE
Segmentation fault when accessing long geometry object using SPARQL

### ISSUE THREAD

**Issue by sylxjtu** [openlink/virtuoso-opensource#1030]
Hi, I encountered a problem when trying to access a long geometry object. First, I imported the object using this nt file https://gist.github.com/sylxjtu/291d47f49cbbfb09c7f42c70df99ac4c. Then I use the query:

```sparql
SELECT ?o WHERE {<http://w3id.org/ckgg/1.0/instances/location/10017810> <http://w3id.org/ckgg/1.0/ontology/properties/P24> ?o.}
```

The query returns ?o=0, which is not true.

Then I tried

```sparql
SELECT str(?o) WHERE {<http://w3id.org/ckgg/1.0/instances/location/10017810> <http://w3id.org/ckgg/1.0/ontology/properties/P24> ?o.}
```

This query caused the virtuoso-t program to segfault.

The version of the virtuoso is 7.2.5.1 (commit 17c4ba1). OS is Ubuntu 18.04.

Thank you for looking into this problem!

**Comment by pkleef** [comment]
I did a quick test against the current `develop/7` branch and both queries return the correct result.

The version you are currently running appears to be from 2018, so i would recommend building a new binary from the `develop/7` branch. 

We are currently working on a new stable release which will come out in the next few weeks.

**Comment by sylxjtu** [comment]
Thank you, I'll try to update my version.

**Comment by sylxjtu** [comment]
I tried to update my version, although the above sparqls still returns invalid results, doing a re-import seems to fix the problem. Thank you!
