### ISSUE TITLE
Distinct keyword in sub-select breaks limit/offset behavior

### ISSUE THREAD

**Issue by wouterbeek** [openlink/virtuoso-opensource#1035]
### Observed

Using the `distinct` keyword in sub-selects silently breaks `limit`/`offset` functionality.

For example, the following query returns 150 results, while 50 results are expected:

```sparql
select * {
  {
    select distinct * {
      ?s ?p ?o.
    }
  }
}
offset 100
limit 50
```

In another example, the following query does not apply `limit`/`offset` at all:

```sparql
select distinct * {
  {
    select distinct * {
      ?s ?p ?o.
    }
  }
}
offset 100
limit 50
```

### Expected

Correct behavior of `distinct` when applied to a sub-select, also when `limit` and/or `offset` are used.

### Steps to reproduce

1. Evaluate the above shared SPARQL queries in Virtuoso.
2. Observed the described incorrect behavior.
3. Optional: remove the `distinct` keywords from the queries, and observe that the queries now exhibit correct behavior.

**Comment by TallTed** [comment]
Interesting.  Quick tests confirm your observation on Open Source Edition 07.20.3233 (0431ba360) built Feb 25 2022 and Enterprise Edition 08.03.3322 (e6bb7a8b23) built Apr 19 2022.  Development will have a look.

**Comment by HughWilliams** [comment]
closed this as [completed](https://github.com/openlink/virtuoso-opensource/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/openlink/virtuoso-opensource/commit/7f162e64a182d0d6e744d85df391b0a73053c009

**Comment by TallTed** [comment]
@wouterbeek —

You can test the fix now through [a beta Docker image](https://github.com/openlink/virtuoso-opensource/issues/1199#issuecomment-1836380746), or by building yourself from the `develop/7` branch.

Of course, it will also be in our next official release, coming in the near future.
