### ISSUE TITLE
Plans for docker images distribution (develop branch, arm64) ?

### ISSUE THREAD

**Issue by serasset** [openlink/virtuoso-opensource#1036]
With the now almost complete arm M1 set of computers from apple (including hi-end server-like machines), will openlink try to distribute the official docker images as multi-architecture images with both amd64 and arm64 architectures ?

Alternatively, could the Dockerfile of virtuoso-opensource-7 image be distributed so that we may rebuilld an equivalent image for arm64 architecture. This will also allows people to deploy docker services using the latest develop/7 codebase (current docker image includes amd64, Version 7.2.6.3233-pthreads only).

**Comment by pkleef** [comment]
OpenLink will publish official multi-architecture docker images for VOS with the upcoming new stable release.

If you are interested to testing a BETA docker and giving me some feedback, try:
```
$ docker pull pkleef/virtuoso-opensource-7:latest 

$ docker run -i -t pkleef/virtuoso-opensource-7:latest version

This Docker image is using the following version of Virtuoso:

Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.7-dev.3233-pthreads as of May  2 2022 (f077264d1)
Compiled for Linux (aarch64-ubuntu_bionic-linux-gnu)
Copyright (C) 1998-2022 OpenLink Software
```

**Comment by serasset** [comment]
Thanks, I'll give it a look. No plan to opensource the Dockerfile I assume?

**Comment by KonradHoeffner** [comment]
Since May 18, you can now use the official release openlink/virtuoso-opensource-7:7.2.7, which supports both amd64 and arm64.

**Comment by pkleef** [comment]
The latest version of  [`openlink/virtuoso-closedsource-8`](https://hub.docker.com/r/openlink/virtuoso-closedsource-8) and [`openlink/virtuoso-opensource-7`](https://hub.docker.com/r/openlink/virtuoso-opensource-7) docker images are multi-arch and support both **amd64** as well as **arm64**.

**Comment by claudiu-cristea** [comment]
@serasset 

> Thanks, I'll give it a look. No plan to opensource the Dockerfile I assume?

I've opened #1095 for this
