### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [openlink/virtuoso-opensource#1038]
Would you like to add the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” to [your build specification](https://github.com/openlink/virtuoso-opensource/blob/7d66d58e38145aafc2f0a47b996d6cfbf3a5728e/configure.ac#L531 "Update candidate")?

**Comment by pkleef** [comment]
Please note that this particular file is licensed as `GPLv3 or newer` which is not compatible with the `GPLv2 only` license we use for VOS at this time.

Note that VOS has always been portable to a large number of systems that use some version of pthreads, including AIX, IRIX,  HP/UX, Solaris, Linux, and Mac OS X. We also support native Windows threads and mutexes.

If you have a particular porting problem on a machine, please contact me and i can help you.

**Comment by elfring** [comment]
Functions are called also according to the POSIX thread programming interface.
Thus I would expect that some checks should be performed for a safe build system.

How do you think about to distinguish the licence versions any further for your build specification?

**Comment by elfring** [comment]
Would you like to reuse functionality from the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” (without bundling it for your software build system)?
