### ISSUE TITLE
Starting over from scratch using same docker container

### ISSUE THREAD

**Issue by davidshumway** [openlink/virtuoso-opensource#1042]
It takes at least 10 minutes to delete the triples using `sparql clear graph <...>;`. But deleting `virtuoso.db` and `virtuoso.trx`, then restarting the container, is instantaneous. Is there any issues with going with the latter method?

**Comment by HughWilliams** [comment]
How many triples are you deleting (`CLEAR`ing) in the graph? If a large number, are you using the `log_enable(3)` option as detailed in the Virtuoso document on [deleting large graphs](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksGuideDeleteLargeGraphs) from a Virtuoso data store?

If the single graph being cleared is the only graph or other resource in the Virtuoso database, then you could delete the `virtuoso.db` and `virtuoso.trx`, then restart the docker(?) container, but this is not a recommended practice...

**Comment by KonradHoeffner** [comment]
I think the most appropriate way using docker is to delete the volume instead.
For example, in my docker compose setups, I always do `docker compose down -v` to delete all volumes and the docker compose setup is configured as to add all the data on startup if it isn't already there.
However if for some reason you insist on the clear graph method, can you try if it is faster using Virtuoso 7.2.7? According to the [release notes](https://community.openlinksw.com/t/virtuoso-open-source-7-2-7-release-notes/3143) they added optimizations for clearing graphs and deleting triples.

**Comment by davidshumway** [comment]
> How many triples are you deleting (`CLEAR`ing) in the graph? If a large number, are you using the `log_enable(3)` option as detailed in the Virtuoso document on [deleting large graphs](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksGuideDeleteLargeGraphs) from a Virtuoso data store?

Perhaps 50 million triples. 
 
> If the single graph being cleared is the only graph or other resource in the Virtuoso database, then you could delete the `virtuoso.db` and `virtuoso.trx`, then restart the docker(?) container, but this is not a recommended practice...

Good to know. Thanks!
