### ISSUE TITLE
Transaction aborted because it's log after image size went above the 50000000 bytes limit

### ISSUE THREAD

**Issue by davidshumway** [openlink/virtuoso-opensource#1043]
Occurs during SPARQL inserting triples via CURL endpoint.

```sparql
insert { GRAPH <http://www.example.org> {
  ?url a sosa:Observation ;
    ... # ~10 triples per entity
}} where { GRAPH <http://www.example.org> {
  select ...
    where {
    ?obs a sosa:Observation ;
      ... # ~ 5 triples per entity
    bind(year(?date) as ?y) .
    bind(month(?date) as ?m) .
    bind(day(?date) as ?d) .
    bind(URI(concat(?obs,'-',?y,'-',?m,'-',?d,'-combined')) as ?url) .
    bind(xsd:dateTime(concat(?y,'-',?m,'-',?d)) as ?combinedDate) .
  } group by ?y ?m ?d ?combinedDate ?url
  having ( ... )
}}
```

Error:
> Virtuoso 40005 Error SR325: Transaction aborted because it's log after image size went above the 50000000 bytes limit

Explain:
```BASH
REPORT
VARCHAR
_______________________________________________________________________________

  { 
    Precode:
      0:   { FOR UPDATE
          Precode:
            0: DB.DBA.RDF_MAKE_OBJ_OF_TYPEDSQLVAL$27 := Call DB.DBA.RDF_MAKE_OBJ_OF_TYPEDSQLVAL (<c BC>,  IRI_ID"...string" , <DB_NULL>)
            7: vector$29 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...type" ,  3 ,  IRI_ID"...Observation" )
            12: vector$31 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...hasFeatureOfInterest" ,  1 ,  9 )
            17: vector$33 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...resultTime" ,  1 ,  8 )
            22: vector$35 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...hasSimpleResult" ,  1 ,  7 )
            27: DB.DBA.RDF_MAKE_LONG_OF_TYPEDSQLVAL_STRINGS$37 := Call DB.DBA.RDF_MAKE_LONG_OF_TYPEDSQLVAL_STRINGS (<c average-daily>, <tag 217 c http://www.w3.org/2001/XMLSchema#string>, <DB_NULL>)
            34: vector$39 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...observedProperty" ,  3 , DB.DBA.RDF_MAKE_LONG_OF_TYPEDSQLVAL_STRINGS$37)
            39: vector$41 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...countObservations" ,  1 ,  6 )
            44: vector$43 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...minFIB" ,  1 ,  5 )
            49: vector$45 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...maxFIB" ,  1 ,  4 )
            54: DB.DBA.RDF_MAKE_LONG_OF_TYPEDSQLVAL_STRINGS$47 := Call DB.DBA.RDF_MAKE_LONG_OF_TYPEDSQLVAL_STRINGS (<c BC-combined>, <tag 217 c http://www.w3.org/2001/XMLSchema#string>, <DB_NULL>)
            61: vector$49 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...obsType" ,  3 , DB.DBA.RDF_MAKE_LONG_OF_TYPEDSQLVAL_STRINGS$47)
            66: vector$51 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...year" ,  1 ,  3 )
            71: vector$53 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...month" ,  1 ,  2 )
            76: vector$55 := Call vector ( 1 ,  0 ,  3 ,  IRI_ID"...day" ,  1 ,  1 )
            81: vector$57 := Call vector (vector$29, vector$31, vector$33, vector$35, vector$39, vector$41, vector$43, vector$45, vector$49, vector$51, vector$53, vector$55)
            86: vector$59 := Call vector ()
            91: BReturn 0
          fork {
              Subquery 61 
                { 
                  fork {
                      RDF_QUAD   5.2e+05 rows(t36.S$75, t36.O$74)
                       inlined  P =  IRI_ID"...hasFeatureOfInterest"  G =  IRI_ID"...www.example.org" 
                      RDF_QUAD unq      0.11 rows (t40.S$79, t40.O$78)
                       inlined  P =  IRI_ID"...obsType"  ,  S = k_t36.S$225 ,  O = k_DB.DBA.RDF_MAKE_OBJ_OF_TYPEDSQLVAL$229 ,  G =  IRI_ID"...www.example.org" 
                      RDF_QUAD unq       0.8 rows (t35.S$82)
                       inlined  P =  IRI_ID"...type"  ,  S = t40.S$79 ,  O =  IRI_ID"...Observation"  ,  G =  IRI_ID"...www.example.org" 
                      RDF_QUAD         1 rows(t39.S$85)
                       inlined  P =  IRI_ID"...observedProperty"  ,  S = k_t35.S$244 G =  IRI_ID"...www.example.org" 
                      RDF_QUAD         1 rows(t38.S$89, t38.O$88)
                       inlined  P =  IRI_ID"...hasSimpleResult"  ,  S = k_t35.S$254 G =  IRI_ID"...www.example.org" 
                      Precode:
                        0: temp$91 := artm t38.O$88 +  0 
                        4: BReturn 0
                      RDF_QUAD         1 rows(t37.O$94)
                       inlined  P =  IRI_ID"...resultTime"  ,  S = k_t35.S$265 G =  IRI_ID"...www.example.org" 
                      
                      After code:
                      0: isnotnull$96 := Call isnotnull (temp$91)
                      5: isnotnull$98 := Call isnotnull (t38.O$88)
                      10: __ro2sq$100 := Call __ro2sq (t36.O$74)
                      15: rdf_year_impl$102 := Call rdf_year_impl (t37.O$94)
                      20: rdf_month_impl$104 := Call rdf_month_impl (t37.O$94)
                      25: rdf_day_impl$106 := Call rdf_day_impl (t37.O$94)
                      30: rdf_concat_impl$108 := Call rdf_concat_impl (rdf_year_impl$102, <c ->, rdf_month_impl$104, <c ->, rdf_day_impl$106)
                      35: _cvt$110 := Call _cvt (<tag 193 flag 0>, rdf_concat_impl$108)
                      40: rdf_concat_impl$112 := Call rdf_concat_impl (__ro2sq$100, <c ->, rdf_year_impl$102, <c ->, rdf_month_impl$104, <c ->, rdf_day_impl$106, <c -combined>)
                      45: __i2idn$114 := Call __i2idn (rdf_concat_impl$112)
                      50: __rdf_sqlval_of_obj$116 := Call __rdf_sqlval_of_obj (__i2idn$114)
                      55: BReturn 0
                      Sort (t36.O$74, rdf_year_impl$102, rdf_month_impl$104, rdf_day_impl$106, t40.O$78, _cvt$110, __rdf_sqlval_of_obj$116, __i2idn$114) -> (t38.O$88, t38.O$88, isnotnull$98, isnotnull$96, temp$91)
                      
                    }
                  group by read node  
                  (t36.O$74, rdf_year_impl$102, rdf_month_impl$104, rdf_day_impl$106, t40.O$78, _cvt$110, __rdf_sqlval_of_obj$116, __i2idn$114, aggregate$120, aggregate$122, aggregate$124, aggregate$126, aggregate$128)
                  
                  After code:
                  0: temp$164 := artm aggregate$128 / aggregate$126
                  4: AvgFIB$62 :=  := artm temp$164
                  8: CountObs$63 :=  := artm aggregate$124
                  12: MinFIB$64 :=  := artm aggregate$122
                  16: MaxFIB$65 :=  := artm aggregate$120
                  20: y$66 :=  := artm rdf_year_impl$102
                  24: m$67 :=  := artm rdf_month_impl$104
                  28: d$68 :=  := artm rdf_day_impl$106
                  32: combinedDate$69 :=  := artm _cvt$110
                  36: beachObsFoi$70 :=  := artm t36.O$74
                  40: url$71 :=  := artm __i2idn$114
                  44: BReturn 0
                  Subquery Select(AvgFIB$62, CountObs$63, MinFIB$64, MaxFIB$65, y$66, m$67, d$68, combinedDate$69, beachObsFoi$70, url$71)
                }
              
              After code:
              0: DB.DBA.RDF_LONG_OF_SQLVAL$173 := Call DB.DBA.RDF_LONG_OF_SQLVAL (MaxFIB$65)
              7: DB.DBA.RDF_LONG_OF_SQLVAL$175 := Call DB.DBA.RDF_LONG_OF_SQLVAL (MinFIB$64)
              14: __ro2lo$177 := Call __ro2lo (beachObsFoi$70)
              19: vector$179 := Call vector (url$71, d$68, m$67, y$66, DB.DBA.RDF_LONG_OF_SQLVAL$173, DB.DBA.RDF_LONG_OF_SQLVAL$175, CountObs$63, AvgFIB$62, combinedDate$69, __ro2lo$177)
              24: if (user_aggr_notfirst$184  =  1 ) then 39 else 28 unkn 28
              28: user_aggr_notfirst$184  :=  := artm  1 
              32: user_aggr_ret$186 := Call DB.DBA.SPARQL_CONSTRUCT_INIT (user_aggr_env$185 )
              39: user_aggr_ret$186 := Call DB.DBA.SPARQL_CONSTRUCT_ACC (user_aggr_env$185 , vector$57, vector$179, vector$59,  0 )
              46: BReturn 0
            }
          skip node  1  <none> set_ctr$181
          
          After code:
          0: DB.DBA.SPARQL_CONSTRUCT_FIN$187 := Call DB.DBA.SPARQL_CONSTRUCT_FIN (user_aggr_env$185 )
          7: callret-0$189 := Call DB.DBA.SPARQL_INSERT_DICT_CONTENT (<tag 182 flag 1 c http://www.example.org>, DB.DBA.SPARQL_CONSTRUCT_FIN$187,  0 , <DB_NULL>,  0 )
          14: BReturn 0
          Subquery Select(callret-0$189)
        }
      
      8: vector$315  := Call vector (scalar$316 )
      13: DB.DBA.SPARUL_RUN$314  := Call DB.DBA.SPARUL_RUN (vector$315 )
      20:  <none>  := Call set_row_count (DB.DBA.SPARUL_RUN$314 )
      25: BReturn 0
    END Node
  }

103 Rows. -- 76 msec.
```

Any ideas?

**Comment by davidshumway** [comment]
http://docs.openlinksw.com/virtuoso/virtuosotipsandtrickssparulupdatestrl/

**Comment by davidshumway** [comment]
The insert is taking place through the SPARQL CURL endpoint. Is it somehow possible to set ` log_enable (2);` via the CURL request? I tried using `isql` and setting it there but it doesn't appear to affect the operation taking place over the CURL endpoint.

**Comment by davidshumway** [comment]
Setting `TransactionAfterImageLimit = 5000000000` (default * 100) in `virtuoso.ini` resolved the issue.

**Comment by TallTed** [comment]
You can also use the [`DEFINE sql:log-enable N`](http://docs.openlinksw.com/virtuoso/rdfsparqlimplementatioptragmas/#rdfsparqlimplementatioptragmasccg) pragma (one of several [related pragmas](http://docs.openlinksw.com/virtuoso/rdfsparqlimplementatioptragmas/)) at the start of a SPARUL command, as `DEFINE sql:log-enable 2`.

**Comment by davidshumway** [comment]
I was curious about how to do that. Good to know, thanks!

**Comment by davidshumway** [comment]
> You can also use the [`DEFINE sql:log-enable N`](http://docs.openlinksw.com/virtuoso/rdfsparqlimplementatioptragmas/#rdfsparqlimplementatioptragmasccg) pragma (one of several [related pragmas](http://docs.openlinksw.com/virtuoso/rdfsparqlimplementatioptragmas/)) at the start of a SPARUL command, as `DEFINE sql:log-enable 2`.

Is it necessary to call `checkpoint` or add another [DEFINE sql:log-enable N](http://docs.openlinksw.com/virtuoso/rdfsparqlimplementatioptragmas/#rdfsparqlimplementatioptragmasccg) pragma at the end of the SPARUL command?

**Comment by pkleef** [comment]
> > You can also use the [`DEFINE sql:log-enable N`](http://docs.openlinksw.com/virtuoso/rdfsparqlimplementatioptragmas/#rdfsparqlimplementatioptragmasccg) pragma (one of several [related pragmas](http://docs.openlinksw.com/virtuoso/rdfsparqlimplementatioptragmas/)) at the start of a SPARUL command, as `DEFINE sql:log-enable 2`.
> 
> Is it necessary to call `checkpoint` or add another [DEFINE sql:log-enable N](http://docs.openlinksw.com/virtuoso/rdfsparqlimplementatioptragmas/#rdfsparqlimplementatioptragmasccg) pragma at the end of the SPARUL command?

Adding a `DEFINE sql:log-enable N` to the start of your SPARUL statement only changes the transaction mode for that particular statement. Virtuoso will automatically reset it back to the mode your database was in before the statement was executed.

By default, SPARUL commands run in manual-commit mode (`sql:log-enable 1`), which means that Virtuoso needs to have enough memory available in its internal `after-image` ledger to record every change to the database your `insert` statement makes. After your statement has completed successfully, the `/sparql/` endpoint executes a `COMMIT WORK` statement, to finalize the data and write the definitive modifications to the db. 

Depending on the number of triples involved with the `INSERT`, `DELETE`, or `CLEAR GRAPH`, you may need to increase the size of the `after-image` by setting the `TransactionAfterImageLimit` in the `virtuoso.ini`.

I recommend using `DEFINE sql:log-enable 3`, as this is the auto-commit mode, which means that every modification the `SPARUL` statement makes is immediately committed, and therefore does not require a huge `TransactionAfterImageLimit` setting. 

This will allow you to run `SPARUL` statements such as `CLEAR GRAPH` on arbitrarily large graphs without the risk of running out of transaction memory.

Using modes `1` and `3` do not require you to execute a  manual `CHECKPOINT` statement after the `SPARUL` statement, as in both cases, the engine writes records into the `virtuoso.trx` file to record the changes.

`DEFINE sql:log-enabled 2` should only be used in special circumstances, as it bypasses the [ACID](https://en.wikipedia.org/wiki/ACID) ([atomicity](https://en.wikipedia.org/wiki/Atomicity_(database_systems)), [consistency](https://en.wikipedia.org/wiki/Consistency_(database_systems)), [isolation](https://en.wikipedia.org/wiki/Isolation_(database_systems)), [durability](https://en.wikipedia.org/wiki/Durability_(database_systems))) protections that Virtuoso normally provides. 

Mode `2` is basically an auto-commit mode without recording the modifications in the `virtuoso.trx` file. This means that if the Virtuoso engine is killed during the operation (or before manual execution of a `CHECKPOINT`), it will not be able to play back the changes into the database, and basically leaves the database in the state it was before the SPARUL statement was executed.

To make sure that all mode `2` changes are permanently recorded in the database, you need to execute a `CHECKPOINT` statement after the SPARUL statement.
