### ISSUE TITLE
Slow parallel loading

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#1050]
I did a fresh install of develop branch.  Implemented the fix from https://github.com/openlink/virtuoso-opensource/issues/742#issuecomment-528871495
as this was needed last year to address a crashing problem I was having.
I'm now reloading about 15 billion triples (which had been loaded on this same server before the clean wipe) and using 22 loaders (64-core server).
The loading process which usually flies at this point, is crawling with only 62,000 triples loaded after 15 minutes.  I'm not sure what is going on here.  Has the loading process changed at all?

**Comment by HughWilliams** [comment]
You indicate having performed a "clean wipe" for this database load, what does that mean? I am assuming you mean the previous database was deleted/discarded and a new empty database started with the new Virtuoso `stable/7` binary for this new load of the data?

There was one change made in the new Virtuoso `stable/7` release to upgrade the [`RDF_IRI` table to use 64-bit prefix IDs](https://community.openlinksw.com/t/upgrading-from-vos-7-2-x-to-vos-7-2-7/3133#upgrading-from-vos-72x-to-vos-727) which does affect bulk loading of databases created by a previous binary (so, using the old 32-bit prefix IDs) as indicated, hence my question.

What does the output of the "`status();`" command report during the current data load?

**Comment by ebremer** [comment]
In short, it's a new installation.  I moved the old installation to another drive, did a `git pull` (from `develop/7`), recompiled, and only used the same `virtuoso.ini` file from the old installation as it had all of the memory settings for this server.  I'm restarting the server and the load process again.  I will check the `status();` then.

**Comment by ebremer** [comment]
I decided to delete the original `develop/7` repo I had and do a fresh `pull` (as oppose to `git pull` on old repo).  I still applied #742, but now, it's loading fast again with 20 loaders atm.  I will close this issue out once the load finishes, but so far, so good.

**Comment by ebremer** [comment]
Load worked fine.
