### ISSUE TITLE
Data disappeared after restarting the computer

### ISSUE THREAD

**Issue by 2213500360** [openlink/virtuoso-opensource#1054]
I spent several hours loading my data, and after shutting down and restarting the computer I found that all the data had disappeared.
Then after several tests, I found that after loading the data with the `rdf_loader_run()`, I have to run `shutdown()` once and the data will not disappear after reboot.
I'm afraid the data loaded later will disappear again, because it takes a lot of time to load data every time. 
What is the reason for this and how to solve it? thank you

**Comment by imitko** [comment]
@2213500360,

You should either use `log_mode` `1` or `3` or do a `checkpoint` after loading. Please see [`log_mode`](http://docs.openlinksw.com/virtuoso/fn_log_enable/) notes.

HTH
