### ISSUE TITLE
Turtle loader syntax error with numbers

### ISSUE THREAD

**Issue by KonradHoeffner** [openlink/virtuoso-opensource#1059]
I use `ld_dir_all()` together with `rdf_loader_run()` to successfully load several files.
However when I include a file with a number, it gives me an error.
For example, the turtle file containing the single line `<x> <y> 1.` generates the error:

`PL LOG:  File data/shacl.ttl error 37000 [Vectorized Turtle loader] TURTLE RDF loader, line 2: SP029: TURTLE RDF loader, line 2: syntax error`

According to the [W3C Turtle Spec](https://www.w3.org/TR/turtle/), this numerical shorthand is valid turtle syntax, but it seems like the Virtuoso Turtle loader cannot handle this.

rapper confirms that the syntax is correct:

```
$ rapper -i turtle -c ontology/shacl.ttl                                                                                              openlink-virtuoso
rapper: Parsing URI file:///home/konrad/projekte/snik/docker/ontology/shacl.ttl with parser turtle
rapper: Parsing returned 1 triple
```

**Comment by pkleef** [comment]
I will check the turtle parser and let you know

**Comment by KonradHoeffner** [comment]
@pkleef: The error still occurs with the tested versions 7.2.7 and the newest 7.2.9 both from DockerHub.

This triggers the error:

```
@prefix : <http://example.com/>.

:x :y 1.
#:x :y "1"^^xsd:integer.
```

but this one doesn't:

```
@prefix : <http://example.com/>.

#:x :y 1.
:x :y "1"^^xsd:integer.
```

**Comment by pkleef** [comment]
A fix for this has been pushed to develop/7
