### ISSUE TITLE
How to get username (and possibly other information) for the current session

### ISSUE THREAD

**Issue by Suichoku** [openlink/virtuoso-opensource#1066]
I am having a problem using virtuoso with react webapp, I want to somehow fetch information about authentication using JavaScript. For example if I authenticate using "_.../sparql-auth/login.vsp?action=login_" or "_.../sparql_" (which uses the default authentication.vsp for the authentication) as "_dba_", session is valid (I get the "_sid_" cookie). But I haven't found any way of requesting authentication details for the connection.

There seems to be method [_VAL.DBA.get_authentication_details_for_connection_](http://docs.openlinksw.com/valdocs/group__val__auth__module__main.html#ga745878ab820820c45f26d15217824cfa) which would give me the information needed, but it is for .vsp files only? Can I somehow access this or similar information with JavaScript?

There is also function [_username()_](http://docs.openlinksw.com/virtuoso/fn_username/) which I can run using iSQL to get this username for the connection. I tried using this function with SPARQL query but couldn't get it working.

I need this information for showing who is currently logged in and for creating new WebDav directories for the logged in user.

_Thank you for the help._

**Comment by TallTed** [comment]
You didn't provide the SPARQL query in which you tried to use the [`username()` function](http://docs.openlinksw.com/virtuoso/fn_username/), but perhaps the examples below will provide enough clues for you to make progress...

```sparql
SELECT
  ( bif:username() AS ?username )
WHERE
  {  ?s  ?p  ?o  }
LIMIT 1
```

```sparql
SELECT ?username
WHERE
  {  BIND ( bif:username() AS ?username )
     ?s  ?p  ?o  
   }
LIMIT 1
```

**Comment by Suichoku** [comment]
Thank you so much. This seems to have fixed my problem.
