### ISSUE TITLE
Question: Does Virtuoso-OpenSource support GraphQL query?

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [openlink/virtuoso-opensource#1072]
at wikipedia it seems to say there is support but looking at the readme doesnt seems to gives any hint about its existence

**Comment by kidehen** [comment]
Native support is on its way. It will be part of the next release which is due out any minute now.

**Comment by RESDXChgfore9hing** [comment]
awesome,i will try out virtuoso then.and will close this issue

**Comment by arnikz** [comment]
@kidehen: Do I understand it correctly that the next Virtuoso OSE release will include GraphQL-based data access? Thank you.

**Comment by arnikz** [comment]
Yes 🎉 It's there: https://github.com/openlink/virtuoso-opensource/tree/v7.2.8

**Comment by pkleef** [comment]
You can read more about this new feature in the following articles on our community forum:
  *  [GraphQL Introduction](https://community.openlinksw.com/t/introducing-native-graphql-support-in-virtuoso/3378) 
  *  [GraphQL Usage Guide](https://community.openlinksw.com/t/usage-guide-virtuoso-graphql-views-creation-management/3381)
