### ISSUE TITLE
Question: How to actually close the `virtuoso-t` server? Is there a basic guide?

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [openlink/virtuoso-opensource#1073]
The readme only teaches up until how to get it running and authenticate at the local server web view.

I tried
```
D:\2ndProgramFiles\Virtuoso OpenSource 7.2\bin>virtuoso-t +instance stop
unable to open the service control manager (5)

D:\2ndProgramFiles\Virtuoso OpenSource 7.2\bin>virtuoso-t +instance 8890 stop
unable to open the service control manager (5)

D:\2ndProgramFiles\Virtuoso OpenSource 7.2\bin>virtuoso-t +instance stop
unable to open the service control manager (5)

D:\2ndProgramFiles\Virtuoso OpenSource 7.2\bin>virtuoso-t stop -f

                Fri Sep 02 2022
15:49:55 There is no configuration file D:\2ndProgramFiles\Virtuoso OpenSource 7.2\bin\virtuoso.ini

D:\2ndProgramFiles\Virtuoso OpenSource 7.2\bin>virtuoso-t stop +manual
unable to open the service control manager (5)

D:\2ndProgramFiles\Virtuoso OpenSource 7.2\bin>virtuoso-t +manual stop +manual
unable to open the service control manager (5)

D:\2ndProgramFiles\Virtuoso OpenSource 7.2\bin>virtuoso-t +manual stop
unable to open the service control manager (5)
```

As you can see, I have no clue how to close it. How do we restart?

Is there a way to manage where the path to db with cli?

Can we disable the local host webview? For example, if we are in production, we just need to do sql query from cli/api and gets the result ASAP.

**Comment by HughWilliams** [comment]
On Windows, Virtuoso is installed as a [Windows Service](https://en.wikipedia.org/wiki/Windows_service) and can be stopped and started with the Windows [Service Control Manager](https://en.wikipedia.org/wiki/Service_Control_Manager) UI, or via an **Administrator** command line session with the commands detailed in the [Virtuoso Windows Services](https://vos.openlinksw.com/owiki/wiki/VOS/VOSUsageWindows#Optional%20--%20Create%20and%20Manage%20Virtuoso%20Windows%20Services) documentation.

Not sure what you mean by, "is there a way to manage where the path to db with cli?" The location of the DB file is set in the `virtuoso.ini` config file. I don't see why you would want to change it once set initially, but if you do, it has to be done via the config file, and the database would have to be stopped and restarted in the new location.

If you want to disable HTTP access, and have the Virtuoso instance only accessible via SQL, then simply comment out the `[HTTP Server]` section of the `virtuoso.ini` config file and restart Virtuoso; it will start only on the SQL port, which can be checked by viewing the `virtuoso.log` file, which shows what service, ports, etc., the server is started with:
```
10:32:13 Roll forward started
10:32:13 Roll forward complete
10:32:13 Default charset UTF-8 not defined. Reverting to ISO-8859-1
10:32:14 Checkpoint started
10:32:14 Checkpoint finished, log reused
10:32:14 Server online at 1111 (pid 24488)
```

**Comment by RESDXChgfore9hing** [comment]
awesome thanks,it actually works as expected. huge thanks,will continue explore.
