### ISSUE TITLE
Question:guide for CRUD operation with virtuoso

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [openlink/virtuoso-opensource#1080]
I saw that graphql support is implemented I wanted to start create database with some data and try utilizing it.
However I am unsure how to do it.

**Comment by HughWilliams** [comment]
Have you read the Virtuoso GraphQL [Introduction](https://community.openlinksw.com/t/introducing-native-graphql-support-in-virtuoso/3378) and [Usage](https://community.openlinksw.com/t/usage-guide-virtuoso-graphql-views-creation-management/3381) guides as starting points ?

**Comment by kidehen** [comment]
Have you read any of [the Virtuoso GraphQL guide ](https://community.openlinksw.com/t/usage-guide-virtuoso-graphql-views-creation-management/3381)about how GraphQL Mappings and view creation?

We've also published [a repo](https://github.com/OpenLinkSoftware/SPASQL-Utility-Showcase-Queries/tree/master/graphql) comprising various sample mappings used in the public demos associated with the following live endpoints:

* [URIBurner](https://linkeddata.uriburner.com/graphql)
* [Virtuoso Live Demo Server](https://demo.openlinksw.com/graphql)

For live interaction with the endpoints above, using a GraphiQL based UI you can use any of the following:
* [URIBurner](https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Flinkeddata.uriburner.com%2Fgraphql)
* [Live Demo Server](https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Fdemo.openlinksw.com%2Fgraphql)

Finally, you can also view [a collection of Twitter Posts](https://twitter.com/search?q=GraphQL%20%40kidehen&src=typed_query&f=live) comprising live demos (that use the endpoints above).

**Comment by RESDXChgfore9hing** [comment]
awesome will try it out and see if I can reproduce the results then maybe implementing my own database for my personal stuff,
