### ISSUE TITLE
Grouping over `FLOAT`s results in strange behaviour

### ISSUE THREAD

**Issue by thomasdegroot18** [openlink/virtuoso-opensource#1081]
### Problem

The handling of `FLOAT`s in SPARQL queries is not working as expected, when a `FLOAT` is used as a `GROUP` identifier. When a `FLOAT` is used as identifier, it can no longer be expected that the value is correct. Instead, there is a large possibility that the value in that is used is no longer correct.

### What was expected

That the value of the `FLOAT` should be correct according to the precision of the `FLOAT` as stored in linked data. 

### How to reproduce

The following query showcases the strange behaviour of `FLOAT`s. The SPARQL query retrieves several subjects where there is only a single `FLOAT` for a predicate, making sure that we never retrieve two different `FLOAT`s. We use this method to retrieve the `FLOAT`s because doing an equality check for `FLOAT`s often does not result in correct comparisons. The SPARQL query then retrieves the `FLOAT` twice, sums one of the `FLOAT`s grouped by the `?subject` and `?float` where we expect both `FLOAT`s to be equal within a small margin of error. 

```sparql
SELECT ?subject ?float1 (sum(?float2) as ?float2Sum)
FROM <http://dbpedia.org>
WHERE {
  {
    select ?subject where {
      ?subject <http://www.w3.org/2003/01/geo/wgs84_pos#lat> []
    } group by ?subject HAVING(count(*) = 1)
  } 
  ?subject <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?float1 ,
      ?float2 .
}
GROUP BY ?subject ?float1
LIMIT 2
```
The static link to the [SPARQL query](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=SELECT+%3Fsubject+%3Ffloat1+%28sum%28%3Ffloat2%29+as+%3Ffloat2Sum%29%0D%0AFROM+%3Chttp%3A%2F%2Fdbpedia.org%3E%0D%0AWHERE+%7B%0D%0A++%7B%0D%0A++++select+%3Fsubject+where+%7B%0D%0A++++++%3Fsubject+%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23lat%3E+%5B%5D%0D%0A++++%7D+group+by+%3Fsubject+HAVING%28count%28*%29+%3D+1%29%0D%0A++%7D+%0D%0A++%3Fsubject+%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23lat%3E+%3Ffloat1+%2C%0D%0A++++++%3Ffloat2+.%0D%0A%7D%0D%0AGROUP+BY+%3Fsubject+%3Ffloat1%0D%0ALIMIT+2&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on) results in the following table. What is noticeable is that the value for `?float1` is not the same as the value for `?float2Sum` even though the values should result to the same value as the query is only summing over a single value that is exactly the same as the non-summed value. 

subject | float1 | float2Sum
-- | -- | --
<http://dbpedia.org/resource/Museum_of_Geology,_Tashkent> | 42.149 | 41.3004
<http://dbpedia.org/resource/Botijas> | 13.0096 | 18.2243

What is noticeable is that the value for summation(`?float2Sum`) is the correct value, whereas the identifier of the group `float1` is not the correct value of the identifier. 

For reproduction purposes, I've used the open SPARQL endpoint of DBpedia, <https://dbpedia.org/sparql> `Virtuoso version 08.03.3326 (b5ffaadfc9) on Linux (x86_64-generic-linux-glibc25) Single Server Edition on 1 Dec 2022`.

**Comment by pkleef** [comment]
Thanks for reporting. I will discuss this within development and get back to you.
