### ISSUE TITLE
Error 37000: [Virtuoso Driver][Virtuoso Server]SQ113: Non-view column set in view update (trying to change dav password)

### ISSUE THREAD

**Issue by JonnyJD** [openlink/virtuoso-opensource#1083]
I am trying to automatically configure a virtuoso instance.
As part of that I want to change the default passwords.
As mentioned here:
https://docs.openlinksw.com/virtuoso/defpasschange/
I should change the dav user password either via UI (not an option if you want to automate) or use:
```
update WS.WS.SYS_DAV_USER set U_PASSWORD='<new password>'
where U_NAME='<username>'
```

However, actually running that gives me:
```
isql-vt "EXEC=update WS.WS.SYS_DAV_USER set U_PASSWORD='...' where U_NAME='dav'"
...
Error 37000: [Virtuoso Driver][Virtuoso Server]SQ113: Non-view column set in view update
```
(Version 07.20.3229-pthreads for Linux as of Oct 20 2021; = 7.2.5.1+dfsg1-0.2 in Ubuntu 22.04; running Docker)

Now there is `user_set_password()`
https://docs.openlinksw.com/virtuoso/fn_user_set_password/
and this seems to work fine.
Apart from not being documented as the option to use.

There is also
https://docs.openlinksw.com/virtuoso/fn_user_change_password/
which is recommended here:
https://docs.openlinksw.com/virtuoso/usermodel/#vumsecobjects
Which is not the best option, when you want to set passwords as DB admin (dba).

Anyways,
so why does that error message appear,
or rather why does it appear for the recommended way to change the default passwords?

Somewhat unrelated, there is an official docker image, which also changes passwords:
https://hub.docker.com/r/openlink/virtuoso-opensource-7/
but I could not find the source code of that one.

**Comment by pkleef** [comment]
The reason you received the error `SQ113: Non-view column set in view update` is that the `WS.WS.SYS_DAV_RES` is a `VIEW` which can be used for updating, however it requires the use of the correct field name which is `U_PWD` and not `U_PASSWORD` as used on the page you found. I can only assume the field name got modified at some point and the documentation was not fixed.

I will have the documentation modified to reflect the correct field name. 

However i recommend you use the `user_set_password('username', 'new password')` method which is the preferred way for the 'dba' user to change the password of any account in the database.

The `user_change_password` function is specifically made for UI so a  non-dba users can change their own password which will naturally only work when the user knows their original password.

Our docker image uses a Docker entry-point startup script, which you can copy to your local filesystem by using the following commands:

```shell
$ docker pull openlink/virtuoso-opensource-7
$ docker create --name vos7test openlink/virtuoso-opensource-7
$ docker cp vos7test:/opt/virtuoso-opensource/bin/virtuoso-entrypoint.sh /tmp
$ docker rm vos7test
```

If you examine the `/tmp/virtuoso-entrypoint.sh` script on your computer, you will see this actually uses a command line method to set the initial password for the `dba` and `dav` accounts based on a randomly generated password.

If you are building/deploying your own VOS docker image, please let me know as i maybe able to help you to add our version into your deployment.

**Comment by JonnyJD** [comment]
Thanks, we actually have it mostly running by now (using `user_set_password()`) and use Ansible.
I didn't want to run the official container just to poke at it, but now I fetched the script and will have a look if we can use something from it.

The important thing is that the next person does not need to fiddle around so much, so updating the doc is good :-)
