### ISSUE TITLE
How to delete a large data graph

### ISSUE THREAD

**Issue by JoinJoker** [openlink/virtuoso-opensource#1085]
Hi!
  I would like to ask how to delete a graph when the server memory is small (40G) when the triplet data of the graph is 1 billion or more?
  I tried to use 
      log_ enabel(2,1); SPARQL CLEAR GRAPH <xxxxx>;
  The discovery program will crash until the log fails to delete data

  Virtuoso version 07.20.3230 on Linux (x86_64-generic_glibc25-linux-gnu), Single Server Edition

![image](https://user-images.githubusercontent.com/101538403/207526590-587a492c-be03-4bd1-b3ea-a36ea2ace5c4.png)

**Comment by hroptatyr** [comment]
Hi,
don't know if officially endorsed but

    DELETE FROM rdf_quad WHERE g = iri_to_id('GRAPH_URL_WITHOUT_ANGLES');

works like a charm.

**Comment by pkleef** [comment]
@JoinJoker 

The official syntax to clear any sized graph without exceeding transaction space or other memory related issues is:

```
SPARQL DEFINE sql:log-enable 3 CLEAR GRAPH <http://example.com/graph/>;
```

This will run the statement in autocommit mode without disabling [ACID mode](https://en.wikipedia.org/wiki/ACID).

**Comment by pkleef** [comment]
@hroptatyr 

Your syntax will only work with small graphs and will quickly run out of transaction space when the graph gets larger than a couple of million triples. I would recommend using [the method I described above](https://github.com/openlink/virtuoso-opensource/issues/1085#issuecomment-1351302108).

**Comment by TallTed** [comment]
@pkleef -- We have [a FAQ answer](https://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksGuideDeleteLargeGraphs) on this which differs slightly from [your advice above](https://github.com/openlink/virtuoso-opensource/issues/1085#issuecomment-1351302108). Which should be edited to match the other?

**Comment by pkleef** [comment]
## Using manual `log_enable`
```
log_enable(3,1);   -- set the session to auto commit
SPARQL CLEAR GRAPH  <http://example.com/graph/>; 
log_enable(1,1);   -- set the session back to manual commit (missing from the FAQ)
```

This snippet will set the session to auto commit mode, clear the graph, then finally set the session back to manual commit mode. Note that if the session was in auto commit mode before these statements were executed, it ends back in manual commit mode. This may have unexpected side effects on the rest of an application or script.

Additionally, if the last line is not executed (as was the case in the original example), then the rest of the session (or connection) will remain in auto commit mode. This can cause issues if the application then wants to perform further `SPARQL` or `SQL` commands and to control those transaction using `COMMIT WORK` or `ROLLBACK WORK` within the same session.

In this example, Virtuoso will both delete the triples from the graph, and delete the references to these triples from the FreeText and GEO indexes.

## Using `sql:log-enable`
```
SPARQL DEFINE sql:log-enable 3 CLEAR GRAPH <http://example.com/graph/>;
```
— actually translates internally to —
```
declare old_mode integer;

old_mode := log_enable(3, 1);   -- set the session to auto commit
SPARQL CLEAR GRAPH <http://example.com/graph/>;
log_enable (old_mode, 1);       -- reset the session back to its original mode
```

This means that whatever commit mode Virtuoso was in before the statement was executed, after the statement, Virtuoso will be back in the original commit mode it was before for this statement. 

In this example Virtuoso will also delete both the triples from the graph, as well as delete references to these triples from the FreeText and GEO indexes.


## Using `RDF_QUAD` table

To be able to delete any sized graph directly from the underlying `RDF_QUAD` table itself, you could use:
```
log_enable(3, 1);   -- set the session to auto commit
DELETE FROM rdf_quad WHERE g = iri_to_id ('http://mygraph.org');
log_enable (1, 1);  -- set the session back to manual commit
```

This has the same problem as the first example, by altering the commit mode the session was originally in.

However, this command only deletes the raw triples from the quad store, without deleting the references to these triples from  the FreeText and GEO indexes. This can cause performance issues when these indexes become cluttered with references to non-existing triples.

**Comment by JoinJoker** [comment]
@pkleef 

Thank you for your answer. Can I understand your method as enabling the transaction settings of virtuoso and automatically submitting it so that I can perform large data mapping operations on virtuoso? If so, I will try
