### ISSUE TITLE
Serving different named graphs over specific endpoints not working

### ISSUE THREAD

**Issue by maribelacosta** [openlink/virtuoso-opensource#1086]
Hi! 

I am trying to create several SPARQL endpoints listening on different ports to serve different named graphs. I have already loaded the named graphs, created the endpoints, and updated the `DB.DBA.SYS_SPARQL_HOST` to associate the `HOST` with the `GRAPH` URI.  This can be seen in the results of the query over the `SYS_SPARQL_HOST` table. 

```
Query result:
--
SH_HOSTVARCHAR | SH_GRAPH_URIVARCHAR
localhost:8895 | http://ex.org/swdf
localhost:8896 | http://ex.org/yago
No. of rows in result: 2
```

Now, the first endpoint (port `8895` in my example) is correctly serving only the associated named graph. However, the second endpoint (port `8896`) is serving all the graphs that I have loaded in my instance. I have also tried adding the information about the default graph with `SH_DEFINES`, but no success. 

I am using `Virtuoso version 07.20.3234 on Mac OS 11 (Apple Silicon) (aarch64-apple-darwin20.6.0) Single Server Edition`. This used to work in Virtuoso 6.   

Thanks!
Maribel

**Comment by HughWilliams** [comment]
we are looking into this ...

**Comment by maribelacosta** [comment]
Thank you! 

I just have a minor correction. The following version also presents the same issue:  `Virtuoso version 06.01.3127 on Linux (x86_64-pc-linux-gnu), Single Server Edition` .

**Comment by pkleef** [comment]
This issue has been fixed by https://github.com/openlink/virtuoso-opensource/commit/3fd81b4379b3906e1c526670cd0bde0a29aa0a57 on the develop/7 branch
