### ISSUE TITLE
Some namespaces were not abbreviated by jena's sparql query, but it's already added in virtuoso

### ISSUE THREAD

**Issue by chenkuncloud** [openlink/virtuoso-opensource#1090]
I've set up some namespaces in virtuoso and see them on the page `http://localhost:8890/sparql?nsdecl`. But when I used jena to do sparql queries in virtuoso, some namespaces were not abbreviated:
- `@prefix sio:     <http://semanticscience.org/resource/SIO_> .`
- `@prefix cheminf:    <http://semanticscience.org/resource/CHEMINF_> .`
- `@prefix snomedct:     <http://purl.bioontology.org/ontology/SNOMEDCT/> .`

Is this a BUG or am I doing something wrong?

## Information for reference

Virtuoso version 07.20.3235 (64e6ecd39) on Win64 (x86_64-generic-win-64) Single Server Edition

Data:
```text
@prefix rdf:        <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sio:     <http://semanticscience.org/resource/SIO_> .
@prefix cheminf:    <http://semanticscience.org/resource/CHEMINF_> .
@prefix snomedct:     <http://purl.bioontology.org/ontology/SNOMEDCT/> .
@prefix example:    <http://example.org/resource/> .

example:7732-18-5 rdf:type snomedct:101782006 .
example:7732-18-5 sio:SIO_000008 example:Descriptor_water_boiling_point_15039 .
example:Descriptor_water_boiling_point_15039 rdf:type sio:CHEMINF_000257 .
```

Jena code & SPARQL:
```java
RDFConnection conn = RDFConnectionRemote.service("http://localhost:8890/sparql").build();
Model model = conn.queryConstruct("CONSTRUCT { ?s ?p ?o . } WHERE { ?s ?p ?o . FILTER ( ?s = <http://example.org/resource/7732-18-5> ) }");

// SPARQL Result
model.write(System.out, "ttl");

// model.listNameSpaces
Iterator iterator = model.listNameSpaces();
while (iterator.hasNext()) {
    System.out.println(iterator.next().toString());
}
```

SPARQL Result:
```text
@prefix example: <http://example.org/resource/> .
@prefix ns1:     <http://semanticscience.org/resource/> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

example:7732-18-5  rdf:type  <http://purl.bioontology.org/ontology/SNOMEDCT/101782006> ;
        ns1:SIO_SIO_000008  example:Descriptor_water_boiling_point_15039 .
```

(Jena)model.listNameSpaces:
```text
http://www.w3.org/1999/02/22-rdf-syntax-ns#
http://purl.bioontology.org/ontology/SNOMEDCT/101782006
http://semanticscience.org/resource/
```

Virtuoso's Namespaces page:
![QL9R2DYQPJC{KH4)QE54~4](https://user-images.githubusercontent.com/40781280/210711719-73837ea2-a27b-4e16-a876-3b5485897767.png)

Best regards

**Comment by hroptatyr** [comment]
Not a bug, it's mandated by turtle (https://www.w3.org/TR/turtle/#sec-grammar). A prefixed name must begin with `PN_CHARS_BASE` after the colon.

**Comment by chenkuncloud** [comment]
> Not a bug, it's mandated by turtle (https://www.w3.org/TR/turtle/#sec-grammar). A prefixed name must begin with `PN_CHARS_BASE` after the colon.

Thanks, I didn't notice it before.

**Comment by TallTed** [comment]
@chenkun19960427 —

(As also noted on StackOverflow...)

I should also have noticed before — your prefixes don't do what you think, given the data as presented here. In your data block, the last object is `sio:CHEMINF_000257` which would expand to `http://semanticscience.org/resource/SIO_CHEMINF_000257` given your declaration of `@prefix sio: <http://semanticscience.org/resource/SIO_> .`.  Similar issues are seen with your `@prefix cheminf: <http://semanticscience.org/resource/CHEMINF_> .` and `sio:SIO_000008`.

**Comment by chenkuncloud** [comment]
Hi, @TallTed 
Thanks for reminding, it's my fault.

I deleted the extra `SIO_` and get `Jena's SPARQL` Result(Still can't be abbreviated):
```
@prefix example: <http://example.org/resource/> .
@prefix ns1:     <http://semanticscience.org/resource/> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

example:7732-18-5  rdf:type  <http://purl.bioontology.org/ontology/SNOMEDCT/101782006> ;
        ns1:SIO_000008  example:Descriptor_water_boiling_point_15039 .
```

But After I changed `snomedct:101782006` to `snomedct:TEST101782006`, I get `Jena's SPARQL` Result(Can be abbreviated):
```
@prefix example:  <http://example.org/resource/> .
@prefix ns2:      <http://semanticscience.org/resource/> .
@prefix rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix snomedct: <http://purl.bioontology.org/ontology/SNOMEDCT/> .

example:7732-18-5  rdf:type  snomedct:TEST101782006 ;
        ns2:SIO_000008  example:Descriptor_water_boiling_point_15039 .
```

It should be the reason of `PN_CHARS_BASE`.
