### ISSUE TITLE
Open source code for virtuoso-opensource-7 docker image?

### ISSUE THREAD

**Issue by claudiu-cristea** [openlink/virtuoso-opensource#1095]
Any chance to opensource the code for https://hub.docker.com/r/openlink/virtuoso-opensource-7? Or maybe it's already but I can't find it anywhere

**Comment by HughWilliams** [comment]
The docker image is created from code in our internal build environment for open source and commercial builds and thus not published.

What is your need for the code used to build the docker image ?

**Comment by claudiu-cristea** [comment]
@HughWilliams, In one of the projects for European Commission, we're currently using https://github.com/tenforce/docker-virtuoso:

* We want to migrate to official image https://hub.docker.com/r/openlink/virtuoso-opensource-7. But not knowing how the image is built is a blocker
* We might want to extend the Dockerfile or understand what scripts are running
* Also it's a matter of openness. We want to know what we're installing in production and in our CI/CD
* While VOS is opensource software, I see no reason why the VOS image should not publish its source code

**Comment by fungiboletus** [comment]
I was wondering about the license. Because Virtuoso opensource is released under the GPLv2 license, wouldn't the Dockerfile be available under this license ?

Anyway, I created a pull/merge request with a Dockerfile I use. It's very minimal but it could be a simple start, with a multi-stage build.

**Comment by claudiu-cristea** [comment]
> Anyway, I created a pull/merge request with a Dockerfile I use. It's very minimal but it could be a simple start, with a multi-stage build.

I don't think this will be ever merged because, my understanding is that the image is generated by an internal code. Maybe they still can export the used Dockerfile + entrypoint scripts in directory or a different repository.

**Comment by claudiu-cristea** [comment]
Closing as duplicate of #1166
