### ISSUE TITLE
Security report

### ISSUE THREAD

**Issue by MPParsley** [openlink/virtuoso-opensource#1096]
Is there a way we can responsibly disclose a security report?

cc @HughWilliams

**Comment by pkleef** [comment]
Yes, you can send email to vos.security@openlinksw.com

**Comment by MPParsley** [comment]
Thank you very much @pkleef, I sent you the report.

**Comment by pkleef** [comment]
Thank you for that report. I will discuss this matter within development and will notify you as soon as we have a fix available.

**Comment by MPParsley** [comment]
FYI, GitHub offers a feature "Private vulnerability reporting" (beta).

> Allow your community to privately report potential security vulnerabilities to maintainers and repository owners. [Learn more about private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability).

See https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability
