### ISSUE TITLE
How to make connection to virtuoso server in C/C++ ?

### ISSUE THREAD

**Issue by Adarsh999bh** [openlink/virtuoso-opensource#1099]
I have installed OpenLink Virtuoso server in my Linux system by following the readme file ( build from source and install "make" ). 

I have also installed iODBC in my system and followed [Virtuoso ODBC RDF Extensions for SPASQL](https://docs.openlinksw.com/virtuoso/odbcimplementationext/) to try running sample connection to the server but I keep getting this error `STMT: ODBC_Connect  | [iODBC][Driver Manager]Data source name not found and no default driver specified. Driver could not be loaded, SQLSTATE=IM002`

It would be really helpful if anyone could help me out with this issue.

Thanks,
Adarsh

**Comment by HughWilliams** [comment]
What is the ODBC client application being used, based on the reference to `ODBC_connect` I assume you are using the [iodbctest](http://wikis.openlinksw.com/UdaWikiWeb/TestingUnixODBCDSNs) sample program ? 

What is the ODBC connect string being passed to make the ODBC connection to the Virtuoso instance ?

What is the `odbc.ini` file in use by the iODBC Driver Manager for locating ODBC DSNs for making connections to database and do you have a DSN for the Virtuoso instanced being connected to, as the error implies the DSN and ODBC driver have not been found ?

Have you reviewed the Virtuoso [ODBC Setup](https://vos.openlinksw.com/owiki/wiki/VOS/VOSODBCSetup)  and [making a test connect on Linux](http://wikis.openlinksw.com:8892/VirtuosoWikiWeb/UnixODBCtoVirt) documentation ?

**Comment by Adarsh999bh** [comment]
@HughWilliams Thanks for responding .! I did a mistake, I had actually not created/configured ODBC.ini file.! That is the reason why I was getting the error .! After i configured ODBC.ini file it's working fine.
Again thanks.!
