### ISSUE TITLE
Feature request: Java 1.7 compatibility for JDBC component

### ISSUE THREAD

**Issue by creffett** [openlink/virtuoso-opensource#11]
Autoconf will currently fail if Java 1.7 is installed, and if that check is overridden the compile still fails at one point during javac. I will post the exact compile error when I am back at my developer box.

**Comment by creffett** [comment]
Ah, here we go: 
virtuoso/jdbc4/VirtuosoDataSource.java:9: error: VirtuosoDataSource is not abstract and does not override abstract method getParentLogger() in CommonDataSource
public class VirtuosoDataSource implements DataSource, Referenceable, Serializable {

And a number of others like that, all of the format "error: (Class) is not abstract and does not override abstract method (Method) in (Class)". From the looks of things, Oracle added a few methods to the JDBC classes in the Java 7 bump, and now since those methods are not defined in the virtuoso extensions to said classes, javac is unhappy.

**Comment by openlink** [comment]
i will have someone in the virtdev team take a look at the JDBC changes and make a patch for this.

**Comment by openlink** [comment]
We have committed a patch that adds  initial JDK1.7 support to the develop/6 branch. 

This will be part of the upcoming 6.1.7 release.
