### ISSUE TITLE
bulk loading RDF gives uninformative error

### ISSUE THREAD

**Issue by mkarikom** [openlink/virtuoso-opensource#1100]
I'm just following the [tutorial on bulk loading RDF](https://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader), starting with the `ld_dir` command to generate my import table:
```
ld_dir ('/usr/share/proj/', 'PathwayCommons12.intact_complex.BIOPAX.owl', 'www.pathwaycommons.org');
```
Sanity check (it's definitely an RDF file):
```
root@20ff189f90b7:/usr/share/proj# head PathwayCommons12.intact_complex.BIOPAX.owl
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
 xmlns:owl="http://www.w3.org/2002/07/owl#"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
 xmlns:bp="http://www.biopax.org/release/biopax-level3.owl#"
 xml:base="http://pathwaycommons.org/pc12/">
<owl:Ontology rdf:about="">
 <owl:imports rdf:resource="http://www.biopax.org/release/biopax-level3.owl#" />
</owl:Ontology>
root@20ff189f90b7:/usr/share/proj#
```

Despite this, after running the `ld_dir()` command above I get an uninformative error: [please see imgur screenshot](https://imgur.com/a/wTQtm2L).

**Comment by HughWilliams** [comment]
In what way is `The statement execution did not return a result set.` response seen as an `uninformative error`?

You have run a SQL procedure that does not return results, which completed successfully without an error and reported such.

Have you actually read the complete [tutorial on bulk loading RDF](https://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader) documentation to understand the bulk load process? Note that this is for loading large datasets across multiple/many files, and the `ld_dir()` function simply adds the indicated file(s) to the `DB.DBA.load_list` table, which you should check as indicated in the documentation; then run one or more `rdf_load_run()` procedures to bulk load the dataset file(s) data into the database; then check the `DB.DBA.load_list` table again, to ensure all files were loaded without error...

**Comment by mkarikom** [comment]
Ok thanks, [this worked](https://community.openlinksw.com/t/how-to-bulk-load-data-into-a-virtuoso-docker-instance/3248#the-10-bulkloadsql-script-9)

**Comment by TallTed** [comment]
@mkarikom — May we consider this issue closed?

**Comment by mkarikom** [comment]
yes thanks!
