### ISSUE TITLE
Graph Store Protocol implementation non-compliant?

### ISSUE THREAD

**Issue by namedgraph** [openlink/virtuoso-opensource#1113]
Looking at Virtuoso's [examples](https://vos.openlinksw.com/owiki/wiki/VOS/VirtGraphProtocolCURLExamples), it appears that it uses `graph-uri` query parameter for graph identification. The W3C spec [defines `graph` as the parameter instead](https://www.w3.org/TR/sparql11-http-rdf-update/#indirect-graph-identification).
Can you please add support for `graph`?

**Comment by TallTed** [comment]
As replied in [the Twitter thread](https://twitter.com/namedgraph/status/1633432513531052032), this [will be addressed](https://twitter.com/kidehen/status/1633531621746827264).

**Comment by pkleef** [comment]
Virtuoso  supports both the  W3C SPARQL 1.1 Graph Crud `graph` parameter as well as the older `graph-uri` parameter since patch 27b126fe798878a5b28f63d97c2fd5173499e0f0 which was committed in 2013.

I will discuss with the documentation team to have the example fixed.
