### ISSUE TITLE
Compilation issue in DkAlloc.c RockyLinux 8 gcc 8.5.0

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#1116]
```
Dkalloc.c: In function ‘dk_memory_finalize’:
Dkalloc.c:996:3: error: implicit declaration of function ‘dk_box_finalize’; did you mean ‘dk_box_initialize’? [-Werror=implicit-function-declaration]
   dk_box_finalize ();
   ^~~~~~~~~~~~~~~
   dk_box_initialize
```

Which seems to be newly marked as an error? In any case https://github.com/openlink/virtuoso-opensource/blob/fa5825a6e9d6b987d2257f6816b1708bf74249a7/libsrc/Dk/Dkalloc.c#L661 and https://github.com/openlink/virtuoso-opensource/blob/fa5825a6e9d6b987d2257f6816b1708bf74249a7/libsrc/Dk/Dkalloc.c#L994 are the same and that seems quite odd to me.

Could it be that a "forward declaration" needs to be added like at https://github.com/openlink/virtuoso-opensource/blob/fa5825a6e9d6b987d2257f6816b1708bf74249a7/libsrc/Dk/Dkernel.h#L1028? (Not sure this is the right terminology)

**Comment by JervenBolleman** [comment]
Last line of the compile does mention *cc1: some warnings being treated as errors*

**Comment by JervenBolleman** [comment]
To note this is with `--with-debug  --with-malloc-debug` configure options

**Comment by pkleef** [comment]
We are working on a fix.

**Comment by pkleef** [comment]
Fix https://github.com/openlink/virtuoso-opensource/commit/7d0f3bbe7eee1ed907ffdffaed69ff2b22129dd1  has been committed to the develop/7 branch.

**Comment by JervenBolleman** [comment]
Thank you for the quick fix!
