### ISSUE TITLE
SR477 when using ORDER BY

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#113]
On DBpedia instance <a href="http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=SELECT+%3Fa+%3Fv0%0D%0AWHERE+%7B%0D%0A%3Fa+a+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FSettlement%3E+%3B%0D%0A%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23geometry%3E+%3Fv0+.%0D%0A%7D+ORDER+BY+%3Fa+%0D%0A&format=text%2Fhtml&timeout=30000&debug=on
">query</a>
`SELECT ?a ?v0
WHERE {
?a a <http://dbpedia.org/ontology/Settlement> ;
<http://www.w3.org/2003/01/geo/wgs84_pos#geometry> ?v0 .
} ORDER BY ?a` 

produces

Virtuoso 22026 Error SR477: Error serializing the value into an ANY column

SPARQL query:
define sql:big-data-const 0 
# output-format:text/html

define sql:signal-void-variables 1 define input:default-graph-uri http://dbpedia.org SELECT ?a ?v0
WHERE {
?a a http://dbpedia.org/ontology/Settlement ;
http://www.w3.org/2003/01/geo/wgs84_pos#geometry ?v0 .
} ORDER BY ?a

It is caused by the ORDER BY clause.

**Comment by HughWilliams** [comment]
Thanks for reporting this, we are looking into it ....

**Comment by HughWilliams** [comment]
The issue appears to have gone away following a restart of the server, can you confirm it is now working for you ?

**Comment by jakubklimek** [comment]
Yes, seems to be working now.
