### ISSUE TITLE
RDF Management via REST 

### ISSUE THREAD

**Issue by eltonfss** [openlink/virtuoso-opensource#1143]
Is there any way to create RDF repositories/databases/datasets/datastores via the REST API?

A similar feature is available in other triplestores, such as Jena Fuseki, AllegroGraph, BlazeGraph, GraphDB and RDFox.
This is somewhat similar to an SQL database in which all the triples can be stored in a default graph or in a named graph.
Thus, we can have multiple "databases" and isolate the RDF graph management within those.

**Comment by HughWilliams** [comment]
A [Virtuoso RDF4J  HTTP Repository](https://vos.openlinksw.com/owiki/wiki/VOS/VirtSesame2HttpRepository) can be created as detailed in the documentation link, assuming this is the type of RDF repository you are seeking ...

**Comment by eltonfss** [comment]
Thank you!
