### ISSUE TITLE
several issues in Faceted Browser `rdf_desc`

### ISSUE THREAD

**Issue by serasset** [openlink/virtuoso-opensource#1144]
There are several issues in Faceted Browser `rdf_desc` code (and UI)

### The `description.js` file included in faceted browser uses jQuery (since commit ccd2d6e )

```javascript
var $j = jQuery.noConflict();
```

but `description.vsp` dos not load any version of `jquery`.

### The `fct` `make_vad.sh` references assets from a non existing `dbpedia` folder

In `binsrc/fct/make_vad.sh`, line 184

```sh
  cp -Rf $HOME/binsrc/samples/dbpedia/vsp/statics vad/vsp/fct/rdfdesc
```

There is a `dbpedia` folder with the expected assets, but it is not in the `samples` subdir, but directly in `binsrc` directory. Also I do not know which of these assets are necessary (and if the expected assets are these ones or if another version of `dbpedia` VAD is supposed to lie there, but there is no submodule in the Virtuoso project to fetch this...).

Note that `dbpedia` includes a copy of `jquery` in its assets.

### the `>>>more>>>` action in long lists of values in `description.js` does not work

Despite commit b215443db73789f107fdf870474c96e9a7321c2d

After digging into this issue, the problem is due to the first error (jQuery not loaded) as the error stops the initialisation of the global environment (hence the global variables are not correctly initialised). So fixing the first error should also fix this one.

**Comment by HughWilliams** [comment]
We are looking into this ...
