### ISSUE TITLE
Behaviour of `xsd:duration` and `xsd:dayTimeDuration`

### ISSUE THREAD

**Issue by mboudet** [openlink/virtuoso-opensource#1147]
Hello!

I'm trying to write a query to filter based on a 'duration', i.e., something like
`date1 < date2  + 20 days`

As far as I know, I should be able to use either `xsd:duration` or `xsd:dayTimeDuration`, but using either throws an error related to a missing column name.

For instance, this query: 

```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?test
WHERE {
    ?a ?b ?c
    BIND ("PT120M"^^xsd:duration as ?test)
}
LIMIT 1
```
Throws a `Virtuoso S0022 Error SQ200: No column PT120MD.`
Same with basically any example from [xsd:dayTimeDuration](http://www.datypic.com/sc/xsd/t-xsd_dayTimeDuration.html)

Am I missing something on the syntax? (It does seems to work on the paid version).

I can manage by using either a direct addition (`dateTime` + a number of seconds), or `bif:dateadd`, but I'd rather not use an engine-specific solution if I can avoid it.

(I tested by directly building from the current main branch, and by using a docker image based on 7.2.9)

**Comment by HughWilliams** [comment]
We are looking into this ...

**Comment by pkleef** [comment]
We added better support for these datatypes in commit https://github.com/openlink/virtuoso-opensource/commit/e0ed09c755b4c5d1ddc9487c654af6a23afd2175 which is part of the develop/7 branch.

Please let us know if this fully resolves your issue.

**Comment by mboudet** [comment]
Seems to works fine building from the develop/7 branch.

Thank you very much!
