### ISSUE TITLE
Virtuoso bulk loader never finishes loading data

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#1148]
After update from a1baf165b4ce766b638d1287f1d6764975663e3c to 1f6a4dbfc0bdce26b89a84a2e347cd49f9634cf7, the bulk loader gets stuck in the "loading" state and never finishes. Tested on two instances with different data in RDF Turtle.

The state is indicated by `1` in the `DB.DBA.load_list` table, and also `virtuoso.log` contains `14:44:05 PL LOG: Loader started`, but no `finished` counterpart.

Also e0b604b49bcf6cecb2809767618c2948c762fc7d is still working.

**Comment by imitko** [comment]
@jakubklimek 
please could you check on which dump it stuck, e.g.
```
SQL> select ll_file from load_list where ll_state = 1
```
what RDF format of dump is it?

**Comment by jakubklimek** [comment]
In one instance it was RDF Turtle, in another one it was RDF/XML

**Comment by HughWilliams** [comment]
@jakubklimek Do you still have the issue with the https://github.com/openlink/virtuoso-opensource/commit/f2432c352877cd0240c4c6ff864ec188de04b910 fix from @pkleef  ?

**Comment by jakubklimek** [comment]
No, it fixed it.
