### ISSUE TITLE
Missing `attach_from_csv` procedure

### ISSUE THREAD

**Issue by ME-DataStudio** [openlink/virtuoso-opensource#1153]
I was following example on dumping CSV data in Virtuoso Open Source 7.2.9, but `attach_from_csv` is missing.

**Comment by HughWilliams** [comment]
The Virtuoso [`attach_from_csv`](https://docs.openlinksw.com/virtuoso/fn_attach_from_csv/) is not available in open source, as it uses Virtuoso virtual database functionality, which is not available in the open source product and is a commercial only feature.

**Comment by TallTed** [comment]
You may find this [feature comparison matrix](https://virtuoso.openlinksw.com/features-comparison-matrix/) helpful in deciding whether to stay which Virtuoso Open Source v7, or move to Virtuoso Enterprise Edition v8. It may be worth noting that we have some active special offers, under which a one year license for the latter [starts at USD 499.99](https://shop.openlinksw.com/shop.vsp?dbms=http%3A%2F%2Fwww.openlinksw.com%2Fontology%2Fsoftware%23OpenLinkVirtuoso).

Please confirm whether these details are sufficient to consider this issue resolved.

**Comment by HughWilliams** [comment]
Note the Virtuoso open source edition does support the follow CSV data load/import methods:

1.  Virtuoso [`csv_load`](https://docs.openlinksw.com/virtuoso/fn_csv_load/) single CSV file Import function.
2. Virtuoso [CSV File Bulk Loader](https://vos.openlinksw.com/owiki/wiki/VOS/VirtCsvFileBulkLoader) multiple CSV file Import functions.
