### ISSUE TITLE
sorting with `LIMIT`, `OFFSET`, `MAX`, and subqueries

### ISSUE THREAD

**Issue by rapw3k** [openlink/virtuoso-opensource#1158]
hi!
When we want to use order by, with `LIMIT` and `OFFSET`, with datasets over 10000 rows, e.g., `LIMIT 100 OFFSET 14000` we get error:

> Virtuoso 22023 Error SR353: Sorted TOP clause specifies more then 14100 rows to sort. Only 10000 are allowed. Either decrease the offset and/or row count or use a scrollable cursor

In order to avoid this error we are using subqueries as suggested in [Working with SPARQL endpoint constraints via `LIMIT` & `OFFSET`](https://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksHowToHandleBandwidthLimitExceed)
 

However, there is a problem when using `MAX (in group)` function. We need `MAX` because there are some `sosa:ObservationCollection` with more than one `sosa:resultTime`/`sosa:phenomenonTime` and we just need to take one

For example, see queries below (you can test in https://www.foodie-cloud.org/sparql) 

- query 1 returns the first 100 rows correctly, but the `ORDER BY` is ignored. Rows are returned in random? order
- the query 2 returns rows in correct order, but the `LIMIT` and `OFFSET` are ignored

Is there a way to make both work properly, where all, `ORDER BY`, plus `LIMIT` and `OFFSET` work properly?

### Query1
```sparql
PREFIX sosa:  <http://www.w3.org/ns/sosa/>

SELECT DISTINCT ?id MAX(?phenomenonTime) as ?p MAX(?resultTime) as ?r

FROM <http://w3id.org/iliad/dataaset/jf-pilot-sample>

WHERE {
    SELECT DISTINCT ?id ?phenomenonTime ?resultTime
    WHERE {
        ?col    a                           sosa:ObservationCollection;
                sosa:resultTime             ?resultTime;
                sosa:phenomenonTime         ?phenomenonTime;
                sosa:hasMember              ?s.
        ?s      rdf:type/rdfs:subClassOf*   sosa:Observation;
                sosa:hasResult              ?result.

        BIND(REPLACE(STRAFTER(STR(?s), "observation/"), "/", "-") AS ?id)

    }
    ORDER BY ?id
} 
GROUP BY ?id
LIMIT 100 OFFSET 0
```

### Query2
```sparql
PREFIX sosa:  <http://www.w3.org/ns/sosa/>

SELECT DISTINCT ?id ?p ?r

FROM <http://w3id.org/iliad/dataaset/jf-pilot-sample>

WHERE {
    SELECT DISTINCT ?id MAX(?phenomenonTime) as ?p MAX(?resultTime) as ?r
    FROM <http://w3id.org/iliad/dataaset/jf-pilot-sample>
    WHERE {
        ?col    a                           sosa:ObservationCollection;
                sosa:resultTime             ?resultTime;
                sosa:phenomenonTime         ?phenomenonTime;
                sosa:hasMember              ?s.
        ?s      rdf:type/rdfs:subClassOf*   sosa:Observation;
                sosa:hasResult              ?result.

        BIND(REPLACE(STRAFTER(STR(?s), "observation/"), "/", "-") AS ?id)

    }
    GROUP BY ?id
    ORDER BY ?id
}
LIMIT 100 OFFSET 0
```

**Comment by HughWilliams** [comment]
The version of Virtuoso being used is [07.20.3230 from Jan  9 2019](https://www.foodie-cloud.org/sparql?default-graph-uri=&query=%0D%0A%0D%0ASELECT%09%0D%0A++%28+bif%3Asys_stat%28%27st_dbms_name%27%29++++++++++AS+%3Fname+%29%0D%0A++%28+bif%3Asys_stat%28%27st_dbms_ver%27%29+++++++++++AS+%3Fversion+%29%0D%0A++%28+bif%3Asys_stat%28%27st_build_thread_model%27%29+AS+%3Fthread+%29%0D%0A++%28+bif%3Asys_stat%28%27st_build_opsys_id%27%29+++++AS+%3Fopsys+%29%0D%0A++%28+bif%3Asys_stat%28%27st_build_date%27%29+++++++++AS+%3Fdate+%29%0D%0A++%28bif%3Asys_stat+%28%27git_head%27%29+AS+%3Fgit_head%29%0D%0A%0D%0AWHERE%0D%0A++%7B+%7D&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+) which is from 4 years ago and there have been a number of releases since then. Thus I would recommend updating to the latest [Virtuoso open source stable/7](https://github.com/openlink/virtuoso-opensource/tree/stable/7) release and test to see if the problem still persists ...

**Comment by rapw3k** [comment]
thanks @HughWilliams this was about the place of `LIMIT`, should be in the subquery.

**Comment by TallTed** [comment]
To be explicit...

## Query variation 3
```sparql
PREFIX sosa:  <http://www.w3.org/ns/sosa/>

SELECT DISTINCT ?id ?p ?r

FROM <http://w3id.org/iliad/dataaset/jf-pilot-sample>

WHERE {
    SELECT DISTINCT ?id MAX(?phenomenonTime) as ?p MAX(?resultTime) as ?r
    FROM <http://w3id.org/iliad/dataaset/jf-pilot-sample>
    WHERE {
        ?col    a                           sosa:ObservationCollection;
                sosa:resultTime             ?resultTime;
                sosa:phenomenonTime         ?phenomenonTime;
                sosa:hasMember              ?s.
        ?s      rdf:type/rdfs:subClassOf*   sosa:Observation;
                sosa:hasResult              ?result.

        BIND(REPLACE(STRAFTER(STR(?s), "observation/"), "/", "-") AS ?id)

    }
    GROUP BY ?id
    ORDER BY ?id
    LIMIT 100 OFFSET 0
}
```

**Comment by rapw3k** [comment]
sorry @TallTed @HughWilliams my bad, because this actually gets me back to my original issue. By the way I have now latest version of virtuoso.

If i use OFFSET over 10000, e.g., 
```
PREFIX sosa:  <http://www.w3.org/ns/sosa/>

SELECT DISTINCT ?id ?p ?r

FROM <http://w3id.org/iliad/dataaset/jf-pilot-sample>

WHERE {
    SELECT DISTINCT ?id MAX(?phenomenonTime) as ?p MAX(?resultTime) as ?r
    FROM <http://w3id.org/iliad/dataaset/jf-pilot-sample>
    WHERE {
        ?col    a                           sosa:ObservationCollection;
                sosa:resultTime             ?resultTime;
                sosa:phenomenonTime         ?phenomenonTime;
                sosa:hasMember              ?s.
        ?s      rdf:type/rdfs:subClassOf*   sosa:Observation;
                sosa:hasResult              ?result.

        BIND(REPLACE(STRAFTER(STR(?s), "observation/"), "/", "-") AS ?id)

    }
    ORDER BY ?id
    LIMIT 100 OFFSET 20000
}
```
then i get error:
``` 
Virtuoso 22023 Error SR353: Sorted TOP clause specifies more then 20100 rows to sort. Only 10000 are allowed. Either decrease the offset and/or row count or use a scrollable cursor
```
If I move the LIMIT outside in the outer query the limit, offset are ignored (all results are returned)
```
PREFIX sosa:  <http://www.w3.org/ns/sosa/>

SELECT DISTINCT ?id ?p ?r

FROM <http://w3id.org/iliad/dataaset/jf-pilot-sample>

WHERE {
    {
         SELECT DISTINCT ?id MAX(?phenomenonTime) as ?p MAX(?resultTime) as ?r
         FROM <http://w3id.org/iliad/dataaset/jf-pilot-sample>
         WHERE {
             ?col    a                           sosa:ObservationCollection;
                sosa:resultTime             ?resultTime;
                sosa:phenomenonTime         ?phenomenonTime;
                sosa:hasMember              ?s.
             ?s      rdf:type/rdfs:subClassOf*   sosa:Observation;
                sosa:hasResult              ?result.
             BIND(REPLACE(STRAFTER(STR(?s), "observation/"), "/", "-") AS ?id) 
         }         
         ORDER BY ?id         
    }    
}
LIMIT 100 OFFSET 20000
```
You can try it in our endpoint: https://www.foodie-cloud.org/sparql

**Comment by HughWilliams** [comment]
The `Error SR353: Sorted TOP clause specifies more then 20100 rows to sort. Only 10000 are allowed. Either decrease the offset and/or row count or use a scrollable cursor` error is caused by the Virtuoso [`MaxSortedTopRows`](https://docs.openlinksw.com/virtuoso/dbadm/) INI file parameter which defaults to `10000`. This will need to be increased, and the Virtuoso server restarted for the new setting to take effect. Note that this will increase the memory requirements to run such queries, which is why it is limited by default.

**Comment by rapw3k** [comment]
thanks @HughWilliams yes I read about the [`MaxSortedTopRows`](https://docs.openlinksw.com/virtuoso/dbadm/) parameter. However, in order to increase this value, I would need  to know in advance the max number of rows I can get in from my queries, i.e., in one case my query could return 100,000 in another 2,000,000.  And since my graphs can grow time after time, this number will increase. So this has two issues:
1. max number of rows is not fixed
2. where and how much should I increase memory requirements in my `virtuoso.ini`, e.g., if I increase `MaxSortedTopRows` from `10000` to `100,000`, what else should I change in `virtuoso.ini`?

In order to avoid such issues, I followed the suggestion to use `LIMIT` and `OFFSET` with subqueries in: [Working with SPARQL endpoint constraints via `LIMIT` & `OFFSET`](https://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksHowToHandleBandwidthLimitExceed)

This works fine, except when I want to use `MAX` or `MIN` functions. For example, the query below is the same as the second query above, except that `MAX` is not used, and it works as expected (returns only 100 rows after the provided offset, in proper order BUT includes multiple values for `?phenomenonTime` and `?resultTime`.
Any idea to overcome this issue with `MAX`/`MIN`?

```sparql
PREFIX sosa:  <http://www.w3.org/ns/sosa/>

SELECT DISTINCT ?id ?p ?r

FROM <http://w3id.org/iliad/dataaset/jf-pilot-sample>

WHERE {
    {
         #SELECT DISTINCT ?id MAX(?phenomenonTime) as ?p MAX(?resultTime) as ?r
         SELECT ?id (?phenomenonTime as ?p) (?resultTime as ?r)
         FROM <http://w3id.org/iliad/dataaset/jf-pilot-sample>
         WHERE {
             ?col    a                           sosa:ObservationCollection;
                sosa:resultTime             ?resultTime;
                sosa:phenomenonTime         ?phenomenonTime;
                sosa:hasMember              ?s.
             ?s      rdf:type/rdfs:subClassOf*   sosa:Observation;
                sosa:hasResult              ?result.
             BIND(REPLACE(STRAFTER(STR(?s), "observation/"), "/", "-") AS ?id) 
         }         
         ORDER BY ?id         
    }    
}
LIMIT 100 OFFSET 20000
```

**Comment by HughWilliams** [comment]
OK, I see what you mean, can recreate locally and have reported to development to look into ...

**Comment by TallTed** [comment]
@rapw3k — 

You can test the fix now through [a beta Docker image](https://github.com/openlink/virtuoso-opensource/issues/1199#issuecomment-1836380746), or by building yourself from the `develop/7` branch.

Of course, it will also be in our next official release, coming in the near future.
