### ISSUE TITLE
Conductor: Graph list missing

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#116]
In the latest version of Conductor (both develop/6 and /7) when I click on Linked Data -> Graphs, I don't get the graph list, but I end up in Users Security, with the "Graphs" subtab not clickable (see screenshot)

![image](https://f.cloud.github.com/assets/718827/1752487/c891d8e4-661f-11e3-9726-5f9c8e41fc75.png)

**Comment by HughWilliams** [comment]
This issue was fixed on Dec 6th in the 6.1.8 branch:

https://github.com/openlink/virtuoso-opensource/commit/f64cfade89dd63fcc82f4d10050bf5ba09984c59

Thus are you sure you are using the latest v6 build ?

The same fixed will be in the next v7 updated ...

**Comment by jakubklimek** [comment]
I am sure that a similar problem happens in the 6.1.9 branch now.
1) When clicking Graphs, I get to Users Security.
2) When I click on Graphs subtab, I get there, but when I try to remove a graph, it logs me out and takes me to conductor home page

**Comment by HughWilliams** [comment]
I have been able to recreate and reported to development to fix ...

**Comment by HughWilliams** [comment]
This problem is fixed in develop/7 branch ...
