### ISSUE TITLE
Error SP031: SPARQL compiler: The name is used in multiple clauses, without any logical connection

### ISSUE THREAD

**Issue by namedgraph** [openlink/virtuoso-opensource#1162]
The following query is valid according to Jena but gives an error on https://dbpedia.org/sparql:
`Virtuoso 37000 Error SP031: SPARQL compiler: The name ?p is used in multiple clauses, without any logical connection`
```sparql
SELECT (?p AS ?property) (MIN(?c) AS ?minCardinality) (MAX(?c) AS ?maxCardinality) 
{
  SELECT ?s ?p (count(?o) AS ?c) {
    { SELECT DISTINCT ?p { [] ?p [] }}
    { SELECT DISTINCT ?s { ?s ?p [] }}
    OPTIONAL { ?s ?p ?o }
  }
  GROUP BY ?s ?p
}
GROUP BY ?p
```

**Comment by HughWilliams** [comment]
You need to untick the "Strict checking of variable names used in multiple clauses but not logically connected to each other" option on the DBpedia SPARQL endpoint for page, which is ticked by default. The query will then run; see [its results](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=SELECT+%28%3Fp+AS+%3Fproperty%29+%28MIN%28%3Fc%29+AS+%3FminCardinality%29+%28MAX%28%3Fc%29+AS+%3FmaxCardinality%29+%0D%0A%7B%0D%0A++SELECT+%3Fs+%3Fp+%28count%28%3Fo%29+AS+%3Fc%29+%7B%0D%0A++++%7B+SELECT+DISTINCT+%3Fp+%7B+%5B%5D+%3Fp+%5B%5D+%7D%7D%0D%0A++++%7B+SELECT+DISTINCT+%3Fs+%7B+%3Fs+%3Fp+%5B%5D+%7D%7D%0D%0A++++OPTIONAL+%7B+%3Fs+%3Fp+%3Fo+%7D%0D%0A++%7D%0D%0A++GROUP+BY+%3Fs+%3Fp%0D%0A%7D%0D%0AGROUP+BY+%3Fp&format=text%2Fhtml&timeout=10000&signal_void=on).

(Note that adding `&signal_unconnected=on` to a query URL, or `define sql:signal-unconnected-variables 1` to a SPARQL query preamble, has the same effect as ticking the box on the form, while adding `&signal_unconnected=off` to a query URL, or `define sql:signal-unconnected-variables 0` to a SPARQL query preamble, has the same effect as unticking it. Including the setting in the SPARQL query preamble overrides the box on the form and/or the query URL argument.)
