### ISSUE TITLE
Virtuoso crashing - migration options

### ISSUE THREAD

**Issue by rapw3k** [openlink/virtuoso-opensource#1165]
Hi!
Our Virtuoso has been crashing for the last few months constantly (after 2-8 hours). The error is always segmentation fault. An extract of `/var/log/kern.log` is below

```
Nov  1 15:42:51 virtuoso kernel: [1295132.159079] virtuoso-t[6661]: segfault at 70 ip 00000000006891f9 sp 00007fb1c7923bb0 error 4 in virtuoso-t[400000+df3000]
Nov  1 20:00:31 virtuoso kernel: [1310591.247369] virtuoso-t[24645]: segfault at 70 ip 00000000006891f9 sp 00007f0f14836bb0 error 4 in virtuoso-t[400000+df3000]
Nov  2 19:23:31 virtuoso kernel: [1394769.846640] virtuoso-t[28091]: segfault at 70 ip 00000000006891f9 sp 00007f5ae4b78bb0 error 4 in virtuoso-t[400000+df3000]
Nov  2 20:23:28 virtuoso kernel: [1398366.479007] virtuoso-t[8756]: segfault at 70 ip 00000000006891f9 sp 00007fcfa4b98bb0 error 4 in virtuoso-t[400000+df3000]
Nov  2 23:12:51 virtuoso kernel: [1408528.783002] virtuoso-t[20164]: segfault at 70 ip 00000000006891f9 sp 00007f85f780dbb0 error 4 in virtuoso-t[400000+df3000]
Nov  3 07:04:01 virtuoso kernel: [1436798.537446] virtuoso-t[15692]: segfault at 70 ip 00000000006891f9 sp 00007fcc9d29abb0 error 4 in virtuoso-t[400000+df3000]
Nov  3 13:00:29 virtuoso kernel: [1458185.606298] virtuoso-t[20063]: segfault at 70 ip 00000000006891f9 sp 00007ff15e01fbb0 error 4 in virtuoso-t[400000+df3000]
```

* First I thought it was something about some heavy queries we were running, so I enabled `HTTPLogFile` in virtuoso `ini`, so i am getting now logs. However, there is nothing related to queries and the crashing
* So, we thought it may be file system, so we created a new Virtual Machine, and copied Virtuoso and database. Result was the same. Virtuoso crashed after started using it.
* Since we are running old version (Virtuoso 7.2.6-dev) I thought it will be good to migrate to the latest Virtuoso (7.2.11) but I thought It would good opportunity to migrate the database into the new format supported by 7.2.7+, which uses 64-bit prefix IDs in `RDF_IRI`. But in order to do that, I was trying to follow migration [option 1](https://github.com/openlink/virtuoso-opensource/blob/develop/7/README.UPGRADE.md#upgrade-method-1) . That means I need to make a dump of whole database using the `RDF_DUMP_NQUADS()` procedure. The problem however, is that i start the procedure, but Virtuoso always crashes somewhere in the middle, so I cannot make the Dump. 

So, the question is what should I do? Should I try copying the existing database in the new Virtuoso 7.2.11, and then try migration [option 2](https://github.com/openlink/virtuoso-opensource/blob/develop/7/README.UPGRADE.md#upgrade-method-2)?

Any other help you can provide?

Details of current Virtuoso
**endpoint**: https://www.foodie-cloud.org/sparql 
**version**: `7.2.6-dev`
**database size**: 265 GB
**`Virtuoso.ini` attached** (renamed to `virtuoso.txt`)
[`virtuoso.txt`](https://github.com/openlink/virtuoso-opensource/files/13250049/virtuoso.txt)

**Comment by HughWilliams** [comment]
Seems there is probably some corruption in the database which should be repaired first to prevent the crashes and also before attempting the migration.

The first point of call would be to run a [database integrity check](https://docs.openlinksw.com/virtuoso/backup_recovery/#diagnosingrepairing) (`backup '/dev/null';`). If that fails, a crash-dump and restore of the database should be performed, as detailed [in the documentation](https://docs.openlinksw.com/virtuoso/backup_recovery/#diagnosingrepairing).

**Comment by rapw3k** [comment]
thanks for the feedback @HughWilliams . 
Indeed the `backup '/dev/null';` failed, 

So i tried running the command below:
```
virtuoso-t +configfile /home/virtuoso/virtuoso.ini +crash-dump
```
but i get an error
```
20:54:41 OpenLink Virtuoso Universal Server
20:54:41 Version 07.20.3230-pthreads for Linux as of Jan  9 2019
20:54:41 uses parts of OpenSSL, PCRE, Html Tidy
20:54:56 The values for log segment 1 are invalid
```
attached is the new [`virtuoso.txt`](https://github.com/openlink/virtuoso-opensource/files/13254177/virtuoso.txt)

Is it something wrong with my settings in `virtuoso.ini`?

**Comment by HughWilliams** [comment]
In the INI file you have the entries:

```
Striping           = 1
LogSegments        = 1
Log1               = /home/virtuoso/virtuoso_db/log1.trx
```

Whereas you also have `DatabaseFile       = /home/virtuoso/virtuoso_db/virtuoso.db`  thus is striping enable in your database or are you writing to a single `virtuoso.db` file ?

I get your error even just trying to start a database with the following entries:

```
LogSegments        = 1
Log1               = log1.trx
```

```
18:51:05 Version 07.20.3238-pthreads for Linux as of Oct 18 2023 (178d62b3c)
18:51:05 uses OpenSSL 1.1.1  11 Sep 2018
18:51:05 uses parts of PCRE, Html Tidy
18:51:05 The values for log segment 1 are invalid
```

I have never used those INI file settings before with a striped or unstriped database and would recommend commenting them out and trying again ...

**Comment by rapw3k** [comment]
thanks @HughWilliams . Indeed, I accidentally set ```Striping``` to `1`. I put it back to `0`, so striping is disabled. Our Virtuoso has only one database file which is located in ```DatabaseFile       = /home/virtuoso/virtuoso_db/virtuoso.db```.

Unfortunately I still have the same error:  ```The values for log segment 1 are invalid```
The settings of `Database` section are as below. 

What should I comment out or change?

```
[Database]
DatabaseFile       = /home/virtuoso/virtuoso_db/virtuoso.db
ErrorLogFile       = /home/virtuoso/virtuoso_db/virtuoso.log
LockFile           = /home/virtuoso/virtuoso_db/virtuoso.lck
TransactionFile    = /home/virtuoso/virtuoso_db/virtuoso.trx
xa_persistent_file = /home/virtuoso/virtuoso_db/virtuoso.pxa
ErrorLogLevel      = 7
FileExtend         = 2000
; Set this to up to 25% of the database page count. with a large database, setting MaxCheckpointRemap to 1/4th of the database size is recommended. This is in pages, 8K per page (each buffer consisting of 8K bytes)
;MaxCheckpointRemap = 2000
MaxCheckpointRemap = 1702500
Striping           = 0
LogSegments        = 1
Log1               = /home/virtuoso/virtuoso_db/log1.trx
TempStorage        = TempDatabase
```

**Comment by rapw3k** [comment]
hi @HughWilliams I think I cleared this part. 
I commented ```LogSegments        = 1```
and then I had to move the ``` TransactionFile`    = /home/virtuoso/virtuoso_db/virtuoso.trx ``` as it was non-zero.

i started the dump now and its executing, and the TransactionFile is growing., so basically the setting for ``` Log1 ``` is ignored

**Comment by rapw3k** [comment]
hi @HughWilliams the crash dump is taking many days. So far, it has been running for more than 3 days and its around 80% completed. I can see the process is running, and the transaction log is growing. 

One question, once this is done, 

1. can i rebuild the database (Start the server with the `+restore-crash-dump` option) directly on a new version of Virtuoso (`7.2.11`) or 

3. should i rebuild the database in the same version (`7.2.6-dev`), and then follow the procedure of [option 1](https://github.com/openlink/virtuoso-opensource/blob/develop/7/README.UPGRADE.md#upgrade-method-1) to make another dump of the whole database using the `RDF_DUMP_NQUADS()` procedure, and then bulkload them into the new database?

**Comment by HughWilliams** [comment]
I would recommend performing the `+restore-crash-dump` with the same binary ie `7.2.6-dev` as the `+crash-dump` was performed with. 

Then dump the RDF data with the `RDF_DUMP_NQUADS()` procedure.  

The bulkload for the RDF datasets can then be performed with the latest `7.2.11` into a new empty database.

**Comment by rapw3k** [comment]
hi @HughWilliams after over 4 days, the log was created. The log has 397GB (while the original database has 251GB).

Yesterday I tried to make the recovery `+restore-crash-dump` and after processing 48% of the log, Virtuoso crashed. I checked the kernel log (`/var/log/kern.log`), and it was again segmentation fault:
```
virtuoso-t[6658]: segfault at 40 ip 00007fa3e5748ca5 sp 00007fff1c453110 error 4 in libc-2.31.so[7fa3e5706000+1e8000]
```

I am trying once again, but I am running out of options here. What should I do if this fails again?

**Comment by rapw3k** [comment]
attached below is the log of the dump generation

[`virtuoso.log.txt`](https://github.com/openlink/virtuoso-opensource/files/13363982/virtuoso.log.txt)

**Comment by HughWilliams** [comment]
4 days seems extremely long to `+crash-dump` a 251GB database. 

The [`virtuoso.log.txt`](https://github.com/openlink/virtuoso-opensource/files/13363982/virtuoso.log.txt) is for the `+crash-dump` and not of much interest, as it completed successfully. Do you not have the `virtuoso.log` for the `+restore-crash-dump` attempt that crashed?

What is the database triple count?

How much memory and how many CPU cores are available on the host machine?

Based on your INI file setting, I assume about 80GB RAM, for which you have `NumberOfBuffers = 6810000`, but how many of those buffers are in use when the database worksheet is loaded into memory, which can be seen by running the `status();` command in `isql`?

If the `+restore-crash-dump` is also causing a crash, we should obtain more information on where these crashes are occurring, by creating a debug, unstripped Virtuoso binary, to force core file generation as detailed in this [Virtuoso open source `gdb` core file stack trace generation for analysis](https://community.openlinksw.com/t/virtuoso-open-source-gdb-core-file-stack-trace-generation-for-analysis/1341) article.

You could also try dumping only the RDF data from the current database and binary with the `RDF_DUMP_NQUADS()` procedure, to see if it completes without crashing. If it does, then reload into an empty database using the latest Virtuoso 64bit prefix binary.

**Comment by rapw3k** [comment]
hi @HughWilliams 
below is the log from virtuoso created during the `+restore-crash-dump` process.  I tried twice and happened exactly the same. There is an error at 20% but continued, then when it reached 48%, Virtuoso simply crashed, but there is no info about that. 

[`virtuoso.log.reload.txt`](https://github.com/openlink/virtuoso-opensource/files/13369157/virtuoso.log.reload.txt)

The database has currently around 2.4 billion triples (`2 433 758 021`)
The server has 96GB of RAM, so I configured in `virtuoso.ini` to use 80GB. 

Below is the result of running `status();` command in `isql` (after querying the total number of triples)

<img width="675" alt="Screenshot 2023-11-15 at 21 10 13" src="https://github.com/openlink/virtuoso-opensource/assets/557493/eb951edf-a674-483c-ae38-e1524ebeff9e">

Regarding using `RDF_DUMP_NQUADS()`, as mentioned above, I tried that at the beginning, but it fails (Virtuoso crashes). Actually, I used `dump_nquads` procedure (`RDF_DUMP_NQUADS` was not in `v7.2.6-dev`)

I can try creating a debug, unstripped Virtuoso binary, to force core file generation as you  mentioned, but i am not sure I can pass custom ini file, i.e., `gdb /home/virtuoso/virtuoso-opensource/bin/virtuoso-t +configfile /home/virtuoso/virtuoso.ini`

I am thinking, though, that maybe a simpler way would be to dump graph by graph using `dump_one_graph`, and then upload in a new virtuoso server in the latest version v7.2.11.

Any ideas are welcome

**Comment by HughWilliams** [comment]
Ah, missed you had already tried `RDF_DUMP_NQUADS()` in your first post. If you don't have too many graphs in the database you could use the [`dump_one_graph`](https://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFDatasetDump) procedure to manually dump the graphs until all are dumped.

If the crash is still occurring when using `dump_one_graph`, then the debug build to enable core file creation will be required, so we can see where these crashes are occurring and possibly fix to enable the database RDF dump or the `+restore-crash-dump` to complete.

Why do you think you cannot "pass custom ini file, i.e., `gdb /home/virtuoso/virtuoso-opensource/bin/virtuoso-t +configfile /home/virtuoso/virtuoso.ini`", as it should be possible. Or you can just enable core file creation (`ulimit -c unlimited`) and start the database normally with the debug binary, and the core will be created and can then be analysed with `gdb` to obtain a stack trace afterwards.

**Comment by rapw3k** [comment]
hi @HughWilliams 
fortunately the last idea worked out. 
I made dumps graph by graph (around 380 graphs), so when virtuoso crashed during one, i could restart it from that graph. 
Then i reloaded them in new server with more resources and with latest virtuoso.
Our endpoint now looks like: https://www.foodie-cloud.org/sparql 

Btw, the db is now only 121G instead of 251G. This is incredible how much space was compacted. Seems we need to frequently regenerate db, or is there another way of compacting db?

thanks anyway for all the ideas and support

**Comment by HughWilliams** [comment]
Glad to hear you were able to use the [`dump_one_graph`](https://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFDatasetDump) procedure to manually dump each graph, and then successfully reload into an empty database with the latest Virtuoso binary.

Generally, the database will fragment over time. The easiest way to re-compact the database would be to perform a [`+backup-dump`](https://docs.openlinksw.com/virtuoso/backup_recovery/#dbrebuild) (similar to `+crash-dump`) and restore of the database to rebuild it as detailed in the link.

I shall close this issue now ...
