### ISSUE TITLE
Missing Dockerfile

### ISSUE THREAD

**Issue by fungiboletus** [openlink/virtuoso-opensource#1166]
Hi,

I do not find the `Dockerfile` of the [openlink/virtuoso-opensource-7](https://hub.docker.com/r/openlink/virtuoso-opensource-7) docker image. I would like to know if the Dockerfile is not opensource or if or if it's just an oversight.

Thanks.

**Comment by pkleef** [comment]
The `Dockerfile` we use for our [openlink/virtuoso-opensource-7 ](https://hub.docker.com/r/openlink/virtuoso-opensource-7) is tied into our internal build and QA structure and therefor is not usable by the general public at this point.

Is there a specific reason why you want to build your own Docker image, instead of using our reference builds which we publish and maintain on a regular basis?

**Comment by fungiboletus** [comment]
> The Dockerfile we use for our [openlink/virtuoso-opensource-7 ](https://hub.docker.com/r/openlink/virtuoso-opensource-7)is tied into our internal build and QA structure and therefor is not usable by the general public at this point.

I understand. Thanks.

> Is there a specific reason why you want to build your own Docker image, instead of using our reference builds which we publish and maintain on a regular basis?

I feel more comfortable from a SecsOps point of view when I have the software container recipe and I can build from the source. It's not a must and I successfully used the docker image you publish.

**Comment by claudiu-cristea** [comment]
This is a duplicate of #1095

**Comment by claudiu-cristea** [comment]
> I feel more comfortable from a SecsOps point of view when I have the software container recipe and I can build from the source. It's not a must and I successfully used the docker image you publish.

I think it's a "must". When you deploy a container using a Docker image, you should be able to understand how that image has been generated. Somehow, it's part of the Open Source philosophy

**Comment by fungiboletus** [comment]
I do run proprietary software in containers and I'm okay with that, but I agree that including a Dockerfile would be best to respect the opensource philosophy.

**Comment by pkleef** [comment]
@fungiboletus @claudiu-cristea 

As i stated before,  our Dockerfile is not usable by anyone else due to the fact it ties in with our internal build/QA structures, but since you are interested, here is the whole file.  You may verify by using the [Docker Hub Layers](https://hub.docker.com/layers/pkleef/virtuoso-opensource-7/latest/images/sha256-cb6e1eeaa58cd43298202319720b940a185447f6eebbe85750331ac7b89eb368?tab=layers) page.

```dockerfile
#
#  Copyright (C) 2023 OpenLink Software
#
FROM ubuntu:focal


#
#  Set arguments in GNUmakefile
#
ARG VIRTUOSO_VERSION
ARG TARGETPLATFORM
ARG DOCKER_TAG


#
#  Global environment for the docker image
#
ENV DOCKER_TAG		"${DOCKER_TAG}-ubuntu"
ENV VIRTUOSO_HOME	/opt/virtuoso-opensource
ENV PATH		$VIRTUOSO_HOME/bin:$PATH
ENV TERM		xterm


#
#  Labels
#
LABEL   com.openlinksw.vendor="OpenLink Software"
LABEL   maintainer="OpenLink Support <support@openlinksw.com>"
LABEL   copyright="Copyright (C) 2023 OpenLink Software"
LABEL   version="$VIRTUOSO_VERSION"
LABEL   description="OpenLink Virtuoso Open Source Edition $VIRTUOSO_VERSION -- Docker Image (Ubuntu/$TARGETPLATFORM)"
LABEL   docker_tag="${DOCKER_TAG}"


#
#  Update the OS with all the runtime packages Virtuoso requires
#
RUN     apt-get         update \
        && apt-get      install -y ca-certificates less openssl pwgen wget netcat vim-tiny libedit2 \
        && apt-get      remove --purge -y \
        && apt-get      autoremove -y \
        && apt-get      autoclean \
        && rm -rf       /var/lib/apt/* \
        && /usr/sbin/useradd virtuoso                                   \
                --no-log-init                                           \
                --create-home                                           \
                --user-group                                            \
                --home-dir "$VIRTUOSO_HOME"                             \
                --shell  /bin/bash                                      \
        && mkdir -p "$VIRTUOSO_HOME"/database                           \
        && mkdir -p "$VIRTUOSO_HOME"/settings                           \
        && mkdir -p "$VIRTUOSO_HOME"/initdb.d                           \
        && ln -s "$VIRTUOSO_HOME"/database /database                    \
        && ln -s "$VIRTUOSO_HOME"/settings /settings                    \
        && ln -s "$VIRTUOSO_HOME"/initdb.d /initdb.d                    \
        && ln -s "$VIRTUOSO_HOME"/bin/virtuoso-entrypoint.sh  /		\
        && chown -R virtuoso:virtuoso "$VIRTUOSO_HOME"


#
#  Install Virtuoso Open Source 7.x
#
COPY --chown=virtuoso:virtuoso ubuntu/$TARGETPLATFORM/virtuoso-opensource /opt/virtuoso-opensource


#
#  Default directory
#
VOLUME	[ "/database" ]
WORKDIR /database


#
#  The TCP ports that Virtuoso uses
#
EXPOSE	1111/tcp
EXPOSE	8890/tcp


#
#  Use SIGINT to gracefully stop this image
#
STOPSIGNAL	SIGINT


#
#  Wrapper
#
ENTRYPOINT [ "/virtuoso-entrypoint.sh" ]


#
#  Default command is start
#
CMD ["start"]
```

One of the reasons for this method, is the fact we actually build a multi-arch version of our images so they work natively on Intel machines (for Linux, macOS Intel, and Windows) as well as ARM-based machines (for Apple Silicon, and ARM boards like Raspberry Pi). Doing this via QEMU emulation may take several hours.

Note that I will be making a reference Dockerfile soon that can be used to build a version of the VOS Docker. It will be published as a separate git tree here on Github.

**Comment by claudiu-cristea** [comment]
@pvk, thank you, that helps a lot. Is it possible to also publish `virtuoso-entrypoint.sh`?

**Comment by pkleef** [comment]
@claudiu-cristea 

You can get a copy of the `virtuoso-entrypoint.sh` script from an existing image using the following commands:

```shell
$ docker create --name vos-demo openlink/virtuoso-opensource-7:latest

$ docker cp vos-demo:/opt/virtuoso-opensource/bin/virtuoso-entrypoint.sh /tmp

$ docker rm vos-demo
```

Of course, this script will also be part of the new git tree I [mentioned above](https://github.com/openlink/virtuoso-opensource/issues/1166#issuecomment-1803766248).

**Comment by claudiu-cristea** [comment]
Great, thank you! Waiting for the new Git tree

**Comment by pkleef** [comment]
@fungiboletus @claudiu-cristea

Please have a look at this document:  [Building a Virtuoso Open Source Edition Docker image](https://community.openlinksw.com/t/building-a-virtuoso-open-source-edition-reference-docker-image) and the new [Git tree for the VOS reference docker](https://github.com/openlink/vos-reference-docker/)

**Comment by claudiu-cristea** [comment]
@pkleef thank you
