### ISSUE TITLE
bulk loader works strangely with TriG

### ISSUE THREAD

**Issue by jdkim** [openlink/virtuoso-opensource#1169]
I am using the newest stable version of VOS.

Version: 07.20.3238
Build: Nov 6 2023 (d89671fa1)

I tested the bulk loader with the three examples in the section [2.2 Graph Statements](https://www.w3.org/TR/trig/#sec-graph-statements).

For bulk loading, I followed the steps in [this page](https://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader).

With Example 1, it worked fine.
With Example 2, it looked fine in my first attempt, but later randomly missed one of the named graphs.
With Example 3, it spat a syntax error, which disappeared when I removed the "GRAPH' keyword. However, it also randomly missed one of the named graphs.

I know there was a similar issue (#816), which I carefully read.
However I could no get the bulk loader properly work with TriG files.

**Comment by HughWilliams** [comment]
We are looking into this ...

How did you remove the "GRAPH" keyword, as when I removed or the complete line I still get a "syntax error" ?

**Comment by jdkim** [comment]
Thank you for looking into it.

I removed only the "GRAPH" keyword, and the code became similar to Example 2.
Another change I made  to the code was removing the second line "previous example" which was an obvious error.
This is the resulting code:
```
# This document contains a same data as the previous example.

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dc: <http://purl.org/dc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

# default graph - no {} used.
<http://example.org/bob> dc:publisher "Bob" .
<http://example.org/alice> dc:publisher "Alice" .

# GRAPH keyword to highlight a named graph
# Abbreviation of triples using ;
<http://example.org/bob>
{
   [] foaf:name "Bob" ;
      foaf:mbox <mailto:bob@oldcorp.example.org> ;
      foaf:knows _:b .
}

<http://example.org/alice>
{
    _:b foaf:name "Alice" ;
        foaf:mbox <mailto:alice@work.example.org>
}
```

**Comment by pkleef** [comment]
We added support for the GRAPH decoration in Trig files with commit https://github.com/openlink/virtuoso-opensource/commit/4db936f23a75bc689cedbe73a30e2f59005054bc on the [develop/7](https://github.com/openlink/virtuoso-opensource/) branch.
