### ISSUE TITLE
Cannot open conductor due to Error 22007

### ISSUE THREAD

**Issue by jdkim** [openlink/virtuoso-opensource#1171]
I got this error message when I was trying to open the conductor from the browser:

Error 22007
XM003: XML parser detected an error:
	ERROR  : Tag nesting error: name 'div' of end tag does not match the name 'v:template' of start tag at line 3412 column 82
at line 3462 column 22 of 'virt://WS.WS.SYS_DAV_RES.RES_FULL_PATH.RES_CONTENT:/DAV/VAD/conductor/dav/dav_browser.xsl'
              </div>
--------------------^

I was running Ubuntu 22.04.3 LTS, and trying to install the latest version locally in the home directory of 'virtuoso'.
Before installation, I double checked that all the process of virtuoso were killed, and deleted every file from the previous version.

I began from a fresh clone from the VOS github project, and took the following steps:
```
- ./autogen.sh
- export CFLAGS="-O2 -m64"
- ./configure --prefix=/home/virtuoso --with-readline
- make
- make install
```
There was no particular problem throughout all the steps.
'make check' also did not show any problem.

It was successfully launched with virtuoso-t, and showed this version number in my browser:

Version: 07.20.3238
Build: Nov 9 2023

However, when I clicked 'conductor' from the main menu, I got the error message above.

**Comment by HughWilliams** [comment]
What Virtuoso git branch are you building from, [stable/7](https://github.com/openlink/virtuoso-opensource/tree/stable/7) or [develop/7](https://github.com/openlink/virtuoso-opensource/tree/develop/7)?

What are your Virtuoso binary version and `gitid`, and Conductor VAD version? These can be obtained by making an `isql` connection and running the commands:

`status('');`
`vad_list_packages();`

Are any errors or warnings reported in the `virtuoso.log` file on startup and when accessing the Conductor? Please provide a copy of the log for review.

**Comment by jdkim** [comment]
Thank you for looking into it.

> What Virtuoso git branch are you building from, [stable/7](https://github.com/openlink/virtuoso-opensource/tree/stable/7) or [develop/7](https://github.com/openlink/virtuoso-opensource/tree/develop/7)?

```
> git status
On branch develop/7
Your branch is up to date with 'origin/develop/7'.
```

> What are your Virtuoso binary version and gitid, and Conductor VAD version? These can be obtained by making an isql connection and running the commands:

```
SQL> status('') ;
Connected to OpenLink Virtuoso
Driver: 07.20.3238 OpenLink Virtuoso ODBC Driver
REPORT
VARCHAR
_______________________________________________________________________________

OpenLink Virtuoso  Server
Version 07.20.3238-pthreads for Linux as of Nov  9 2023 (4db936f23)
Started on: 2023-11-09 18:34 GMT+0
CPU: 0.05% RSS: 11066MB
 
Database Status:
  File size 69206016, 8448 pages, 6287 free.
  2720000 buffers, 734 used, 3 dirty 0 wired down, repl age 0 0 w. io 0 w/crsr.
  Disk Usage: 795 reads avg 0 msec, 0% r 0% w last  8 s, 284 writes flush          0 MB/s,
    25 read ahead, batch = 14.  Autocompact 8 in 7 out, 11% saved.
Gate:  91 2nd in reads, 0 gate write waits, 0 in while read 0 busy scrap. 
Log = /home/virtuoso/db/virtuoso.trx, 6699 bytes
2095 pages have been changed since last backup (in checkpoint state)
Current backup timestamp: 0x0000-0x00-0x00
Last backup date: unknown
Clients: 2 connects, max 1 concurrent
RPC: 8 calls, 1 pending, 1 max until now, 0 queued, 0 burst reads (0%), 0 second 0M large, 10M max
Checkpoint Remap 38 pages, 0 mapped back. 0 s atomic time.
    DB master 8448 total 6287 free 38 remap 2 mapped back
   temp  256 total 251 free
 
Lock Status: 0 deadlocks of which 0 2r1w, 0 waits,
   Currently 1 threads running 0 threads waiting 0 threads in vdb.
Pending:

24 Rows. -- 29 msec.
```

```
SQL> vad_list_packages();
name     title    version  build_date  install_date
VARCHAR  VARCHAR  VARCHAR  VARCHAR  VARCHAR
_______________________________________________________________________________

conductor  Virtuoso Conductor  1.00.8853  2023-11-09 18:09  2023-11-09 18:11

1 Rows. -- 1 msec.
```

> Are any errors or warnings reported in the virtuoso.log file on startup and when accessing the Conductor? Please provide a copy of the log for review.

```
                Thu Nov 09 2023
23:37:12 { Loading plugin 1: Type `plain', file `wikiv' in `/home/virtuoso/lib/virtuoso/hosting'
23:37:12   WikiV version 0.6 from OpenLink Software
23:37:12   Support functions for WikiV collaboration tool
23:37:12   SUCCESS plugin 1: loaded from /home/virtuoso/lib/virtuoso/hosting/wikiv.so }
23:37:12 { Loading plugin 2: Type `plain', file `mediawiki' in `/home/virtuoso/lib/virtuoso/hosting'
23:37:12   MediaWiki version 0.1 from OpenLink Software
23:37:12   Support functions for MediaWiki collaboration tool
23:37:12   SUCCESS plugin 2: loaded from /home/virtuoso/lib/virtuoso/hosting/mediawiki.so }
23:37:12 { Loading plugin 3: Type `plain', file `creolewiki' in `/home/virtuoso/lib/virtuoso/hosting'
23:37:12   CreoleWiki version 0.1 from OpenLink Software
23:37:12   Support functions for CreoleWiki collaboration tool
23:37:12   SUCCESS plugin 3: loaded from /home/virtuoso/lib/virtuoso/hosting/creolewiki.so }
23:37:12 { Loading plugin 8: Type `plain', file `shapefileio' in `/home/virtuoso/lib/virtuoso/hosting'
23:37:12   ShapefileIO version 0.1virt71 from OpenLink Software
23:37:12   Shapefile support based on Frank Warmerdam's Shapelib
23:37:12   SUCCESS plugin 8: loaded from /home/virtuoso/lib/virtuoso/hosting/shapefileio.so }
23:37:12 { Loading plugin 9: Type `plain', file `graphql' in `/home/virtuoso/lib/virtuoso/hosting'
23:37:12   GraphQL/SPARQL Bridge version 0.9.3 (4db936f23) from OpenLink Software
23:37:12   Support functions for GraphQL/SPARQL Bridge
23:37:12   SUCCESS plugin 9: loaded from /home/virtuoso/lib/virtuoso/hosting/graphql.so }
23:37:12 OpenLink Virtuoso Universal Server
23:37:12 Version 07.20.3238-pthreads for Linux as of Nov  9 2023 (4db936f23)
23:37:12 uses OpenSSL 3.0.2 15 Mar 2022
23:37:12 uses parts of PCRE, Html Tidy
23:37:17 Database version 3126
23:37:17 SQL Optimizer enabled (max 1000 layouts)
23:37:18 Compiler unit is timed at 0.000135 msec
23:37:19 Roll forward started
23:37:19     15 transactions, 1242 bytes replayed (100 %)
23:37:19 Roll forward complete
23:37:19 Checkpoint started
23:37:19 Checkpoint finished, log reused
23:37:19 HTTP/WebDAV server online at 8890
23:37:19 Server online at 1111 (pid 331322)
```
```

**Comment by HughWilliams** [comment]
I have been able to recreate this issue with the `conductor_dav.vad` (`1.00.8853`) package built from the current `develop/7` branch, and we are looking into the cause.

Please use the `stable/7` [`conductor_dav.vad`](https://download3.openlinksw.com/uda/vad-vos-packages/7.2/conductor_dav.vad) (`1.00.8849`) VAD package in this link, containing the pre-built VAD.

**Comment by pkleef** [comment]
I just committed https://github.com/openlink/virtuoso-opensource/commit/d14fc28e7c475dbac733e8953d5d9e2dcef98c77  to the develop/7 branch which fixes this issue.
