### ISSUE TITLE
Trouble sponging graph in SPARQL endpoint:  RDF_SPONGE_UP_1 permission

### ISSUE THREAD

**Issue by malajvan** [openlink/virtuoso-opensource#1180]
Hello,
I'm trying to sponge through the SPARQL query example from the documentation [here](https://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFInsert#Example%20using%20SPARQL%20Query%20%26%20Sponger)
```
SPARQL
SELECT ?id 
FROM NAMED <http://www.openlinksw.com/dataspace/kidehen@openlinksw.com/weblog/kidehen@openlinksw.com%27s%20BLOG%20%5B127%5D/sioc.ttl>
 OPTION (get:soft "soft", get:method "GET")
WHERE { GRAPH ?g { ?id a ?o } }
LIMIT 10; 
```
However I don't understand why even though it works in iSQL (http://localhost:8890/conductor/isql.vspx), it throws permission error at http://localhost:8890/sparql/ : 
`Virtuoso RDFZZ Error The graph  is not sponged by RDF_SPONGE_UP_1 due to lack of sponge permission for user 107`
 
I followed the instructions and gave `SPARQL_SPONGE` and `SPARQL_UPDATE` permissions to user `107` (`SPARQL`), and even manually granted access for `RDF_SPONGE_UP_1`.

Did I misunderstand somewhere? I would appreciate any suggestions on how I can move forward. Thank you very much!

**Comment by HughWilliams** [comment]
With recent Virtuoso releases, to perform SPARQL operations as an existing or new user, low level [RDF Graph Security](https://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFGraphsSecurity) permissions need to be set, to determine what access (read/write/sponge) the user has on the RDF Quad Store. This is done using the [`DB.DBA.RDF_DEFAULT_USER_PERMS_SET()`](https://docs.openlinksw.com/virtuoso/fn_rdf_default_user_perms_set/) function, in addition to the high level SQL roles (`SPARQL_SELECT`, `SPARQL_UPDATE`, `SPARQL_SPONGE`). Thus, try running the following to resolve the problem:

```
DB.DBA.RDF_DEFAULT_USER_PERMS_SET ('SPARQL', 7);
```

**Comment by malajvan** [comment]
Thank you very much! This fixed it.
