### ISSUE TITLE
Wikidata RDF - schema:description mapping

### ISSUE THREAD

**Issue by malajvan** [openlink/virtuoso-opensource#1186]
Hello, I'm trying to sponge Wikidata pages. In URIBurner, the field `schema:description` is boxed at the top of the faceted browser like so:

![image](https://github.com/openlink/virtuoso-opensource/assets/64571718/6a12cb14-1017-49ae-bafe-e7270dde75bd)

However, this doesn't happen in my local version. Upon further inspection of this repo, I found [this line]
(https://github.com/openlink/virtuoso-opensource/blob/77800f6e1a610add7c152fc67f2e49a07e16b15e/NEWS.md?plain=1#L179) and thought maybe it's related but failed to find where it is implemented. The other pages with `rdfs:comment` showed up as expected in my local version, though. 

I would appreciate it if someone could give me a hint of why there's this difference. Another theory of mine is there is a Wikidata sponger in URIBurner that is not available to us, so the data is handled differently, but I'm not confident in this theory. 
Thank you very much

**Comment by pkleef** [comment]
>  I would appreciate it if someone could give me a hint of why there's this difference. 

The problem was that the patch mentioned in the NEWS item, was not committed to the open source tree by mistake.

I have added the fix in commit https://github.com/openlink/virtuoso-opensource/commit/bfc23b1c02b5a86cd4ed8798cf82da0e713bf45d on the develop/7 branch.

> Another theory of mine is there is a Wikidata sponger in URIBurner that is not available to us, so the data is handled differently, but I'm not confident in this theory.

There is no special Wikidata sponger on URIburner.

**Comment by malajvan** [comment]
Great! This fixed it, thank you very much. Quick question: When will this be on the Docker image? How often do you guys update your official Docker image?

**Comment by pkleef** [comment]
Typically docker images are build as part as of the next stable release, unless there is some important reason to pull it forward.

Currently the next release is scheduled for second half of January.

**Comment by pkleef** [comment]
In case you want to test it, i have provided a new beta Docker image via my account:

```
$ docker pull pkleef/virtuoso-opensource-7
Using default tag: latest
latest: Pulling from pkleef/virtuoso-opensource-7
96d54c3075c9: Pull complete
a0765e2e968a: Pull complete
bc970729504e: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:125479fe239e930451ed791e4c178d12c8315bbdae0767e930881c017050434e
Status: Downloaded newer image for pkleef/virtuoso-opensource-7:latest
docker.io/pkleef/virtuoso-opensource-7:latest

$ docker run -i -t pkleef/virtuoso-opensource-7 version

[pkleef/virtuoso-opensource-7:7.2.12-r17-2-gee76fd3-ubuntu]

This Docker image is using the following version of Virtuoso:

Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.12-dev.3238-pthreads as of Nov 27 2023 (28e2d633f)
Compiled for Linux (x86_64-ubuntu_bionic-linux-gnu)
Copyright (C) 1998-2023 OpenLink Software
```

**Comment by malajvan** [comment]
Thank you very much! I managed to test the fix by manually replacing the file in Webdav, but the Docker image is a lot more convenient.
