### ISSUE TITLE
Unsupported type application/n-triples

### ISSUE THREAD

**Issue by claudiu-cristea** [openlink/virtuoso-opensource#1187]
In one of our projects from European Commision, we're migrating from [tenforce/virtuoso](https://hub.docker.com/r/tenforce/virtuoso) to the official image [openlink/virtuoso-opensource-7](https://hub.docker.com/r/openlink/virtuoso-opensource-7/). This HTTP request used to work correctly, for years, with the old image:

```
PUT /sparql-graph-crud?graph=http%3A%2F%2Factor HTTP/1.1
Host: virtuoso:8890
Connection: close
User-Agent: EasyRdf HTTP Client
Content-Type: application/n-triples

<http://joinup.eu/taxonomy/actor> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#ConceptScheme> .
<http://joinup.eu/taxonomy/actor#cashier> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> .
<http://joinup.eu/taxonomy/actor#cashier> <http://www.w3.org/2004/02/skos/core#prefLabel> "Cashier"@en .
... more triples here
```

but with `openlink/virtuoso-opensource-7`, fails with:

```
HTTP/1.1 500 Internal Server Error
Accept-Ranges: bytes
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
Date: Sat, 25 Nov 2023 10:39:46 GMT
Server: Virtuoso/07.20.3238 (Linux) x86_64-ubuntu_bionic-linux-gnu
Connection: close
Transfer-Encoding: chunked

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head>
  <title>SPARQL Graph Protocol request failed</title>
</head>
<body>
<h1>HTTP/1.1 500 Request Failed</h1>
<h3>Error 22023</h3>
<xmp>The PUT request for graph <http://actor> is rejected: the submitted resource is of unsupported type application/n-triples
</xmp>
</body>
</html>
```

Any clue what we're missing?

**Comment by imitko** [comment]
@claudiu-cristea 

Please indicate the last version of Virtuoso Open-Source that worked with `application/n-triples` RDF dataset uploads, e.g., output of `virtuoso -?`.

Meanwhile, you can use `Content-Type: text/rdf+n3` or `text/turtle`.

**Comment by claudiu-cristea** [comment]
@imitko,

It worked with:

```
$ virtuoso-t -v
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.6.3233-pthreads as of Oct 30 2021 (111d17e5b)
Compiled for Mac OS X (Intel x86_64) (x86_64-apple-darwin21.1.0)
Copyright (C) 1998-2021 OpenLink Software
```

**Comment by claudiu-cristea** [comment]
@imitko, thank you. Yes, it worked with `text/rdf+n3` and `text/turtle`, but is there still a chance that I can configure to work with `application/n-triples`?

**Comment by imitko** [comment]
@claudiu-cristea 
The media type support is not configurable, we are working on a fix for SPARQL-CRUD handler for N-Triples & related media types.

**Comment by claudiu-cristea** [comment]
So, we should wait for a fix  The PHP library we're using, https://github.com/sweetrdf/easyrdf, defaults to N-Triples and I would not start to change our project code.

**Comment by pkleef** [comment]
This issue was fixed with commit https://github.com/openlink/virtuoso-opensource/commit/28e2d633f6e2c86b7e5fc180fde1a56306edb1ba on the develop/7 branch

**Comment by pkleef** [comment]
In case you want to test it, i have provided a new beta Docker image via my account:

```
$ docker pull pkleef/virtuoso-opensource-7
Using default tag: latest
latest: Pulling from pkleef/virtuoso-opensource-7
96d54c3075c9: Pull complete
a0765e2e968a: Pull complete
bc970729504e: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:125479fe239e930451ed791e4c178d12c8315bbdae0767e930881c017050434e
Status: Downloaded newer image for pkleef/virtuoso-opensource-7:latest
docker.io/pkleef/virtuoso-opensource-7:latest

$ docker run -i -t pkleef/virtuoso-opensource-7 version

[pkleef/virtuoso-opensource-7:7.2.12-r17-2-gee76fd3-ubuntu]

This Docker image is using the following version of Virtuoso:

Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.12-dev.3238-pthreads as of Nov 27 2023 (28e2d633f)
Compiled for Linux (x86_64-ubuntu_bionic-linux-gnu)
Copyright (C) 1998-2023 OpenLink Software
```

**Comment by claudiu-cristea** [comment]
@pkleef,

Thank you, `7.2.12-r17-2-gee76fd3-ubuntu` works. Any clue when 7.2.12 (stable) will be released?

**Comment by pkleef** [comment]
At the moment the next stable release of virtuoso opensource is scheduled for january 2024.
