### ISSUE TITLE
Unexpected results for query with many optionals

### ISSUE THREAD

**Issue by achort** [openlink/virtuoso-opensource#1188]
I am using Virtuoso version 07.20.3237 prebuilt binary  for Windows.
Loading in a named graph the following data
```
<http://example.com/resource/acronyms/bf8f>	<http://example.com/shortForm>	"TEST" .
<http://example.com/resource/acronyms/bf8f>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/Acronym> .
<http://example.com/resource/organisations/52f7>	<http://example.com/hasSite>	<http://example.com/resource/sites/852c> .
<http://example.com/resource/organisations/52f7>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/Organisation> .
<http://example.com/resource/organisations/52f9>	<http://example.com/hasAcronym>	<http://example.com/resource/acronyms/bf8f> .
<http://example.com/resource/organisations/52f9>	<http://example.com/hasSite>	<http://example.com/resource/sites/53ed> .
<http://example.com/resource/organisations/52f9>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/Organisation> .
<http://example.com/resource/sites/03b7>	<http://example.com/hasNUTS1code>	<http://data.europa.eu/nuts/code/BE1> .
<http://example.com/resource/sites/03b7>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/AdministrativeArea> .
<http://example.com/resource/sites/2bab>	<http://example.com/hasNUTS2code>	<http://data.europa.eu/nuts/code/BE10> .
<http://example.com/resource/sites/2bab>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/AdministrativeArea> .
<http://example.com/resource/sites/2cf8>	<http://example.com/hasNUTS3code>	<http://data.europa.eu/nuts/code/BE100> .
<http://example.com/resource/sites/2cf8>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/AdministrativeArea> .
<http://example.com/resource/sites/2d31>	<http://example.com/hasNUTS1code>	<http://data.europa.eu/nuts/code/EL3> .
<http://example.com/resource/sites/2d31>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/AdministrativeArea> .
<http://example.com/resource/sites/53ed>	<http://example.com/hasGeographicalLocation>	<http://example.com/resource/sites/03b7> .
<http://example.com/resource/sites/53ed>	<http://example.com/hasGeographicalLocation>	<http://example.com/resource/sites/2bab> .
<http://example.com/resource/sites/53ed>	<http://example.com/hasGeographicalLocation>	<http://example.com/resource/sites/2cf8> .
<http://example.com/resource/sites/53ed>	<http://example.com/hasGeographicalLocation>	<http://example.com/resource/sites/e470> .
<http://example.com/resource/sites/53ed>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/Site> .
<http://example.com/resource/sites/7154>	<http://example.com/hasNUTS0code>	<http://data.europa.eu/nuts/code/EL> .
<http://example.com/resource/sites/7154>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/AdministrativeArea> .
<http://example.com/resource/sites/852c>	<http://example.com/hasGeographicalLocation>	<http://example.com/resource/sites/2d31> .
<http://example.com/resource/sites/852c>	<http://example.com/hasGeographicalLocation>	<http://example.com/resource/sites/7154> .
<http://example.com/resource/sites/852c>	<http://example.com/hasGeographicalLocation>	<http://example.com/resource/sites/9cae> .
<http://example.com/resource/sites/852c>	<http://example.com/hasGeographicalLocation>	<http://example.com/resource/sites/e670> .
<http://example.com/resource/sites/852c>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/Site> .
<http://example.com/resource/sites/9cae>	<http://example.com/hasNUTS3code>	<http://data.europa.eu/nuts/code/EL303> .
<http://example.com/resource/sites/9cae>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/AdministrativeArea> .
<http://example.com/resource/sites/e470>	<http://example.com/hasNUTS0code>	<http://data.europa.eu/nuts/code/BE> .
<http://example.com/resource/sites/e470>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/AdministrativeArea> .
<http://example.com/resource/sites/e670>	<http://example.com/hasNUTS2code>	<http://data.europa.eu/nuts/code/EL30> .
<http://example.com/resource/sites/e670>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://example.com/AdministrativeArea> .
```
and asking the query
```
SELECT *
WHERE
  { VALUES ?c_0 {   <http://example.com/resource/organisations/52f7> <http://example.com/resource/organisations/52f9> }
    ?c_0  a                     <http://example.com/Organisation>
    OPTIONAL
      { ?c_0    <http://example.com/hasAcronym>  ?c_0_0 .
        ?c_0_0  a                     <http://example.com/Acronym>
        OPTIONAL
          { ?c_0_0  <http://example.com/shortForm>  ?r0 }
      }
    OPTIONAL
      { ?c_0    <http://example.com/hasSite>  ?c_1_0 .
        ?c_1_0  a                     <http://example.com/Site>
        OPTIONAL
          { ?c_1_0    <http://example.com/hasGeographicalLocation>  ?c_1_2_0 .
            ?c_1_2_0  a                     <http://example.com/AdministrativeArea>
            OPTIONAL
              { ?c_1_2_0  <http://example.com/hasNUTS0code>  ?r8 }
            OPTIONAL
              { ?c_1_2_0  <http://example.com/hasNUTS1code>  ?r9 }
            OPTIONAL
              { ?c_1_2_0  <http://example.com/hasNUTS2code>  ?r10 }
            OPTIONAL
              { ?c_1_2_0  <http://example.com/hasNUTS3code>  ?r11 }
          }
      }
  }
```
I get the result
<table class="table table-striped table-sm table-borderless">
  <tr>
    <th>c_0</th>
    <th>c_0_0</th>
    <th>r0</th>
    <th>c_1_0</th>
    <th>c_1_2_0</th>
    <th>r8</th>
    <th>r9</th>
    <th>r10</th>
    <th>r11</th>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f9](view-source:http://example.com/resource/organisations/52f9)">http://example.com/resource/organisations/52f9</a></td>
    <td><a href="[http://example.com/resource/acronyms/bf8f](view-source:http://example.com/resource/acronyms/bf8f)">http://example.com/resource/acronyms/bf8f</a></td>
    <td><pre>"TEST"</pre></td>
    <td><a href="[http://example.com/resource/sites/53ed](view-source:http://example.com/resource/sites/53ed)">http://example.com/resource/sites/53ed</a></td>
    <td><a href="[http://example.com/resource/sites/2cf8](view-source:http://example.com/resource/sites/2cf8)">http://example.com/resource/sites/2cf8</a></td>
    <td></td>
    <td></td>
    <td></td>
    <td><a href="[http://data.europa.eu/nuts/code/BE100](view-source:http://data.europa.eu/nuts/code/BE100)">http://data.europa.eu/nuts/code/BE100</a></td>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f9](view-source:http://example.com/resource/organisations/52f9)">http://example.com/resource/organisations/52f9</a></td>
    <td><a href="[http://example.com/resource/acronyms/bf8f](view-source:http://example.com/resource/acronyms/bf8f)">http://example.com/resource/acronyms/bf8f</a></td>
    <td><pre>"TEST"</pre></td>
    <td><a href="[http://example.com/resource/sites/53ed](view-source:http://example.com/resource/sites/53ed)">http://example.com/resource/sites/53ed</a></td>
    <td><a href="[http://example.com/resource/sites/2bab](view-source:http://example.com/resource/sites/2bab)">http://example.com/resource/sites/2bab</a></td>
    <td></td>
    <td></td>
    <td><a href="[http://data.europa.eu/nuts/code/BE10](view-source:http://data.europa.eu/nuts/code/BE10)">http://data.europa.eu/nuts/code/BE10</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f9](view-source:http://example.com/resource/organisations/52f9)">http://example.com/resource/organisations/52f9</a></td>
    <td><a href="[http://example.com/resource/acronyms/bf8f](view-source:http://example.com/resource/acronyms/bf8f)">http://example.com/resource/acronyms/bf8f</a></td>
    <td><pre>"TEST"</pre></td>
    <td><a href="[http://example.com/resource/sites/53ed](view-source:http://example.com/resource/sites/53ed)">http://example.com/resource/sites/53ed</a></td>
    <td><a href="[http://example.com/resource/sites/03b7](view-source:http://example.com/resource/sites/03b7)">http://example.com/resource/sites/03b7</a></td>
    <td></td>
    <td><a href="[http://data.europa.eu/nuts/code/BE1](view-source:http://data.europa.eu/nuts/code/BE1)">http://data.europa.eu/nuts/code/BE1</a></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f9](view-source:http://example.com/resource/organisations/52f9)">http://example.com/resource/organisations/52f9</a></td>
    <td><a href="[http://example.com/resource/acronyms/bf8f](view-source:http://example.com/resource/acronyms/bf8f)">http://example.com/resource/acronyms/bf8f</a></td>
    <td><pre>"TEST"</pre></td>
    <td><a href="[http://example.com/resource/sites/53ed](view-source:http://example.com/resource/sites/53ed)">http://example.com/resource/sites/53ed</a></td>
    <td><a href="[http://example.com/resource/sites/e470](view-source:http://example.com/resource/sites/e470)">http://example.com/resource/sites/e470</a></td>
    <td><a href="[http://data.europa.eu/nuts/code/BE](view-source:http://data.europa.eu/nuts/code/BE)">http://data.europa.eu/nuts/code/BE</a></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f7](view-source:http://example.com/resource/organisations/52f7)">http://example.com/resource/organisations/52f7</a></td>
    <td></td>
    <td></td>
    <td><a href="[http://example.com/resource/sites/852c](view-source:http://example.com/resource/sites/852c)">http://example.com/resource/sites/852c</a></td>
    <td><a href="[http://example.com/resource/sites/9cae](view-source:http://example.com/resource/sites/9cae)">http://example.com/resource/sites/9cae</a></td>
    <td></td>
    <td></td>
    <td></td>
    <td><a href="[http://data.europa.eu/nuts/code/EL303](view-source:http://data.europa.eu/nuts/code/EL303)">http://data.europa.eu/nuts/code/EL303</a></td>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f7](view-source:http://example.com/resource/organisations/52f7)">http://example.com/resource/organisations/52f7</a></td>
    <td></td>
    <td></td>
    <td><a href="[http://example.com/resource/sites/852c](view-source:http://example.com/resource/sites/852c)">http://example.com/resource/sites/852c</a></td>
    <td><a href="[http://example.com/resource/sites/e670](view-source:http://example.com/resource/sites/e670)">http://example.com/resource/sites/e670</a></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f7](view-source:http://example.com/resource/organisations/52f7)">http://example.com/resource/organisations/52f7</a></td>
    <td></td>
    <td></td>
    <td><a href="[http://example.com/resource/sites/852c](view-source:http://example.com/resource/sites/852c)">http://example.com/resource/sites/852c</a></td>
    <td><a href="[http://example.com/resource/sites/2d31](view-source:http://example.com/resource/sites/2d31)">http://example.com/resource/sites/2d31</a></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f7](view-source:http://example.com/resource/organisations/52f7)">http://example.com/resource/organisations/52f7</a></td>
    <td></td>
    <td></td>
    <td><a href="[http://example.com/resource/sites/852c](view-source:http://example.com/resource/sites/852c)">http://example.com/resource/sites/852c</a></td>
    <td><a href="[http://example.com/resource/sites/7154](view-source:http://example.com/resource/sites/7154)">http://example.com/resource/sites/7154</a></td>
    <td><a href="[http://data.europa.eu/nuts/code/EL](view-source:http://data.europa.eu/nuts/code/EL)">http://data.europa.eu/nuts/code/EL</a></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

which seems to miss the bindings for r9 and r10 resulting from the triples
```
<http://example.com/resource/sites/2d31>	<http://example.com/hasNUTS1code>	<http://data.europa.eu/nuts/code/EL3> .
<http://example.com/resource/sites/e670>	<http://example.com/hasNUTS2code>	<http://data.europa.eu/nuts/code/EL30> .
```
corresponding to the first resource the VALUES statement.

However, when asking the query

```
SELECT *
FROM <http://cordis.com/test>
WHERE
  { VALUES ?c_0 {   <http://example.com/resource/organisations/52f7>  }
    ?c_0  a                     <http://example.com/Organisation>
    OPTIONAL
      { ?c_0    <http://example.com/hasAcronym>  ?c_0_0 .
        ?c_0_0  a                     <http://example.com/Acronym>
        OPTIONAL
          { ?c_0_0  <http://example.com/shortForm>  ?r0 }
      }
    OPTIONAL
      { ?c_0    <http://example.com/hasSite>  ?c_1_0 .
        ?c_1_0  a                     <http://example.com/Site>
        OPTIONAL
          { ?c_1_0    <http://example.com/hasGeographicalLocation>  ?c_1_2_0 .
            ?c_1_2_0  a                     <http://example.com/AdministrativeArea>
            OPTIONAL
              { ?c_1_2_0  <http://example.com/hasNUTS0code>  ?r8 }
            OPTIONAL
              { ?c_1_2_0  <http://example.com/hasNUTS1code>  ?r9 }
            OPTIONAL
              { ?c_1_2_0  <http://example.com/hasNUTS2code>  ?r10 }
            OPTIONAL
              { ?c_1_2_0  <http://example.com/hasNUTS3code>  ?r11 }
          }
      }
  }
```

that is including only the first one of the values in the initial VALUES statement, I get the result
<table class="table table-striped table-sm table-borderless">
  <tr>
    <th>c_0</th>
    <th>c_0_0</th>
    <th>r0</th>
    <th>c_1_0</th>
    <th>c_1_2_0</th>
    <th>r8</th>
    <th>r9</th>
    <th>r10</th>
    <th>r11</th>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f7](view-source:http://example.com/resource/organisations/52f7)">http://example.com/resource/organisations/52f7</a></td>
    <td></td>
    <td></td>
    <td><a href="[http://example.com/resource/sites/852c](view-source:http://example.com/resource/sites/852c)">http://example.com/resource/sites/852c</a></td>
    <td><a href="[http://example.com/resource/sites/9cae](view-source:http://example.com/resource/sites/9cae)">http://example.com/resource/sites/9cae</a></td>
    <td></td>
    <td></td>
    <td></td>
    <td><a href="[http://data.europa.eu/nuts/code/EL303](view-source:http://data.europa.eu/nuts/code/EL303)">http://data.europa.eu/nuts/code/EL303</a></td>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f7](view-source:http://example.com/resource/organisations/52f7)">http://example.com/resource/organisations/52f7</a></td>
    <td></td>
    <td></td>
    <td><a href="[http://example.com/resource/sites/852c](view-source:http://example.com/resource/sites/852c)">http://example.com/resource/sites/852c</a></td>
    <td><a href="[http://example.com/resource/sites/e670](view-source:http://example.com/resource/sites/e670)">http://example.com/resource/sites/e670</a></td>
    <td></td>
    <td></td>
    <td><a href="[http://data.europa.eu/nuts/code/EL30](view-source:http://data.europa.eu/nuts/code/EL30)">http://data.europa.eu/nuts/code/EL30</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f7](view-source:http://example.com/resource/organisations/52f7)">http://example.com/resource/organisations/52f7</a></td>
    <td></td>
    <td></td>
    <td><a href="[http://example.com/resource/sites/852c](view-source:http://example.com/resource/sites/852c)">http://example.com/resource/sites/852c</a></td>
    <td><a href="[http://example.com/resource/sites/2d31](view-source:http://example.com/resource/sites/2d31)">http://example.com/resource/sites/2d31</a></td>
    <td></td>
    <td><a href="[http://data.europa.eu/nuts/code/EL3](view-source:http://data.europa.eu/nuts/code/EL3)">http://data.europa.eu/nuts/code/EL3</a></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="[http://example.com/resource/organisations/52f7](view-source:http://example.com/resource/organisations/52f7)">http://example.com/resource/organisations/52f7</a></td>
    <td></td>
    <td></td>
    <td><a href="[http://example.com/resource/sites/852c](view-source:http://example.com/resource/sites/852c)">http://example.com/resource/sites/852c</a></td>
    <td><a href="[http://example.com/resource/sites/7154](view-source:http://example.com/resource/sites/7154)">http://example.com/resource/sites/7154</a></td>
    <td><a href="[http://data.europa.eu/nuts/code/EL](view-source:http://data.europa.eu/nuts/code/EL)">http://data.europa.eu/nuts/code/EL</a></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table></div>

which is correct since it includes the bindings for the r9 and r10 variables (together with the ones for r8, r11) corresponding to the first resource of the initial VALUES statement.

**Comment by HughWilliams** [comment]
We are looking into this ...

**Comment by HughWilliams** [comment]
This issue has been resolved in the latest [stable/7](https://github.com/openlink/virtuoso-opensource/tree/stable/7) branch and [Virtuoso_Open_Source_for_Windows.exe](https://github.com/openlink/virtuoso-opensource/releases/download/v7.2.12/Virtuoso_Open_Source_for_Windows.exe) installer ...
