### ISSUE TITLE
Virtuoso 22023 Error SR580

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#120]
Does this mean the db is corrupted?

<pre><code>Virtuoso 22023 Error SR580: RDF box refers to row with RO_ID = 7481090 of table DB.DBA.RDF_OBJ, but no such row in the table

SPARQL query:
define sql:big-data-const 0 
#output-format:text/turtle
define sql:signal-void-variables 1 PREFIX s: &lt;http://schema.org/&gt;
CONSTRUCT {?address ?p ?o}
WHERE 
{
?address a s:PostalAddress ;
     s:streetAddress ?street ;
     s:postalCode ?postal ;
     s:addressRegion ?region;
     s:addressLocality ?locality;
    
?p ?o . 
FILTER NOT EXISTS {?address s:geo ?geo}
}</code></pre>

**Comment by HughWilliams** [comment]
Potentially see the following post on our support forum where a similar issue was reported:

http://boards.openlinksw.com/support/viewtopic.php?f=12&t=1679&start=10#p5644

and resolved by determining the bad iris and objects and then removing them ...

**Comment by jakubklimek** [comment]
Yes, either this, or removal of certain data (see https://github.com/openlink/virtuoso-opensource/issues/118#issuecomment-30845337) fixed it.
