### ISSUE TITLE
Delete SPARQL query permissions issue

### ISSUE THREAD

**Issue by claudiu-cristea** [openlink/virtuoso-opensource#1201]
We're migrating from [tenforce/virtuoso](https://hub.docker.com/r/tenforce/virtuoso) to the official image [openlink/virtuoso-opensource-7](https://hub.docker.com/r/openlink/virtuoso-opensource-7/). With `tenforce/virtuoso` we used to run this query:

```sparql
DELETE FROM <http://languages-skos> { ?entity ?field ?value. } WHERE { ?entity ?field ?value . FILTER(str(?value) = "Multilingual Code") }
```

...against http://dba:dba@virtuoso:8890/sparql endpoint and worked well for years. 

Switching to `openlink/virtuoso-opensource-7` image, I'm getting:

```
Virtuoso RDF02 Error SR619: SPARUL DELETE access denied: database user 107 (SPARQL) has no write permission on graph http://languages-skos

SPARQL query:
define sql:big-data-const 0
DELETE FROM <http://languages-skos> { ?entity ?field ?value. } WHERE { ?entity ?field ?value . FILTER(str(?value) = "Multilingual Code") }
```

I've already ran `GRANT SPARQL_UPDATE TO "SPARQL";`

The legacy image Virtuoso version was:

```
$ virtuoso-t -v
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.6.3233-pthreads as of Oct 30 2021 (111d17e5b)
Compiled for Mac OS X (Intel x86_64) (x86_64-apple-darwin21.1.0)
Copyright (C) 1998-2021 OpenLink Software
```

**Comment by HughWilliams** [comment]
For recent Virtuoso releases, in addition to the SQL `GRANT SPARQL_UPDATE TO "SPARQL";` role assignment, RDF Graph Security permission also needs to be set, to enable the `SPARQL` user to write to the RDF Quad Store, with the command `DB.DBA.RDF_DEFAULT_USER_PERMS_SET ('SPARQL', 7, 0);`, as detailed in this [Virtuoso user RDF Graph Level access to RDF Quad Store](https://community.openlinksw.com/t/virtuoso-user-rdf-graph-level-access-to-rdf-quad-store/4147) post.

**Comment by claudiu-cristea** [comment]
@HughWilliams, thank you for your quick reply. I assume that I need to use `SPARQL` instead of `demo`, right?

**Comment by claudiu-cristea** [comment]
It works with "`SPARQL`" as user. Thank you. Closing this...

**Comment by HughWilliams** [comment]
Yes, in your case, the user would be "`SPARQL`" and any other user accounts (apart from "`dba`") that require access to the RDF Quad Store ...

**Comment by claudiu-cristea** [comment]
@HughWilliams,  Weird, this is now regressing. I'm running:

```
root@ed682ea66c20:/opt/virtuoso-opensource/database# isql
OpenLink Virtuoso Interactive SQL (Virtuoso)
Version 07.20.3238 as of Nov 27 2023
Type HELP; for help and EXIT; to exit.
SQL> DB.DBA.RDF_DEFAULT_USER_PERMS_SET("SPARQL", 7, 0);
Connected to OpenLink Virtuoso
Driver: 07.20.3238 OpenLink Virtuoso ODBC Driver

*** Error 42S22: [Virtuoso Driver][Virtuoso Server]SQ063: No column SPARQL.
at line 1 of Top-Level:
DB.DBA.RDF_DEFAULT_USER_PERMS_SET("SPARQL", 7, 0)
```

see the "No column SPARQL" error

But on `conductor/accounts_page.vspx` I can clearly see the `SPARQL` user

**Comment by timhaynesopenlink** [comment]
Single quote not double around the `'SPARQL'`.

HTH

**Comment by claudiu-cristea** [comment]
@timhaynesopenlink, thanks, that fixed
