### ISSUE TITLE
segfault when using md5 on unbound variable in conductor sparql

### ISSUE THREAD

**Issue by nvdk** [openlink/virtuoso-opensource#121]
We experienced a segfault when executing the following query from the conductor sparql and isql interface. It was handled correctly on the public sparql endpoint.

```
PREFIX dcat: <http://www.w3.org/ns/dcat#> 
PREFIX dct: <http://purl.org/dc/terms/> 
INSERT INTO <http://my-url/distributions/> { 
?distribution a dcat:Distribution.
?distribution dct:title ?title.
} 
WHERE { 
?ds a dcat:Distribution .
?ds dct:title ?title .
BIND (IRI(CONCAT("http://my-url/distributions/",md5(?id))) AS ?distribution). }
```

Expected result (returned on public /sparql)

```
Virtuoso 37000 Error SP031: SPARQL compiler: Variable 'id' is used in the query result set but not assigned
```

Returned result

```
virtuoso-t[17175]: segfault at 7fcb10279000 ip 00007fcb9ae6ca6b sp 00007fcb278628d0 error 4 in libcrypto.so.1.0.1e[7fcb9adfe000+1b5000]
```

Virtuoso version: 6.1.8 stable

**Comment by HughWilliams** [comment]
Hi 

I would expect the same failure from all 3 interfaces.

Is anything reported in the virtuoso.log at the time of the crash ?

Is a core file created ( must have ulimit -c unlimited set) such that a gdb back trace can be obtained to show the calls leading to the crash ?

Do you have a minimal sample dataset that can be used to recreate the issue locally ?

**Comment by nvdk** [comment]
Hey hugh,

Nothing in the virtuoso.log unfortunately. I believe the issue is not dataset related, the query crashed my virtuoso server even with a clean db. No core file was created. where must i set ulimit, just from the shell?

**Comment by HughWilliams** [comment]
Hi 

OK, I have been able to recreate it locally so need need for a back trace as I have one and have reported to development to fix ...

**Comment by nvdk** [comment]
:+1:

**Comment by openlink** [comment]
A fix for this has been committed to the develop/7 branch.
