### ISSUE TITLE
Sparql Endpoint text query search

### ISSUE THREAD

**Issue by malajvan** [openlink/virtuoso-opensource#1215]
I'm trying to run this query on my instance of Virtuoso against the DBpedia Virtuoso SPARQL endpoint
```
SELECT ?s1 ?sc
WHERE {
  SERVICE <http://dbpedia.org/sparql> {
    SELECT ?s1 ((?sc * 3e-1) as ?sc) ?o1
    WHERE {
      ?s1 ?s1textp ?o1 .
      FILTER (CONTAINS(?o1, 'MARTIN AND LUTHER AND PRAISED'))
    }
    ORDER BY DESC(?sc + sql:rnk_scale(<LONG::IRI_RANK>(?s1)))
    LIMIT 50 OFFSET 0
  }
}
```

After running I receive this error message: 
> `Virtuoso RDFZZ Error DB.DBA.SPARQL_REXEC('http://dbpedia.org/sparql', ...) returned Content-Type 'text/plain' status 'HTTP/1.1 400 Bad Request`
>
> `Virtuoso 37000 Error SP031: SPARQL compiler: Free-text options can be specified only for triple patterns with special predicates, not for plain patterns`

I'm unsure about special predicates and plain patterns, what I'm trying to achieve is to do text search similar to searching on the DBpedia endpoint but instead using their endpoint as a service.
I would appreciate any guidance. Thank you!

**Comment by TallTed** [comment]
The first thing I would suggest is testing your "inner" query directly on the DBpedia endpoint, as you'll need that to work before the Federated SPARQL will work. For me, your inner query brings a different error —

> `Virtuoso 37000 Error SP031: SPARQL compiler: Variable 'sc' is used in the query result set but not assigned`

This error is correct. What do you think populates the `sc` variable in your query? I see a calculation based on `sc` in both the `SELECT` and the `ORDER BY` clauses, but nothing involving `sc` in the pattern matching `WHERE` clause.

Also note, `?o1` may match *any* datatype, but `CONTAINS` only functions over strings, so you might want to coerce the `?o1` values into strings (by changing `CONTAINS(?o1,` to `CONTAINS(STR(?o1),`), or you might want to filter out the non-literal `?o1` matches (by adding `FILTER isLiteral(?o1) .`), among other possibilities.

Please let us know if the above gets you any further...

**Comment by malajvan** [comment]
Thank you very much, your suggestions helped me a lot and eventually, I figured it out. Cheers!
