### ISSUE TITLE
Import triples from *.rdf files

### ISSUE THREAD

**Issue by claudiu-cristea** [openlink/virtuoso-opensource#1234]
What is the easiest way to import triples from `*.rdf` files when an `openlink/virtuoso-opensource-7` container's database is created?

**Comment by HughWilliams** [comment]
The Virtuoso [RDF Bulk Loader](https://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader) can be used to import `*.rdf` (RDF/XML) and other format data files into Virtuoso as detailed in the documentation link.

A Virtuoso docker container can also be set up to initially bulk load data as described in [How to Bulk Load Data into a Virtuoso Docker Instance](https://community.openlinksw.com/t/how-to-bulk-load-data-into-a-virtuoso-docker-instance/3248)...

**Comment by claudiu-cristea** [comment]
Thank you. Closing...
