### ISSUE TITLE
Crash by `CASE WHEN` and unknown identifier

### ISSUE THREAD

**Issue by suyZhong** [openlink/virtuoso-opensource#1239]
Consider the test case below.

```sql
CREATE TABLE t0(c0 INT, c1 VARCHAR(500), c2 INTEGER, PRIMARY KEY(c1));
CREATE TABLE t1(c0 INTEGER);
INSERT INTO t0(c0, c1) VALUES ('eኧ', '');

SELECT * FROM t1 LEFT  JOIN t0 ON (CASE 1 WHEN 2 THEN A(t0.c2) ELSE 3 END );
-- *** Error 08S01: [Virtuoso Driver]CL065: Lost connection to server
```

This query would cause a crash. I guess we could substitute `A` to any other unknown identifier.

I build docker image following this: https://github.com/openlink/vos-reference-docker. Kindly inform me if I did something wrong or I should provide more information (e.g. backtrace).

Here's the version:

```
[vos-reference/develop/7]

This Docker image is using the following version of Virtuoso:

Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.12-dev.3238-pthreads as of Jan 19 2024 (b361275)
Compiled for Linux (x86_64-pc-linux-gnu)
Copyright (C) 1998-2024 OpenLink Software
```

**Comment by TallTed** [comment]
We believe we've fixed this in https://github.com/openlink/virtuoso-opensource/commit/862e3141e98ee16187652ce8f0e7b6760de2be86, now in the `develop/7` branch.

Please let us know if your testing shows otherwise.
