### ISSUE TITLE
Undefined procedure DB.DBA.tweak_by_keywords.

### ISSUE THREAD

**Issue by doriantaylor** [openlink/virtuoso-opensource#124]
Installed 6.1.8, tried to navigate to Linked Data -> Graphs -> Roles Security in the Conductor. Got this:

> An error has occurred when processing "/conductor/graphs_page.vspx" page.
> SQL State     42001 
> SQL Message   
> 
> SR185: Undefined procedure DB.DBA.tweak_by_keywords.

I've tried searching several versions of the source and I can only find references to tweak_by_keywords in binsrc/yacutia/graphs_{page,{roles,users}_security}.vspx but no definition of it to be found in the source anywhere. Not even in 7.x or master.

**Comment by HughWilliams** [comment]
I have been able to recreate this issue and reported to development to fix. Will let you know when it is available ...

**Comment by doriantaylor** [comment]
Thanks!

**Comment by openlink** [comment]
The missing function has been added to develop/7 and will be part of the upcoming new release of VOS 7
