### ISSUE TITLE
Certain SPARQL query causes Virtuoso to segfault

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#1245]
The following SPARQL query:
```sparql
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT DISTINCT ?publisher ?dataset ?label
WHERE {
GRAPH ?g { 
    ?dataset a dcat:Dataset; 
          dct:title ?label; 
          dct:publisher/foaf:name ?publisher . 
} 
} 
LIMIT 100
```
causes Virtuoso (after update from 178d62b3c1ddad323ee5ecbbb9ea3d7b7253a6b0 to 33f93b139ccbab42282bd36e81f301699320ae58) to segfault on 2 out of 3 tested instances.
From `/var/log/syslog`:
```
kernel: [491374.364584] show_signal_msg: 10 callbacks suppressed
Feb 15 08:29:53 oha-proto-02 kernel: [491374.364588] virtuoso-t[97684]: segfault at 7f106a8d1fe8 ip 0000559d92160054 sp 00007f106a8d1fd0 error 6 in virtuoso-t[559d91f22000+836000]
Feb 15 08:29:53 oha-proto-02 kernel: [491374.364597] Code: 55 e0 48 89 02 48 8b 45 f8 48 89 45 e0 48 83 7d e0 00 75 bb 48 8b 45 e8 c9 c3 f3 0f 1e fa 55 48 89 e5 53 48 81 ec 88 00 00 00 <48> 89 7d 88 48 89 75 80 48 89 95 78 ff ff ff 48 83 7d 80 00 75 0a
```

After rollback to 178d62b3c1ddad323ee5ecbbb9ea3d7b7253a6b0 the query runs OK again.

**Comment by imitko** [comment]
@jakubklimek 

The query crash is in execution, as it is compiled without a problem.  In order to reproduce and fix it, we will need at very least call stack from core dump or a dataset on which the crash occurs.

**Comment by jakubklimek** [comment]
Of course. Please see https://oha02.dia.gov.cz/soubor/db01.zip
