### ISSUE TITLE
Query returns nothing in group graph

### ISSUE THREAD

**Issue by mhoangvslev** [openlink/virtuoso-opensource#1277]
# What I want

Since I can not perform `SELECT * FROM g1, g2, ...g100`, I want to use `Graph Groups` to perform  `SELECT * FROM biggroup` where `biggroup = g1, g2, ...g100`.

# What I did:

1. I executed the following commands
   ```sql
   DB.DBA.RDF_GRAPH_GROUP_DROP('http://www.batch0.fr/', 0);
   DB.DBA.RDF_GRAPH_GROUP_CREATE('http://www.batch0.fr/',0);
   DB.DBA.RDF_GRAPH_USER_PERMS_SET ('http://www.batch0.fr/', 'nobody', 1);
   DB.DBA.RDF_GRAPH_GROUP_INS('http://www.batch0.fr/', 'http://www.vendor0.fr/');
   DB.DBA.RDF_GRAPH_GROUP_INS('http://www.batch0.fr/', 'http://www.vendor1.fr/');
   DB.DBA.RDF_GRAPH_GROUP_INS('http://www.batch0.fr/', 'http://www.vendor2.fr/');
   DB.DBA.RDF_GRAPH_GROUP_INS('http://www.batch0.fr/', 'http://www.vendor3.fr/');
   DB.DBA.RDF_GRAPH_GROUP_INS('http://www.batch0.fr/', 'http://www.vendor4.fr/');
   ```

2. When I performed the following query, I have no results:
   ```sparql
   SELECT * 
   FROM <http://www.batch0.fr/>
   WHERE {
       ?s ?p ?o 
   } 
   LIMIT 10
   ```

# Virtuoso files

- virtuoso.db: https://zenodo.org/records/8339384/files/fedshop-virtuoso.db?download=1
- virtuoso.ini: https://zenodo.org/records/10913110/files/virtuoso.ini?download=1

**Comment by imitko** [comment]
@mhoangvslev 

You should execute
`DB.DBA.RDF_GRAPH_USER_PERMS_SET ('http://www.batch0.fr/', 'nobody', 9)`
i.e., read & graph group member list permitted.

HTH

**Comment by mhoangvslev** [comment]
@imitko Thank you for your prompt reaction!

When I read this line from the [doc](https://docs.openlinksw.com/virtuoso/fn_rdf_graph_user_perms_set/), I feel confused:
> Bit 8 allows to obtain list of members of graph group; an IRI can be used as graph IRI and as graph group IRI at the same time so bit 8 can be freely combined with any of bits 1, 2 or 4.

My understanding from the doc for [RDF Graph Groups](https://docs.openlinksw.com/virtuoso/rdfgraphsecuritygroups/) is that its sole purpose is to provide a convenient way to query specific subset of graphs, as described here:
> It would be nice to create named lists of graphs and a clause like "SELECT from all graph names of the specified list". "Graph groups" serve for this purpose. That is Virtuoso-specific SPARQL extension that let create a named list of IRIs such that if name of the list is used in FROM clause like IRI of default graph then it is equivalent to list of FROM clauses, one clause for each item of the list.

I think the line `DB.DBA.RDF_GRAPH_USER_PERMS_SET (graph_group_iri, 'nobody', 9)` should be added to the `DB.DBA.RDF_GRAPH_GROUP_CREATE` procedure. If not possible, for security reason, it should be mentioned in the document.
