### ISSUE TITLE
Cannot make VOS7

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#129]
Cannot make VOS7 since bb4a14c0aa08a3b1180c5255cfd4cf25f8a4c0b4

<pre><code>Making install in Dk
make[2]: Entering directory `/home/klimek/virtuoso-opensource/libsrc/Dk'
/bin/bash ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -fno-strict-aliasing -O2  -Wall  -DNDEBUG -DPOINTER_64   -I/home/klimek/virtuoso-opensource/libsrc/Xml.new  -DOPENSSL_NO_KRB5 -Dlinux -D_GNU_SOURCE -DFILE64 -D_LARGEFILE64_SOURCE   -I../../libsrc -g -O2 -MT libdksrv_la-Dkmem.lo -MD -MP -MF .deps/libdksrv_la-Dkmem.Tpo -c -o libdksrv_la-Dkmem.lo `test -f 'Dkmem.c' || echo './'`Dkmem.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -fno-strict-aliasing -O2 -Wall -DNDEBUG -DPOINTER_64 -I/home/klimek/virtuoso-opensource/libsrc/Xml.new -DOPENSSL_NO_KRB5 -Dlinux -D_GNU_SOURCE -DFILE64 -D_LARGEFILE64_SOURCE -I../../libsrc -g -O2 -MT libdksrv_la-Dkmem.lo -MD -MP -MF .deps/libdksrv_la-Dkmem.Tpo -c Dkmem.c  -fPIC -DPIC -o .libs/libdksrv_la-Dkmem.o
Dkmem.c:110:1: error: conflicting types for 'rdtsc'
In file included from ../../libsrc/Dk.h:79:0,
                 from Dkmem.c:27:
../../libsrc/Dk/Dkutil.h:51:17: note: previous declaration of 'rdtsc' was here
make[2]: *** [libdksrv_la-Dkmem.lo] Error 1
make[2]: Leaving directory `/home/klimek/virtuoso-opensource/libsrc/Dk'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/klimek/virtuoso-opensource/libsrc'
make: *** [install-recursive] Error 1
</code></pre>

**Comment by HughWilliams** [comment]
I have been able to recreate this we are looking into it ...

**Comment by HughWilliams** [comment]
This issue has been fixed in develop/7, see:

https://github.com/openlink/virtuoso-opensource/commit/58a84504919b39d802df541d2f76a54f1bfa3ba7
