### ISSUE TITLE
How to expose a R/O SPARQL endpoint?

### ISSUE THREAD

**Issue by claudiu-cristea** [openlink/virtuoso-opensource#1297]
Our application is interacting with Virtuoso by making API calls (`GET` & `POST`) to the SPARQL endpoint, `http://virtuoso:8890/sparql`. This endpoint is not publicly accessible. We want to offer a public endpoint, say `https://virtuoso/sparql` (port 443), but we want to allow only read queries. No inserts, no deletions, no updates. Only `SELECT`, `ASK`, etc...

**Comment by HughWilliams** [comment]
The Virtuoso default `~/sparql` endpoint is read-only by default, and the default `~/sparql-auth` endpoint challenges for digest authentication, which, if successful, then allows read and/or write access depending on what SPARQL roles (e.g., `SPARQL_SELECT`, `SPARQL_UPDATE`) the authenticated user has been assigned in the database.

**Comment by claudiu-cristea** [comment]
Tested `/sparql-auth` and works with a new user having `SPARQL_SELECT` permission. Thank you!
