### ISSUE TITLE
Windows installer gets scary error

### ISSUE THREAD

**Issue by stevereiner** [openlink/virtuoso-opensource#1300]
In running 7.2.13 or previous 7.2.12, you get a security error message about a suspicious action.
This is on Windows 11. I have Norton 360. I disabled Norton auto protect and firewall and still get it.
I isolated it to client connectivity kit option (if do full install or client only, you get it; if do server only, you don't get it.)

Get an error msg, `OpenLink.Data.Virtuoso.dll`
> InstallAssembly failed, access is denied

![error](https://github.com/openlink/virtuoso-opensource/assets/921792/35ad58d4-02a1-4f84-a42b-e2870e6f4b2f)

Note some part of Norton Protection must still be running when turn off virus protection in UI and turn off firewall in UI

Get a Norton Security Threat Blocked error msg
![blocked](https://github.com/openlink/virtuoso-opensource/assets/921792/321c6b40-2dd5-4df2-b9eb-11a1a4449440)

**View Details**
> Category: Data Protector
> Date & Time,Risk,Activity,Status,Recommended Action,Status,Program Path,Program Name,Date & Time,Action Observed,Target
> 6/14/2024 4:24:12 PM,High,Data Protector blocked a suspicious action by `Virtuoso_Open_Source_for_Windows.tmp`,Action Blocked,No Action Required,Action Blocked,`C:\Users\sreiner\AppData\Local\Temp\is-EIR4O.tmp\Virtuoso_Open_Source_for_Windows.tmp`,`Virtuoso_Open_Source_for_Windows.tmp`,6/14/2024 4:24:12 PM,Suspicious process attempted to open a file protected by Data Protector,`C:\Windows\assembly\GACLock.dat`

![details](https://github.com/openlink/virtuoso-opensource/assets/921792/7d9669c3-62d2-42a5-9334-68183e1edda9)

Note that if you choose _skip this file (not recommended)_, 
the DLL still gets installed in the `Virtuoso OpenSource 7.2\lib` dir

**Comment by pkleef** [comment]
Development is looking into this.

**Comment by pkleef** [comment]
## Description
The  `OpenLink.Data.Virtuoso.dll` is a `.NET provider` we created, so users can access their Virtuoso Database from within the [Microsoft .NET Framework](https://en.wikipedia.org/wiki/.NET). 

As part of the installation of this `.DLL` file, we set a flag for this file to be installed in the [Global Assembly Cache (GAC)](https://en.wikipedia.org/wiki/Global_Assembly_Cache) on your machine. This cache enables the `.NET runtime` to use several driver (or assembly) versions side-by-side, avoiding the old [.DLL hell](https://en.wikipedia.org/wiki/DLL_hell).

After the `OpenLink.Data.Virtuoso.dll` is installed to the `Virtuoso OpenSource 7.2\lib` directory on your filesystem, the installer attempts to register this file to the cache, by adding it to the GAC directory `C:\Windows\assembly\` using  standard Microsoft API calls; as part of these calls, it tries to open the `C:\Windows\assembly\GACLock.dat` file. 

It is at this point that the Norton Data Protector tool decides to give you an alert. As the description of the alert is rather vague, I can only assume your Norton tool generally guards the `assembly` directory against possible attack from malware. 

At this point you can choose to `Skip this file (not recommended)` which will only skip the `InstallAssembly (into the GAC)` step, to continue the installation to its conclusion. This will leave you with a fully working installation of Virtuoso Open Source Edition.

Please note that your Norton Protector Tool does **NOT** flag `OpenLink.Data.Virtuoso.dll` to contain a virus, as that would have resulted in a very different alert.

## Conclusion
As there are several [pitfalls to using this GAC cache](https://en.wikipedia.org/wiki/Global_Assembly_Cache#Pitfalls), we have decided to simply remove the `GAC installation flag` from our installer. This will not affect the usability of the `OpenLink.Data.Virtuoso.dll` driver if you are actually using programs written in `.NET`.

I will notify you when we have replaced the 7.2.13 installer for Windows on our release page.

**Comment by pkleef** [comment]
I uploaded a [new installer for Windows](https://github.com/openlink/virtuoso-opensource/releases/download/v7.2.13/Virtuoso_Open_Source_for_Windows.exe) that fixes this `GAC cache` issue.
Please download it and let us know if your `Norton Tool` is now happy.

**Comment by stevereiner** [comment]
The full option  installs fine on windows 11 with Norton with no error messages. The conductor runs.

**Comment by stevereiner** [comment]
comment

**Comment by stevereiner** [comment]
The full option installs fine on windows 11 with Norton with no error messages. The conductor runs.

**Comment by TallTed** [comment]
Closing based on https://github.com/openlink/virtuoso-opensource/issues/1300#issuecomment-2178358941
