### ISSUE TITLE
How to convert CSV to RDF with PL procedure using DB.DBA.CSVREAD Function?

### ISSUE THREAD

**Issue by candlecao** [openlink/virtuoso-opensource#1305]
I asked this question to ChatGPT 4o. It answered:

-----

#### Step 1
```sql
-- Create a table to hold the CSV data
CREATE TABLE csv_data (
    column1 VARCHAR(100),
    column2 VARCHAR(100),
    column3 VARCHAR(100)
);

-- Load the CSV data into the table
DB.DBA.CSVREAD('/path/to/your/csv/data.csv', 'csv_data', ',', '"');
```
#### Step 2
Next, you needs to create a PL procedure that reads the data from the table and converts it into RDF triples. Here’s an example of a PL procedure:
```sql
CREATE PROCEDURE csv_to_rdf()
{
    DECLARE c1 VARCHAR;
    DECLARE c2 VARCHAR;
    DECLARE c3 VARCHAR;

    FOR (SELECT column1, column2, column3 FROM csv_data)
    {
        c1 := column1;
        c2 := column2;
        c3 := column3;

        -- Insert RDF triples into the Virtuoso RDF store
        DB.DBA.RDF_INSERT (IRI_TO_ID('http://example.org/resource/' || c1),
                           IRI_TO_ID('http://example.org/property/hasColumn2'),
                           c2);
        DB.DBA.RDF_INSERT (IRI_TO_ID('http://example.org/resource/' || c1),
                           IRI_TO_ID('http://example.org/property/hasColumn3'),
                           c3);
    }
}
```
#### Step 3
Finally, execute the PL procedure to convert the CSV data to RDF:
```
CALL csv_to_rdf();
```

-----

My questions are:

1. When I was executing the `DB.DBA.CSVREAD()` function, it prompted `Undefined procedure DB.DBA.CSVREAD`. I don't know how to activate the `CSVREAD()` function despite some trials. Then I just `INSERT` data using SQL as a substitute method.

2. When I executed the scripts of Step 2 in ISQL, it prompted:
   ```
   SQLState: 37000
   Message: SQ074: Line 8: syntax error...
   ```

Anyway, could somebody help me out?

**Comment by candlecao** [comment]
Here is another answer from Customer Support Assistant from [https://virtuoso.openlinksw.com/](https://virtuoso.openlinksw.com/):

-----

#### 1. Prepare the CSV File:
Ensure your CSV file is properly formatted and accessible from the Virtuoso server.

#### 2. Create a Procedure to Read CSV:
Write a Virtuoso PL procedure that uses the `DB.DBA.CSVREAD` function to read the CSV file.

#### 3. Convert CSV Data to RDF:
Within the procedure, convert the CSV data to RDF triples and insert them into the Virtuoso RDF store.

Here is an example of how you can achieve this:

```sql
-- Create a procedure to read CSV and convert to RDF
CREATE PROCEDURE CSV_to_RDF (IN csv_file VARCHAR)
{
  DECLARE c INT;
  DECLARE row VARCHAR;
  DECLARE col1 VARCHAR;
  DECLARE col2 VARCHAR;
  DECLARE col3 VARCHAR;

  -- Open the CSV file
  c := DB.DBA.CSVREAD (csv_file, ',', '"');

  -- Loop through each row in the CSV file
  WHILE (row := DB.DBA.CSVNEXT (c)) IS NOT NULL
  DO
    -- Split the row into columns
    col1 := DB.DBA.CSVGET (c, 1);
    col2 := DB.DBA.CSVGET (c, 2);
    col3 := DB.DBA.CSVGET (c, 3);

    -- Insert RDF triples into the RDF store
    DB.DBA.RDF_INSERT_TRIPLE (
      iri_to_id ('http://example.org/resource/' || col1),
      iri_to_id ('http://example.org/property/hasValue'),
      iri_to_id ('http://example.org/resource/' || col2)
    );

    DB.DBA.RDF_INSERT_TRIPLE (
      iri_to_id ('http://example.org/resource/' || col1),
      iri_to_id ('http://example.org/property/hasDescription'),
      col3
    );
  END;

  -- Close the CSV file
  DB.DBA.CSVCLOSE (c);
};

-- Call the procedure with the path to your CSV file
CALL CSV_to_RDF ('/path/to/your/file.csv');
```

### Explanation:

#### 1. Procedure Definition:

The procedure `CSV_to_RDF` takes the path to the CSV file as an input parameter.

#### 2. Open CSV File:

`DB.DBA.CSVREAD` function is used to open the CSV file.

#### 3. Read and Process Rows:

A loop reads each row using `DB.DBA.CSVNEXT`.
Each row is split into columns using `DB.DBA.CSVGET`.

#### 4. Insert RDF Triples:

RDF triples are inserted into the RDF store using `DB.DBA.RDF_INSERT_TRIPLE`.

#### 5. Close CSV File:

The CSV file is closed using `DB.DBA.CSVCLOSE`.

- Note:

> Adjust the column indices and RDF properties according to your CSV structure and RDF schema.<br>
> Ensure the CSV file path is correct and accessible from the Virtuoso server.

If you need further assistance or a more specific guide, please provide additional details about your CSV structure and the desired RDF schema.

-----

**Comment by HughWilliams** [comment]
Why are you asking about the `DB.DBA.CSVREAD` function, as that does not exist in Virtuoso?

The document [Virtuoso HowTo: Generating Linked Data from CSV version of Northwind Database](https://community.openlinksw.com/t/virtuoso-howto-generating-linked-data-from-csv-version-of-northwind-database/941) is an example of how to convert a CSV file to RDF Linked Data.

**Comment by candlecao** [comment]
Oh, do you mean `DB.DBA.CSVREAD` doesn't exist at all in Virtuoso!? Oh, is that another hallucination by Chat Gpt 4o which was asked about this by me!?

I checked [Virtuoso HowTo: Generating Linked Data from CSV version of Northwind Database](https://community.openlinksw.com/t/virtuoso-howto-generating-linked-data-from-csv-version-of-northwind-database/941) you shared with me. It seems, the conversion from CSV to RDF is still returning to and relying on other methods like Sponger, R2RML:
![image](https://github.com/openlink/virtuoso-opensource/assets/63447377/2620ddf7-7192-48fd-98bf-cc21be047890)
So I can not only rely on an "independent method of PL Procedure" to realize CSV2RDF. Is my understanding right?

(My aim is to figure out how many ways actually exist to convert from CSV2RDF: [Several Ways of CSV to Virtuoso LinkedData](https://github.com/DDMAL/linkedmusic-datalake/wiki/Several-Ways-of-CSV-to-Virtuoso-LinkedData%E2%80%90%E2%80%90account-for-the-2nd-way-we-are-in) (updating-by-adding-more-ways).)

Thank you a lot!

**Comment by kidehen** [comment]
What prompt did you provide to ChatGPT?

**Comment by candlecao** [comment]
I prompted "What are different ways to import CSV files with proper URIs into Virtuoso RDF graph database".

**Comment by HughWilliams** [comment]
I get a completely different answer when to the `What are different ways to import CSV files with proper URIs into Virtuoso RDF graph database` prompt question when I ask [ChatGPT](https://chatgpt.com/) or the [Virtuoso Customer Support Assistant](https://virtuoso.openlinksw.com/), which responds with:

> Different Ways to Import CSV Files with Proper URIs into Virtuoso RDF Graph Database
> Using Virtuoso's Bulk Loader:
> 
> Virtuoso provides a bulk loader utility that can be used to import CSV files into the RDF graph database. This utility can map CSV data to RDF triples and load them into a specified graph.
> Using SPARQL INSERT Queries:
> 
> You can write SPARQL INSERT queries to manually insert data from CSV files into the RDF graph. This method is more flexible but requires more effort to parse the CSV and construct the appropriate triples.
> Using OpenLink Data Importer:
> 
> OpenLink Data Importer is a tool that can be used to import various data formats, including CSV, into Virtuoso. It provides a user-friendly interface for mapping CSV columns to RDF properties and generating URIs.
> Using Custom Scripts:
> 
> You can write custom scripts in languages like Python, Java, or any other language that supports HTTP requests to read CSV files, generate RDF triples, and use Virtuoso's SPARQL endpoint to insert the data.
> Using RDFizers:
> 
> RDFizers are tools that convert various data formats, including CSV, into RDF. These tools can be used to preprocess the CSV files into RDF format before importing them into Virtuoso.
> 
> Would you like a step-by-step guide on any of these methods?
> 

With regards to your question, "So I can not only rely on an "independent method of PL Procedure" to realize CSV2RDF. Is my understanding right?", you can write your own PL Procedure for transforming CSV files to RDF, which is essentially what the Virtuoso [Sponger Middleware](https://vos.openlinksw.com/owiki/wiki/VOS/VirtSponger) cartridges are. There is also a [Sponger Programming Guide](https://vos.openlinksw.com/owiki/wiki/VOS/VirtSpongerCartridgeProgrammersGuide) which details how to create custom cartridges that can be hooked into the Virtuoso Sponger processing pipeline.

**Comment by kidehen** [comment]
> I prompted "What are different ways to import CSV files with proper URIs into Virtuoso RDF graph database".

I've updated the Virtuoso Support Assistant CustomGPT with regards to your prompt. 

Links:

1. https://chatgpt.com/share/9f6897db-17ff-4b3f-b5fc-f244e83c055c -- Response via our Virtuoso Support Assistant CustomGPT
2. https://linkeddata.uriburner.com/chat/?chat_id=s-5dtDDhLZAe6Km6FJz2U8Li3oxct8XcboFc2iYrtjbvsr -- Response via our OPAL instance, which mirrors what you will see via https://virtuoso.openlinksw.com's chat window

**Comment by candlecao** [comment]
OK. Thank you very much!
