### ISSUE TITLE
multiple `BNODE()` calls result in non-distinct blank nodes (not SPARQL 1.1 standard compliant)

### ISSUE THREAD

**Issue by jmkeil** [openlink/virtuoso-opensource#1310]
The query `ASK { FILTER (BNODE() = BNODE()) }` ([try](https://dbpedia.org/sparql?query=ASK+{+FILTER+(BNODE()+%3D+BNODE())+})) returns `true` on Virtuoso version 08.03.3330 (879a32f2c3).

According to the [standard](https://www.w3.org/TR/sparql11-query/#func-bnode), it should return `false`:
> If the no argument form is used, every call results in a distinct blank node.

**Comment by HughWilliams** [comment]
we are looking into this ...

**Comment by pkleef** [comment]
This has been fixed in the latest commercial release 08.03.3332 that was released in September 2024. 

Please contact our [support team](mailto:support@openlinksw.com)
