### ISSUE TITLE
build fails with GCC 14 (-Werror=incompatible-pointer-types)

### ISSUE THREAD

**Issue by anbe42** [openlink/virtuoso-opensource#1312]
GCC 14 has turned some warnings into errors by default.

First failure for 7.2.13:
```
Dksesstr.c: In function 'strses_chars_length':
Dksesstr.c:710:41: error: passing argument 2 of 'virt_mbsnrtowcs' from incompatible pointer type [-Wincompatible-pointer-types]
  710 |       last_len = virt_mbsnrtowcs (NULL, &ptr, ses->dks_out_fill, 0, &mb);
      |                                         ^~~~
      |                                         |
      |                                         unsigned char **
In file included from ../../libsrc/libutil.h:41,
                 from Dksesstr.c:29:
../../libsrc/util/utf8funs.h:52:68: note: expected 'const unsigned char **' but argument is of type 'unsigned char **'
   52 | extern size_t virt_mbsnrtowcs (wchar_t *dst, const unsigned char **src, size_t nmc, size_t len, virt_mbstate_t *ps);
      |                                              ~~~~~~~~~~~~~~~~~~~~~~^~~
```

Complete build log with all GCC 14 failures for 7.2.12:
http://qa-logs.debian.net/2024/07/01/virtuoso-opensource_7.2.12+dfsg-0.2_unstable_gccexp.log

**Comment by openlink** [comment]
We will have a look.

What version of Debian are you using? 

Also be aware that 7.2.13 is the latest stable release of VOS.

**Comment by david-geiger** [comment]
Hi,

Same build issue here on Mageia Cauldron with latest 7.2.13 release!

Regards,
David

**Comment by pkleef** [comment]
A [patch for this](https://github.com/openlink/virtuoso-opensource/commit/0ffbf1b39a2ec6e5caba76c95c2eb26c273cf852) will be part of VOS 7.2.14 which [will be released](https://github.com/openlink/virtuoso-opensource/releases/) in the next week or so.
