### ISSUE TITLE
Is there a method by which we can convert the xsd:datetime format to the day of week?

### ISSUE THREAD

**Issue by candlecao** [openlink/virtuoso-opensource#1316]
For example,
"2013-02-12T13:11:39"
can be mapped to Tuesday.

Can we use SPARQL to realize it in Virtuoso?

**Comment by TallTed** [comment]
SPARQL doesn't have a name-of-day function, but given that your SPARQL endpoint is a [Virtuoso](https://virtuoso.openlinksw.com/) instance, you can leverage its SQL functions, specifically, [`dayname()`](https://docs.openlinksw.com/virtuoso/fn_dayname/). 

Here's a [query you can run against DBpedia](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=SELECT%0D%0A+++++++++++++++++++++++++++++++++++%3Fbirthdate+%0D%0A++++%28+bif%3Adayname%28%3Fbirthdate%29++AS++%3Fdayname+%29%0D%0AWHERE%0D%0A+++%7B++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FKamala_Harris%3E%0D%0A+++++++++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FbirthDate%3E++%3Fbirthdate+%0D%0A+++%7D%0D%0A&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on) --
```sparql
SELECT
                                   ?birthdate 
    ( bif:dayname(?birthdate)  AS  ?dayname )
WHERE
   {  <http://dbpedia.org/resource/Kamala_Harris>
         <http://dbpedia.org/ontology/birthDate>  ?birthdate 
   }
```
-- which will get [Kamala Harris' birthdate and day](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=SELECT%0D%0A+++++++++++++++++++++++++++++++++++%3Fbirthdate+%0D%0A++++%28+bif%3Adayname%28%3Fbirthdate%29++AS++%3Fdayname+%29%0D%0AWHERE%0D%0A+++%7B++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FKamala_Harris%3E%0D%0A+++++++++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FbirthDate%3E++%3Fbirthdate+%0D%0A+++%7D%0D%0A&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on) --
```
birthdate    dayname
1964-10-20   Tuesday
```

**Comment by candlecao** [comment]
Thank you very much!
