### ISSUE TITLE
How to import CIDOC-CRM ontology into Virtuoso?

### ISSUE THREAD

**Issue by fishfree** [openlink/virtuoso-opensource#1317]
On page /conductor/rdf_import.vspx of the Conductor, I'd like to import [CIDOC-CRM owl ontology](https://github.com/erlangen-crm/ecrm/raw/master/ecrm_current.owl) as below:
![image](https://github.com/user-attachments/assets/83b2be1c-178b-4360-8210-85308ef2d250)
After clicking Upload button, the page splashed and I then access the SPARQL endpoint as below:
![image](https://github.com/user-attachments/assets/2c1afd09-caf7-4006-82a8-ad5ef29cee00)
No CIDCO-CRM ontology related stuff showed up.

But the https://github.com/schemaorg/schemaorg/raw/main/data/releases/27.0/schemaorg-all-https.ttl  can be successfully imported.

**Comment by HughWilliams** [comment]
The [CIDOC-CRM owl ontology](https://github.com/erlangen-crm/ecrm/raw/master/ecrm_current.owl) dataset loads successfully for me in my Virtuoso open source instance:

<img width="1167" alt="Screenshot 2024-09-12 at 12 53 32" src="https://github.com/user-attachments/assets/a67125f5-5809-49b8-aa8d-11a190f7008f">

and I can query the data:

<img width="1168" alt="Screenshot 2024-09-12 at 12 54 42" src="https://github.com/user-attachments/assets/a46bde65-e112-4c82-b6f6-1535f61292a5">

<img width="953" alt="Screenshot 2024-09-12 at 12 54 59" src="https://github.com/user-attachments/assets/697bff7e-2fb5-4f99-9812-38435f101a6c">

I note you are using an old Virtuoso build from 2017 and would recommend upgrading to the latest build ...

**Comment by fishfree** [comment]
@HughWilliams Thank you! My fault. I still don't understand the SPARQL.
