### ISSUE TITLE
GeoSPARQL support for cartesian 2D & 3D coordinate systems

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#1318]
Does Virtuoso have GeoSPARQL support for Cartesian 2D & 3D coordinate systems?

**Comment by HughWilliams** [comment]
Yes, Virtuoso does support 2D & 3D coordinate systems.

**Comment by ebremer** [comment]
@HughWilliams Fantastic!  What are best URLs for the 2D and 3D Cartesian coordinate systems?
I am working down at a cellular scale so measurements are general in microns (um).
I also often work at just a pixel level with x,y and x,y,z just specified as integers.

**Comment by HughWilliams** [comment]
The following documentation exists on the Virtuoso GeoSPARQL and GeoSpatial support:

* [Virtuoso GeoSPARQL Demo Server](https://community.openlinksw.com/t/virtuoso-geosparql-demo-server/223) 
* [Virtuoso Geospatial Enhancements](https://vos.openlinksw.com/owiki/wiki/VOS/VirtGeoSPARQLEnhancementDocs)
