### ISSUE TITLE
Virtuoso Restart Overwrites custom dbpedia_dav.vad

### ISSUE THREAD

**Issue by alexandrutodor** [openlink/virtuoso-opensource#132]
Hi, I have a custom dbpedia_dav.vad compiled from the 1.4.0 that is on Github. However, at each restart (no crash, just a manual stop/ start) of virtuoso it gets overwritten with the 1.4.26 version. My version of virtuoso is 07.00.3203, compiled from source, from the 7 Stable branch and no config modifications. This behaviour is anoying, any idea how I could work around it.

**Comment by HughWilliams** [comment]
I presume you must have a 1.4.26 version of the the dbpedia_dav.vad file in the "VADInstallDir"  INI file setting of your virtuoso.ini file, which is being installed each time the server starts which is standard behaviour ie a new version will always overwrite and older version on startup. To prevent his simply remover the dbpedia_dav.vad file in the "VADInstallDir" location ...

**Comment by alexandrutodor** [comment]
Thank you so much, I didn't know about that config option, this is going to spare me some headaches.
