### ISSUE TITLE
How can a custom SRS be added to a Virtuoso instance?

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#1323]
How can a custom SRS be added to a Virtuoso instance so that I can specify things like the following:

```
:object231 :hasPolygon "<https://customsrs.com/deadbeef84> POINT(20001 30000)"^^ogcgs:wktLiteral .
```
and that the geosparql spatial operators will know how that custom SRS is specified?

**Comment by HughWilliams** [comment]
@ebremer — The Virtuoso Open Source [proj4 Plug-in](https://vos.openlinksw.com/owiki/wiki/VOS/VirtGeoSPARQLEnhancementDocs?#Open%20Source%20proj4%20Plug-in) page details how additional SRS (a/k/a CRS) in the well-known SRID format can be added to Virtuoso in the `DB.DBA.SYS_PROJ4_SRIDS` table using `DB.DBA.PROJ4_LOAD_SYS_SRIDS()` and associated functions.

**Comment by ebremer** [comment]
@HughWilliams thank you!
