### ISSUE TITLE
Negligible? difference in SPARQL query means huge performance issue

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#133]
In 74ed20c7a3fbef3783f5e07fbfb88a8a1ebb42b7 (develop/7) when I use this query:

<pre><code>PREFIX s: &lt;http://schema.org/&gt;
PREFIX skos: &lt;http://www.w3.org/2004/02/skos/core#&gt;
CONSTRUCT {
 ?b s:geo ?c ;
      s:title ?title;
      s:description ?desc ;
      &lt;http://linked.opendata.cz/ontology/domain/seznam.gov.cz/ovm/typSubjektu&gt; ?type.
?type skos:prefLabel ?typeText ;
          ?p ?o .
?c s:latitude ?lat; s:longitude ?lng .
} WHERE {
 ?b s:name ?title ;
      &lt;http://linked.opendata.cz/ontology/domain/seznam.gov.cz/ovm/typSubjektu&gt; ?type ;
      s:address ?address .
?address s:streetAddress ?street;
      s:postalCode ?psc;
      s:addressRegion ?region;
      s:addressLocality ?locality.
?type skos:prefLabel ?typeText ;
          ?p ?o .
graph &lt;http://linked.opendata.cz/resource/dataset/geocoordinates/google/schema.org&gt; {
          ?c s:longitude ?lng; 
              s:latitude ?lat ; 
              ^s:geo ?address.
}
BIND(concat(?typeText, ": ", ?title, """
""",?street, """
""", ?region ,"""
""", ?locality, """
""", ?psc ) as ?desc)
}</code></pre>

it takes forever to answer.

When I omit the <code>?p</code> and <code>?o</code> variables, the query evaluates within seconds:

<pre><code>PREFIX s: &lt;http://schema.org/&gt;
PREFIX skos: &lt;http://www.w3.org/2004/02/skos/core#&gt;
CONSTRUCT {
 ?b s:geo ?c ;
      s:title ?title;
      s:description ?desc ;
      &lt;http://linked.opendata.cz/ontology/domain/seznam.gov.cz/ovm/typSubjektu&gt; ?type.
?type skos:prefLabel ?typeText .
?c s:latitude ?lat; s:longitude ?lng .
} WHERE {
 ?b s:name ?title ;
      &lt;http://linked.opendata.cz/ontology/domain/seznam.gov.cz/ovm/typSubjektu&gt; ?type ;
      s:address ?address .
?address s:streetAddress ?street;
      s:postalCode ?psc;
      s:addressRegion ?region;
      s:addressLocality ?locality.
?type skos:prefLabel ?typeText .
graph &lt;http://linked.opendata.cz/resource/dataset/geocoordinates/google/schema.org&gt; {
          ?c s:longitude ?lng; 
              s:latitude ?lat ; 
              ^s:geo ?address.
}
BIND(concat(?typeText, ": ", ?title, """
""",?street, """
""", ?region ,"""
""", ?locality, """
""", ?psc ) as ?desc)
}</code></pre>

Each of the <code>?type</code> skos:Concepts has approx. 3 more triples that would be returned by the <code>?p</code> and <code>?o</code> variables.

In addition, it seems that even adding just one more property like this causes this performance issue:

<pre><code>PREFIX s: &lt;http://schema.org/&gt;
PREFIX skos: &lt;http://www.w3.org/2004/02/skos/core#&gt;
CONSTRUCT {
 ?b s:geo ?c ;
      s:title ?title;
      s:description ?desc ;
      &lt;http://linked.opendata.cz/ontology/domain/seznam.gov.cz/ovm/typSubjektu&gt; ?type;
      &lt;http://linked.opendata.cz/ontology/domain/seznam.gov.cz/ovm/datumOvereni&gt; ?datum .
?type skos:prefLabel ?typeText .
?c s:latitude ?lat; s:longitude ?lng .
} WHERE {
 ?b s:name ?title ;
      &lt;http://linked.opendata.cz/ontology/domain/seznam.gov.cz/ovm/typSubjektu&gt; ?type ;
      &lt;http://linked.opendata.cz/ontology/domain/seznam.gov.cz/ovm/datumOvereni&gt; ?datum ;
      s:address ?address .
?address s:streetAddress ?street;
      s:postalCode ?psc;
      s:addressRegion ?region;
      s:addressLocality ?locality.
?type skos:prefLabel ?typeText .
graph &lt;http://linked.opendata.cz/resource/dataset/geocoordinates/google/schema.org&gt; {
          ?c s:longitude ?lng; 
              s:latitude ?lat ; 
              ^s:geo ?address.
}
BIND(concat(?typeText, ": ", ?title, """
""",?street, """
""", ?region ,"""
""", ?locality, """
""", ?psc ) as ?desc)
}</code></pre>

**Comment by openlink** [comment]
Try using the absolute latest version of VOS 7 from the develop/7 branch and try the method in this document as it will report both compiler and query execution plans and times on the various queries, so we can help analyze them:

http://docs.openlinksw.com/virtuoso/databaseadmsrv.html#readingqueryprofile

**Comment by jakubklimek** [comment]
Well, in 788bb9da315b19605856091726079338320e6212 the queries work as expected again. So I guess there is no need for the profiling of this one?

**Comment by openlink** [comment]
No if they work fine with this latest release this issue can be regarded as resolved. Thanks for your quick feedback.
