### ISSUE TITLE
Dynamic CRS registration

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#1330]
Any thoughts on adding a custom CRS dynamically to a Virtuoso instance through a dereferenceable URI like this one for [epsg:3395](https://epsg.io/3395.proj4)?

I ask because much of the spatial data I use, it would require potentially a custom CRS per reference image as each image has (potentially) a different scaling per dimension.   I can use a known Cartesian CRS in the WKT literals and then use units:GridSpacing in the spatial functions and get the right numbers out (#1320) in Virtuoso, but I don't like that my GeoSPARQL [feature collection](https://opengeospatial.github.io/ogc-geosparql/geosparql11/document.html#_class_geofeaturecollection) isn't self-described completely.  I know I can add a custom CRS via [#1323], but its onerous for numerous custom CRSs.  [CRS Ontology](https://github.com/opengeospatial/ontology-crs) perhaps might be helpful in the future for an all-RDF, OGC-complaint solution.

**Comment by HughWilliams** [comment]
@ebremer To be clear, are you saying that rather than statically using the `DB.DBA.PROJ4_LOAD_SYS_SRIDS()` procedure in https://github.com/openlink/virtuoso-opensource/issues/1323, you want to be able to dynamically pass the CRS as a URI, e.g., [epsg:3395](https://epsg.io/3395.proj4), on the fly?

**Comment by ebremer** [comment]
@HughWilliams The short answer is yes, but, after doing some reading over the weekend, it may better to wait until GeoSPARQL 1.3, which will, hopefully, have support for an RDF specified CRS.  My particular use cases would benefit from a "Engineering CRS" or "Local CRS" if I follow the OGC spec correctly.  My spatial data is relative to and derived from an image and an image of human tissue, not the Earth.  Each of my images vary enough that the Engineering CRS specified in each GeoSPARQL FeatureCollection would be more convenient.
