### ISSUE TITLE
How to use the "Virtuoso-specific" ChatGPT (Virtuoso SupportBot)?

### ISSUE THREAD

**Issue by candlecao** [openlink/virtuoso-opensource#1332]
https://linkeddata.uriburner.com/chat/?chat_id=s-5dtDDhLZAe6Km6FJz2U8Li3oxct8XcboFc2iYrtjbvsr 
This is what I call a "'Virtuoso-specific' ChatGPT" (Virtuoso SupportBot).

But I always can not log in.

I managed to log in with my user name. Then I should enter my API key. I entered one API key that was generated from the official website of Open AI, then:

![image](https://github.com/user-attachments/assets/28dc94ce-ba73-41b1-a89e-e5f8daa6fca7)

**Comment by HughWilliams** [comment]
The reason for this error is that we had inadvertently locked the URIBurner instance down such that it only accepted OpenAI API Keys scoped to our organization. That restriction has now been removed, so you can try again.

**Comment by candlecao** [comment]
Thank you. However, I tried:
![image](https://github.com/user-attachments/assets/c44685e4-2499-4be3-889c-165b8611b251)
Maybe I don't have an effective API? How can I retrieve a valid API or re-obtain another one?

**Comment by HughWilliams** [comment]
What type of Open AI key are you using, as I presume you were prompted for and entered one during the login process ?

**Comment by kidehen** [comment]
> Thank you. However, I tried: ![image](https://private-user-images.githubusercontent.com/63447377/391195874-c44685e4-2499-4be3-889c-165b8611b251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwODIxMTYsIm5iZiI6MTczMzA4MTgxNiwicGF0aCI6Ii82MzQ0NzM3Ny8zOTExOTU4NzQtYzQ0Njg1ZTQtMjQ5OS00YmUzLTg4OWMtMTY1Yjg2MTFiMjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE5MzY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlM2JiMmU1ZmU0MTg1OGM5OTUxYTkwNzA5MTE0ZTQyOTBlMDBhMGQ5ZmJlODU0YzNmMWUxNWQyYWFhYmVlZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vvpyxZexgWCgTWe-Qltj5JqFR04nph_77WfFKfArKts) Maybe I don't have an effective API? How can I retrieve a valid API or re-obtain another one?

You can share your session link rather than a screenshot for easier troubleshooting.

**Comment by candlecao** [comment]
> What type of Open AI key are you using, as I presume you were prompted for and entered one during the login process ?

Sorry, I don't understand your meaning by "what type of Open Ai key". I first clicked log in, then see:
![image](https://github.com/user-attachments/assets/f74f9cbf-23f0-42b1-be9a-aaf8ce09e545)
and I proceeded with "Authorize"...

Just now, I generated an API key from the OpenAI official website
![Screenshot 2024-12-07 at 20 39 31](https://github.com/user-attachments/assets/d57abd9a-448e-4255-a3a2-6dfc02ed8778)
then I copied the generated API key to:
![image](https://github.com/user-attachments/assets/6b89ef45-af5a-4f81-9f91-c7b8617a8f3f)
but it still didn't work

**Comment by candlecao** [comment]
> > Thank you. However, I tried: ![image](https://private-user-images.githubusercontent.com/63447377/391195874-c44685e4-2499-4be3-889c-165b8611b251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwODIxMTYsIm5iZiI6MTczMzA4MTgxNiwicGF0aCI6Ii82MzQ0NzM3Ny8zOTExOTU4NzQtYzQ0Njg1ZTQtMjQ5OS00YmUzLTg4OWMtMTY1Yjg2MTFiMjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE5MzY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlM2JiMmU1ZmU0MTg1OGM5OTUxYTkwNzA5MTE0ZTQyOTBlMDBhMGQ5ZmJlODU0YzNmMWUxNWQyYWFhYmVlZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vvpyxZexgWCgTWe-Qltj5JqFR04nph_77WfFKfArKts) Maybe I don't have an effective API? How can I retrieve a valid API or re-obtain another one?
> 
> You can share your session link rather than a screenshot for easier troubleshooting.

Hi, what to share? I don't know!

**Comment by HughWilliams** [comment]
Does your OpenAI account actually have [credit](https://platform.openai.com/settings/organization/billing/overview) on it? If it does not, you would get that `HTTP:404: [model_not_found] The model gpt-4o does not exist or you do not have access to it.` error.

Note that the OpenAI API key has to be created when the account already has credit, as keys created before credit is in place will not inherit new credits added, as detailed in this [post](https://community.openai.com/t/response-the-model-gpt-4o-does-not-exist-or-you-do-not-have-access-to-it/789556/4).

**Comment by candlecao** [comment]
I purchased 5$ billing. It worked now:
![image](https://github.com/user-attachments/assets/546ffa65-9daf-4bcd-996a-0fd2c660f36d)
Thank you very much.
