### ISSUE TITLE
VOS7 cannot start due to plugins

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#135]
When updated to 49e2669327a05846d926dc88bb6356cc64d95141, VOS7 cannot start (terminates prematurely after starting).

End of virtuoso.log:

<pre><code>                Tue Feb 11 2014
09:33:27 { Loading plugin 1: Type `plain', file `wikiv' in `/usr/local/lib/virtuoso/hosting'
09:33:27   WikiV version 0.6 from OpenLink Software
09:33:27   Support functions for WikiV collaboration tool
</code></pre>

When deleted plugins from <code>/usr/local/lib/virtuoso/hosting</code>, it starts normally.

**Comment by openlink** [comment]
A fix for this has been pushed to develop/7 branch
