### ISSUE TITLE
Issue with Perl configure option

### ISSUE THREAD

**Issue by ghost** [openlink/virtuoso-opensource#143]
Hi,

I try to compile Virtuoso with the option "--enable-perl" and I fall on this error during the "make" step :

`libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../libsrc/Dk -fno-strict-aliasing -O2 -Wall -DNDEBUG -DPOINTER_64 -I/home/jenkins/build-virtuoso-packaging/virtuoso-opensource-7.1.0/libsrc/Xml.new -DOPENSSL_NO_KRB5 -Dlinux -D_GNU_SOURCE -DFILE64 -D_LARGEFILE64_SOURCE -I../../../libsrc -I../../../libsrc/Dk -I../../../libsrc/Wi -I../../../libsrc/plugin -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/lib/perl/5.10/CORE -g -O2 -MT hosting_perl_la-hosting_perl.lo -MD -MP -MF .deps/hosting_perl_la-hosting_perl.Tpo -c hosting_perl.c  -fPIC -DPIC -o .libs/hosting_perl_la-hosting_perl.o
hosting_perl.c:169: error: expected '}' before 'PERL_XS_APIVERSION'
hosting_perl.c: In function 'virtm_make_perl_hash':
hosting_perl.c:311: warning: value computed is not used
make[5]: *** [hosting_perl_la-hosting_perl.lo] Error 1`

Is-it normal ? Or it come from a bug with the Perl option ?

Thanks in advance.

**Comment by HughWilliams** [comment]
We are checking this as I have a similar error building on Mac OS X . Are you seeking to host a perl application in Virtuoso ?

**Comment by ghost** [comment]
Yes, we use perl to make an "auto-profiling" of Virtuoso to create a graph of its activities.

**Comment by HughWilliams** [comment]
development suggest changing the references to PERL_XS_APIVERSION' in "hosting_perl.c" to 'PERL_VERSION_STRING' which later versions of Perl seem to use as this has enable them to build it with this change, which will be submitted to the develop/7 branch soon ...

**Comment by ghost** [comment]
Yes it works now, sorry for my late reply. Thanks.
