### ISSUE TITLE
Problem with getting DATATYPE xsd:string back

### ISSUE THREAD

**Issue by joerixaop** [openlink/virtuoso-opensource#146]
Tested on 7.1, same problem exists on 6.1.8, (and 6.1.7 IIRC), but not 6.1.6

Test data:

```
PREFIX vocab: <http://example.com/vocab#>

WITH <http://test.graph/>
INSERT {
  <http://example.com/Book/1> a vocab:Book;
                              vocab:title "Book 1" .
}
```

Query:

```
PREFIX vocab: <http://example.com/vocab#>

SELECT DISTINCT ?me ?var3 DATATYPE(?var3) AS ?var4
WHERE {
  GRAPH <http://test.graph/> {
    ?me vocab:title ?var3
  }
}
```

asking for HTML: works
asking for XML:

```
Virtuoso 22023 Error SR544: Function __xsd_type() can not find XML Schema datatype that matches SQL datatype UNAME (217)
```

**Comment by HughWilliams** [comment]
This issue has been recreated and reported to development to fix ...

**Comment by larsga** [comment]
I ran into this one now, running "07.10.3207 on Win64 (x86_64-generic-win-64)". Exact same issue as reported by OP.

I also tried BIND( ?dt AS datatype(?var3) ) instead of doing it in the select, but same problem.

It works in the browser (accept=html), doesn't work from code (accept=xml). Intensely annoying.

**Comment by fgiasson** [comment]
I am experimenting exactly the same issue with 7.1.

SPARQL/JSON output is also affected.

**Comment by HughWilliams** [comment]
Have flagged this as also occurring in v7 in the internal report logged this error ...

**Comment by fgiasson** [comment]
Seems to be the same as #131. If so, it was an issue in 6.1.8

**Comment by joerixaop** [comment]
As was already mentioned in my original report.

**Comment by fgiasson** [comment]
@HughWilliams I think you can close this issue since it should be the same as #247 which is now operational and closed.
