### ISSUE TITLE
SQL State	 42001

### ISSUE THREAD

**Issue by DanielZhangQingLong** [openlink/virtuoso-opensource#154]
I have installed it successfully,but when I tried to create a new user , I got this ERROR:
Error
Stop
An error has occurred when processing "/conductor/cont_page.vspx" page.

SQL State    42001
SQL Message 
SR185: Undefined procedure DB.DBA.ACL_VALIDATE.

Would you please help me? I use Mac os 10.9 System. Thank you very much!

**Comment by HughWilliams** [comment]
What is the version of Virtuoso you are using:

   virtuoso-t -?

and what is the version Virtuoso conductor vad you are using which should be reported in the "virtuoso.log" file ?

I have tested with the git stable/7 virtuoso branch  07.10.3208  and the conductor vad 1.00.8725/ 2014-02-12 , user creation works for me ...

**Comment by vronk** [comment]
I also receive this error, when I try to create a new DAV folder:

Error
Stop
An error has occurred when processing "/conductor/cont_page.vspx" page.
SQL State   42001
SQL Message     

SR185: Undefined procedure DB.DBA.ACL_VALIDATE.

Virtuoso version 07.10.3207 
conductor: 1.00.8727/ 2014-05-09 
System: Centos 6.5

What about this procedure? Is it available somewhere and could it be post-loaded?

Thanks.

**Comment by openlink** [comment]
This problem has been fixed on the develop/7 branch. 

You need a newer conductor package with version 1.00.8733

**Comment by vronk** [comment]
Thanks! confirming this indeed resolved the issue
