### ISSUE TITLE
classcast exception in sesame virtuoso driver 

### ISSUE THREAD

**Issue by ghost** [openlink/virtuoso-opensource#161]
When trying to use sesame2 driver with a datasource provided by jboss, we encountered a classcast exception in 

binsrc/sesame2/virtuoso_driver/VirtuosoRepositoryConnection.java

at line 2688

else { // if(val instanceof String) {
            try {
                return getRepository().getValueFactory().createLiteral((String) val);
            }

we solved by replacing it this way :

else { // if(val instanceof String) {
            try {
                return getRepository().getValueFactory().createLiteral(val.toString());
            }

In case this is valid fix , could you update the repository ?

Thank you.

**Comment by smalinin** [comment]
The patch is valid. It will be committed to github soon.

**Comment by HughWilliams** [comment]
Patches pushed to develop/6 and develop/7

Updated the version number of the drivers to reflect these fxes.
