### ISSUE TITLE
Virtuoso 37000 Error SP031: SPARQL compiler: Internal error: Built-in function is not implemented

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#166]
In e438b4e056a2faef1952dba8a9ba3270b2683fde

<pre><code>Virtuoso 37000 Error SP031: SPARQL compiler: Internal error: Built-in function is not implemented

SPARQL query:
define sql:big-data-const 0 
#output-format:text/turtle
define sql:signal-void-variables 1 PREFIX adms:    &lt;http://www.w3.org/ns/adms#&gt;
PREFIX dcterms: &lt;http://purl.org/dc/terms/&gt;
PREFIX gr:      &lt;http://purl.org/goodrelations/v1#&gt;
PREFIX rdf:     &lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#&gt;
PREFIX schema:  &lt;http://schema.org/&gt;
PREFIX skos:    &lt;http://www.w3.org/2004/02/skos/core#&gt;
PREFIX void:    &lt;http://rdfs.org/ns/void#&gt;
PREFIX xsd:     &lt;http://www.w3.org/2001/XMLSchema#&gt;

PREFIX ldtab:   &lt;http://linked.opendata.cz/resource/domain/coi.cz/tabular/&gt;

CONSTRUCT {
  ?inspection a schema:CheckAction ;
    skos:notation ?ID_kontroly ;
    dcterms:date ?inspectionDate ;
    schema:agent ?coi ;
    schema:object ?businessEntity ;
    void:inDataset ?dataset ;
    schema:address ?address 
    .

  ?businessEntity a gr:BusinessEntity ;
    adms:identifier ?identifier 
    .
  
  ?identifier a adms:Identifier ;
    skos:notation ?IC ;
    skos:inScheme ?icoScheme 
    .

  ?address a schema:PostalAddress ;
    schema:addressRegion ?Kraj ;
    schema:streetAddress ?streetAddress ;
    schema:addressLocality ?Obec ;
    schema:postalCode ?PSC ;
    schema:location ?locationNUTS3, ?locationNUTS4, ?locationNUTS5 
    .
}
WHERE {
  ?x ldtab:idKontroly ?ID_kontroly;
     ldtab:datumKontroly ?Datum_kontroly;
     ldtab:icSubjektu ?IC_subjektu;
     ldtab:nuts3 ?NUTS_3;
     ldtab:nuts4 ?NUTS_4;
     ldtab:nuts5 ?NUTS_5;
     ldtab:ulice ?Ulice;
     ldtab:obec ?Obec;
     ldtab:cPopisne ?C_popisne;
     ldtab:cOrientacni ?C_orientacni;
     ldtab:psc ?PSC;
         ldtab:kraj ?Kraj
     .
  
  # Base URI
  BIND ("http://linked.opendata.cz/resource/" AS ?baseUri)
  
  # Static URIs
  BIND (URI("http://www.coi.cz/") AS ?coi)
  BIND (URI(CONCAT(?baseUri, "concept-scheme/CZ-ICO")) AS ?icoScheme)
  BIND (URI(CONCAT(?baseUri, "dataset/coi.cz/kontroly")) AS ?dataset)
  
  BIND ( 
  CONCAT(
    IF(STRLEN(?IC_subjektu)=7, "0",""),
    IF(STRLEN(?IC_subjektu)=6, "00",""),
    IF(STRLEN(?IC_subjektu)=5, "000",""),
    IF(STRLEN(?IC_subjektu)=4, "0000",""),
    IF(STRLEN(?IC_subjektu)=3, "00000",""),
    IF(STRLEN(?IC_subjektu)=2, "000000",""),
    ?IC_subjektu
    ) as ?IC)

  # Mint per-row URIs
  BIND (URI(CONCAT(?baseUri, "coi.cz/check-action/", ENCODE_FOR_URI(?ID_kontroly))) AS ?inspection)
  BIND (URI(CONCAT(?baseUri, "business-entity/CZ", ENCODE_FOR_URI(?IC))) AS ?businessEntity)
  BIND (URI(CONCAT(?baseUri, "business-entity/CZ", ENCODE_FOR_URI(?IC), "/identifier/", ENCODE_FOR_URI(?IC))) AS ?identifier)
  BIND (URI(CONCAT(?baseUri, "coi.cz/check-action/", ENCODE_FOR_URI(?ID_kontroly), "/postal-address")) AS ?address)
  BIND (URI(CONCAT(
    "http://linked.opendata.cz/resource/region/",
    ENCODE_FOR_URI(?NUTS_5)
  )) AS ?locationNUTS5)
  # ?locationNUTS4 and ?locationNUTS4 are unnecessary as they may be retrieved from data
  # linked via ?locationNUTS5
  BIND (URI(CONCAT(
    "http://ec.europa.eu/eurostat/ramon/rdfdata/nuts2008/",
    ENCODE_FOR_URI(?NUTS_3)
  )) AS ?locationNUTS3)
  BIND (URI(CONCAT(
    "http://linked.opendata.cz/resource/region/",
    ENCODE_FOR_URI(?NUTS_4)
  )) AS ?locationNUTS4)
   
  # Datatyped literals
  BIND (REPLACE(
    ?Datum_kontroly,
    "^(\\d{1,2}).*$",
    "$1"
  ) AS ?inspectionMonth)
  BIND (REPLACE(
    ?Datum_kontroly,
    "^(\\d{1,2})/(\\d{1,2}).*$",
    "$2"
  ) AS ?inspectionDay)
  BIND (REPLACE(
    ?Datum_kontroly,
    "^(\\d{1,2})/(\\d{1,2})/(\\d{4})$",
    "$3"
  ) AS ?inspectionYear)
  BIND (STRDT(CONCAT(
    ?inspectionYear,
    "-",
    IF(STRLEN(?inspectionMonth) &lt; 2, CONCAT("0", ?inspectionMonth), ?inspectionMonth),
    "-",
    IF(STRLEN(?inspectionDay) &lt; 2, CONCAT("0", ?inspectionDay), ?inspectionDay)
  ), xsd:date) AS ?inspectionDate) 
  
  BIND (CONCAT(?Ulice, IF(
    BOUND(?C_popisne) && ?C_popisne != "0" && BOUND(?C_orientacni),
    CONCAT(" ", ?C_popisne, "/", ?C_orientacni),
    IF(
      BOUND(?C_popisne) && ?C_popisne != "0",
      CONCAT(" ", ?C_popisne),
      IF(
        BOUND(?C_orientacni),
        CONCAT(" ", ?C_orientacni),
        ""
)))) AS ?streetAddress)

}</code></pre>

**Comment by HughWilliams** [comment]
The error can be reproduced running the query against any database. Turning on tracing on the server I see:

22:51:56 ERRS_0 37000 SP031 SPARQL compiler: Internal error: Built-in function is not implemented
22:51:56 ERRS_0 37000 SQ074 Line 132: SP031: SPARQL compiler: Internal error: Built-in function is not implemented
22:51:56 LTRS_1 SPARQL 192.168.33.162 Internal Commit transact 0x56ba7c0 140230682214400
22:51:56 LTRS_2 SPARQL 192.168.33.162 Internal Restart transact 0x56ba7c0
22:51:56 COMP_2 SPARQL 192.168.33.162 Internal Compile text:  isnull (sparql_to_sql_text ('{ define sql:big-data-const 0 ' || ? || '\n}'))
22:51:56 ERRS_0 37000 SP031 SPARQL compiler: Internal error: Built-in function is not implemented
22:51:56 LTRS_1 <DBA> 192.168.33.162 Internal Commit transact 0x56ba7c0 140230682214400
22:51:56 LTRS_2 <DBA> 192.168.33.162 Internal Restart transact 0x56ba7c0

We shall look into it ...

**Comment by yonyonson** [comment]
Any progress on this one? I am hitting it as well on 07.10.3207.

**Comment by HughWilliams** [comment]
@yonyonson: No this is still to be looked into by development ...

**Comment by HughWilliams** [comment]
This problem is resolved in the latest git develop/7 branch

**Comment by jakubklimek** [comment]
I can confirm that this does not happen anymore with my query.
