### ISSUE TITLE
Sesame VirtuosoConnection size() uses int instead of long

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#170]
In the method 

```
public long size(Resource... contexts)
```

You use a int instead of a long. This overflows for large datasets like uniprot.

```
 if (rs.next())
                ret = rs.getInt(1);
```

should be

```
if (rs.next())
                ret = rs.geLong(1);
```

Of course the type of res should be changed to long as well.

**Comment by smalinin** [comment]
Fixed, the sources will be updated soon
