### ISSUE TITLE
javac strips debug information

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#171]
For java in production having debug information available does not cost performance. 
However, it does make tracking bugs down much easier.
I suggest that the Makefiles for the java parts is changed.

```
#JDK_FLAGS = -Xlint -O -g:none
```

should be

```
#JDK_FLAGS = -Xlint -g
```

As the -O is no longer a valid option that should be removed as well.

**Comment by JervenBolleman** [comment]
Just to note the -O is a noop since the last millenia :)

**Comment by smalinin** [comment]
Fixed, the sources will be updated soon
