### ISSUE TITLE
Float match fails for some values.

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#173]
```
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#> 
PREFIX up:<http://purl.uniprot.org/core/> 
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#> 
SELECT ?float 
WHERE { ?uniref up:identity ?float . 
FILTER (?float != 1.0 && ?float != 0.5) 
}
```

Find answers while showing that 0.9 is a common potential value for ?float.
However querying directly for 0.9 returns no values.

```
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#> 
PREFIX up:<http://purl.uniprot.org/core/> 
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#> 
SELECT * WHERE { ?uniref up:identity 0.9 }
```

Putting the match into a filter like this

```
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX up:<http://purl.uniprot.org/core/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE { ?uniref up:identity ?float 
FILTER(sameTerm(?float, 0.9)) }
```

Does not help

You can try these queries at lod.openlinksw.com/sparql

**Comment by LorenzBuehmann** [comment]
I have a similar problem when working on http://dbpedia.org/sparql 

The SPARQL query

```
SELECT DISTINCT ?x0 WHERE {
?x0 <http://dbpedia.org/ontology/city> <http://dbpedia.org/resource/New_Cuyama,_California>.
?x0 <http://dbpedia.org/ontology/elevation> "671.474"^^xsd:double.
?x0 <http://dbpedia.org/ontology/faaLocationIdentifier> "L88".
?x0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Airport>.
}
```

returns no result, although there is a resource http://dbpedia.org/resource/New_Cuyama_Airport which has exactly the given elevation. Removing the triple pattern

```
?x0 <http://dbpedia.org/ontology/elevation> "671.474"^^xsd:double.
```

results indeed in 1 result, so I guess there is a bug when matching literals of type xsd:double and xsd:float. I couldn't even get it working with a comparison of the lexical form, i.e.

```
FILTER(str(?val) = "671.474")
```

**Comment by HughWilliams** [comment]
@LorenzBuehmann : We shall schedule to look into this ...

**Comment by HughWilliams** [comment]
@JervenBolleman: @LorenzBuehmann: Development indicate there's no such thing as "equal floating point values" as soon as these values were processed somehow in different ways, not copied in binary form. Do not ever hope on such a good luck as strong equality, that will happen only when unwanted.

So the querying should always include a tolerance, such as

SELECT DISTINCT ?x0 ?e WHERE {
?x0 http://dbpedia.org/ontology/city
http://dbpedia.org/resource/New_Cuyama,_California.
?x0 http://dbpedia.org/ontology/elevation ?e .
?x0 http://dbpedia.org/ontology/faaLocationIdentifier "L88" .
?x0 http://www.w3.org/1999/02/22-rdf-syntax-ns#type
http://dbpedia.org/ontology/Airport .
filter (?e > 671.4739 && ?e < 671.4745)
}

**Comment by JervenBolleman** [comment]
The == operator in SPARQL is not the == operator in C.
While the '== ' operator tests identity in C it should test [equality](http://www.w3.org/TR/xpath-functions/#func-numeric-equal) in [SPARQL/XML](http://www.w3.org/TR/sparql11-query/#OperatorMapping). 
And equality is defined in the [value space](http://www.w3.org/TR/xmlschema-2/#value-space) not [in the bit encoding](http://www.w3.org/TR/xmlschema-2/#float).

**Comment by JervenBolleman** [comment]
```
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#> 
PREFIX up:<http://purl.uniprot.org/core/> 
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#> 
SELECT * WHERE { ?uniref up:identity "0.9"^^xsd:float }
```

Works
