### ISSUE TITLE
gYear strings in virtuoso are not valid gYears

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#174]
see this example 
[at lod.openlinksw.com/sparql](http://lod.openlinksw.com/sparql?default-graph-uri=&query=SELECT+*+WHERE+{%3Fs+a+%3Chttp%3A%2F%2Fpurl.uniprot.org%2Fcore%2FCitation%3E+.+%3Fs+%3Fp+%3Fo+.+FILTER%28datatype%28%3Fo%29+%3D+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23gYear%3E%29+}+limit+100&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on)

See [specification](http://www.w3.org/TR/xmlschema-2/#gYear) for which lexical forms are allowed.

**Comment by HughWilliams** [comment]
This is a known issue I have reported this to development as another test case ...
