### ISSUE TITLE
Virtuoso 7.1 regression for SPARQL VALUES

### ISSUE THREAD

**Issue by jindrichmynarz** [openlink/virtuoso-opensource#184]
Virtuoso 7.1 has a regression bug for [SPARQL `VALUES`](http://www.w3.org/TR/sparql11-query/#inline-data), because doesn't correctly bind more than 1 variable, when more than 1 row of `VALUES` is given. The following 2 queries work fine:

```
SELECT ?a
WHERE {
  VALUES ?a {
         "a"
         "b"
  }
}
```

```
SELECT ?a ?b
WHERE {
  VALUES (?a ?b) {
         ("a" "ABC")
  }
}
```

However, when more than 1 variable and more than 1 row is given in the `VALUES` clause, Virtuoso produces empty bindings for the second (and further) variable(s):

```
SELECT ?a ?b
WHERE {
  VALUES (?a ?b) {
         ("a" "ABC")
         ("b" "DEF")
  }
}
```

What's unexpected is that Virtuoso reports the second (and further) variable(s) as bound:

```
SELECT ?a (BOUND(?b) AS ?bound) # ?bound is projected as true
WHERE {
  VALUES (?a ?b) {
         ("a" "ABC")
         ("b" "DEF")
  }
}
```

Nevertheless, the query doesn't project the values of the (allegedly) bound variables into the query results.

The previous version of Virtuoso (7.0) didn't have this issue, so I presume this is an regression bug, which could be avoided if test suite like [the one for SPARQL 1.1](http://www.w3.org/2009/sparql/docs/tests/summary.html) was employed.

Note: tested with Virtuoso version 07.10.3207 on Linux (x86_64-pc-linux-gnu), Single Server Edition. Virtuoso that runs on DBpedia also suffers from the same regression.

**Comment by jakubklimek** [comment]
Also tested on 616e55a4f8c14c124479594e743fed76062d313b

**Comment by HughWilliams** [comment]
Development will be looking into this ...

**Comment by jindrichmynarz** [comment]
I see this is working again on Virtuoso version 07.10.3211, so I'm closing the issue.
