### ISSUE TITLE
SQ200: No column s_21_17.goTerm when trying to execute comples sparql query

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#191]
The following query

```
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX up:<http://purl.uniprot.org/core/>
SELECT ?uniprot
(GROUP_CONCAT(?celtype; separator=";") AS ?celtypes)
(GROUP_CONCAT(?biotype; separator=";") AS ?biotypes)
(GROUP_CONCAT(?moltype; separator=";") AS ?moltypes)
WHERE
{
VALUES (?ac) {("Q6GZX4") ("Q96375")}
BIND (iri(concat("http://purl.uniprot.org/uniprot/",?ac)) AS ?protein)
?protein a up:Protein .
?protein up:classifiedWith ?goTerm .
#Determine if the type is biological_process
OPTIONAL {
?goTerm rdfs:subClassOf+ <http://purl.uniprot.org/go/0008150>.
?goTerm skos:prefLabel ?biotype .
}
#Determine if the type is cellular_component
OPTIONAL {
?goTerm rdfs:subClassOf+ <http://purl.uniprot.org/go/0005575>.
?goTerm skos:prefLabel ?celtype .
}
#Determine if the type is molecular_function
OPTIONAL {
?goTerm rdfs:subClassOf+ <http://purl.uniprot.org/go/0003674> .
?goTerm skos:prefLabel ?moltype .
}
#Filter out the uniprot keywords
FILTER(bound(?biotype) || bound(?celtype) || bound(?moltype))
BIND(concat(substr(str(?protein), 33)) as ?uniprot)
} GROUP BY ?uniprot
```

Generates this error virtuoso.jdbc4.VirtuosoException: SQ200: No column s_21_17.goTerm

The query is valid and used to run on competing SPARQL 1.1. endpoints.

**Comment by HughWilliams** [comment]
Jerven, Does this error only occur when it is executed via the JDBC Driver to query the Quad store, or does it also occur when executing via isql  or directly against the Virtuoso SPARQL endpoint ?

**Comment by HughWilliams** [comment]
Jerven, nerver mind I have been able to recreate this against our local uniprot installation and have reported to development to look into:

SQL> SPARQL PREFIX skos:http://www.w3.org/2004/02/skos/core# PREFIX rdfs:http://www.w3.org/2000/01/rdf-schema# PREFIX up:http://purl.uniprot.org/core/ SELECT ?uniprot (GROUP_CONCAT(?celtype; separator=";") AS ?celtypes) (GROUP_CONCAT(?biotype; separator=";") AS ?biotypes) (GROUP_CONCAT(?moltype; separator=";") AS ?moltypes) WHERE { VALUES (?ac) {("Q6GZX4") ("Q96375")} BIND (iri(concat("http://purl.uniprot.org/uniprot/",?ac)) AS ?protein) ?protein a up:Protein . ?protein up:classifiedWith ?goTerm . OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0008150. ?goTerm skos:prefLabel ?biotype . } OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0005575. ?goTerm skos:prefLabel ?celtype . } OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0003674 . ?goTerm skos:prefLabel ?moltype . } FILTER(bound(?biotype) || bound(?celtype) || bound(?moltype)) BIND(concat(substr(str(?protein), 33)) as ?uniprot) } GROUP BY ?uniprot;

**\* Error S0022: VD [Virtuoso Server]SQ200: No column s_1_17.goTerm
at line 96 of Top-Level:
SPARQL PREFIX skos:http://www.w3.org/2004/02/skos/core# PREFIX rdfs:http://www.w3.org/2000/01/rdf-schema# PREFIX up:http://purl.uniprot.org/core/ SELECT ?uniprot (GROUP_CONCAT(?celtype; separator=";") AS ?celtypes) (GROUP_CONCAT(?biotype; separator=";") AS ?biotypes) (GROUP_CONCAT(?moltype; separator=";") AS ?moltypes) WHERE { VALUES (?ac) {("Q6GZX4") ("Q96375")} BIND (iri(concat("http://purl.uniprot.org/uniprot/",?ac)) AS ?protein) ?protein a up:Protein . ?protein up:classifiedWith ?goTerm . OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0008150. ?goTerm skos:prefLabel ?biotype . } OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0005575. ?goTerm skos:prefLabel ?celtype . } OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0003674 . ?goTerm skos:prefLabel ?moltype . } FILTER(bound(?biotype) || bound(?celtype) || bound(?moltype)) BIND(concat(substr(str(?protein), 33)) as ?uniprot) } GROUP BY ?uniprot
SQL>

**Comment by HughWilliams** [comment]
Jerven, nerver mind I have been able to recreate this against our local uniprot installation and have reported to development to look into:

SQL> SPARQL PREFIX skos:http://www.w3.org/2004/02/skos/core# PREFIX rdfs:http://www.w3.org/2000/01/rdf-schema# PREFIX up:http://purl.uniprot.org/core/ SELECT ?uniprot (GROUP_CONCAT(?celtype; separator=";") AS ?celtypes) (GROUP_CONCAT(?biotype; separator=";") AS ?biotypes) (GROUP_CONCAT(?moltype; separator=";") AS ?moltypes) WHERE { VALUES (?ac) {("Q6GZX4") ("Q96375")} BIND (iri(concat("http://purl.uniprot.org/uniprot/",?ac)) AS ?protein) ?protein a up:Protein . ?protein up:classifiedWith ?goTerm . OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0008150. ?goTerm skos:prefLabel ?biotype . } OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0005575. ?goTerm skos:prefLabel ?celtype . } OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0003674 . ?goTerm skos:prefLabel ?moltype . } FILTER(bound(?biotype) || bound(?celtype) || bound(?moltype)) BIND(concat(substr(str(?protein), 33)) as ?uniprot) } GROUP BY ?uniprot;

**\* Error S0022: VD [Virtuoso Server]SQ200: No column s_1_17.goTerm
at line 96 of Top-Level:
SPARQL PREFIX skos:http://www.w3.org/2004/02/skos/core# PREFIX rdfs:http://www.w3.org/2000/01/rdf-schema# PREFIX up:http://purl.uniprot.org/core/ SELECT ?uniprot (GROUP_CONCAT(?celtype; separator=";") AS ?celtypes) (GROUP_CONCAT(?biotype; separator=";") AS ?biotypes) (GROUP_CONCAT(?moltype; separator=";") AS ?moltypes) WHERE { VALUES (?ac) {("Q6GZX4") ("Q96375")} BIND (iri(concat("http://purl.uniprot.org/uniprot/",?ac)) AS ?protein) ?protein a up:Protein . ?protein up:classifiedWith ?goTerm . OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0008150. ?goTerm skos:prefLabel ?biotype . } OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0005575. ?goTerm skos:prefLabel ?celtype . } OPTIONAL { ?goTerm rdfs:subClassOf+ http://purl.uniprot.org/go/0003674 . ?goTerm skos:prefLabel ?moltype . } FILTER(bound(?biotype) || bound(?celtype) || bound(?moltype)) BIND(concat(substr(str(?protein), 33)) as ?uniprot) } GROUP BY ?uniprot
SQL>

Internal tracking number 16185

**Comment by HughWilliams** [comment]
Hi Jerven, I fix for this issue is available in the open source v7fasttrack branch, the fix will be applied to the develop/7 branch next week ...

Note you may have to set the tn_max_memory INI file param in the [Flags] section as I got a transitive memory exceeded error and this had to increase to get around it ...
