### ISSUE TITLE
Update README.WINDOWS

### ISSUE THREAD

**Issue by robertoea** [openlink/virtuoso-opensource#192]
Hi, I'm trying to make a build in Windows by following the instructions in the README.WINDOWS file. However, it seems to be outdated and some parts are not valid anymore.

Could someone please update the instruction to make it aligned with the current version?

Thanks.

**Comment by HughWilliams** [comment]
I presume you are aware we provide prebuilt Virtuoso binaries for Windows at:

http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VOSDownload#Pre-built binaries for Windows

As building on Windows is not an easy process ?

Will see about getting the readme updated for building with the latest Windows compilers ...

**Comment by robertoea** [comment]
Hi,

Yes, I'm aware of the prebuilt binaries. I was trying to rebuild Virtuoso to increase the transitive temp memory (similar issue: http://boards.openlinksw.com/phpBB3/viewtopic.php?f=12&t=801).

Meanwhile, I stumbled across your post here: https://www.mail-archive.com/virtuoso-users@lists.sourceforge.net/msg06394.html, but it didn't seem to work for me. I still see:

```
Message: TN...: Exceeded 100000000 bytes in transitive temp memory.  use t_distinct, t_max or more T_MAX_memory options to limit the search or increase the pool
```

(the number didn't change although I have specified something like `__dbf_set ('tn_max_memory', 5000000000);`)

I will try to continue exploring this direction for the time being, but having the readme updated will be great. Thanks!

**Comment by HughWilliams** [comment]
Hmmm, will have to check with development when the tn_max_memory param was  added as it may not be in the stable/7 branch the current windows binaries were built against and you need a develop/7 build ?

**Comment by robertoea** [comment]
Hi, @HughWilliams... any updates on this?

I just encountered this issue: https://github.com/openlink/virtuoso-opensource/issues/154 which is supposedly fixed in the devel branch.

Alternatively, any new version coming up soon?

Thanks!

**Comment by HughWilliams** [comment]
The latest Windows open source Virtuoso 7.1 binary can be downloaded from:

 ftp://download.openlinksw.com/support/db/virtuoso-t.zip

Simply run a checkpoint, shutdown Virtuoso, unzip and replace the current virtuoso-t.exe file with this one and restart.

The version details being:

..\bin\virtuoso -t -? 
Virtuoso Open Source Edition (multi threaded) 
Version 7.1.0.3211-threads as of Jul 10 2014 
Compiled for Win64 (x86_64-generic-win-64) 
Copyright (C) 1998-2014 OpenLink Software

**Comment by robertoea** [comment]
Thanks! Do you also have a newer ready-made conductor_dav.vad package?

**Comment by HughWilliams** [comment]
ftp://download.openlinksw.com/support/virtuoso/vads/conductor_dav.vad

**Comment by robertoea** [comment]
Thanks again. I'm still encountering the issue when trying to add a webdav property, but I guess it's better if I create a new issue for this.
