### ISSUE TITLE
autogen.sh issue on Solaris 11.1

### ISSUE THREAD

**Issue by kgardas** [openlink/virtuoso-opensource#196]
Hello,
while trying to ./autogen.sh on Solaris 11.1 I've been always hit by:
$ ./autogen.sh 

Checking build environment ...
Using aclocal (GNU automake) 1.10
Using autoconf (GNU Autoconf) 2.68
Using autoheader (GNU Autoconf) 2.68
Using automake (GNU automake) 1.11.2
Using libtoolize (GNU libtool) 2.4.2
Using bison (GNU Bison) 2.3
Using flex 2.5.35
Using GNU Awk 3.1.8
Using GNU gperf 3.0.3
Using OpenSSL 1.0.0j 10 May 2012

Generating build scripts ...
Running libtoolize ...
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `binsrc/config'.
libtoolize: copying file`binsrc/config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `binsrc/config'.
libtoolize: copying file`binsrc/config/libtool.m4'
libtoolize: copying file `binsrc/config/ltoptions.m4'
libtoolize: copying file`binsrc/config/ltsugar.m4'
libtoolize: copying file `binsrc/config/ltversion.m4'
libtoolize: copying file`binsrc/config/lt~obsolete.m4'
Running aclocal ...
Running autoheader ...
Running automake ...

*\* ERROR **
libsrc/JDBCDriverType4/virtuoso/jdbc2/Makefile.am:516: `%'-style pattern rules are a GNU make extension
libsrc/JDBCDriverType4/virtuoso/jdbc2/Makefile.am:519:`%'-style pattern rules are a GNU make extension
libsrc/JDBCDriverType4/virtuoso/jdbc2/Makefile.am:522: `%'-style pattern rules are a GNU make extension

Bootstrap script aborting (see autogen.log for details) ...

Any idea how to solve this?

Thanks!
Karel

**Comment by openlink** [comment]
On 13 June 2014 22:56, kgardas notifications@github.com wrote:

> Running automake ...
> 
> *\* ERROR **
> libsrc/JDBCDriverType4/virtuoso/jdbc2/Makefile.am:516: %'-style pattern
> rules are a GNU make extension
> libsrc/JDBCDriverType4/virtuoso/jdbc2/Makefile.am:519:%'-style pattern
> rules are a GNU make extension
> libsrc/JDBCDriverType4/virtuoso/jdbc2/Makefile.am:522: `%'-style pattern
> rules are a GNU make extension
> 
> Bootstrap script aborting (see autogen.log for details) ...
> 
> Any idea how to solve this?

Hi,
Is it picking up GNU versions of automake and make from your PATH?

## ~Tim

Tim Haynes
Product Development Consultant
OpenLink Software
http://www.openlinksw.com/
http://twitter.com/openlink

**Comment by kgardas** [comment]
Ah, thanks for the note, I've rechecked my PATH and it contained a link to aclocal-2.10. Now with canonic SUSv3 PATH set:
$ echo $PATH
/usr/xpg6/bin:/usr/xpg4/bin:/usr/bin:/opt/solarisstudio12.3/bin

it looks like everything is fine. Sorry for noise and please close this.
Thanks! Karel
