### ISSUE TITLE
Virtuoso 7.1 Ignores literals schema

### ISSUE THREAD

**Issue by feugen24** [openlink/virtuoso-opensource#199]
Given the command:

```
                            INSERT { 
                                GRAPH <http://www.example.com/>  { 
<#book2> <http://purl.org/dc/elements/1.1/title>  "David Copperfield"^^<http://www.w3.org/2001/XMLSchema#string>.
<#book2> <http://www.example.com/Int32> 789  .
<#book2> <http://www.example.com/Double> "23"^^<http://www.w3.org/2001/XMLSchema#double> .
<#book2> <http://www.example.com/Float> "23"^^<http://www.w3.org/2001/XMLSchema#float> .
<#book2> <http://www.example.com/Decimal> "0"^^<http://www.w3.org/2001/XMLSchema#decimal>  .
<#book2> <http://www.example.com/DateTime> "2014-06-17T12:08:26.7675955+03:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> .

                                }
                                }
```

followed by a select returns data without schema (except for string)

```
#book2  http://purl.org/dc/elements/1.1/title   "David Copperfield"^^<http://www.w3.org/2001/XMLSchema#string>
#book2  http://www.example.com/Int32    789
#book2  http://www.example.com/Double   23
#book2  http://www.example.com/Float    23.0
#book2  http://www.example.com/Decimal  0
#book2  http://www.example.com/DateTime     2014-06-17T12:08:26.767595+03:00
```

**Comment by HughWilliams** [comment]
What is the Virtuoso version and build date are using as using the git develop/7 branch schema/type is shown for either literal/object value:

SQL> sparql select \* from http://www.example.com/ where {?s ?p ?o};
s                                                                                 p                                                                                 o
VARCHAR                                                                           VARCHAR                                                                           VARCHAR

---

#book2                                                                            http://purl.org/dc/elements/1.1/title                                             David Copperfield
#book2                                                                            http://www.example.com/Int32                                                      789
#book2                                                                            http://www.example.com/Double                                                     23
#book2                                                                            http://www.example.com/Float                                                      23
#book2                                                                            http://www.example.com/Decimal                                                    0
#book2                                                                            http://www.example.com/DateTime                                                   2014-06-17 12:08:26.767595

6 Rows. -- 1 msec.
SQL> 

Note also the following Virtuoso Tip on how to obtain the schema/type of literal/object values:

http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtTipsAndTricksGuideGetObjDatatype

Enabling the following query to be run to obtain the schema/types of the literal/object values in your insert query:

SQL> SPARQL  SELECT ?o (iri(sql:RDF_DATATYPE_OF_OBJ(?o, 'untyped!')))  FROM http://www.example.com/ { ?s ?p ?o} ;
o                                                                                 callret-1
VARCHAR                                                                           VARCHAR

---

David Copperfield                                                                 http://www.w3.org/2001/XMLSchema#string
789                                                                               http://www.w3.org/2001/XMLSchema#integer
23                                                                                http://www.w3.org/2001/XMLSchema#decimal
23                                                                                http://www.w3.org/2001/XMLSchema#double
0                                                                                 http://www.w3.org/2001/XMLSchema#decimal
2014-06-17 12:08:26.767595                                                        http://www.w3.org/2001/XMLSchema#dateTime

6 Rows. -- 1 msec.
SQL>

**Comment by feugen24** [comment]
Virtuoso Open Source Edition (multi threaded)
Version 7.1.0.3207-threads as of Feb 17 2014
Compiled for Win64 (x86_64-generic-win-64)

In the example the value 23 is inserted as  (double+float)

```
<#book2> <http://www.example.com/Double> "23"^^<http://www.w3.org/2001/XMLSchema#double> .
<#book2> <http://www.example.com/Float> "23"^^<http://www.w3.org/2001/XMLSchema#float> .
```

but if i run on my server (add ?p to the projection in your example):

```
select ?p ?o (iri(sql:RDF_DATATYPE_OF_OBJ(?o, 'untyped!')))
from <http://www.example.com/>
where
{
 ?s ?p ?o
}
```

the result is:

```
http://www.example.com/Double   23  http://www.w3.org/2001/XMLSchema#decimal
http://www.example.com/Float    23.0    http://www.w3.org/2001/XMLSchema#double
```

So double -> decimal, float -> double.

Notice that the results you obtained on dev version are also not correct(where is the 23 float?):

```
23 http://www.w3.org/2001/XMLSchema#decimal
23 http://www.w3.org/2001/XMLSchema#double
```

**Comment by rumito** [comment]
Hi, 
Virtuoso saves the 23 as value without exact type -- i.e. can be stored only distinct values, and cannot be stored e.g., 23, double 23.0 , float 23.0 and decimal 23.0 in same any column that is an index key.

**Comment by furver** [comment]
Any updates on that ?
I got the same thing here.. I insert:
<#item1> http://schema.org/amount "2053.96"^^http://www.w3.org/2001/XMLSchema#float .

And it returns it as http://www.w3.org/2001/XMLSchema#decimal

If I get the value using JDBC it actually gives me a BigDecimal object already, shouldn't it give me a Literal with the URI as the type?

I'm getting the data as specified [here](http://docs.openlinksw.com/virtuoso/VirtuosoDriverJDBC.html#jdbc4features) 
in the section "7.4.4.5. Extension datatype for RDF"

So I was expecting it to be a instance of "VirtuosoRdfBox" so I could get the type from it.
If I use Jena than it converts to a RDFNode that has the decimal type

**Comment by pchampin** [comment]
Same problem here ; when inserting (with a SPARUL query on the `sparql-auth` endpoint) a literal with datatype `xsd:float` or `xsd:double`, I get back (through a SELECT or CONSTRUCT query on the same endpoint) a literal with datatype `xsd:decimal`.

I'm using: Virtuoso version 07.20.3214 on Linux (x86_64-pc-linux-gnu), Single Server Edition  .

**Comment by HughWilliams** [comment]
@pchampin: Do you have a test case to recreate ? 

Also note the latest open source release is 07.20.3217 , the 3214 build you are using is from over a year ago thus you should consider upgrading ...

**Comment by pchampin** [comment]
First run:

``` sparql
  insert { graph <http://champin.net/2016-06-28-test1> {
    [] rdfs:label "3.14"^^xsd:float } }
```

Then run

``` sparql
  select (datatype(?o) as ?dt) { graph <http://champin.net/2016-06-28-test1> {
    ?s ?p ?o } }
```

The result should be `http://www.w3.org/2001/XMLSchema#float` but it is `http://www.w3.org/2001/XMLSchema#decimal`.

I'll try the latest version.

**Comment by pchampin** [comment]
Indeed, the bug seems to be gone in 07.20.3217 .
