### ISSUE TITLE
pyodbc connection works only with localhost

### ISSUE THREAD

**Issue by nicholsn** [openlink/virtuoso-opensource#225]
I'm able to successfully connect to a 7.1.0 virtuoso server running on a mac 10.9.4 as localhost.

```
connection = pyodbc.connect('DRIVER=/usr/local/lib/virtodbcu_r.so;SERVER=localhost:1111;UID=dba;PWD=dba')
```

but if I try to connect remotely, the `SERVER` connection string seems to be ignored

```
connection = pyodbc.connect('DRIVER=/usr/local/lib/virtodbcu_r.so;SERVER=192.168.59.103:1111;UID=dba;PWD=dba')
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-2-db5e3d4564d9> in <module>()
----> 1 connection = pyodbc.connect('DRIVER=/usr/local/lib/virtodbcu_r.so;SERVER=192.168.59.103:1111;UID=dba;PWD=dba')

Error: ('S2801', '[S2801] [OpenLink][Virtuoso iODBC Driver]CL033: Connect failed to localhost:1111 = localhost:1111. (-1) (SQLDriverConnect)')
```

As you can see, the driver is still looking for virtuoso on localhost. Is there a setting I'm missing somewhere so the connection string is read correctly?

**Comment by HughWilliams** [comment]
The connect string attribute for specifying the network location of a Virtuoso server instance is "HOST" not "SERVER" as you have used, see:

http://docs.openlinksw.com/virtuoso/odbcimplementation.html#SQLDriverConnect

The end result being that the default  localhost:1111 was being used for all connections, thus only working from localhost ...

**Comment by nicholsn** [comment]
Ah, perfect - thank you! Connection is working now.
