### ISSUE TITLE
SPARQL result format JSON types bnodes as literal or uri

### ISSUE THREAD

**Issue by white-gecko** [openlink/virtuoso-opensource#226]
When querying a graph containing blank nodes the JSON format will type them inconsistently as literal or uri as in the following snippet. You can reproduce this with the `http://vocab.ub.uni-leipzig.de/bibrm/` model, which you can find in our github repo: https://github.com/ERM-HD/vocab.bibrm/blob/develop/bibrm.ttl

```
…
{ "resourceUri": { "type": "uri", "value": "_:node1" }  , "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" }   , "o": { "type": "uri", "value": "http://vocab.ub.uni-leipzig.de/bibrm/Database" }},
{ "resourceUri": { "type": "uri", "value": "_:node1" }  , "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest" }    , "o": { "type": "literal", "value": "_:node2" }},
{ "resourceUri": { "type": "uri", "value": "_:node2" }  , "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" }   , "o": { "type": "uri", "value": "http://vocab.ub.uni-leipzig.de/bibrm/Ejournal" }},
{ "resourceUri": { "type": "uri", "value": "_:node2" }  , "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest" }    , "o": { "type": "literal", "value": "_:node3" }},
{ "resourceUri": { "type": "uri", "value": "_:node3" }  , "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" }   , "o": { "type": "uri", "value": "http://vocab.ub.uni-leipzig.de/bibrm/EjournalPackage" }},
…
```

The correct output would be `{ "type": "bnode", "value": "node2" }` as I understand the [SPARQL recommendation](http://www.w3.org/TR/2013/REC-sparql11-results-json-20130321/#select-encode-terms).

I ran

```
SELECT ?resourceUri ?p ?o {
    ?resourceUri ?p ?o
}
```

ans selected `JSON` as „Results Format“.

**Comment by HughWilliams** [comment]
What Virtuoso version are you using as I get the following:

...
    { "resourceUri": { "type": "bnode", "value": "nodeID://b10015" }    , "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" }   , "o": { "type": "uri", "value": "http://vocab.ub.uni-leipzig.de/bibrm/silentUninterpreted" }},
    { "resourceUri": { "type": "bnode", "value": "nodeID://b10005" }    , "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" }   , "o": { "type": "uri", "value": "http://vocab.ub.uni-leipzig.de/bibrm/Database" }},
    { "resourceUri": { "type": "bnode", "value": "nodeID://b10008" }    , "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" }   , "o": { "type": "uri", "value": "http://vocab.ub.uni-leipzig.de/bibrm/Ebook" }},
    { "resourceUri": { "type": "bnode", "value": "nodeID://b10009" }    , "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" }   , "o": { "type": "uri", "value": "http://vocab.ub.uni-leipzig.de/bibrm/EbookPackage" }},
    { "resourceUri": { "type": "bnode", "value": "nodeID://b10006" }    , "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" }   , "o": { "type": "uri", "value": "http://vocab.ub.uni-leipzig.de/bibrm/Ejournal" }},
    { "resourceUri": { "type": "bnode", "value": "nodeID://b10007" }    , "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" }   , "o": { "type": "uri", "value": "http://vocab.ub.uni-leipzig.de/bibrm/EjournalPackage" }},
...

running against the latest  git open source develop/7 build available from:

http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VOSGitUsage

Thus I would suggest you update to it:

$ ~/src/git/vos-7-develop/binsrc/virtuoso/virtuoso-t -?
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.1.1-dev.3211-pthreads as of Jul 14 2014
Compiled for Darwin (x86_64-apple-darwin13.2.0)
Copyright (C) 1998-2014 OpenLink Software

**Comment by white-gecko** [comment]
Thank you. I'm running Virtuoso 6.1.6. I will reopen the issue if I can reproduce it with any current version.

**Comment by HughWilliams** [comment]
OK, note you can also try with the latest git stable/6 or develop/6 branches which are 6.1.8+ and I would expect to behave the same as 7.1 in terms of SPARQL 1.1 support etc

**Comment by white-gecko** [comment]
That was my plan since I'm still worried regarding #206 resp. #188 .
