### ISSUE TITLE
develop/7: Install on Ubuntu

### ISSUE THREAD

**Issue by Kellli** [openlink/virtuoso-opensource#228]
Hi
I am facing exactly the same problem of issue #55. 

I am trying to install the branch develop7 locally on ubuntu, but i cant get it to work. 

I am running as root and I've uninstalled Virtuoso 6. But the problem persists.

Thanks for any help!
Kelli

---

less mkvad.output

  CREATING VAD PACKAGE FOR VIRTUOSO CONDUCTOR (mkvad.sh)
  Thu Aug 14 16:22:05 BRT 2014

VAD Sticker vad_fs.xml creation...
VAD Sticker vad_dav.xml creation...

**\* Error S2801: [Virtuoso Driver]CL033: Connect failed to localhost:1111 = localhost:1111.
at line 0 of Top-Level:

Starting Virtuoso server ...
***FAILED: Could not start Virtuoso Server within 120 seconds

---

make

  CREATING VAD PACKAGE FOR VIRTUOSO CONDUCTOR (mkvad.sh)
  Thu Aug 14 16:22:05 BRT 2014

cp: omitting directory `dav'
cp: omitting directory`help'
cp: omitting directory `images'
cp: omitting directory`syntax'
cp: omitting directory `vad'
cp: omitting directory`dav/image'
cp: omitting directory `dav/image/dav'
cp: omitting directory`images/buttons'
cp: omitting directory `images/dav_browser'
cp: omitting directory`images/icons'
cp: omitting directory `/tmp/virtuoso-opensource/binsrc/oat/images/markers'
VAD Sticker vad_fs.xml creation...
VAD Sticker vad_dav.xml creation...
Starting Virtuoso server ...
The VDBMS server process terminated prematurely
after opening the database.
***FAILED: Could not start Virtuoso Server within 120 seconds
make[2]: *** [conductor_dav.vad] Error 1
make[2]: Leaving directory`/tmp/virtuoso-opensource/binsrc/yacutia'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/tmp/virtuoso-opensource/binsrc'
make: **\* [all-recursive] Error 1

---

cat /proc/version
Linux version 3.2.0-67-generic (buildd@brownie) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #101-Ubuntu SMP Tue Jul 15 17:46:11 UTC 2014

**Comment by openlink** [comment]
On 14 August 2014 23:49, Kellli notifications@github.com wrote:

> CREATING VAD PACKAGE FOR VIRTUOSO CONDUCTOR (mkvad.sh)
> Thu Aug 14 16:22:05 BRT 2014
> 
> VAD Sticker vad_fs.xml creation...
> VAD Sticker vad_dav.xml creation...
> 
> **\* Error S2801: [Virtuoso Driver]CL033: Connect failed to localhost:1111
> = localhost:1111.
> at line 0 of Top-Level:
> 
> Starting Virtuoso server ...
> ***FAILED: Could not start Virtuoso Server within 120 seconds
> 
> Hi,

Are you sure you don't have processes still running from prior build
attempts? Running
pkill virtuoso-
would be reasonable.

## ~Tim

Tim Haynes
Product Development Consultant
OpenLink Software
http://www.openlinksw.com/
http://twitter.com/openlink

**Comment by Kellli** [comment]
Hi Tim @openlink 

Thanks very much for the prompt answer.

I have rebooted the server, changed the ports from ./configure, pkill virtuoso-, make and then
/binsrc/yacutia# make

The mkvad.output file messages instill the same.

One more information, the vad.log has many message errors about file format. 
The same messages appear when I`ve tried 
/usr/local/virtuoso-opensource/bin# ./virtuoso-t -f -c virtuoso.ini

Thanks for your precious time and assistance,
Kelli

---

mkvad.output
VAD Sticker vad_fs.xml creation...
VAD Sticker vad_dav.xml creation...

**\* Error S2801: [Virtuoso Driver]CL033: Connect failed to localhost:1133 = localhost:1133.
at line 0 of Top-Level:

---

vad.log
                Fri Aug 15 2014
05:52:30 Error compiling a server init statement : 37000: SQ074: Line 1: Too many closing parentheses at ')' immediately before end of line -- _as_o)
{
if (isiri_id (s))
{
phys_s := s;
vectorbld_acc (phys_subjects, phys_s);
}
else
{
phys_s...
05:52:30 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at '', s, '' before 'maps' -- ', s, ' maps = ', maps);

}
vectorbld_ge_name any, in options any)
{
declare all_subj_descs, phy...
05:52:30 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at '[' before 's_ctr' -- bjs [s_ctr] := 0;

}
vectorbld_final (phys_subjects);
for (s_ctr := 0; s_ctr < all_s_count; s_c...
05:52:30 Error compiling a server init statement : 37000: SQ074: Line 1: Too many closing parentheses at ')' before ';' -- s_obj);
}
}
maps := subseq (maps, 0, maps_len-1);
maps_len := maps_len - 1;
}
if (maps_len > 0)
...
05:52:30 Error compiling a server init statement : 37000: SQ074: Line 1: Too many closing parentheses at '}' immediately before end of line -- }
else
{
final_tblname := DB.DBA.SQLQNAME_NOTATION_TO_QNAME (sqlcol[0], 3);
if (not exists (sele...
05:52:30 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at 'done' before '.' -- phs done...');
 ;
}

---

./virtuoso-t -f -c virtuoso.ini

```
            Thu Aug 14 2014
```

19:48:52 { Loading plugin 1: Type `plain', file`wikiv' in `../hosting'
19:48:52   FAILED  plugin 1: Unable to locate file }
19:48:52 { Loading plugin 2: Type`plain', file `mediawiki' in`../hosting'
19:48:52   FAILED  plugin 2: Unable to locate file }
19:48:52 { Loading plugin 3: Type `plain', file`creolewiki' in `../hosting'
19:48:52   FAILED  plugin 3: Unable to locate file }
19:48:52 { Loading plugin 4: Type`plain', file `im' in`../hosting'
19:48:52   FAILED  plugin 4: Unable to locate file }
19:48:52 OpenLink Virtuoso Universal Server
19:48:52 Version 07.10.3211-pthreads for Linux as of Aug 14 2014
19:48:52 uses parts of OpenSSL, PCRE, Html Tidy
19:48:53 SQL Optimizer enabled (max 1000 layouts)
19:48:53 Compiler unit is timed at 0.000737 msec
19:48:53 Error compiling a server init statement : 37000: SQ074: Line 1: Too many closing parentheses at ')' immediately before end of line -- _as_o)
{
if (isiri_id (s))
{
phys_s := s;
vectorbld_acc (phys_subjects, phys_s);
}
else
{
phys_s...
19:48:53 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at '', s, '' before 'maps' -- ', s, ' maps = ', maps);

}
vectorbld_ge_name any, in options any)
{
declare all_subj_descs, phy...
19:48:53 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at '[' before 's_ctr' -- bjs [s_ctr] := 0;

}
vectorbld_final (phys_subjects);
for (s_ctr := 0; s_ctr < all_s_count; s_c...
19:48:53 Error compiling a server init statement : 37000: SQ074: Line 1: Too many closing parentheses at ')' before ';' -- s_obj);
}
}

**Comment by HughWilliams** [comment]
I setup a Ubuntu 12.04 LTS x64_64 VM and it compiles file for me including the conductor VAD:

hwilliams@ubuntu:~/src/git/virt-develop7$ cat /etc/issue
Ubuntu 12.04.3 LTS \n \l

hwilliams@ubuntu:~/src/git/virt-develop7$ cat /proc/version
Linux version 3.2.0-53-generic (buildd@allspice) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #81-Ubuntu SMP Thu Aug 22 21:01:03 UTC 2013
hwilliams@ubuntu:~/src/git/virt-develop7$ uname -a
Linux ubuntu 3.2.0-53-generic #81-Ubuntu SMP Thu Aug 22 21:01:03 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
hwilliams@ubuntu:~/src/git/virt-develop7$ git status

# On branch develop/7

nothing to commit (working directory clean)
hwilliams@ubuntu:~/src/git/virt-develop7$ ./binsrc/virtuoso/virtuoso-t -?
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.1.1-dev.3211-pthreads as of Aug 17 2014
Compiled for Linux (x86_64-unknown-linux-gnu)
Copyright (C) 1998-2014 OpenLink Software
.
.
.

Making all in yacutia
make[2]: Entering directory `/home/hwilliams/src/git/virt-develop7/binsrc/yacutia'
PATH="/home/hwilliams/src/git/virt-develop7/binsrc/virtuoso:/home/hwilliams/src/git/virt-develop7/binsrc/tests:.:$PATH" PORT=1111 HOME="/home/hwilliams/src/git/virt-develop7" HOST=localhost /bin/bash ./mkvad.sh

# 

=  CREATING VAD PACKAGE FOR VIRTUOSO CONDUCTOR (mkvad.sh)

# =  Sun Aug 17 09:53:50 PDT 2014

cp: omitting directory `dav'
cp: omitting directory`help'
cp: omitting directory `images'
cp: omitting directory`syntax'
cp: omitting directory `vad'
cp: omitting directory`dav/image'
cp: omitting directory `dav/image/dav'
cp: omitting directory`images/buttons'
cp: omitting directory `images/dav_browser'
cp: omitting directory`images/icons'
cp: omitting directory `/home/hwilliams/src/git/virt-develop7/binsrc/oat/images/markers'
VAD Sticker vad_fs.xml creation...
VAD Sticker vad_dav.xml creation...
Starting Virtuoso server ...
Virtuoso server started
PASSED: DB.DBA.VAD_PACK('vad_dav.xml', '.', 'conductor_dav.vad')
PASSED: DB.DBA.VAD_PACK('vad_fs.xml', '.', 'conductor_filesystem.vad')
PASSED: checkpoint
PASSED: shutdown

# 

# =  Checking log file mkvad.output for statistics:

=  Total number of tests PASSED  : 4
=  Total number of tests FAILED  : 0

# =  Total number of tests ABORTED : 0

egrep: input file `mkvad.output' is also the output

# 

=  COMPLETED VAD PACKAGING

# =  Sun Aug 17 09:54:02 PDT 2014

SQL> status();
REPORT
VARCHAR

---

OpenLink Virtuoso  Server
Version 07.10.3211-pthreads for Linux as of Aug 17 2014 
Started on: 2014-08-17 10:26 GMT-7

**Comment by Kellli** [comment]
Thank very much, @HughWilliams, for you detailed answer. 

I followed each step checking the versions. 
The only difference I have noticed is that my Ubuntu is 12.04 and yours is 12.04.3. Could it be the problem or I`ve missed something else? 

The parser errors on vad.log still the same.

Any other suggestion? 

Thanks

## Kelli

root@prodgrecosite:~/virtuoso-opensource# cat /etc/issue
Ubuntu 12.04 LTS \n \l

root@prodgrecosite:~/virtuoso-opensource# cat /proc/version
Linux version 3.2.0-67-generic (buildd@brownie) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #101-Ubuntu SMP Tue Jul 15 17:46:11 UTC 2014

root@prodgrecosite:~/virtuoso-opensource# ./binsrc/virtuoso/virtuoso-t -?                                                                                    Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.1.1-dev.3211-pthreads as of Aug 14 2014
Compiled for Linux (x86_64-unknown-linux-gnu)
Copyright (C) 1998-2014 OpenLink Software

root@prodgrecosite:~/virtuoso-opensource/binsrc/yacutia# make
PATH="/root/virtuoso-opensource/binsrc/virtuoso:/root/virtuoso-opensource/binsrc/tests:.:$PATH" PORT=1111 HOME="/root/virtuoso-opensource" HOST=localhost /bin/bash ./mkvad.sh

# 

=  CREATING VAD PACKAGE FOR VIRTUOSO CONDUCTOR (mkvad.sh)

# =  Mon Aug 18 18:15:44 BRT 2014

cp: omitting directory `dav'
cp: omitting directory`help'
cp: omitting directory `images'
cp: omitting directory`syntax'
cp: omitting directory `vad'
cp: omitting directory`dav/image'
cp: omitting directory `dav/image/dav'
cp: omitting directory`images/buttons'
cp: omitting directory `images/dav_browser'
cp: omitting directory`images/icons'
cp: omitting directory `/root/virtuoso-opensource/binsrc/oat/images/markers'
VAD Sticker vad_fs.xml creation...
VAD Sticker vad_dav.xml creation...
Starting Virtuoso server ...
The VDBMS server process terminated prematurely
after opening the database.
_**FAILED: Could not start Virtuoso Server within 120 seconds
make: *_\* [conductor_dav.vad] Error 1

---

mkvad.output

# 

=  CREATING VAD PACKAGE FOR VIRTUOSO CONDUCTOR (mkvad.sh)

# =  Mon Aug 18 18:18:57 BRT 2014

VAD Sticker vad_fs.xml creation...
VAD Sticker vad_dav.xml creation...

**\* Error S2801: [Virtuoso Driver]CL033: Connect failed to localhost:1111 = localhost:1111.
at line 0 of Top-Level:

Starting Virtuoso server ...

---

vad.log

```
            Mon Aug 18 2014
```

18:18:58 Error compiling a server init statement : 37000: SQ074: Line 1: Too many closing parentheses at ')' immediately before end of line -- _as_o)
{
if (isiri_id (s))
{
phys_s := s;
vectorbld_acc (phys_subjects, phys_s);
}
else
{
phys_s...
18:18:58 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at '', s, '' before 'maps' -- ', s, ' maps = ', maps);

}
vectorbld_ge_name any, in options any)
{
declare all_subj_descs, phy...
18:18:58 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at '[' before 's_ctr' -- bjs [s_ctr] := 0;

}
vectorbld_final (phys_subjects);
for (s_ctr := 0; s_ctr < all_s_count; s_c...
18:18:58 Error compiling a server init statement : 37000: SQ074: Line 1: Too many closing parentheses at ')' before ';' -- s_obj);
}
}
maps := subseq (maps, 0, maps_len-1);
maps_len := maps_len - 1;
}
if (maps_len > 0)
...
18:18:58 Error compiling a server init statement : 37000: SQ074: Line 1: Too many closing parentheses at '}' immediately before end of line -- }
else
{
final_tblname := DB.DBA.SQLQNAME_NOTATION_TO_QNAME (sqlcol[0], 3);
if (not exists (sele...
18:18:58 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at 'done' before '.' -- phs done...');
 ;
}
for (select RGGM_MEMBER_IID from DB.DBA.RDF_GRAPH_GROUP_MEMBER
where RGGM...
18:18:58 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at ''grant execute on DB.DBA.RDF_FORMAT_RESULT_SET_AS_RDF_XML_INIT to SPARQL_SELECT'' before ',' -- 'grant execute on DB.DBA.RDF_FORMAT_RESULT_SET_AS_RDF_XML_INIT to SPARQL_SELECT',
'grant execute...
18:18:58 Error executing a server init statement : 42001: SR185: Undefined procedure DB.DBA.RDF_CREATE_SPARQL_ROLES. -- DB.DBA.RDF_CREATE_SPARQL_ROLES ()

18:18:58 Error compiling a server init statement : 37000: SQ074: Line 2: syntax error at 'goto' before 'g_done' -- result ('00000', 'The resource <' || service_iri || '> exists but does not contain any RDF data,...
18:18:58 Error compiling a server init statement : 37000: SQ074: Line 2: syntax error at 'else' before 'if' -- DB.DBA.RDF_TRIPLES_TO_ATOM_XML_TEXT (triples, 1, ses);
else if (ret_format = 'JSON;ODATA')
DB.DB...
18:18:58 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at ''500'' before ',' -- '500', 'SPARQL Request Failed',
full_query, state3, msg3, format);
return;
}
dict_put (reported_...
18:18:58 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at '/' before 'x' -- cation/x-turtle, application/turtle, application/xml, _/_';

{
declare mtd, new_origin_uri_save ...
18:18:58 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at 'or' immediately before end of line -- l or
strstr (ret_content_type, 'application/rdf+n3') is not null or
strstr (ret_content_type, 'a...
18:18:59 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at 'DB' before '.' -- rom DB.DBA.SYS_USERS where U_NAME = http_map_get ('soap_uid'));
for select 0 as TP, P_NAME as op...
18:18:59 Error executing a server init statement : 22007: XM003: XML parser detected an error:
        ERROR  : More end tags than start tags
at line 4 column 21 of 'http://local.virt/soap_sch'
          /xsl:if
-------------------^
 --      <attribute ref="enc:arrayType" wsdl:arrayType
18:18:59 Error compiling a server init statement : 37000: SQ074: Line 1: syntax error at '=' before '\' -- name=\'Supporting\' type=\'wsse:SecurityTokenReferenceType\' />\n', ses);
http ('  <xs:element n...
18:18:59 Error executing a server init statement : 42001: SR185: Undefined procedure DB.DBA.WSRM_WSS0212_XSD. -- SOAP_LOAD_SCH (WSRM_WSS0212_XSD (), null, 0, 0)
18:19:00 Error executing a server init statement : 22007: XM003: XML parser detected an error:
        ERROR  : Character data are not allowed here by XML structure rules
at line 1 column 2 of 'http://local.virt/vspx_expand'
ribute name="name"><xsl:value-of select="$p" />_<xsl:value-of select="$c" />_h
-^
 -- ribute name="name"><xsl:value-of select="$p" />_<x

**Comment by HughWilliams** [comment]
Can you please provide complete copies of the following files in the ~/binsrc/yacutia directory for review :

vad.log
mkvad.output

**Comment by Kellli** [comment]
Here they are. 
Thanks

## Kelli

https://gist.github.com/Kellli/2340c75d8a679231c971#file-vad-log
https://gist.github.com/Kellli/2340c75d8a679231c971#file-mkvad-output

**Comment by Kellli** [comment]
Dear Hugh @openlink 

I've started a new installation on another server with the same configuration (Ubuntu 12.04) and it works fine after following guidelines of the issues #55, #219 and setting LC_ALL=en_US.utf8

But it still not working on the original server, even setting the LC_ALL. Maybe it is some other configuration that is causing some conflict.

I would like to thank very much the team and other users for supporting this issue!

Best regards
Kelli

**Comment by ArVr** [comment]
I had exact same problem. After deleting virtuoso ( <code> apt-get remove --purge virtuoso-opensource </code> ) i notice the same problem as you describe.  Than I tried to delete all the config files from the old Virtuoso 6 manual. But I screwed up my complete Ubuntu installation (fortunately I worked in a virtual box). After a fresh installation everything works fine.   

Greats 

Aron
