### ISSUE TITLE
suspect memory leak in virtjdbc4

### ISSUE THREAD

**Issue by jeremiehuchet** [openlink/virtuoso-opensource#235]
Hi, 
I'm running a test for learning purpose and I am badly surpised how my JVM memory is consumed.

I use the Virtuoso Jena Adapter over Virtuoso JDBC driver to insertsome thousands of triples. My algorithm is really simple : 

```
Graph g = new VirtGraph(...);
for each line as Triple, do
   g.add(triple);
done
```

When I run my test program, I see : 
- the amount of `VirtuosoPreparedStatement`/`VirtuosoResultSet` instances strictly increasing
- the amount of `VirtuosoFuture` instances increasing at long term
- almost all the cpu time is consumed by the garbage collector until I get a `java.lang.OutOfMemoryError`: GC overhead limit exceeded

I can tune the `Xmx` and the GC parameters.. I already set `Xmx`up to `1G`, I think its more than necessary.

I'm wondering if some `VirtuosoFuture` instances may not be properly released?

Regards,

**Comment by smalinin** [comment]
What kind of versions Virtuoso JDBC driver & Virtuoso Jena Adapter did you use?  One memory leak related with `PreparedStatement` was fixed in last updates. Use JDBC driver ver `3.73` and Jena adapter ver `2.12.0(build 1.11)`
p.s.
And try to use `BulkUpdateHandler` for insert your data, it will work much faster for insert bunch of triples.

**Comment by jeremiehuchet** [comment]
Hi, thanks for your advice. You're right, I was using an old driver :)
However I can't find the Jena Adapter ver `2.12.0(build 1.11)`, I tried [github](https://github.com/openlink/virtuoso-opensource/tree/stable/7/binsrc/jena2) and [virtuoso wiki](http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VOSDownload#Jena Provider).

(This bring me to another question, but I will open another issue for it !)

After upgrading to `virtjdbc 4.1 [Build 3.72]`, I'm still issuing something like a memory leak. 

p.s.
thanks for the tip, I saw it in the Jena API, but it has been marked `@Deprecated` since version `2.10.0`.

**Comment by smalinin** [comment]
The current `virt_jena2.jar` was not rebuilt, the version in source code (`Version.java` file) is `2.12.0(build 1.11)`. You could rebuild new binary or try to use [this precompiled binary](https://www.dropbox.com/s/n37spnmvbfcva1b/virt_jena2.jar?dl=0).

 About deprecated api:
You could also do the next:
1) create `InMemory` temporary `Model` and insert bunch of data to that `Model`
2) create `VirtDataset` object (from Virtuoso Jena Adapter) 
    It implements: `com.hp.hpl.jena.query.Dataset` interface (from `jena-arq`)

```
 VirtDataset vd = new VirtDataset (...);
 vd.addNamedModel("my_name", tmpInMemModel, false); //non standart Virtuoso Jena Adapter method
```

OR

```
 vd.addNamedModel("my_name", tmpInMemModel); //it will check, if graph "my_name" is existed already in DBMS, before insert data
```

**Comment by smalinin** [comment]
Addons:
The latest JDBC driver must be `Build 3.73` (based on current sources) the JDBC jars wasn't rebuilt else.
You could get JDBC drivers `Build 3.73` here ([JDBC 4.1](https://www.dropbox.com/s/rjfkxwwm9b3bb0e/virtjdbc4_1.jar?dl=0) or [JDBC 4.0](https://www.dropbox.com/s/dx4fep2egt2nm8e/virtjdbc4.jar?dl=0)) (or build it from source code)

I think, that JDBC driver `Build 3.72` doesn't have fix for Memory leaks.

**Comment by openlink** [comment]
I have updated the `develop/7` branch with rebuilt versions of Jena2, Sesame2 and Virtuoso JDBC drivers.

**Comment by jeremiehuchet** [comment]
Thanks, I will post feedback in a few days

**Comment by jeremiehuchet** [comment]
It's better with `build 3.73`, but it's not fixed.

I think you missed some of them, for instance in [`VirtuosoPreparedStatement`](https://github.com/openlink/virtuoso-opensource/blob/develop/7/libsrc/JDBCDriverType4/virtuoso/jdbc2/VirtuosoPreparedStatement.java#L362), the reference to the previously holded object in variable `future` is lost.

In addition, I observed a lot of `Finalizer`s. I suspects another leak issued from overrided `public void finalize()` methods. The garbage collector can't release objects before the `finalize()` method had been called. Some of the overrided methods seem to take too much time to execute and cause instances to be held in memory.

**Comment by smalinin** [comment]
The reference in `future` (in [`VirtuosoPreparedStatement`](https://github.com/openlink/virtuoso-opensource/blob/develop/7/libsrc/JDBCDriverType4/virtuoso/jdbc2/VirtuosoPreparedStatement.java#L362)) isn't lost, it is properly cleared by 'VirtuosoStatement.cancel()' method. 

The `Finalizer`s are required for properly close server side objects and for avoid leaks on server side, so it could not be removed. They don't create leak issue, it could create only a little garbage collector delay.  

But I will note, that some `Finalizer`s may be optimized, it will be done later.

**Comment by jbjares** [comment]
I'm with the same feeling. I don't know if I'm using the API properly, or if I'm with old driver version (with the related memory leak). 

Virtuoso Opensource Version: Merge branch 'release/7.1.0' into stable/7 under Ubuntu 12.04.5 LTS

Code: http://pastebin.com/PDeYvbNS
Elapsed Time for each file:  http://pastebin.com/ymigLyW2
Dependencies:  http://pastebin.com/k5XXdME4
Virtuoso .ini: http://pastebin.com/imniGhdA
Spring data source config: http://pastebin.com/qv9mf1rm

Thanks for help.

**Comment by smalinin** [comment]
It looks, that you used an old version of Jena and old version of Virtuoso Jena provider.  

Use new version of Jena Apache, new Virtuoso Jena provider `~/binsrc/jena2/virt_jena2.jar` and latest version of Virtuoso JDBC driver  `virtjdbc4.jar` 

Also, it looks, you will need replace `VirtDataSource` with `VirtDataset`.

**Comment by jbjares** [comment]
@smalinin, thanks a lot. I'll try it.

**Comment by HughWilliams** [comment]
Hi Can you confirm if this problem is still an issue for you particularly with the latest Virtuoso 7.2 release?

**Comment by danizen** [comment]
I see a memory leak when my Tomcat instance dynamically reloads a WAR that is using Virtuoso JDBC through JNDI.   The leak occurs because `VirtuosoPoolManager` has no capability to clean-up its two threads.

I've seen the leak now using both JDK Mission Control and VisualVm.    I don't think it is the same as this issue, but I was looking for similar JVM leaks.

**Comment by smalinin** [comment]
It is not memory leak, the `VirtuosoPoolManager` uses two daemon threads for pool tasks, so you have such problem. You must to use the `Tomcat JDBC Connection Pool`, it is the easy way.
I could to add a method for shutdown  `VirtuosoPoolManager`, but you will need update  your application also for use such method, so easy way is using  `Tomcat JDBC Connection Pool`.
