### ISSUE TITLE
42000 COL..: insert fetch column must be typed int or iri id

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#238]
In b4a5b8325934844cc0f921617e7c9da1287f9e94 I cannot load <a href="http://v7.xrg.cz/micr.zip">this file</a> using the standard way:
<code><pre>ld_dir('/usr/local/var/lib/virtuoso/upload','*.ttl','');
rdf_loader_run();
</pre></code>
I get:
<code>14:39:39 PL LOG:  File /usr/local/var/lib/virtuoso/upload/MICR_3-gov-cz-agendy.ttl error 42000 COL..: insert fetch column must be typed int or iri id
</code>

This also happens with other files.

It did not happen with the commit from end of August: b5abc441deb1fb6325ff88f219fd328818458cce

**Comment by HughWilliams** [comment]
I have been able to recreate with the open source develop/7 branch , but works with closed source so probably missing patch. We shall look into this ...

**Comment by jimkont** [comment]
I have the same problem both with loader script as well as with DB.DBA.RDF_LOAD_RDFXML

**Comment by jimkont** [comment]
I instance is based on b4a5b8325934844cc0f921617e7c9da1287f9e94
@HughWilliams can you give an estimate on the fix or suggest a commit to rollback

**Comment by openlink** [comment]
There are 2 separate patches (e5b9cf1 and bab3882) which together should resolve this problem. Please update your archive to the latest develop/7 and me know what happens.

**Comment by jimkont** [comment]
Works for me, thanks!

**Comment by jakubklimek** [comment]
Works for me as well.
