### ISSUE TITLE
distribute via maven central

### ISSUE THREAD

**Issue by jeremiehuchet** [openlink/virtuoso-opensource#249]
Why don't you distribute the JDBC driver and the Jena provider via maven central repository ?
It would make life easier for a lot of developers.

**Comment by HughWilliams** [comment]
It is on the todo at some point ...

**Comment by nvdk** [comment]
:+1:

**Comment by furver** [comment]
[+1]

**Comment by tlomb** [comment]
[+1]

**Comment by gtrefs** [comment]
:100:

**Comment by nandana** [comment]
+1

**Comment by amalic** [comment]
+1

**Comment by MarcelMager** [comment]
[+ 1]

**Comment by tfrancart** [comment]
+1

**Comment by dikshantshahi** [comment]
+1

**Comment by iesnaola** [comment]
+1

**Comment by vimaldarjiv26** [comment]
when the JDBC driver and the Jena provider via maven central repository available?

**Comment by senaarpinar** [comment]
+1

**Comment by codehustler** [comment]
we approach 2019 and the driver is still not in maven central 👎

**Comment by reckart** [comment]
Just a note: if the license of the software permits, anybody can do **third-party upload** to Maven Central. It is a good idea to obtain consent from the actual maintainers (in particular if their groupId is used for the deployment). The process of manually bundling resources and uploading them to Maven Central is described [here](https://central.sonatype.org/pages/manual-staging-bundle-creation-and-deployment.html).

For more info, check out the [OSSRH Guide](https://central.sonatype.org/pages/ossrh-guide.html) (guide to Maven Central).

**Comment by TallTed** [comment]
@smalinin @pkleef @openlink 

It looks like PR #156 (April 2014) and/or PR #587 (October 2016) would close this...

**Comment by arthurhaelterman** [comment]
+1

**Comment by mynameisbill2** [comment]
+1

**Comment by ledsoft** [comment]
Hi, I created a PR (#905) with Mavenization of the RDF4J provider. It uses the current RDF4J (3.1.2). Still doesn't solve the missing JDBC driver in Maven, but maybe it could help at least a little bit.

**Comment by HughWilliams** [comment]
@ledsoft: OpenLink are in the process of setting up a [nexus](https://www.sonatype.com/nexus-repository-oss) repository for distributing our Java (and ADO.Net, etc.) client components. Development will be reviewing your [#905](https://github.com/openlink/virtuoso-opensource/pull/905) PR ...

**Comment by ledsoft** [comment]
Is there any progress on this. Can I help somehow? Thanks

**Comment by TallTed** [comment]
@HughWilliams @openlink -- Where does this stand?

**Comment by jeremiehuchet** [comment]
@openlink @HughWilliams @smalinin @pkleef,  
Hope you won't mind me publishing virtuoso driver to a [public maven repository](https://bintray.com/jeremiehuchet/virtuoso-drivers/virtuoso-jdbc/).  
Please let me know if there is any licensing issue. I took care of shipping the GPL v2 and your copying notice in the JAR files.

I host a copy of the [JDBC generated source files](https://github.com/jeremiehuchet/virtuoso-drivers) to make it easier.

I would be glad to help you setup your official repository.

**Comment by openlink** [comment]
There should not be a licensing issue with this approach.

OpenLink is working on getting all our providers registered on maven, however you seem to use a `com.openlink` groupID which may be a problem. Once we finalize our providers for publication, we would like to use a centralized location, so users can be sure they use the latest bugfix releases for all of our JDBC drivers as well as Jena and RDF4J providers, etc.

We would appreciate any help in the form of scripts you use to register your version, as this would speed up finalizing this work. I saw some pull requests from another user and I will be looking to integrate it into the tree. 

Submissions can be made either via pull requests, or via private email to vos.admin@openlinksw.com.

**Comment by jeremiehuchet** [comment]
I renamed the artifacts' groupId to `unofficial.com.openlink` to make it clear for users they are not using libraries built officially.

**Comment by pkleef** [comment]
OpenLink has published its Virtuoso JDBC drivers as well as its Jena and RDF4j providers to maven central:

https://community.openlinksw.com/t/openlink-virtuoso-java-artifacts-on-maven-central
