### ISSUE TITLE
xsd:boolean returned as xsd:integer

### ISSUE THREAD

**Issue by Rahien** [openlink/virtuoso-opensource#251]
Hi,

When using virtuoso on Ubuntu linux 14.04 64Bit, and building virtuoso from source using commit 57052e50328c77ce7814efe6a14681b4e8360608, it have the problem that I input a value in an rdf file using the xsd:boolean datatype 

```
<ns5:isIndirect rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">false</ns5:isIndirect>
```

and I get it back as an xsd:integer 

```
<ns5:isIndirect rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">0</ns5:isIndirect>
```

I am using the quad store upload functionality with an xml/rdf file in the conductor.

Could you have a look?

Thanks!

**Comment by HughWilliams** [comment]
It is known that virtuoso store boolean types as integers as it does not have a boolean type, but you should be able to perform boolean operations data stored as such.

Can you provide the actually queries being run to insert and retrieve the data ?

**Comment by Rahien** [comment]
Hi Hugh,

Thanks for your quick response! I don't have a problem with the boolean operations not working. I simply insert an rdf file into the store using the quad store upload in the conductor and then use a basic construct query on that graph to get it back out

```
construct {?s ?p ?o} where { graph <http://localhost/target> { ?s ?p ?o} }
```

The problem is that our taxonomy specifies that the isIndirect property is actually of the boolean type, not integer. So I was hoping for a workaround for this one...

**Comment by HughWilliams** [comment]
Hi Karel,  Can you provide a sample dataset or triple I can load to see this problem ?

**Comment by Rahien** [comment]
Hi Hugh,

The scenario is as follows. 

## 1 ontology

Say that we publish an ontology, for instance a simple ontology with a single property 'isIndirect':

```
<?xml version="1.0"?>
<!DOCTYPE rdf:RDF [
  <!ENTITY ex  "http://example.org/" >
  <!ENTITY xsd  "http://www.w3.org/2001/XMLSchema#" > ]>

<rdf:RDF 
    xmlns     ="http://example.org/" 
    xmlns:ex ="http://example.org/"       
    xmlns:owl ="http://www.w3.org/2002/07/owl#"
    xmlns:rdf ="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"> 
  <owl:Ontology rdf:about="">
    <rdfs:comment>example ontology</rdfs:comment>
  </owl:Ontology>

  <owl:DatatypeProperty rdf:about="http://example.org/isIndirect">
    <rdfs:range rdf:resource="&xsd;boolean"/>
  </owl:DatatypeProperty>
</rdf:RDF>
```

The range of the 'isIndirect' property is defined as a boolean.

This ontology needs not be loaded in our triple store, but is simply published online so our content providers know which type of data we expect.

---

## 2 content provided

Then one of our content providers sends us a dataset, for instance the dataset below:

```
<?xml version="1.0"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:ex="http://example.org/">
  <rdf:Description rdf:about="http://example.org/thing">
    <ex:isIndirect rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">false</ex:isIndirect>
  </rdf:Description>
</rdf:RDF>
```

Note that the dataset complies with the ontology, the value of the 'isIndirect' property has a boolean datatype.

I load this example into the store using quad store upload in the conductor. I create a new graph http://localhost/example doing so.

---

## 3 content consumed

I then run the following query in the regular Virtuoso sparql interface (hosted at http://localhost:8890/sparql by default):

```
construct {
?s ?p ?o
} where {
 graph <http://localhost/example> {
  ?s ?p ?o
 }
}
```

I use the RDF/XML datatype available in the drop down and this gives me the new file below:

```
<?xml version="1.0" encoding="utf-8" ?>
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:ns2="http://example.org/" >
  <rdf:Description rdf:about="http://example.org/thing">
    <ns2:isIndirect rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">0</ns2:isIndirect>
  </rdf:Description>
</rdf:RDF>
```

In this file, the datatype of the 'isIndirect' property has changed to an integer, so content consumers of our service receive data that does not comply to our ontology any more.

**Comment by kidehen** [comment]
On 10/30/14 3:19 PM, Karel Kremer wrote:

> Hi Hugh,
> 
> The scenario is as follows.
> 
> ```
> 1 ontology
> ```
> 
> Say that we publish an ontology, for instance a simple ontology with a 
> single property 'isIndirect':
> 
> |<?xml version="1.0"?>
> <!DOCTYPE rdf:RDF [
>    <!ENTITY ex  "http://example.org/" >
>    <!ENTITY xsd  "http://www.w3.org/2001/XMLSchema#" > ]>
> 
> <rdf:RDF
>      xmlns     ="http://example.org/"
>      xmlns:ex ="http://example.org/"
>      xmlns:owl ="http://www.w3.org/2002/07/owl#"
>      xmlns:rdf ="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
>      xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
>    <owl:Ontology rdf:about="">
>      rdfs:commentexample ontology/rdfs:comment
>    /owl:Ontology
> 
>    <owl:DatatypeProperty rdf:about="http://example.org/isIndirect">
>      <rdfs:range rdf:resource="&xsd;boolean"/>
>    /owl:DatatypeProperty
> /rdf:RDF
> |
> 
> The range of the 'isIndirect' property is defined as a boolean.
> 
> This ontology needs not be loaded in our triple store, but is simply 
> published online so our content providers know which type of data we 
> expect.
> 
> ---
> 
> ```
> 2 content provided
> ```
> 
> Then one of our content providers sends us a dataset, for instance the 
> dataset below:
> 
> |<?xml version="1.0"?>
> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
>           xmlns:ex="http://example.org/">
>    <rdf:Description rdf:about="http://example.org/thing">
>      <ex:isIndirect rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">false/ex:isIndirect
>    /rdf:Description
> /rdf:RDF
> |
> 
> Note that the dataset complies with the ontology, the value of the 
> 'isIndirect' property has a boolean datatype.
> 
> I load this example into the store using quad store upload in the 
> conductor. I create a new graph http://localhost/example doing so.
> 
> ---
> 
> ```
> 3 content consumed
> ```
> 
> I then run the following query in the regular Virtuoso sparql 
> interface (hosted at http://localhost:8890/sparql by default):
> 
> |construct {
> ?s ?p ?o
> } where {
>   graph http://localhost/example {
>    ?s ?p ?o
>   }
> }
> |
> 
> I use the RDF/XML datatype available in the drop down and this gives 
> me the new file below:
> 
> |<?xml version="1.0" encoding="utf-8" ?>
> <rdf:RDF
>      xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
>      xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
>      xmlns:ns2="http://example.org/" >
>    <rdf:Description rdf:about="http://example.org/thing">
>      <ns2:isIndirect rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">0/ns2:isIndirect
>    /rdf:Description
> /rdf:RDF
> |
> 
> In this file, the datatype of the 'isIndirect' property has changed to 
> an integer, so content consumers of our service receive data that does 
> not comply to our ontology any more.

That's a serialization bug! It shouldn't be printing xsd:integer .

We already handle xsd:boolean, in its many datatype guises: 
"1"^^xsd:boolean, "true"^^xsd:boolean, "0"^^xsd:boolean, 
"false"^^xsd:boolean .

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by HughWilliams** [comment]
Hi Karel, Thanks I have been able to recreate and reported to development to fix ... will let you know when the fix is available ...

**Comment by jakubklimek** [comment]
@HughWilliams  As discussed in our call, I retested the xsd:boolean support and 

<pre><code>select * where {
BIND (strdt(true, xsd:boolean) as ?boolean)
}</pre></code> 
still returns 1 instead of <code>true</code>
so does <pre><code>select * where {
BIND (true as ?boolean)
}</code></pre>

and

<pre><code>select \* where {
BIND (strdt("true", xsd:boolean) as ?boolean)
}</pre></code>

**Comment by kidehen** [comment]
On 1/16/15 9:13 AM, Jakub Klímek wrote:

> @HughWilliams https://github.com/HughWilliams As discussed in our 
> call, I retested the xsd:boolean support and
> 
> |select \* where {
> 
> BIND (strdt(true, xsd:boolean) as ?boolean)
> 
> }|
> still returns 1 instead of |true|

This isn't the test to perform. What you should be doing is making a 
boolean test based on 1 or true. We only have a problem if the boolean 
test presents contradictory solutions.

You are better of making a SPARQL ASK test rather than the kind of 
SELECT you've presented above.

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by jakubklimek** [comment]
OK, what about that

<pre><code>select * where {
BIND (datatype(strdt("true", xsd:boolean)) as ?string)
}</code></pre>

returns <code>xsd:interger</code>... that shoud return xsd:boolean as it does in Jena Fuseki, for instance

**Comment by IvanMikhailov** [comment]
Bools will stay integers as long as there's no BOOL in our SQL engine. Sorry. The  datatype(strdt("true", xsd:boolean)) = xsd:integer looks funny indeed, but that will stay so for some noticeable time. Version 7.5 will clearly miss BOOL type in SQL, for future versions it is not yet decided.

**Comment by JervenBolleman** [comment]
I want to report that this bug is affecting us as well.

**Comment by HughWilliams** [comment]
@JervenBolleman: We are nearing completion of the addition of xsd:boolean support in the SPARQL engine, which should be in place in the next two weeks ...

**Comment by HughWilliams** [comment]
@JervenBolleman: Support for xsd:boolean type has been added the the Virtuoso SPARL engine in the latest develop/7 branch ...

**Comment by JervenBolleman** [comment]
@HughWilliams I think this issue can be closed as fixed on the development branch. Thanks!
