### ISSUE TITLE
Union with multiple binds fails in SPARQL compiler (2)

### ISSUE THREAD

**Issue by knoan** [openlink/virtuoso-opensource#252]
Virtuoso Version: 07.10.3209

```
select

    ?direct ?link ?term

where {

    { select distinct ?direct ?link ?term where {

        bind (<tag:metreeca.net;2013:birt/offices/7> as ?0)

        {

            ?0 ?link ?term bind (true as ?direct)

        } union {

            ?term ?link ?0 bind (false as ?direct)

        }

    } }

}
```

Fails with:

```
Virtuoso 37000 Error SP031: SPARQL: Internal error: ssg_tmpl_X_of_Y(): bad mode needed
```
- The query is a stripped down version of a larger one generated by an interactive linked data analytics tool.
- Fine without union.
- Very likely related to #212 and #253

**Comment by HughWilliams** [comment]
I have added this ( & 253) to the internal ticket for 212 to be looked into by development ...

**Comment by openlink** [comment]
Pushed fix for this in deveop/7 branch
