### ISSUE TITLE
VIrtuoso 7.1 server randomly shutting itself down

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#261]
I have a few virtuoso servers, but I have one that is randomly shutting itself down.  See log excerpt here (Version 07.10.3207-pthreads for Linux as of Sep 17 2014).  Any thoughts to what this might be?  It's running on a Linux 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Nov 6 15:06:03 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux server.

**\* snip ***
15:20:51 Checkpoint started
15:20:51 Checkpoint finished, log reused
16:20:52 Checkpoint started
16:20:52 Checkpoint finished, log reused
17:20:55 Checkpoint started
17:20:55 Checkpoint finished, log reused
18:20:55 Checkpoint started
18:20:55 Checkpoint finished, log reused
18:33:32 Server received signal 1
18:33:32 Initiating quick shutdown
18:33:32 Server shutdown complete
**\* end snip ****

**Comment by ebremer** [comment]
I dug into this one more and found the cause.  This is my first centos7 box.  If I launch virtuoso using nohup, the moment I close the shell window, nohup fails and virtuoso shuts down.  I switched to "screen" and now virtuoso stays running.

**Comment by HughWilliams** [comment]
How do you actually start virtuoso, as if you start  with "virtuoso-t  -c virtuoso.ini"  it will run in background mode and will not shutdown after you log out ?

**Comment by kidehen** [comment]
On 12/2/14 12:21 PM, HughWilliams wrote:

> How do you actually start virtuoso, as if you start with "virtuoso-t 
> -c virtuoso.ini" it will run in background mode and will not shutdown 
> after you log out ?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/openlink/virtuoso-opensource/issues/261#issuecomment-65268225.

You can run it in a screen:
1. screen -S {some-screen-name}
2. then virtuoso -c <ini-file> -f
3. ctrl+a+d to exit screen .

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by ebremer** [comment]
Hugh,
From within the db folder:
nohup virtuoso-t -f &
which is generally how I run background processes without issue, but, this is my first Centos 7 box.

Kingsley,
Yup, screen is cool and I don't even need the nohup at this point.

I'm still curious why the nohup seems to be failing, but I'm glad this virtuoso instance is now running without shutting down.
