### ISSUE TITLE
Faceted browser does not support text/turtle MIME type in content negotiation

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#264]
When I do
<code>curl -I -H "Accept: rdf/turtle"  http://linked.opendata.cz/resource/business-entity/CZ01475461</code>, I would expect the Turtle representation of the above entity (link leads to Virtuoso faceted browser) or a HTTP 303 See Other. This is actually what the <a href="http://validator.lod-cloud.net/validate.php">LOD Cloud dataset validator</a> expects.

Instead, I get:

<pre><code>HTTP/1.1 406 Not Acceptable
Date: Thu, 27 Nov 2014 15:15:41 GMT
Server: Virtuoso/07.10.3211 (Linux) x86_64-unknown-linux-gnu
Content-Type: text/html; charset=UTF-8
Accept-Ranges: bytes
Alternates: { "http://localhost:8890/describe/?url=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461" 0.5 {type text/html}}, 
{ "http://localhost:8890/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=text%2Fn3" 0.80 {type text/n3}}, 
{ "http://localhost:8890/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=text%2Frdf%2Bn3" 0.80 {type text/rdf+n3}}, 
{ "http://localhost:8890/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=application%2Frdf%2Bxml" 1.00 {type application/rdf+xml}}, 
{ "http://localhost:8890/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=application%2Fjson" 0.70 {type application/json}}, 
{ "http://localhost:8890/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=text%2Fplain" 0.10 {type text/plain}}
Vary: Accept-Encoding
</code></pre>

It works OK with the mime-types mentioned in the error response, however, faceted browser should be updated to handle more mime-type variants, especially those mentioned in standards like http://www.w3.org/TR/turtle/

**Comment by kidehen** [comment]
On 11/27/14 10:25 AM, jakubklimek wrote:

> When I do
> |curl -I -H "Accept: rdf/turtle" 
> http://linked.opendata.cz/resource/business-entity/CZ01475461|, I 
> would expect the Turtle representation of the above entity (link leads 
> to Virtuoso faceted browser) or a HTTP 303 See Other. This is actually 
> what the LOD Cloud dataset validator 
> http://validator.lod-cloud.net/validate.php expects.

"rdf/turtle" isn't a recognized content-type. Please use "text/turtle" .

Also look at the footer links in the Faceted Browser page for the 
corrent URI and content-type combos.

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by jakubklimek** [comment]
You are right, of course, the standard is <code>text/turtle</code>. Nevertheless, the issue stands:
for <code>curl -I -H "Accept: text/turtle" http://linked.opendata.cz/resource/business-entity/CZ01475461</code> I get the same response. If I specify it explicitly in the describe query suggested by fct (&format=text/turtle - this one as you can see in the output is not offered), it works and I get Turtle. What is missing is the 303 redirect as it is for the other MIME types.

**Comment by jakubklimek** [comment]
E.g. how it works for text/rdf+n3 is <pre><code>curl -I -H "Accept: text/rdf+n3" http://linked.opendata.cz/resource/business-entity/CZ01475461
HTTP/1.1 303 See Other
Date: Fri, 28 Nov 2014 19:39:45 GMT
Server: Virtuoso/07.10.3211 (Linux) x86_64-unknown-linux-gnu
Content-Type: text/html; charset=UTF-8
Accept-Ranges: bytes
TCN: choice
Vary: negotiate,accept,Accept-Encoding
Location: http://linked.opendata.cz/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=text%2Frdf%2Bn3
</code></pre>

**Comment by kidehen** [comment]
On 11/28/14 2:37 PM, jakubklimek wrote:

> You are right, of course, the standard is |text/turtle|. Nevertheless, 
> the issue stands:
> for |curl -I -H "Accept: text/turtle" 
> http://linked.opendata.cz/resource/business-entity/CZ01475461| I get 
> the same response. If I specify it explicitly in the describe query 
> suggested by fct (&format=text/turtle - this one as you can see in the 
> output is not offered), it works and I get Turtle. What is missing is 
> the 303 redirect as it is for the other MIME types.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/openlink/virtuoso-opensource/issues/264#issuecomment-64923700.

You appear to be handling this yourself, so shouldn't you be 
implementing the re-write rule? If you are using the faceted browsing 
service exposed by the default endpoint 
http://{cname}/describe/?uri={entity-uri}, you should end up with what 
you see on dbpedia and dbpedia-live:
1. http://dbpedia.org/describe/?uri=http://dbpedia.org/resource/Linked_data
2. 
   http://dbpedia-live.openlinksw.com/describe/?uri=http://dbpedia.org/resource/Linked_data

Example:

curl -I 
http://dbpedia-live.openlinksw.com/describe/?uri=http://dbpedia.org/resource/Linked_data

Link: response example:

Link: 
http://dbpedia-live.openlinksw.com/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLinked_data%3E&output=application%2Frdf%2Bxml; 
rel="alternate"; type="application/rdf+xml"; title="Structured 
Descriptor Document (RDF/XML 
format)",http://dbpedia-live.openlinksw.com/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLinked_data%3E&output=text%2Fn3; 
rel="alternate"; type="text/n3"; title="Structured Descriptor Document 
(N3/Turtle 
format)",http://dbpedia-live.openlinksw.com/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLinked_data%3E&output=application%2Frdf%2Bjson; 
rel="alternate"; type="application/rdf+json"; title="Structured 
Descriptor Document (RDF/JSON 
format)",http://dbpedia-live.openlinksw.com/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLinked_data%3E&output=application%2Fatom%2Bxml; 
rel="alternate"; type="application/atom+xml"; title="Structured 
Descriptor Document (OData/Atom 
format)",http://dbpedia-live.openlinksw.com/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLinked_data%3E&output=application%2Fodata%2Bjson; 
rel="alternate"; type="application/odata+json"; title="Structured 
Descriptor Document (OData/JSON 
format)",http://dbpedia-live.openlinksw.com/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLinked_data%3E&output=text%2Fcxml; 
rel="alternate"; type="text/cxml"; title="Structured Descriptor Document 
(CXML 
format)",http://dbpedia-live.openlinksw.com/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLinked_data%3E&output=text%2Fcsv; 
rel="alternate"; type="text/csv"; title="Structured Descriptor Document 
(CSV 
format)",http://dbpedia-live.openlinksw.com/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLinked_data%3E&output=application%2Fmicrodata%2Bjson; 
rel="alternate"; type="application/microdata+json"; title="Structured 
Descriptor Document (Microdata/JSON 
format)",http://dbpedia-live.openlinksw.com/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLinked_data%3E&output=text%2Fhtml; 
rel="alternate"; type="text/html"; title="Structured Descriptor Document 
(HTML+Microdata 
format)",http://dbpedia-live.openlinksw.com/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FLinked_data%3E&output=application%2Fld%2Bjson; 
rel="alternate"; type="application/ld+json"; title="Structured 
Descriptor Document (JSON-LD 
format)",http://dbpedia.org/resource/Linked_data; 
rel="http://xmlns.com/foaf/0.1/primaryTopic", <?first>; rel="first", 
<?last>; rel="last", <?next>; rel="next", <?prev>; rel="prev", 
http://dbpedia.org/resource/Linked_data; rev="describedby"

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by jakubklimek** [comment]
Well, yes, I could handle the content negotiation myself in Apache or something similar, but that is not the point, I thought that is what fct is for.
I still think it is a fct issue, because it works with some content types and does not with others.
It works fine (gives 303 redirect) with <code>text/n3</code>, <code>text/rdf+n3</code>, <code>application/rdf+xml</code>, <code>application/json</code>, <code>text/plain</code>.

So I don't get why it should not work with standard RDF syntaxes and their content types:
<a href="http://www.w3.org/TR/2014/REC-trig-20140225/#sec-mime">TriG</a>: <code>application/trig</code>, <a href="http://www.w3.org/TR/2014/REC-turtle-20140225/#sec-mime">Turtle</a>: <code>text/turtle</code>, <a href="http://www.w3.org/TR/2014/REC-n-triples-20140225/#n-triples-mediatype">N-Triples</a>: <code>application/n-triples</code>, <a href="http://www.w3.org/TR/2014/REC-n-quads-20140225/#sec-mediatype">N-Quads</a>: <code>application/n-quads</code>

**Comment by kidehen** [comment]
On 11/29/14 2:47 PM, jakubklimek wrote:

> Well, yes, I could handle the content negotiation myself in Apache or 
> something similar, but that is not the point, I thought that is what 
> fct is for.
> I still think it is a fct issue, because it works with the other 
> content types and does not with others.
> It works fine (gives 303 redirect) with |text/n3|, |text/rdf+n3|, 
> |application/rdf+xml|, |application/json|, |text/plain|.
> 
> So I don't get why it should not work with standard RDF syntaxes and 
> their content types:
> TriG http://www.w3.org/TR/2014/REC-trig-20140225/#sec-mime: 
> |application/trig|, Turtle 
> http://www.w3.org/TR/2014/REC-turtle-20140225/#sec-mime: 
> |text/turtle|, N-Triples 
> http://www.w3.org/TR/2014/REC-n-triples-20140225/#n-triples-mediatype: 
> |application/n-triples|, N-Quads 
> http://www.w3.org/TR/2014/REC-n-quads-20140225/#sec-mediatype: 
> |application/n-quads|
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/openlink/virtuoso-opensource/issues/264#issuecomment-64962974.

The long standing issue, cropping up here too, is the notion of 
"text/rdf+n3" (an obsolete experimental content type) which still sits 
in for "text/turtle" (an actual content type).

Hence:
curl -IH "Accept: text/rdf+n3" 
http://linked.opendata.cz/resource/business-entity/CZ01475461
HTTP/1.1 303 See Other
Date: Sat, 29 Nov 2014 22:00:52 GMT
Server: Virtuoso/07.10.3211 (Linux) x86_64-unknown-linux-gnu
Content-Type: text/html; charset=UTF-8
Accept-Ranges: bytes
TCN: choice
Vary: negotiate,accept,Accept-Encoding
Location: 
http://linked.opendata.cz/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=text%2Frdf%2Bn3

And:
curl -IH "Accept: text/turtle" 
http://linked.opendata.cz/resource/business-entity/CZ01475461
HTTP/1.1 406 Not Acceptable
Date: Sat, 29 Nov 2014 22:01:38 GMT
Server: Virtuoso/07.10.3211 (Linux) x86_64-unknown-linux-gnu
Content-Type: text/html; charset=UTF-8
Accept-Ranges: bytes
Alternates: { 
"http://localhost:8890/describe/?url=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461" 
0.5 {type text/html}}, { 
"http://localhost:8890/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=text%2Fn3" 
0.80 {type text/n3}}, { 
"http://localhost:8890/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=text%2Frdf%2Bn3" 
0.80 {type text/rdf+n3}}, { 
"http://localhost:8890/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=application%2Frdf%2Bxml" 
1.00 {type application/rdf+xml}}, { 
"http://localhost:8890/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=application%2Fjson" 
0.70 {type application/json}}, { 
"http://localhost:8890/sparql?query=define%20sql%3Adescribe-mode%20%22LOD%22%20%20DESCRIBE%20%3Chttp%3A%2F%2Flinked.opendata.cz%2Fresource%2Fbusiness-entity%2FCZ01475461%3E&format=text%2Fplain" 
0.10 {type text/plain}}

Conclusion:

This is a known bug, so you are correct in your bug claim! Luckily, this 
is one that's already been reported internally months ago and will be 
fixed any minute. The darn problem is that we have "text/rdf+n3" all 
over the place where it should be "text/turtle" :(

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this
