### ISSUE TITLE
SPARQL: filter and optional clause influencing bug

### ISSUE THREAD

**Issue by joernhees** [openlink/virtuoso-opensource#27]
It seems as if the current SPARQL parser has a bug wrt. same level co-existence
of FILTER and OPTIONAL clauses. In the following example i would expect to get
all ?p ?o candidates for Einstein where ?o is an IRI and ?t never bound (the OPTIONAL should be
unmatched).

``` sparql
SELECT * WHERE {
    dbpedia:Albert_Einstein ?p ?o.
    FILTER(isIRI(?o))
    OPTIONAL { ?o <http://example.com/foo> ?t. }
}
```

If you run this against http://dbpedia.org/sparql it returns nothing: [1](http://dbpedia.org/sparql?qtxt=select+*+where+{%0D%0A++++dbpedia%3AAlbert_Einstein+%3Fp+%3Fo.%0D%0A++++FILTER%28isIRI%28%3Fo%29%29%0D%0A++++OPTIONAL+{+%3Fo+%3Chttp%3A%2F%2Fexample.com%2Ffoo%3E+%3Ft.+}%0D%0A}%0D%0A)
Seems as if the filter clause changed the optional clause to be mandatory.
If you leave the filter part away you get a results as expected.

Here is a workaround based on double brackets:

``` sparql
SELECT * WHERE {
    {
        dbpedia:Albert_Einstein ?p ?o.
        FILTER(isIRI(?o))
    }
    OPTIONAL { ?o <http://example.com/foo> ?t. }
} LIMIT 10
```

It's a mean bug in bigger queries though :-/

**Comment by openlink** [comment]
We are working on a solution. Will advice as soon as it is committed.

**Comment by openlink** [comment]
This issue has been fixed in develop/7 and will be part of the upcoming release

**Comment by joernhees** [comment]
:+1:
