### ISSUE TITLE
List graphs query stops working after Virtuoso restart

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#290]
Commit: 3e7d5423cddb7a05bbf63094b2cf55be2943e572
Database: same as in https://github.com/openlink/virtuoso-opensource/issues/286
1) I created some data in graphs in a new db using UnifiedViews to demonstrate another issue - it uses Sesame2 JDBC driver to access Virtuoso. After creating the data, which ended with an error seen in https://github.com/openlink/virtuoso-opensource/issues/286 I ran a query used by @HughWilliams :

<pre><code>SELECT distinct ?graph WHERE { GRAPH ?graph { ?s ?p ?o } }</code></pre>

And got:

<pre><code>
graph
http://www.openlinksw.com/schemas/virtrdf#
http://www.w3.org/ns/ldp#
http://localhost:8890/sparql
http://localhost:8890/DAV/
http://www.w3.org/2002/07/owl#
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/194/du/0
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/3
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/2
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/181/du/0
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/5
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/196/du/1
http://unifiedviews.eu/resource/internal/data
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/180/du/0
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/179/du/0
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/189/du/0
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/188/du/1
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/193/du/1
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/6
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/177/du/1
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/4
</code></pre>

I also ran:

<pre><code>
select count (*) where {?s ?p ?o}
</code></pre>

And got:

<pre><code>
callret-0
172281
</code></pre>

So far so good.
Now I did checkpoint (interactive sql in conductor), just to be sure that all the data is written to the disk and that I can shut down Virtuoso without data loss and ran <code>/etc/init.d/virtuoso-opensource stop</code> to shut down virtuoso.

Then I ran <code>/etc/init.d/virtuoso-opensource start</code> to start it again and I ran the same 2 queries.
The count one got me the same number of triples, however, the list graphs one now gives:

<pre><code>
graph
http://www.openlinksw.com/schemas/virtrdf#
http://www.w3.org/2002/07/owl#
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/5
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/4
</code></pre>

Note that even some of the Virtuoso initial graphs are not listed, even though I did not touch them.

Now the weird thing is, that a query that I use to list graphs (and number of triples in them):

<pre><code>
select ?g count (?s) where {graph ?g {?s ?p ?o}} group by ?g order by desc(count(?s))
</code></pre>

still works and returns:

<pre><code>
g   callret-1
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/3 38189
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/6 35251
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/2 31845
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/4 31507
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1/entry/5 29440
http://localhost:8890/DAV/  2995
http://www.openlinksw.com/schemas/virtrdf#  2647
http://www.w3.org/2002/07/owl#  160
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/193/du/1 120
http://unifiedviews.eu/resource/internal/data   54
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/177/du/1 15
http://localhost:8890/sparql    14
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/190/du/1 12
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/188/du/1 12
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/194/du/0 3
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/179/du/0 3
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/189/du/0 3
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/180/du/0 3
http://www.w3.org/ns/ldp#   3
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/181/du/0 3
http://unifiedviews.eu/resource/internal/dataunit/exec/161/dpu/196/du/1 2
</code></pre>

**Comment by HughWilliams** [comment]
@jakubklimek: I see what you mean and have reported to development to look into. How were these graphs created i.e. implicit (via sparql update query) or explicit (via data load) ?

**Comment by jakubklimek** [comment]
All the unifiedviews graphs are created using the Sesame2 Virtuoso driver via SPARQL Update queries.

**Comment by HughWilliams** [comment]
@jakubklimek: This problem has been fixed in the latest git develop/7 branch ...

**Comment by jakubklimek** [comment]
I confirm
