### ISSUE TITLE
Empty group pattern leads to empty result

### ISSUE THREAD

**Issue by schwarja** [openlink/virtuoso-opensource#291]
I have this query with empty group pattern which gives empty result:

```
SELECT ?X WHERE
{
    VALUES ?X {1 2}
    {}
    FILTER (?X > 1)
}
```

According to SPARQL 1.1 documentation (http://www.w3.org/TR/sparql11-query/#emptyGroupPattern):

"The group pattern:
{ }
matches any graph (including the empty graph) with one solution that does not bind any variables."

So as far as I am concerned the result should have one row with "2".

**Comment by rumito** [comment]
Hi Schwarja,
Thank you for reporting this issue.
We have been able to reproduce it and our developers team is already notified ..
