### ISSUE TITLE
Weird slow down for small change in a SPARQL query

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#293]
I have a SPARQL query that has a nested sub-query with a grouping,  It takes three seconds to execute.  Adding one "?target :relation ?someuri" where :relation and ?someuri isn't used in the rest of the query and the query then times out after three minutes (I have the timeout set to 3 minutes).  What is the command in isql to find out where the system is spending it's time to figure out why an extra property object relationship bogs it down so much?

**Comment by ebremer** [comment]
found it, figuring it out now...

**Comment by ebremer** [comment]
Ok, I found a work around in my SPARQL query:

1) This query executes in 4 seconds on about 10 million triples

select ?target ?cguri where {
     ?target :cgroup ?cguri .
     {select sample(?s) as ?target where {?s :MD5 ?md5; a :svsfile} group by ?md5 order by ?md5 limit 5}
}

2) However, when I add "?cguri :handledbyhost ?host ." to get the URI of a host server, the query times out (3 minutes by my server's settings):

select ?target ?cguri where {
     ?cguri :handledbyhost ?host .
     ?target :cgroup ?cguri .
     {select sample(?s) as ?target where {?s :MD5 ?md5; a :svsfile} group by ?md5 order by ?md5 limit 5}
}

3) I added a type triple "?host a :Server ." and now the query finishes in about 12 seconds which works for me:
select ?target ?cguri where {
     ?cguri :handledbyhost ?host .
     ?host a :Server .
     ?target :cgroup ?cguri .
     {select sample(?s) as ?target where {?s :MD5 ?md5; a :svsfile} group by ?md5 order by ?md5 limit 5}
}

It seems like Virtuoso wanders off when it doesn't know what type ?host is even though ":handledbyhost" isn't used by anything but ":Server".  - Erich

**Comment by ebremer** [comment]
Oh - I'm using Virtuoso version 07.10.3211

**Comment by HughWilliams** [comment]
@ebremer: I presume you have performance tuning your Virtuoso instance as detailed at:

   http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFPerformanceTuning

assuming it is and there are buffers available, which you can check with the "status('');" command, then it  is probably a bad compiler plan being generated. Can you provide a query profile for the good and bad queries using the "set profile on" command from isql as detailed at:

   http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtTipsAndTricksAanalyzingSPARQLQuery

**Comment by ebremer** [comment]
Good presumption.  Not my first Virtuoso install so it's all beef'd up with lots of RAM and the ini file set accordingly.  :-)  I will send you good and bad plans.

**Comment by ebremer** [comment]
These queries all work great now using today's download of virtuoso-7/devel on the same dataset
