### ISSUE TITLE
Jena Provider: LIMIT off by one

### ISSUE THREAD

**Issue by nespera** [openlink/virtuoso-opensource#296]
Just spent some time banging my head against this issue, which looks like it was reported back in Oct 2013 and never been fixed: https://www.mail-archive.com/virtuoso-users@lists.sourceforge.net/msg05676.html

I'm using virt_jena2.jar and virtjdbc4.jar from the OpenLink website along with Jena 2.12.1

I've tried the latest version of virt_jena2.jar pulled directly from GitHub and I get the same results.

**Comment by HughWilliams** [comment]
@nespera:  The old mailing list report was intermittent on the users machine and we could never recreate locally.

I have amended the VirtuosoSPARQLExample1.java program in the Jena docs @ http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtJenaProvider#The%20Tests , that performs a select query execution, to add a "LIMIT 2" and running it against Jena 2.12 the expected 2 rows are returned, see:

Hughs-MBP:virtuoso_driver hwilliams$ javac -classpath ".:../lib/junit-4.5.jar:../lib/jena-arq-2.12.1.jar:../lib/jena-iri-1.1.1.jar:../lib/jena-core-2.12.1.jar:../lib/jena-core-2.12.1-tests.jar:../../../libsrc/JDBCDriverType4/virtjdbc4.jar:../virt_jena2.jar:../lib/jcl-over-slf4j-1.7.6.jar:../lib/log4j-1.2.17.jar:../lib/slf4j-api-1.7.6.jar:../lib/slf4j-log4j12-1.7.6.jar:../lib/xercesImpl-2.11.0.jar:../lib/xml-apis-1.4.01.jar" VirtuosoSPARQLExample1.java
Hughs-MBP:virtuoso_driver hwilliams$ java -classpath ".:../lib/junit-4.5.jar:../lib/jena-arq-2.12.1.jar:../lib/jena-iri-1.1.1.jar:../lib/jena-core-2.12.1.jar:../lib/jena-core-2.12.1-tests.jar:../../../libsrc/JDBCDriverType4/virtjdbc4.jar:../virt_jena2.jar:../lib/jcl-over-slf4j-1.7.6.jar:../lib/log4j-1.2.17.jar:../lib/slf4j-api-1.7.6.jar:../lib/slf4j-log4j12-1.7.6.jar:../lib/xercesImpl-2.11.0.jar:../lib/xml-apis-1.4.01.jar" VirtuosoSPARQLExample1
log4j:WARN No appenders could be found for logger (org.apache.jena.riot.RDFLanguages).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
http://localhost:8890/sys { http://localhost:8890/sys/user?id=124 http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://rdfs.org/sioc/ns#user . }
http://localhost:8890/sys { http://localhost:8890/sys/user?id=122 http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://rdfs.org/sioc/ns#user . }
Hughs-MBP:virtuoso_driver hwilliams$

Can you try this yourself to see what it returns for you ?

Or provided a compilable program to demonstrate the problem you are seeing  ...

**Comment by nespera** [comment]
I get one result running that as part of my current project. I will create a minimal program that demonstrates the problem.

**Comment by nespera** [comment]
I have created this minimal project based on that example java file which also produces just one result:
https://github.com/67Bricks/virtuoso-jena-test

I am on Ubuntu 14.04 and I've had the same results on both Oracle JDK 1.7.0_45 and 1.8.0_25. I'm running against Virtuoso 07.10.3211.

**Comment by HughWilliams** [comment]
@nespera: What do I do with this project ? 

If you run the query in my example above from command line as I do (no projects/IDEs etc to confuse matters) ,  do you get the expected results ?

**Comment by nespera** [comment]
Sorry, I though Maven projects were a standard way to describe dependencies. Here it is running on the command line with _all_ the dependencies pulled in by Jena:

chris $ /usr/lib/jvm/jdk1.8.0/bin/java -classpath /usr/lib/jvm/jdk1.8.0/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/resources.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/jfxswt.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/plugin.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/rt.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/deploy.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/javaws.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/management-agent.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/jce.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/ext/zipfs.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/ext/localedata.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/ext/sunec.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/ext/nashorn.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/ext/dnsns.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/jdk1.8.0/jre/lib/ext/sunpkcs11.jar:/home/chris/Projects/virtuoso-jena-test/target/classes:/home/chris/Projects/virtuoso-jena-test/lib/virtjdbc4.jar:/home/chris/Projects/virtuoso-jena-test/lib/virt_jena2.jar:/home/chris/.m2/repository/org/apache/jena/jena-arq/2.12.1/jena-arq-2.12.1.jar:/home/chris/.m2/repository/org/apache/jena/jena-core/2.12.1/jena-core-2.12.1.jar:/home/chris/.m2/repository/org/apache/jena/jena-iri/1.1.1/jena-iri-1.1.1.jar:/home/chris/.m2/repository/xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar:/home/chris/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar:/home/chris/.m2/repository/org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.jar:/home/chris/.m2/repository/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar:/home/chris/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar:/home/chris/.m2/repository/com/github/jsonld-java/jsonld-java/0.5.0/jsonld-java-0.5.0.jar:/home/chris/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.3.3/jackson-core-2.3.3.jar:/home/chris/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.3.3/jackson-databind-2.3.3.jar:/home/chris/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar:/home/chris/.m2/repository/org/apache/httpcomponents/httpclient-cache/4.2.6/httpclient-cache-4.2.6.jar:/home/chris/.m2/repository/org/apache/thrift/libthrift/0.9.1/libthrift-0.9.1.jar:/home/chris/.m2/repository/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar:/home/chris/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.6/jcl-over-slf4j-1.7.6.jar:/home/chris/.m2/repository/org/apache/commons/commons-csv/1.0/commons-csv-1.0.jar:/home/chris/.m2/repository/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar:/home/chris/.m2/repository/org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.jar:/home/chris/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar VirtuosoSPARQLExample1
log4j:WARN No appenders could be found for logger (org.apache.jena.riot.system.stream.JenaIOEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
http://www.openlinksw.com/schemas/virtrdf# { http://www.openlinksw.com/virtrdf-data-formats#default-iid-nullable http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://www.openlinksw.com/schemas/virtrdf#QuadMapFormat . }
Found 1 results

**Comment by smalinin** [comment]
It looks, that your problem is related with old version of Virtuoso JDBC driver. Your test project on github uses Java driver Build 3.62
The latest version of JDBC driver has Build 3.76 and your project works properly with last version of JDBC driver.  
You could check your JDBC driver with the next command:

```
java -jar virtjdbc4.jar virtuoso.jdbc4.Driver
```

**Comment by nespera** [comment]
Where is that version available? I'm using the one linked from here: http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VOSDownload#Jena%20Provider

Thanks

**Comment by nespera** [comment]
Ok, I guess it's here: https://github.com/openlink/virtuoso-opensource/blob/develop/7/libsrc/JDBCDriverType4/virtjdbc4.jar

That does indeed fix the problem. Can I suggest that this file is linked from the website rather than being buried in this repo? Cheers

**Comment by HughWilliams** [comment]
@nespera: Will update the JDBC provider on the download page, but you also said you tried the versions from git or did u pull from stable/7 rather than develop/7 ?

**Comment by nespera** [comment]
I said: "I've tried the latest version of virt_jena2.jar pulled directly from GitHub".

**Comment by HughWilliams** [comment]
Exactly and as git points to the develop/7 branch by default I would expect you to have gotten the latest ... anyway I have updated the VOSDownload page now ...

**Comment by nespera** [comment]
Yes, but the offending jar was virtjdbc4.jar not virt_jena2.jar. Thanks!

**Comment by HughWilliams** [comment]
Of course, the virtjdbc4 & virtjdbc3 jars have been updated ...
