### ISSUE TITLE
Virtuoso 22023 Error SR066: Unsupported case in CONVERT (incomplete RDF box -> VARCHAR)

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#298]
Something about this piece of my SPARQL query:
bind(concat("/data",strafter(?hostname,"nfs0"),"/data/phase/",?cgname,"/",?filename,".meta") as ?dest)

Virtuoso is throwing the following error:
Using Virtuoso version 07.10.3211 on Linux (x86_64-unknown-linux-gnu), Single Server Edition

adding str() around ?filename like this:
bind(concat("/data",strafter(?hostname,"nfs0"),"/data/phase/",?cgname,"/",str(?filename),".meta") as ?dest)

and the error goes away.  I cannot see any weird characters in the variable ?filename.  - Erich

**Comment by HughWilliams** [comment]
@ebremer: If you didn't have to add str() around ?cgname then I don't see why it would be needed for ?filename  , assuming the object values are of the same type, presumable xsd:string ? 

Can you provide a test case for this that can be setup locally ?

**Comment by ebremer** [comment]
I actually had to add str() around more.  When I ran it on my full set of about 32,000 things, there were more problem cases which didn't go away until I str()'d them.  Let me double check what the types are on these fields.  I'm assuming they are string since they were string in java.  But, maybe not.  Worse case, I don't mind sending you the dataset off-line.

**Comment by HughWilliams** [comment]
@ebremer: OK, if you can provide a dataset that would be ideal ...
