### ISSUE TITLE
What about UnixODBC?

### ISSUE THREAD

**Issue by fgiasson** [openlink/virtuoso-opensource#304]
Hi @HughWilliams,

I know that in the past, Virtuoso 5/6 had some issues with unixODBC drivers. That is for that reason that I always used the iODBC ones when working with Virtuoso. However, the problem there is that maintenance cost of using iODBC on Ubuntu since we have to re-compile PHP5 every time such that it works with iODBC instead of unixODBC (the default on Ubuntu).

So, I was wondering if it was safe to use UnixODBC with VOS 7.1?

Thanks!

**Comment by kidehen** [comment]
On 1/21/15 8:46 AM, Frederick Giasson wrote:

> Hi @HughWilliams https://github.com/HughWilliams,
> 
> I know that in the past, Virtuoso 5/6 had some issues with unixODBC 
> drivers. That is for that reason that I always used the iODBC ones 
> when working with Virtuoso. However, the problem there is that 
> maintenance cost of using iODBC on Ubuntu since we have to re-compile 
> PHP5 every time such that it works with iODBC instead of unixODBC (the 
> default on Ubuntu).
> 
> So, I was wondering if it was safe to use UnixODBC with VOS 7.1?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/openlink/virtuoso-opensource/issues/304.

I don't see why not. Note, iODBC isn't built specifically for our 
Drivers. We believe in the notion of a generic ODBC Driver, across any 
platform. What we can't do is fix issues in UnixODBC that break the 
aforementioned notion.

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by fgiasson** [comment]
Hi @kidehen,

Good, thanks for confirming these things.
