### ISSUE TITLE
VALUES with more tuples

### ISSUE THREAD

**Issue by schwarja** [openlink/virtuoso-opensource#305]
Query:

```
SELECT ?X WHERE
{
VALUES (?X ?Y) {(2 3) (3 2)}
FILTER (?X < ?Y).
}
```

Should return "2", but returns empty result.

**Comment by HughWilliams** [comment]
@schwarja: What Virtuoso version (virtuoso-t -?) are you running as the query returns "2" when run against the latest git develop/7 branch:

SQL> SPARQL SELECT ?X WHERE { VALUES (?X ?Y) {(2 3) (3 2)} FILTER (?X < ?Y). } ;
X
VARCHAR

---

2

1 Rows. -- 0 msec.
SQL> status('');
REPORT
VARCHAR

---

OpenLink Virtuoso  Server
Version 07.10.3211-pthreads for Linux as of Jan 20 2015 
Started on: 2015-01-22 05:20 GMT+1

**Comment by schwarja** [comment]
Virtuoso Open Source Edition (multi threaded)
Version 7.1.0.3207-threads as of Feb 17 2014
Compiled for Win64 (x86_64-generic-win-64)
Copyright (C) 1998-2014 OpenLink Software

Usage:
  virtuoso-t [-fcnCbDARMKrBdSIm] [+foreground] [+configfile arg]
             [+no-checkpoint] [+checkpoint-only] [+backup-dump] [+crash-dump]
             [+crash-dump-data-ini arg] [+restore-crash-dump] [+mode arg]
             [+dumpkeys arg] [+restore-backup arg] [+backup-dirs arg] [+debug]
             [+pwdold arg] [+pwddba arg] [+pwddav arg] [+service arg]
             [+instance arg] [+manual]
  +foreground            run in the foreground
  +configfile            specify an alternate configuration file to use,
                        or a directory where virtuoso.ini can be found
  +no-checkpoint         do not checkpoint on startup
  +checkpoint-only       exit as soon as checkpoint on startup is complete
  +backup-dump           dump database into the transaction log, then exit
  +crash-dump            dump inconsistent database into the transaction log,
                        then exit
  +crash-dump-data-ini   specify the DB ini to use for reading the data to dump
  +restore-crash-dump    restore from a crash-dump
  +mode                  specify mode options for server startup (onbalr)
  +dumpkeys              specify key id(s) to dump on crash dump (default : all)
  +restore-backup        restore from online backup
  +backup-dirs           default backup directories
  +debug                 allocate a debugging console
  +pwdold                Old DBA password
  +pwddba                New DBA password
  +pwddav                New DAV password
  +service               specify a service action to perform
  +instance              specify a service instance to start/stop/create/delete
  +manual                when creating a service, disable automatic startup

The argument to the +service option can be one of the following options:
  start         start a service instance
  stop          stop a service instance
  create        create a service instance
  screate       create a service instance without deleting the existing one
  delete        delete a service instance
  list          list all service instances

To create a windows service 'MyService' using the configuration file c:\database\virtuoso.ini:
  virtuoso-t +service create +instance MyService +configfile c:\database\virtuoso.ini

To start this service, use 'sc start MyService' or:
  virtuoso-t +service start +instance MyService

**Comment by HughWilliams** [comment]
@schwarja: Ok, so you are running the Windows prebuilt stable/7 binary we provide, whereas you need a develop/7 build which needs to be compiled ... Windows is not readily compilable, hence the reason the prebuilt binary is provided. Are you able to compile on Linux or Mac  such that you can compile a develop/7 build to test  ?

**Comment by schwarja** [comment]
I tested the issue on develop/7 and I can confirm that it works.
