### ISSUE TITLE
Faceted Browser installation broken

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#310]
With the latest commit 78a0ed5ac1f43c363a49c45b13bd981cf224dccf Faceted Browser installation is broken.

I start with clean db, login to conductor, System Admin, Packages and click on Install on fct. Installation completes. However, when I access /fct, I wait indefinitely. When I access e.g. /describe/?url=http://unifiedviews.eu/resource/internal/dataunit/exec/174/dpu/498/du/1/entry/1 I get

<pre><code>Error 42000

SR186: No permission to execute procedure fct_build_info with user ID 107, group ID 107</code></pre>

When FCT was installed before the update that breaks it, it works fine even after the update.

**Comment by HughWilliams** [comment]
@jakubklimek: I have been able to recreate and reported to development to fix ...

**Comment by openlink** [comment]
Please try latest version from develop/7 branch

**Comment by jakubklimek** [comment]
Tested and OK
