### ISSUE TITLE
Infinite loop in function dfe_prev_tb()

### ISSUE THREAD

**Issue by galgonek** [openlink/virtuoso-opensource#314]
Hi,

we have found another problem in the Virtuoso server. The following query causes an infinite loop in function dfe_prev_tb().

SELECT \* FROM (sparql SELECT \* { ?X ?P ?Y. }) AS __tmpTab
WHERE ( ( "Y" > DB.DBA.RDF_OBJ_OF_SQLVAL(2) ) )
OPTION(QUIETCAST)

We have tested it on both stable (07.10.3207) and devel (07.10.3211) versions. We have used "clean installations" in the both cases and no additional data has been loaded.

Best wishes,
Jakub

**Comment by HughWilliams** [comment]
I can see this query is hanging, but how did u determine the function dfe_prev_tb() was the cause ?

**Comment by galgonek** [comment]
Hi @HughWilliams,

I am not familiar with the virtuoso code, bud I have tried to debug the issue. During the evaluation of the query, function sqlo_place_dfe_after() try to place a dfe that is already placed in a list of dfes. This causes damage of the list (dfes begin to form a loop). Later, the dfe_prev_tb() function wants to go through the damage list and it hangs in an infinite loop.

Jakub

**Comment by HughWilliams** [comment]
Are you @jakubklimek or another jakub ? 

What is the query being run above suppose to be doing or provide as its use is unclear to me ?

**Comment by galgonek** [comment]
I am another Jakub. It is a very common Czech name.

The query does not do anything useful, it is only used to show the bug in virtuoso. Its result should be equivalent to the following query that works fine:

SELECT \* FROM (sparql SELECT \* { ?X ?P ?Y. }) AS __tmpTab
WHERE ( ( "Y" > 2 ) )
OPTION(QUIETCAST)

**Comment by HughWilliams** [comment]
This issue has been recreated and reported to development to look into ...
