### ISSUE TITLE
Faceted Browser broken

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#315]
In be5e99d7bf4e5c1de1d105efe96c347e73c9100e when accessing /describe... I get

<pre><code>Error 42000

SR186: No permission to execute procedure DB.DBA.b3s_get_entity_graph with user ID 106, group ID 106
  </code></pre>

**Comment by openlink** [comment]
I pushed a fix for the missing grant

**Comment by jakubklimek** [comment]
Works, however needs fct uninstall/install if the broken version was already installed.
