### ISSUE TITLE
CLEAR GRAPH not necessarily cleared for all SPARQL queries

### ISSUE THREAD

**Issue by fgiasson** [openlink/virtuoso-opensource#316]
@HughWilliams, @iv-an-ru,

I am having a really weird issue with my Virtuoso 7 instance. It is using the latest Dev branch code, but I am wondering if the index is not somehow broken.

I did import a dataset using `DB.DBA.TTLP_MT`.

Then I cleared it using the following SPARQL Update query:

```
sparql clear graph <http://localhost/datasets/test/>;
```

Then I ran that query:

```
sparql
select count(?s) as ?nb
from <http://localhost/datasets/test/>
where
{
  ?s a ?type.
};
```

I was expecting to get `0`, but I got `16` (the number doesn't matter, what matters is that it is no `0` :) )

Then I tested this other query:

```
select count(?s) as ?nb
from <http://localhost/datasets/test/>
where
{
  ?s ?p ?type.
}
```

And then I got `0`.

So, if I was using `a` or not was impacting the query to return results or not (even the first thing I did is to clear the graph!).

This is really weird and totally unexpected and this is why I am wondering if this is not due to a corrupted index or something similar. Is there some procedure I could run to detect/fix issues with an index? Can you reproduce this issue?

**Comment by kidehen** [comment]
On 1/28/15 2:39 PM, Frederick Giasson wrote:

> @HughWilliams https://github.com/HughWilliams, @iv-an-ru 
> https://github.com/iv-an-ru,
> 
> I am having a really weird issue with my Virtuoso 7 instance. It is 
> using the latest Dev branch code, but I am wondering if the index is 
> not somehow broken.
> 
> I did import a dataset using |DB.DBA.TTLP_MT|.
> 
> Then I cleared it using the following SPARQL Update query:
> 
> |sparql clear graph http://localhost/datasets/test/;
> |
> 
> Then I ran that query:
> 
> |sparql
> select count(?s) as ?nb
> from http://now.winnipeg.ca/datasets/zoning-parcels/
> where
> {
>    ?s a ?type.
> };
> |
> 
> I was expecting to get |0|, but I got |16| (the number doesn't matter, 
> what matters is that it is no |0| :) )
> 
> Then I tested this other query:
> 
> |select count(?s) as ?nb
> from http://now.winnipeg.ca/datasets/zoning-parcels/
> where
> {
>    ?s ?p ?type.
> }
> |
> 
> And then I got |0|.
> 
> So, if I was using |a| or not was impacting the query to return 
> results or not (even the first thing I did is to clear the graph!).
> 
> This is really weird and totally unexpected and this is why I am 
> wondering if this is not due to a corrupted index or something 
> similar. Is there some procedure I could run to detect/fix issues with 
> an index? Can you reproduce this issue?

What happens when you run:

DROP SILENT GRAPH <Named-Graph-IRI>

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by fgiasson** [comment]
Hi @kidehen,

I tried that too, but I am getting that error:

```
SQLState: 22023 Message: SPARUL_DROP() failed: graph <http://localhost/datasets/test/> has not been explicitly created before
```

Is it necessary to create it in a particular manner?

**Comment by kidehen** [comment]
On 1/28/15 3:35 PM, Frederick Giasson wrote:

> Hi @kidehen https://github.com/kidehen,
> 
> I tried that too, but I am getting that error:
> 
> |SQLState: 22023 Message: SPARUL_DROP() failed: graph http://localhost/datasets/test/ has not been explicitly created before
> |
> 
> Is it necessary to create it in a particular manner?
> 
> No, SILENT should simply stop the aforementioned error occurring i.e., 
> don't require that said named graph was explicitly created using CREATE 
> GRAPH <named-graph-iri>.

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by fgiasson** [comment]
@kidehen,

thanks for clarifying for the `silent` clause. However, exactly the same behavior happens.

Could it be possible that it is because the database comes from a V6 installation (even if I think they are supposedly compatible)?

**Comment by fgiasson** [comment]
Another thing I just noticed, the dataset I just dropped still appears in the resultset of that query:

```
select distinct ?g
where
{
    graph ?g {?s ?p ?o}
}
```

**Comment by fgiasson** [comment]
@kidehen, @HughWilliams,

I exported the datasets, created a new empty V7.1 database, re-imported the datasets in it, and now I cannot reproduce this issue. I think the DB has been corrupted in some ways which was leading to these weird behaviors.

Thanks!
