### ISSUE TITLE
FILTER division by zero - BIND vs. VALUES

### ISSUE THREAD

**Issue by schwarja** [openlink/virtuoso-opensource#317]
Query 1:

```
SELECT DISTINCT ?X WHERE 
{
    BIND (0 AS ?X)
    BIND (0 AS ?Y)
    FILTER(1/?X || 1/?Y)
}
```

Result 1:

```
0
```

Query 2:

```
SELECT DISTINCT ?X WHERE 
{
    VALUES (?X ?Y) {(0 0)}
    FILTER(1/?X || 1/?Y)
}
```

Result 2:

```
Virtuoso 22012 Error SR084: Division by 0.
```

Firstly, these two queries should give the same result. And secondly, as far as I am concerned, the correct answer is empty result, because FILTER should survive an inside error and ERROR OR ERROR is ERROR which should be filtered out.

**Comment by HughWilliams** [comment]
This issue has been recreated and reported to development to look into ...
