### ISSUE TITLE
SPARQL "LOAD … INTO …" doesn't work in recent git-version

### ISSUE THREAD

**Issue by indeyets** [openlink/virtuoso-opensource#32]
Seems like **Major Regression**

I just recompiled my test-environment and noticed, that `LOAD <file:///path/to/dataset.ttl> INTO <http://example.com/graph>` command doesn't work anymore.

I do queries against `http://127.0.0.1:8890/sparql/` and get confirmation of success:

`Load <file:///path/to/dataset.ttl> into graph <http://example.com/graph> -- done` but data doesn't appear in triplestore. If I use `http://127.0.0.1:8890/sparql-graph-crud` form than data is uploaded successfully

Both approaches worked fine in build from 2013-01-18, which I used until now.

I wonder if it is related to recent changes to `/sparql/` endpoint. I'll do some digging and will add comments when I find something

**Comment by indeyets** [comment]
This problem persists in develop/7. So, looks like you just made a release with a known regression

**Comment by imitko** [comment]
The SPARQL account is disabled by default for security reasons, thus /sparql endpoint will simply ignore the insert due to lack of permissions. In order to enable /sparql to do CRUD, via conductor enable the SPARQL sql user account.

**Comment by indeyets** [comment]
@imitko I know that and it has nothing to do with this issue. Privileges mismatch would result in error, and this results in false success

**Comment by indeyets** [comment]
ok. It IS fixed in current develop/7. I'm not sure which commit did it
