### ISSUE TITLE
Equality of nonPositiveIntegers -5 and -3

### ISSUE THREAD

**Issue by schwarja** [openlink/virtuoso-opensource#321]
Query:

```
SELECT ?X WHERE
{
  BIND ("-5"^^xsd:nonPositiveInteger AS ?X)
  FILTER (?X = "-3"^^xsd:nonPositiveInteger)
}
```

Result:

```
-3
```

Besides the fact that these numbers are not equal there is the number -3 in the result which is not even in variable ?X

**Comment by indeyets** [comment]
epic :+1:

**Comment by indeyets** [comment]
this is a regression. works fine in Virtuoso 06.01.3127

**Comment by HughWilliams** [comment]
This issue has been recreated and reported to development to look into ...
