### ISSUE TITLE
Data import (DB.DBA.RDF_LOAD_RDFXML_MT) sometimes hangs in middle of its process

### ISSUE THREAD

**Issue by fgiasson** [openlink/virtuoso-opensource#325]
Hi,

There is one thing I am experiencing with the latest dev code: apparently that Virtuoso "hangs" when importing data using `DB.DBA.RDF_LOAD_RDFXML_MT`. It may not be the only one, but this is the one that is hanging now. 

After a Virtuoso restart, I started importing some data (it imported about 20k records), then it stops. It didn't die, but it is not doing anything. `top` reveals that the process is not taking any CPU. `free` reveals that I have 2G of free memory. And `status('c')` reveals:

```
 OpenLink Virtuoso Server
 Version 07.10.3211-pthreads for Linux as of Jan 24 2015
 Started on: 2015-02-03 06:12 GMT-6

 Database Status:
  File size 0, 137728 pages, 46692 free.
  20000 buffers, 19653 used, 4109 dirty 0 wired down, repl age 136356 0 w. io 1 w/crsr.
  Disk Usage: 146820 reads avg 0 msec, 1% r 0% w last 880 s, 260988 writes flush 54.2 MB,
  1601 read ahead, batch = 84. Autocompact 44990 in 38247 out, 14% saved col ac: 503 in 16% saved.
 Gate: 1032 2nd in reads, 0 gate write waits, 0 in while read 0 busy scrap.
 Log = /data/virtuoso/db/virtuoso.trx, 140027757 bytes
 64409 pages have been changed since last backup (in checkpoint state)
 Current backup timestamp: 0x0000-0x00-0x00
 Last backup date: unknown
 Clients: 13 connects, max 2 concurrent
 RPC: 112 calls, -3 pending, 1 max until now, 0 queued, 77 burst reads (68%), 0 second 281M large, 442M max
 Checkpoint Remap 38 pages, 0 mapped back. 0 s atomic time.
  DB master 137728 total 46692 free 38 remap 2 mapped back
  temp 768 total 763 free

 Lock Status: 0 deadlocks of which 0 2r1w, 4 waits,
  Currently 5 threads running 3 threads waiting 1 threads in vdb.
 Pending:

 Client 1111:1: Account: dba, 597 bytes in, 337 bytes out, 2 stmts.
 PID: 59016, OS: unix, Application: unknown, IP#: 127.0.0.1
 Transaction status: PENDING, 1 threads.
 Locks: 49680: IE, 49697: IE, 50444: IE, 49672: IE, 98: IE, 50447: IE, 50453: IE, 50446: IE, 50432: IE, 101: IE, 50452: IE, ....


 Running Statements:
  Time (msec) Text
  1150290 DB.DBA.RDF_LOAD_RDFXML_MT(file_to_string_output('/data/datasets/FME/Property_add
```

What I am wondering about is the following:
- `Currently 5 threads running 3 threads waiting 1 threads in vdb` it has been the case for 30 minutes
- `Transaction status: PENDING, 1 threads.` what does that mean? Pending for 30 mins as well
- `Locks: 49680` appears pretty hight, no?

Normally, if I kill the query, and restart it, it should finish normally. But I never know when it would hangs again in the future.

Any hints about what could be causing this?

Thanks!

**Comment by fgiasson** [comment]
@HughWilliams, @iv-an-ru,

I just updated another server with the latest code, and I even used an empty database to test this thing. I have a dataset here where this issue happen at every attemps. Sometimes it will index half of the entities, other 25% of them, etc.

`status();` shows that it is running, but the process uses not CPU and no new triples are being indexed.

I tested with:
- `DB.DBA.TTLP(file_open('/data/foo.n3'),'http://localhost/datasets/foo', 'http://localhost/datasets/foo');`
- `DB.DBA.TTLP_MT(file_open('/data/foo.n3'),'http://localhost/datasets/foo', 'http://localhost/datasets/foo');`
- `DB.DBA.TTLP(file_to_string_output('/data/foo.n3'),'http://localhost/datasets/foo', 'http://localhost/datasets/foo');`
- `DB.DBA.TTLP_MT(file_to_string_output('/data/foo.n3'),'http://localhost/datasets/foo', 'http://localhost/datasets/foo');`

It is all the same and I have nothing in `virtuoso.log`

There is 16G of memory allocated to it, and the size of the N3 serialized dataset is about `500M`. Am I the only one experiencing this kind of issues?

Are there other functions/methods I could try to use to import the dataset?

Another thing to note, I can't stop virtuoso using `/etc/init.d/virtuoso stop` when it hangs like this, I have to kill it.

Finally note that I am doing all my test using Conductor's iSQL interface.

**Comment by kidehen** [comment]
On 2/5/15 2:04 PM, Frederick Giasson wrote:

> @HughWilliams https://github.com/HughWilliams, @iv-an-ru 
> https://github.com/iv-an-ru,
> 
> I just updated another server with the latest code, and I even used an 
> empty database to test this thing. I have a dataset here where this 
> issue happen at every attemps. Sometimes it will index half of the 
> entities, other 25% of them, etc.
> 
> |status();| shows that it is running, but the process uses not CPU and 
> no new triples are being indexed.
> 
> I tested with:
> - |DB.DBA.TTLP(file_open('/data/foo.n3'),'http://localhost/datasets/foo',
>   'http://localhost/datasets/foo');|
> - |DB.DBA.TTLP_MT(file_open('/data/foo.n3'),'http://localhost/datasets/foo',
>   'http://localhost/datasets/foo');|
> - |DB.DBA.TTLP(file_to_string_output('/data/foo.n3'),'http://localhost/datasets/foo',
>   'http://localhost/datasets/foo');|
> - |DB.DBA.TTLP_MT(file_to_string_output('/data/foo.n3'),'http://localhost/datasets/foo',
>   'http://localhost/datasets/foo');|
> 
> It is all the same and I have nothing in |virtuoso.log|
> 
> There is 16G of memory allocated to it, and the size of the N3 
> serialized dataset is about |500M|. Am I the only one experiencing 
> this kind of issues?
> 
> Are there other functions/methods I could try to use to import the 
> dataset?

Have you looked at: 
http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtBulkRDFLoader 
?

SeeAlso: https://twitter.com/kidehen/status/560483341766778881 .

Hope that helps.

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by fgiasson** [comment]
Hi Kingsley,

Yes, but ultimately it will uses `DB.DBA.RDF_LOAD_RDFXML` or `TTLP` to load that file, no?

I will try anyway, but there seems to be an issue with `TTLP`/`TTLP_MT` in any cases.

Thanks!

Fred

**Comment by kidehen** [comment]
On 2/5/15 4:30 PM, Frederick Giasson wrote:

> Hi Kingsley,
> 
> Yes, but ultimately it will uses |DB.DBA.RDF_LOAD_RDFXML| or |TTLP| to 
> load that file, no?
> 
> I will try anyway, but there seems to be an issue with 
> |TTLP|/|TTLP_MT| in any cases.

I'll have that looked into.

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by HughWilliams** [comment]
@fgiasson: Do you have a sample dataset that demonstrates the problem . Also does it also occur if you do it from the isql command line tool ?

**Comment by fgiasson** [comment]
@HughWilliams, about isql command line tool: yes, it does as well.

let me do one more test and I will prepare one for you.

Thanks,

**Comment by fgiasson** [comment]
@HughWilliams, @kidehen,

It turned out the issue was the N3 file. The problem was one of the following reasons:
- bad character encoding
- same triples defined too many times in the same N3 file (is that possible? I doubt)

Before fixing the file, I tried the third parameter of `TTLP` with `128` as the mask. This didn't fix the issue. In any case, it seems to be related to some issues with the N3 file but no error were returned (it was hanging).

**Comment by kidehen** [comment]
On 2/6/15 1:19 PM, Frederick Giasson wrote:

> @HughWilliams https://github.com/HughWilliams, @kidehen 
> https://github.com/kidehen,
> 
> It turned out the issue was the N3 file. The problem was one of the 
> following reasons:
> - bad character encoding
> - same triples defined too many times in the same N3 file (is that
>   possible? I doubt)
> 
> Before fixing the file, I tried the third parameter of |TTLP| with 
> |128| as the mask. This didn't fix the issue. In any case, it seems to 
> be related to some issues with the N3 file but no error were returned 
> (it was hanging).

It shouldn't hang.

That's a bug that needs to be fixed.

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by fgiasson** [comment]
@kidehen ok, so I will create the dataset that hangs to @HughWilliams on Monday.

**Comment by fgiasson** [comment]
Can't reproduce with latest dev. Will re-open is I restart getting this issue.
