### ISSUE TITLE
isIRI/isURI not working

### ISSUE THREAD

**Issue by schwarja** [openlink/virtuoso-opensource#327]
Query:

```
SELECT ?X WHERE
{
{
BIND(<http://www.uochb.org/chebi/1.0/terms#chebiName> AS ?X).
}
UNION
{
BIND(3 AS ?X).
}
FILTER(isIRI(?X))
}
```

Result:

| X |
| --- |
| http://www.uochb.org/chebi/1.0/terms#chebiName |
| 3 |

Number 3 is definitely not an IRI. And the result is same even if the argument of FILTER is negative (FILTER(! isIRI(?X))).

The same situation with isURI.

**Comment by HughWilliams** [comment]
Development are looking into this ...
