### ISSUE TITLE
isNumeric leads to internal error

### ISSUE THREAD

**Issue by schwarja** [openlink/virtuoso-opensource#328]
Query:

```
SELECT ?CH WHERE
{
BIND (3 AS ?CH)
FILTER(isNumeric(?CH))
}
```

Leads to error:
Virtuoso 37000 Error SP031: SPARQL: Internal error: ssg_print_builtin_expn(): bad native type for isNUMERIC()

**Comment by HughWilliams** [comment]
A fix for this issue is now available:

SQL> SPARQL SELECT ?CH WHERE { BIND (3 AS ?CH) FILTER(isNumeric(?CH)) };
CH
INTEGER NOT NULL

---

3

1 Rows. -- 0 msec.
SQL> status('');
REPORT
VARCHAR

---

OpenLink Virtuoso VDB Server
Version 07.20.3213-pthreads for Linux as of Mar 29 2015
