### ISSUE TITLE
deadlock on Windows Virtuoso Version: 07.10.3207 Build: Feb 17 2014

### ISSUE THREAD

**Issue by ghost** [openlink/virtuoso-opensource#333]
Using a whole list of Graph Store HTTP Protocol cURL commando's for deleting and loading e.g.
curl -f -v --digest --user dba:XXX --url "http://server:8890/sparql-graph-crud-auth?graph-uri=urn:graph:egp:aat" -X DELETE
curl -f -v --digest --user dba:XXX --url "http://server:8890/sparql-graph-crud-auth?graph-uri=urn:graph:egp:aat" -T "c:\temp\rdfstore\2015-02-05T11-00-05-171\aat\centuries.rdf" 
.....

Leads to a deadlock:
14:19:07 Write wait on column page 83237.  Waits should be on the index leaf page, except when col page is held for read by background write
·         14:19:08 \* Monitor: Locks are held for a long time
·         14:19:40 Write wait on column page 42306.  Waits should be on the index leaf page, except when col page is held for read by background write
·         14:19:43 Write wait on column page 4871.  Waits should be on the index leaf page, except when col page is held for read by background write
·         14:19:43 Write wait on column page 36283.  Waits should be on the index leaf page, except when col page is held for read by background write

The same with the commercial version on MacOS works flawless.

Any idea ?

**Comment by HughWilliams** [comment]
@PaulZH I presume your Mac build is a recent  build 3211 or similar as the windows 3207 build is quite old ?  A later 3211 build from Jul can be obtained from:

```
ftp://download.openlinksw.com/support/db/virtuoso-t.zip
```

Simply run a checkpoint, shutdown Virtuoso, unzip and replace the current virtuoso-t.exe file with this one and restart.

The version details being:

..\bin\virtuoso -t -? 
Virtuoso Open Source Edition (multi threaded) 
Version 7.1.0.3211-threads as of Jul 10 2014 
Compiled for Win64 (x86_64-generic-win-64) 
Copyright (C) 1998-2014 OpenLink Software

A new 7.2 build should also be available next week when the stable release is scheduled to me made ....

**Comment by ghost** [comment]
Many thanks. We'll check it out.

Paul

> On 07 Feb 2015, at 16:03, HughWilliams notifications@github.com wrote:
> 
> @PaulZH https://github.com/PaulZH I presume your Mac build is a recent build 3211 or similar as the windows 3207 build is quite old ? A later 3211 build from Jul can be obtained from:
> 
> ftp://download.openlinksw.com/support/db/virtuoso-t.zip
> Simply run a checkpoint, shutdown Virtuoso, unzip and replace the current virtuoso-t.exe file with this one and restart.
> 
> The version details being:
> 
> ..\bin\virtuoso -t -? 
> Virtuoso Open Source Edition (multi threaded) 
> Version 7.1.0.3211-threads as of Jul 10 2014 
> Compiled for Win64 (x86_64-generic-win-64) 
> Copyright (C) 1998-2014 OpenLink Software
> 
> A new 7.2 build should also be available next week when the stable release is scheduled to me made ....
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/openlink/virtuoso-opensource/issues/333#issuecomment-73367664.

Kind Regards,
Paul Hermans

---

ProXML bvba
Linked Data services
KBO: http://data.kbodata.be/organisation/0476_068_080#id http://data.kbodata.be/organisation/0476_068_080#id
(w) www.proxml.be http://www.proxml.be/
(e) paul@proxml.be mailto:paul@proxml.be
(tw)  @PaulZH
(t)  +32 15 23 00 76
(m) +32 473 66 03 20

OpenCube – Linked Open Statistical Data - http://opencube-project.eu/

**Comment by ghost** [comment]
Hugh,

This issue was indeed solved with the newer Windows build.
