### ISSUE TITLE
Root app missing

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#334]
With the latest commits in develop/7 (v7.2) the root app is missing. Accessing http://localhost:8890 gives

<pre><code>Error HTTP/1.1 404 File not found

The requested URL was not found    URI  = '/'
  </code></pre>

**Comment by HughWilliams** [comment]
Can you try against the latest `stable/7` and `develop/7` branches as they are basically the same following the 7.2 stable release and work for me ... note I tried using `--with-layout=openlink` such that all files are installed in the same `--prefix` installation dir much as with a commercial installer installation ...

**Comment by jakubklimek** [comment]
I tried it with the Feb 11 version of `develop/7`, the Feb 14 version is just a version string change, so that will not affect it I guess.

I am configuring it with
`./configure --prefix=/usr/local/ --with-readline --program-transform-name="s/isql/isql-v/" --with-layout=Debian --enable-fct-vad` as always, it stopped working for the root app only lately.

**Comment by HughWilliams** [comment]
@jakubklimek: So what is in the `ServerRoot` in the HTTP Server section of your INI file for this debian layout, as that will determine where the server root will be expected to be found?

**Comment by jakubklimek** [comment]
@HughWilliams I do not change the `.ini` when I update Virtuoso. So in my `ini` there is
`ServerRoot = /usr/local/var/lib/virtuoso/vsp` which is in fact empty (when I update, I uninstall the old virtuoso first).

But now I see that there is a new folder from Feb 3
`/usr/local/var/lib/virtuoso-opensource-7/vsp` that contains the root app.

When I changed the `ServerRoot` to this path it works.

**Comment by HughWilliams** [comment]
@jakubklimek:  Will have to check with development  if this was a specific change made recently as I know there were some improvements made for building Virtuoso debian packages recently ...

**Comment by KimJBaran** [comment]
@HughWilliams I have the same problem. Checked out tag v7.2.1.

**Comment by jakubklimek** [comment]
Fixed a long time ago
