### ISSUE TITLE
NullPointerException with openrdf/sesame SPARQLJSONWriterBase for sparql queries with OPTIONAL

### ISSUE THREAD

**Issue by tlomb** [openlink/virtuoso-opensource#336]
Dear Hugh,
Dear all,

I observed a problem with OPTIONAL and JSON results when using the virtuoso-opensource sesame2 driver (from version  0b74378067a7fdda16e0f0789d12f80b1028c483 ).

When trying the following query with openrdf/sesame 2.7.3 on a virtuoso-t devel/7 0b74378067a7fdda16e0f0789d12f80b1028c483 , trying to get json results, I get an exception:

query:
###### 

PREFIX up_core:http://purl.uniprot.org/core/
PREFIX taxon:http://purl.uniprot.org/taxonomy/
PREFIX rdfs:http://www.w3.org/2000/01/rdf-schema#
SELECT ?taxonId ?scitName ?comName
WHERE
{
?taxonId a up_core:Taxon .
?taxonId rdfs:subClassOf+ taxon:554915 .
?taxonId up_core:scientificName ?scitName .
OPTIONAL {
?taxonId up_core:commonName ?comName .
}
} LIMIT 100
###### 

Exception:
###### 

java.lang.NullPointerException
    at org.openrdf.query.resultio.sparqljson.SPARQLJSONWriterBase.writeValue(SPARQLJSONWriterBase.java:351)
    at org.openrdf.query.resultio.sparqljson.SPARQLJSONWriterBase.handleSolution(SPARQLJSONWriterBase.java:177)
    at org.openrdf.query.resultio.sparqljson.SPARQLResultsJSONWriter.handleSolution(SPARQLResultsJSONWriter.java:29)
[...]
###### 

The dataset is ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/rdf/taxonomy.rdf.gz ,  but I guess you can reproduce the issue with any dataset with a sparql query with OPTIONAL and openrdf/sesame SPARQLResultsJSONWriter, as soon as you have a particular solution with an unbound variable.

It seems that this issue has been reported to openrdf/sesame in the past ( http://sesame-general.435816.n3.nabble.com/SPARQLResultsJSONWriter-td2738739.html ), but they pointed out that the problem might lie in VirtuosoRepositoryConnection.executeSPARQLForHandler - see https://github.com/openlink/virtuoso-opensource/blob/0b74378067a7fdda16e0f0789d12f80b1028c483/binsrc/sesame2/virtuoso_driver/VirtuosoRepositoryConnection.java .

Here is another older bug report that might also be related: https://sourceforge.net/p/virtuoso/mailman/message/25051822/

Let me know if you need more details,

Thanks for your help,

Thierry

**Comment by smalinin** [comment]
Patch has been created, it will be in Git soon.

You could you the next, if you want it now:

```
--- a/binsrc/sesame2/virtuoso_driver/VirtuosoRepositoryConnection.java
+++ b/binsrc/sesame2/virtuoso_driver/VirtuosoRepositoryConnection.java
@@ -1749,8 +1749,10 @@ public class VirtuosoRepositoryConnection implements RepositoryConnection {
                    // TODO need to parse these into appropriate resource values
                    String col = rsmd.getColumnName(i);
                    Object val = rs.getObject(i);
-                   Value v = castValue(val);
-                   qbs.addBinding(col, v);
+                   if (val!=null){
+                       Value v = castValue(val);
+                       qbs.addBinding(col, v);
+                   }
                }
                tqrh.handleSolution(qbs);
            }
```

**Comment by tlomb** [comment]
Dear smalinin,

Thanks for your fix in VirtuosoRepositoryConnection.executeSPARQLForHandler. However, some more testing suggests that the same issue (missing test for val!=null) is also present in VirtuosoRepositoryConnection.CloseableIterationBindingSet.extractRow(). I can see this in the latest tag (v7.2.0.1). Let me know if you need more details and if you can fix it in an upcoming v7.2.0.2.

**Comment by smalinin** [comment]
Yes, I see, it was missed. I create the next patch( it will be in Git soon.):

```
--- a/binsrc/sesame2/virtuoso_driver/VirtuosoRepositoryConnection.java
+++ b/binsrc/sesame2/virtuoso_driver/VirtuosoRepositoryConnection.java
@@ -3407,8 +3407,10 @@ public class VirtuosoRepositoryConnection implements RepositoryConnection {
            for (int i = 1; i <= rsmd.getColumnCount(); i++) {
                String col = rsmd.getColumnName(i);
                Object val = v_rs.getObject(i);
-               Value v = castValue(val);
-               ((QueryBindingSet)v_row).setBinding(col, v);
+               if (val!=null) {
+                   Value v = castValue(val);
+                   ((QueryBindingSet)v_row).setBinding(col, v);
+               }
            }
        }
    }

```

**Comment by tlomb** [comment]
Dear smalinin,
Thanks for that. I can't see the fix yet in the develop/7 branch.
And any chance you create a minor release v7.2.0.2 including this?

**Comment by smalinin** [comment]
I don't know, but it will be soon in a cumulative update of issues in Sesame provider: the fix for above, a performance insert issue,  fix for insert triples with BlankNodes  and some server side update related with handle insert BlankNodes.

**Comment by tlomb** [comment]
I can see this has been fixed in develop/7 on 2015-05-04:
https://github.com/openlink/virtuoso-opensource/commit/5abb5a3d27e5be8711ad6354331e4a1cd61dbdfb#diff-f77bbd5d9efc33795d7394a246ce0808

Thanks a lot.

(int. ref. UPS-70)
