### ISSUE TITLE
STRENDS - Argument compatibility rules are not followed

### ISSUE THREAD

**Issue by schwarja** [openlink/virtuoso-opensource#343]
Query 1:

```
SELECT ?S WHERE
{
    BIND("test string"@cz AS ?S)
    FILTER(STRENDS(?S,"ing"@en))
}
```

Query 2:

```
SELECT ?S WHERE
{
    BIND("test string" AS ?S)
    FILTER(STRENDS(?S,"ing"@en))
}
```

Result 1:

```
"test string"@cz
```

Result 2:

```
"test string"
```

But according to SPARQL 1.1 documentation (http://www.w3.org/TR/sparql11-query/#func-arg-compatibility) the results should be empty, because this usage of STREDNS should raise an error (a language tag of the second argument must be same as a language tag of the first argument).

**Comment by HughWilliams** [comment]
this issue has been recreated and reported to development to fix ...
