### ISSUE TITLE
Faceted Browser Installation Fails

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#35]
On develop/6 and develop/7 branches, when installing a fresh version, fct cannot be enabled. When clicking on Install in conductor, I get the following error:
00000 Errors detected
00000 Installation of "Faceted Browser" was unsuccessful.
      The installation of this VAD package has failed.
      Please delete the transaction file /data/virtuoso/db01/virtuoso.trx
      and then restart your database server.
      Note: Your database will be in its pre VAD installation state after you restart.
00000 FATAL

In virtuoso.log:
10:47:04 PL LOG: SR185: Undefined procedure DB.DBA.dpipe_define.
while executing the following statement:
--no_c_escapes-
dpipe_define ('IRI_RANK', 'DB.DBA.RDF_IRI_RANK', 'RDF_IRI_RANK', 'DB.DBA.IR_SRV', 128)
in file
10:47:04 PL LOG: SR185: Undefined procedure DB.DBA.dpipe_define.
while executing the following statement:
--no_c_escapes-
dpipe_define ('DB.DBA.IRI_RANK', 'DB.DBA.RDF_IRI_RANK', 'RDF_IRI_RANK', 'DB.DBA.IR_SRV', 128)

10:47:04 PL LOG: Errors where detected during installation of "Faceted Browser".
10:47:04 PL LOG: The installation of this VAD package has failed.
10:47:04 PL LOG: Please delete the transaction file
10:47:04 PL LOG: /data/virtuoso/db01/virtuoso.trx
10:47:04 PL LOG: and then restart your database server.
10:47:04 PL LOG: Note: Your database will be in its pre VAD installation
10:47:04 PL LOG: state after you restart.
10:47:07 Server shutdown complete

On v6 this can be worked around by installing stable/6, enabling fct and then updating to develop/6.

I am running debian,
Linux xrg13 2.6.32-5-amd64 #1 SMP Sun Sep 23 10:07:46 UTC 2012 x86_64 GNU/Linux

and configuring virtuoso like this:
./configure --prefix=/usr/local/ --with-readline --program-transform-name="s/isql/isql-v/" --with-layout=Debian --enable-fct-vad

**Comment by openlink** [comment]
A fix for this has just been pushed to develop/7

**Comment by jakubklimek** [comment]
Hi, I tried to install faceted browser in a develop/6 version and it does not work again.
