### ISSUE TITLE
Datetime problems with Jena Provider

### ISSUE THREAD

**Issue by nespera** [openlink/virtuoso-opensource#358]
I am consistently seeing datetime values misreported via the Jena Provider. Given a triple with a datetime value shown as "2014-06-21T22:59:46Z" in Conductor this is returned to Jena as a literal with value "2014-06-21T23:59:46.0". This happens if I am using a SPARQL query or Jena's Graph interface.

I am currently using version 1.10 of the Jena provider against Virtuoso 07.10.3211. I tried version 1.13 of the Jena Provider. This changed the behaviour to return a timezone, but it was still off by an hour. I can't upgrade to this version as I encountered other (more serious) problems that look related to #181.

I suspect these are related to the issues reported in #158.

**Comment by nespera** [comment]
I have also tried the _very_ latest version of the Jena provider and JDBC library from Github. Again, this produces a result which is off by an hour. By debugging and catching the SQL and issuing this via Conductor, I also get the correct data. So in the case above I get "2014-06-21 22:59:46" as the result. So it seems the problem is occurring in one of the client libraries.

**Comment by HughWilliams** [comment]
Please confirm the version of the Virtuoso Jena provider and JDBC driver being used with the commands:

   java -jar virt_jena2.jar
   java -jar virtjdbc4.jar

The Virtuoso 7.2 Jena version should be 1.15 and the JDBC Driver 3.76 , not you would also need the Virtuoso 7.2 server to use these client components and perform a correct test of the latest 7.2 release ...

**Comment by smalinin** [comment]
Thanks,  I see, the problem, the patch for current version of Jena provider is prepared. For your Jena provider build 1.10, the patch will be( But note, it will be compiled and work only with last version of Virtuoso JDBC driver) :

```
--- a/binsrc/jena2/virtuoso_driver/VirtGraph.java
+++ b/binsrc/jena2/virtuoso_driver/VirtGraph.java
@@ -39,6 +39,9 @@ import com.hp.hpl.jena.rdf.model.impl.*;

 import virtuoso.jdbc4.VirtuosoConnectionPoolDataSource;
 import virtuoso.jdbc4.VirtuosoDataSource;
+import virtuoso.jdbc4.VirtuosoDate;
+import virtuoso.jdbc4.VirtuosoTime;
+import virtuoso.jdbc4.VirtuosoTimestamp;


 public class VirtGraph extends GraphBase
@@ -1044,6 +1047,25 @@ public class VirtGraph extends GraphBase
         dt = TypeMapper.getInstance().getSafeTypeByName("http://www.w3.org/2001/XMLSchema#hexBinary");
         return Node.createLiteral(o.toString(), null, dt);

+        } else if (o instanceof VirtuosoDate) {
+
+            RDFDatatype dt = null;
+            dt = TypeMapper.getInstance().getSafeTypeByName("http://www.w3.org/2001/XMLSchema#date");
+            return NodeFactory.createLiteral(((VirtuosoDate) o).toXSD_String(), null, dt);
+
+        } else if (o instanceof VirtuosoTimestamp) {
+
+            RDFDatatype dt = null;
+            dt = TypeMapper.getInstance().getSafeTypeByName("http://www.w3.org/2001/XMLSchema#dateTime");
+            return NodeFactory.createLiteral(((VirtuosoTimestamp) o).toXSD_String(), null, dt);
+
+        } else if (o instanceof VirtuosoTime) {
+
+            RDFDatatype dt = null;
+            dt = TypeMapper.getInstance().getSafeTypeByName("http://www.w3.org/2001/XMLSchema#time");
+            return NodeFactory.createLiteral(((VirtuosoTime) o).toXSD_String(), null, dt);
+
+
       } else if (o instanceof java.sql.Date) {
```
