### ISSUE TITLE
Corrupted literals with datatypes using Jena provider 

### ISSUE THREAD

**Issue by nespera** [openlink/virtuoso-opensource#362]
I have hit a problem using the Jena provider with literals having non-standard datatypes. I am using a patched version of version 1.10 of the provider as discussed here: #358 

Literals using "standard" datatypes such as xsd:Integer are fine, but if an arbitrary URI is used for the datatype, the object node is saved with a value such as "com.hp.hpl.jena.datatypes.BaseDatatype$TypedValue@483c8ed4" as it appears to end up calling Object.toString().

I have patched my Jena jar and fixed the problem in this commit:
https://github.com/67Bricks/virtuoso-opensource/commit/afbe02c0e320a7cf08db65e9ea617e1d44e4d414

I can't open a pull request as this branch is based on a point in time where v1.10 was the current Jena provider jar.

**Comment by smalinin** [comment]
Ok, thanks, it will be committed to Jena provider code
