### ISSUE TITLE
Virtuoso crash when doing update query

### ISSUE THREAD

**Issue by EasonDong** [openlink/virtuoso-opensource#363]
I'm using Virtuoso Version 07.20.3212 on 64 bit Ubuntu

when i ran an update query in isql-v: 

``` sparql
sparql 
with <http://abc.com/Article> 
delete{?a a <http://abc.com/Author>. ?a a <http://schema.org/Person>. ?a rdfs:label ?b}
insert { graph <http://abc.com> {?a a <http://abc.com/Author>. ?a a <http://schema.org/Person>. ?a rdfs:label ?b}} 
where {?a a <http://abc.com/Author>. ?a a <http://schema.org/Person>. optional{?a rdfs:label ?b}};
```

I got 

Connected to OpenLink Virtuoso
Driver: 07.20.3212 OpenLink Virtuoso ODBC Driver

**\* Error 08S01: [Virtuoso Driver]CL065: Lost connection to server
in lines 3-5 of Top-Level:
# line 3 "(console)"

and the server log only shows 
Segmentation fault (core dumped)

Restarting the server and run the same query crash the database again with the same error. 

Any idea how to solve this problem?

**Comment by HughWilliams** [comment]
Is a core file being created when the server crashes ( note core size for user account should be set to be unlimited with command “ulimit -c unlimited” first), as if so you can create a debug unstripped Virtuoso binary, recreate the core with it and use gdb to debug it as follows:
1. Edit ~/Makefile
2. To CONFIGURE_ARGS add --with-debug
3. To CONFIGURE_ENV prepend CC='cc -g’
4. Then do "make clean all deinstall reinstall” to build a new debug  unstripped binary (virtuoso-t)
5. Start database with this new binary and force the crash condition again to generate a new core file
6. Use gdb to load core file
   
   gdb virtuoso-t  core
7. At  the prompt, type "bt" or “backtrace” to backtrace through stack and provide the output when top of stack is reached.

**Comment by EasonDong** [comment]
Hi HughWilliams, 

I came up with a workaround I wrote a java program to do the same thing using several queries. Tried to run a similar query just now and it worked fine. The core file wasn't created so now I have nothing to debug with. I'll keep an eye on it next time it happens. Thanks.
