### ISSUE TITLE
Faceted Browser: remove Gill Sans font from styles

### ISSUE THREAD

**Issue by drassokhin** [openlink/virtuoso-opensource#375]
On many systems, text rendered with Gill Sans bold looks really ugly and is very hard to read. Attached are screenshots showing the same page rendered with Gill Sans (default) and Verdana (manually overridden using dev. tools in Chrome).

Gill Sans
![gillsans](https://cloud.githubusercontent.com/assets/10214550/7215877/a9c563ea-e5b7-11e4-8974-7485d9cedaf0.png)

Verdana
![verdana](https://cloud.githubusercontent.com/assets/10214550/7215878/b23f16c4-e5b7-11e4-9c2c-bb945b777287.png)

Here's the fragment of the style definition where the change should be made:

```
body {
  margin: 0;
  padding: 0;
  font-family: Gill Sans, Verdana, Helvetica, sans-serif;
  font-size: 9pt;
  text-align: center;
}
```

**Comment by openlink** [comment]
A patch for this has been pushed to develop/6 and develop/7 branches
