### ISSUE TITLE
ADO.NET provider: incorrect handling of the VirtuosoCommand.CommandTimeout property due to integer overflow 

### ISSUE THREAD

**Issue by drassokhin** [openlink/virtuoso-opensource#376]
Here's the SendRequest method of the ManagedCommand class:

```
internal void SendRequest(ISession session, int timeout)
{
    object[] objArray = new object[] { 1, this.requestNo, null, this.service.name, this.arguments };
    if (timeout == 0)
    {
        this.endOfTime = 0L;
        this.timeout = -1;
    }
    else
    {
        this.endOfTime = DateTime.Now.Ticks + (timeout * 0x989680);
        this.timeout = timeout * 0x3e8;
    }
    ISession session2 = session;
    lock (session2)
    {
        session.Write(objArray);
       session.Flush();
    }
}
```

The (timeout \* 0x989680) expression results in an integer overflow if the timeout is set to a value greater than 214 seconds (which may be necessary for long-running complicated queries against large data sets). This, in turn, can result in either erroneous timeout exceptions or queries allowed to run much longer than expected. A partial workaround is to set the ConnectionTimeout to 0, which effectively disables the timeout so a query can run indefinitely, but this is not always desired.

**Comment by smalinin** [comment]
Fixed, patch has been sent to git maintainer
