### ISSUE TITLE
tidy_html function crashes version 7.2

### ISSUE THREAD

**Issue by rroeneman** [openlink/virtuoso-opensource#377]
Hi, let me first say I'm enjoying using Open Virtuoso! But I did run into an issue.

My Virtuoso (Ubuntu) install - a java install - seems to crash when using the tidy_html function. I've put together this report. 
Besides this I also noticed tidy has a new version - recently - with html5 support!
All this is at the outside of my technical knowledge, but do note the difference in Java VM 1.6 and JRE 1.7. Could that be a cause?
Hope you can help.

SQL Procedure, with function call: 
content := tidy_html(content, '
    output-xhtml: yes 
    char-encoding: utf8');
"content" being a varchar of HTML source code (__tag code 182). Also pages that do run fine through Sponge etc. without tidy, do crash the system when run through tidy!

Startup console info:
06:59:51 INFO: Hosting Java VM 1.6
06:59:51 INFO: OpenLink Virtuoso Universal Server
06:59:51 INFO: Version 07.20.3212-pthreads for Linux as of Mar  3 2015
06:59:51 INFO: uses parts of OpenSSL, PCRE, Html Tidy
06:59:51 INFO: Database version 3126

CRASH CONSOLE INFO:
06:56:11 INFO: virtuoso-javavm-t() [0x80e25a]
06:56:11 INFO: virtuoso-javavm-t() [0x80e2b8]
06:56:11 INFO: virtuoso-javavm-t() [0x7f568e]
06:56:11 INFO: virtuoso-javavm-t() [0x885afc]
06:56:11 INFO: virtuoso-javavm-t() [0x6a7de8]
06:56:11 INFO: virtuoso-javavm-t() [0x6b03a7]
06:56:11 INFO: virtuoso-javavm-t() [0x6dbcd2]
06:56:11 INFO: virtuoso-javavm-t() [0x6e4ca9]
06:56:11 INFO: virtuoso-javavm-t() [0x6a84ce]
06:56:11 INFO: virtuoso-javavm-t() [0x6b0817]
06:56:11 INFO: virtuoso-javavm-t() [0x6dbcd2]
06:56:11 INFO: virtuoso-javavm-t() [0x6e4ca9]
06:56:11 INFO: virtuoso-javavm-t() [0x6a84ce]
06:56:11 INFO: virtuoso-javavm-t() [0x6b0817]
06:56:11 INFO: virtuoso-javavm-t() [0x6dbcd2]
06:56:11 INFO: virtuoso-javavm-t() [0x6e4ca9]
06:56:11 INFO: virtuoso-javavm-t() [0x6a84ce]
06:56:11 INFO: virtuoso-javavm-t() [0x6b0817]
06:56:11 INFO: virtuoso-javavm-t() [0x6dbcd2]
06:56:11 INFO: virtuoso-javavm-t() [0x6e4ca9]
06:56:11 INFO: virtuoso-javavm-t() [0x6a84ce]
06:56:11 INFO: virtuoso-javavm-t() [0x6b0817]
06:56:11 INFO: virtuoso-javavm-t() [0x6dbcd2]
06:56:11 INFO: virtuoso-javavm-t() [0x6e6286]
06:56:11 INFO: virtuoso-javavm-t() [0x42141b]
06:56:11 INFO: virtuoso-javavm-t() [0x42192a]
06:56:11 INFO: virtuoso-javavm-t() [0x81168c]
06:56:11 INFO: /lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7fe2cb07d182]
06:56:11 INFO: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fe2c9a2847d]
06:56:11 ERROR: GPF: Dkbox.c:622 Double free
GPF: Dkbox.c:622 Double free
# 
# A fatal error has been detected by the Java Runtime Environment:
# 
# SIGSEGV (0xb) at pc=0x000000000080e31e, pid=4879, tid=140611396278016
# 
# JRE version: Java(TM) SE Runtime Environment (7.0_75-b13) (build 1.7.0_75-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.75-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [virtuoso-javavm-t+0x40e31e]
# 
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
# 
# An error report file with more information is saved as:
# /usr/local/var/lib/virtuoso/db/hs_err_pid4879.log
# 
# If you would like to submit a bug report, please visit:
# http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
# 

06:56:11 INFO: java VM aborted

And now Virtuoso stopped working and returned to command prompt (so did not freeze, but aborted).

Thank you for your assistance,
Kind regards,
Roeneman

**Comment by HughWilliams** [comment]
The Hosting Java VM 1.6 refer to the version to the Virtuoso hosted Java Module and not the JVM version.

Assuming "ulimit -c unlimited" is set before starting Virtuoso is a "core" file created, in which case a back trace can be obtained to determine calls being made leading up to the crash ?

**Comment by rroeneman** [comment]
The backtrace ("gdb -bt full", is this what you were looking for? 
#0  0x00007f7131adfcc9 in ?? ()
No symbol table info available.
#1  0x00007f7131ae30d8 in ?? ()
No symbol table info available.
#2  0x0000000000000020 in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.

**Comment by openlink** [comment]
On 28 April 2015 at 12:09, rroeneman notifications@github.com wrote:

> The backtrace ("gdb -bt full", is this what you were looking for?
> #0 0x00007f7131adfcc9 in ?? ()
> #1 https://github.com/openlink/virtuoso-opensource/issues/1
> 0x00007f7131ae30d8 in ?? ()
> #2 https://github.com/openlink/virtuoso-opensource/pull/2
> 0x0000000000000020 in ?? ()
> #3 https://github.com/openlink/virtuoso-opensource/pull/3
> 0x0000000000000000 in ?? ()
> 
> Hi,

It seems the binary is still stripped so the symbols showing where it was
in the code are lost. Please:
1) re-run configure --with-debug
2) check the resultant Makefile:
  on the line defining LD, ensure there is no  -s  option passed to ld;
  on the line defining STRIP, replace the strip command with /bin/true
3) re-run make, etc

You can run virtuoso from within gdb, e.g.

bash$ gdb ./virtuoso
...
gdb> run -df
...
gdb> where

Thanks,

## ~Tim

Tim Haynes
Product Development Consultant
OpenLink Software
http://www.openlinksw.com/
http://twitter.com/openlink

**Comment by rroeneman** [comment]
Well thanks, did like suggested, but can't run the virtuoso-javavm-t in gdb. He say's no file or directory found. Probably something I do wrong ...
Did re-generate the issue and run "bt full", but resulted in the same backtrace as above.
Any more suggestions?

Rgds, Roeneman

**Comment by rroeneman** [comment]
So, I figured the dbg out (for my ref: copied virtuoso-javavm-t to /db directory + chmod 777), and here is the backtrace up till step 4. Hope you can help with this info:

#0  gpf_notice (file=file@entry=0xafad83 "Dkbox.c", line=line@entry=622, text=text@entry=0xafada0 "Double free") at Dkutil.c:86
No locals.
#1  0x00000000007f568e in dk_free_box (box=0x7fffd405bf50) at Dkbox.c:622
        len = 0
        ptr = 0x7fffd405bf50 "line 16 column 14 - Warning: unknown attribute \"xmlns:xsd\"\nline 16 column 14 - Warning: unknown attribute \"xmlns:skos\"\nline 16 column 14 - Warning: unknown attribute \"xmlns:sioct\"\nline 16 column 14 - "...
        tag = 0 '\000'
        box = 0x7fffd405bf50
#2  0x00000000008859fe in bif_tidy_html (qst=<optimized out>, err_ret=<optimized out>, args=<optimized out>) at bif_tidy.c:170
        html_input = 0x7fffd40498e8 "<!doctype html>\n  \n  \n  <!--[if (IE 7)"...
        config_input = <optimized out>
        html_output = 0x7fffd40d0ce8 ""
        res = 2
        tidy_errout = {tio_data = {lm_length = 8644,
            lm_memblock = 0x7fffd405bf50 "line 16 column 14 - Warning: unknown attribute \"xmlns:xsd\"\nline 16 column 14 - Warning: unknown attribute \"xmlns:skos\"\nline 16 column 14 - Warning: unknown attribute \"xmlns:sioct\"\nline 16 column 14 - "...}, tio_pos = 4552}
#3  0x00000000006a7de8 in ins_call_bif (ins=<optimized out>, qst=qst@entry=0x7fffd0a89cc0, code_vec=code_vec@entry=0x7fffe47e3b88) at sqlintrp.c:304
        err = 0x0
        value = <optimized out>
        ins_tmp = {_ = {artm = {ins_type = 0 '\000', func = 0, result = 0x7fffd40c1b88, left = 0x2, right = 0x68}, agg = {ins_type = 0 '\000', op = 0 '\000', result = 0x7fffd40c1b88, arg = 0x2,
              set_no = 0x68, distinct = 0x2}, artm_fptr = {ins_type = 0 '\000', result = 0x7fffd40c1b88, left = 0x2, right = 0x68, func = 0x2}, pred = {ins_type = 0 '\000', succ = 0, fail = 1,
              unkn = 0, end = 7048, next_mask = 54284, func = 0x2, cmp = 0x68}, cmp = {ins_type = 0 '\000', op = 0 '\000', succ = 0, fail = 1, unkn = 0, end = 7048, next_mask = 54284,
              func = 32767, left = 0x2, right = 0x68}, label = {ins_type = 0 '\000', label = 0, nesting_level = 1}, vret = {ins_type = 0 '\000', value = 0x7fffd40c1b88}, bret = {
              ins_type = 0 '\000', bool_value = 0 '\000'}, subq = {ins_type = 0 '\000', query = 0x7fffd40c1b88, cl_cn = 0x2, cl_run = 0x68, cl_out = 0x2, cl_clb = 0x7fffe47e14b0,
              cl_set_no_in_clb = -25408, scalar_ret = 0xa1a5900}, qnode = {ins_type = 0 '\000', node = 0x7fffd40c1b88}, aref = {ins_type = 0 '\000', arr = 0x7fffd40c1b88, inx = 0x2, val = 0x68},
            open = {ins_type = 0 '\000', exclusive = 0 '\000', query = 0x7fffd40c1b88, cursor = 0x2}, fetch = {ins_type = 0 '\000', row_ctr = 0, query = 0x7fffd40c1b88, cursor = 0x2,
              targets = 0x68, set_no_ret = 0x2}, close = {ins_type = 0 '\000', cursor = 0x7fffd40c1b88}, call = {ins_type = 0 '\000', proc = 0x7fffd40c1b88 <incomplete sequence \330>, ret = 0x2,
              params = 0x68, proc_ssl = 0x2, kwds = 0x7fffe47e14b0, pn = 0x7fffd0a89cc0}, bif = {ins_type = 0 '\000', vectored = 0 '\000', proc = 0x7fffd40c1b88 <incomplete sequence \330>,
              ret = 0x2, params = 0x68, bif = 0x2}, handler = {ins_type = 0 '\000', label = 0, states = 0x7fffd40c1b88, throw_location = 0x2, throw_nesting_level = 0x68, state = 0x2,
              message = 0x7fffe47e14b0}, handler_end = {ins_type = 0 '\000', type = 0 '\000', throw_location = 0x7fffd40c1b88, throw_nesting_level = 0x2}, compound_start = {ins_type = 0 '\000',
              line_no = 0, l_line_no = 1, skip = 0, file_name = 0x7fffd40c1b88 <incomplete sequence \330>}, breakpoint = {ins_type = 0 '\000', line_no = 0, brk_set = 1, scope = 0x7fffd40c1b88},
            for_vect = {ins_type = 0 '\000', modify = 0 '\000', in_vars = 0x7fffd40c1b88, in_values = 0x2, out_vars = 0x68, out_values = 0x2, code = 0x7fffe47e14b0}}}
        ins_to_use = 0x7fffe47e3b98
#4  0x00000000006b03a7 in code_vec_run_1 (code_vec=0x7fffe47e3b88, qst=qst@entry=0x7fffd0a89cc0, offset=offset@entry=0) at sqlintrp.c:2549
        __self = 0xa2d1170
        __old_ctx = 0x7fffd0a89930
        __ctx = {buf = {{__jmpbuf = {140736694098224, -2259090554842089886, 169498880, 140736694099136, 0, 140737027319024, -2259090554519128478, 2259039654566458978}, __mask_was_saved = 0,
              __saved_mask = {__val = {140736694098016, 140736694098128, 140736694098240, 140736694097904, 0, 0, 5983729, 140736820338752, 4303313201, 21335, 140736750933016, 140736694099136,
                  140736750933016, 140736694099136, 40, 140736750926016}}}}}
        reset_code = <optimized out>
        __tlsf = 0x0
        nesting_level = 1
        ins = 0x7fffe47e3b98
        prev_ins = 0x7fffe47e3b98
        prev_breakpoint_ins = 0x0
        qi = 0x7fffd0a89cc0
        no_vec = 0

Thank you!
Roeneman

**Comment by openlink** [comment]
We replaced the tidy code with a more recent version.

Please use the latest code from the develop/7 branch.
