### ISSUE TITLE
Error 42000: SR159:SECURITY: Function __set_user_id restricted to DBA group

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#380]
I updated to the latest develop version ccf9803f3ae06277a02ff1886eda680c3623dc26
and when I access http://localhost:8890/describe/?url=http://aaa or try to describe any other url this way, I get:
```Error 42000

SR159:SECURITY: Function __set_user_id restricted to DBA group.

```
```

**Comment by HughWilliams** [comment]
@jakubklimek: I have been able to recreate and reported to development to fix ...

**Comment by openlink** [comment]
A fix for this issue was committed to develop/6 and develop/7 branches

**Comment by jakubklimek** [comment]
Still not working after update to 6416f9bec352a84f863aa8e558aa444d8550fc94

**Comment by openlink** [comment]
A secondary fix was needed to fix a couple of permission issues. Please try again.

**Comment by jakubklimek** [comment]
Works
