### ISSUE TITLE
abs() casts results to xsd:integer

### ISSUE THREAD

**Issue by knoan** [openlink/virtuoso-opensource#382]
The following [query](http://yasgui.org/#query=prefix+dbo%3A+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0A%0Aselect+%3Fa+%3Fl+%28abs%28%3Fl%29+as+%3Fabs%29+%7B%0A++%0A++%3Fa+a+dbo%3AAutomobile%3B+dbo%3Alength+%3Fl%0A++++%0A%7D+limit+10&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=http%3A%2F%2Fdbpedia.org%2Fsparql&requestMethod=POST&tabTitle=Query+2&outputFormat=table) is casting `xsd:double` values to `xsd:integer` on the http://dbpedia.org/sparql endpoint (Virtuoso 7.20).

```
prefix dbo: <http://dbpedia.org/ontology/>

select ?a ?l (abs(?l) as ?abs) {

  ?a a dbo:Automobile; dbo:length ?l

} limit 10
```

Same behaviour with `xsd:decimal` on a private endpoint.

Very likely related to #211.

**Comment by HughWilliams** [comment]
You mean the "abs(?l)"  ? As that does not seem unreasonable to me give the absolute value is an "integer" ?

**Comment by knoan** [comment]
?l returns `xsd:double` values: I'd expect `abs(?l)` to preserve the datatype and the fractional part of the value as per http://www.w3.org/TR/sparql11-query/#func-abs and http://www.w3.org/TR/xpath-functions/#func-abs.

**Comment by HughWilliams** [comment]
This issue has been reported to development to look into ...

**Comment by openlink** [comment]
This has been fixed in the latest develop/7 branch.
