### ISSUE TITLE
Missing CORS headers on error responses

### ISSUE THREAD

**Issue by knoan** [openlink/virtuoso-opensource#385]
HTTP responses with 500 (and likely 400) error status codes don’t include CORS access control  headers (Access-Control-Allow-Origin:*).

This issue is severe for browser-based apps, which won't be able to properly report endpoint errors to the user, as the missing CORS headers prevent them from accessing status codes/details from XHR objects.

This issue is also likely to prevent browser-based apps to access Virtuoso SPARQL endpoints secured with HTTP Basic/Digest authentication when running under Internet Explorer, as this browser requires application-level handling of 401 Unauthorized status codes on CORS resources.

In order to support such features CORS headers must be included in all HTTP responses regardless of the status code.

The following [query](http://yasgui.org/#query=prefix+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%0Aselect+%3Fs+%3Fl+%7B%0A++++%3Fs+%3Fp+%3Fo+optional+%7B+%3Fs+rdfs%3Alabel+%3Fl+%7D%0A%7D+order+by+%3Fl+&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=http%3A%2F%2Fdbpedia.org%2Fsparql&requestMethod=POST&tabTitle=Query+2&outputFormat=table) demonstrates the issue on the http://dbpedia.org/sparql endpoint (Virtuoso 7.20).

```
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?s ?l {
    ?s ?p ?o optional { ?s rdfs:label ?l }
} order by ?l 
```

**Comment by openlink** [comment]
A patch for this has been pushed to develop/7 branch.

**Comment by sthenault** [comment]
as of virtuoso 7.2, I can confirm that this problem is fixed and issue could be closed.
