### ISSUE TITLE
SPARQL Sesame graph encapsulation

### ISSUE THREAD

**Issue by ale003** [openlink/virtuoso-opensource#390]
Hi,
I am using Virtuoso through the Sesame2 driver. I would like to make a SPARQL query to one specific graph without specifying this in the SPARQL FROM construct. Is this possible?

I was expecting that if I created a VirtuosoRepository by giving explicitly the graphName, all insert and SPARQL queries will be executed only for the specific graph.

The problem is that the SPARQL queries are always executed for the default graph (so for all graphs at once).

In my application it is very important to keep encapsulated the various graph databases as they can belong to completely different users. Can I do this in Virtuoso?

My code looks like this:
sr = new VirtuosoRepository(jdbcLocation,user,pass,graphName);
src = sr.getConnection();
vf = sr.getValueFactory();
src.add(subj,pred,obj,graphName);
TupleQuery tQuery = src.prepareTupleQuery(QueryLanguage.SPARQL, queryString,graphName);
TupleQueryResult result = tQuery.evaluate();
--> result contains the result from all graphs!

Thank you for your help!

**Comment by ale003** [comment]
By the way, I am not sure if this is a bug or it is intended.

**Comment by smalinin** [comment]
The code must looks like:

```
import org.openrdf.query.*;
import org.openrdf.query.impl.*;
import org.openrdf.model.URI;

sr = new VirtuosoRepository(jdbcLocation,user,pass,graphName);
src = sr.getConnection();
vf = sr.getValueFactory();
src.add(subj,pred,obj,graphName);
TupleQuery tQuery = src.prepareTupleQuery(QueryLanguage.SPARQL, queryString,graphName);
Dataset ds = new DatasetImpl();
ds.addDefaultGraph(src.getValueFactory().createURI(graphName));
tQuery.setDataset(ds);
TupleQueryResult result = tQuery.evaluate();
```

**Comment by ale003** [comment]
Thank you! You saved me a lot of time.
Your code is working as expected. I only needed to change
Dataset ds = new DatasetImpl(); -->DatasetImpl ds = new DatasetImpl(); 
because in my version of sesame DataSet does not contain the addDefaultGraph method.

Still one question remains is the graphName needed in these two lines:
sr = new VirtuosoRepository(jdbcLocation,user,pass,graphName);
TupleQuery tQuery = src.prepareTupleQuery(QueryLanguage.SPARQL, queryString,graphName);

I tried with an without the graphName parameter and nothing seems to change.

For the next time, could you point me to some Sesame documentation where this kind of things are written? I searched for it but only the javadocs exists and from this it is difficult to understand this kind of tricky settings.

Thank you again.
Alessandro

**Comment by smalinin** [comment]
```
sr = new VirtuosoRepository(jdbcLocation,user,pass,graphName);
```

graphName - now it is used, if contexts parameter is empty in VirtuosoRepositoryConnection methods
     but it isn't used for execute SPARQL queries

```
  TupleQuery tQuery = src.prepareTupleQuery(QueryLanguage.SPARQL, queryString,graphName);
```

the last parameter isn't graphName, it is baseURI and it isn't used in Virtuoso Sesame provider now

The my version of code with Dataset will work properly with all types of Sesame repositories.
p.s.
I will try to add the docs links, if I found it (in next time).

**Comment by ale003** [comment]
Ok now it is clear.
I must have lost some piece while compiling sesame with IKVM, I will check.

Thank you again for your help.
