### ISSUE TITLE
Problems in Adding Data

### ISSUE THREAD

**Issue by amirSharif32dm** [openlink/virtuoso-opensource#396]
Hi dears

in a instruction says:
###### 

We will use Virtuoso to provide the backend for querying this data. Make sure you have Virtuoso downloaded and compiled

Start the server:

scripts/virtuoso start tutorial.vdb 3001
Add the small graph to the database:

scripts/virtuoso add data/tutorial.ttl 3001
###### 

second line(adding) gives me this problem:
###### 

amir2@ubuntu:~/Documents/sempre-master$ scripts/virtuoso add data/tutorial.ttl 3001
/usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- fig/bin/../lib/myutils (LoadError)
    from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from fig/bin/chunk:3:in `<main>'
scripts/virtuoso:18:in`Integer': invalid value for Integer(): "" (ArgumentError)
    from scripts/virtuoso:18:in `parseInt'
    from scripts/virtuoso:126:in`add'
    from scripts/virtuoso:206:in `<main>'
###### 

I have ubuntu 14.10 and I ve installed last version of Ruby.
Can you please tell me how to fix it???
Tnx

**Comment by HughWilliams** [comment]
What Ruby application/service are you using to add data to Virtuoso ? Please provide more details steps on what you are attempting to do ...

**Comment by amirSharif32dm** [comment]
Thanks for your attention:

Ruby that was installed :
##
amir2@ubuntu:~$ ruby -v
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
amir2@ubuntu:~$ gem -v
2.4.6
##

I want to work with Sempre:
https://github.com/percyliang/sempre/blob/master/TUTORIAL.md

in this part
it Starts server and adds a small dataset.and runs java application
(by Sparql Executor)

**Comment by openlink** [comment]
The problem is in the ruby script provided by the https://github.com/percyliang/sempre project which seems to pop a wrong argument, which is not an integer value.

This script is written by that project, not by the Virtuoso team, so i suggest you ask them what the correct commandline syntax is. It is possible they added an extra argument, without updating their Tutorial

**Comment by amirSharif32dm** [comment]
thank u.I will ask them.
