### ISSUE TITLE
Can't change password with CLI argument

### ISSUE THREAD

**Issue by white-gecko** [openlink/virtuoso-opensource#402]
I'm trying to change the default "dba" password, when starting the virtuoso server using the CLI argument `+pwddba`. As I understand the `--help` text:

```
  +pwdold                Old DBA password
  +pwddba                New DBA password
  +pwddav                New DAV password
```

It the password of the virtuoso started with the following command should be `hello` instead of `dba` while it actually is `dba`.

```
/var/lib/virtuoso/db# /usr/bin/virtuoso-t -c virtuoso +foreground +pwdold dba +pwddba hello
```

Am I not understanding the `--help` text correctly or are I missing other details? As I see the situation it doesn't work and is a bug …

Thank you
Natanael

**Comment by HughWilliams** [comment]
The is a bug that was fixed last month in the latest develop/7 branch, see:

   http://sourceforge.net/p/virtuoso/virtuoso-opensource/ci/855f383206a26f8f7bbb700085ee9327f71269cb

**Comment by white-gecko** [comment]
Ok, thanks, but it currently doesn't build on debian :-\ #342

**Comment by sofiageo** [comment]
is this going to be fixed for the develop/6 ?

**Comment by white-gecko** [comment]
Just an additional question regarding virtuoso password management. Where is the password stored? If I move the `/var/lib/virtuoso/db/` folder to some other machine an run virtuoso on it, will I have the dba-password set on the first machine?

**Comment by openlink** [comment]
On 20 May 2015 at 14:20, Natanael Arndt notifications@github.com wrote:

> Just an additional question regarding virtuoso password management. Where
> is the password stored? If I move the /var/lib/virtuoso/db/ folder to
> some other machine an run virtuoso on it, will I have the dba-password set
> on the first machine?

Hi,
select \* from sys_users;
So yes it will follow you around wherever you copy the db file (assuming
you've checkpointed it first, of course).
HTH

## ~Tim

Tim Haynes
Product Development Consultant
OpenLink Software
http://www.openlinksw.com/
http://twitter.com/openlink

**Comment by ezyk** [comment]
Hello, when will be merged to the stable/6 branch?
