### ISSUE TITLE
Two files whose name only differ by case: creates naming conflict on OS X.

### ISSUE THREAD

**Issue by maparent** [openlink/virtuoso-opensource#403]
In 8e47d57cb3468afc1fbb8b092397a23c71542dc7, you have introduced 
`docsrc/xmlsource/funcref/ST_SRID.xml` and `docsrc/xmlsource/funcref/ST_SetSRID.xml`, whose names conflict with `docsrc/xmlsource/funcref/st_srid.xml` and `docsrc/xmlsource/funcref/st_setsrid.xml` respectively in OS X's annoying case-insensitive file system.
Could those files be renamed?
Thank you.

**Comment by openlink** [comment]
I updated the documentation in develop/7 branch and removed the duplicate files
