### ISSUE TITLE
Can't delete files with WebDAV browser

### ISSUE THREAD

**Issue by sebdg** [openlink/virtuoso-opensource#410]
Hi all, 

There seem to be some issue with the delete buttons of the webdav browser.
I've build from the repo using version: 07.20.3213

After uploading a file i can't delete it.
I get to the confirmation dialog with the list of files to delete but the Delete button doesn't do anything.
In appearance at least, because i could catch  a POST request that is returning a code 500.

SR185: Undefined procedure VAL.DBA.authentication_details_for_connection.

I can't dig deeper into this now and worked my way around using the DAV functions to delete my files.

Kind Regards

**Comment by openlink** [comment]
I have passed your comments to the development team. We should have a fix for this issue soon.

**Comment by openlink** [comment]
A fix for this has been pushed to the develop/7 branch

**Comment by sebdg** [comment]
Splendid.
You guys rock ! 
Many Thanks.

**Comment by sebdg** [comment]
Tested! Works great.

A little sugestion maybe turn the red to green when everything succeeds.
