### ISSUE TITLE
Error installing Virtuoso Conductor

### ISSUE THREAD

**Issue by ssingh8008** [openlink/virtuoso-opensource#413]
```
    Thu May 21 2015
```

18:19:34 OpenLink Virtuoso Universal Server
18:19:34 Version 06.01.3127-pthreads for Linux as of Sep 24 2013
18:19:34 uses parts of OpenSSL, PCRE, Html Tidy
18:19:34 Database version 3126
18:19:34 SQL Optimizer enabled (max 1000 layouts)
18:19:36 Compiler unit is timed at 0.000603 msec
18:19:36 built-in procedure "repl_undot_name" overruled by the RDBMS
18:19:36 built-in procedure "REPL_FQNAME" overruled by the RDBMS
18:19:36 built-in procedure "REPL_COLTYPE_PS" overruled by the RDBMS
18:19:36 built-in procedure "REPL_COLTYPE" overruled by the RDBMS
18:19:36 Roll forward started
18:19:36 Roll forward complete
18:19:36 PL LOG: Installing Virtuoso Conductor version 1.00.8744 (DAV)
18:19:36 Checkpoint started
18:19:36 Checkpoint finished, log reused
18:19:36 PL LOG: VAD_INSTALL: Please update server version (FATAL)                     <------ HERE
18:19:36 PL LOG: Errors where detected during installation of "Virtuoso Conductor".    <------- HERE
18:19:36 Checkpoint started
18:19:36 Checkpoint finished, log reused
18:19:36 HTTP/WebDAV server online at 8890
18:19:36 Server online at 1111 (pid 7754)

I am unable to start the conductor services. Please advise. I have tried various steps, including -
http://shadok.enst.fr:8890/doc/html/fn_vad_install.html
I even installed virtuoso-vad-conductor_6.1.0-0ubuntu3_all.deb in case it did not install automatically

I used TallTed's answer from the link below
http://answers.semanticweb.com/questions/3830/virtuoso-errors-with-virtuoso-t-f-command
to take care of
15:48:17   FAILED  plugin 1: Unable to locate file }
15:48:17 { Loading plugin 2: Type `plain', file`mediawiki' in `/usr/lib/virtuoso-opensource-6.0/hosting'
15:48:17   FAILED  plugin 2: Unable to locate file }
15:48:17 { Loading plugin 3: Type`plain', file `creolewiki' in`/usr/lib/virtuoso-opensource-6.0/hosting'
15:48:17   FAILED  plugin 3: Unable to locate file }
15:48:17 { Loading plugin 4: Type `plain', file`im' in `/usr/lib/virtuoso-opensource-6.0/hosting'

I have been following instructions(and using the resources) from https://github.com/openlink/virtuoso-opensource to install Virtuoso.

Please advise.

**Comment by HughWilliams** [comment]
What version of Virtuoso are you seeking to us  6 or 7 ?

As the error indicates you are using a version 6 binary as indicated in your log i.e. 06.01.3127  with a version 7 conductor_dav.vad package 1.00.8744 as indicated in the log, which are incompatible ...

Assuming you are seeking to use the latest Virtuoso 7 release then you should build all the components from the  https://github.com/openlink/virtuoso-opensource git source tree and ensure a the Virtuoso 7  built is what is being used rather them some old 6 version which is probably from one of the ubuntu debian packages built by the debian maintainers and rather old and should not be mixed.

The instructions for building from git are available at:

   http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VOSGIT

**Comment by ssingh8008** [comment]
Ok thank you Hugh, I actually uninstalled and purged it and followed http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VOSUbuntuNotes and it installed Virtuoso perfectly. I really appreciate the answer though.
