### ISSUE TITLE
Virtuoso 7.1 and 7.2 hanging when importing UMBEL reference concepts

### ISSUE THREAD

**Issue by fgiasson** [openlink/virtuoso-opensource#418]
Virtuoso 7.1 and 7.2 appears to be hanging when importing this UMBEL reference concepts file:
- https://raw.githubusercontent.com/structureddynamics/UMBEL/master/Reference%20Structure/umbel_reference_concepts.n3

I am importing it using this command:

```
DB.DBA.TTLP_MT(file_to_string_output('/data/ontologies/files/umbel_reference_concepts.n3');
```

Then the file start to get loaded into the dataset. However, it eventually stops and hang Virtuoso. If I connect to iSQL in the command line, and run the `status();` command I am getting the following:

About 160 000 fines of:

```
      336: IER NO_CONN
      332: IER NO_CONN
      328: IER NO_CONN
      324: IER NO_CONN
      320: IER NO_CONN
      316: IER NO_CONN
      312: IER NO_CONN
      308: IER NO_CONN
      304: IER NO_CONN
      300: IER NO_CONN
      296: IER NO_CONN
      292: IER NO_CONN
      288: IER NO_CONN
      284: IER NO_CONN
      280: IER NO_CONN
      276: IER NO_CONN
      272: IER NO_CONN
      268: IER NO_CONN
      264: IER NO_CONN
      260: IER NO_CONN
      256: IER NO_CONN
      252: IER NO_CONN
      248: IER NO_CONN
      244: IER NO_CONN
      240: IER NO_CONN
      236: IER NO_CONN
      232: IER NO_CONN
      228: IER NO_CONN
      224: IER NO_CONN
      220: IER NO_CONN
      216: IER NO_CONN
      212: IER NO_CONN
      208: IER NO_CONN
      204: IER NO_CONN
      200: IER NO_CONN
      196: IER NO_CONN
      192: IER NO_CONN
      188: IER NO_CONN
      184: IER NO_CONN
      180: IER NO_CONN
      176: IER NO_CONN
      172: IER NO_CONN
      168: IER NO_CONN
      164: IER NO_CONN
      160: IER NO_CONN
      156: IER NO_CONN
      152: IER NO_CONN
      148: IER NO_CONN
      144: IER NO_CONN
      140: IER NO_CONN
      136: IER NO_CONN
      132: IER NO_CONN
      128: IER NO_CONN
      124: IER NO_CONN
      120: IER NO_CONN
      116: IER NO_CONN
      112: IER NO_CONN
      108: IER NO_CONN
      104: IER NO_CONN
      100: IER NO_CONN
      96: IER NO_CONN
      92: IER NO_CONN
      88: IER NO_CONN
      84: IER NO_CONN
      80: IER NO_CONN
      76: IER NO_CONN
      72: IER NO_CONN
      68: IER NO_CONN
      64: IER NO_CONN
      60: IER NO_CONN
      56: IER NO_CONN
      52: IER NO_CONN
      48: IER NO_CONN
      44: IER NO_CONN
      40: IER NO_CONN
      36: IER NO_CONN
      32: IER NO_CONN
      28: IER NO_CONN
      24: IER NO_CONN
      20: IER NO_CONN
      16: IER NO_CONN
      12: IER NO_CONN
      8: IER NO_CONN
      4: IER NO_CONN
      0: IER NO_CONN
      361: IER NO_CONN
      357: IER NO_CONN
      353: IER NO_CONN
      349: IER NO_CONN
      345: IER NO_CONN
      341: IER NO_CONN
      337: IER NO_CONN
      333: IER NO_CONN
      329: IER NO_CONN
      325: IER NO_CONN
      321: IER NO_CONN
      317: IER NO_CONN
      313: IER NO_CONN
      309: IER NO_CONN
      305: IER NO_CONN
      301: IER NO_CONN
      297: IER NO_CONN
      293: IER NO_CONN
      289: IER NO_CONN
      285: IER NO_CONN
      281: IER NO_CONN
      277: IER NO_CONN
      273: IER NO_CONN
      269: IER NO_CONN
      265: IER NO_CONN
      261: IER NO_CONN
      257: IER NO_CONN
      253: IER NO_CONN
      249: IER NO_CONN
      245: IER NO_CONN
      241: IER NO_CONN
      237: IER NO_CONN
      233: IER NO_CONN
      229: IER NO_CONN
      225: IER NO_CONN
      221: IER NO_CONN
      217: IER NO_CONN
      213: IER NO_CONN
      209: IER NO_CONN
      205: IER NO_CONN
      201: IER NO_CONN
      197: IER NO_CONN
      193: IER NO_CONN
      189: IER NO_CONN
      185: IER NO_CONN
      181: IER NO_CONN
      177: IER NO_CONN
      173: IER NO_CONN
      169: IER NO_CONN
      165: IER NO_CONN
      161: IER NO_CONN
      157: IER NO_CONN
      153: IER NO_CONN
      149: IER NO_CONN
      145: IER NO_CONN
      141: IER NO_CONN
      137: IER NO_CONN
      133: IER NO_CONN
      129: IER NO_CONN
      125: IER NO_CONN
      121: IER NO_CONN
      117: IER NO_CONN
      113: IER NO_CONN
      109: IER NO_CONN
      105: IER NO_CONN
      101: IER NO_CONN
      97: IER NO_CONN
      93: IER NO_CONN
      89: IER NO_CONN
      85: IER NO_CONN
      81: IER NO_CONN
      77: IER NO_CONN
      73: IER NO_CONN
      69: IER NO_CONN
      65: IER NO_CONN
      61: IER NO_CONN
      57: IER NO_CONN
      53: IER NO_CONN
      49: IER NO_CONN
      45: IER NO_CONN
      41: IER NO_CONN
      37: IER NO_CONN
      33: IER NO_CONN
      29: IER NO_CONN
      25: IER NO_CONN
      21: IER NO_CONN
      17: IER NO_CONN
      13: IER NO_CONN
      9: IER NO_CONN
      5: IER NO_CONN
      1: IER NO_CONN
      362: IER NO_CONN
      358: IER NO_CONN
      354: IER NO_CONN
      350: IER NO_CONN
      346: IER NO_CONN
      342: IER NO_CONN
      338: IER NO_CONN
      334: IER NO_CONN
      330: IER NO_CONN
      326: IER NO_CONN
      322: IER NO_CONN
      318: IER NO_CONN
      314: IER NO_CONN
      310: IER NO_CONN
      306: IER NO_CONN
      302: IER NO_CONN
      298: IER NO_CONN
      294: IER NO_CONN
      290: IER NO_CONN
      286: IER NO_CONN
      282: IER NO_CONN
      278: IER NO_CONN
      274: IER NO_CONN
      270: IER NO_CONN
      266: IER NO_CONN
      262: IER NO_CONN
      258: IER NO_CONN
      254: IER NO_CONN
      250: IER NO_CONN
      246: IER NO_CONN
      242: IER NO_CONN
      238: IER NO_CONN
      234: IER NO_CONN
      230: IER NO_CONN
      226: IER NO_CONN
      222: IER NO_CONN
      218: IER NO_CONN
      214: IER NO_CONN
      210: IER NO_CONN
      206: IER NO_CONN
      202: IER NO_CONN
      198: IER NO_CONN
```

Then the last lines returned by the command:

```
      83: IER 4
      79: IER 4
      47: IER 4
      43: IER 4
      39: IER 4
      35: IER 4
      31: IER 4
      27: IER 4
      19: IER 4
      7: IER 4
      3: IER 4
  50: IER 4
Trx 4 s=1 0x7fdcc4003990:  w. for:
   is before:  NO_CONN
Trx NO_CONN s=1 0x9a80440: for 498211 ms  w. for:  4
   is before:  NO_CONN
Trx NO_CONN s=1 0x9f7c1b0: for 502716 ms  w. for:  NO_CONN
   is before:

Client 1111:4:  Account: dba, 4431 bytes in, 1543 bytes out, 1 stmts.
PID: 31905, OS: unix, Application: unknown, IP#: 127.0.0.1
Transaction status: PENDING, 1 threads.
Locks: 6387: IE, 100: IE, 6330: IE, 6381: IE, 19980: IE, 6388: IE, 6395: IE, 6327: IE, 6328: IE, 6393: IE, 6318: IE, ....

Client 1111:5:-6:  Account: dba, 572 bytes in, 27439137 bytes out, 1 stmts.
PID: 32439, OS: unix, Application: unknown, IP#: 127.0.0.1
Transaction status: PENDING, 1 threads.
Locks:


Running Statements:
 Time (msec) Text
        1906 status()
      517498 DB.DBA.TTLP_MT(file_to_string_output('/data/ontologies/files/umbel_reference_con


Hash indexes


166735 Rows. -- 7857 msec.
```

I would like to know:
- if you are able to reproduce this issue
- what cause this issue (is it something that can be fixed in the N3 file?
- is there a way to load the file without waiting for a possible fix?

**Comment by fgiasson** [comment]
I just tried with a XML serialization, same result.

Also, I noticed that it always stop indexing triples once there are 106403 triples indexed. Maybe there is a tripled in there that it doesn't like.

Also: I have plenty of ram available (100G for the process) and the disk where the virtuoso.db file has many G free.

**Comment by fgiasson** [comment]
Did test with the `umbel 1.10` version:

```
https://raw.githubusercontent.com/structureddynamics/UMBEL/version-1.10/Reference%20Structure/umbel_reference_concepts.n3
```

Same result, but I have roughly 40 000 lines returned by `status()`

**Comment by HughWilliams** [comment]
@fgiasson:  I downloaded the dataset and it loads fine for me in no time:

SQL> TTLP_MT(file_to_string_output('./umbel_reference_concepts.n3'), '', 'fred');

Done. -- 5200 msec.
SQL> sparql select count(*) from <fred> {?s ?p ?o};
callret-0
INTEGER

---

402173

1 Rows. -- 243 msec.
SQL> status('');
REPORT
VARCHAR

---

OpenLink Virtuoso  Server
Version 07.20.3213-pthreads for Linux as of Apr 24 2015 
Started on: 2015-05-29 11:02 GMT+2

Database Status:
  File size 0, 24320 pages, 18837 free.
  1000000 buffers, 3321 used, 2561 dirty 0 wired down, repl age 0 0 w. io 0 w/crsr.
  Disk Usage: 864 reads avg 0 msec, 0% r 0% w last  435 s, 110 writes flush          0 MB,
    25 read ahead, batch = 17.  Autocompact 0 in 0 out, 0% saved.
Gate:  150 2nd in reads, 0 gate write waits, 0 in while read 0 busy scrap. 
Log = virtuoso.trx, 56086679 bytes
2855 pages have been changed since last backup (in checkpoint state)
Current backup timestamp: 0x0000-0x00-0x00
Last backup date: unknown
Clients: 1 connects, max 1 concurrent
RPC: 16 calls, 1 pending, 1 max until now, 0 queued, 0 burst reads (0%), 0 second 0M large, 183M max
Checkpoint Remap 38 pages, 0 mapped back. 0 s atomic time.
    DB master 24320 total 18837 free 38 remap 2 mapped back
   temp  1024 total 1019 free

Lock Status: 0 deadlocks of which 0 2r1w, 4 waits,
   Currently 1 threads running 0 threads waiting 0 threads in vdb.
Pending:

23 Rows. -- 148 msec.
SQL> 

Please provide the complete output of running status on the machine and also what the current triple count of the server is ?

**Comment by fgiasson** [comment]
Hi @HughWilliams!

Here is the complete output:

```
https://gist.github.com/fgiasson/9aaf775bda22d479a418
```

The number of triples in the triple store has 3 255 199 751 (so, 3.2 billion triples). 

The server has 8 cores and 128G RAM. The main configurations in `virtuoso.ini` are:
- NumberOfBuffers          = 9450000
- MaxDirtyBuffers            = 7000000
- MaxQueryMem             = 2G  
- VectorSize                     = 1000
- MaxVectorSize              = 3000000  
- MaxMemPoolSize              = 200000000
- ResultSetMaxRows           = 10000
- MaxQueryCostEstimationTime = 65535 
- MaxQueryExecutionTime      = 65535  

Otherwise, all other settings have the defaults.

I had no issues importing Freebase a few weeks back on this server, so this is why it is kind of stange that this is not happening.

Thanks!

**Comment by HughWilliams** [comment]
@fgiasson: When loading the dataset do you set   log_enable(2) before the loading to disable transaction logging  and reduce memory requirements for the load , not that the dataset in particularly large  especially in comparison with the available memory.

How did you load the 3.2billions triples currently in the database, was it loaded using TTLP_MT, or was the RDF Bulk Loader used, automatically set log_enable(2) before loading datasets ?

The status() output does not showing an locks or deadlock and there seem to be enough memory buffers available, so I assume the server can still be accessed from other clients.

**Comment by fgiasson** [comment]
Hi @HughWilliams,

That was exactly the problem. A few questions regarding the transaction logging:
- what is the impact of disabling it?
- what is the benefit of _using_ transaction logging when dealing with RDF data importation/creation only (via the Virtuoso API and/or SPARQL Update)?

Thanks!

Take care 

Fred

**Comment by fgiasson** [comment]
@HughWilliams, another question regarding this issue:
- How does the size of the current DB affect the memory required to use the transaction log?

**Comment by HughWilliams** [comment]
@fgiasson: The impact of disabling transaction logging is that all operations are automatically committed when done, and as SPARQL updates are generally not meant to be transactional logging should be turned off when using the APIs or SPARQL update via the endpoint etc. See:

   http://docs.openlinksw.com/virtuoso/rdfperformancetuning.html#rdfperfsparul

If transaction logging it is more the size of the update that affects the memory required which is why it should be turned off for large updates, which can then deplete memory. The size of the database or RDF data would affect the memory requirement when SPARUL operations are performed as they would need to be added to the indexes whose size increases with the existing data size.

**Comment by fgiasson** [comment]
great, thanks for the information @HughWilliams!
