### ISSUE TITLE
Error during the "isparql_dav.vad" installation step (branch develop/7)

### ISSUE THREAD

**Issue by jplu** [openlink/virtuoso-opensource#42]
Hi,

During the compilation of the develop/7 branch. I fall on this error (from the log file) :

Cleaning the vad directory
Creating the vad directory
Virtuoso.ini creation...
PASSED: virtuoso successfully started on port 1111
iSPARQL VAD sticker creation...
-  isql localhost:1111 dba dba ERRORS=STDOUT VERBOSE=OFF PROMPT=OFF EXEC=DB.DBA.VAD_PACK('make_isparql_vad.xml', '.', 'isparql_dav.vad')
  ***FAILED: starting DB.DBA.VAD_PACK('make_isparql_vad.xml', '.', 'isparql_dav.vad')
-  isql localhost:1111 dba dba ERRORS=STDOUT VERBOSE=OFF PROMPT=OFF EXEC=commit work
  ***FAILED: starting commit work
-  isql localhost:1111 dba dba ERRORS=STDOUT VERBOSE=OFF PROMPT=OFF EXEC=checkpoint
  ***FAILED: starting checkpoint
  Shutdown localhost:1111 ...
  Cleaning the vad directory
# 
# =  Checking log file /home/julien-plu/virtuoso-opensource/binsrc/isparql/make_isparql_vad.log for statistics:

=  Total number of tests PASSED  : 1
=  Total number of tests FAILED  : 3
# =  Total number of tests ABORTED : 0

**\* Not all tests completed successfully
**\* Check the file /home/julien-plu/virtuoso-opensource/binsrc/isparql/make_isparql_vad.log for more information
- egrep "**._FAILED:|\_*.*ABORTED:" /home/julien-plu/virtuoso-opensource/binsrc/isparql/make_isparql_vad.log
# 

=  COMPLETED VAD PACKAGING
# =  Fri Apr 26 12:16:38 CEST 2013

Is-it normal ? Or is-it a bug ?

Best.

Julien.

**Comment by jplu** [comment]
Solved !

**Comment by ruggerman** [comment]
Hi I am University student in Japan and I got the same error and I don't know how to solve it. But you did it. How did you it? Please tell me.
