### ISSUE TITLE
ADO.NET provider: VirtuosoCommand.Cancel() has no effect

### ISSUE THREAD

**Issue by drassokhin** [openlink/virtuoso-opensource#422]
Tested with OpenLink.Data.Virtuoso.dll 6.2.3128.1 and virtado4.dll 4.0.0.0.

```
var conn = new OpenLink.Data.Virtuoso.VirtuosoConnection(connString);
...
var cmd = conn.CreateCommand();
...
var r = cmd.ExecuteReader();
...
while (r.Read())
{
    ...
}
```

Calling

```
cmd.Cancel();
```

asynchronously from a thread other than the worker thread currently executing cmd.ExecuteReader() has no effect. The command keeps running to completion on the server and the worker thread keeps waiting for ExecuteReader() method call to return. The desired behavior would be for the server to stop processing the query, the ExecuteReader() to return immediately and the subsequent call to r.Read() to return false.

**Comment by smalinin** [comment]
Fixed

**Comment by drassokhin** [comment]
Re-tested with OpenLink Virtuoso  Server Version 07.20.3215-threads for Win64 as of Dec 10 2015 and virtado4 from NuGet OpenLink Virtuoso ADO.Net Provider 7.20.3214.1 package. Now the Cancel() method hangs. When this happens in the main application thread, the application has to be killed.

Stack trace:

```
System.dll!System.Net.Sockets.Socket.Poll(int microSeconds, System.Net.Sockets.SelectMode mode) + 0x12b bytes   
virtado4.dll!OpenLink.Data.Virtuoso.TcpSession.PollRead(int microSeconds) + 0x4e bytes  
virtado4.dll!OpenLink.Data.Virtuoso.Future.GetResult(OpenLink.Data.Virtuoso.ISession session = {OpenLink.Data.Virtuoso.TcpSession}, OpenLink.Data.Virtuoso.FutureList futures = {OpenLink.Data.Virtuoso.FutureList}, bool remove = false) + 0x2ae bytes 
virtado4.dll!OpenLink.Data.Virtuoso.ManagedCommand.Cancel() + 0xf9 bytes    
virtado4.dll!OpenLink.Data.Virtuoso.VirtuosoCommand.Cancel() + 0x39 bytes   
```

**Comment by HughWilliams** [comment]
Dmitrii,  A 7.20.3214.1 version of the provider would be from a Release 7.2.1 provider from the Jun 2015 release and there were fixed to the provider since then for  hang and cancel issues you reported last year. You can download a 7.20.3216.1 of the Provider for the upcoming 7.2.2 release which would contain the latest fixes from:

   ftp://download.openlinksw.com/support/virtuoso/virtado4.dll

**Comment by drassokhin** [comment]
Hugh, would it be possible to deliver the updated version of virtado4 as a NuGet package? I have downloaded virtado4.dll (file version 7.20.3216.2) from the link you provided and am going to test it later today. However, we have several projects that depend on virtato4.dll with automated build/unit testing/packaging set up for these projects. Having a dependency on a particular dll downloaded from somewhere and referenced in the projects explicitly creates a whole lot of headaches for us, since we have to remove the dependency on the Virtuoso NuGet package, add the dll binary to our source code control system, adjust the build and deployment scripts and manually track versions and updates of that dependency.

**Comment by HughWilliams** [comment]
@drassokhin: This is something development would need to schedule to create a package for, thus I have logged an internal issue tracker for this, but it is unlikely to be done immediately ...
