### ISSUE TITLE
Large "COUNT... ORDER BY" sparql query sometimes hangs for hours when using AdjustVectorSize=1

### ISSUE THREAD

**Issue by tlomb** [openlink/virtuoso-opensource#438]
Dear virtuoso team,

I am testing virtuoso-opensource v7.2.1 and I am facing an issue with the AdjustVectorSize=1 parameter and a high MaxQueryMem for virtuoso-t:

The following sparql query sometimes returns results in ~1min but sometimes hangs with 100% cpu virtuoso-t for >2 hours without results:

PREFIX up:http://purl.uniprot.org/core/ PREFIX rdfs:http://www.w3.org/2000/01/rdf-schema# SELECT ?protein (COUNT(?xref) AS ?nbxrefs) WHERE { ?protein a up:Protein . ?protein rdfs:seeAlso ?xref . ?xref up:database http://purl.uniprot.org/database/PROSITE } GROUP BY ?protein ORDER BY DESC(?nbxrefs) LIMIT 3;

The dataset is uniprot (2015_07), ~14 billions triples (!)

The problem appears (randomly?) with the following virtuoso-t parameters:
AdjustVectorSize=1
MaxQueryMem=10G

But the query always works fine in ~1min when using:
AdjustVectorSize=0
MaxQueryMem=10G

Version:
- your latest tag from 2015-06-24: virtuoso-opensource tags/v7.2.1, compiled from source
- OS: linux CentOS 6.4 Final
  tested on isql, using "sparql " prefix.

Generally, would you advice to have AdjustVectorSize=0 or AdjustVectorSize=1 for a store with ~14 billions triples, ~800G on disk?

Let me know if you can reproduce this or if you need more details (trace_on() or a sparql translate...)

Thanks for your help,

Best regards

(int. ref. UPS-131)

**Comment by HughWilliams** [comment]
@tlomb: I suppose you have confirmed ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/rdf/ is the dataset you are using in this issue, so will be downloading to check this issue also.

Can you please provide a copy of the complete INI file in use for reference ...

By Default AdjustVectorSize=0  in the INI file we ship and should be set to 1 typically when running large queries, so it is not so much dependant on the dataset size but more the query and structure of the dataset . And as such is not guaranteed to be beneficial in all cases, see details of the param at:

http://docs.openlinksw.com/virtuoso/databaseadmsrv.html

and so has to be tried on a case by case basis generally ...

**Comment by tlomb** [comment]
@HughWilliams: The files in ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/rdf/ (as of 2015-07-10, version 2015_07) is the dataset I am using in these tests.
Here are the corresponding virtuoso.ini files:

virtuoso.ini with AdjustVectorSize=1 (query of comment 1 can hang):
###################
[user@testserver]$ cat /scratch/uuw_sparql/tmp/virtuoso-config-expasy4j-sparql6237756606046863387_MaxQueryMem_10G.ini
;
;  virtuoso.ini
;

;  Database setup
;
[Database]
DatabaseFile                = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso.db
ErrorLogFile                = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso.log
LockFile                    = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso.lck
TransactionFile             = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso.trx
xa_persistent_file          = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso.pxa
ErrorLogLevel               = 7
FileExtend                  = 20000
MaxCheckpointRemap          = 20000
Striping                    = 0
TempStorage                 = TempDatabase

[TempDatabase]
DatabaseFile                = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso-temp.db
TransactionFile             = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso-temp.trx
MaxCheckpointRemap          = 2000
Striping                    = 0

;
;  Server parameters
;
[Parameters]
ServerPort                  = 1112
LiteMode                    = 1
DisableUnixSocket           = 0
DisableTcpSocket            = 0
ServerThreads               = 64
AsyncQueueMaxThreads        = 10
MaxClientConnections        = 64
CheckpointInterval          = 600
O_DIRECT                    = 0
UseAIO                      = 1
CaseMode                    = 2
MaxStaticCursorRows         = 5000
CheckpointAuditTrail        = 0
AllowOSCalls                = 0
SchedulerInterval           = 10
DirsAllowed                 = 
ThreadCleanupInterval       = 0
ThreadThreshold             = 10
ResourcesCleanupInterval    = 0
FreeTextBatchSize           = 100000
SingleCPU                   = 0
VADInstallDir               = /dev/null
PrefixResultNames           = 0
RdfFreeTextRulesSize        = 100
IndexTreeMaps               = 256
MaxMemPoolSize              = 134217728
TransactionAfterImageLimit  = 1000000000
ColumnStore                 = 1
QueryLog                    = /tmp/virtuoso-query.log
NumberOfBuffers             = 14695720
MaxDirtyBuffers             = 11021790
ThreadsPerQuery             = 64
MaxQueryMem                 = 10G
VectorSize                  = 10000
MaxVectorSize               = 1000000
AdjustVectorSize            = 1
CheckpointSyncMode          = 2

[AutoRepair]
BadParentLinks              = 0

[HTTPServer]
ClientIdString = Mozilla/4.0 (compatible; Virtuoso, running-at: sparql.uniprot.org)

[Client]
SQL_PREFETCH_ROWS           = 100
SQL_PREFETCH_BYTES          = 16000
SQL_QUERY_TIMEOUT           = 0
SQL_TXN_TIMEOUT             = 0

[VDB]
ArrayOptimization           = 0
NumArrayParameters          = 10
VDBDisconnectTimeout        = 1000
KeepConnectionOnFixedThread = 0

[SPARQL]
;ExternalQuerySource        = 1
;ExternalXsltSource         = 1
DefaultGraph                = http://beta.sparql.uniprot.org/
ResultSetMaxRows            = 20000000000 ; 20 billion for now.
MaxQueryCostEstimationTime  = 360000  ; in seconds
MaxQueryExecutionTime       = 360000  ; in seconds
DefaultQuery                = select distinct ?Concept where {[] a ?Concept} LIMIT 100
DeferInferenceRulesInit     = 0  ; controls inference rules loading
###################

-------------------------------------------

virtuoso.ini with AdjustVectorSize=0 (query of comment 1 always running ok):
###################
[user@testserver]$ cat /scratch/uuw_sparql/tmp/virtuoso-config-expasy4j-sparql6237756606046863387_MaxQueryMem_10G_AdjustVectorSize_0.ini 
;
;  virtuoso.ini
;

;  Database setup
;
[Database]
DatabaseFile                = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso.db
ErrorLogFile                = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso.log
LockFile                    = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso.lck
TransactionFile             = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso.trx
xa_persistent_file          = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso.pxa
ErrorLogLevel               = 7
FileExtend                  = 20000
MaxCheckpointRemap          = 20000
Striping                    = 0
TempStorage                 = TempDatabase

[TempDatabase]
DatabaseFile                = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso-temp.db
TransactionFile             = /scratch/uuw_sparql/2015_07.1/./data/triples/virtuoso-temp.trx
MaxCheckpointRemap          = 2000
Striping                    = 0

;
;  Server parameters
;
[Parameters]
ServerPort                  = 1112
LiteMode                    = 1
DisableUnixSocket           = 0
DisableTcpSocket            = 0
ServerThreads               = 64
AsyncQueueMaxThreads        = 10
MaxClientConnections        = 64
CheckpointInterval          = 600
O_DIRECT                    = 0
UseAIO                      = 1
CaseMode                    = 2
MaxStaticCursorRows         = 5000
CheckpointAuditTrail        = 0
AllowOSCalls                = 0
SchedulerInterval           = 10
DirsAllowed                 = 
ThreadCleanupInterval       = 0
ThreadThreshold             = 10
ResourcesCleanupInterval    = 0
FreeTextBatchSize           = 100000
SingleCPU                   = 0
VADInstallDir               = /dev/null
PrefixResultNames           = 0
RdfFreeTextRulesSize        = 100
IndexTreeMaps               = 256
MaxMemPoolSize              = 134217728
TransactionAfterImageLimit  = 1000000000
ColumnStore                 = 1
QueryLog                    = /tmp/virtuoso-query.log
NumberOfBuffers             = 14695720
MaxDirtyBuffers             = 11021790
ThreadsPerQuery             = 64
MaxQueryMem                 = 10G
VectorSize                  = 10000
MaxVectorSize               = 1000000
AdjustVectorSize            = 0
CheckpointSyncMode          = 2

[AutoRepair]
BadParentLinks              = 0

[HTTPServer]
ClientIdString = Mozilla/4.0 (compatible; Virtuoso, running-at: sparql.uniprot.org)

[Client]
SQL_PREFETCH_ROWS           = 100
SQL_PREFETCH_BYTES          = 16000
SQL_QUERY_TIMEOUT           = 0
SQL_TXN_TIMEOUT             = 0

[VDB]
ArrayOptimization           = 0
NumArrayParameters          = 10
VDBDisconnectTimeout        = 1000
KeepConnectionOnFixedThread = 0

[SPARQL]
;ExternalQuerySource        = 1
;ExternalXsltSource         = 1
DefaultGraph                = http://beta.sparql.uniprot.org/
ResultSetMaxRows            = 20000000000 ; 20 billion for now.
MaxQueryCostEstimationTime  = 360000  ; in seconds
MaxQueryExecutionTime       = 360000  ; in seconds
DefaultQuery                = select distinct ?Concept where {[] a ?Concept} LIMIT 100
DeferInferenceRulesInit     = 0  ; controls inference rules loading
###################

-------------------------------------------

You can see that all other parameters are unchanged:
###################
[user@testserver]$ diff /scratch/uuw_sparql/tmp/virtuoso-config-expasy4j-sparql6237756606046863387_MaxQueryMem_10G.ini /scratch/uuw_sparql/tmp/virtuoso-config-expasy4j-sparql6237756606046863387_MaxQueryMem_10G_AdjustVectorSize_0.ini 
67c67
< AdjustVectorSize            = 1
---
> AdjustVectorSize            = 0
###################

Best regards

**Comment by tlomb** [comment]
@HughWilliams: Any progresses on this one? In the meantime, I am using AdjustVectorSize = 0, but as this option is supposed to speed-up some queries, this is a pity.

**Comment by openlink** [comment]
Please upgrade your installation to version 7.2.2 which was released earlier today. 

It contains some  fixes to the cost based optimizer that i think will have a positive effect the speed of your queries.

I recommend setting AdjustVectorSize back to 1 and try your query again with the new binary and let me know if this resolves the problem.
