### ISSUE TITLE
Error installing ODS

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#444]
I tried to install the ODS framework from:
http://s3.amazonaws.com/opldownload/uda/vad-vos-packages/7.2/ods_framework_dav.vad

onto Virtuoso 7.2.1 running under CENTOS 7, but it crashed with the following error:

00000 Errors detected
00000 Installation of "ODS Framework" was unsuccessful.
      The installation of this VAD package has failed.
      Please delete the transaction file /opt/virtuoso/var/lib/virtuoso/db//opt/virtuoso/var/lib/virtuoso/db/virtuoso.trx
      and then restart your database server.
      Note: Your database will be in its pre VAD installation state after you restart.
00000 FATAL

**Comment by HughWilliams** [comment]
@ebremer: 

This is a know issue we are working on a fix for ...

**Comment by HughWilliams** [comment]
@ebremer:

This problem has been resolved and a new set of VADs uploaded to:

```
http://s3.amazonaws.com/opldownload/uda/vad-vos-packages/7.2/
```

please download and try again ...

**Comment by ebremer** [comment]
I got an error trying to access: http://s3.amazonaws.com/opldownload/uda/vad-vos-packages/7.2/

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>FC4D4AAEA171D329</RequestId><HostId>jom6DgAHhhdJhfHxbSjWfZQg1c5xwyYnc+a40io32YsxkZgaXQGsbySSyqOyC7CDAlUY9fA2z6U=</HostId></Error>

**Comment by HughWilliams** [comment]
Standard S3 bucket folders are not directly browsable on the files within if they have suitable perms , thus you need to access the file you want directly:

   http://s3.amazonaws.com/opldownload/uda/vad-vos-packages/7.2/ods_framework_dav.vad

If that is the VAD u want ...
We did add a script to enable browsing such that you can access content from:

   http://opldownload.s3.amazonaws.com/index.html?prefix=uda/vad-vos-packages/7.2/

**Comment by ebremer** [comment]
I was able to grab all of them and the basic framework loaded without any crashes.  Thanks Hugh!
