### ISSUE TITLE
Virt_sesame2 driver ignores Literal.language when Literal.datatype is also present

### ISSUE THREAD

**Issue by ghost** [openlink/virtuoso-opensource#448]
This issue is a copy from https://github.com/UnifiedViews/Plugins/issues/283

When RDF Triple:

```
s p "some text"@en^^Xsd.LangString
```

is loaded into Virtuoso using virt_sesame2.jar provider (1.25 version from develop/7 branch), the language is ignored by driver and triple is loaded as

```
s p "some text"^^Xsd.LangString
```

Since Sesame 2.8.x has all triples datatyped, this occurs mainly when the triple is obtained from other RDF repository using Sesame 2.8.x or by parsing RDF files using Sesame Rio parsers in 2.8.x version.

The root cause is this line:
https://github.com/openlink/virtuoso-opensource/blob/develop/7/binsrc/sesame2/virtuoso_driver/VirtuosoRepositoryConnection.java#L2383
where, the else branch (https://github.com/openlink/virtuoso-opensource/blob/develop/7/binsrc/sesame2/virtuoso_driver/VirtuosoRepositoryConnection.java#L2388) is never executed, even if the Value has language tag.

Possible solution (or workaround as this does not adapt the driver to fully support Sesame 2.8.x) is to exchange those if-else conditions and bodies.

**Comment by ghost** [comment]
The solution is tested and works.

**Comment by pkleef** [comment]
We pushed a fix for this to both the Jena2 and Sesame2 providers.

Please check the develop/7 branch
