### ISSUE TITLE
Setting up LDP not working

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#466]
Following the directions here for enable LDP don't seem to work:
http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtLDP

When putting in the property "LDP", it gets rejected (no error) and doesn't appear in the drop down.  Properties in the drop down can be added, but not LDP.

I am using virtuoso 7.2.1.3214-pthreads as of July 23 2015

**Comment by HughWilliams** [comment]
@ebremer:  building from the develop/7 head I am able to add the LDP property and is saved to the dav folder it is set for , even if not added to the drop down list box i.e. it can be added manually

**Comment by ebremer** [comment]
Okay, I'll try the develop/7 head

**Comment by ebremer** [comment]
Still the same thing for me.  It doesn't give an error when I hit update, but if you go back into action, the LDP property is not there.  I used the develop/7 head branch as of today

**Comment by ebremer** [comment]
I just loaded the latest virtuoso-7/devel.  I noticed the new "LDP enable/disable" option in the WebDAV.  Is it necessary to add the "LDP" property anymore?

**Comment by akuckartz** [comment]
@ebremer How was this resolved?
