### ISSUE TITLE
Using trigonometry functions in SPARQL

### ISSUE THREAD

**Issue by iaptsiauri** [openlink/virtuoso-opensource#471]
I am trying to use the trigonometry functions, something similar to this 
`select sin(90) where {?s ?p ?o}`
but get the following exception
`SPARQL compiler, line 1: syntax error at 'sin' before '('`
Do I need to use some specific prefix?

**Comment by rumito** [comment]
Hi Ilia,

Please try using bif:sin, i.e.:

SELECT bif:sin(90) 
WHERE {?s ?p ?o} 
LIMIT 1

View query results: -- http://lod.openlinksw.com/c/9DN36RWH

Best Regards,
Rumi Kocis

**Comment by iaptsiauri** [comment]
Thanks :+1: that worked, perfect.
Just one more question though, where can I find what prefixes need to be used to use other functions?

**Comment by rumito** [comment]
Here are the variants re. calling functions in SPARQL query:

1) Using "bif" prefix: 
To call Virtuoso built-in functions ( http://docs.openlinksw.com/virtuoso/functions.html ) ,  one should use the "bif:" prefix.

2) If you want to call a user-defined function, (as ex. documented at http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtTipsAndTricksGuideCustomSPARQLExtensionFunction), one should use the "sql:" prefix.
