### ISSUE TITLE
Unable to run Virtuoso 7 stable version

### ISSUE THREAD

**Issue by ma-garcia** [openlink/virtuoso-opensource#48]
Hi,

I have downloaded the latest Virtuoso 7 Stable version, 1e7b4b77afbc4ab94a1a361404dbe076954ae2bf, and install it in an Ubuntu Server 12 64 bits edition.

Before the installation, I have downloaded all the dependencies needed and followed all the steps for the installation. When I run "make check" for ensuring that the installation process finished properly, test_server.sh script fails. In the console output, it's said that I should check some *.output files. In testall.output, it's indicated that some tests were aborted: nwxml.sh, trecov.sh, trecov_schema.sh, tnwords.sql and tsqlo.sql and one failed, thttp.sh:

nwxml.output:**_ABORTED: nwxml.sh: nwxml.sql functions 
thttp.output:**_FAILED: DBSCHEMA_COLUMNS : LAST[4]=Out_of_Bounds(0)
trecov.output:**_ABORTED: trecov.sh: Connect failed after log roll forward
trecov_schema.output:**_ABORTED: trecov_schema.sh: Connect failed after -d roll forward
tsql.output:**_ABORTED: nvarchar Wordtest -- tnwords.sql
tsqlo.output:**_ABORTED: tsqlo.sql: SQL optimizer functions

If I try to run the Virtuoso instance, an error is displayed on the screen "The VDBMS server process terminated prematurely after opening the database" but not in virtuoso.log file:

```
    Thu May 09 2013
```

13:20:13 { Loading plugin 1: Type `plain', file`wikiv' in `/opt/virtuoso-7/default/lib/virtuoso/hosting'
13:20:13   WikiV version 0.6 from OpenLink Software
13:20:13   Support functions for WikiV collaboration tool
13:20:13   SUCCESS plugin 1: loaded from /opt/virtuoso-7/default/lib/virtuoso/hosting/wikiv.so }
13:20:13 { Loading plugin 2: Type`plain', file `mediawiki' in`/opt/virtuoso-7/default/lib/virtuoso/hosting'
13:20:13   MediaWiki version 0.1 from OpenLink Software
13:20:13   Support functions for MediaWiki collaboration tool
13:20:13   SUCCESS plugin 2: loaded from /opt/virtuoso-7/default/lib/virtuoso/hosting/mediawiki.so }
13:20:13 { Loading plugin 3: Type `plain', file`creolewiki' in `/opt/virtuoso-7/default/lib/virtuoso/hosting'
13:20:13   CreoleWiki version 0.1 from OpenLink Software
13:20:13   Support functions for CreoleWiki collaboration tool
13:20:13   SUCCESS plugin 3: loaded from /opt/virtuoso-7/default/lib/virtuoso/hosting/creolewiki.so }
13:20:13 OpenLink Virtuoso Universal Server
13:20:13 Version 07.00.3201-pthreads for Linux as of May  9 2013
13:20:13 uses parts of OpenSSL, PCRE, Html Tidy
13:20:13 Database version 3126
13:20:13 SQL Optimizer enabled (max 1000 layouts)
13:20:14 Compiler unit is timed at 0.000801 msec
13:20:15 Roll forward started
13:20:15 Roll forward complete
13:20:16 PL LOG: Installing Virtuoso Conductor version 1.00.7920 (DAV)
13:20:16 Checkpoint started
13:20:17 Checkpoint finished, log reused

Any clue about the possible solution for this error or the error source?

Thanks in advance.

**Comment by indeyets** [comment]
"stable/7" is ancient. please wait until it is updated. you can try "develop/7", but it still has issues

**Comment by openlink** [comment]
The develop/7 branch is where all current work is committed on. 

As soon as this code is deemed stable it will be merged into stable/7

As vos 7 has a few last details to be sorted, we have not yet made a final release for it
