### ISSUE TITLE
MaxSortedTopRows has no effect

### ISSUE THREAD

**Issue by jindrichmynarz** [openlink/virtuoso-opensource#481]
Using Virtuoso compiled from the latest develop/7 commit (cfb50e30826d7952ce37f414b152353139a8368a), setting `MaxSortedTopRows` in virtuoso.ini doesn't have any effect. When I set `MaxSortedTopRows` to `40000`, restart Virtuoso, and execute the following query:

```
SELECT *
WHERE {
  ?s ?p ?o .
}
ORDER BY ?s
LIMIT 1000
OFFSET 10000
```

I see this error: `Virtuoso 22023 Error SR353: Sorted TOP clause specifies more then 11000 rows to sort. Only 10000 are allowed. Either decrease the offset and/or row count or use a scrollable cursor`

Is `MaxSortedTopRows` still supported?

**Comment by HughWilliams** [comment]
@jindrichmynarz: The INI file param is still supported with a default of 10K as indicated in:

   https://github.com/openlink/virtuoso-opensource/blob/develop/7/binsrc/virtuoso/viconfig.c

```
 if (cfg_getlong (pconfig, section, "MaxSortedTopRows", &c_setp_top_row_limit) == -1)
    c_setp_top_row_limit = 10000;
```

You sure it was set in the the correct i.e. "[Parameters]" section of the INI file and the Virtuoso server restarted ?

**Comment by jindrichmynarz** [comment]
I see, `MaxSortedTopRows` needs to be in the `[Parameters]` section and then it works. For some reason I thought it should go into the `[SPARQL]` section of the INI file. Thanks @HughWilliams for clarification!
