### ISSUE TITLE
Virtuoso 7 typed numbers and JSON-LD

### ISSUE THREAD

**Issue by coyotefive** [openlink/virtuoso-opensource#482]
when values are inserted as floats but contain no decimal section (1 instead of 1.0), it seems that the responses to construct queries do not indicate any type for the value (no @type section at all in json-ld). this is the case even when the type float is given for the value. if the value is inserted as 1.0 instead of 1, the value is returned with the expected type. 

Though this works as workaround, is there a way to permanently correct this issue?

**Comment by HughWilliams** [comment]
@coyotefive:  Are you able to provide a test case for recreating/demonstrating this reported issue ?

**Comment by coyotefive** [comment]
i seem to have been able to track it down to the following:
if i insert some information using "insert" (such as):
insert { 
&lt;DEMOURI#APPLICATION_Test_for_BUG&gt; a &lt;DEMOURI#External&gt;. 
&lt;DEMOURI#APPLICATION_Test_for_BUG&gt; &lt;ValuedEntity#val&gt; "2"^^&lt;http://www.w3.org/2001/XMLSchema#float&gt; .
&lt;DEMOURI#APPLICATION_Test_for_BUG&gt; &lt;ValuedEntity#val&gt; "1.0"^^&lt;http://www.w3.org/2001/XMLSchema#float&gt; .
&lt;DEMOURI#APPLICATION_Test_for_BUG&gt; &lt;DEMOURI#description&gt; "this is a description" 
}

then the values seem to come out untyped for the "2" and the type of 1 comes out as ""http://www.w3.org/2001/XMLSchema#decimal"

if i use "insert data", which cannot have a where clause it seems, the results are fine. 

Below is a sample of the json-ld being generated when i have tried both methods to insert "valuedEntity#val" using both methods

the construct query:
construct {
                ?demo a ?demo_type.
                ?demo &lt;ValuedEntity#val&gt; ?val .
                ?demo &lt;DEMOURI#description&gt; ?descr .
}
where {
                ?demo a ?demo_type.
                ?demo &lt;ValuedEntity#val&gt; ?val .
                ?demo &lt;DEMOURI#description&gt; ?descr .
}

Generates the output (which mixes and matches instances where insert and insert data were used):

{ "@graph": [
    { "@id": "DEMOURI#APPLICATION_Test_for_BUG_3",
      "@type" : [ { "@id": "DEMOURI#External"} ] ,
      "DEMOURI#description" : [ { "@value" : "this is a description" } ] ,
      "ValuedEntity#val" : [ { "@value" : 1 , "@type" : "http://www.w3.org/2001/XMLSchema#decimal" } ,
        2 ] } ,
    { "@id": "DEMOURI#APPLICATION_Test_for_BUG_4",
      "@type" : [ { "@id": "DEMOURI#External"} ] ,
      "DEMOURI#description" : [ { "@value" : "this is a description" } ] ,
      "ValuedEntity#val" : [ 2 ,
        { "@value" : 1 , "@type" : "http://www.w3.org/2001/XMLSchema#decimal" } ] } ,
    { "@id": "DEMOURI#APPLICATION_Test_for_BUG",
      "@type" : [ { "@id": "DEMOURI#External"} ] ,
      "DEMOURI#description" : [ { "@value" : "this is a description" } ] ,
      "ValuedEntity#val" : [ { "@value" : 3 , "@type" : "http://www.w3.org/2001/XMLSchema#float" } ,
        { "@value" : 2 , "@type" : "http://www.w3.org/2001/XMLSchema#float" } ,
        { "@value" : 1 , "@type" : "http://www.w3.org/2001/XMLSchema#float" } ,
        { "@value" : 4 , "@type" : "http://www.w3.org/2001/XMLSchema#float" } ] } ,
    { "@id": "DEMOURI#APPLICATION_Test_for_BUG_2",
      "@type" : [ { "@id": "DEMOURI#External"} ] ,
      "DEMOURI#description" : [ { "@value" : "this is a description" } ] ,
      "ValuedEntity#val" : [ { "@value" : 4 , "@type" : "http://www.w3.org/2001/XMLSchema#float" } ,
        { "@value" : 3 , "@type" : "http://www.w3.org/2001/XMLSchema#float" } ,
        { "@value" : 11 , "@type" : "http://www.w3.org/2001/XMLSchema#float" } ] }
] }

**Comment by coyotefive** [comment]
the above comment was mangled by the system's attempt to convert the URIs into html markup. this has been corrected.

**Comment by openlink** [comment]
Please check the latest version from develop/7 branch as we recently fixed some issues with type mapping in JSON format.
