### ISSUE TITLE
No rule to make target `INSTALL', needed by `all-am'

### ISSUE THREAD

**Issue by ccoocode** [openlink/virtuoso-opensource#488]
when i run make, the following error happen:
   make[1]: Entering directory `/home/tool/sempre-master/virtuoso-opensource'
  make[1]: *** No rule to make target`INSTALL', needed by `all-am'.  Stop.
  make[1]: Leaving directory`/home//tool/sempre-master/virtuoso-opensource'
  make: **\* [all-recursive] Error 1

**Comment by XBOOS** [comment]
I have the same problem

**Comment by openlink** [comment]
Please try running

```
    $ sh autogen.sh
```

as this is supposed to install such files as part of generating the configure and Makefile.in scripts using the GNU autoconf and automake tools.

**Comment by XBOOS** [comment]
@openlink  Hi, it still doesn't work. How could we solve the problem?

**Comment by openlink** [comment]
You can try to use the following command:

```
$ touch INSTALL
```

but if the autogen.sh script does not automatically add this file, i think you may not have all the tools needed to build this package yourself which are detailed in the README.GIT file.

Did this script return any errors?

Note you could try to download the [Source Tar](https://github.com/openlink/virtuoso-opensource/releases/download/v7.2.2.1/virtuoso-opensource-7.2.2.tar.gz) which has already pre-generated a number of files to lessen the dependency on the number of tools you need to build this code yourself.

**Comment by zhaopku** [comment]
I also have this problem. Did you solve this? @ccoocode @XBOOS
