### ISSUE TITLE
Tests should be run on a non-standard (unused port)

### ISSUE THREAD

**Issue by jpmccu** [openlink/virtuoso-opensource#49]
Building a new version of virtuoso on a machine that has an old one running results in test failures because the tests spin up a VOS instance on the default ports and fails.

**Comment by openlink** [comment]
You can use:

./configure  --with-port=XXXX .....

to make sure the version you build uses different ports than your current running system. 

The default port is 1111 and when you have a virtuoso running on that port already, it will be shutdown at the start of the test suite.

**Comment by jpmccu** [comment]
This is only true if the user building the software has permissions to shut
down the server. Unit tests should never intrude on existing running
software.

On Thu, May 16, 2013 at 6:56 AM, OpenLink Software <notifications@github.com

> wrote:
> 
> You can use:
> 
> ./configure --with-port=XXXX .....
> 
> to make sure the version you build uses different ports than your current
> running system.
> 
> The default port is 1111 and when you have a virtuoso running on that port
> already, it will be shutdown at the start of the test suite.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/openlink/virtuoso-opensource/issues/49#issuecomment-17994312
> .

## 

Jim McCusker
Programmer Analyst
Krauthammer Lab, Pathology Informatics
Yale School of Medicine
james.mccusker@yale.edu | (203) 785-4436
http://krauthammerlab.med.yale.edu

PhD Student
Tetherless World Constellation
Rensselaer Polytechnic Institute
mccusj@cs.rpi.edu
http://tw.rpi.edu
