### ISSUE TITLE
Virtuoso build stuck

### ISSUE THREAD

**Issue by migalkin** [openlink/virtuoso-opensource#492]
Hello, I have an issue with Virtuoso 7.2 taken from git.
Compiling the stable/7 branch I execute
`./configure`
then
`make`

In short time I get the next console output:

```
CREATING VAD PACKAGE FOR VIRTUOSO CONDUCTOR (mkvad.sh)
TUE Oct 20

omitting directories...
VAD Sticker vad_fs.xml creation...
VAD Sticker vad_dav.xml creation...
Starting Virtuoso server ...
Virtuoso server started 

```

And then the process seems to continue forever.
I waited for 5 hours, 6 hours and nothing changes. 

Could you please help ?

The server is:
Intel Xeon 2 Ghz, 2 CPUs
4 GB RAM
500 GB SSD

**Comment by TwinbrotherPro** [comment]
As a  fast fix, try the develop/7 branch, worked for me on a Debian 64 bit system.

**Comment by openlink** [comment]
On 20 October 2015 at 15:21, Michael Galkin notifications@github.com
wrote:

> CREATING VAD PACKAGE FOR VIRTUOSO CONDUCTOR (mkvad.sh)
> TUE Oct 20
> 
> omitting directories...
> VAD Sticker vad_fs.xml creation...
> VAD Sticker vad_dav.xml creation...
> Starting Virtuoso server ...
> Virtuoso server started
> 
> And then the process seems to continue forever.
> I waited for 5 hours, 6 hours and nothing changes.
> 
> Could you please help ?
> 
> Hi,

I've seen that when you've had a previous build attempt fail or abort but
there's a dangling virtuoso-t process running (or anything else listening
on port 1111).

^C it
pkill virtuoso
make
(again).

If that doesn't work,
cd binsrc/yacutia
ls -ltr *log
have a look at the bottom of the most recent couple of log files - it
should give you a more concrete error message for us to work from.

HTH,

## ~Tim

Tim Haynes
Product Development Consultant
OpenLink Software
http://www.openlinksw.com/
http://twitter.com/openlink

**Comment by migalkin** [comment]
> ^C it
> pkill virtuoso
> make
> (again).
> 
> If that doesn't work,
> cd binsrc/yacutia
> ls -ltr *log

Tried both compiling from develop/7 and pkill with subsequent making - the result is still the same. Stuck at Virtuoso server started. 
Might it be the case that port 8890 is closed? Our organization has quite strict firewall rules, so does it make sense to open the port before the installation is completed? 
Are there any other ports involved in the installation?

**Comment by openlink** [comment]
On 20 October 2015 at 20:31, Michael Galkin notifications@github.com
wrote:

> Tried both compiling from develop/7 and pkill with subsequent making - the
> result is still the same. Stuck at Virtuoso server started.
> Might it be the case that port 8890 is closed? Our organization has quite
> strict firewall rules, so does it make sense to open the port before the
> installation is completed?
> Are there any other ports involved in the installation?
> 
> Depends what you mean by `closed'. If the machine can't talk to
> localhost:8890 and localhost:1111 then it has issues.

Any worrd in the logfiles? There should be a virtuoso.log from the attempt
to start the server which might say what's wrong.

## ~Tim

Tim Haynes
Product Development Consultant
OpenLink Software
http://www.openlinksw.com/
http://twitter.com/openlink

**Comment by migalkin** [comment]
> Any worrd in the logfiles? There should be a virtuoso.log from the attempt
> to start the server which might say what's wrong.

The log file is empty. After ^C its size is 0 B.

I will try to recompile with open ports.

**Comment by migalkin** [comment]
Hello, 

we opened all the ports for incoming and outgoing connections but the error is still present. 
The process after 
`Virtuoso server started`
takes hours and never ends.

**Comment by openlink** [comment]
Check with ps -ef to make sure there is no virtuoso-t running. If there is, you may need to kill -9 it.

Next try the following commands:

  $ cd binsrc/yacutia
  $ ../virtuoso/virtuoso-t -f

This will start virtuoso in foreground mode so we can check if there are any warnings or errors it reports. If it ends with a line like this:

  17:23:13 Server online at XXXX (pid YYYY)

then your server is running properly, else cut/paste last 10 lines of output and put it in this issue.

If it has started properly, press CTRL-C to shutdown this server and perform the following commands:

  $ make clean
  $ make

**Comment by migalkin** [comment]
Thank you for the prompt reply!

> $ cd binsrc/yacutia
> $ ../virtuoso/virtuoso-t -f

Results in 
` Server online at 1111

However, the server is not accessible in the web-browser at ip:1111 or ip:8890. 
Assuming it has started properly:

> $ make clean
> $ make

But we still have the message `Virtuoso server started` after an hour.

**Comment by openlink** [comment]
Next test. 

```
$ cd binsrc/yacutia
```

Edit the file mkvad.sh and add the following line:

```
set -x
```

just below the first line so it should look like this:

```
#!/bin/sh
set -x
#
#  mkvad.sh
#
```

Then do

```
$ make clean
$ make
```

There will be lots of output to the screen, but now we should be able to see why it is not detecting virtuoso has started. It could be your system is missing a binary that we use in this script.

If you see it looping, just press CTRL-C and cut/paste the last block of lines to this git issue.

**Comment by migalkin** [comment]
Hello, 

after adding in the mkvad.sh
`set -x`
and subsequent
`make clean`
`make`

The last rows in the output are:

```
echo '     <registry>'
echo '     </registry>'
echo '</stickers>'
cat mkvad.ini
sed -e s/1112/1111/g
sed -e s/1113/1121/g
STOP_SERVER
isql localhost:1111 dba dba '"EXEC=raw_exit();"' VERBOSE=OFF PROMPT=OFF ERRORS=STDOUT
```

The process stops after `isql`

**Comment by migalkin** [comment]
Hello, 

the problem has been solved by switching off the sophos antivirus, which prevented the further installation. As soon as I stopped the daemons Virtuoso has been installed fine. 
Thanks all for the help!
The issue could be closed.
