### ISSUE TITLE
Faceted browser broken: HY105

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#497]
When I access http://ruian.linked.opendata.cz:8890/describe/?url=http:// where I have 5943bbbb9c88693e4df79f01a55b022beee3ef32 installed (with any url in the param) I get:

```
Error HY105

SR181: Cannot pass literal as reference parameter "val_serviceId"
```

**Comment by HughWilliams** [comment]
@jakubklimek: I have been able to recreate locally and reported to development to look into ...

**Comment by openlink** [comment]
A fix for this issue has been pushed into develop/7
