### ISSUE TITLE
Variable is used in the result set outside aggregate and not mentioned in GROUP BY clause

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#498]
I am trying to rebuild a string in original order using a group_concat and order by combination.
The following query works in Jena in memory but is rejected by virtuoso 7.2.1

```
*** Error 37000: [Virtuoso Driver][Virtuoso Server]SQ074: Line 9 (line 9 of "(console)"): SP031: SPARQL compiler: Variable ?order is used in the result set outside aggregate and not mentioned in GROUP BY clause
in lines 1-9 of Top-Level:
#line 1 "(console)"
 sparql PREFIX vg:<http://example.org/o/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?path (GROUP_CONCAT(?y; separator=' ') AS ?seq)
WHERE {?step vg:path ?path;
             vg:node ?node ;
             vg:step ?order.
       ?node rdf:value ?y .
} GROUP BY ?path
 ORDER BY ?order
```

**Comment by HughWilliams** [comment]
@JervenBolleman: I have been able to recreate against lod.openlinksw.com and reported to development to look into:

http://lod.openlinksw.com/sparql?default-graph-uri=&qtxt=PREFIX+vg%3A%3Chttp%3A%2F%2Fexample.org%2Fo%2F%3E%0D%0APREFIX+rdf%3A%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0ASELECT+%3Fpath+%28GROUP_CONCAT%28%3Fy%3B+separator%3D%27+%27%29+AS+%3Fseq%29%0D%0AWHERE+%7B%3Fstep+vg%3Apath+%3Fpath%3B%0D%0A+++++++++++++vg%3Anode+%3Fnode+%3B%0D%0A+++++++++++++vg%3Astep+%3Forder.%0D%0A+++++++%3Fnode+rdf%3Avalue+%3Fy+.%0D%0A%7D+GROUP+BY+%3Fpath%0D%0A+ORDER+BY+%3Forder&should-sponge=&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on

**Comment by JervenBolleman** [comment]
FYI: this impacts the demo for Genomic Variation Graphs as described at https://github.com/ekg/vg/wiki/RDF:-for-VG

**Comment by IvanMikhailov** [comment]
SPARQL compiler wonders: what if different ?step-s share same value of ?path but differ in values of ?order  ? Or, what if single ?step has many vg:step property values? Given single value of ?path, which value of vg:step should be elected to represent the group in the sorting?

So the optimizer reports an error. You should chose some specific behavior in case of multiple values and write ORDER BY ASC(MAX(?order)) or ORDER BY ASC(MIN(?order)) or ORDER BY ASC(SAMPLE(?order)) or maybe ORDER BY ASC(SUM(?order)) --- any aggregate will work.

**Comment by IvanMikhailov** [comment]
A sample URI, BTW:
http://lod.openlinksw.com/sparql?default-graph-uri=&qtxt=PREFIX+vg%3A%3Chttp%3A%2F%2Fexample.org%2Fo%2F%3E%0D%0APREFIX+rdf%3A%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0ASELECT+%3Fpath+%28GROUP_CONCAT%28%3Fy%3B+separator%3D%27+%27%29+AS+%3Fseq%29%0D%0AWHERE+{%3Fstep+vg%3Apath+%3Fpath%3B%0D%0A+++++++++++++vg%3Anode+%3Fnode+%3B%0D%0A+++++++++++++vg%3Astep+%3Forder.%0D%0A+++++++%3Fnode+rdf%3Avalue+%3Fy+.%0D%0A}+GROUP+BY+%3Fpath%0D%0A+ORDER+BY+ASC%28SAMPLE%28%3Forder%29%29&should-sponge=&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on

**Comment by JervenBolleman** [comment]
This is still a bug in the way the sparql compiler works. ?step being unbound in the result set.

``` sparql
PREFIX vg:<http://example.org/o/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?path (GROUP_CONCAT(?y; separator=' ') AS ?seq)
WHERE {[] vg:path ?path;
             vg:node ?node ;
             vg:step ?order.
       ?node rdf:value ?y .
} GROUP BY ?path
```

is accepted by virtuoso 7.2.2

**Comment by HughWilliams** [comment]
@JervenBolleman: ?step is not in the result set of the query you provided which does run and not give the error reported, but then it is not quite the same as your original query ?

http://lod.openlinksw.com/sparql?default-graph-uri=&qtxt=PREFIX+vg%3A%3Chttp%3A%2F%2Fexample.org%2Fo%2F%3E%0D%0APREFIX+rdf%3A%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0ASELECT+%3Fpath+%28GROUP_CONCAT%28%3Fy%3B+separator%3D%27+%27%29+AS+%3Fseq%29%0D%0AWHERE+%7B%5B%5D+vg%3Apath+%3Fpath%3B%0D%0A+++++++++++++vg%3Anode+%3Fnode+%3B%0D%0A+++++++++++++vg%3Astep+%3Forder.%0D%0A+++++++%3Fnode+rdf%3Avalue+%3Fy+.%0D%0A%7D+GROUP+BY+%3Fpath&should-sponge=&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on

**Comment by JervenBolleman** [comment]
@HughWilliams The issue is the ?step value in the original query is not in the result set and can be replaced with a []. Which will give a semantically equivalent query. However, the second form is accepted by the engine, and I believe the first one should too.

**Comment by mirkospasic** [comment]
@JervenBolleman 
Yes, you are right about ?step value. But here, the problem does not come from it, but from the ordering, from 'order by' clause. If you don't have ordering, both queries will work (the first one with ?step and the other one with [ ] ). But, if you have 'order by' clause, the error message will appear. Ivan explained that in detail.
Imagine this: Among other things, you have a ?step, with single ?path, and single ?node (that has a single ?y), but for it, you have 2 different ?order-s.
In the query, you have grouping by ?path, so the data mentioned in the previous sentence will fall into one single group. At the end of the query execution, you have to sort groups by ?order-s, but here, you will have problem. The mentioned group has 2 different ?order-s, so you cannot know which one you should use in sorting.
So, the solution can be:
1. Not to use 'order by' at all
2. If you want to use 'order by', you have to put an aggregate function there, as Ivan suggested.
