### ISSUE TITLE
Versioning of VirtuosoClient.Net

### ISSUE THREAD

**Issue by meberl** [openlink/virtuoso-opensource#501]
Hi,

I am working with the C# Ado.net provider OpenLink.Data.Virtuoso.dll and I am a bit confused about the version numbering. It seems like it has been 6.2.3128.1 for quite some time and has never been incremented.
This makes it real hard for me to track which version I am working with, not to mention the deployment issues.

Is it possible to keep the AssemblyVersion of OpenLink.Data.Virtuoso.dll in sync with the version number of the server?

Kind regards,
Moritz

**Comment by HughWilliams** [comment]
@meberl: We shall check and update the version number ...

**Comment by openlink** [comment]
We have updated the version number for this provider in the develop/7 branch and will increase it on changes.
