### ISSUE TITLE
Support of Sesame 4.x?

### ISSUE THREAD

**Issue by fgiasson** [openlink/virtuoso-opensource#504]
Hi,

I would like to know if the `Virtuoso Sesame Provider` will be updated for `Sesame 4.x`? If so, is there some kind of ETA as of when this could become available?

Thanks!

**Comment by HughWilliams** [comment]
@fgiasson: It is already on the Todo list, i shall check with development when it is scheduled to be available ...

**Comment by fgiasson** [comment]
Hi @HughWilliams! Great thanks for confirming, I will wait to know when this could happen.

**Comment by fgiasson** [comment]
Hi @HughWilliams, any news on that?

**Comment by kidehen** [comment]
On 12/7/15 6:36 PM, Frederick Giasson wrote:

> Hi @HughWilliams https://github.com/HughWilliams, any news on that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openlink/virtuoso-opensource/issues/504#issuecomment-162705773.

It is being scheduled but it simply isn't a high priority task bearing
in mind other todos.

## 

Regards,

Kingsley Idehen  
Founder & CEO 
OpenLink Software  
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by fgiasson** [comment]
Hi @kidehen, sure understood, but I was just wondering if there were an ETA to that task. Otherwise, is that module open source too? If so, maybe I could take a look at it.

Thanks!

Fred

**Comment by kidehen** [comment]
On 12/8/15 8:38 AM, Frederick Giasson wrote:

> Hi @kidehen https://github.com/kidehen, sure understood, but I was
> just wondering if there were an ETA to that task. Otherwise, is that
> module open source too? If so, maybe I could take a look at it.
> 
> Thanks!
> 
> Fred
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openlink/virtuoso-opensource/issues/504#issuecomment-162881428.

About two - three weeks time, from today.

## 

Regards,

Kingsley Idehen  
Founder & CEO 
OpenLink Software  
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by fgiasson** [comment]
Hi @kidehen, that would be great, thanks!

**Comment by fgiasson** [comment]
@smalinin, @kidehen, I wanted to know if the work started on this upgrade to Sesame 4?

Another collateral question: the `sesame3` folder in the VOS `binsrc` folder, is this VirtuosoProvider code for the Sesame4 codebase while it was in development? (before they choose to step over to version 4?)

**Comment by HughWilliams** [comment]
@fgiasson: The Sesame 4 Provider updated it not complete yet ...

The sesame3 folder is from a number of years ago when a Sesame 3 pre-release of some form was available but then abandoned, so it is redundant now ...

**Comment by fgiasson** [comment]
@HughWilliams Thanks for the `sesame3` information. This is what I was assuming.

About the work on the `sesame4` provider, I just want to know if the work started? If not, then maybe I would have to give it a try considering that it is currently blocking some of my activities. If so, then maybe coordinating with @smalinin could be helpful to move this task forward.

**Comment by kidehen** [comment]
On 12/28/15 9:22 AM, Frederick Giasson wrote:

> @HughWilliams https://github.com/HughWilliams Thanks for the
> |sesame3| information. This is what I was assuming.
> 
> About the work on the |sesame4| provider, I just want to know if the
> work started? If not, then maybe I would have to give it a try
> considering that it is currently blocking some of my activities. If
> so, then maybe coordinating with @smalinin
> https://github.com/smalinin could be helpful to move this task forward.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openlink/virtuoso-opensource/issues/504#issuecomment-167580030.

This work will be available in the next 48 or so hours.

## 

Regards,

Kingsley Idehen  
Founder & CEO 
OpenLink Software  
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by fgiasson** [comment]
Hi @kidehen,

Wonderful thanks!

**Comment by HughWilliams** [comment]
@fgiasson: You should have seen the commit of the Sesame4 provider to VOS, do let us know if this works for you:

Begin forwarded message:

From: "OpenLink Virtuoso (Open-Source Edition) Git repository" noreply@virtuoso-opensource.virtuoso.p.re.sf.net
Subject: [virtuoso:virtuoso-opensource] 3 new commits to Git
Date: 30 December 2015 at 13:08:14 GMT
To: "OpenLink Virtuoso (Open-Source Edition) Git repository" noreply@virtuoso-opensource.virtuoso.p.re.sf.net
Reply-To: "OpenLink Virtuoso (Open-Source Edition) Git repository" noreply@virtuoso-opensource.virtuoso.p.re.sf.net

Branch: develop/7

Merge branch 'feature/2015_12_29_Sesame4' into develop/7

By VOS Maintainer on 12/30/2015 13:07
[View Changes](http://sourceforge.net/p/virtuoso/virtuoso-opensource/ci/1b5a2d9a3901f4a2c788adecc4ff3a3e84a0e161/)

Added support for JDK 1.8 to use with sesame 4 provider

By VOS Maintainer on 12/30/2015 13:06
[View Changes](http://sourceforge.net/p/virtuoso/virtuoso-opensource/ci/736a42e05301747e3ebd1ff776aed81c5c42a5cb/)

new Sesame4 provider

By Sergey Malinin on 12/29/2015 09:25
[View Changes](http://sourceforge.net/p/virtuoso/virtuoso-opensource/ci/8381b2f0aa9fcff3651ae8e73b5cae393c87f4a5/)

**Comment by fgiasson** [comment]
Hi @HughWilliams,

Great thanks! Will test this out today and will report my success here once I am done, thanks for this!

**Comment by fgiasson** [comment]
@smalinin, @HughWilliams 

Early tests using the Sesame workbench doesn't work. I will test programatically once I am done reporting what is currently happening.

I followed these steps:
- http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtSesame2HttpRepository

However I used the following files:
- https://github.com/openlink/virtuoso-opensource/blob/develop/7/binsrc/sesame4/virt_sesame4.jar
- https://github.com/openlink/virtuoso-opensource/blob/develop/7/libsrc/JDBCDriverType4/virtjdbc4.jar

I copied both in both `openrdf-sesame` and `openrdf-workbench` as specified in the documentation.

I restarted Tomcat.

I started a local Virtuoso instance that is running locally as `localhost:1111`. It is properly running (I can query the SPARQL endpoint, etc.

Then I tried to create the new Virtuoso repository connection. Here is what the Sesame Workbench looks like:

![sesame-workbench](https://cloud.githubusercontent.com/assets/216022/12055774/6038fc3a-aefe-11e5-876b-006ebf737222.png)

However when I click `create` I am getting the following exception:

```
Etat HTTP 500 - javax.servlet.ServletException: java.lang.NullPointerException

type Rapport d'exception

message javax.servlet.ServletException: java.lang.NullPointerException

description Le serveur a rencontré une erreur interne qui l'a empêché de satisfaire la requête.

exception

javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
    org.openrdf.workbench.base.TransformationServlet.service(TransformationServlet.java:116)
    org.openrdf.workbench.base.AbstractServlet.service(AbstractServlet.java:142)
    org.openrdf.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:104)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:222)
    org.openrdf.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:151)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:119)
    org.openrdf.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:131)
    org.openrdf.workbench.base.AbstractServlet.service(AbstractServlet.java:142)
    org.openrdf.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:75)
    org.openrdf.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:63)

cause mère

javax.servlet.ServletException: java.lang.NullPointerException
    org.openrdf.workbench.commands.CreateServlet.doPost(CreateServlet.java:79)
    org.openrdf.workbench.base.TransformationServlet.service(TransformationServlet.java:106)
    org.openrdf.workbench.base.AbstractServlet.service(AbstractServlet.java:142)
    org.openrdf.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:104)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:222)
    org.openrdf.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:151)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:119)
    org.openrdf.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:131)
    org.openrdf.workbench.base.AbstractServlet.service(AbstractServlet.java:142)
    org.openrdf.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:75)
    org.openrdf.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:63)

cause mère

java.lang.NullPointerException
    org.openrdf.workbench.commands.CreateServlet.getConfigTemplate(CreateServlet.java:163)
    org.openrdf.workbench.commands.CreateServlet.createRepositoryConfig(CreateServlet.java:131)
    org.openrdf.workbench.commands.CreateServlet.doPost(CreateServlet.java:76)
    org.openrdf.workbench.base.TransformationServlet.service(TransformationServlet.java:106)
    org.openrdf.workbench.base.AbstractServlet.service(AbstractServlet.java:142)
    org.openrdf.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:104)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:222)
    org.openrdf.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:151)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:119)
    org.openrdf.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:131)
    org.openrdf.workbench.base.AbstractServlet.service(AbstractServlet.java:142)
    org.openrdf.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:75)
    org.openrdf.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:63)

note La trace complète de la cause mère de cette erreur est disponible dans les fichiers journaux de Apache Tomcat/6.0.41.
Apache Tomcat/6.0.41
```

**Comment by HughWilliams** [comment]
@fgiasson: I haven't tried with the Sesame Workbench / HTTP Repository, which is a pain to use at the best of times ...  

Have you tested with the "VirtuosoTest.java" program in git ?

```
Hughs-MBP:sesame4 hwilliams$ pwd
/Users/hwilliams/src/git/vos-7-develop/binsrc/sesame4
Hughs-MBP:sesame4 hwilliams$ ls
total 248
drwxr-xr-x   3 hwilliams  staff    102 30 Dec 13:09 META-INF
-rw-r--r--   1 hwilliams  staff  18075 30 Dec 13:28 Makefile
-rw-r--r--   1 hwilliams  staff   3735 30 Dec 13:09 Makefile.am
-rw-r--r--   1 hwilliams  staff  17290 30 Dec 13:16 Makefile.in
-rw-r--r--   1 hwilliams  staff   5345 30 Dec 13:09 create-virtuoso.xsl
-rw-r--r--   1 hwilliams  staff   2542 30 Dec 13:09 create.xsl
drwxr-xr-x   5 hwilliams  staff    170 30 Dec 13:38 lib
-rw-r--r--   1 hwilliams  staff     44 30 Dec 13:09 manifest.main
drwxr-xr-x   3 hwilliams  staff    102 30 Dec 13:39 out.examples
-rw-r--r--   1 hwilliams  staff    103 30 Dec 13:39 results.n3.txt
drwxr-xr-x   5 hwilliams  staff    170 30 Dec 13:09 tests
-rw-r--r--   1 hwilliams  staff  55873 30 Dec 13:32 virt_sesame4.jar
-rw-r--r--   1 hwilliams  staff    960 30 Dec 13:09 virtuoso.ttl
drwxr-xr-x  16 hwilliams  staff    544 30 Dec 13:09 virtuoso_driver
        virtuoso_driver
Hughs-MBP:sesame4 hwilliams$ ls -l lib
total 5816
-rw-r--r--@ 1 hwilliams  staff   185140 30 Dec 13:51 commons-io-2.4.jar
-rw-r--r--@ 1 hwilliams  staff  2752912 30 Dec 13:46
openrdf-sesame-4.0.0-onejar.jar
-rw-r--r--@ 1 hwilliams  staff    32119 30 Dec 13:51 slf4j-api-1.7.10.jar
Hughs-MBP:sesame4 hwilliams$ make run-tests
rm -rf out.examples
mkdir out.examples
/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/javac  \
                -d out.examples \
                -classpath
"lib/slf4j-api-1.7.10.jar:lib/commons-io-2.4.jar:lib/openrdf-sesame-4.0.0-onejar.jar:../../libsrc/JDBCDriverType4/virtjdbc4.jar:virt_sesame4.jar"
\
                virtuoso_driver/VirtuosoTest.java
Note: virtuoso_driver/VirtuosoTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java \
                -classpath
"lib/slf4j-api-1.7.10.jar:lib/commons-io-2.4.jar:lib/openrdf-sesame-4.0.0-onejar.jar:../../libsrc/JDBCDriverType4/virtjdbc4.jar:virt_sesame4.jar:out.examples"
\
                VirtuosoTest localhost 1111
== TEST 1:  : Start
== TEST 1:  : End
PASSED: TEST 1

== TEST 2:  : Start
   Loading data from URL: http://dbpedia.org/data/Berlin.rdf
log4j:WARN No appenders could be found for logger
(org.openrdf.rio.RDFParserRegistry).
log4j:WARN Please initialize the log4j system properly.
== TEST 2:  : End
PASSED: TEST 2

== TEST 3:  : Start
   Clearing triple store
== TEST 3:  : End
PASSED: TEST 3

== TEST 4:  : Start
   Loading data from file: virtuoso_driver/data.nt
== TEST 4:  : End
PASSED: TEST 4

== TEST 5:  : Start
   Loading UNICODE single triple
== TEST 5:  : End
PASSED: TEST 5

== TEST 6:  : Start
   Loading single triple
== TEST 6:  : End
PASSED: TEST 6

== TEST 7:  : Start
   Casted value type
== TEST 7:  : End
PASSED: TEST 7

== TEST 8:  : Start
   Selecting property
== TEST 8:  : End
PASSED: TEST 8

== TEST 9:  : Start
   Statement does not exists
== TEST 9:  : End
PASSED: TEST 9

== TEST 10:  : Start
   Statement exists (by resultset size)
== TEST 10:  : End
PASSED: TEST 10

== TEST 11:  : Start
   Statement exists (by hasStatement())
== TEST 11:  : End
PASSED: TEST 11

== TEST 12:  : Start
   Retrieving namespaces
== TEST 12:  : End
PASSED: TEST 12

== TEST 13:  : Start
   Retrieving statement (http://myopenlink.net/dataspace/person/kidehen
http://myopenlink.net/foaf/name null)
== TEST 13:  : End
PASSED: TEST 13

== TEST 14:  : Start
   Writing the statements to file:
(/Users/hwilliams/src/git/vos-7-develop/binsrc/sesame4/results.n3.txt)
== TEST 14:  : End
PASSED: TEST 14

== TEST 15:  : Start
   Retrieving graph ids
== TEST 15:  : End
PASSED: TEST 15

== TEST 16:  : Start
   Retrieving triple store size
== TEST 16:  : End
PASSED: TEST 16

== TEST 17:  : Start
   Sending ask query
== TEST 17:  : End
PASSED: TEST 17

== TEST 18:  : Start
   Sending construct query
== TEST 18:  : End
PASSED: TEST 18

== TEST 19:  : Start
   Sending describe query
== TEST 19:  : End
PASSED: TEST 19

============================
PASSED:19 FAILED:0
Hughs-MBP:sesame4 hwilliams$
```

**Comment by fgiasson** [comment]
Hi @HughWilliams,

Yeah, let me test that once I finished testing it programmatically. I should be able to report shortly on this.

**Comment by fgiasson** [comment]
@HughWilliams, @smalinin, @kidehen,

I just tested programatically (using Clojure) and everything appears to be working perfectly so far! (did send SPARQL queries, added data using a Sesame Model, etc. and everything seems to work as expected!

For some reason the Workbench is not working as reported above, but I think it is a workbench issue more than anything else (or a configuration one). 

In any case, it is not an issue with the `VirtuosoRepository` since everything works as expected.

Thanks guys for this great support!

**Comment by fgiasson** [comment]
@kidehen,

Are there any ways to publish `virtjdbc4.jar` and `virt_sesame4.jar` to `search.maven.org` and/or `clojars.org`?

I am not sure what is the maven publication requirements, but I have the sense that it will be much easier on Clojars.

If you don't want to put resources in this, would you mind if I publish them on clojars on your behalf?

This would be essential to make Sesame 4 easily deployable using the Virtuoso Repository.

**Comment by kidehen** [comment]
On 12/30/15 2:57 PM, Frederick Giasson wrote:

> @kidehen https://github.com/kidehen,
> 
> Are there any ways to publish |virtjdbc4.jar| and |virt_sesame4.jar|
> to |search.maven.org| and/or |clojars.org|?
> 
> I am not sure what is the maven publication requirements, but I have
> the sense that it will be much easier on Clojars.
> 
> If you don't want to put resources in this, would you mind if I
> publish them on clojars on your behalf?

No problem, please proceed .

> This would be essential to make Sesame 4 easily deployable using the
> Virtuoso Repository.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openlink/virtuoso-opensource/issues/504#issuecomment-168064505.

## 

Regards,

Kingsley Idehen  
Founder & CEO 
OpenLink Software  
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by HughWilliams** [comment]
@fgiasson: Note an updated Sesame 4 provider and template files are now available in the VOS git develop/7 branch, that work with the Sesame HTTP Repository Workbench and the docs have been updated accordingly, see:

   http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtSesame2HttpRepository

   https://github.com/openlink/virtuoso-opensource/tree/develop/7/binsrc/sesame4

**Comment by fgiasson** [comment]
Hi @HughWilliams, great thanks for this! Will test a bit later.
