### ISSUE TITLE
Difference between virtjdb4 and virtjdbc4_1

### ISSUE THREAD

**Issue by heinlja** [openlink/virtuoso-opensource#505]
Hi!

Can someone enlighten what's the difference between virtjdb4.jar and virtjdbc4_1.jar?
Which is the more correct version to use when running Virtuoso OpenSource 7.2.1 and Java 8 on Tomcat 8?

Thanks!

**Comment by JervenBolleman** [comment]
jdbc4.1 introduced try with resources so it should be the nicer driver to use.
