### ISSUE TITLE
Accessing Virtuoso from C#?

### ISSUE THREAD

**Issue by BassamNa** [openlink/virtuoso-opensource#512]
Hello 
I'm Bassam a master student in software engineering
I want to send sparql queries from C# .net to virtuoso server, then read the query result from C#, how can I do that????

I note there is a OpenLink.Data.Virtuoso.dll in open source but I have a commercial virtuoso? any help?

thanks alot.

**Comment by HughWilliams** [comment]
Do u actually search our documentation or google before asking questions, as there is a complete chapter on the Virtuoso ADO.Net Provider  and  sample programs, see:

   http://docs.openlinksw.com/virtuoso/virtclientref.html

Not the "OpenLink.Data.Virtuoso.dll" is basically a .Net 2 version provider for command line use build against Mono.

If you have the commercial installer there are .Net 2  , 3 & 4 Providers called:

   virtado2.dll
   virtado3.dll
   virtado4.dll

and you can select which one most closely matches your .Net version and it will automatically get registered as a .Net Assembly making instantly accessible in the .Net runtime (or it can also be reference manually as some seem to prefer these days) ...

**Comment by BassamNa** [comment]
thanks Hugh
I have downloaded connectivity kit as described at:
http://docs.openlinksw.com/virtuoso/virtclientref.html
and all done successfully and it exist in installed programs list.
I have visual studio 2013, when I try to add data source via provider
(openlink virtuoso data source),  this provider not exist what is the
problem????

thanks again

On Sat, Dec 19, 2015 at 4:18 AM, HughWilliams notifications@github.com
wrote:

> Do u actually search our documentation or google before asking questions,
> as there is a complete chapter on the Virtuoso ADO.Net Provider and sample
> programs, see:
> 
> http://docs.openlinksw.com/virtuoso/virtclientref.html
> 
> Not the "OpenLink.Data.Virtuoso.dll" is basically a .Net 2 version
> provider for command line use build against Mono.
> 
> If you have the commercial installer there are .Net 2 , 3 & 4 Providers
> called:
> 
> virtado2.dll
> virtado3.dll
> virtado4.dll
> 
> and you can select which one most closely matches your .Net version and it
> will automatically get registered as a .Net Assembly making instantly
> accessible in the .Net runtime (or it can also be reference manually as
> some seem to prefer these days) ...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openlink/virtuoso-opensource/issues/512#issuecomment-165936272
> .

## 

---

> Eng.Bassam Najeeb.
> Software Engineer.

**Comment by BassamNa** [comment]
Hi
for developers who want to access virtuoso via C#, I do the following:
1- add connection string at app settings
<add name="virCon" connectionString="Data Source=localhost:1113; User
ID=dba;Password=dba"
      providerName="Provider=OpenLink.Data.Virtuoso; Persist Security
Info=False" />
2- using virtado4.dll ADO's classes after reference it
string conString =
System.Configuration.ConfigurationManager.ConnectionStrings["MYCONN"].ConnectionString;
            VirtuosoConnection virtuosoSrv = new
VirtuosoConnection(conString );
            virtuosoSrv .Open();
            VirtuosoCommand cmd = new VirtuosoCommand("sparql SELECT
?termURI FROM http://localhost:8890/ontologies/geonames WHERE { ?termURI
?z ?y.} LIMIT 10", virtuosoSrv );
            VirtuosoDataReader countryDataReader =  cmd.ExecuteReader();
            while (countryDataReader.Read())
            {
                String col = countryDataReader.GetString(0); // make
something
            }

wish it's usefull :)

On Sun, Dec 20, 2015 at 7:30 AM, Eng.Bassam bassam86@gmail.com wrote:

> thanks Hugh
> I have downloaded connectivity kit as described at:
> http://docs.openlinksw.com/virtuoso/virtclientref.html
> and all done successfully and it exist in installed programs list.
> I have visual studio 2013, when I try to add data source via provider
> (openlink virtuoso data source),  this provider not exist what is the
> problem????
> 
> thanks again
> 
> On Sat, Dec 19, 2015 at 4:18 AM, HughWilliams notifications@github.com
> wrote:
> 
> > Do u actually search our documentation or google before asking questions,
> > as there is a complete chapter on the Virtuoso ADO.Net Provider and sample
> > programs, see:
> > 
> > http://docs.openlinksw.com/virtuoso/virtclientref.html
> > 
> > Not the "OpenLink.Data.Virtuoso.dll" is basically a .Net 2 version
> > provider for command line use build against Mono.
> > 
> > If you have the commercial installer there are .Net 2 , 3 & 4 Providers
> > called:
> > 
> > virtado2.dll
> > virtado3.dll
> > virtado4.dll
> > 
> > and you can select which one most closely matches your .Net version and
> > it will automatically get registered as a .Net Assembly making instantly
> > accessible in the .Net runtime (or it can also be reference manually as
> > some seem to prefer these days) ...
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/openlink/virtuoso-opensource/issues/512#issuecomment-165936272
> > .
> 
> ## 
> 
> ---
> 
> > Eng.Bassam Najeeb.
> > Software Engineer.

## 

---

> Eng.Bassam Najeeb.
> Software Engineer.
