### ISSUE TITLE
VOS 7.2.2 count(distinct *) returns a wrong value

### ISSUE THREAD

**Issue by yayamamo** [openlink/virtuoso-opensource#513]
I use vos 7.2.2 on Red Hat Enterprise Linux Server release 6.2, and the SPARQL query "select (count(distinct *) as ?total) where {?s ?p ?o} " returns a wrong value.
When issuing it from the browser (http://localhost/sparql), I got 1499, but counted more than 5000 lines when using curl on a terminal with the return format value of text/tab-separated-values as follows.

```
% curl -g 'http://localhost/sparql?default-graph-uri=&query=select+distinct+*+where+{%3Fs+%3Fp+%3Fo}&format=text%2Ftab-separated-values'
```

**Comment by kidehen** [comment]
On 12/18/15 1:02 AM, Yasunori wrote:

> I use vos 722 on Red Hat Enterprise Linux Server release 62, and the
> SPARQL query "select (count(distinct *) as ?total) where {?s ?p ?o} "
> returns a wrong value
> When issuing it from the browser (http://localhost/sparql), I got
> 1499, but counted more than 5000 lines when using curl on a terminal
> with the return format value of text/tab-separated-values as follows
> 
> |% curl -g
> 'http://localhost/sparql?default-graph-uri=&query=select+distinct+*+where+{%3Fs+%3Fp+%3Fo}&format=text%2Ftab-separated-values'
> |
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openlink/virtuoso-opensource/issues/513.

Did you try this same query via the ISQL interface? Note, the HTML
interface includes an "Anytime Query" feature that produces aggregates
within set timeframe. You can make this timeframe larger to reduce its
effect. Try something like 30000 msec or higher.

## 

Regards,

Kingsley Idehen  
Founder & CEO 
OpenLink Software  
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by yayamamo** [comment]
I tried via ISQL, and got the same result as via a browser, i.e., 1499.

**Comment by HughWilliams** [comment]
@yayamamo:  I have been able to recreate this issue and reported to development to look into ...

**Comment by openlink** [comment]
We have committed a fix for this issue.

Please checkout the develop/7 branch.
