### ISSUE TITLE
Timestamp reading anomaly in virtjdbc-4.x on Virtuoso 7.2.x

### ISSUE THREAD

**Issue by heinlja** [openlink/virtuoso-opensource#518]
Versions tried with:
- Virtuoso 7.2.1 and 7.2.2
- virtjdbc4 and virtjdbc4.1
- Java 6 and 7
- Win 7 74-bit and CentOS 7 64-bit

Start a brand new database from default virtuoso.ini. Create simple table with 1 simple row that inserts current transaction timestamp:

``` sql
create table "TEST"."DBA"."test_table" (
  "id" INTEGER IDENTITY,
  "name" VARCHAR(255),
  "time_created" DATETIME,
  PRIMARY KEY ("id")
);
insert into "TEST"."DBA"."test_table" (name, time_created) values ('name 1', now());
```

Read this row with virtujdbc4 or 4_1 driver, like this:

``` java
Connection conn = null;
ResultSet rs = null;
Statement stmt = null;
try {
     // some code here for getting DB connection and creating SQL statement
     // ...
     rs = stmt.executeQuery("select * from test_table");
     if (rs.next()) {
         Timestamp ts = rs.getTimestamp("time_created");
     }
}
```

The timestamp that is read is a few days in the future (even though the minutes, seconds and milliseconds are correct), but it should have been the above transaction timestamp.

When querying directly in ISQL, we can see the timestamp in the table is correct.
When doing the same on Virtuoso 7.0.x, it works!

**Comment by HughWilliams** [comment]
@heinlja: I can recreate:

```
SQL> create table "TEST"."DBA"."test_table" (   "id" INTEGER IDENTITY,   "name" VARCHAR(255),   "time_created" DATETIME,   PRIMARY KEY ("id") );

Done. -- 20 msec.
SQL> insert into "TEST"."DBA"."test_table" (name, time_created) values ('name 1', now());

Done. -- 1 msec.
SQL> select * from "TEST"."DBA"."test_table";
id                name                                                                              time_created
INTEGER NOT NULL  VARCHAR                                                                           TIMESTAMP
_______________________________________________________________________________

1                 name 1                                                                            2016.1.6 1:54.30 970141000

1 Rows. -- 1 msec.
SQL>

Hughs-MBP:Downloads hwilliams$ javac -cp ./virtjdbc4-10.jar samplevirt.java 
Hughs-MBP:Downloads hwilliams$ java -cp "./virtjdbc4-10.jar:." samplevirt
2016-01-11 09:15:54.566938
Hughs-MBP:Downloads hwilliams$
```

This seems to be as a result of the recent timezoneless datetime support added to Virtuoso in 7.2.1+ , see:

```
http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtTimezoneLessDateTime
```

As indicated you can get the old behaviour by setting "TimezonelessDatetimes = 0" in the INI file , although any datetime data would have to be reloaded.

I shall report this to development to look into ...

**Comment by heinlja** [comment]
Thanks, Hugh!
Setting "TimezonelessDatetimes = 0" has worked indeed.

So when I'm upgrading from 7.0.0 to 7.2.1+, does it mean I have to set "TimezonelessDatetimes = 0" **before** I start the database with the new Virtuoso? And that will take care of my already existing datetimes?

P.S. Perhaps you can also look into issue #517 ?

**Comment by HughWilliams** [comment]
@heinlja: Yes, as it would continue to function in that mode i.e. without TimezonelessDatetimes ...

Hmmm, thought I commented on #517 already, as it has been recreated and report to development to look into already  ...

**Comment by HughWilliams** [comment]
@heinlja: Actually my problem was being on Mac OS X which was pickup and old jar file from my Java "Extensions" folder:

```
Hughs-MBP:JDBCDriverType4 hwilliams$ java -jar
/Library/Java/Extensions/virtjdbc4.jar 
OpenLink Virtuoso(TM) Driver for JDBC(TM) Version 4.x [Build 3.76]
```

When I remove that thing, then my 4.1 jar gives the correct version and the correct datetime value is returned:

```
Hughs-MBP:JDBCDriverType4 hwilliams$ java -jar ./virtjdbc4_1.jar
OpenLink Virtuoso(TM) Driver for JDBC(TM) Version 4.1 [Build 3.92]
Hughs-MBP:Downloads hwilliams$ java -cp "./virtjdbc4_1.jar:." samplevirt
2016-01-06 02:05:43.716666
Hughs-MBP:Downloads hwilliams$
```

So you need to make sure you are using the latest 3.92 version of the JDBC Driver which has updates to work with Timezponeless Datetimes ...
