### ISSUE TITLE
missing dependency: debian packages for 7.2.2.1 and stable/7 don't compile

### ISSUE THREAD

**Issue by joernhees** [openlink/virtuoso-opensource#521]
it seems that after 7.2.1 a dependency bug with java 6 was re-introduced:

```
$ dpkg-buildpackage -us -uc -j4
dpkg-buildpackage: source package virtuoso-opensource
dpkg-buildpackage: source version 7.2.2
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by OpenLink Virtuoso Maintainer <vos.admin@openlinksw.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build virtuoso-opensource-7.2.2.1
 debian/rules clean
dpkg-query: package 'openjdk-6-jdk' is not installed
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
test -x debian/rules
/usr/bin/make -C binsrc/VirtuosoClient.Net clean
make[1]: Entering directory '/tmp/build/virtuoso-opensource-7.2.2.1/binsrc/VirtuosoClient.Net'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory '/tmp/build/virtuoso-opensource-7.2.2.1/binsrc/VirtuosoClient.Net'
debian/rules:75: recipe for target 'cleanbuilddir/libvirtmono0-cil' failed
make: *** [cleanbuilddir/libvirtmono0-cil] Error 2
dpkg-buildpackage: error: debian/rules clean gave error exit status 2
```

To reproduce this, you can either run

``` bash
docker run --rm -it -v ~/virtuoso_7.2.2_pkgs:/export/ joernhees/dpkg_build https://github.com/openlink/virtuoso-opensource/archive/stable/7.tar.gz -j4
```

or the following equivalent on a vanilla debian 8 (`docker run --rm -it debian`):

``` bash
apt-get update && apt-get install -y build-essential devscripts wget
mkdir /tmp/build && cd /tmp/build
wget https://github.com/openlink/virtuoso-opensource/archive/v7.2.2.1.tar.gz  # or // https://github.com/openlink/virtuoso-opensource/archive/stable/7.tar.gz
tar -xvzf *.tar.gz
cd virtuoso-opensource*/
mk-build-deps -irt'apt-get --no-install-recommends -yV' && dpkg-checkbuilddeps
dpkg-buildpackage -us -uc -j4
```

reminds me of #342 and #404 ... note that `openjdk-6-jdk` isn't available anymore...

**Comment by openlink** [comment]
The debian/rules file checks if your system has the openjdk-6-jdk package and automatically configures to build with it if available. If not, it will not build the virtjdbc4.jar. The output you see is a warning from dpkg-query that this package is not available on your platform but it has no consequences for your building process. We may redirect the stderr of this command if this causes confusion

The problem you have is not with the openjdk 6, but with the build rules for the Mono provider which was not compiled/installed properly on Debian and other systems. We made some fixes to better detect the various versions of the Mono compiler during the configuration phase so make would be able to build our mono provider automatically. Unfortunately the debian/rules file used an older construction which broke on a clean build which was unfortunately detected after the release (see commit 4c438f3f6).

You can try this by using https://github.com/openlink/virtuoso-opensource/archive/develop/7.tar.gz 

We have setup some extra verification steps to make sure this does not happen again for the next stable release.

**Comment by joernhees** [comment]
cool, thanks... and sorry for getting the error wrong.

could you maybe add the debian build to your internal tests/CI?
