### ISSUE TITLE
DB corrution with Virtuoso 7.2.0.1 (insert.c:1557 and colsearch.c:816)

### ISSUE THREAD

**Issue by yonyonson** [openlink/virtuoso-opensource#522]
Hei,

we are regularly getting DB corruption issues with Virtuoso 7.2.0.1.

It always starts with following error in log: `ERROR: GPF: insert.c:1557 In compact, no remap dp for a dirty buffer`. Afterwards Virtuoso enters restart cycle where it:
- Starts up and waits for the first SPARQL query coming in
- Sometimes returns result of 1 query
- Writes error `ERROR: GPF: colsearch.c:816 ref to deld col page` in the log
- Dies

When trying to execute backup procedure as described [here](http://docs.openlinksw.com/virtuoso/databaseadmsrv.html#diagnosingrepairing) we see that Virtuoso is crashing with following error message:

```
                Mon Jan 11 2016
12:44:06 INFO: { Loading plugin 1: Type `plain', file `wikiv' in `/usr/local/virtuoso-opensource/lib/virtuoso/hosting'
12:44:06 ERROR:   FAILED  plugin 1: Unable to locate file }
12:44:06 INFO: { Loading plugin 2: Type `plain', file `mediawiki' in `/usr/local/virtuoso-opensource/lib/virtuoso/hosting'
12:44:06 ERROR:   FAILED  plugin 2: Unable to locate file }
12:44:06 INFO: { Loading plugin 3: Type `plain', file `creolewiki' in `/usr/local/virtuoso-opensource/lib/virtuoso/hosting'
12:44:06 ERROR:   FAILED  plugin 3: Unable to locate file }
12:44:06 INFO: OpenLink Virtuoso Universal Server
12:44:06 INFO: Version 07.20.3212-pthreads for Linux as of Nov 12 2015
12:44:06 INFO: uses parts of OpenSSL, PCRE, Html Tidy
12:44:13 INFO: Database version 3126
12:44:13 INFO: SQL Optimizer enabled (max 1000 layouts)
12:44:14 INFO: Compiler unit is timed at 0.000185 msec
12:44:17 DEBUG: built-in procedure "repl_undot_name" overruled by the RDBMS
12:44:17 INFO: Roll forward started
12:44:18 INFO:     4 transactions, 835 bytes replayed (100 %)
12:44:18 INFO: Roll forward complete
12:44:20 INFO: Checkpoint started
12:44:20 INFO: Checkpoint finished, log reused
12:44:20 INFO: HTTP/WebDAV server online at 8890
12:44:20 INFO: Server online at 1111 (pid 1)
12:52:11 INFO: Backup to /dev/null started
12:52:11 DEBUG: Dumping the schema tables
12:52:11 DEBUG: Dumping the registry
12:52:11 DEBUG: Dumping the schema done
12:53:05 ERROR: Columns of different length in seg key RDF_QUAD_POGS L=14293, r = 0
```

We are working now on trying to run restore procedure as described [here](http://docs.openlinksw.com/virtuoso/databaseadmsrv.html#dbrebuild) . 

We see also that there are segfaults in `syslog`, attaching them.

It should be noted that:
- We run Virtuoso in Docker container that we can make available for Openlink in case you need it for debugging (and that's why Virtuoso always has PID 1)
- We have time zone UTC in Docker container
- Time zone CET (+1) on host OS

We run:
- Ubuntu 14.04 as host OS
- Docker 1.9.0
- `ubuntu:14.04` as a base image for Virtuoso docker image

Attachments:
- Last 20 000 lines from virtuoso log: [virtuoso.log.zip](https://github.com/openlink/virtuoso-opensource/files/85861/virtuoso.log.zip)
- Summary of GPF issues fom Virtuosos log: [GPF.errors.log.txt](https://github.com/openlink/virtuoso-opensource/files/85863/GPF.errors.log.txt)
- Syslog from server: [syslog.txt](https://github.com/openlink/virtuoso-opensource/files/85865/syslog.txt)
- Virtuoso.ini: [virtuoso.ini.txt](https://github.com/openlink/virtuoso-opensource/files/85874/virtuoso.ini.txt)

**Comment by yonyonson** [comment]
I can provide docker inspect data on container, Dockerfile for image and DB files if necessary.

**Comment by HughWilliams** [comment]
There was a fix for this issue in the latest open source 7.2.2 (07.20.3215) develop or stable 7 branches in git  at https://github.com/openlink/virtuoso-opensource   ... thus you should update you 07.20.3212 (7.20) build to this release. I would also recommend performing a crash-dump and restore to rebuild the database with updated binary ...

**Comment by yonyonson** [comment]
@HughWilliams Thanks for the answer!
We have unfortunately seen incompatibility between database engines while migrating from 7.2.0 to 7.2.1 and different ways to handle datetime in DB (it broke some of our SPARQL queries), so we will migrate, but it would most likely take some time and testing. We haven't really tried 7.2.2 out so far.

Another question: What is recommended way to migrate data between different versions of binaries? Performing backup and restoring it?

**Comment by HughWilliams** [comment]
@yonyonson Strictly speaking as all 7.x version use the same database engine you should just have to run a checkpoint prior to closing down the existing database running with a given version and then restart the same database with the new version as detailed at http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/UpgradingToVOS610#Upgrading%20from%20Release%207.x%20to%20a%20newer%20Release%207.x

But if you suspect there may be some corruption or inconsistency in the existing database, as in this case, then an integrity check,  +crash-dump and restore should be performed as detailed in the restore procedure you referred to previously at http://docs.openlinksw.com/virtuoso/databaseadmsrv.html#dbrebuild ...

**Comment by yonyonson** [comment]
@HughWilliams Yes, that is checkpoint that causes issues, you are correct.

Ok, thanks, I will try it out.

Closing issue so far.
