### ISSUE TITLE
Question about enterprise license

### ISSUE THREAD

**Issue by Miyayx** [openlink/virtuoso-opensource#526]
Hi

I want to install Virtuoso on a new server with the old dataset and license. 

We have a purchased virtuoso.lic for previous virtuoso. Can I reuse it?

 Here are my steps:
1. uncompress the downloaded tar to directory /usr/local/virtuoso-server/
2. copy the virtuoso.lic to /usr/local/virtuoso-server/
3. run install.sh ( now there is a virtuoso.lic in /usr/local/virtuoso-server/bin)
4. start virtuoso  `virtuoso -f -c /usr/local/virtuoso-server/database/virtuoso.ini`

```
11:19:56 License not found
11:19:56 Please make sure it is installed correctly
11:19:56 If you did not receive a license file,
11:19:56 contact sales@openlinksw.com or visit www.openlinksw.com
11:19:56 and a new license will be made available to you
```
1.  copy the previous virtuoso.db(23G) to virtuoso-server/database
    run virtuoso-start.sh

```
Starting Virtuoso instance in [database]
The VDBMS server process terminated prematurely
after opening the database.

***
*** ERROR: Could not start this Virtuoso Instance.
***
11:01:56 contact sales@openlinksw.com or visit www.openlinksw.com
11:01:56 and a new license will be made available to you
11:01:56 
11:02:06 Database version 3126
11:02:06 SQL Optimizer enabled (max 1000 layouts)
11:02:07 
11:02:07 Your license does not allow the Column Store Extension
11:02:07 Please contact OpenLink Customer Support <support@openlinksw.com>
11:02:07 
11:02:07 Server exiting
***
*** Please fix the above issue(s) before trying again.
***
```

Did I make mistakes?  How can I reuse the license and dataset in a right way?

Thank you.

**Comment by kidehen** [comment]
On 1/27/16 10:56 PM, Miyayx wrote:

> Hi
> 
> I want to install Virtuoso on a new server with the old dataset and
> license.
> 
> We have a purchased virtuoso.lic for previous virtuoso. Can I reuse it?
> 
> Here are my steps:
> 1. uncompress the downloaded tar to directory /usr/local/virtuoso-server/
> 2. copy the virtuoso.lic to /usr/local/virtuoso-server/
> 3. run install.sh ( now there is a virtuoso.lic in
> /usr/local/virtuoso-server/bin)
> 4. start virtuoso |virtuoso -f -c
> /usr/local/virtuoso-server/database/virtuoso.ini|
> 
> |11:19:56 License not found 11:19:56 Please make sure it is installed
> correctly 11:19:56 If you did not receive a license file, 11:19:56
> contact sales@openlinksw.com or visit www.openlinksw.com 11:19:56 and
> a new license will be made available to you |
> 1. copy the previous virtuoso.db(23G) to virtuoso-server/database run
>    virtuoso-start.sh
> 
> |Starting Virtuoso instance in [database] The VDBMS server process
> terminated prematurely after opening the database. **\* **\* ERROR:
> Could not start this Virtuoso Instance. **\* 11:01:56 contact
> sales@openlinksw.com or visit www.openlinksw.com 11:01:56 and a new
> license will be made available to you 11:01:56 11:02:06 Database
> version 3126 11:02:06 SQL Optimizer enabled (max 1000 layouts)
> 11:02:07 11:02:07 Your license does not allow the Column Store
> Extension 11:02:07 Please contact OpenLink Customer Support
> support@openlinksw.com 11:02:07 11:02:07 Server exiting **\* ***
> Please fix the above issue(s) before trying again. **\* |
> 
> Did I make mistakes? How can I reuse the license and dataset in a
> right way?
> 
> Thank you.

You appear to be attempting to use a version 6 license with version 7.
As the error message indicates, you need to upgrade your license.

On receipt of your upgrade (if that's what this matter boils down to)
you will need to perform the following steps:

[1] dump you V6 RDF data
[2] start the license manager using:
oplmgr +start +directory {where-ever-you-have-your-dot-lic-file}
[3] start virtuoso server
[4] load dumped data into new V7 database (that has column-store module
enabled).

## 

Regards,

Kingsley Idehen  
Founder & CEO 
OpenLink Software  
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by Miyayx** [comment]
Sorry, how to upgrade my license?

Send an email to the official? or purchase a new one ?

2016-01-29 0:00 GMT+08:00 Kingsley Idehen notifications@github.com:

> On 1/27/16 10:56 PM, Miyayx wrote:
> 
> > Hi
> > 
> > I want to install Virtuoso on a new server with the old dataset and
> > license.
> > 
> > We have a purchased virtuoso.lic for previous virtuoso. Can I reuse it?
> > 
> > Here are my steps:
> > 1. uncompress the downloaded tar to directory /usr/local/virtuoso-server/
> > 2. copy the virtuoso.lic to /usr/local/virtuoso-server/
> > 3. run install.sh ( now there is a virtuoso.lic in
> > /usr/local/virtuoso-server/bin)
> > 4. start virtuoso |virtuoso -f -c
> > /usr/local/virtuoso-server/database/virtuoso.ini|
> > 
> > |11:19:56 License not found 11:19:56 Please make sure it is installed
> > correctly 11:19:56 If you did not receive a license file, 11:19:56
> > contact sales@openlinksw.com or visit www.openlinksw.com 11:19:56 and
> > a new license will be made available to you |
> > 1. copy the previous virtuoso.db(23G) to virtuoso-server/database run
> >    virtuoso-start.sh
> > 
> > |Starting Virtuoso instance in [database] The VDBMS server process
> > terminated prematurely after opening the database. **\* **\* ERROR:
> > Could not start this Virtuoso Instance. **\* 11:01:56 contact
> > sales@openlinksw.com or visit www.openlinksw.com 11:01:56 and a new
> > license will be made available to you 11:01:56 11:02:06 Database
> > version 3126 11:02:06 SQL Optimizer enabled (max 1000 layouts)
> > 11:02:07 11:02:07 Your license does not allow the Column Store
> > Extension 11:02:07 Please contact OpenLink Customer Support
> > support@openlinksw.com 11:02:07 11:02:07 Server exiting **\* ***
> > Please fix the above issue(s) before trying again. **\* |
> > 
> > Did I make mistakes? How can I reuse the license and dataset in a
> > right way?
> > 
> > Thank you.
> 
> You appear to be attempting to use a version 6 license with version 7.
> As the error message indicates, you need to upgrade your license.
> 
> On receipt of your upgrade (if that's what this matter boils down to)
> you will need to perform the following steps:
> 
> [1] dump you V6 RDF data
> [2] start the license manager using:
> oplmgr +start +directory {where-ever-you-have-your-dot-lic-file}
> [3] start virtuoso server
> [4] load dumped data into new V7 database (that has column-store module
> enabled).
> 
> ## 
> 
> Regards,
> 
> Kingsley Idehen
> Founder & CEO
> OpenLink Software
> Company Web: http://www.openlinksw.com
> Personal Weblog 1: http://kidehen.blogspot.com
> Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
> Twitter Profile: https://twitter.com/kidehen
> Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
> LinkedIn Profile: http://www.linkedin.com/in/kidehen
> Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openlink/virtuoso-opensource/issues/526#issuecomment-176247946
> .

## 

Best Wishes

GitHub:github.com/Miyayx

**Comment by Miyayx** [comment]
In addition, could the license be shared in two or more Virtuosos?

2016-01-29 0:00 GMT+08:00 Kingsley Idehen notifications@github.com:

> On 1/27/16 10:56 PM, Miyayx wrote:
> 
> > Hi
> > 
> > I want to install Virtuoso on a new server with the old dataset and
> > license.
> > 
> > We have a purchased virtuoso.lic for previous virtuoso. Can I reuse it?
> > 
> > Here are my steps:
> > 1. uncompress the downloaded tar to directory /usr/local/virtuoso-server/
> > 2. copy the virtuoso.lic to /usr/local/virtuoso-server/
> > 3. run install.sh ( now there is a virtuoso.lic in
> > /usr/local/virtuoso-server/bin)
> > 4. start virtuoso |virtuoso -f -c
> > /usr/local/virtuoso-server/database/virtuoso.ini|
> > 
> > |11:19:56 License not found 11:19:56 Please make sure it is installed
> > correctly 11:19:56 If you did not receive a license file, 11:19:56
> > contact sales@openlinksw.com or visit www.openlinksw.com 11:19:56 and
> > a new license will be made available to you |
> > 1. copy the previous virtuoso.db(23G) to virtuoso-server/database run
> >    virtuoso-start.sh
> > 
> > |Starting Virtuoso instance in [database] The VDBMS server process
> > terminated prematurely after opening the database. **\* **\* ERROR:
> > Could not start this Virtuoso Instance. **\* 11:01:56 contact
> > sales@openlinksw.com or visit www.openlinksw.com 11:01:56 and a new
> > license will be made available to you 11:01:56 11:02:06 Database
> > version 3126 11:02:06 SQL Optimizer enabled (max 1000 layouts)
> > 11:02:07 11:02:07 Your license does not allow the Column Store
> > Extension 11:02:07 Please contact OpenLink Customer Support
> > support@openlinksw.com 11:02:07 11:02:07 Server exiting **\* ***
> > Please fix the above issue(s) before trying again. **\* |
> > 
> > Did I make mistakes? How can I reuse the license and dataset in a
> > right way?
> > 
> > Thank you.
> 
> You appear to be attempting to use a version 6 license with version 7.
> As the error message indicates, you need to upgrade your license.
> 
> On receipt of your upgrade (if that's what this matter boils down to)
> you will need to perform the following steps:
> 
> [1] dump you V6 RDF data
> [2] start the license manager using:
> oplmgr +start +directory {where-ever-you-have-your-dot-lic-file}
> [3] start virtuoso server
> [4] load dumped data into new V7 database (that has column-store module
> enabled).
> 
> ## 
> 
> Regards,
> 
> Kingsley Idehen
> Founder & CEO
> OpenLink Software
> Company Web: http://www.openlinksw.com
> Personal Weblog 1: http://kidehen.blogspot.com
> Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
> Twitter Profile: https://twitter.com/kidehen
> Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
> LinkedIn Profile: http://www.linkedin.com/in/kidehen
> Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openlink/virtuoso-opensource/issues/526#issuecomment-176247946
> .

## 

Best Wishes

GitHub:github.com/Miyayx

**Comment by HughWilliams** [comment]
@Miyayx: If you are a commercial Virtuoso user then you should log an online support case with us at http://support.openlinksw.com/support/online-support.vsp detailing the issue being encountered , where one of our consultants can assist in resolution ...
