### ISSUE TITLE
develop/7 missing implementation for clrdf.c/cl_id_to_iri

### ISSUE THREAD

**Issue by jeremycarroll** [openlink/virtuoso-opensource#53]
I loaded a million or so skos triples and then trying to index them with:

SQL> RDF_OBJ_FT_RULE_ADD(null,'http://www.w3.org/2004/02/skos/core#altLabel','alt label');
SQL> RDF_OBJ_FT_RULE_ADD(null,'http://www.w3.org/2004/02/skos/core#prefLabel','pref label'); 

results in:

16:46:27 0   virtuoso-t                          0x000000010aef1038 gpf_notice + 56
16:46:27 1   virtuoso-t                          0x000000010aa5d587 cl_id_to_iri + 23
16:46:27 2   virtuoso-t                          0x000000010acf95db bif_rdf_obj_ft_rule_add + 187
16:46:27 3   virtuoso-t                          0x000000010ac49506 ins_call_bif + 166
16:46:27 4   virtuoso-t                          0x000000010ac4fe5a code_vec_run_1 + 1498
16:46:27 5   virtuoso-t                          0x000000010ac7a912 qn_input + 546
16:46:27 6   virtuoso-t                          0x000000010ac7edea qr_subq_exec + 1306
16:46:27 7   virtuoso-t                          0x000000010ac4ce04 ins_call + 2644
16:46:27 8   virtuoso-t                          0x000000010ac4fe3d code_vec_run_1 + 1469
16:46:27 9   virtuoso-t                          0x000000010ac7a912 qn_input + 546
16:46:27 10  virtuoso-t                          0x000000010ac80606 qr_exec + 2758
16:46:27 11  virtuoso-t                          0x000000010ac80d9d qr_quick_exec + 445
16:46:27 12  virtuoso-t                          0x000000010aa99475 ddl_ensure_table + 277
16:46:27 13  virtuoso-t                          0x000000010aba0674 sqls_define_sparql + 6052
16:46:27 14  virtuoso-t                          0x000000010ac823b2 sql_code_global_init + 50
16:46:27 15  virtuoso-t                          0x000000010ac897ad srv_global_init + 2957
16:46:27 16  virtuoso-t                          0x000000010aa0e71a main + 1514
16:46:27 17  libdyld.dylib                       0x00007fff8d9237e1 start + 0
16:46:27 18  ???                                 0x0000000000000002 0x0 + 2
16:46:27 GPF: clrdf.c:680 internal error
GPF: clrdf.c:680 internal error
'

Tracking that down in the source gives:

caddr_t
cl_id_to_iri (query_instance_t \* qi, caddr_t id)
{
  GPF_T;
  return NULL;
}

**Comment by openlink** [comment]
This has been fixed on the develop/7 branch
