### ISSUE TITLE
Searching for polygons within a polygon

### ISSUE THREAD

**Issue by Polymathronic** [openlink/virtuoso-opensource#531]
The following query:

```
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT ?shape
WHERE { 
?shape geo:hasGeometry ?g .
?g geo:asWKT ?gWKT .
FILTER (bif:st_within(?gWKT, "POLYGON ((23.533692 41.095936,23.613343 41.089727,23.671021 41.063846,23.730073 41.042098))"^^geo:wktLiteral)) 
}
```

...results in this:

> Virtuoso 42000 Error GEO..: for geo contains, only "shape contains point" case is supported in current version

Happens with 07.20.3212 (GeoKnow) and 07.20.3214, but **works** with 07.10.3211 (Build: Jul 23 2014).

**Comment by HughWilliams** [comment]
Hi Uroš, 

We haven't seen any occurrences of this error before. Have you tried dumping the datasets from the 7.1 database and reloading into an empty database with a 7.2 binary ?

If the problem persists, is  a public dataset being used that can be provided such that we can load locally to recreated ?

Regards
Hugh

**Comment by Polymathronic** [comment]
Hi Hugh,

Yes (same data, clean db, 7.2 binary).
I've just noticed it also happens with 7.1 if I remove the `?shape geo:hasGeometry ?g` bit. :/
Here's a small dump to replicate the problem:

```
@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix elod:   <http://linkedeconomy.org/ontology#> .
@prefix ogcgs:  <http://www.opengis.net/ont/geosparql#> .
@prefix virtrdf:    <http://www.openlinksw.com/schemas/virtrdf#> .

<http://linkedeconomy.org/resource/Subsidy/200122>  rdf:type    elod:Subsidy ;
                                                    elod:hasRelatedFeature  <http://linkedeconomy.org/resource/PlaceOfInterest/200122> .
<http://linkedeconomy.org/resource/Feature/200122>  ogcgs:hasGeometry   <http://linkedeconomy.org/resource/Geometry/200122> .
<http://linkedeconomy.org/resource/Geometry/200122> ogcgs:asWKT "POLYGON((23.533692 41.095936,23.613343 41.089727,23.671021 41.063846,23.730073 41.042098))"^^virtrdf:Geometry .
```

Thanks for looking into it.

Best,
Uroš

**Comment by HughWilliams** [comment]
Hi Uroš,  

I have loaded the sample data and have been able to recreate the problem against a local Virtuoso instance running the latest, Virtuoso open source develop/7 branch and have reported to development to look into:

```
SQL> sparql PREFIX geo: <http://www.opengis.net/ont/geosparql#>  SELECT ?shape WHERE {  ?shape geo:hasGeometry ?g . ?g geo:asWKT ?gWKT . FILTER (bif:st_within(?gWKT, "POLYGON ((23.533692 41.095936,23.613343 41.089727,23.671021 41.063846,23.730073 41.042098))"^^geo:wktLiteral))  };

*** Error 42000: VD [Virtuoso Server]GEO..: for geo contains, only "shape contains point" case is supported in current version
at line 1 of Top-Level:
sparql PREFIX geo: <http://www.opengis.net/ont/geosparql#>  SELECT ?shape WHERE {  ?shape geo:hasGeometry ?g . ?g geo:asWKT ?gWKT . FILTER (bif:st_within(?gWKT, "POLYGON ((23.533692 41.095936,23.613343 41.089727,23.671021 41.063846,23.730073 41.042098))"^^geo:wktLiteral))  }
SQL> status('');
REPORT
VARCHAR
_______________________________________________________________________________

OpenLink Virtuoso  Server
Version 07.20.3216-pthreads for Darwin as of Feb 16 2016 
Started on: 2016-02-16 13:39 GMT+0
```

Regards
Hugh

**Comment by mirkospasic** [comment]
Hi Uroš,

You are right. I have tried that, and everything mentioned here is true, but...

My opinion is that this is not a bug. This is only a small difference between those versions. Basically, when we are talking about predicate `st_within`, we support only check if whether the point is within a shape. The error message in question unambiguously expressed that:
`Virtuoso 42000 Error GEO..: for geo contains, only "shape contains point" case is supported in current version`

The problem seems to be in the older version, where this kind of message did not appear. In that case, instead of the appropriate error message, all queries containing similar filtering return 0 rows, without informing a user that the query in question is not supported. If we take a look on the SQL translation of this SPARQL query using the old version of Virtuoso, this will be obvious:
```sql
SQL> SET BLOBS ON;
SQL> SET SPARQL_TRANSLATE ON;
SQL> SELECT ?shape WHERE { ?shape geo:hasGeometry ?g . ?g geo:asWKT ?gWKT . FILTER (bif:st_within(?gWKT, "POLYGON ((23.533692 41.095936,23.613343 41.089727,23.671021 41.063846,23.730073 41.042098))"^^geo:wktLiteral)) };
SPARQL_TO_SQL_TEXT
LONG VARCHAR

---

SELECT __id2in ( /_retval[_/ "s_1_4_t0"."S" /\* shape _/ /_]retval_/ ) AS /_tmpl_/ "shape"
FROM DB.DBA.RDF_QUAD AS "s_1_4_t0"
  INNER JOIN (SELECT  "s_1_4_t1-int"."G" AS /_tmpl_/ "1f4d6c1~G",  "s_1_4_t1-int"."S" AS /_tmpl_/ "7359bf7e~S",  "s_1_4_t1-int"."P" AS /_tmpl_/ "13cd6c1~P",  "s_1_4_t1-int"."O" AS /_tmpl_/ "6373ceb9~O" FROM DB.DBA.RDF_QUAD AS "s_1_4_t1-int"
     WHERE  /_ invalidated freetext or spatial predicate _/ 
   (1 = 2)
    AND  /_ field equal to URI ref _/ 
    "s_1_4_t1-int"."P" = __i2idn ( /_ UNAME as sqlval _/ __bft ( 'http://www.w3.org/2003/01/geo/wgs84_pos#asWKT' , 1))) AS "s_1_4_t1"
  ON ( /_ two fields belong to same equiv _/ 
    /_retval[_/ "s_1_4_t0"."O" /_ g _/ /_]retval_/  = /_retval[_/ "s_1_4_t1"."7359bf7e~S" /_ g _/ /_]retval_/ )
WHERE /_ field equal to URI ref _/ 
  "s_1_4_t0"."P" = __i2idn ( /_ UNAME as sqlval */ __bft ( 'http://www.w3.org/2003/01/geo/wgs84_pos#hasGeometry' , 1))
OPTION (QUIETCAST)
```
There is a condition `(1 = 2)` in `WHERE` clause, indicating `invalidated freetext or spatial predicate` (the second one in this case).

The query plans of this SPARQL query in those two versions of Virtuoso are a little bit different, and in the current version, we don't have this invalid condition is SQL translation, but we have more appropriate error message.

Best Regards,
Mirko

**Comment by Polymathronic** [comment]
@HughWilliams Oddly enough, it started working (on that same triple set & Virtuoso instance) after some performance tuning, meaning that, in certain cases, it can bypass the above check. Mirko had a look, and can confirm this, but we are both aware that pinpointing the exact cause might be much more difficult now (we moved to a different version in the meantime). Thanks both, though.
