### ISSUE TITLE
Error when using "drop silent graph" Virtuoso 7.2.2.1

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#541]
When using:
drop silent graph http://crux.bmi.stonybrook.edu/tcga/2016-03-16
on a named graph that is ~15 million triples, via the sparql-auth endpoint, the browser hangs for a while and then returns:

---

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /sparql-auth.

Reason: Error reading from remote server

---

Weirdly, I would think the browser wouldn't hang since "silent" is included in the command.  On smaller graphs, the command works fine.  I can delete the ~15 million triple graph via conductor without issue though.

**Comment by HughWilliams** [comment]
Begin forwarded message:

**Comment by HughWilliams** [comment]
Hi Erich,

drop "silent" does not mean to silently drop but rather is a means of silently deleting graphs IRIs that were not explicitly create with the "create graph ..." command, see:

http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtTipsAndTricksGuideCreateGraph
