### ISSUE TITLE
Variable used in result set group by but sparql compiler error claiming it is not.

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#546]
> VirtuosoException: SQ074: Line 16: SP031: SPARQL compiler: Variable ?range is used in the result set outside aggregate and not mentioned in GROUP BY clause

``` sparql
PREFIX up:<http://purl.uniprot.org/core/> 
SELECT ?range (COUNT(DISTINCT(?protein)) as ?entryWithInteraction)
WHERE
{
    VALUES ?range {5 10 15}
    {
       SELECT ?protein 
          WHERE{
            ?protein a up:Protein . 
            ?protein up:interaction ?interaction .
        } GROUP BY ?protein HAVING (COUNT(?interaction) > ?range && COUNT(?interaction) <= ?range + 5)
    }
} GROUP BY ?range
```

**Comment by HughWilliams** [comment]
@JervenBolleman: We are looking into this as unlike the previous query in git issue #498 the variable ?range is in the GROUP BY clause ...

**Comment by mirkospasic** [comment]
@JervenBolleman : 
Your query is a natural inner join of two fragments:

VALUES ?range {5 10 15}

and

SELECT ?protein 
          WHERE{
            ?protein a up:Protein . 
            ?protein up:interaction ?interaction .
        } GROUP BY ?protein HAVING (COUNT(?interaction) > ?range && COUNT(?interaction) <= ?range + 5)

So, you cannot know which one will be executed first, thus in the second fragment, variable ?range is not mentioned anywhere, and it is not bounded to 5, 10 or 15. The clause HAVING (COUNT(?interaction) > ?range && COUNT(?interaction) <= ?range + 5)
refers to variable ?range not mentioned in GROUP BY, thus the error message in question is appropriate here. The variable ?range is mentioned in the group by clause, but in the outer one, while in the inner one it is not. There are two possible queries that can be used here for your intention:

1.
PREFIX up:http://purl.uniprot.org/core/ 
SELECT ?range (COUNT(DISTINCT(?protein)) as ?entryWithInteraction)
WHERE
{
    {
       SELECT ?range ?protein 
          WHERE{
            VALUES ?range {5 10 15}
            ?protein a up:Protein . 
            ?protein up:interaction ?interaction .
        } GROUP BY ?range ?protein HAVING (COUNT(?interaction) > ?range && COUNT(?interaction) <= ?range + 5)
    }
} GROUP BY ?range

2.
PREFIX up:http://purl.uniprot.org/core/ 
SELECT ?range, (COUNT(DISTINCT(?protein)) as ?entryWithInteraction)
WHERE
{
    {
       SELECT ?protein COUNT(?interaction) as ?cnt
          WHERE{
            ?protein a up:Protein . 
            ?protein up:interaction ?interaction .
        }
    GROUP BY ?protein
    }
}
group by ((?cnt-1)/5*5 as ?range)
having (?range in (5, 10, 15))

**Comment by JervenBolleman** [comment]
@mirkospasic 
I thought the values clause needs to be executed before what follows as it closes a BGP. Much like a BIND.
e.g. as in this example

``` sparql
PREFIX up:<http://purl.uniprot.org/core/> 
SELECT ?range (COUNT(DISTINCT(?protein)) as ?entryWithInteraction)
WHERE
{
    BIND (5 AS ?range)
    {
       SELECT ?protein 
          WHERE{
            ?protein a up:Protein . 
            ?protein up:interaction ?interaction .
        } GROUP BY ?protein HAVING (COUNT(?interaction) > ?range && COUNT(?interaction) <= ?range + 5)
    }
} GROUP BY ?range
```

**Comment by mirkospasic** [comment]
@JervenBolleman 
That is true, but only if the VALUES clause is in the same fragment (our first solution). In your case, you never know. This is semantics, but your subquery should be syntactically correct itself, but that is not a case.

**Comment by JervenBolleman** [comment]
Ah its the left bound of subquery evaluation tricking me up here. The subquery is evaluated before the main body in sparql.

**Comment by JervenBolleman** [comment]
But then this is not the result I would expect.
http://sparql.uniprot.org/sparql/?format=html&query=PREFIX+up%3A%3Chttp%3A%2F%2Fpurl.uniprot.org%2Fcore%2F%3E+%0D%0ASELECT+%3Frange+%28COUNT%28DISTINCT%28%3Fprotein%29%29+as+%3FentryWithInteraction%29%0D%0AWHERE%0D%0A%7B%0D%0A+++++++SELECT+%3Frange+%3Fprotein+%0D%0A++++++++++WHERE%7B%0D%0A++++++++++++VALUES+%3Frange+%7B0+5+10+15+20+25+30+35+40+45+50+55+60+65+70+75+80+85+90+95+100%7D%0D%0A++++++++++++%3Fprotein+a+up%3AProtein+.+%0D%0A++++++++++++%3Fprotein+up%3Ainteraction+%3Finteraction+.%0D%0A++++++++%7D+GROUP+BY+%3Frange+%3Fprotein+HAVING+%28COUNT%28%3Finteraction%29+%3E+%3Frange+%26%26+COUNT%28%3Finteraction%29+%3C%3D+%3Frange+%2B+5%29%0D%0A++++%0D%0A%7D+GROUP+BY+%3Frange

``` sparql
PREFIX up:<http://purl.uniprot.org/core/> 
SELECT ?range (COUNT(DISTINCT(?protein)) as ?entryWithInteraction)
WHERE
{
       SELECT ?range ?protein 
          WHERE{
            VALUES ?range {0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100}
            ?protein a up:Protein . 
            ?protein up:interaction ?interaction .
        } GROUP BY ?range ?protein HAVING (COUNT(?interaction) > ?range && COUNT(?interaction) <= ?range + 5)

} GROUP BY ?range
```

gives just one result line

**Comment by JervenBolleman** [comment]
This gives 1

``` sparql
PREFIX up:<http://purl.uniprot.org/core/> 
SELECT ?range (COUNT(DISTINCT(?protein)) as ?entryWithInteraction)
WHERE
{
       SELECT ?range ?protein 
          WHERE{
             VALUES (?range) {(5)}
            ?protein a up:Protein . 
            ?protein up:interaction ?interaction .
        } GROUP BY ?range ?protein HAVING (COUNT(?interaction) > ?range)

} GROUP BY ?range
```

this gives some too

``` sparql
PREFIX up:<http://purl.uniprot.org/core/> 
SELECT ?range (COUNT(DISTINCT(?protein)) as ?entryWithInteraction)
WHERE
{
       SELECT ?range ?protein 
          WHERE{
             VALUES (?range) {(10)}
            ?protein a up:Protein . 
            ?protein up:interaction ?interaction .
        } GROUP BY ?range ?protein HAVING (COUNT(?interaction) > ?range)

} GROUP BY ?range
```

this gives no results

``` sparql
PREFIX up:<http://purl.uniprot.org/core/> 
SELECT ?range (COUNT(DISTINCT(?protein)) as ?entryWithInteraction)
WHERE
{
       SELECT ?range ?protein 
          WHERE{
             VALUES (?range) {(5) (10)}
            ?protein a up:Protein . 
            ?protein up:interaction ?interaction .
        } GROUP BY ?range ?protein HAVING (COUNT(?interaction) > ?range)

} GROUP BY ?range
```

**Comment by mirkospasic** [comment]
I have downloaded the dataset in question from your data store, and run all the queries you mentioned. For me, everything is OK.
The first query:
0 - 15616
5 - 1304
10 - 452
15 - 195
20 - 116
25 - 77
30 - 50
35 - 42
40 - 22
45 - 20
50 - 19
55 - 9
60 - 8
65 - 10
70 - 4
75 - 4
80 - 3
85 - 3
90 - 2
95 - 4
100 - 4
The second query:
5 - 2374
The third query: 
10 - 1070
The fourth query:
5 - 2374
10 - 1070

I guess that we use different versions. Try to do the same with the newest version of open source Virtuoso.

**Comment by JervenBolleman** [comment]
The values thing is probably fixed in your version as that looks like it is actually issue #539
