### ISSUE TITLE
develop/7: Install on Ubuntu

### ISSUE THREAD

**Issue by schweigerd** [openlink/virtuoso-opensource#55]
Hello!

I am trying to install the branch develop7 locally on a ubuntu 13.04 32 bit, but i cant get it to work.

This is what i did:
1. Download zip from here. Branch develop/7
2. read the readme from here.
3. ran ./autogen.sh from root folder, no errors (installed dependencies previously)
   -> "Bootstrap script completed successfully".
4. ran ./configure  then make then make install
 ./configure:

```
Virtuoso Open Source Edition (Column Store) 7.0.0-rc2 configuration summary
===========================================================================

Installation variables
  layout                  default
  prefix                  /usr/local/virtuoso-opensource
  exec_prefix             ${prefix}

Installation paths
  programs                ${exec_prefix}/bin
  include files           ${prefix}/include
  libraries               ${exec_prefix}/lib
  manual pages            ${datarootdir}/man
  vad packages            ${datarootdir}/virtuoso/vad
  database                ${prefix}/var/lib/virtuoso/db
  hosting                 ${exec_prefix}/lib/virtuoso/hosting

Options
  BUILD_OPTS               xml ssl imsg pldebug pthreads
```

make:

```
=  CREATING VAD PACKAGE FOR VIRTUOSO CONDUCTOR (mkvad.sh)
=  Tue Jun 4 15:52:39 CEST 2013

cp: omitting directory 'images/dav_browser'
cp: omitting directory 'images/icons'
cp: omitting directory 'help'
cp: omitting directory 'images'
cp: omitting directory 'syntax'
cp: omitting directory 'vad'
cp: cannot stat '/home/ds/Downloads/virtuoso-opensource-develop-7/binsrc/oat/toolkit/images/*': No such file or directory
VAD Sticker vad_fs.xml creation...
VAD Sticker vad_dav.xml creation...
Starting Virtuoso server ...
The VDBMS server process terminated prematurely
after opening the database.
***FAILED: Could not start Virtuoso Server within 120 seconds
make[2]: *** [conductor_dav.vad] Error 1
make[2]: Leaving directory `/home/ds/Downloads/virtuoso-opensource-develop-7/binsrc/yacutia'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ds/Downloads/virtuoso-opensource-develop-7/binsrc'
make: *** [all-recursive] Error 1
```
1. make install:

```

Making install in .
make[1]: Entering directory `/home/ds/Downloads/virtuoso-opensource-develop-7'
make[2]: Entering directory `/home/ds/Downloads/virtuoso-opensource-develop-7'
make[2]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/usr/local/virtuoso-opensource/share/virtuoso/doc'
/bin/mkdir: cannot create directory ‘/usr/local/virtuoso-opensource’: Permission denied
make[2]: *** [install-dist_docDATA] Error 1
make[2]: Leaving directory `/home/ds/Downloads/virtuoso-opensource-develop-7'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/ds/Downloads/virtuoso-opensource-develop-7'
make: *** [install-recursive] Error 1

```

any help appreciated :)

**Comment by larsga** [comment]
You need to run it as root.

**Comment by openlink** [comment]
On 4 June 2013 14:59, schweigerd notifications@github.com wrote:

> = CREATING VAD PACKAGE FOR VIRTUOSO CONDUCTOR (mkvad.sh) = Tue Jun 4
> 15:52:39 CEST 2013 cp: omitting directory 'images/dav_browser' cp: omitting
> directory 'images/icons' cp: omitting directory 'help' cp: omitting
> directory 'images' cp: omitting directory 'syntax' cp: omitting directory
> 'vad' cp: cannot stat
> '/home/ds/Downloads/virtuoso-opensource-develop-7/binsrc/oat/toolkit/images/_':
> No such file or directory VAD Sticker vad_fs.xml creation... VAD Sticker
> vad_dav.xml creation... Starting Virtuoso server ... The VDBMS server
> process terminated prematurely after opening the database. *__FAILED: Could
> not start Virtuoso Server within 120 seconds make[2]: *_*
> [conductor_dav.vad] Error 1 make[2]: Leaving directory
> `/home/ds/Downloads/virtuoso-opensource-develop-7/binsrc/yacutia' make[1]:
> **\* [all-recursive] Error 1

You need to fix this one first.
cd binsrc/yacutia
make
ls -sltr     (looking for logfiles)
less mkvad.output
see if you can find a reason why the server isn't starting. Do you have
another installation of Virtuoso running, perhaps from Ubuntu's packages?

## ~Tim

Tim Haynes
Product Development Consultant
OpenLink Software
http://www.openlinksw.com/
http://twitter.com/openlink

**Comment by schweigerd** [comment]
thanks tim and larsga.
I also tried running configure make and make install as root with the same result.

@tim: the mkvad.output contains the following:

```
*** Error S2801: [Virtuoso Driver]CL033: Connect failed to localhost:1111 = localhost:1111.
at line 0 of Top-Level:
```

I also do not have another version of virtuoso running.
Btw, i forgot to mention that i am running ubuntu on virtualbox. Could this cause problems??

Thanks for your help!

EDIT: Finally got it working on Mint 14. The problem was most likely a preinstalled Virtuoso 6.x, which was not uninstalled completely by me before trying to install version 7.

Thanks again.

**Comment by tim** [comment]
@schweigerd Please be aware that mentioning someone by username will notify that user and subscribe them to that thread (more info: https://github.com/blog/821).

**Comment by Kellli** [comment]
Dear schweigerd

I am facing exactly the same problem. How did you completely uninstalled Virtuoso 6? 

Thanks
Kelli
