### ISSUE TITLE
virtuoso.jdbc4.VirtuosoInputStream/convByte2UTF causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by fgiasson** [openlink/virtuoso-opensource#551]
I am using the latest version of the `[virt_sesame4.jar](https://github.com/openlink/virtuoso-opensource/tree/develop/7/binsrc/sesame4)` and I am getting this exception while getting results for a query:

```
3. Unhandled org.openrdf.query.QueryEvaluationException
2. Caused by virtuoso.jdbc4.VirtuosoException
1. Caused by java.lang.ArrayIndexOutOfBoundsException
   45

  VirtuosoInputStream.java:  325  virtuoso.jdbc4.VirtuosoInputStream/convByte2UTF
  VirtuosoInputStream.java:  158  virtuoso.jdbc4.VirtuosoInputStream/read_object
  VirtuosoInputStream.java:  492  virtuoso.jdbc4.VirtuosoInputStream/readRdfBox
  VirtuosoInputStream.java:  259  virtuoso.jdbc4.VirtuosoInputStream/read_object
  VirtuosoInputStream.java:   70  virtuoso.jdbc4.VirtuosoInputStream/read_object
  VirtuosoInputStream.java:   70  virtuoso.jdbc4.VirtuosoInputStream/read_object
  VirtuosoInputStream.java:   70  virtuoso.jdbc4.VirtuosoInputStream/read_object
   VirtuosoConnection.java:  482  virtuoso.jdbc4.VirtuosoConnection/read_request
       VirtuosoFuture.java:   55  virtuoso.jdbc4.VirtuosoFuture/nextResult
    VirtuosoResultSet.java:  215  virtuoso.jdbc4.VirtuosoResultSet/process_result
    VirtuosoResultSet.java:  857  virtuoso.jdbc4.VirtuosoResultSet/next
     ResultSetWrapper.java:   69  virtuoso.jdbc4.ResultSetWrapper/next
VirtuosoRepositoryConnection.java: 3166  virtuoso.sesame4.driver.VirtuosoRepositoryConnection$CloseableIterationBase/moveForward
VirtuosoRepositoryConnection.java: 3114  virtuoso.sesame4.driver.VirtuosoRepositoryConnection$CloseableIterationBase/hasNext
     IterationWrapper.java:   68  info.aduna.iteration.IterationWrapper/hasNext
                 query.clj:  270  cognonto-rdf.query/bindings->sparql-edn-seq/fn
```

One of the problem I see is that the line numbers does not fit what I can see here:
- https://github.com/openlink/virtuoso-opensource/blob/ea51ed3b81a43250ed2e3cfa77ee6e0116388b4b/libsrc/JDBCDriverType4/virtuoso/jdbc2/VirtuosoInputStream.java

This problem occurs when I am creating a lazy sequence that convert Convert a TupleQueryResult (a set of bindings) into a SPARQL Results EDN structure. This happens when I all `.hasNext` on the TupleQueryResult object.

**Comment by fgiasson** [comment]
@smalinin I just noticed that I was looking at the code for the `jdbc2` library and not the `jdbc4` (does not appear to be on Git) so ignore my comment about the line numbers that doesn't fit.

I also tested with `virtjdbc4_1.jar` and the same occurs.

**Comment by smalinin** [comment]
What kind of JDBC version build did you use? It must be fixed in build 3.95.

**Comment by fgiasson** [comment]
@smalinin I tested the two `virtjdbc4_0.jar` and `virtjdbc4_1.jar` that I can find in the Virtuoso 7.2.2 release. I am not sure what the build 3.95 refers to, so please clarify.

**Comment by smalinin** [comment]
Run in console the next command:
    java -jar virtjdbc4.jar
You will get the next message:
OpenLink Virtuoso(TM) Driver with SSL support for JDBC(TM) Version 4.x [Build 3.95]

**Comment by fgiasson** [comment]
@smalinin Sorry?

**Comment by smalinin** [comment]
I have updated my comment, but I rechecked fix, it was related with bad unicode data and it may not fix your problem. So could you give some simple example: your query and some source triples?

**Comment by fgiasson** [comment]
@smalinin will do my best, but the code is in Clojure and not yet released. However, this happens with a specific "slice" of DBpedia with a specific query, so I will be able to send you the query, and hopefully the resultset from `isql` for that query (which should includes the triple that break the code)

should be able to get this by sometime this afternoon

**Comment by fgiasson** [comment]
@smalinin Here is the query:

```
select ?s ?p ?o
from <http://dbpedia.org>
where
{
  {
    select distinct ?s from <http://dbpedia.org> where
    {
       ?s <http://www.w3.org/2000/01/rdf-schema#label> ?o .
    }
    limit 2000
    offset 528000
  }
  optional {?s ?p ?o .}
  filter(?p in (<http://www.w3.org/2000/01/rdf-schema#label>))
}
```

and I attached the resultset returned by the _same_ Virtuoso server but via the sparql endpoint web interface:
- [virtuoso_issue_no551.zip](https://github.com/openlink/virtuoso-opensource/files/217490/virtuoso_issue_no551.zip)

**Comment by fgiasson** [comment]
@smalinin any news on that?

**Comment by smalinin** [comment]
I was busy a little. Please run your test app(with test query) with using the attached JDBC driver version in Console. It will give the detailed info for exception above and send me the results.
[virtjdbc4.jar.zip](https://github.com/openlink/virtuoso-opensource/files/231381/virtjdbc4.jar.zip)
I added the next code to method onvByte2UTF()  for print details:

```
      } catch(ArrayIndexOutOfBoundsException ex) {
        System.out.println("==================================");
        System.out.println(ex);
        System.out.println("=======STACK TRACE  ===============");
        ex.printStackTrace();
        System.out.println("==================================");
        System.out.println("==Input Data==");
        System.out.print("Len="); System.out.println(data.length);
        System.out.print("Data=[");
        System.out.print(new String(Bin2HexArr(data, 0, data.length)));
        System.out.println("]");
        System.out.println("==Output Data==");
        System.out.print("ch_count="); System.out.println(ch_count);
        System.out.print("Data=[");
        for(int i=0; i<c_arr.length&& i<ch_count; i++)
          System.out.print(c_arr[i]);
        System.out.println("]");
        System.out.println("==================================");
        throw ex;
      }
```

**Comment by fgiasson** [comment]
@smalinin good! Testing it right now, but I probably won't be able to send you the results until next Monday (leaving soon for the weekend).

But right now, I think it didn't break where it did last time. Have you changed anything else in this code? I am processing the entities 824000/12000000 and it was breaking at 528000 before and nothing changed for that dataset.

Any thoughts?

**Comment by smalinin** [comment]
May be(I am not sure, it must already in your binary):   The `count++;` was added( look below)
for convByte2UTF()

```
                default:
                    /* 10xx xxxx,  1111 xxxx */
+                    count++;
                    c_arr[ch_count++] = bad_char;
/**
                    throw new UTFDataFormatException("malformed input around byte " + count);
**/
```

**Comment by fgiasson** [comment]
@smalinin ok, maybe so, but I didn't receive that exception neither, so hard to say :)

Could you send me what you consider the latest version of the `virtjodbc` and `virt-sesame` and I will make sure to use both of them in conjunction and then I will retest the whote process again to see if I still can reproduce this issue or not.

**Comment by smalinin** [comment]
The Virtuoso JDBC jar (in Git) were updated 5 days ago and it is contained all needed updates for you. The latest fix(that isn't in Git else) was for SSL connection support, so it isn't actual for you. But you could try it 
[virtjdbc4.jar.zip](https://github.com/openlink/virtuoso-opensource/files/236325/virtjdbc4.jar.zip)
[virtjdbc4ssl.jar.zip](https://github.com/openlink/virtuoso-opensource/files/236326/virtjdbc4ssl.jar.zip)
The Sesame providers weren't updated in the last time and you could found last jar files in Git.
You could check Virtuoso JDBC and Sesame  build_id via cmd: 

`java -jar virtjdbc4.jar`
`java -jar virt_sesame4.jar`

JDBC latest build in Opensouce git is =>3.95  (The attached JDBC has build_id = 3.97)
Sesame4 provider latest build_id is => 0.3

**Comment by fgiasson** [comment]
@smalinin great thanks, will try these tomorrow.

**Comment by fgiasson** [comment]
@smalinin, here is what I am using: 
- virtodbc: `OpenLink Virtuoso(TM) Driver for JDBC(TM) Version 4.0 [Build 3.97]`
- virt-sesame: `OpenLink Virtuoso(TM) Provider for Sesame4(TM) Version 4.0.0 [Build 0.3]`

Will tell you if I can re-produce this bug with these versions once I finished to process the 12M items.

**Comment by fgiasson** [comment]
@smalinin everything appears to be working normally with these two versions. I will close for now and re-open if this ever happen again thanks!

**Comment by smalinin** [comment]
Could you clear, if everything works properly for you now? If, yes, I will close this issue.

**Comment by smalinin** [comment]
Ok
