### ISSUE TITLE
Migrating latest Virtuoso Sesame drivers to RDF4J?

### ISSUE THREAD

**Issue by fgiasson** [openlink/virtuoso-opensource#560]
The sesame team announced the release of the first RDF4J library which is a clone of the Sesame version 4.1.2 and which will replace the Sesame project going forward.

I was wondering if it was in the plans to create a new Virtuoso driver for RDF4J? It should be straightforward to do since it is the same with same changes in the namespaces.

Here is the migration guide: http://rdf4j.org/doc/sesame-to-rdf4j-migration-guide/

Thanks

**Comment by fgiasson** [comment]
@smalinin I would like to know your assessment of this task (should it be as simple as changing the namespaces references?)

Also, is all the code related to this task available from here: https://github.com/openlink/virtuoso-opensource/tree/develop/7/binsrc/sesame4

**Comment by smalinin** [comment]
Thanks for note, I will prepare update for this on next week. All sources are in place.

**Comment by fgiasson** [comment]
@smalinin ok great, as soon as it is available I will update my codebase accordingly and run the unit tests to make sure everything is allright

**Comment by fgiasson** [comment]
@smalinin Do you think you will get to this early in the week or later?

Also looking at /binsrc/sesame4

There is just a "Makefile.am" file (no configurate.in or whatever), what are you using and what are the commands you normally run to compile that library?

**Comment by smalinin** [comment]
Try this new jar, note I executed only an initial test, it worked for me.
[virt_rdf4j.jar.zip](https://github.com/openlink/virtuoso-opensource/files/293160/virt_rdf4j.jar.zip)
The 'Makefile' is created from 'Makefile.am', when you run 'configure' script for prepare the build of Virtuoso DBMS server.

**Comment by smalinin** [comment]
New package name  is `virtuoso.rdf4j.driver.*`

**Comment by fgiasson** [comment]
@smalinin wonderful thanks! I will test that in a few minutes, we will be clear if I encounter any issues after I ran my tests suites. Will keep you updated.

**Comment by fgiasson** [comment]
@smalinin also, is it something that will make it to: https://github.com/openlink/virtuoso-opensource/tree/develop/7/binsrc ?

**Comment by fgiasson** [comment]
@smalinin everything is working as expected thanks!
