### ISSUE TITLE
Incorrect dateTime in ODBC

### ISSUE THREAD

**Issue by pchampin** [openlink/virtuoso-opensource#561]
I'm using Virtuoso open-source edition 07.20.3217 , and accessing it through ODBC.

When I run the following query:

``` sparql
SPARQL insert { graph <http://champin.net/2016-06-28-test1> { [] rdfs:label "2016-06-28T10:17:24.567"^^xsd:dateTime } }
```

and then get it back with

``` sparql
SPARQL select ?o { graph <http://champin.net/2016-06-28-test1> { ?s ?p ?o } }
```

I get the following invalid timestamp: `2016-06-28 138:17:24.567` (notice the value 138 for hours...).

Note that when I run the same `select` query in the SPARQL endpoint, I get the correct result, so the data seems to be correctly stored, the problem seems to be in the ODBC interface.

**Comment by HughWilliams** [comment]
@pchampin:

I don't see a problem with the direct ODBC interface:

```
SQL> SPARQL insert { graph <http://champin.net/2016-06-28-test1> { [] rdfs:label "2016-06-28T10:17:24.567"^^xsd:dateTime } };

Done. -- 83 msec.
SQL> SPARQL select ?o { graph <http://champin.net/2016-06-28-test1> { ?s ?p ?o } };
o
LONG VARCHAR
_______________________________________________________________________________

2016-06-28 10:17:24.567

1 Rows. -- 6 msec.
SQL> quit;
Hughs-MBP-2:~ hwilliams$ iodbctest "DSN=Local Virtuoso;UID=dba;PWD=dba"
iODBC Demonstration program
This program shows an interactive SQL processor
Driver Manager: 03.52.0815.0106
Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver (virtodbc.so)

SQL> SPARQL select ?o { graph <http://champin.net/2016-06-28-test1> { ?s ?p ?o } }

o                             
------------------------------
2016-06-28 10:17:24.567       

 result set 1 returned 1 rows.


SQL>
```

What exactly is the ODBC interface you are using i.e. PHP, Perl, Python or other ?

Note also if you upgraded your binary form 3214 to 3217 as indicated in the other git issue and are still using the existing database, then you need to be aware for the datetime changes  to support timezone-less dates in Virtuoso since 3214+ as detailed at , http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtTimezoneLessDateTime ... but if your original database was 3214 the it should have this new feature

Also, when you upgraded you Virtuoso server side to 3214 was the Virtuoso ODBC Client also updated ad there was an update in the ODBC Driver in the 7.2.2 ( 3215 ) update ...

**Comment by pchampin** [comment]
I'm using a fresh database, so the problem does not come from that.

I encountered the bug with Python, and reproduced it through `isql` (from package unixODBC 2.3.1).

I just tested it with `isql-vt` as provided by Virtuoso, and indeed, I don't reproduce the problem there...

So the problem is between Virtuoso and `libodbc1` (used by both the Python ODBC implementation and `isql`). I'm using `libodbc1:amd64 2.3.1-4.1` in Ubuntu 16.04 . Could this have to do with the Virtuoso's SPARQL extensions in ODBC?

**Comment by HughWilliams** [comment]
@pchampin: Will have to check with development if the Virtuoso ODBC RDF Extensions for SPASQL (http://docs.openlinksw.com/virtuoso/odbcimplementation.html#odbcimplementationext) could be the possible cause, as they are some specific extension of date types.

You could also try linking Python against iODBC as detailed at, http://www.iodbc.org/dataspace/iodbc/wiki/iODBC/IODBCPythonHOWTO

**Comment by HughWilliams** [comment]
@pchampin: Please confirm the version of the Virtuoso ODBC Driver your DSN is pointing to with its "Driver = .../virtodbc_r.so" param using the command:

```
$ strings virtodbc_r.so | grep 07.20
07.20.3217
07.20.3217 OpenLink Virtuoso ODBC Driver
$
```

And as indicated previously you must be using this latest driver (or at least 3215+) and not an earlier version ...

**Comment by pchampin** [comment]
Actually, I have a much older version of that lib:

```
Version 06.01.3127 as of Thu Dec 24 17:24:19 UTC 2015.
```

which is the version available in the repositories of the latest Ubuntu (16.04).
Generating deb packages from the source, and installing them, solves the problem in Python, but makes `isql` crash... :-/

**Comment by HughWilliams** [comment]
@pchampin: Glad to hear the rebuild with the latest Virtuoso ODBC Client resolved the problem.  `isql` is the UnixODBC  Interactive SQL client program, which there team should look into why it is crashing , especially if it works in Python ...
