### ISSUE TITLE
geosparql: support for orther projections

### ISSUE THREAD

**Issue by bertvannuffelen** [openlink/virtuoso-opensource#562]
Hi,

I have a point "POINT (78022.09 168725.84)" which should be interpreted w.r.t. projection
http://spatialreference.org/ref/epsg/belge-1972-belgian-lambert-72/.

I found the st_transform function which I believe can be used (based on the information found on the projection page) to transform all points to the usual wgs84 coordinates.

SELECT ?geo ?p ?pt 
WHERE
  {
    ?href  
          http://www.opengis.net/ont/geosparql#hasGeometry ?geo.
    ?geo http://www.opengis.net/ont/geosparql#asWKT ?p.
    bind(bif:st_transform(?p, "EPSG", "+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=106.869,-52.2978,103.724,-0.33657,0.456955,-1.84218,1 +units=m +no_defs","") as ?pt)  
  }
LIMIT 100

however Virtuoso complains that the bif:st_transform function is not present.

Any suggestion on what is wrong?

kr
Bert

**Comment by HughWilliams** [comment]
Hi Bert,

st_transform requires the Virtuoso  v7proj4 hosted plugin module , which is required to perform such transformations, see: 

   http://docs.openlinksw.com/virtuoso/sqlrefgeospatial.html#sqlrefgeospatial7enchanceplg
   http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtGeoSPARQLEnhancementDocs#Open Source v7proj4 Plug-in

but is not part of the current open source or commercial v7 releases, although is part of the special "v7fasttrack"  development branch as indicated in the documentation, where you can built and tested from.

It will be part of the upcoming Virtuoso 8 release ...

Regards
Hugh

**Comment by bertvannuffelen** [comment]
Hi Hugh,

thanks for the insight.

kr,

Bert
