### ISSUE TITLE
Illegal RDF/XML returned

### ISSUE THREAD

**Issue by LorenzBuehmann** [openlink/virtuoso-opensource#567]
Problem with illegal character in returned RDF/XML data:
## SPARQL Endpoint

http://dbpedia.org/sparql
(Virtuoso version 07.20.3217 on Linux (i686-generic-linux-glibc212-64), Single Server Edition)
## Query:

```
CONSTRUCT {
?s0 ?p0 <http://dbpedia.org/resource/Nepal>.
} WHERE {
?s0 ?p0 <http://dbpedia.org/resource/Nepal>.
}
```

[Click](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=CONSTRUCT+%7B%0D%0A%3Fs0+%3Fp0+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FNepal%3E.%0D%0A%7D%0D%0AWHERE+%7B%0D%0A%3Fs0+%3Fp0+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FNepal%3E.%0D%0A%7D&format=text%2Fturtle&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on)
## Results Format:

RDF/XML
## Error Line

[line: 18117, col: 15]
`<dbp:birth°place rdf:resource="http://dbpedia.org/resource/Nepal" />`

**Comment by openlink** [comment]
I have alerted the dbpedia team as this is clearly a bad property.

Nevertheless Virtuoso should use the long form for this url, so i will speak with the development team about a fix.

**Comment by LorenzBuehmann** [comment]
Ok, didn't know that this happened during loading. Thank you!

**Comment by HughWilliams** [comment]
This problem no longer occurs it seems .. pleas check to confirm ...

**Comment by TallTed** [comment]
@LorenzBuehmann - Are you able to confirm whether this issue has been resolved, as we believe it has, so we may mark it closed?

**Comment by LorenzBuehmann** [comment]
Can be closed, I'd say - prefixed IRIs now only will be used when there is no non-alpha-numeric character.
