### ISSUE TITLE
Illegal Turtle returned for SPARQL CONSTRUCT query

### ISSUE THREAD

**Issue by LorenzBuehmann** [openlink/virtuoso-opensource#569]
Problem with illegal character in returned Turtle data:
(Similar to issue #567 , i.e. a prefixed URI contains a character which is only allowed in long form)
## SPARQL Endpoint

http://dbpedia.org/sparql
(Virtuoso version 07.20.3217 on Linux (i686-generic-linux-glibc212-64), Single Server Edition)
## Query:

```
CONSTRUCT {
<http://dbpedia.org/resource/Oleg_Novitskiy> ?p0 ?o0.
} WHERE {
<http://dbpedia.org/resource/Oleg_Novitskiy> ?p0 ?o0.
}
```

[Click](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=CONSTRUCT+%7B%0D%0A%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FOleg_Novitskiy%3E+%3Fp0+%3Fo0.%0D%0A%7D%0D%0AWHERE+%7B%0D%0A%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FOleg_Novitskiy%3E+%3Fp0+%3Fo0.%0D%0A%7D&format=text%2Fturtle&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on)
## Results Format:

Turtle
## Error Line

[line: 35, col: 15] 

```
33 dbr:Oleg_Novitskiy   dbp:birthPlace  dbr:Belarus ,
34      dbr:Minsk_Region ,
35      dbr:Chervyen’ .
```

See the resource `dbr:Chervyen’` which contains a `’` at the end, which is not allowed in prefixed URIs.

**Comment by openlink** [comment]
Same problem as the other issue you logged. We should have a fix soon.

**Comment by TallTed** [comment]
@LorenzBuehmann - Are you able to confirm whether this issue has been resolved, as we believe it has, so we may mark it closed??

**Comment by LorenzBuehmann** [comment]
Well, I can just say that for the DBpedia endpoint it returns URI encoded valid Turtle now. For the example above it omits prefixed URIs now and returns instead

```
dbr:Oleg_Novitskiy	owl:sameAs	dbpedia-wikidata:Q963226 ;
	dbo:birthPlace	<http://dbpedia.org/resource/Chervyen\u2019> ,
		dbr:Minsk_Voblast ,
		<http://dbpedia.org/resource/\u010Cervie\u0144> ,
		dbr:Belarus .
```
From my side, feel free to close the ticket (clearly I'm not able to say "yes", the Turtle serializer now always does use full IRIs when non alpha-numeric characters occur, but looks like)

The same holds for the other RDF/XML related ticket - was basically the same issue with prefixed IRIs.

Cheers and thanks for fixing it.
