### ISSUE TITLE
Error 42000 SR186:SECURITY: No permission to execute procedure DB.DBA.EXEC_AS with user ID 107, group ID 107   

### ISSUE THREAD

**Issue by arnikz** [openlink/virtuoso-opensource#573]
Hi,
I wanted to "sponge" some RDF content via GUI (Virtuoso Facets Web Service, Virtuoso 07.20.3217) but got this error message. I have _rdf_mappers.vad__ package installed (v1.34.74, compiled from sources). Also granted SPARQL user SPARQL_SELECT, SPARQL_SPONGE and SPARQL_UPDATE permissions but it did not help. After some searching I found that DB.DBA.EXEC_AS procedure does not even exist in the main DB. Could you please help? Thanks.

**Comment by HughWilliams** [comment]
@arnikz: user ID 107 is most probably the ID of the "SPARQL" user to which execute privileges need to be granted on the DB.DBA.EXEC_AS procedure, which is probably a built-in function and this not listed in the DB schema, with the command:

```
   grant execute on "DB.DBA.EXEC_AS" to "SPARQL";
```

**Comment by arnikz** [comment]
@HughWilliams: yep, this one solved the problem! Thanks.
