### ISSUE TITLE
encode_base64 - Strange behavior

### ISSUE THREAD

**Issue by dans-er** [openlink/virtuoso-opensource#576]
It seems the function `encode_base64 ( in str varchar );` gives strange results. Example:

```
SQL> select encode_base64('http://www.telegraphis.net/ontology/geography/geography#');
encode_base64
VARCHAR
_______________________________________________________________________________

aHR0cDovL3d3dy50ZWxlZ3JhcGhpcy5uZXQvb250b2xvZ3kvZ2VvZ3JhcGh5L2dlb2dyYXBo
eSM=

1 Rows. -- 4 msec.
```

The new line is inclusive. On Unix I get:

```
aHR0cDovL3d3dy50ZWxlZ3JhcGhpcy5uZXQvb250b2xvZ3kvZ2VvZ3JhcGh5L2dlb2dyYXBoeSMK
```

which seems more appropriate.

My version of Virtuoso:
Version 07.10.3211-pthreads for Linux as of Apr  3 2015

**Comment by HughWilliams** [comment]
How are you calling this on Unix ?

**Comment by dans-er** [comment]
How I call it on Unix?

```
# echo 'http://www.telegraphis.net/ontology/geography/geography#' | base64                                                          
aHR0cDovL3d3dy50ZWxlZ3JhcGhpcy5uZXQvb250b2xvZ3kvZ2VvZ3JhcGh5L2dlb2dyYXBoeSMK
```

Later on I learned that also Unix/Linux base64 program is putting line breaks after a certain amount of characters, unless you specify the `-w` or `--wrap` option and give it a value of `0`.

I need this function to get suitable directory names for graphs I'm exporting.

So the issue doesn't seem to indicate a bug, only a shortcoming: you cannot use encode_base64 to get URL-safe translations.

**Comment by HughWilliams** [comment]
OK, we shall look into this ...

**Comment by HughWilliams** [comment]
Development indicate the test should be:

```
echo -n 'http://www.telegraphis.net/ontology/geography/geography#' | base64
```

which produces same as the Virtuoso function:

```
$ echo -n 'http://www.telegraphis.net/ontology/geography/geography#' | base64
aHR0cDovL3d3dy50ZWxlZ3JhcGhpcy5uZXQvb250b2xvZ3kvZ2VvZ3JhcGh5L2dlb2dyYXBoeSM=
```
