### ISSUE TITLE
Error 42001: [Virtuoso Driver][Virtuoso Server]SR185: Undefined procedure DB.DBA.ft_set_file.

### ISSUE THREAD

**Issue by arnikz** [openlink/virtuoso-opensource#584]
Hi, 

The following command documented [here](http://docs.openlinksw.com/virtuoso/sqlbulkloadoperationsftable/) does not seem to work for me:

<pre>
ft_set_file('MYDATA', '/home/mydata.tsv', delimiter => '\t');
</pre>

My Virtuoso OSE version is 07.20.3217. Any suggestions? Thanks.

**Comment by HughWilliams** [comment]
@arnikz: This is a commercial only feature and this not available in open source ...

**Comment by arnikz** [comment]
Thanks @HughWilliams. Is there maybe another way to batch load tab-delimited files into Virtuoso RDB?

**Comment by HughWilliams** [comment]
@arnikz: Yes, there is a CSV bulk loader that works with open or closed source builds, detailed at:

   http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtCsvFileBulkLoader

**Comment by arnikz** [comment]
@HughWilliams: Thanks.
