### ISSUE TITLE
Bad hardware led to V7.2 crash with row with bad kv in RDF_IRI 

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#586]
We had a crash with the following log messages

```
16:20:22 row with bad kv in RDF_IRI
16:20:22 ./virtuoso-t() [0xac7092]
16:20:22 ./virtuoso-t() [0xac711d]
16:20:22 ./virtuoso-t() [0x52ed6d]
16:20:22 ./virtuoso-t() [0x4f21b1]
16:20:22 ./virtuoso-t() [0x4a1722]
16:20:22 ./virtuoso-t() [0x519cbc]
16:20:22 ./virtuoso-t() [0xad4f24]
16:20:22 /lib64/libpthread.so.0() [0x364ae079d1]
16:20:22 /lib64/libc.so.6(clone+0x6d) [0x364aae8b5d]
16:20:22 GPF: page.c:110 key with bad key version
GPF: page.c:110 key with bad key version
```

Leading to an crash = > Process /scratch/uuw_sparql/triples/main/2016_09/virtuoso-t was killed by signal 11 (SIGSEGV)

We have a coredump and other details and can provide them if desired.
.

**Comment by HughWilliams** [comment]
@JervenBolleman: If your open source binary is not stripped of symbols then a gdb back trace of the core would be useful to see  call leading up to the crash ...

**Comment by JervenBolleman** [comment]
@HughWilliams looks like an hardware failure is the cause of this error message. We will verify with the operational/hardware team. But I suspect this issue will be closed as dying disks is not something that virtuoso can guard against. Anyway the core dump was on the same disks so unlikely to be recovered.

**Comment by JervenBolleman** [comment]
Definitely bad hardware, closing issue as not something that dev can do anything about.
