### ISSUE TITLE
Virtuoso RDF4J Provider Test Failing

### ISSUE THREAD

**Issue by sdmonroe** [openlink/virtuoso-opensource#588]
Hi,

For VirtuosoTest.java Test 5 I added an IRI bind on a query variable [here](https://github.com/Vacuity/rudi-core/blob/master/src/main/test/ai/vacuity/rudi/adaptors/test/VirtuosoTest.java), starting at line 207. It throws this error:

```
org.eclipse.rdf4j.query.QueryEvaluationException: : SPARQL execute failed:[SELECT ?s FROM <http://demo.openlinksw.com/demo#this> WHERE {?s ?p ?o} LIMIT 1] 
 Exception:virtuoso.jdbc4.VirtuosoException: SQ074: Line 3: SP030: SPARQL compiler, line 3: syntax error at '`' before 'iri'
    at com.openlink.virtuoso.rdf4j.driver.VirtuosoRepositoryConnection.executeSPARQLForTupleResult(VirtuosoRepositoryConnection.java:1595)
    at com.openlink.virtuoso.rdf4j.driver.VirtuosoRepositoryConnection$1.evaluate(VirtuosoRepositoryConnection.java:350)
    at ai.vacuity.rudi.adaptors.test.VirtuosoTest.doTupleQuery(VirtuosoTest.java:566)
    at ai.vacuity.rudi.adaptors.test.VirtuosoTest.main(VirtuosoTest.java:214)
```

Somehow, the jdbc4 driver doesn't like the 'iri(??)' substitution taking place at VirtuosoRepositoryConnection.substBindings() line 1858. Has this been tested? If so, how do I remediate?

**Comment by smalinin** [comment]
The example link could not be opened, please recheck it or etc.

**Comment by sdmonroe** [comment]
Please try [this one](https://github.com/sdmonroe/virtuoso-opensource/blob/develop/7/binsrc/rdf4j/src/main/test/com/openlink/virtuoso/rdf4j/driver/test/VirtuosoTest.java) instead.

**Comment by smalinin** [comment]
The problem is related with handle `iri(??)` substitution on server side, shortly syntax `iri(??)` could be used only inside triple patterns, for another cases the iri(??) must be  used without backquotes. I will fix Provider for properly support it.

**Comment by sdmonroe** [comment]
Awesome, thanks!

**Comment by smalinin** [comment]
The draft version of fix is ready:

**Comment by smalinin** [comment]
I created patch and updated tests, it was sent, so it was in Git soon. 
Also I have attached the final version of patch, if you need it.
[patch.txt](https://github.com/openlink/virtuoso-opensource/files/533229/patch.txt)

**Comment by sdmonroe** [comment]
Perfect, many thanks!
