### ISSUE TITLE
Add Java-related extensions to Maven Central Repository

### ISSUE THREAD

**Issue by sdmonroe** [openlink/virtuoso-opensource#589]
Hi,

Currently, the Virtuoso Providers are not available in [Maven Central Repository](https://mvnrepository.com/), which makes team contributions to applications that use these providers cumbersome. Unless it is available in Maven Central, team members will need to fetch the related jars and add them manually to their local Maven repo. We would instead like to just add `<dependency>` tags for the Virtuoso Providers in the pom.xml file for our applications. Then team members just clone the project code and do `mvn clean install`, and they are set to start coding. I hope you can consider this.

[The process](https://maven.apache.org/guides/mini/guide-central-repository-upload.html) is pretty straight-forward. I am available to pitch in, and I have already Mavenized the RDF4J provider and made a [pull request](https://github.com/openlink/virtuoso-opensource/pull/587).

**Comment by nvdk** [comment]
:+1:

**Comment by pkleef** [comment]
OpenLink has published its Virtuoso JDBC drivers as well as its Jena and RDF4j providers to maven central:

https://community.openlinksw.com/t/openlink-virtuoso-java-artifacts-on-maven-central
