### ISSUE TITLE
VOS7: csv import issue

### ISSUE THREAD

**Issue by geokollias** [openlink/virtuoso-opensource#59]
After following the instructions [here](http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtCsvFileBulkLoader), i get that error:

```
SQL> csv_register('/home/user/Virtuoso/import-data', '*.csv');

Done. -- 1 msec.
SQL> csv_loader_run ();

*** Error 22023: [Virtuoso Driver][Virtuoso Server]SR022: Type for make_array must be float, double, long or any
at line 2 of Top-Level:
csv_loader_run ()
```

Any idea?

Thank you,
George

**Comment by imitko** [comment]
Hi George,

In the document there is a typo, the line --

    arr := make_array (100, 'ANY');

-- should be --

    arr := make_array (100, 'any');

-- i.e. lowercase string `'any'`. You could change the line and re-load the script. 

Best Regards,
Mitko

**Comment by geokollias** [comment]
It worked. Thanks!
