### ISSUE TITLE
Compile error with make

### ISSUE THREAD

**Issue by yilingjia** [openlink/virtuoso-opensource#594]
Hi virtuoso team,

Recently, I just want to install the whole virtuoso in my computer,. All thing is right when I do the git clone, ./autogen.sh(I use sh autogen.sh to fix the problem that the INSTALL file is missing) and ./configure. However, when I do the make, it comes out with the error:

```
make[3]: *** [libutil_la-getdate.lo] Error 1
make[3]: Leaving directory `/home/yj9xs/Documents/virtuoso-opensource/libsrc/util'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/yj9xs/Documents/virtuoso-opensource/libsrc/util'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/yj9xs/Documents/virtuoso-opensource/libsrc'
make: *** [all-recursive] Error 1
```

the version is tags/v7.0.0.

Then I found one issue [https://github.com/openlink/virtuoso-opensource/issues/160](url)
I change the branch to develop/7, and do the make, however, new errors just came out:

```
make[3]: *** No rule to make target 'mem.c', needed by 'libwi_la-mem.lo'.  Stop.
make[3]: Leaving directory '/home/yj9xs/Documents/virtuoso-opensource/libsrc/Wi'
Makefile:1120: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/yj9xs/Documents/virtuoso-opensource/libsrc/Wi'
Makefile:469: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/yj9xs/Documents/virtuoso-opensource/libsrc'
Makefile:594: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

So, what could I do to fix this problem? I really stock by it.

Thank you very much!

**Comment by HughWilliams** [comment]
have you check the require dependant packages for building on your OS are in place as detailed at http://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VOSMake  ?

**Comment by yilingjia** [comment]
@HughWilliams  
Seems I missed to set the CFLAGS before doing everything. And I have solved the problem by just reset the whole repository.

Thank you very much!
