### ISSUE TITLE
gawk 4.0 Seems To Break sql_to_c.awk

### ISSUE THREAD

**Issue by dMaggot** [openlink/virtuoso-opensource#6]
I'm using Virtuoso in Gentoo Unstable.After updating to 6.1.4-r1 it stopped working for the following query:

sparql select distinct ?r where { ?r http://www.semanticdesktop.org/ontologies/2007/08/15/nao#identifier "c8ae2fe2-0a63-429d-9ad4-b63a5fad8619"^^http://www.w3.org/2001/XMLSchema#string. } LIMIT 1

with an error on sparql.sql, line 770. I examined the sources and noticed that file is used to autogenerate another file using gawk, I checked my gawk installations and I installed gawk 4.0 on Feb 12 and Apr 28, after installing virtuoso-server 6.1.4 on Dec 11, but before installing virtuoso-server 6.1.4-r1 on May 16. I then downgraded my gawk to 3.1.8 and reinstalled virtuoso-server 6.1.4-r1 and it is working fine again.

The issue seems to be related to single quotes escaping but I couldn't get any info from gawk man pages about version 4.0 changes on that matter.

**Comment by openlink** [comment]
This problem started when the Gawk 4.0 maintainers changed from traditional regexp handling to POSIX handling as a default. A number of distros started shipping this version which unfortunately broke a lot of awk scripts including the ones in VOS.

I added a version check to distinguish between versions 3 and 4 to provide a fix. However as many people started to object to this sudden change of regexp handling, the maintainers rolled back that patch and distros started to ship the "fixed" version with the exact version number. 

Fortunately i found a better fix that works for both traditional and POSIX regexp handling which has been integrated in VOS 6.1.5. 

See also:

https://github.com/openlink/virtuoso-opensource/commit/b01c641b917485d0e23beb98787e43cb40baae8a
