### ISSUE TITLE
Create SPARQL endpoint via ISQL

### ISSUE THREAD

**Issue by migalkin** [openlink/virtuoso-opensource#604]
I have to create dozens of custom SPARQL endpoints in Virtuoso and assign a particular named graph to a particular endpoint. There is a Conductor GUI but I would not like to create endpoints manually. How do I create an endpoint (say, on port 8899) via Virtuoso ISQL command line?

In Virtuoso Conductor you can navigate to **Web Services → Virtual Directories** and create a new VHost with the SPARQL access point on this VHost. The problem is that it's done manually. I'm looking for a way to use `isql` commands to create them automatically.

Thanks.

**Comment by HughWilliams** [comment]
The Virtuoso [`DB.DBA.VHOST_DEFINE()` function](http://docs.openlinksw.com/virtuoso/fn_vhost_define/) can be used to manually create a SPARQL endpoint via `iSQL`.

If you create a sample endpoint via the Conductor **Web Services → Virtual Directories** tab, to the right of it you will see an **`export`** link. If you click on this, it will display the SQL commands used to create the vdir, for example:

```
DB.DBA.VHOST_DEFINE (
     lhost=>'*ini*',
     vhost=>'*ini*',
     lpath=>'/your-sparql-endpoint-name',
     ppath=>'/DAV/VAD/val/www/sparql/',
     is_dav=>1,
     is_brws=>0,
     def_page=>'sparql.vsp',
     vsp_user=>'dba',
     ses_vars=>0,
     opts=>vector ('browse_sheet', ''),
     is_default_host=>0
);
```

This function basically writes to the `DB.DBA.HTTP_PATH` & `DB.DBA.SYS_SPARQL_HOST` tables. See [**Manage Public Web Service Endpoints**](http://docs.openlinksw.com/virtuoso/rdfperfindexes/) for more details.

**Comment by migalkin** [comment]
Thank you very much, works perfectly!

**Comment by virtuosou** [comment]
Hi @HughWilliams Can you please help me to set an option 

> Map the logical path to a single page (Boolean) to true.

I did not see in isql function but i need to set it true manually from web page.
Thank you

**Comment by TallTed** [comment]
@virtuosou - Looks like you also [asked on StackOverflow](https://stackoverflow.com/questions/52050757/virtuoso-create-sparql-endpoint-via-isql-missing-option)...  I am researching, and expect to post answers here and there.

**Comment by timhaynesopenlink** [comment]
Hi, @virtuosou --

```
DB.DBA.VHOST_DEFINE (
	 lhost=>'*ini*',
	 vhost=>'*ini*',
	 lpath=>'/stuff',
	 ppath=>'/DAV/VAD/',
	 is_dav=>1,
	 is_brws=>0,
	 def_page=>'index.vsp',
	 vsp_user=>'dba',
	 ses_vars=>0,
	 opts=>vector ('browse_sheet', '', 'noinherit', 'yes'),
	 is_default_host=>0
);
```

You need to specify both the `def_page` and `'noinherit','yes'` options as above; the page will then be filled-in and the box will be checked.

Top tip: there's an **Export** button beside each vdir definition. :)

HTH

~Tim

**Comment by mhoangvslev** [comment]
The export button seems to be removed. Is there any other way to do this?

**Comment by HughWilliams** [comment]
What do you mean the `export button seems to be removed`, as it is in the same place it has always been checking the latest Virtuoso build:

<img width="1167" alt="Screenshot 2024-08-23 at 16 14 00" src="https://github.com/user-attachments/assets/e0b4ee01-e555-4276-8b7a-c6f8cccd029e">

**Comment by mhoangvslev** [comment]
For me, the UI has always been like this (I have only known virtuoso 7, but I never use the interface until today)

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/924b5151-fa54-42ea-9640-2fd9eab4f70c">

N.B: I use the docker version of virtuoso

**Comment by HughWilliams** [comment]
The fact that you are running on docker is not relevant, as the Virtuoso Conductor is generic across all platforms it runs on.

Why have you not clicked on the blue folder icon on the left to expand the HTTP `interface` to see the actual `virtual directories`, as I have done in my screenshot ???

**Comment by mhoangvslev** [comment]
This is actually funny as it flies right over my head; 😂 

First, I don't know what the icons mean, and the column name being another mystery icon doesn't really help. 

Second, when in doubt, don't click.
