### ISSUE TITLE
Turtle parser parses prefixed names as QNames

### ISSUE THREAD

**Issue by jamesamcl** [openlink/virtuoso-opensource#605]
The turtle parser appears to be attempting to parse Turtle prefixed names as XML QNames.  For example, when attempting to use a prefixed name starting with an integer in the local part (e.g. `taxonomy:1423` where `taxonomy` is the prefix `<http://identifiers.org/taxonomy>`), the following error is generated:

> SP029: TURTLE RDF loader, line 78: Invalid characters in local part of QName; this error can be suppressed by parser flags at taxonomy:1423

However, the [turtle specification](https://www.w3.org/TR/turtle/) clearly states that:

> Prefixed names are a superset of XML QNames. They differ in that the local part of prefixed names may include:
> leading digits, e.g. leg:3032571 or isbn13:9780136019701
>  non leading colons, e.g. og:video:height
> reserved character escape sequences, e.g. wgs:lat\-long

**Comment by HughWilliams** [comment]
What is your test case as the following works for me ?

```
SQL> sparql prefix taxonomy: <http://identifiers.org/taxonomy> select * where { taxonomy:1423 ?s ?p};
s                                                                                 p
LONG VARCHAR                                                                      LONG VARCHAR
_______________________________________________________________________________


0 Rows. -- 17 msec.
SQL>
```

**Comment by jamesamcl** [comment]
This doesn't affect SPARQL queries, only Turtle files.  Try submitting the following RDF/Turtle to a Virtuoso instance:

```
@prefix taxonomy: <http://identifiers.org/taxonomy/> .
@prefix ncbi:  <http://www.ncbi.nlm.nih.gov#> .

<foo> ncbi:taxid taxonomy:1423 .
```

**Comment by HughWilliams** [comment]
The following works for me also:

```
SQL> DB.DBA.TTLP_MT (file_to_string_output ('ncbi.ttl'), '', 'ncbi');

Done. -- 6 msec.
SQL> sparql select * from <ncbi> where {?s ?p ?o};
s                                                                                 p                                                                                 o
LONG VARCHAR                                                                      LONG VARCHAR                                                                      LONG VARCHAR
_______________________________________________________________________________

foo                                                                               http://www.ncbi.nlm.nih.gov#taxid                                                 http://identifiers.org/taxonomy/1423

1 Rows. -- 1 sec.
SQL> status('');
REPORT
VARCHAR
_______________________________________________________________________________

OpenLink Virtuoso  Server
Version 07.20.3217-pthreads for Darwin as of Sep 15 2016 
Started on: 2016-11-16 01:26 GMT+0

Hughs-MBP-2:database hwilliams$ cat ncbi.ttl 
@prefix taxonomy: <http://identifiers.org/taxonomy/> .
@prefix ncbi:  <http://www.ncbi.nlm.nih.gov#> .

<foo> ncbi:taxid taxonomy:1423 .
Hughs-MBP-2:database hwilliams$ 
```

Thus what is your Virtuoso server version ?

**Comment by jamesamcl** [comment]
> Version: 06.01.3127
> Build: Dec 24 2015

Sorry about that, looks like the version packaged in Ubuntu 16.04 is old.  I'll update...

**Comment by jamesamcl** [comment]
Confirm this works fine in 7.x.
