### ISSUE TITLE
Issue with SPARQL select query with an optional clause

### ISSUE THREAD

**Issue by jplu** [openlink/virtuoso-opensource#615]
Hi,

I'm using Virtuoso 7.2.4.2 on a Debian 9.

The issue concerns resources that are not retrieved by a select query whereas they should. I'm using this [SPARQL endpoint](http://3cixty.eurecom.fr/dbpedia) which contains a subpart of DBpedia with the dumps:

- anchor_text_en.ttl
- instance_types_en.ttl
- long_abstracts_en.ttl
- page_ids_en.ttl
- PageRank_scores_en_grph.ttl (generated by https://github.com/dineshreddykdp/JungGraphMeasures)
- disambiguations_en.ttl
- instance_types_transitive_en.ttl
- labels_en.ttl
- mappingbased_literals_en.ttl
- page_links_en.ttl
- redirects_en.ttl

If I do the following query:

```
SELECT distinct count(distinct ?s)
    FROM <http://dbpedia.org> WHERE {
        optional {
            ?s a ?type .
        }
        ?s <http://dbpedia.org/ontology/wikiPageRank> ?pr .
        ?s <http://dbpedia.org/ontology/wikiPageID> ?id .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageRedirects> ?x} .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageDisambiguates> ?y} .
    }
```

I get 3386942 resources. Now if I do this query:

```
SELECT distinct count(distinct ?s)
    FROM <http://dbpedia.org> WHERE {
        ?s a ?type .
        ?s <http://dbpedia.org/ontology/wikiPageRank> ?pr .
        ?s <http://dbpedia.org/ontology/wikiPageID> ?id .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageRedirects> ?x} .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageDisambiguates> ?y} .
    }
```

I get the exact same number of resources, 3386942. Which is wrong because there are resources without types in the KB, and then the number should be higher. As example, the resource ```http://dbpedia.org/resource/HC_CSKA_Moscow```, doesn't have types and then should appears among the results of the first query, which is not the case. Nevertheless, if I run the following query:

```
SELECT distinct count(distinct ?s)
    FROM <http://dbpedia.org> WHERE {
        optional {
            ?s a ?type .
        }
        ?s <http://dbpedia.org/ontology/wikiPageRank> ?pr .
        ?s <http://dbpedia.org/ontology/wikiPageID> ?id .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageRedirects> ?x} .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageDisambiguates> ?y} .
        filter (?s = <http://dbpedia.org/resource/HC_CSKA_Moscow>) .
    }
```
I get a result and if I remove the optional, I get 0 results which is the normal behavior. So, is there something wrong in my first query or there is an issue with the optional clause in Virtuoso?

**Comment by HughWilliams** [comment]
@jplu: In your last statement you said `if I remove the optional, I get 0 results` , but when I remove the optional clause it actually returns 1 row, see:

http://3cixty.eurecom.fr/dbpedia?default-graph-uri=&qtxt=SELECT+distinct+count%28distinct+%3Fs%29%0D%0A++++FROM+%3Chttp%3A%2F%2Fdbpedia.org%3E+WHERE+%7B%0D%0A%0D%0A++++++++%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageRank%3E+%3Fpr+.%0D%0A++++++++%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageID%3E+%3Fid+.%0D%0A++++++++filter+not+exists%7B%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageRedirects%3E+%3Fx%7D+.%0D%0A++++++++filter+not+exists%7B%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageDisambiguates%3E+%3Fy%7D+.%0D%0A++++++++filter+%28%3Fs+%3D+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FHC_CSKA_Moscow%3E%29+.%0D%0A++++%7D&format=text%2Fhtml&timeout=0&debug=on

Also, what DBpedia datasets are you using ? As there queries above returns no results when run against http://dbpedia.org/sparql , which has complete DBpedia 2016 datasets loaded, and thus should have the subset of datasets you loaded ...

**Comment by rtroncy** [comment]
Hi @HughWilliams. Thanks for the quick answer, the issue described by @jplu can actually be simplified. We are indeed using a local version where some dbpedia dumps have been loaded (see the [edited original issue description](https://github.com/openlink/virtuoso-opensource/issues/615#issue-195239995) for the details).

Look at this query which counts the number of unique resources which have a wikiPageRank, a wikiPageID, etc. There are [3386942 resources](http://3cixty.eurecom.fr/dbpedia?default-graph-uri=&query=SELECT+distinct+count%28distinct+%3Fs%29%0D%0A++++FROM+%3Chttp%3A%2F%2Fdbpedia.org%3E+WHERE+%7B%0D%0A++++++++optional+%7B+%3Fs+a+%3Ftype+.+%7D%0D%0A++++++++%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageRank%3E+%3Fpr+.%0D%0A++++++++%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageID%3E+%3Fid+.%0D%0A++++++++filter+not+exists%7B%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageRedirects%3E+%3Fx%7D+.%0D%0A++++++++filter+not+exists%7B%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageDisambiguates%3E+%3Fy%7D+.%0D%0A++++%7D%0D%0A&format=text%2Fhtml&timeout=0&debug=on). While the ```?type``` is **optional**, it only counts the resources which have a type!
```
SELECT distinct count(distinct ?s)
    FROM <http://dbpedia.org> WHERE {
        optional { ?s a ?type . }
        ?s <http://dbpedia.org/ontology/wikiPageRank> ?pr .
        ?s <http://dbpedia.org/ontology/wikiPageID> ?id .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageRedirects> ?x} .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageDisambiguates> ?y} .
    }
```

Hence, remove entirely the optional clause about the type:
```
SELECT distinct count(distinct ?s)
    FROM <http://dbpedia.org> WHERE {
        ?s <http://dbpedia.org/ontology/wikiPageRank> ?pr .
        ?s <http://dbpedia.org/ontology/wikiPageID> ?id .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageRedirects> ?x} .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageDisambiguates> ?y} .
    }
``` 
Now, there are [6013629 resources](http://3cixty.eurecom.fr/dbpedia?default-graph-uri=&query=SELECT+distinct+count%28distinct+%3Fs%29%0D%0A++++FROM+%3Chttp%3A%2F%2Fdbpedia.org%3E+WHERE+%7B%0D%0A++++++++%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageRank%3E+%3Fpr+.%0D%0A++++++++%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageID%3E+%3Fid+.%0D%0A++++++++filter+not+exists%7B%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageRedirects%3E+%3Fx%7D+.%0D%0A++++++++filter+not+exists%7B%3Fs+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageDisambiguates%3E+%3Fy%7D+.%0D%0A++++%7D%0D%0A&format=text%2Fhtml&timeout=0&debug=on)

But should NOT the 2 sets return exactly the same number of results?

**Comment by HughWilliams** [comment]
Should the "optional" value not be specified after the triple pattern as in the examples at:

    http://www.w3.org/TR/sparql11-query/#optionals
    http://www.slideshare.net/juliandolby/optionals-25419705

When I did this against your endpoint the same results we're created ?

**Comment by rtroncy** [comment]
Indeed, putting the OPTIONAL clause as the last one provides the correct set of answers. Therefore, the appropriate query to write is:
```
SELECT distinct count(distinct ?s)
    FROM <http://dbpedia.org> WHERE {
        ?s <http://dbpedia.org/ontology/wikiPageRank> ?pr .
        ?s <http://dbpedia.org/ontology/wikiPageID> ?id .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageRedirects> ?x} .
        filter not exists{?s <http://dbpedia.org/ontology/wikiPageDisambiguates> ?y} .
        optional { ?s a ?type . }
    }
```

@HughWilliams, you're argue-ing that this the correct expected behavior of a sparql engine? @jplu Does this solve your problem?

**Comment by HughWilliams** [comment]
@rtroncy: In all use cases and examples I have seen even the W3C example the optional comes after the pattern ... and that slideshare presentation on optionals specifically says they should immediately precede the patterns ...

**Comment by jplu** [comment]
I confirm I get the proper results if the optional clause becomes the last one of the pattern. Thanks a lot for the hint @HughWilliams !!
