### ISSUE TITLE
Bulk import RDF - What IRI ?

### ISSUE THREAD

**Issue by smarek** [openlink/virtuoso-opensource#616]
Hi,

non-standard set of czech national subsidy registry (cedr), not documented well.

URLs used in data are under similar namespaces, such as:

http://cedropendata.mfcr.cz/c3lod/cedr/vocabCEDR# 
http://cedropendata.mfcr.cz/c3lod/mmr/vocabMMR#
http://cedropendata.mfcr.cz/c3lod/ruian/vocabRUIAN#

All data are exported in notation-3 (.n3) files, which I'm trying to import.

Will use bulk load, `ld_dir('/tmp/', '*.n3', 'http://cedropendata.mfcr.cz/c3lod/cedr/vocabCEDR#');`, but thats imho not correct

Is it possible to let the import decide into which graph data belong by auto-discovering correct namespace?

**Comment by HughWilliams** [comment]
I don't understand how you expect a graph name to be determined from a namespace automatically ? What if there are multiple namespaces defined in the dataset or even no namespaces, which impossible if a dataset is split into multiple files ?

**Comment by kidehen** [comment]
@smarek , 

How about the following steps:

1. Download the data from the respective namespaces to local files
2. Use the Bulk Loader with local file names.

ld_dir('/tmp/', '{local-file-name-pattern}', '{desired-graph-iri}');

**Comment by smarek** [comment]
@HughWilliams i'm new to RDF, I presume it's obvious from triplets like this, which graph namespace the triplet belongs to? But yes, in cases you defined, it can be hard to tell...

```
<http://cedropendata.mfcr.cz/c3lod/cedr/resource/Adresa/000012CF04B788C22153B0647AB27EB3C22768FD> <http://cedropendata.mfcr.cz/c3lod/cedr/vocabCEDR#nachaziSeNaUzemiStatu> <http://cedropendata.mfcr.cz/c3lod/csu/resource/ciselnik/Stat/v01/CZE/19930101> .
<http://cedropendata.mfcr.cz/c3lod/cedr/resource/Adresa/000012CF04B788C22153B0647AB27EB3C22768FD> <http://cedropendata.mfcr.cz/c3lod/isdp/vocabIsdp/space/v1#adresniMistoKod> "4410335"^^<http://www.w3.org/2001/XMLSchema#integer> .
```

@kidehen we're talking about roughly 32gb in plaintext N3 files, and remote sparql endpoint is being limited, so this would take weeks, if we were to download the data through requests.

I'm already doing bulk loading, however If i put all the data into single graph, then queries that work for upstream, does not work for my copy, because respective graphs are not filled with data. Is it possible to set graph aliases? I have 6 graphs, imported from respective upstream URLs (see the URLs in first post), but I'm filling data into single one, because in exported data, those are not separated by IRI.

Solution of course would be for upstream to provide TriG or N-Quads exports, instead of plain N3, but that's not possible in short-term and really hard in long-term view.

**Comment by jindrichmynarz** [comment]
[Namespaces](https://www.w3.org/TR/rdf11-concepts/#dfn-namespace-iri) and [named graphs](https://www.w3.org/TR/rdf11-concepts/#dfn-named-graph) are different things in RDF. Namespaces organize identifiers, while named graphs organize data. You cannot automatically determine a named graph from a namespace. You can follow some heuristic based on a convention, but that's it.

What @kidehen suggested is bulk loading from files, so there's no involvement of the remote SPARQL server.

The problem with upstream queries not working for your local copy can be only resolved by using the same named graph IRIs as the upstream queries do (in the `FROM` and `GRAPH` clauses) or by rewriting the queries. If you can post an example of the upstream query, we may help.

TriG or N-Quads are just RDF serializations, just as N3 is. You can use parsers to convert from between the serializations automatically. The only thing required to provide data in these formats is deciding on named graph IRIs and reserializing the data, which is very easy to do.

**Comment by smarek** [comment]
@jindrichmynarz I want to achieve state, where equal queries on upstream and my copy, will result in identical results. Is this possible, by ie. setting the aliases to default namespace IRI, i've bulk loaded the N3 upstream exports?

**Comment by jindrichmynarz** [comment]
This is possible if you load the data into the named graphs used by the upstream queries. If you share some of these queries, we can help you find out the named graph IRIs required by these queries.

**Comment by kidehen** [comment]
@smarek , 

@jindrichmynarz has provided you with an accurate description of the situation. In addition to that, bearing in mind that you are new to RDF, I will attempt to use another anecdote to aid your understanding of this realm (which can be confusing). 

Imagine you have a Book that consists of the following:
1. Pages
2. Sentences
3. Paragraphs.

The items above map to RDF, in the context of a quad store like Virtuoso, as follows:

1. Page => Named Graph
2. Sentences => RDF triples
3. Paragraphs => RDF triples that share a common predicate

Alternatively, if leveraging what's referred to as Reification (where each sentence is an entity described using terms from the RDF Reification vocabulary), you can also break things down as follows:

1. Page => Named Graph
2. Sentences => RDF triples
3. Paragraphs => Collection of Reified RDF triples 

You simply need to decide what triples you want to load into what page.

When querying in SPARQL, you have to decide if the default graph used for query evaluation is scoped to:

1. A Union of all Named Graphs -- this is the default when there are no FROM CLAUSES
2. Specific Named Graphs -- this is the consequence of FROM {named-graph-iri}
3. Specific Named Graphs where Individual Graph IRIs are visible to the SPARQL dataset modifier (body of the sparql query) -- this is the consequence of FROM NAMED {named-graph-iri} .

With regards to #3, you end up with queries like:

```
SELECT *
FROM NAMED <{named-graph-iri-1}>
FROM NAMED <{named-graph-iri-2}>
WHERE {GRAPH <{named-graph-iri-1}> {?s a ?o}
               GRAPH <{named-graph-iri-2}> {?s2 a ?o2} 
               }
```

**Comment by smarek** [comment]
Sorry, yes, I was confused about the terms, thank you for clearing that up for me.
