### ISSUE TITLE
Error while running virtuoso-t -f &

### ISSUE THREAD

**Issue by likhitha-surapaneni** [openlink/virtuoso-opensource#621]
Hi,
I am trying to set up virtuoso on my system(Ubuntu 64-bit).
After running virtuoso-t -f &, this is the log obtained

OpenLink Virtuoso Universal Server
08:58:11 Version 06.01.3127-pthreads for Linux as of Sep 24 2013
08:58:11 uses parts of OpenSSL, PCRE, Html Tidy
08:58:11 Database version 3126
08:58:11 SQL Optimizer enabled (max 1000 layouts)
08:58:12 Compiler unit is timed at 0.001314 msec
08:58:13 built-in procedure "repl_undot_name" overruled by the RDBMS
08:58:13 built-in procedure "REPL_FQNAME" overruled by the RDBMS
08:58:13 built-in procedure "REPL_COLTYPE_PS" overruled by the RDBMS
08:58:13 built-in procedure "REPL_COLTYPE" overruled by the RDBMS
08:58:13 Roll forward started
08:58:13     3 transactions, 155 bytes replayed (100 %)
08:58:13 Roll forward complete
08:58:14 PL LOG: Installing Virtuoso Conductor version 1.00.8762 (DAV)
08:58:14 Checkpoint started
08:58:14 Checkpoint finished, log reused
**08:58:14 PL LOG: VAD_INSTALL: Please update server version (FATAL)
08:58:14 PL LOG: Errors where detected during installation of "Virtuoso Conductor".**
08:58:14 Checkpoint started
08:58:14 Checkpoint finished, log reused
08:58:14 HTTP/WebDAV server online at 8890
08:58:14 Server online at 1111 (pid 8487)

 It is throwing an error when I try to open http://localhost:8890/conductor saying

Error HTTP/1.1 404 File not found

The requested URL was not found    URI  = '/conductor'

However, http://localhost:8890 is working fine.

I downloaded the develop/7 version hoping it to be the latest version. Any kind of help would be gratetful. 

Thankyou.

**Comment by HughWilliams** [comment]
What is the physical location of the `virtuoso-t` you started which reports its version as 06.01.3127 , whereas you indicate having loaded develop/7 and the error `VAD_INSTALL: Please update server version (FATAL)`  which make me think the VAD is from the Virtuoso develop/7 setup but the Virtuoso server is 6.x . Thus where is the Virtuoso 7  `virtuoso-t` binary installed ?
