### ISSUE TITLE
Override graph IRI when loading RDF in N-Quads

### ISSUE THREAD

**Issue by arnikz** [openlink/virtuoso-opensource#622]
Hi,
My  _data_ dir contains the following files: _data.nq.gz_ and _data.nq.graph_ (with graph IRI different from the one in *.nq.gz).  The RDF data was loaded using

```
ld_dir('/data/', 'data.nq.gz', NULL) ;
SELECT * FROM DB.DBA.load_list ; # shows graph IRI as in *.graph (OK)
rdf_loader_run() ;
```
However, according to Virtuoso Conductor -> Linked Data -> Graphs, the RDF data was loaded under original graph IRI (in the N-Quads file). I'm running Virtuoso v7.20.3217. Any suggestions?

**Comment by HughWilliams** [comment]
Not sure what your issue is ... you have requested the N-Quad dataset data.nq.gz be loaded into the Quad Store so the graph name must be that specified in the dataset and will override any graph name specified in ld_dir or the .graph name which can be used when loading multiple triple format datasets like ttl or .rdf etc datasets ...

**Comment by arnikz** [comment]
Thanks @HughWilliams. You are right about the N-Quads & standard behavior. Is it possible to ignore the graph name in N-Quads file and use the name specified in ld_dir or *.graph file during bulk loading? Otherwise I need to post-process *.nq.gz files with desired graph name, which takes time for large files, prior to loading.

**Comment by HughWilliams** [comment]
It is not possible to ignore the graph name in N-Quad or Trig datasets, as that is there purpose, and will always take precedence ... if u don't want the graph name in the dataset then it should be converted to a triple dataset i.e. TTL, Turtle, RDF/XML and then the graph name can be specified at load time ...

**Comment by arnikz** [comment]
OK; however, I wanted to avoid any post-processing/conversion and specify the (new) graph name at load time.
