### ISSUE TITLE
Unable to delete data (virtuoso.db magically re-appears)

### ISSUE THREAD

**Issue by LLTommy** [openlink/virtuoso-opensource#624]
Hi,

my virtuoso database seems to be in an unstable state. What I usually do to fix this, is just to delete everything and rebuild the database. I usually do this by deleting virtuoso.db, virtuoso-temp.db, virtuoso.pxa, virtuoso.trx ... if you restart virtuoso then, you should have an empty database as far as I am concerned. This does not seem to work anymore. If I restart, the server fails at start up with the following message:

> 08:38:56 PL LOG: DB.DBA.DAV_QUEUE_RUN exit handler: 
 SR325: Transaction aborted due to a database checkpoint or database-wide atomic operation. Please retry transaction
08:38:57 PL LOG: Installation with dependencies complete
08:38:57 Failed to start listening at SQL port '1111'
08:38:57 Server exiting

...and the files I previously deleted are magically there again. I don't understand it, since my database file is quite big (70 GB) - where does virtuoso even keep that information to magically restore this file? And why is my previous approach not working anymore? All I want is to get rid of everything and start fresh! So I am pretty confused and would appreciate some comments.

**Comment by openlink** [comment]
On 27 February 2017 at 08:50, LLTommy <notifications@github.com> wrote:

> my virtuoso database seems to be in an unstable state. What I usually do
> to fix this, is just to delete everything and rebuild the database. I
> usually do this by deleting virtuoso.db, virtuoso-temp.db, virtuoso.pxa,
> virtuoso.trx ... if you restart virtuoso then, you should have an empty
> database as far as I am concerned. This does not seem to work anymore. If I
> restart, the server fails at start up with the following message:
>
> 08:38:56 PL LOG: DB.DBA.DAV_QUEUE_RUN exit handler:
> SR325: Transaction aborted due to a database checkpoint or database-wide
> atomic operation. Please retry transaction
> 08:38:57 PL LOG: Installation with dependencies complete
> 08:38:57 Failed to start listening at SQL port '1111'
> 08:38:57 Server exiting
>
> ...and the files I previously deleted are magically there again. I don't
> understand it, since my database file is quite big (70 GB) - where does
> virtuoso even keep that information to magically restore this file? And why
> is my previous approach not working anymore? All I want is to get rid of
> everything and start fresh! So I am pretty confused and would appreciate
> some comments.
>
The clue is the line "Failed to start listening at SQL port '1111'". You
still have a virtuoso instance running; deleting the files from under a
running instance will have no effect on the filesystem until the executable
terminates.

As a rule the instances is defined by the ini-file, so if you want to
remove an entire instance and start afresh, you only need keep the
virtuoso.ini.

HTH,

~Tim
-- 
Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by LLTommy** [comment]
Thanks for the support! I was able to solve it. I am building the database on a cluster and it turned out that another program took that port. So I was not running another instance of virtuoso, but yes, the problem was connected to that error message!
