### ISSUE TITLE
change password of dva

### ISSUE THREAD

**Issue by andrewufrank** [openlink/virtuoso-opensource#625]
````
virtuoso opensource : 06.01.3127  
llogin as dba with password. open system-admin -> user accounts
edit dav
set password, confirm 
save
--
open a new browser window for virtuoso 
account - dav
password - the one just set
-> invalid credentials

````
what i am doing wrong?  (are there restrictions on what the password must be? must virtuoso be restarted  for password to be set?)
thank you for help!

**Comment by openlink** [comment]
On 28 February 2017 at 08:48, andrew u frank <notifications@github.com>
wrote:

> what i am doing wrong? (are there restrictions on what the password must
> be? must virtuoso be restarted for password to be set?)


Try running  checkpoint;   after changing the password - does that help?

Regards,

~Tim
-- 
Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by andrewufrank** [comment]
can i run checkpoint from the browser interface? what would be the command line?

**Comment by openlink** [comment]
On 28 February 2017 at 10:30, andrew u frank <notifications@github.com>
wrote:

> can i run checkpoint from the browser interface? what would be the command
> line?


Yes, use either the Conductor's iSQL or commandline isql.

~Tim
-- 
Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by andrewufrank** [comment]
nope - i learned how to do checkpoint. but the dav password is not set and i cannot login.
what i really need is #626 (allow DVA login) - which i do not see on the dba create user page.

**Comment by andrewufrank** [comment]
i did a new clean install from github c30a3c711993b2f60d8e807c4bab8d717a56f28b on a debian jessie (amd64). i can login to dba with password dba and change the password for dba and dav.
the change to the dba account works. the change to the dav account does not, as a consequence, i cannot login to dav at all (neither with the standard password dav nor the newly set one).
what could i do wrong? thank you for your help

**Comment by HughWilliams** [comment]
@andrewufrank: What are you trying to login with the "dav" user to , is it the Virtuoso Conductor ? As note the Conductor is the SQL Admin interface for the Virtuoso database and the "dav" is a "WebDav" user type for accessing WebDav folders/resources and thus not allowed to login to the Conductor or isql , see http://docs.openlinksw.com/virtuoso/davaccountsforwebuser/

You would have to set to it be a SQL & WebDav user type of SQL only, then you would also have to give it "dba" role for it to be able to login and have access to resources of in the Conductor.

**Comment by andrewufrank** [comment]
thank you for the information - i did not understand what the `dav` user is, but had the suspicion that it was related to my inability to create a new user and have it use the conductor. (#626 where i see your answer - will check in a minute).
i understand that there is no need to have dav to access the conductor web interface. correct?
thank you for the help!
