### ISSUE TITLE
how to set dva login when creating a user

### ISSUE THREAD

**Issue by andrewufrank** [openlink/virtuoso-opensource#626]
virtuoso opensource : 06.01.3127 
on the page to create a new user there is no `Allow DAV logins` field, but this seems necessary to allow the SPARQL POST as described in https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFInsert#HTTP%20POST.

i can run example one `INSERT` but not `INSERT DATA {...}` . for these i get 
    HTTP/1.1 403 Forbidden: insufficient user permissions
    Server: Virtuoso/06.01.3127 (Linux) x86_64-pc-linux-gnu

i assume that the `allow DAV logins` is the problem. where to set them? where is that set?
thank you for help!

**Comment by HughWilliams** [comment]
you probably need to grant the SPARQL_UPDATE role to the dav user for it to be able to perform SPARUL (i.e. insert/update/delete) operations as detailed at:

     http://docs.openlinksw.com/virtuoso/rdfsparul/

**Comment by andrewufrank** [comment]
i did a new clean install from `github c30a3c711993b2f60d8e807c4bab8d717a56f28b` on a debian jessie (amd64). i can login to dba with password dba and change the password for dba and dav. 
the change to the dba account works. the change to the dav account does not, as a consequence, i cannot login to dav at all (neither with the standard password dav nor the newly set one).
what could i do wrong? thank you for your help
this seems to be a different issue - i open it separately

**Comment by andrewufrank** [comment]
i have a new clean install of current ( github c30a3c711993b2f60d8e807c4bab8d717a56f28b ) virtuoso opensource. i crated a user and gave him sparql_update and all what i could think of (see attached screenshot). i can login as the new user, but not do anything on the browser interface. what did i wrong?
![virtuoso screenshot_2017-03-03_12-37-14](https://cloud.githubusercontent.com/assets/928208/23549953/ca4cec0a-000e-11e7-951e-c406f0b6974d.png)

**Comment by HughWilliams** [comment]
@andrewufrank: Once again are you seeking to have the created user access the Conductor Admin Interfaces menu items, as a user needs to have the "dba" primary role to have rights to access the Conductor for Administering the database ...

**Comment by andrewufrank** [comment]
thank you - when i set the "dba" primary role, i can open with this user the conductor interface. 

however, i did not intend for this user to be able to administer the user accounts, just to ask sparql queries etc. what role should it have then? 
thank you for the help?

**Comment by HughWilliams** [comment]
@andrewufrank: The Conductor UI is not mean't to be used for general execution of SPARQL queries by general "users" , as it is an Admin Interface, with the ability to execute SPARQL & SQL etc queries by a user with "dba" role. If you want to have general users execute SPARQL queries, then you should use the /sparql or one of the other default endpoints as detailed at:

    http://docs.openlinksw.com/virtuoso/rdfsparqlprotocolendpoint/#rdfsupportedprotocolendpoint

Then you just have to grant the user SPARQL_SELECT, SPARQL_UPDATE etc privileges to allow them to execute queries. Note  the /sparql endpoint run as the special "SPARQL" user which has SPARQL_SELECT privileges by default and is thus a read-only endpoint. Then you have the /sparql-auth default endpoint, which would challenge you for authenticate by default and what ever use you login as it would then allow access bases on the privileges assigned to that user etc

In terms of general graph security and controlling access to graph in Virtuoso open source you should read the Graph Security chapter at:

    http://docs.openlinksw.com/virtuoso/rdfgraphsecurity/

I should also make you aware of the Virtuoso Attribute Based Access Controls (ABAC), which provides scalable fine-grained, attributed-based access controls (ABAC) to protected resources (HTTP-accessible documents, folders, services [via their endpoints], and SPARQL named graphs), using the Virtuoso Authentication Layer (VAL), and is a commercial only feature, see:

    https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/ValWhatWhyHow
    https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/WebIDTLSDelegationWhatWhyHow

**Comment by andrewufrank** [comment]
thank you a lot for this very careful and extensive answer. you clarified a number of misunderstandings and reminded me of the /sparql interface - i just checked it, it works great and will do for students to explore the dataset i am constructing!
