### ISSUE TITLE
TTLP() and R2RML_MAKE_QM_FROM_G() generate a graph that can neither be queried from a procedure nor deleted

### ISSUE THREAD

**Issue by mazzogp** [openlink/virtuoso-opensource#630]
The RDF graph generated using DB.DBA.TTLP() and DB.DBA.R2RML_MAKE_QM_FROM_G() procedures cannot be deleted and the statement `for (sparql ...) do {}` with a query over it do not iterate.

Following the example in the page [Virtuoso R2RMLSupport](http://docs.openlinksw.com/virtuoso/r2rmlhow/) I have run the proposed script `basic.sql` that generates a simple graph from a DB table with single row.
I have used the following code to query the content of the example result graph.

```
create procedure R2RML.TEST.try() returns integer
{
  for (sparql define input:storage ""
    select ?o
    #from <http://localhost:8890/sparql>
    from <http://example.com/>
    where { ?s ?p ?o } LIMIT 5 ) do
    {
      string_to_file ('trashMe.txt', "o"||'\n', -1);
    };
};
R2RML.TEST.try();

```
The code snippet does not iterate over the 3 quads of the graph. If another graph is used (like the one commented out in the code) the iterations are executed.

I tried as well to use the `dump_one_graph()` procedure (actually on other R2RML generated graphs, not the one of this example) and I have noticed that the graphs are not dumped.

I have run the `basic.sql` example as `dba` with a Windows Virtuoso Open Source just installed together with the rdb2rdf_dav.vad package.

My VOS version is the following.
Virtuoso Open Source Edition (multi threaded)
Version 7.2.4.3217-threads as of Apr 25 2016
Compiled for Win64 (x86_64-generic-win-64)

I have tried with the following rdb2rdf_dav.vad packages installed, with both the result is the same.
`http://opldownload.s3.amazonaws.com/uda/vad-packages/6.3/virtuoso/rdb2rdf_dav.vad`
`http://s3.amazonaws.com/opldownload/uda/vad-packages/7.0/rdb2rdf_dav.vad`

Below is the session with the execution of `basic.sql` and the `CLEAR GRAPH` that does not delete the content of the generated graph `<http://example.com/>`

```
SQL> load .\basic.sql;
Done. -- 4 msec.
Done. -- 16 msec.
Done. -- 0 msec.
Done. -- 0 msec.
Done. -- 0 msec.
STATE    MESSAGE
VARCHAR  VARCHAR
_______________________________________________________________________________

00000    IRI class <r2rml:virt02-d6310c8f81a31b40880be84617cef62c> has been defined (inherited from rdfdf:sql-integer-uri-nullable)
00000    Literal class <r2rml:virt02-bf406ba67f39c90ee07c9e8b9f0611ae> has been defined (inherited from rdfdf:sql-integer-literal-nullable)
00000    Quad storage <http://www.openlinksw.com/schemas/virtrdf#DefaultQuadStorage> is flagged as being edited
00000    Quad map <http://temp/product> has been created and added to the <http://www.openlinksw.com/schemas/virtrdf#DefaultQuadStorage>
00000    Quad map <sys:qm-0b840fec4c625440d1915a0ae8e5cab9> has been created and added to the <http://www.openlinksw.com/schemas/virtrdf#DefaultQuadStorage>
00000    Quad map <sys:qm-84e7c00e26da8476895ddc0d779d2538> has been created and added to the <http://www.openlinksw.com/schemas/virtrdf#DefaultQuadStorage>
00000    Quad map <sys:qm-60348ca058fc088a9c89f6e10efc15f9> has been created and added to the <http://www.openlinksw.com/schemas/virtrdf#DefaultQuadStorage>
00000    Quad storage <http://www.openlinksw.com/schemas/virtrdf#DefaultQuadStorage> is unflagged and can be edited by other transactions
00000    Transaction committed, SPARQL compiler re-configured
00000    9 RDF metadata manipulation operations done

10 Rows. -- 297 msec.
SQL>
SQL>
SQL> sparql select * from <http://example.com/> where {?s ?p ?o};                                                    
s                                  p                                                o
LONG VARCHAR                       LONG VARCHAR                                     LONG VARCHAR
___________________________________                                                
                                                                                   
http://example.com/product/1       http://example.com/product#id                    1
http://example.com/product/1       http://example.com/product#name                  Virtuoso
http://example.com/product/1       http://www.w3.org/1999/02/22-rdf-syntax-ns#type  http://example.com/ns#product
                                                                                   
3 Rows. -- 16 msec.                                                                                
SQL>                                                                                                                 
SQL> SPARQL CLEAR GRAPH <http://example.com/>;                                                                       
callret-0                                                                                                            
LONG VARCHAR                                                                                                         
____________________________________________________________________                                                 
                                                                                                                     
Clear graph <http://example.com/> -- done                                                                            
                                                                                                                     
1 Rows. -- 16 msec.                                                                                                  
SQL>                                                                                                                 
SQL>                                                                                                                 
SQL> sparql select * from <http://example.com/> where {?s ?p ?o};                                                    
s                                 p                                                o
LONG VARCHAR                      LONG VARCHAR                                     LONG VARCHAR
__________________________________                                                
                                                                                  
http://example.com/product/1      http://example.com/product#id                    1
http://example.com/product/1      http://example.com/product#name                  Virtuoso
http://example.com/product/1      http://www.w3.org/1999/02/22-rdf-syntax-ns#type  http://example.com/ns#product
                                                                                  
3 Rows. -- 15 msec.                                                          
```

**Comment by HughWilliams** [comment]
When I create your R2RML.TEST.try() procedure and run it with the virtual or physical graphs, in both case no results are returned, whereas you indicated the physical graphs do returns results for you ?

As indicated previously to remove the Virtual graphs you have to removed the Virtual Graphs quad map storage which is not part of the Default Quad Map storage used for physical graphs for which they SPARQL CLEAR/DROP/DELETE commands would only apply as the Virtual Graph do not exist in this location.

So for the basic.sql script the quad map storage created for the Virtual Graph from your above is:

```
00000    Quad map <http://temp/product> has been created and added to the <http://www.openlinksw.com/schemas/virtrdf#DefaultQuadStorage>
```

So remove the `<http://temp/product>` Quad map for the Virtual graph you would do:

```
SQL> SPARQL drop silent quad map <http://temp/product>;
STATE    MESSAGE
VARCHAR  VARCHAR
_______________________________________________________________________________

00000    Quad map <http://temp/product> is no longer used in storage <http://www.openlinksw.com/schemas/virtrdf#DefaultQuadStorage>
00000    Quad map <http://temp/product> is deleted
00000    Transaction committed, SPARQL compiler re-configured
00000    Transaction committed, SPARQL compiler re-configured
00000    2 RDF metadata manipulation operations done

5 Rows. -- 16719 msec.
SQL> 
SQL> sparql select * from <http://example.com/> where {?s ?p ?o};
s                                                                                 p                                                                                 o
LONG VARCHAR                                                                      LONG VARCHAR                                                               LONG VARCHAR
_______________________________________________________________________________


0 Rows. -- 99 msec.
SQL>
```

**Comment by mazzogp** [comment]
Hi Hugh

The code snippet R2RML.TEST.try() is not supposed to return a value (sorry,
the returns keyword is misleading). It is supposed to write in the Virtuoso
directory in the file trashMe.txt the triple object each iteration
performed.

In my test, with the generated graph <http://example.com/>  no iteration is
performed. Furthermore, if I try to dump such a graph with the
<https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFDatasetDump>
dump_one_graph()
<https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFDatasetDump>
procedure, a file is written with no triples inside.

I must serialize in RDF/XML and Json-ld formats my R2RML generated graph.
Given the iteration issue above and the dump not working I do not see any
workaround possibilities...


Thanks for the hint regarding the deletion! Now I have succeeded to delete
the generated graph. So a virtual graph is a graph generated via TTLP() and
R2RML_MAKE_QM_FROM_G()? There is a place where each and every triples of
such a graph are physically stored, or are they computed on demand?

I was assuming that the virtual graphs are only the ones obtained via the
"RDF View" approach...

Cheers

Beppe

2017-03-15 11:30 GMT+00:00 HughWilliams <notifications@github.com>:

**Comment by kidehen** [comment]
On 3/15/17 10:49 AM, beppem wrote:
>
> Thanks for the hint regarding the deletion! Now I have succeeded to delete
> the generated graph. So a virtual graph is a graph generated via
> TTLP() and
> R2RML_MAKE_QM_FROM_G()? There is a place where each and every triples of
> such a graph are physically stored, or are they computed on demand?

Computed on demand.

RDF Views generated by either W3C R2RML or Virtuoso built-in Mapping
Language result in a collection of mappings. These mapping are what we
refer to as virtual triples since they are computed on demand (i.e.,
execute SQL queries against associated SQL Tables).
>
> I was assuming that the virtual graphs are only the ones obtained via the
> "RDF View" approach...

Yes, as per comment above.


-- 
Regards,

Kingsley Idehen	      
Founder & CEO 
OpenLink Software   (Home Page: http://www.openlinksw.com)

Weblogs (Blogs):
Legacy Blog: http://www.openlinksw.com/blog/~kidehen/
Blogspot Blog: http://kidehen.blogspot.com
Medium Blog: https://medium.com/@kidehen

Profile Pages:
Pinterest: https://www.pinterest.com/kidehen/
Quora: https://www.quora.com/profile/Kingsley-Uyi-Idehen
Twitter: https://twitter.com/kidehen
Google+: https://plus.google.com/+KingsleyIdehen/about
LinkedIn: http://www.linkedin.com/in/kidehen

Web Identities (WebID):
Personal: http://kingsley.idehen.net/dataspace/person/kidehen#this
        : http://id.myopenlink.net/DAV/home/KingsleyUyiIdehen/Public/kingsley.ttl#this

**Comment by mazzogp** [comment]
Thank you for the feedback!
I am converting now my virtual graph into a physical one (in order to serialize it), executing the `RDF_VIEW_SYNC_TO_PHYSICAL()` procedure. The command execution apparently hangs up after few seconds.  Virtuoso Conductor and isql do not respomd as well. Nothing written in the virtuoso.log file. No temp file created in the Virtuoso`database`folder. Everything seems frozen waiting for the execution completion, that after few hours has not happened yet. 
The graph has 6.6M triples. I am running Virtuoso in a Windows workstation with 16GB. The following is the execution session.
```
SQL> RDF_VIEW_SYNC_TO_PHYSICAL ('http://example.com/resource-vgraph', 1, 'http://example.com/resource', 1, 1);
STATE    MESSAGE
VARCHAR  VARCHAR
_______________________________________________________________________________

00000    Quad storage <http://www.openlinksw.com/schemas/virtrdf#SyncToQuads> is flagged as being edited
00000    Quad storage <http://www.openlinksw.com/schemas/virtrdf#SyncToQuads> is flagged as being edited
22023    Quad map <http://temp/testR2RML> is not used in storage <http://www.openlinksw.com/schemas/virtrdf#SyncToQuads>
00000    Reloading built-in metadata, this might fix some errors without accurate reporting that they did exist
00000    Built-in metadata were reloaded (2475 triples)
00000    Metadata from system graph are cached in memory-resident JSOs (JavaScript Objects)
00000    Quad storage <http://www.openlinksw.com/schemas/virtrdf#SyncToQuads> is flagged as being edited
00000    Quad map <http://temp/testR2RML> is added to the storage <http://www.openlinksw.com/schemas/virtrdf#SyncToQuads>
00000    Quad storage <http://www.openlinksw.com/schemas/virtrdf#SyncToQuads> is unflagged and can be edited by other transactions
00000    Transaction committed, SPARQL compiler re-configured
00000    4 RDF metadata manipulation operations done
```
If I run`RDF_VIEW_SYNC_TO_PHYSICAL()`with the `load_data` parameter to `0` (no data loaded) the execution is very fast. Then if the mapped tables are updated, the corresponding modified triples are copied in the designated quad store named graph. So it seems to work fine. 

Is there any optimization or memory set up to perform in order to run`RDF_VIEW_SYNC_TO_PHYSICAL()` with the `load_data` parameter to `1` ?

Thanks!

**Comment by HughWilliams** [comment]
@beppem: given the size of the virtual graph i.e. 6.6M triples you should set the "transaction_mode = 2" as indicated in the documentation at:

   http://docs.openlinksw.com/virtuoso/fn_rdf_view_sync_to_physical/

This will basically set log_enable(2) which turns transaction logging off and set row by row auto commit of the operation, otherwise the entire transaction would be logged to memory which could thus become depleted and slow things to a halt as you seem to be experiencing. See:

   http://docs.openlinksw.com/virtuoso/fn_log_enable/
   
This is the transaction log mode used by the Virtuoso Bulk Loader and what we recommend be used when performing SPARUL (UID) operations on large graphs ...

**Comment by mazzogp** [comment]
This is not a bug. 
Since the involved graph is virtual (result of a R2RML mapping), in order to make the code above to iterate through the graph, the `input:storage` parameter must not be empty. It should contain the name of the quad storage in which the graph is described. In case the used quad storage is the default one the correct code is the following one.

    create procedure R2RML.TEST.try() returns integer
    {
      for (sparql define input:storage "http://www.openlinksw.com/schemas/virtrdf#DefaultQuadStorage"
        select ?o
        #from <http://localhost:8890/sparql>
        from <http://example.com/>
        where { ?s ?p ?o } LIMIT 5 ) do
        {
          string_to_file ('trashMe.txt', "o"||'\n', -1);
        };
    };
    R2RML.TEST.try();


Always because of the "virtual" nature of the graph, the following statement has to be used in order to delete the graph of the example above. 

    SPARQL drop silent quad map <http://temp/product>;
