### ISSUE TITLE
problems with SPARQL Insert via /sparql endpoint

### ISSUE THREAD

**Issue by andrewufrank** [openlink/virtuoso-opensource#632]
i use virtuoso-opensource build from sources (github) on a linux amd64 with debian jessie.

i try to use the instructions in https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFInsert#SPARQL%20Insert%20via%20/sparql%20endpoint, but get `409 Invalid path` error. 
the user `demo` with password `demo` is set to `sql/odbc and webDAV` roles are set to `sparql_load_service_data` and `sparql_update`. default catalog is none and the primary role is none. 

the query is  

````
SPARQL INSERT IN GRAPH <http://example/store> {<http://demo.openlinksw.com/DAV/home/demo_about.rdf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://rdfs.org/sioc/ns#User>  .
}
````

leaving out SPARQL to be consistent with standard does not change the result.  the same result is obtained with `INSERT DATA { GRAPH ... { ... }  }.`

the request is POST and the credentials are encoded in the url. the server responds in the browser with the sparql query editor.

````
http://demo:...@nlp.xx.x:8890/sparql  
Content-Type: application/sparql-query
````

i guess that `409 invalid path` is misleading me and assume that i have a problem with authentication. does virtuoso not accept the authentication with `user:pw@.../sparql` ? how would i authentication a user in a sparql update query? i do not see a difference when i pass incorrect username or passwd. 

thank you for pointers!

**Comment by HughWilliams** [comment]
What exactly is the command you are passing to perform the insert (SPARUL operation) ?

Note the /sparql endpoint does not do authentication and will always run queries as the internal "SPARQL" user with whatever SPARQL roles it has been assigned.

As said in one of your previous issues, to perform SPARUL operations as a specific user  the default /sparql-auth endpoint which has SPARQL_UPDATE role and support digest connections has to be used as detailed at:

   http://docs.openlinksw.com/virtuoso/rdfsparqlprotocolendpoint/
   https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtTipsAndTricksGuideSPARQLEndpoints 

See the following example using curl:

```
De-iMac:~ hwilliams$ curl --request POST 'http://127.0.0.1:8890/sparql-auth/?' --digest --user dba:dba --data-urlencode 'query=INSERT INTO GRAPH <http://example.org> { <1> <2> <3> }'
<sparql xmlns="http://www.w3.org/2005/sparql-results#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/sw/DataAccess/rf1/result2.xsd">
 <head>
  <variable name="callret-0"/>
 </head>
 <results distinct="false" ordered="true">
  <result>
   <binding name="callret-0"><literal>Insert into &lt;http://example.org&gt;, 1 (or less) triples -- done</literal></binding>
  </result>
 </results>
</sparql>De-iMac:~ hwilliams$ 

De-iMac:~ hwilliams$ curl --request POST 'http://127.0.0.1:8890/sparql/?' --data-urlencode 'query=select * from  <http://example.org> where {?s ?p ?o}'
<sparql xmlns="http://www.w3.org/2005/sparql-results#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/sw/DataAccess/rf1/result2.xsd">
 <head>
  <variable name="s"/>
  <variable name="p"/>
  <variable name="o"/>
 </head>
 <results distinct="false" ordered="true">
  <result>
   <binding name="s"><uri>1</uri></binding>
   <binding name="p"><uri>2</uri></binding>
   <binding name="o"><uri>3</uri></binding>
  </result>
 </results>
</sparql>
De-iMac:~ hwilliams$ 
```

**Comment by andrewufrank** [comment]
thank you for your patience. i set the sparql user to update and now i get different error messages, but at the end i am still with '409 invalid path' or (new) 'Virtuoso 22023 Error The request does not contain text of SPARQL query' if i send it to `sparql/?query=' (which i think is ok).

unfortunately the `tips and tricks` page was not accessible for a while, but the information in it did not show me how to proceed.

i can use your curl example without a problem - thus the basic functionality of virtuoso is ok, however i want to use the insert query in a program (Haskell) with the HTTP call software provided there, because the number of triples i want to insert is larger.

if i attach the query (which is 

INSERT DATA { GRAPH <http://example/store>
 {<http://demo.openlinksw.com/DAV/home/demo_about.rdf> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://rdfs.org/sioc/ns#User>  .
} }
 
with the url/sparql/?query=' it works or in the sparql query browser.

what i cannot do is to attach the query as a body to the http post request. independently  if i set the content type `application/sparql-query` and pass the query text as above or url-encoded, i get `409 invalid path` (with `text/plain` as content type, the body is not considered and the response is the sparql web browser).  the result type was set to `*/*`, setting it to `application/sparql-query` does not change the result (i.e it remains 409 invalid path).  if the body is url encoded and the type is set to `application/x-www-form-urlencoded` then i get `Virtuoso 22023 Error The request does not contain text of SPARQL query`

the `sparql-crud` endpoint seems not to look into the body and always replies with the sparql input form. 

thank you for your help!

**Comment by HughWilliams** [comment]
If the curl command works then you should be able to pass the same params in a HTTP post request to the Virtuoso SPARQL endpoint from any HTTP client application, as curl is often used to simulate HTTP client behaviour from command line.

Note also, if you are seeking to bulk load data then we recommend using the Virtuoso RDF Bulk Loader for  best performance as detailed at:

   https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtBulkRDFLoader

Bulk loading via the HTTP REST interface i.e. SPARQL endpoint will be the least performant.

**Comment by andrewufrank** [comment]
thank you for your information, which does not address the issue:
the query in curl or in the http call encoded as part of the url works; what does not work, is the same query  as a text in the body of the http post. in curl i have no control whether the payload is send url encoded in the url or in a body. performance is not an issue (the process which produces the rdf triples is much slower). 

i assume  that there is a bug in virtuoso such that the sparql endpoint does not work with http when the query is sent in the body of the message, not encoded in the url. i would be interested to see a http post request coded in a language where you can insert the query in the body of the request.

**Comment by HughWilliams** [comment]
If you are querying the /sparql endpoint then the SPARQL/SPARUL queries should be URL encoded as detailed in the W3C SPARQL Protocol for RDF , which is what we and all RDF store offering a SPARQL endpoint should support, see:

   https://www.w3.org/TR/rdf-sparql-protocol/

See also our documentation at:

   http://docs.openlinksw.com/virtuoso/rdfsparqlprotocolendpoint/

If you want to see the URL encoded query and params that need to be passed then execute a query form the /sparql endpoint and on the query results page look at the URL in the Web Browser which shows the URL encoded params passed to execute a given query. For example:

```
http://demo.openlinksw.com/sparql?default-graph-uri=&query=select+distinct+%3FConcept+where+%7B%5B%5D+a+%3FConcept%7D+LIMIT+50&should-sponge=&format=text%2Fhtml&timeout=20000
```

which is what is passed for executing the query:

```
select distinct ?Concept where {[] a ?Concept} LIMIT 50
```
Note also if you change the `&query` param to `qtxt` you can run in a browser to see the text for the query that produces the result i.e. for the above query:

```
http://demo.openlinksw.com/sparql?default-graph-uri=&qtxt=select+distinct+%3FConcept+where+%7B%5B%5D+a+%3FConcept%7D+LIMIT+50&should-sponge=&format=text%2Fhtml&timeout=20000
```

**Comment by andrewufrank** [comment]
thank you for trying to be helpful. the correct answer is that the body must be encoded as 

`application/sparql-update` 

which i cannot find anywhere in your documentation. fortunately, fuseki gives helpful error messages and the solution works for both (except that virtuose does not allwo a `INSERT DATA` without somehow selecting a default graph. i add this to the conversation to help others finding themselves in the same bind.
