### ISSUE TITLE
Can't delete certain triples (with literals) in Version 7.1.0

### ISSUE THREAD

**Issue by shinobu** [openlink/virtuoso-opensource#633]
I have noticed the following problem concerning Virtuoso through our integration tests:

Certain Triples don't get properly deleted with a normal DELETE/DELETE WHERE call on Version 7.1 (I used the docker container "encoflife/virtuoso:7.1.0" to reproduce the error)

Minimal Example for reproducing the Error in the conductor:

Insert into Default Graph URI "http://example.org/" the following Triples:

```
INSERT {
    <http://example.org/renameTest/old> <http://example.org/renameTest/p2> <http://example.org/renameTest/old> .
    <http://example.org/renameTest/old> <http://example.org/renameTest/p2> "http://example.org/renameTest/old" .
    <http://example.org/renameTest/old> <http://example.org/renameTest/type> "TYPE"^^<http://www.w3.org/2001/XMLSchema#string> .
}
```
result: `3 added`

Afterwards, attempt to delete them with:

DELETE {
    <http://example.org/renameTest/old> <http://example.org/renameTest/p2> <http://example.org/renameTest/old> .
    <http://example.org/renameTest/old> <http://example.org/renameTest/p2> "http://example.org/renameTest/old" .
    <http://example.org/renameTest/old> <http://example.org/renameTest/type> "TYPE"^^<http://www.w3.org/2001/XMLSchema#string> .
}

result: `3 deleted`

Afterwards, checking the Graph with a normal Select Query:

SELECT * { ?s ?p ?o }

result: 

```
<http://example.org/renameTest/old> <http://example.org/renameTest/p2> "http://example.org/renameTest/old" .
<http://example.org/renameTest/old> <http://example.org/renameTest/type> "TYPE"^^<http://www.w3.org/2001/XMLSchema#string> .
```

The only way I was able to delete those are with DELETE WHERE and __not__ specifying the Object part.
E.G.:
```
DELETE WHERE  { 
    <http://example.org/renameTest/old> <http://example.org/renameTest/p2> ?o .
 }
```

**Comment by HughWilliams** [comment]
The problem does not occur in the latest Virtuoso open source develop/7 branch which is version 7.2.5 ... 7.1 is rather old thus I would suggest updating to the latest release ...

**Comment by shinobu** [comment]
OK, thanks for the fast reaction
I guess this Issue can be closed then.
