### ISSUE TITLE
virtuoso start error in Linux

### ISSUE THREAD

**Issue by wudapeng268** [openlink/virtuoso-opensource#637]
Hi；
when I want to start this db using `sudo ./bin/virtuoso-t +foreground +configfile var/lib/virtuoso/db/virtuoso.ini &`, unfortunately,I got error:

Tue Mar 21 2017
10:44:36 { Loading plugin 1: Type `plain', file `wikiv' in `/home/xxx/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/lib/virtuoso/hosting'
10:44:36   FAILED  plugin 1: Unable to locate file }
10:44:36 { Loading plugin 2: Type `plain', file `mediawiki' in `/home/xxx/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/lib/virtuoso/hosting'
10:44:36   FAILED  plugin 2: Unable to locate file }
10:44:36 { Loading plugin 3: Type `plain', file `creolewiki' in `/home/xxx/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/lib/virtuoso/hosting'
10:44:36   FAILED  plugin 3: Unable to locate file }
10:44:36 Unable to lock file /home/xxx/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/var/lib/virtuoso/db/virtuoso.lck (Resource temporarily unavailable).
10:44:36 Virtuoso is already runnning (pid 12313)
10:44:36 This probably means you either do not have permission to start
10:44:36 this server, or that virtuoso-t is already running.
10:44:36 If you are absolutely sure that this is not the case, please try
10:44:36 to remove the file /home/xxx/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/var/lib/virtuoso/db/virtuoso.lck and start again.

[1]+  Exit 1                  sudo ./bin/virtuoso-t +foreground +configfile var/lib/virtuoso/db/virtuoso.ini

I want to run https://github.com/zihangdai/CFO   a Question Answer system using this db, my virtuoso.ini as follows:

;
;  virtuoso.ini
;
;  Configuration file for the OpenLink Virtuoso VDBMS Server
;
;  To learn more about this product, or any other product in our
;  portfolio, please check out our web site at:
;
;      http://virtuoso.openlinksw.com/
;
;  or contact us at:
;
;      general.information@openlinksw.com
;
;  If you have any technical questions, please contact our support
;  staff at:
;
;      technical.support@openlinksw.com
;

;
;  Database setup
;
[Database]
DatabaseFile			= /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/var/lib/virtuoso/db/virtuoso.db
ErrorLogFile			= /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/var/lib/virtuoso/db/virtuoso.log
LockFile			= /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/var/lib/virtuoso/db/virtuoso.lck
TransactionFile			= /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/var/lib/virtuoso/db/virtuoso.trx
xa_persistent_file		= /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/var/lib/virtuoso/db/virtuoso.pxa
ErrorLogLevel			= 7
FileExtend			= 200
MaxCheckpointRemap		= 2000
Striping			= 0
TempStorage			= TempDatabase

[TempDatabase]
DatabaseFile			= /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/var/lib/virtuoso/db/virtuoso-temp.db
TransactionFile			= /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/var/lib/virtuoso/db/virtuoso-temp.trx
MaxCheckpointRemap		= 2000
Striping			= 0

;
;  Server parameters
;
[Parameters]
ServerPort			= 1111
LiteMode			= 0
DisableUnixSocket		= 1
DisableTcpSocket		= 0
;SSLServerPort			= 2111
;SSLCertificate			= cert.pem
;SSLPrivateKey			= pk.pem
;X509ClientVerify		= 0
;X509ClientVerifyDepth		= 0
;X509ClientVerifyCAFile		= ca.pem
MaxClientConnections		= 10
CheckpointInterval		= 60
O_DIRECT			= 0
CaseMode			= 2
MaxStaticCursorRows		= 5000
CheckpointAuditTrail		= 0
AllowOSCalls			= 0
SchedulerInterval		= 10
DirsAllowed			= ., /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/share/virtuoso/vad, , /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/data
ThreadCleanupInterval		= 0
ThreadThreshold			= 10
ResourcesCleanupInterval	= 0
FreeTextBatchSize		= 100000
SingleCPU			= 0
VADInstallDir			= /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/share/virtuoso/vad/
PrefixResultNames               = 0
RdfFreeTextRulesSize		= 100
IndexTreeMaps			= 256
MaxMemPoolSize                  = 200000000
PrefixResultNames               = 0
MacSpotlight                    = 0
IndexTreeMaps                   = 64
MaxQueryMem 		 	= 16G		; memory allocated to query processor
VectorSize 		 	= 10000		; initial parallel query vector (array of query operations) size
MaxVectorSize 		 	= 1000000	; query vector size threshold.
AdjustVectorSize 	 	= 0
ThreadsPerQuery 	 	= 4
AsyncQueueMaxThreads 	 	= 10
;;
;; When running with large data sets, one should configure the Virtuoso
;; process to use between 2/3 to 3/5 of free system memory and to stripe
;; storage on all available disks.
;;
;; Uncomment next two lines if there is 2 GB system memory free
;NumberOfBuffers          = 170000
;MaxDirtyBuffers          = 130000
;; Uncomment next two lines if there is 4 GB system memory free
;NumberOfBuffers          = 340000
; MaxDirtyBuffers          = 250000
;; Uncomment next two lines if there is 8 GB system memory free
;NumberOfBuffers          = 680000
;MaxDirtyBuffers          = 500000
;; Uncomment next two lines if there is 16 GB system memory free
;NumberOfBuffers          = 1360000
;MaxDirtyBuffers          = 1000000
;; Uncomment next two lines if there is 32 GB system memory free
;NumberOfBuffers          = 2720000
;MaxDirtyBuffers          = 2000000
;; Uncomment next two lines if there is 48 GB system memory free
;NumberOfBuffers          = 4000000
;MaxDirtyBuffers          = 3000000
;; Uncomment next two lines if there is 64 GB system memory free
;NumberOfBuffers          = 5450000
;MaxDirtyBuffers          = 4000000
;;
;; Note the default settings will take very little memory
;; but will not result in very good performance
;;
NumberOfBuffers          = 10000
MaxDirtyBuffers          = 6000

[HTTPServer]
ServerPort			= 8890
ServerRoot			= /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/var/lib/virtuoso/vsp
MaxClientConnections		= 10
DavRoot				= DAV
EnabledDavVSP			= 0
HTTPProxyEnabled		= 0
TempASPXDir			= 0
DefaultMailServer		= localhost:25
ServerThreads			= 10
MaxKeepAlives			= 10
KeepAliveTimeout		= 10
MaxCachedProxyConnections	= 10
ProxyConnectionCacheTimeout	= 15
HTTPThreadSize			= 280000
HttpPrintWarningsInOutput	= 0
Charset				= UTF-8
;HTTPLogFile		        = logs/http.log
MaintenancePage             	= atomic.html
EnabledGzipContent          	= 1

[AutoRepair]
BadParentLinks			= 0

[Client]
SQL_PREFETCH_ROWS		= 100
SQL_PREFETCH_BYTES		= 16000
SQL_QUERY_TIMEOUT		= 0
SQL_TXN_TIMEOUT			= 0
;SQL_NO_CHAR_C_ESCAPE		= 1
;SQL_UTF8_EXECS			= 0
;SQL_NO_SYSTEM_TABLES		= 0
;SQL_BINARY_TIMESTAMP		= 1
;SQL_ENCRYPTION_ON_PASSWORD	= -1

[VDB]
ArrayOptimization		= 0
NumArrayParameters		= 10
VDBDisconnectTimeout		= 1000
KeepConnectionOnFixedThread	= 0

[Replication]
ServerName			= db-1080-3
ServerEnable			= 1
QueueMax			= 50000

;
;  Striping setup
;
;  These parameters have only effect when Striping is set to 1 in the
;  [Database] section, in which case the DatabaseFile parameter is ignored.
;
;  With striping, the database is spawned across multiple segments
;  where each segment can have multiple stripes.
;
;  Format of the lines below:
;    Segment<number> = <size>, <stripe file name> [, <stripe file name> .. ]
;
;  <number> must be ordered from 1 up.
;
;  The <size> is the total size of the segment which is equally divided
;  across all stripes forming  the segment. Its specification can be in
;  gigabytes (g), megabytes (m), kilobytes (k) or in database blocks
;  (b, the default)
;
;  Note that the segment size must be a multiple of the database page size
;  which is currently 8k. Also, the segment size must be divisible by the
;  number of stripe files forming  the segment.
;
;  The example below creates a 200 meg database striped on two segments
;  with two stripes of 50 meg and one of 100 meg.
;
;  You can always add more segments to the configuration, but once
;  added, do not change the setup.
;
[Striping]
Segment1			= 100M, db-seg1-1.db, db-seg1-2.db
Segment2			= 100M, db-seg2-1.db
;...

;[TempStriping]
;Segment1			= 100M, db-seg1-1.db, db-seg1-2.db
;Segment2			= 100M, db-seg2-1.db
;...

;[Ucms]
;UcmPath			= <path>
;Ucm1				= <file>
;Ucm2				= <file>
;...

[Zero Config]
ServerName			= virtuoso (1080-3)
;ServerDSN			= ZDSN
;SSLServerName			= 
;SSLServerDSN			= 

[Mono]
;MONO_TRACE			= Off
;MONO_PATH			= <path_here>
;MONO_ROOT			= <path_here>
;MONO_CFG_DIR			= <path_here>
;virtclr.dll			=

[URIQA]
DynamicLocal			= 0
DefaultHost			= localhost:8890

[SPARQL]
;ExternalQuerySource		= 1
;ExternalXsltSource 		= 1
;DefaultGraph      		= http://localhost:8890/dataspace
;ImmutableGraphs    		= http://localhost:8890/dataspace
ResultSetMaxRows           	= 10000
MaxQueryCostEstimationTime 	= 400	; in seconds
MaxQueryExecutionTime      	= 60	; in seconds
DefaultQuery               	= select distinct ?Concept where {[] a ?Concept} LIMIT 100
DeferInferenceRulesInit    	= 0  ; controls inference rules loading
;PingService       		= http://rpc.pingthesemanticweb.com/

[Plugins]
LoadPath			= /home/zhaocq/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/lib/virtuoso/hosting
Load1				= plain, wikiv
Load2				= plain, mediawiki
Load3				= plain, creolewiki
;Load4			= plain, im
;Load5		= plain, wbxml2
;Load6			= plain, hslookup
;Load7			= attach, libphp5.so
;Load8			= Hosting, hosting_php.so
;Load9			= Hosting,hosting_perl.so
;Load10		= Hosting,hosting_python.so
;Load11		= Hosting,hosting_ruby.so
;Load12				= msdtc,msdtc_sample

I try to restart virtuoso many times, and also try to re-make this virtuoso, But can't solve it.
my virtuoso version is 7.2.4.2 develop clone from github
my os is Linux 64bit

Anyone can help me will be thanks.

**Comment by HughWilliams** [comment]
If the Virtuoso server is not current running then the file  /home/xxx/virtuoso_install/virtuoso-opensource/KnowledgeBase/VirtuosoKG/var/lib/virtuoso/db/virtuoso.lck should not exist, thus if it does you should remove it manually and try to start the server again ...

**Comment by wudapeng268** [comment]
Actually, I comment relative three sentences，so the server can start, thanks!
