### ISSUE TITLE
Facet text search broken

### ISSUE THREAD

**Issue by DavideAllavena** [openlink/virtuoso-opensource#640]
After the installation of the VAD package fct ( following successfully this guide: https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtFacetBrowserInstallConfig) i got this error clicking on "Text Search" at http://servername:8890/fct: 

```
Could not process your request because of an unexpected error.
Diagnostics
SQLSTATE: 42000
SQLMSG  : DAV does not contain resource with path equal to "/DAV/VAD/fct/fct_set_text.xsl"
More info…
Permalink
STATE:
<query inference="" same-as="" view3="" s-term="" c-term="" agg="" />
```
Actually the file needed seems located in the wrong WebVAD path. Is there at least a quick fix?

According to this [conversation](https://www.mail-archive.com/virtuoso-users@lists.sourceforge.net/msg08102.html) I upgraded but the problem persist.

Here the version of Virtuoso:
```
$ /opt/virtuoso-opensource/bin/virtuoso-t -?    
 Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.5-dev.3217-pthreads as of Apr  5 2017
Compiled for Linux (x86_64-pc-linux-gnu)
Copyright (C) 1998-2017 OpenLink Software
```

**Comment by HughWilliams** [comment]
I performed a build with from the latest git develop/7 branch:

```
De-iMac:database hwilliams$ ../bin/virtuoso-t -?
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.5-dev.3217-pthreads as of Apr  8 2017
Compiled for Darwin (x86_64-apple-darwin15.6.0)
Copyright (C) 1998-2017 OpenLink Software
```

 and the FCT Browser works fine for me ...

What is you version of the FCT VAD , mine is `	1.13.91`

**Comment by DavideAllavena** [comment]
Issue solved downloading ftc from here: http://opldownload.s3.amazonaws.com/uda/vad-packages/7.2/fct_dav.vad
