### ISSUE TITLE
 FAILED  plugin 1: Unable to locate file

### ISSUE THREAD

**Issue by plegault3397** [openlink/virtuoso-opensource#642]
I reviewed a couple of similar issues and was unable to find the solution to this error.
I'm running RedHat 7
08:03:10 { Loading plugin 1: Type `plain', file `wikiv' in `/app/virtuoso/lib/virtuoso/hosting'
08:03:10   FAILED  plugin 1: Unable to locate file }
08:03:10 { Loading plugin 2: Type `plain', file `mediawiki' in `/app/virtuoso/lib/virtuoso/hosting'
08:03:10   FAILED  plugin 2: Unable to locate file }
08:03:10 { Loading plugin 3: Type `plain', file `creolewiki' in `/app/virtuoso/lib/virtuoso/hosting'
08:03:10   FAILED  plugin 3: Unable to locate file }
08:03:10 OpenLink Virtuoso Universal Server
08:03:10 Version 07.20.3217-pthreads for Linux as of Apr 10 2017
08:03:10 uses parts of OpenSSL, PCRE, Html Tidy
08:03:10 Database version 3126
08:03:10 SQL Optimizer enabled (max 1000 layouts)
08:03:11 Compiler unit is timed at 0.000142 msec
08:03:12 Roll forward started
08:03:12 Roll forward complete
08:03:12 Checkpoint started
08:03:12 Checkpoint finished, log reused
08:03:14 HTTP/WebDAV server online at 8890
08:03:14 Server online at 1111 (pid 19265)

**Comment by openlink** [comment]
On 11 April 2017 at 13:11, plegault3397 <notifications@github.com> wrote:

> I reviewed a couple of similar issues and was unable to find the solution
> to this error.
> 08:03:10 { Loading plugin 1: Type plain', filewikiv' in
> /app/virtuoso/lib/virtuoso/hosting' 08:03:10 FAILED plugin 1: Unable to
> locate file } 08:03:10 { Loading plugin 2: Typeplain', file mediawiki' in
> /app/virtuoso/lib/virtuoso/hosting'
> 08:03:10 FAILED plugin 2: Unable to locate file }
> 08:03:10 { Loading plugin 3: Type plain', filecreolewiki' in
> `/app/virtuoso/lib/virtuoso/hosting'
> 08:03:10 FAILED plugin 3: Unable to locate file }
>

You shouldn't be seeing any { } characters in there. Please check for
corruption toward the end of your virtuoso.ini file. It should look
something like


[Plugins]
LoadPath                        =
/somewhere/based/on/your/installation/$PREFIX
Load1                           = plain, wikiv
Load2                           = plain, mediawiki
Load3                           = plain, creolewiki


instead.

HTH,

~Tim
-- 
Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by plegault3397** [comment]
That is what I see,
What I don't see in the directory is /app/virtuoso/lib/virtuoso/hosting
the directory virtuoso is missing from there

#-> ll /app/virtuoso/lib/
total 128396
drwxr-xr-x 2 root root     4096 Apr 11 07:19 hibernate
drwxr-xr-x 2 root root     4096 Apr 11 07:19 jdbc-2.0
drwxr-xr-x 2 root root     4096 Apr 11 07:19 jdbc-3.0
drwxr-xr-x 2 root root     4096 Apr 11 07:19 jdbc-4.0
drwxr-xr-x 2 root root     4096 Apr 11 07:19 jdbc-4.1
drwxr-xr-x 2 root root     4096 Apr 11 07:19 jdbc-4.2
drwxr-xr-x 2 root root     4096 Apr 11 07:19 jena
drwxr-xr-x 2 root root     4096 Apr 11 07:19 jena2
drwxr-xr-x 2 root root     4096 Apr 11 07:19 jena3
-rw-r--r-- 1 root root 98574168 Apr 11 07:19 libvirtuoso-t.a
-rwxr-xr-x 1 root root      920 Apr 11 07:19 libvirtuoso-t.la
drwxr-xr-x 2 root root     4096 Apr 11 07:19 rdf4j
drwxr-xr-x 2 root root     4096 Apr 11 07:19 sesame
-rw-r--r-- 1 root root  5154624 Apr 11 07:19 virtodbc.a
-rwxr-xr-x 1 root root      937 Apr 11 07:19 virtodbc.la
-rw-r--r-- 1 root root  5191524 Apr 11 07:19 virtodbc_r.a
-rwxr-xr-x 1 root root      961 Apr 11 07:19 virtodbc_r.la
-rwxr-xr-x 1 root root  2768008 Apr 11 07:19 virtodbc_r.so
-rwxr-xr-x 1 root root  2743784 Apr 11 07:19 virtodbc.so
-rw-r--r-- 1 root root  5449742 Apr 11 07:19 virtodbcu.a
-rwxr-xr-x 1 root root      944 Apr 11 07:19 virtodbcu.la
-rw-r--r-- 1 root root  5486642 Apr 11 07:19 virtodbcu_r.a
-rwxr-xr-x 1 root root      968 Apr 11 07:19 virtodbcu_r.la
-rwxr-xr-x 1 root root  2943288 Apr 11 07:19 virtodbcu_r.so

**Comment by openlink** [comment]
On 11 April 2017 at 13:23, plegault3397 <notifications@github.com> wrote:

> That is what I see,
> What I don't see in the directory is /app/virtuoso/lib/virtuoso/hosting
> the directory virtuoso is missing from there
>

What's in the [Plugins] section of virtuoso.ini?

~Tim
-- 
Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by plegault3397** [comment]
Figured it out
just commented that out in the ini
