### ISSUE TITLE
Incorrect UTF-8 character IRI handling in "Namespaces" in Conductor

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#643]
When creating a namespace (prefix) with an UTF-8 character in it, e.g. ```https://ruian.linked.opendata.cz/slovník/```, it is saved correctly, but in the list of namespaces it is shown as  ```https://ruian.linked.opendata.cz/slovnÃ­k/```. The handling of UTF-8 characters in IRIs is broken in fct and conductor in many places in general.

**Comment by HughWilliams** [comment]
I have recreated an reported to development to look into ...

**Comment by jakubklimek** [comment]
This is resolved in d76ab20f8cdee8b7660bf1b653fda85d08e5153c.
