### ISSUE TITLE
docs.openlinksw.com entry for dump_one_graph procedure has incorrect number of params for dict_new function

### ISSUE THREAD

**Issue by alsyia** [openlink/virtuoso-opensource#644]
Dear all,

The dumping procedure described [here](https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VirtRDFDatasetDump) is bugged. 

Line 
`env := VECTOR (dict_new (16000), 0, '', '', '', 0, 0, 0, 0, 0);`
 should be
`env := VECTOR (dict_new (16000), 0, '', '', '', 0, 0, 0, 0);`
 as described in [official docs](http://docs.openlinksw.com/virtuoso/rdfperfdumpandreloadgraphs/).

The wiki procedure will result in this error : 
`Error 22023: [Virtuoso Driver][Virtuoso Server]SR601: Argument 0 of http_ttl_triple() should be an array of special format`

Could you please fix it ? This is very confusing ;)

Thank you,
Alsyia.

**Comment by HughWilliams** [comment]
When exactly are you see the error as I don't get it using the dump_one_graph() procedure from the wiki ?

```
SQL> CREATE PROCEDURE dump_one_graph 
dump_one_graph(0)   ( IN  srcgraph           VARCHAR
dump_one_graph(0)   , IN  out_file           VARCHAR
dump_one_graph(0)   , IN  file_length_limit  INTEGER  := 1000000000
dump_one_graph(0)   )
dump_one_graph(0)   {
dump_one_graph(1)     DECLARE  file_name     VARCHAR
dump_one_graph(1)   ; DECLARE  env
dump_one_graph(1)           ,  ses           ANY
dump_one_graph(1)   ; DECLARE  ses_len
dump_one_graph(1)           ,  max_ses_len
dump_one_graph(1)           ,  file_len
dump_one_graph(1)           ,  file_idx      INTEGER
dump_one_graph(1)   ; SET ISOLATION = 'uncommitted'
dump_one_graph(1)   ; max_ses_len  := 10000000
dump_one_graph(1)   ; file_len     := 0
dump_one_graph(1)   ; file_idx     := 1
dump_one_graph(1)   ; file_name    := sprintf ('%s%06d.ttl', out_file, file_idx)
dump_one_graph(1)   ; string_to_file ( file_name || '.graph', 
dump_one_graph(1)                      srcgraph, 
dump_one_graph(1)                      -2
dump_one_graph(1)                    );
dump_one_graph(1)     string_to_file ( file_name, 
dump_one_graph(1)                      sprintf ( '# Dump of graph <%s>, as of %s\n@base <> .\n', 
dump_one_graph(1)                                srcgraph, 
dump_one_graph(1)                                CAST (NOW() AS VARCHAR)
dump_one_graph(1)                              ), 
dump_one_graph(1)                      -2
dump_one_graph(1)                    )
dump_one_graph(1)   ; env := vector (dict_new (16000), 0, '', '', '', 0, 0, 0, 0, 0)
dump_one_graph(1)   ; ses := string_output ()
dump_one_graph(1)   ; FOR (SELECT * FROM ( SPARQL DEFINE input:storage "" 
dump_one_graph(1)                          SELECT ?s ?p ?o { GRAPH `iri(?:srcgraph)` { ?s ?p ?o } } 
dump_one_graph(1)                        ) AS sub OPTION (LOOP)) DO
dump_one_graph(1)       {
dump_one_graph(2)         http_ttl_triple (env, "s", "p", "o", ses);
dump_one_graph(2)         ses_len := length (ses);
dump_one_graph(2)         IF (ses_len > max_ses_len)
dump_one_graph(2)           {
dump_one_graph(3)             file_len := file_len + ses_len;
dump_one_graph(3)             IF (file_len > file_length_limit)
dump_one_graph(3)               {
dump_one_graph(4)                 http (' .\n', ses);
dump_one_graph(4)                 string_to_file (file_name, ses, -1);
dump_one_graph(4) 
data.ttl              data_000001.ttl.graph virtuoso.db           virtuoso.ini.sample   virtuoso.log          virtuoso.trx         
data_000001.ttl       virtuoso-temp.db      virtuoso.ini          virtuoso.lck          virtuoso.pxa         
dump_one_graph(4) gz_compress_file (file_name, file_name||'.gz');
dump_one_graph(4) 
data.ttl              data_000001.ttl.graph virtuoso.db           virtuoso.ini.sample   virtuoso.log          virtuoso.trx         
data_000001.ttl       virtuoso-temp.db      virtuoso.ini          virtuoso.lck          virtuoso.pxa         
dump_one_graph(4) file_delete (file_name);
dump_one_graph(4)                 file_len := 0;
dump_one_graph(4)                 file_idx := file_idx + 1;
dump_one_graph(4)                 file_name := sprintf ('%s%06d.ttl', out_file, file_idx);
dump_one_graph(4)                 string_to_file ( file_name, 
dump_one_graph(4)                                  sprintf ( '# Dump of graph <%s>, as of %s (part %d)\n@base <> .\n', 
dump_one_graph(4)                                            srcgraph, 
dump_one_graph(4)                                            CAST (NOW() AS VARCHAR), 
dump_one_graph(4)                                            file_idx), 
dump_one_graph(4)                                  -2
dump_one_graph(4)                                );
dump_one_graph(4)                  env := VECTOR (dict_new (16000), 0, '', '', '', 0, 0, 0, 0, 0);
dump_one_graph(4)               }
dump_one_graph(3)             ELSE
dump_one_graph(3)               string_to_file (file_name, ses, -1);
dump_one_graph(3)             ses := string_output ();
dump_one_graph(3)           }
dump_one_graph(2)       }
dump_one_graph(1)     IF (LENGTH (ses))
dump_one_graph(1)       {
dump_one_graph(2)         http (' .\n', ses);
dump_one_graph(2)         string_to_file (file_name, ses, -1);
dump_one_graph(2) gz_compress_file (file_name, file_name||'.gz');
dump_one_graph(2) file_delete (file_name);
dump_one_graph(2)       }
dump_one_graph(1)   };

Done. -- 3 msec.
SQL> 
SQL> dump_one_graph ('urn:rules.skos', './urn_rules_skos_', 1000000000);                                                     

Done. -- 15 msec.
SQL>quit;

De-iMac:database hwilliams$ ls -ltr urn_rules_skos_000001.ttl.g*
-rw-r--r--  1 root  wheel  200 22 Apr 21:49 urn_rules_skos_000001.ttl.gz
-rw-r--r--  1 root  wheel   14 22 Apr 21:49 urn_rules_skos_000001.ttl.graph
De-iMac:database hwilliams$
```

**Comment by alsyia** [comment]
I can create the procedure normally, but every attempt to call it fails with given error. Could it be a version mismatch? I'm using 7.2.4 from comsode packet, but I initially had the problem with a binary compiled from source (`stable/7`). There must be something wrong going on since wiki and doc give different arguments for `http_ttl_triple()`...

**Comment by HughWilliams** [comment]
What is the `comsode packet` ???

I tested against the latest `develop/7` branch which is about to become the new `stable/7` branch; thus I would suggest testing with a build from that, i.e., https://github.com/openlink/virtuoso-opensource

**Comment by alsyia** [comment]
Sorry, I made a typo. I was thinking of the Comsode packet, a virtuoso 7 deb packet provided by Open Data Node team. It's in a repo called `comsode` (see [here](http://packages.comsode.eu/dists/jessie/main/binary-amd64/Packages)). But I remember trying with `stable/7` compiled and had the same issue.  I will try with `develop/7` when I have time, thanks !

**Comment by ebremer** [comment]
I just tried this with the latest develop/7 and this bug appears to still persist.

**Comment by ebremer** [comment]
From: [16.17.9. Dump and Reload Graphs](http://docs.openlinksw.com/virtuoso/rdfperfdumpandreloadgraphs/)
I get the error:
```pre
*** Error 22023: [Virtuoso Driver][Virtuoso Server]SR601: Argument 0 of http_ttl_triple() should be an array of special format
at line 2 of Top-Level:
```

**Comment by ebremer** [comment]
I changed `env := vector (dict_new (16000), 0, '', '', '', 0, 0, 0, 0);` in the URL
[16.17.9. Dump and Reload Graphs](http://docs.openlinksw.com/virtuoso/rdfperfdumpandreloadgraphs/)
to
`env := vector (dict_new (16000), 0, '', '', '', 0, 0, 0, 0, 0);`

and it now works.

**Comment by ebremer** [comment]
It appears the documentation needs to be updated.

**Comment by HughWilliams** [comment]
@ebremer The Wiki [`dump_one_graph()`](http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFDatasetDump) documentation has the correct number of params for the `dict_new` function; will have the [docs.openlinksw.com function](http://docs.openlinksw.com/virtuoso/rdfperfdumpandreloadgraphs/) updated to correct that error.

**Comment by ebremer** [comment]
I'm still getting this error for some of my named graphs.  I have 25 graphs and four of them are throwing that error.  Is there anything else I should look for?

**Comment by ebremer** [comment]
Nevermind, I figured it out.  I had a partially fixed version of the one that was wrong.  When I swapped the wiki version completely, it worked fine.

**Comment by alsyia** [comment]
Oh, that _is_ an old issue!
It looks like you had a bug opposite to mine @ebremer! 

Thanks @HughWilliams for the fix in the docs!

**Comment by ebremer** [comment]
Perhaps it's time to finally close this issue @TallTed @HughWilliams?

**Comment by TallTed** [comment]
We'll hold this open until the updated manual page is in place.

**Comment by timhaynesopenlink** [comment]
Docs updated, sorry for the confusion: http://docs.openlinksw.com/virtuoso/rdfperfdumpandreloadgraphs/
