### ISSUE TITLE
SQL Message	The user "(NULL)" does not exist

### ISSUE THREAD

**Issue by logicfish** [openlink/virtuoso-opensource#652]
I'm getting this error in ODS on both linux and windows after a clean install of virtuoso `2.7.4`.

The error happens when I log in to ODS.  The edit profile and settings links do not work.

I have installed only the "framework" package and configured this to a new listener on `0.0.0.0:8890` .

Error message:
```
Technical data
Page	
SQL State	22023
SQL Message	The user "(NULL)" does not exist.
```
The error is repeated in the log.

**Comment by HughWilliams** [comment]
Where did you obtain the ODS Framework VAD from , was this compiled from the source tree or download from the online VADs available ?

**Comment by logicfish** [comment]
The linux was compiled, the windows was a download.

**Comment by Carpani** [comment]
Hello. 
I have the same issue  in the default listener.

Any news on that?

Thanks.
FDO.

**Comment by HughWilliams** [comment]
Same questions applies as to the other user ... 

Also Suggest trying against the latest develop/7 branch ...

**Comment by hackerceo** [comment]
Same issue here.

**Comment by logicfish** [comment]
I've tried with the latest from git - no change.

**Comment by logicfish** [comment]
I've tried with docker stable/7

`20:50:57 PL LOG: ODS [22023] The user "(NULL)" does not exist.`

and develop/7 fresh checkout.

**Comment by HughWilliams** [comment]
This issue is still to be resolved ...

**Comment by openlink** [comment]
A fix is pushed into develop/7 (https://github.com/openlink/virtuoso-opensource/commit/18dd9e33b08cc1214bea65d280ec87166aa8c9a4)
