### ISSUE TITLE
label is not systematically stored as string in a virtual graph

### ISSUE THREAD

**Issue by mazzogp** [openlink/virtuoso-opensource#653]
I have executed the R2RML mapping of many tables stored in the Virtuoso RDB in order to create a virtual graph and to publish the database as RDF.

I have noticed that the class attributes declared `labels `in the triples maps are  not systematically converted in the same `internal_type`in the corresponding RDF. 
For example for the table with the following structure

    CREATE TABLE DB.PEST.SUBSTANCES_LANG 
    (
    SUBSTANCES_LNG_ID NUMERIC NOT NULL   
    , SUBSTANCES_ID NUMERIC NOT NULL   
    , SUBSTANCES_LANGUE VARCHAR(3) NOT NULL 
    , SUBSTANCES_NAME NVARCHAR(500) NOT NULL 
    , CONSTRAINT PK_SUBSTANCES_LANG PRIMARY KEY ( SUBSTANCES_LNG_ID ) 
    );
 that is mapped with this R2RML triples map

    @prefix rr: <http://www.w3.org/ns/r2rml#> .
    @prefix pest: <http://example.com/pesticides/resource/> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    <#TriplesMapSUBSTANCES_LANG> a rr:TriplesMap; 
        rr:logicalTable [ 
            rr:tableSchema "DB" ; 
            rr:tableOwner "pest" ; 
            rr:tableName "SUBSTANCES_LANG" ] ; 
        rr:subjectMap [ 
            rr:termType rr:IRI  ; 
            rr:template "http://example.com/pesticides/resource/substanceLang-{SUBSTANCES_LNG_ID}"; 
            rr:class pest:SubstanceLang; 
            rr:graph <http://example.com/pesticides/resource> 
        ] ;
        rr:predicateObjectMap [ 
            rr:predicateMap [ 
                rr:constant pest:languageCode ] ; 
            rr:objectMap [ 
                rr:column "SUBSTANCES_LANGUE" ] ; 
        ] ;
        rr:predicateObjectMap [ 
            rr:predicateMap [ 
                rr:constant pest:substanceLangId ] ; 
            rr:objectMap [ 
                rr:column "SUBSTANCES_LNG_ID" ] ; 
        ] ;
        rr:predicateObjectMap [ 
            rr:predicateMap [ 
                rr:constant rdfs:label ] ; 
            rr:objectMap [ 
                rr:column "SUBSTANCES_NAME" ] ; 
        ] ;
        rr:predicateObjectMap [ 
            rr:predicateMap [ 
                rr:constant pest:hasSubstance 
            ] ; 
            rr:objectMap [ 
                rr:termType rr:IRI ; 
                rr:template "http://example.com/pesticides/resource/substance-{SUBSTANCES_ID}" 
            ]; 
        ] .
the attribute`rdfs:label`corresponding to the `NVARCHAR `column`SUBSTANCES_NAME`is allocated in my Virtuoso Windows installation with `internal_type=246`. On the contrary the same attribute in my Linux installation performing the same operations is allocated with `internal_type=225`. 
The correct type I suppose is `internal_type=246` because I see the label value displayed in a SPARQL query result wrapped with the double quotation mark (see the image below)
    
![capturewindows](https://user-images.githubusercontent.com/26257378/27488744-0f65f0b0-5830-11e7-88c7-a2b33a1601af.JPG)

On the contrary in Linux environment the same query produces as result a text without the double quotation mark (see the image below).

![capturelinux](https://user-images.githubusercontent.com/26257378/27488965-c6d3303c-5830-11e7-89be-05f3ea33c32b.JPG)

The effect of this difference is that a stored procedure I have developed works fine in Windows and fails in Linux Virtuoso installation. This because in Widows a variable (named `xmlTxt` in the code excerpt below) hosting the value of the query above has the correct `internal_type`.

    declare xmlTxt string;
    [SPARQL code assigning a value to xmlTxt]
    replace(xmlTxt ,'&','&amp;');
Instead in Linux the same code causes the following error 

    `*** Error 22023: [Virtuoso Driver][Virtuoso Server]SR028: From arg (#2) to replace was not a wide string`
because of the variable `internal_type=225` .

This prevents the execution of my developed stored procedure in the Linux Virtuoso installation.

I am using Virtuoso Open Source with the following versions.
WINDOWS
Virtuoso Open Source Edition (multi threaded)
Version 7.2.4.3217-threads as of Apr 25 2016
Compiled for Win64 (x86_64-generic-win-64)
Copyright (C) 1998-2016 OpenLink Software

LINUX
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.4.2.3217-pthreads as of Feb  3 2017
Compiled for Linux (x86_64-unknown-linux-gnu)
Copyright (C) 1998-2016 OpenLink Software

Thanks a lot for any suggestion

**Comment by HughWilliams** [comment]
When I attempt to validate your R2RML triple mappings in the Conductor it fails with the following error:

```
22:39:53 LTRS_2 dba 0.0.0.0 Internal Restart transact 0x7fce47e9faa0
22:39:53 ERRS_0 22007 XM033 XML parser detected an error:
	ERROR  : A tag, processing instruction or special <!...> item expected after '<' character
at line 1 column 3 of 'http://example.com/pesticides/resource'
<#TriplesMapSUBSTANCES_LANG> a rr:TriplesMap; 
-^

22:39:53 LTRS_1 <DBA> 127.0.0.1 Internal Commit transact 0x7fce4e184eb0 0 4295984695
```

Thus are they correct ?

**Comment by mazzogp** [comment]
@HughWilliams There was a typo. I have corrected the R2RML code. I have rephrased the issue description and added pictures as well. I hope this helps to identify the problem

**Comment by HughWilliams** [comment]
I assume you edited the original post and fixed the typo ... and so copied the r2rml mapping to a text file and attempted to load via the Conductr R2RML interface and when attempting to validate the R2RML script it gives an error:

```
Error	Nothing to validate, graph <http://localhost:8890/r2rml> is totally empty
```

which if I ignore to does then generate a set of RDFView mappings, but when I attempt to create the mapping they fail with an error:

```
No table "DB"."pest"."SUBSTANCES_LANG" (alias tbl0) in database, please check spelling and character case
```

So had to make "pest" upper case as in your table declaration i.e. "PEST" then the RDFView mapping would successfully be created. Thus did you not have this same problem with the case of "pest" ?

But now, where is the data from the SQL table to run the "select * from <http://example.com/pesticides/resource> where { <http://example.com/pesticides/resource/substanceLang-1> <http://www.w3.org/2000/01/rdf-schema#label> ?o }" query you provided against as you only provided the schema for the "DB"."pest"."SUBSTANCES_LANG" table ?

**Comment by mazzogp** [comment]
@HughWilliams No, I haven't the validation issue (in fact this is my validation result)

![capture](https://user-images.githubusercontent.com/26257378/27587147-1a969ce2-5b3b-11e7-8188-b8c80c53fe58.JPG)
nor have I the upper case `pest` problem. But I have created a `pest` user (I thought this was not mandatory working with a `dba`user so I did not mention it).
As requested please find attached as well a short script to initialize the created table.
[init_table.txt](https://github.com/openlink/virtuoso-opensource/files/1106125/init_table.txt)

**Comment by mazzogp** [comment]
@HughWilliams I have improved the issue description, adding the stored procedure code in order to reproduce the mentioned run-time error in Linux environment.

    `*** Error 22023: [Virtuoso Driver][Virtuoso Server]SR028: From arg (#2) to replace was not a wide string`
Please find it below as well for your convenience.

    create procedure R2RML.test.trushme()
    {
      declare label varchar;
      for (sparql define input:storage "http://www.openlinksw.com/schemas/virtrdf#DefaultQuadStorage"
        select ?labelVal from <http://example.com/pesticides/resource>
        where 
           {
             ?s <http://www.w3.org/2000/01/rdf-schema#label> ?labelVal .
           } limit 10)
      do {
      label := replace("labelVal",'&','&amp;');
      string_to_file('C:/LocalPrograms/dev/virtuoso/scripts/issues/bug-Label/trushme.log','value of the label='||label||'\n',-1);
      }
    };

**Comment by mazzogp** [comment]
I checked now with VOS version 07.20.3217 and the problem has disappeared. I close the issue.
Thank you!
Beppe
