### ISSUE TITLE
JDBC driver - Problems with non-Latin characters

### ISSUE THREAD

**Issue by mazzogp** [openlink/virtuoso-opensource#656]
I have implemented a plain Java bulk loader to initialize many tables in a Virtuoso relational DB. I am experiencing a problem related to the insertion of Unicode text. Running the program, when the following INSERT statement is executed,

    INSERT INTO DB.PEST.V_SEM_PRODUCT_NAMES_MOD(PRODUCT_CODE,PRODUCT_NAME_ID,LANGUAGE_CD,PART,PRODUCT_NAM,SCIENTIFIC_NAME,PART_NAME) VALUES('0130010',9949,'LV',1,'EĻĻAS AUGU SĒKLAS UN AUGĻI',NULL,NULL)
the inserted row has all the non-Latin characters corrupted (see the attachment below).
With the same INSERT statement having other non-Latin characters I get the following run-time error.

    virtuoso.jdbc4.VirtuosoException exception 
    virtuoso.jdbc4.VirtuosoException: SQ074: Line 1:
            at virtuoso.jdbc4.VirtuosoResultSet.process_result(VirtuosoResultSet.java:631)

Instead the execution of these INSERT statements in the Conductor Interactive SQL is successful.
If I remove as well the non-Latin characters from such INSERT the Java program runs correctly.

I use the JDBC driveris `virtjdbc4_1.jar` found in the [following folder](http://id.myopenlink.net/DAV/home/smalinin/Public/JDBC/).
I use as well Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.4.2.3217-pthreads as of Feb  3 2017
for windows

I made a small example (an Eclipse Java project) able to reproduce the issue executing one INSERT statement only.
With the SQL statement currently configured in the example I get the text inserted in the DB corrupted in the non-Latin characters. 
Please find attached 
-the .zip file with the built java project (rename its extension as .jar), 
-the property file where the executed SQL statement is, together with the DB connection string (VirtuosoBulkLoader.txt - rename its extension as .properties).
-a zip file with the example Java project source code.
**Instructions to reproduce the issue**
Change the DB connection string in the property file and copy the file in the same folder where the example jar is. 
Create a table in the DB with the following structure.

    CREATE TABLE DB.PEST.V_SEM_PRODUCT_NAMES_MOD   -- DICTIONARY
    (
      PRODUCT_CODE    VARCHAR(7) NOT NULL,
      PRODUCT_NAME_ID NUMERIC NOT NULL,
      LANGUAGE_CD VARCHAR(2) NOT NULL,
      PART NUMERIC NOT NULL,
      PRODUCT_NAM NVARCHAR(500),     
      SCIENTIFIC_NAME NVARCHAR(500),   
      PART_NAME NVARCHAR(500),         
      CONSTRAINT PK_V_SEM_PRODUCT_NAMES_MOD PRIMARY KEY (PRODUCT_NAME_ID )
    );
You can directly run the example with the following command.

    java -jar .\virtJdbcDriverProb.jar

![captureconductor](https://cloud.githubusercontent.com/assets/26257378/26360748/dba684d2-3fd0-11e7-8fb3-22f26366f01d.JPG)
[virtJdbcDriverProb.zip](https://github.com/openlink/virtuoso-opensource/files/1018954/virtJdbcDriverProb.zip)
[sourceCode.zip](https://github.com/openlink/virtuoso-opensource/files/1018974/sourceCode.zip)
[VirtuosoBulkLoader.txt](https://github.com/openlink/virtuoso-opensource/files/1018977/VirtuosoBulkLoader.txt)

**Comment by mazzogp** [comment]
I have improved a bit the problem description, adding a snapshot

**Comment by smalinin** [comment]
I could recreate the problem, checking.

**Comment by smalinin** [comment]
I created patch for this problem in JDBC driver and it will be in Git soon.
BUT note also, that you used a WRONG query for insert unicode data.
If you used UNICODE strings in the query, it must have prefix **N**
For example we have table:
```create table test (id integer, f1 nvarchar(50))```
So for insert unicode data the query must be:
```insert into test values(1, N'test')```

If you don't want to use prefix **N** for unicode strings, you could use parameter binding.

**Comment by mazzogp** [comment]
Thanks Sergey!
I tried this syntax with the "N" from the Java program but I got a SQL run-time error. So I concluded that you can use it only with the Virtuoso stored procedure language...

**Comment by smalinin** [comment]
I think, that it was relater with character **'Ā'**  in your test query, that was unproperly converted to unicode and server return back the error message, that was related with the wrong unicode character in query.

**Comment by mazzogp** [comment]
Is this is the place where the patched JDBC driver will come up?
https://github.com/openlink/virtuoso-opensource/tree/develop/7/libsrc/JDBCDriverType4

**Comment by smalinin** [comment]
Yes, the patch was added to Git and JDBC jars were rebuilt about 30min ago.

**Comment by mazzogp** [comment]
I am now using the 'N' in the INSERT from the Java program as advised and the fix performed in the JDBC driver. All the errors are gone!
Thanks!
