### ISSUE TITLE
Faceted Browser only browses one named graph

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#67]
In Faceted Browser v1.13.35 when browsing, I can only browse within one named graph and cannot see related triples from other named graphs.

If, for example, I get to subject, to which references are in other named graphs, these are not visible, which is new in this version and makes browsing an endpoint with multiple interconnected named graphs useless.

I can add more graphs in **Metadata → Referenced by Documents**, but I expect to see all data from all graphs by default.

**Comment by HughWilliams** [comment]
Do you have a sample URL or steps that can be provided for recreating this issue?

Note also that the latest Facet Browser VAD is v `1.13.44`, thus what is the version of Virtuoso being used (`virtuoso-t -?`)?

Note Virtuoso `6.1.7` was released last week and is available from the git `stable/6` branch; thus please attempt and upgrade to this release and see if this resolves the problem ...

**Comment by jakubklimek** [comment]
I have built a fresh checkout c4e0817a34f70ba4efb036fa65f7062c66fdeb42 from Jul 25 (6.1.8-dev)
The Virtuoso Faceted Browser VAD is still 1.13.35.
The url is http://linked.opendata.cz/fct

Repro steps:

Go to http://linked.opendata.cz/describe/?url=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fczso.cz%2Fdataset%2Fdemography%2Fdeaths%2F529303-2011

It is a statistical reading. It has "reference municipality" `Benešov`. If you look at the URL, it is http://linked.opendata.cz/describe/?url=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fregion%2F529303&graph=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fdataset%2Fczso.cz%2Fdemography (notice the graph attribute)

When I click it, I see various readings of which Benešov is reference municipality (data in the mentioned named graph), but no other data of Benešov URL which is in other named graphs.

When I delete the graph attribute from the URL:

http://linked.opendata.cz/describe/?url=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fregion%2F529303

I see data from other named graphs, but I don't see the readings from before.

In previous versions, there were no "graph" attributes in the URL and I could see all available data for a given URI from all named graphs.

**Comment by jakubklimek** [comment]
Now updated to Faceted Browser 1.13.44 and the issue is still present.

**Comment by HughWilliams** [comment]
OK, thanks for confirming the problem persists with the latest develop/6 build, development shall look into this issue and fix ...

**Comment by jakubklimek** [comment]
Is there any progress on this? The issue is still present in fct 1.13.53 making it unusable for browsing multiple integrated datasets

**Comment by HughWilliams** [comment]
Unfortunately this has not been looked into yet. When I look at the original problem description, you state that:

> It has "reference municipality" Benešov. If you look at the URL, it is 
> http://linked.opendata.cz/describe/?url=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fregion%2F529303&graph=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fdataset%2Fczso.cz%2Fdemography (notice the graph attribute)

But when I look at the current live server the "Benešov" URL is
http://linked.opendata.cz/describe/?url=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fregion%2F529303

i.e., there is no reference to a graph, thus the behaviour seems to have changed?

**Comment by kidehen** [comment]
See:
http://linked.opendata.cz/fct/rdfdesc/usage.vsp?g=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fregion%2F529303

In this UI you can hatch the checkbox to scope descriptions to one or more named graphs.

**Comment by jakubklimek** [comment]
Hi, this seems to be resolved in fct v1.13.55, it is showing data from all graphs again.

**Comment by agbeltran** [comment]
Hi, I am having this same problem. The version I downloaded from here:
http://virtuoso.openlinksw.com/download/
under VAD packages for release 7.1 is fct version 1.13.54.
Where can I get version 1.3.55? Thanks.

**Comment by jakubklimek** [comment]
You either need to fetch and build the `develop/7` branch here from github, which I would recommend (https://github.com/openlink/virtuoso-opensource/tree/develop/7) or get only the fct binary from me here: http://linked.opendata.cz/fct_dav.vad which is actually 1.13.58 now

**Comment by agbeltran** [comment]
Thank you!

**Comment by HughWilliams** [comment]
Note, http://virtuoso.openlinksw.com/download/ is the link to download commercial (closed) components as opposed to open source, although in this the fct vad works with both ...

**Comment by agbeltran** [comment]
I see, that's good to know. Thanks.

**Comment by TallTed** [comment]
For future reference -- there are repositories of prebuilt VADs for Virtuoso, for both [Open Source (VOS)](http://download3.openlinksw.com/index.html?prefix=uda/vad-vos-packages/) and [Enterprise Edition](http://download3.openlinksw.com/index.html?prefix=uda/vad-packages/).

**Comment by TallTed** [comment]
For future reference -- there are repositories of prebuilt VADs for Virtuoso, for both [Open Source (VOS)](http://download3.openlinksw.com/index.html?prefix=uda/vad-vos-packages/) and [Enterprise Edition](http://download3.openlinksw.com/index.html?prefix=uda/vad-packages/).

@agbeltran, @jakubklimek -- Can you confirm whether the current [Faceted Browser v1.13.91 for VOS](http://download3.openlinksw.com/uda/vad-vos-packages/7.2/fct_dav.vad) performs as expected/desired?

**Comment by jakubklimek** [comment]
@TallTed It does behave as expected regarding this issue (data from multiple graphs) since https://github.com/openlink/virtuoso-opensource/issues/67#issuecomment-34735392. However, there are [other issues with FCT](https://github.com/openlink/virtuoso-opensource/issues?q=is%3Aissue+is%3Aopen+facet+author%3Ajakubklimek), mainly regarding unicode in IRIs, which still make it hard to use for simple browsing.

**Comment by TallTed** [comment]
Thanks, @jakubklimek.  I'll mark this issue closed on that basis.  The other issues are in the queue, but I cannot provide ETAs on their fixes.  Suggested patches are welcome!

**Comment by pkleef** [comment]
Note i have merged a number of i18n and other assorted fixes for the faceted browser to the current develop/7 branch
