### ISSUE TITLE
Bad incoming tag 80

### ISSUE THREAD

**Issue by jbkoh** [openlink/virtuoso-opensource#676]
Hi,

I am trying to use Virtuoso as a SPARQL endpoint and testing it through curl. However, it did not respond and the server said "Bad incoming tag 80". 

I checked [here](http://wikis.openlinksw.com/VirtuosoWikiWeb/MalformedData) but the port number is right as I checked in the log file as 1111.

```bash
curl -X POST http://localhost:1111/sparql/?query=%0Aselect+%3Fs+%3Fp+%3Fo+where+%7B%0A%3Fs+%3Fp+%3Fo+.%0A%7D%0A --header "Accept:application/sparql-results+json"
```
, of which the query is "select ?s ?p ?o where {?s ?p ?o .}".

- Curl returns "curl: (52) Empty reply from server"
- Virtuoso Server prints "Malformed data received from IP [127.0.0.1] : Bad incoming tag 80. Disconnecting the client"

Is there something obvious that I am missing?

configuration: 
- Ubuntu 16.04
- Virtuoso 7.2.5-dev

Thank you.

**Comment by HughWilliams** [comment]
@jbkoh: You are specifying the Virtuoso default SQL port 1111 in your curl command, where you should be specifying the Virtuoso HTTP port whose default value is 8890  (or whatever HTTP port specified in the config file virtuoso.ini) ...

**Comment by jbkoh** [comment]
Thanks, it works. Thought SPARQL endpoint was associated with ServerPort. Thanks!
