### ISSUE TITLE
 Message: SR185 ImageMagick check failed

### ISSUE THREAD

**Issue by popsovik** [openlink/virtuoso-opensource#679]
i just try to confirm from wiki page:

>To confirm that the ImageMagick plugin is working, execute the following query through Conductor's ISQL interface and check that the return value is 3.
>
>     select "IM XYtoMorton"(1,1)

And have this result.

> Query result:
> IM XYtoMorton
> ANY
> SQLState: 42001
> Message: SR185: Undefined procedure DB.DBA.IM XYtoMorton

```
INFO: Version 07.20.3217-pthreads for Linux as of Sep 26 2017
# magick -version
Version: ImageMagick 7.0.7-3 Q16 x86_64 2017-09-19 http://www.imagemagick.org
```

**`virtuoso.ini`**
```
[Plugins]
#LoadPath = /usr/local/virtuoso-opensource/lib/virtuoso/hosting
#LoadPath = /usr/local/lib
#Load1    = plain, wikiv
#Load2    = plain, mediawiki
#Load3    = plain, creolewiki
Load1     = plain, im
```

**Comment by openlink** [comment]
Hi,

It looks like you've commented-out all the possible LoadPath directives in
the virtuoso.ini. This probably doesn't help.

If you run the server in foreground debug mode:
virtuoso-iodbc-t -df
then among the first few lines you should see something like this:

10:19:12 INFO: { Loading plugin 6: Type `plain', file `im' in `../hosting'
10:19:12 INFO:   IM version 0.63 from OpenLink Software
10:19:12 INFO:   Support functions for Image Magick 6.9.6
10:19:12 INFO:   SUCCESS plugin 6: loaded from ../hosting/im.so }

If adding the LoadPath doesn't help, please include your debug output and
we'll see what else it might be.

HTH,

~Tim

Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by popsovik** [comment]
I dont have this path `/usr/local/virtuoso-opensource/lib/virtuoso/hosting`

If I try load load plugin from `/usr/local/lib`
```
16:22:01 INFO: { Loading plugin 1: Type `plain', file `im' in `/usr/local/lib'
16:22:01 ERROR:   FAILED  plugin 1: Unable to locate file }
```

`ls /usr/local/lib`
```
ImageMagick-7.0.7          libMagickCore-7.Q16HDRI.la  libMagickCore-7.Q16HDRI.so.4      libMagickWand-7.Q16HDRI.a   libMagickWand-7.Q16HDRI.so    libMagickWand-7.Q16HDRI.so.4.0.0  python3.5
libMagickCore-7.Q16HDRI.a  libMagickCore-7.Q16HDRI.so  libMagickCore-7.Q16HDRI.so.4.0.0  libMagickWand-7.Q16HDRI.la  libMagickWand-7.Q16HDRI.so.4  pkgconfig
```

I tried to create symlink for  `libMagickWand-7.Q16HDRI.so.4.0.0` as `im.so` but have new error:

>16:21:14 ERROR:   FAILED  plugin 1: /usr/local/lib/im.so: undefined symbol: im_check }

I don't have any idea where I can find `im.so` file.

**Comment by openlink** [comment]
Hi,

im.so is built as part of the Virtuoso build process.  This will generate a
consistent virtuoso.ini with the right path for hosted modules. Trying to
symlink other libraries to im.so will not work.

After some investigation here, what's happened is that the structure of
ImageMagick packages has changed in certain distributions, and where we
previously used to check for `Wand-config', that has been moved into a
deeper subdirectory outwith people's PATH so we should now also use
pkg-config.


There will be a patch pushed to git in the next couple of hours, so the
best solution is a short wait and then:

git pull
git clean -df
./autogen.sh
./configure  --enable-maintainer-mode --enable-imagemagick
[optionally, --prefix=/usr/local/stow/vos  or similar to taste]
make clean
make -j 4 all
make install


Given my suggested prefix above, this will produce a file
/usr/local/stow/vos/lib/virtuoso/hosting/im.so

and in virtuoso.ini, you want:


[Plugins]
LoadPath                        = /usr/local/stow/vos/lib/virtuoso/hosting
Load1                           = plain, wikiv
Load2                           = plain, mediawiki
Load3                           = plain, creolewiki
Load4                   = plain, im


After the `make install' command, if you were to run

find /usr/local/ -iname im.so

then that should show where it's been installed.

An alternative is just to put the directory containing Wand-config at the
top of your PATH environment variable before running ./configure.

HTH,

~Tim
-- 
Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by popsovik** [comment]
```
git pull
git clean -df
./autogen.sh
```

```
Running autoconf ...

** ERROR **
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:1275: error: possibly undefined macro: AC_MSG_WARN

Bootstrap script aborting (see autogen.log for details) ...
```

```
autogen.log 
```

```
libsrc/util/Makefile.am:36: but option 'subdir-objects' is disabled
configure.ac:331: error: possibly undefined macro: AC_PATH_PROG
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:1275: error: possibly undefined macro: AC_MSG_WARN
```

**Comment by openlink** [comment]
Hi,

OK, that's odd.

What version of what distribution are you running?

What version of autoconf do you have, e.g. from running
aclocal --version

?

Thanks,

~Tim
-- 
Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by popsovik** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

aclocal --version
aclocal (GNU automake) 1.15

**Comment by openlink** [comment]
Hi,

OK, that's interesting. I'm on 17.04 here with no problems. So. Please can
you send the config.log so we can check it?

Thanks,

-- 
~Tim
-- 
Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by openlink** [comment]
Also please can you include the autogen.log as well. Thanks


-- 
~Tim
-- 
Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by popsovik** [comment]
[autogen.log](https://github.com/openlink/virtuoso-opensource/files/1340760/autogen.log)
[config.log](https://github.com/openlink/virtuoso-opensource/files/1340761/config.log)

**Comment by popsovik** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty

./autogen.sh
```
Running autoconf ...

** ERROR **
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:1275: error: possibly undefined macro: AC_MSG_WARN

Bootstrap script aborting (see autogen.log for details) ...
```

./configure --enable-maintainer-mode --enable-imagemagick

```
configure: WARNING: The hslookup plugin will not be build
./configure: line 17921: syntax error near unexpected token `IM,'
./configure: line 17921: `PKG_CHECK_MODULES_STATIC(IM, MagickWand, ,'
```

**Comment by openlink** [comment]
Hi,

Thanks for these. The autogen.log shows autogen.sh aborting with an error
about AC_PATH_PROG.

However it works for me locally with both Ubuntu 16.04 and 17.04.

I recall an earlier comment in which you appear to have a custom
ImageMagick 7 installation under /usr/local/  Let's first try and get it
working with the regular 6.x packages and then you can try switching later;
so, please check your PATH that Ubuntu's version 6.x is being picked-up
first.

I suggest, first please try a complete git clone into a new subdirectory,
in case there's some cruft lying around in the existing build directory.

Second, if that doesn't work, reinstall the more obvious important OS
development packages:

sudo aptitude reinstall automake autoconf build-essential dpkg-dev libtool
make m4


While we're here, I suspect Ubuntu have broken their imagemagick
development packages; when our configure script asks what libraries to use,
it tells us `-lfftw3' but no package fulfilling that is installed through
apt. Hence, also,

sudo aptitude install libfftw3-dev


On ubuntu 17.04 I have these magick-related packages installed:

imagemagick-6-common libmagick++-6-headers libmagick++-6.q16-7 \
libmagick++-6.q16-dev libmagickcore-6-arch-config libmagickcore-6-headers \
libmagickcore-6.q16-3 libmagickcore-6.q16-3-extra libmagickcore-6.q16-dev \
libmagick++-dev libmagickwand-6-headers libmagickwand-6.q16-3 \
libmagickwand-6.q16-dev



On ubuntu 16.04 it's:

imagemagick-common libmagick++-6-headers libmagick++-6.q16-5v5 \
libmagick++-6.q16-dev libmagickcore-6-arch-config libmagickcore-6-headers \
libmagickcore-6.q16-2 libmagickcore-6.q16-2-extra libmagickcore-6.q16-dev \
libmagickcore-dev libmagick++-dev libmagickwand-6-headers \
libmagickwand-6.q16-2 libmagickwand-6.q16-dev libmagickwand-dev


If you install all of one or other block of those, and libfftw3-dev as
stated, you *will* be able to build your own im.so.

Regards,

~Tim


-- 
~Tim
-- 
Tim Haynes
Product Development Consultant
OpenLink Software
<http://www.openlinksw.com/>
<http://twitter.com/openlink>

**Comment by popsovik** [comment]
Ok. Thank You for help!

I create new clear VM with ubuntu 16.04 and install all dependencies packages and additional i install next packages:
```
imagemagick
libmagick++-6.q16-dev
libfftw3-dev
libmagickcore-dev
libmagick++-dev
libmagickwand-dev
```
It works! I find `im.so` and I can use PivotViewer.

**Comment by mediaprophet** [comment]
I found this thread useful when installing on Ubuntu 16.04.  
The main thing i found was that v6 works, v7 does not.

**Comment by logicfish** [comment]
This is what I'm getting from develop/7 on debian 9.8
```
00:20:11 { Loading plugin 4: Type `plain', file `im' in `/opt/virtuoso/lib/virtuoso/hosting
00:20:11   IM version 0.62 from OpenLink Software
00:20:11   Support functions for Image Magick 6.9.7
00:20:11   FAILED  plugin 4: Loaded plugin requires core functionality not provided by main application }
```
