### ISSUE TITLE
JDBC over use of finalize methods

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#685]
In our production use case we have seen our tomcat go down with GC overhead exceeded exceptions. This seems to be due to a high number of outstanding finalizer references.
This is not often an issue and our monitoring system deals with this nicely.
However, I think a general review of the use of what work finalize methods are doing should be undertaken.

For example the finalize method in VirtuosoStatement calls close on the VirtuosoResultSetMetaData. However that is not a great idea as VirtuosoResultSetMetaData has it's own finalize method. Such cycles can cause issues on a long finalizer queue. The same finalizer currently also calls close_rs(true) via close(). Which does no work at all.

I think the changes in https://github.com/JervenBolleman/virtuoso-opensource/tree/nofinalizerneeded are safe to apply. Further review would be appreciated on the other cases.

**Comment by JervenBolleman** [comment]
@smalinin I went through all the finalizers, but wouldn't mind discussing which ones are really needed or not.

**Comment by smalinin** [comment]
I will recheck all.

**Comment by smalinin** [comment]
The patches will be applied exclude update for finalizer in VirtuosoStatement(I added comment for it)

**Comment by smalinin** [comment]
Patches were added
