### ISSUE TITLE
Error in chash.c

### ISSUE THREAD

**Issue by lolive** [openlink/virtuoso-opensource#69]
Hello.
I try to compile develop/7 and get this log error after compilation:
chash.c:5796 chash.c expects 64 bit pointers, they are cast to and from int64

Is it something that can be corrected?
I am on a (quite old) 32 bit Intel PC.

**Comment by openlink** [comment]
At this point in time the virtuoso-opensource 7 version in develop/7 is 64bit only.

We are currently contemplating if we should continue to support 32bit environments with V7. 

Please feel free to send me a comment advocating why you feel this project should still maintain a 32bit version.

Note that the Virtuoso 6 release is available for both 32 and 64bit environments.

**Comment by indeyets** [comment]
just a notice: if @openlink decides that 32-bit support should be ditched it would be a good idea to detect this on `configure` stage, so, that build doesn't even start

**Comment by openlink** [comment]
I have just committed a (temp) fix in configure.in to check for 64bit platforms

**Comment by ghost** [comment]
Virtuoso OSE is backend for Nepomuk (Sebastian Trueg's child) in KDE-based Linux distributions. Depending on the way it's packaged there, V7 may be unavailable to arm/x86 distro users (ppc will become more and more marginal) or unavailable at all (distros will stay with V6).
Btw, what happens to V6 after V7 release? Is it developed/maintained in parallel or development/maintenance switches to V7 exclusively?
MM (distro packager)
