### ISSUE TITLE
sparql substr function does not follow specification

### ISSUE THREAD

**Issue by JervenBolleman** [openlink/virtuoso-opensource#692]
The query 

```sparql
select ?substr where {BIND(substr("1234567890", 0, 11) AS ?substr)} LIMIT 1
```
should return the string "1234567890" not an error. see the [specification and examples]("https://www.w3.org/TR/xpath-functions/#func-substring')

**Comment by HughWilliams** [comment]
@JervenBolleman: I have been able to recreate this issue and have reported to development to look into and fix (btw: also saw your thread on the Jena mailing list indicating this same query runs against it) ...

**Comment by openlink** [comment]
I pushed a fix for this issue into the develop/7 branch for testing

**Comment by JervenBolleman** [comment]
It works as far as my testing goes. Thank you for fixing this and all the other great work your team is doing.
