### ISSUE TITLE
Virtuoso crash “search.c:326 box_serial_length not supported for data type”

### ISSUE THREAD

**Issue by TallTed** [openlink/virtuoso-opensource#697]
Opened on behalf of Thomas Francart, @tfrancart

(also posted to Virtuoso-Users mailing list, https://sourceforge.net/p/virtuoso/mailman/message/36089665/)

(copy of https://stackoverflow.com/questions/46912359/virtuoso-crash-search-c326-box-serial-length-not-supported-for-data-type)

I am connecting to a Virtuoso 7.20.3216 compiled and installed inside a VirtualBox CentOS 7.3 64bit, using the RDF4J Virtuoso adapter.

I try to load a Turtle file in Virtuoso using this code :

```
Repository r = new virtuoso.rdf4j.driver.VirtuosoRepository(url, login, password);
RepositoryConnection connection = r.openConnection();

ByteArrayOutputStream baos = new ByteArrayOutputStream();
// Turtle data written inside baos

String graphUri = ... ;
connection.add(new ByteArrayInputStream(baos.toByteArray()), RDF.NAMESPACE, RDFFormat.TURTLE, SimpleValueFactory.getInstance().createIRI(graphUri));
```

Virtuoso crashes (stops) with the following logs :

```
12:10:01 box_serial_len called with dtp 225
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x8c6d3a]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x8c6d98]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x4fba85]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x629664]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x629997]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x622485]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x65233d]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x6524dd]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x592328]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x59a807]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x59760a]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x5c0e30]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x5ca63b]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x59370c]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x597d13]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x5c0e30]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x5cbeee]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x5d3d36]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t(sf_sql_execute_w+0x7b) [0x5d3edb]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x8cb297]
12:10:01 /usr/local/virtuoso-opensource/bin/virtuoso-t() [0x8d1683]
12:10:01 /lib64/libpthread.so.0(+0x7e25) [0x7fe04db7ee25]
12:10:01 /lib64/libc.so.6(clone+0x6d) [0x7fe04d3a634d]
12:10:01 GPF: search.c:326 box_serial_length not supported for data type
```

The same Turtle string, when uploaded to the conductor back-office, works properly. The file is pretty large so I can't paste it here.

We have narrowed down the problem to a character encoding issue. The turtle file contains literals with accented characters such as `"Disque à gravure directe"@fr`.

We haven't set any character encoding parameters, neither on the Virtuoso config side, nor in the JDBC connection side. We tried by adding `charset=UTF-8` in the JDBC connection string, with no luck.

It seems also that the problem only arises when the database is empty. When the database already contains some data, Virtuoso does not crash.

Any idea on

what the error message means?
how to get some additionnal logs ?
what could be the cause of the problem?
how to fix or work around this?
Thanks!

**Comment by dikshantshahi** [comment]
We are also facing the same issue with Virtuoso Jena adapter. The same code is working in one environment but throwing the below error in another environment. Virtuoso fails to upload even a small ttl and the instance crashes.

```
19:26:19 Server online at 1111 (pid 9168)
19:35:38 box_serial_len called with dtp 225
19:35:38 GPF: ..\libsrc\Wi\search.c:326 box_serial_length not supported for data type 
```

Below is the code block:

```
// connect
conn = vClient.getConnection(graphName);

// clear existing statements, if any
conn.clear();

// export
vModel = new VirtModel(conn);
vModel.begin();
vModel.read(is, null, rdfFormat);
vModel.commit();

```

Upload from connector works in the failing environment.

**Comment by HughWilliams** [comment]
A fix for this issue is in the git develop/7 branch, see:

   https://github.com/openlink/virtuoso-opensource/commit/a6719e8f4e3e056235cb1b5aac574d63b82b46e3
