### ISSUE TITLE
Loose-coupling of persistent storage

### ISSUE THREAD

**Issue by sdmonroe** [openlink/virtuoso-opensource#698]
Hi,

[This is in relation to the virtuoso-devel thread "Blockchain-backed 'SAIL' for Virt".]

I've been examining the Virtuoso codebase to determine how to abstract the disk.c code in such a way as to allow the xyz.db file to be swapped for other persistence mechanisms so that "rather than being pegged to "xyz.db" you end up being able to use a variety of document types (CSV, ORC, Parquet etc..)". I concluded that the path of least resistance is to swap xyz.db for a named pipe, e.g. a [FIFO special file](http://www.gnu.org/software/libc/manual/html_node/FIFO-Special-Files.html), then have a custom script on one end of the pipe. My question is, is this something we can put on the roadmap? My ultimate goal is to have the file be implemented by a eos.io smart contract, which would allow the blockchain to model, and manage concurrent i/o for, a file of infinite length. Then, have multiple instances of Virtuoso all share that "virtual file" as their xyz.db, effectively creating one infinitely scaleable quad-store to serve unlimited Virtuoso clients.

**Comment by HughWilliams** [comment]
If you want to retract the issue then the git issue can just be closed ...
