### ISSUE TITLE
xsd:boolean literals returned as xsd:string literals by RDF4J provider 

### ISSUE THREAD

**Issue by knoan** [openlink/virtuoso-opensource#701]
# Environment

- Virtuoso Open Source v07.20.3217
- Virtuoso RDF4J Provider v2.1.4
- Virtuoso JDBC driver v4.0

# How To Reproduce 

Run the following java snippet on a fresh database

```java
final ValueFactory factory=SimpleValueFactory.getInstance();

final IRI x=factory.createIRI("test:x");
final Literal value=factory.createLiteral(true);

final VirtuosoRepository repository
    =new VirtuosoRepository( "jdbc:virtuoso://localhost/", "dba", "dba");

repository.initialize();

try (RepositoryConnection connection=repository.getConnection()) {

    connection.add(x, x, value);

    System.out.println(connection.getStatements(x, x, null).next().getObject());

} finally {
    repository.shutDown();
}
```

# Expected Output

`"true"^^<http://www.w3.org/2001/XMLSchema#boolean>`

# Actual Output

`"true"^^<http://www.w3.org/2001/XMLSchema#string>`

**Comment by smalinin** [comment]
Fixed, the fix will be in Git soon. Now you could use the next fresh build 
[virt_rdf4j.zip](https://github.com/openlink/virtuoso-opensource/files/1572184/virt_rdf4j.zip)
