### ISSUE TITLE
Namespaces not persisted by RDF4J provider

### ISSUE THREAD

**Issue by knoan** [openlink/virtuoso-opensource#702]
# Environment

- Virtuoso Open Source v07.20.3217
- Virtuoso RDF4J Provider preview as provided in https://github.com/openlink/virtuoso-opensource/issues/701#issuecomment-352794551
- Virtuoso JDBC driver v4.0

# How To Reproduce

Run the following java snippet on a fresh database:

```java
public static void main(final String... args) {

	final Repository repository=new VirtuosoRepository(
		"jdbc:virtuoso://localhost/", "dba", "dba");

	repository.initialize();

	try (RepositoryConnection connection=repository.getConnection()) {

		connection.setNamespace("", "http://example.com/terms/");

		System.out.println(connection.getNamespace(""));

	}

	try (RepositoryConnection connection=repository.getConnection()) {

		System.out.println(connection.getNamespace(""));

	}

	repository.shutDown();

}
```

# Expected Output

```
http://example.com/terms/
http://example.com/terms/
```

Actual Output

```
http://example.com/terms/
null
```

**Comment by smalinin** [comment]
The RDF4J provider stored Namespaces in the connection hash. I updated code for store Namespaces in the global cache. Try the next fresh build 
[virt_rdf4j.zip](https://github.com/openlink/virtuoso-opensource/files/1576368/virt_rdf4j.zip)

**Comment by knoan** [comment]
Up and running. Thanks
