### ISSUE TITLE
regex filter with case insensitive flag does not match letters with accents

### ISSUE THREAD

**Issue by yyz1989** [openlink/virtuoso-opensource#705]
Hi,

Given a string literal containing letters with accents like "Wärme", the query
```
select ?o where {?s ?p ?o filter(regex(str(?o), 'ä', 'i'))}
```
does not match the literal. While
```
select ?o where {?s ?p ?o filter(regex(str(?o), 'ä'))}
```
does so, but we cannot match different cases any more. This should be a bug.

Interestingly,
```
ask {filter(regex('Wärme', 'ä', 'i'))}
```
works properly.

Many thanks for the investigation.

Best regards,
Yang

**Comment by HughWilliams** [comment]
@yyz1989: I have been able to recreate this issue inserting the following triple into a Virtuoso database:

```
INSERT INTO GRAPH <http://example.org> { <1> <2> "Wärme" }
```

and reported to development to look into ...

**Comment by KonradHoeffner** [comment]
I noticed the same problem with Persian letters on Virtuoso 07.20.3229, e.g. the current DBpedia endpoint:

```
select *
{
  <http://dbpedia.org/resource/Persian_language> dbo:abstract ?l.    
  filter(regex(str(?l),"فارسی","i")).
}
```

In case someone needs some workarounds, see https://stackoverflow.com/questions/53560508/sparql-regex-doesnt-match-persian-characters-with-the-i-flag

For example, not using the `str` function does not cause this error:

```
select *
{
  <http://dbpedia.org/resource/Persian_language> dbo:abstract ?l.    
  filter(regex(?l,"فارسی","i")).
}
```

**Comment by ethieblin** [comment]
Hello, has this bug been fixed ? We have issues working around it in some SPARQL consumer tools:
https://github.com/sparna-git/Sparnatural/issues/471

**Comment by HughWilliams** [comment]
This issue is still to be fixed by development, and I have notified them of your report as reminder for it to be looked into and fixed ...

**Comment by xgaia** [comment]
thanks @HughWilliams ! can you make a [release](https://github.com/openlink/virtuoso-opensource/releases) with this fix ?
