### ISSUE TITLE
Virtuoso Jena Provider: VirtGraph.getBulkUpdateHandler() method not available

### ISSUE THREAD

**Issue by dikshantshahi** [openlink/virtuoso-opensource#708]
I downloaded Virtuoso Jena Provider For Jena 3.0.x and later from URL http://vos.openlinksw.com/owiki/wiki/VOS/VOSDownload#Jena%20Provider. The class in the jar file doesn't contain the VirtGraph.getBulkUpdateHandler() method.

Has the API changed or something is missing? The provided example VirtuosoSPARQLExample7 provides an usage example though.

**Comment by smalinin** [comment]
The method Graph.getBulkUpdateHandler() was deprecated in Jena3 API and the example  VirtuosoSPARQLExample7 isn't existed in Jena3 provider sources => https://github.com/openlink/virtuoso-opensource/tree/develop/7/binsrc/jena3/virtuoso_driver . 
You could to use another Jena3 methods, for example from VirtModel class
```
    public Model add(Statement[] statements);
    public Model add(List<Statement> statements);
    public Model add(StmtIterator iter);
    public Model add(Model m);

    public Model remove(Statement[] statements);
    public Model remove(List<Statement> statements);
    public Model remove(Model m);

```
or etc.
