### ISSUE TITLE
Virtuoso performance issue when hosting Freebase

### ISSUE THREAD

**Issue by lkq1992yeah** [openlink/virtuoso-opensource#711]
I have set up a virtuoso server for hosting Freebase data, and encountered performance issues.
Let's consider this scenario: find the largest location (probably a county, denoted by ?var1) in Wisconsin State (m.0824r), where ?var1 contains at least one location (denoted by ?var2) with the type "place_with_neighborhoods".
I wrote the SPARQL query as follows:

    PREFIX fb: <http://rdf.freebase.com/ns/> 
    SELECT DISTINCT ?var1 ?var2 ?v2_name WHERE {
      fb:m.0824r fb:location.location.contains ?var1 . 
      ?var1 fb:location.location.contains ?var2 . 
      ?var2 fb:type.object.type fb:location.place_with_neighborhoods . 
      ?var1 fb:location.location.area ?area .
      OPTIONAL {?var2 fb:type.object.name ?v2_name} .
    } ORDER BY DESC(?area) LIMIT 1

Unfortunately, the virtuoso engine fail to return the query result for more than one hour.

I tried some simpler queries, which could produce results in less than one second:

    PREFIX fb: <http://rdf.freebase.com/ns/> 
    SELECT DISTINCT ?var1 ?var2 ?v2_name WHERE {
      fb:m.0824r fb:location.location.contains ?var1 . 
      ?var1 fb:location.location.contains ?var2 . 
      ?var2 fb:type.object.type fb:location.place_with_neighborhoods . 
      OPTIONAL {?var2 fb:type.object.name ?v2_name} .    
    }
    # Remove the area-related information with ?var1
    # Returns ONLY ONE result in 0.05s.

and,

    PREFIX fb: <http://rdf.freebase.com/ns/> 
    SELECT DISTINCT ?var1 ?var2 ?v2_name ?area WHERE {
      fb:m.0824r fb:location.location.contains ?var1 . 
      ?var1 fb:location.location.contains ?var2 . 
      ?var1 fb:location.location.area ?area .
      OPTIONAL {?var2 fb:type.object.name ?v2_name} .
    }
    # Remove the type limitation of ?var2
    # Returns ~7000 results in ~1s.

Given the results of those simpler queries, I'm really confused which step brought the performance issue. Is there anybody who can give me some advice? Thank you so much!

**Comment by TallTed** [comment]
Next time, please provide the same information here as [you did on StackOverflow](https://stackoverflow.com/questions/48729471/how-to-make-sparql-queries-faster-on-virtuoso-by-controlling-query-execution-ord) -- especially, the [link to your active server](http://202.120.38.146:8999/sparql), which is running VOS 07.20.3217, built Jan 5 2017.

There appears to be a query plan issue with `OPTIONAL` when the rest of the query produces no solution, as removing only that clause from your initial query [brings results near instantly](http://202.120.38.146:8999/sparql?default-graph-uri=&qtxt=PREFIX+fb%3A+%3Chttp%3A%2F%2Frdf.freebase.com%2Fns%2F%3E+%0D%0ASELECT+DISTINCT+%3Fvar1+%0D%0A++++++++++++++++%3Fvar2+%0D%0A++++++++++++++%23+%3Fv2_name+%0D%0AWHERE+{%0D%0A++++++++++++++fb%3Am.0824r++fb%3Alocation.location.contains++%3Fvar1+.+%0D%0A++++++++++++++%3Fvar1+++++++fb%3Alocation.location.contains++%3Fvar2+.+%0D%0A++++++++++++++%3Fvar2+++++++fb%3Atype.object.type++++++++++++fb%3Alocation.place_with_neighborhoods+.+%0D%0A++++++++++++++%3Fvar1+++++++fb%3Alocation.location.area++++++%3Farea+.%0D%0A%23++OPTIONAL+{+%3Fvar2+++++++fb%3Atype.object.name++++++++++++%3Fv2_name+}+.%0D%0A}+ORDER+BY+DESC%28%3Farea%29+LIMIT+1%0D%0A&format=text%2Fhtml&timeout=0&debug=on).

Removing the `?var1 fb:location.location.area ?area` pattern (and therefore, the `ORDER BY DESC(?area)`), which is what reduces the solution set to zero, likewise [brings near instant results](http://202.120.38.146:8999/sparql?default-graph-uri=&qtxt=PREFIX+fb%3A+%3Chttp%3A%2F%2Frdf.freebase.com%2Fns%2F%3E+%0D%0ASELECT+DISTINCT+%3Fvar1+%0D%0A++++++++++++++++%3Fvar2+%0D%0A+++++++++++++++%3Fv2_name+%0D%0AWHERE+%7B%0D%0A++++++++++++++fb%3Am.0824r++fb%3Alocation.location.contains++%3Fvar1+.+%0D%0A++++++++++++++%3Fvar1+++++++fb%3Alocation.location.contains++%3Fvar2+.+%0D%0A++++++++++++++%3Fvar2+++++++fb%3Atype.object.type++++++++++++fb%3Alocation.place_with_neighborhoods+.+%0D%0A%23++++++++++++++%3Fvar1+++++++fb%3Alocation.location.area++++++%3Farea+.%0D%0A++OPTIONAL+%7B+%3Fvar2+++++++fb%3Atype.object.name++++++++++++%3Fv2_name+%7D+.%0D%0A%7D+%0D%0A%23+ORDER+BY+DESC%28%3Farea%29+%0D%0ALIMIT+1%0D%0A&format=text%2Fhtml&timeout=0&debug=on).

**Comment by lkq1992yeah** [comment]
@TallTed Thank you so much for your explanation, and I'll definitely follow your suggestion in the next time!

**Comment by TallTed** [comment]
@lkq1992yeah I have been trying to recreate this against a current build of Virtuoso, without success. I note that you're running a year-old build of a similarly aged code-base. Can you build a fresh binary, from the [current codebase](https://github.com/openlink/virtuoso-opensource/tree/develop/7), and retest with your database?

**Comment by lkq1992yeah** [comment]
@TallTed Sure I will have it a try. Will update this comment once I get some result.

Update on 03/09/18: Issue was solved using the [current codebase](https://github.com/openlink/virtuoso-opensource/tree/develop/7).
Virtuoso version: Version 7.2.5-dev.3217-pthreads as of Mar  9 2018 (000000)
