### ISSUE TITLE
Openlink Virtuoso site is not working

### ISSUE THREAD

**Issue by kotheoha** [openlink/virtuoso-opensource#717]
Hi,

I noticed today that Virtuoso official site is not working. For instance, documentation page cannot get loaded at all. Does someone knows what happens or noticed the same thing?

Thanks,
KT.

**Comment by TallTed** [comment]
Machines get rebooted, bugs bite, maintenance happens, etc.  

In reports like this, it is VERY helpful if you can include specific URLs that you're having issues with.

As of this writing, "[Virtuoso official site](https://virtuoso.openlinksw.com/)" is fine; "[documentation page](https://docs.openlinksw.com/)" is undergoing some work, and should return shortly.

**Comment by kotheoha** [comment]
Hi TallTed,

thanks for your reply!

Actually whatever is under documentation page does not load. Namely, documentation page has the problem. Specifically I cares about RDF spatial support, loading, inserting & updating rdf triples, appendix functions, isql-v and stuff like that and all these are under documentation and are not working. 

Further, Virtuoso documentation page has many interconnected info, so I do not think that it makes sense to find what is working under documentation and what it is not. It must the whole documentation page to work so as to be useful for developing and running experiments in Virtuoso. Many times I follow various interconnected links to find what I was looking to.

So, please let me know when documentation page will be ready!

Thanks,
KT.

**Comment by TallTed** [comment]
Your update did not include any specific URIs, only topics.  It is difficult to check the status of a topic -- which may be addressed by pages on multiple servers, with very different URIs.

In future, *please* include a specific URI -- such as http://docs.openlinksw.com/ or http://vos.openlinksw.com/owiki/wiki/VOS/VirtSpongerLinkedDataHooksIntoSPARQL or whatever page (or service) you try that doesn't load.  That helps us deal with specific issues much more quickly.

In the immediate case, an AMI which hosts several services had hung.  The AMI has now been rebooted, and http://docs.openlinksw.com/ is responding.

**Comment by TallTed** [comment]
@kotheoha - Please close this issue once you've confirmed that the previously problematic services are answering.

**Comment by kotheoha** [comment]
Hi TallTed,
I checked the links and now documentation page it works, so everything is fine.
Thank you for your response!,
KT.

**Comment by kotheoha** [comment]
Hi all,

documentation page http://docs.openlinksw.com/virtuoso/ is again out of
order. Do you know when we will have a recovery?,

Best,
KT.

On Mon, Feb 26, 2018 at 3:58 PM, OpenLink Software <notifications@github.com

**Comment by HughWilliams** [comment]
@kotheoha: The docs server is back online ...
