### ISSUE TITLE
Blank distinct count

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#719]
I get the following results on a large graph for the following queries:

select count(*) where {?s ?p ?o} limit 1
6,204,086,892
select count(?id) where {?s :id ?id} limit 1
53,789,314
select count(distinct ?id) where {?s :id ?id} limit 1
blank screen

Why would I be getting a blank result on the last one?

**Comment by TallTed** [comment]
Knowing only what you've pasted here, I'd bet on a [query timeout](http://docs.openlinksw.com/virtuoso/anytimequeries/) for the last (though you would not ordinarily get a blank screen; more reproduction details may provide the reason for this). 

For fastest confirmation, you can copy the URI for that query's result page from your browser, and do a `curl -LI "that-URI"`.  Look for the `X-SQL-State:` , `X-SQL-Message:` , `X-Exec-Milliseconds:`, and `X-Exec-DB-Activity:` response headers.

**Comment by ebremer** [comment]
It was that.  I increased the maximum query execution time in virtuoso.ini to 15 minutes and the query completed (not that it needed 15 mins, but more than the default).  The blank screen displayed the usual results "callret-0" but with no value rather than the explicit timeout error.  I did not know about the results headers above but they confirmed a timeout condition.
