### ISSUE TITLE
virtuoso.jdbc3.VirtuosoException: HC001: Connection Error in HTTP Client

### ISSUE THREAD

**Issue by ifourvimal** [openlink/virtuoso-opensource#726]
While running query I am getting an error,

```
Class.forName("virtuoso.jdbc3.Driver");

		      String urlDB = "jdbc:virtuoso://192.168.99.100:1111/log_enable=1";

		      Connection conn = DriverManager.getConnection(urlDB,"dba","dba");
		      Statement st;

		      st = conn.createStatement();

		      st.execute("sparql clear graph <http://192.168.99.100/test1>");
		      conn.setAutoCommit(false);

		      

		        String query = "sparql LOAD <src/main/webapp/resources/inputfile/sparqlTest.ttl> INTO GRAPH <http://192.168.99.100/test1>";
		        ResultSet rs = st.executeQuery(query);
		        rs.close();
		      
		      
		      st.close();
		      conn.close();

		    } catch (Exception e) {
		    	e.printStackTrace();
		    }
```

```
virtuoso.jdbc3.VirtuosoException: HC001: Connection Error in HTTP Client
	at virtuoso.jdbc3.VirtuosoResultSet.process_result(Unknown Source)
	at virtuoso.jdbc3.VirtuosoResultSet.<init>(Unknown Source)
	at virtuoso.jdbc3.VirtuosoStatement.sendQuery(Unknown Source)
	at virtuoso.jdbc3.VirtuosoStatement.executeQuery(Unknown Source)
	at com.bordercloud.sparql.virtuoso.VirtuosoSPARQLExample10.main(VirtuosoSPARQLExample10.java:32)
```

**Comment by smalinin** [comment]
It looks, that you tried to use some local path `src/main/webapp/resources/inputfile/sparqlTest.ttl` with SPARQL LOAD command. It will not work, it must be URI ! https://www.w3.org/TR/sparql11-update/#load
If you want to load data from some local file on client side, you must to use Jena or RDF4J Virtuoso providers and a special API (from Jena/RDF4J) for this.

**Comment by TallTed** [comment]
@ifourvimal - [SPARQL `LOAD`](https://www.w3.org/TR/sparql11-update/#load) requires an IRI be used to specify the file to be loaded.

You can use a `file:` scheme IRI for this, *if* the file is both

- on the Virtuoso server host
- in a directory included in `DirsAllowed` in the `[Parameters]` section of the Virtuoso server INI file 

If the file is client-side, there are various other methods you can use, including the Jena or RDF4J methods mentioned by @smalinin.
