### ISSUE TITLE
How to format output when using isql? 

### ISSUE THREAD

**Issue by SteffRhes** [openlink/virtuoso-opensource#727]
When querying virtuoso via the isql shell, is there a way to format the output to the console in such a way that after each variable / column of a 'select' a newline is printed? (As  in mysql with '\G' for example)

We have rather long URIs in our virtuoso instance and when printing those to the console each result line can easily span two console lines, thus making it hard to read.

**Comment by timhaynesopenlink** [comment]
Hi,

Nice and simple:

    SQL> set VERT_ROW_OUTPUT=ON;

HTH!

**Comment by SteffRhes** [comment]
Exactly what I hoped for!! Thanks a lot!
