### ISSUE TITLE
Planned version update on 7.2 release?

### ISSUE THREAD

**Issue by jbkoh** [openlink/virtuoso-opensource#735]
Dear Openlink,

The released version, 7.2 has not been updated for 544 commits since the last release. Is there any plan to update the released opensource version?

Thanks!

**Comment by HughWilliams** [comment]
A new stable/7 branch is being prepared for release from the current develop/7 branch in the coming weeks ...

**Comment by jbkoh** [comment]
That sounds great. Thanks!
