### ISSUE TITLE
connection.prepare*Query() baseURI parameter not handled by RDF4J provider

### ISSUE THREAD

**Issue by knoan** [openlink/virtuoso-opensource#738]
# Environment

- Virtuoso Open Source v07.20.3217
- Virtuoso RDF4J Provider preview as provided https://github.com/openlink/virtuoso-opensource/issues/702#issuecomment-353118432
- Virtuoso JDBC driver v4.0

# How To Reproduce

Run the following java snippet on a fresh database:

```java
public static void main(final String... args) {

	final Repository repository=new VirtuosoRepository(
		"jdbc:virtuoso://localhost/", "dba", "dba"
	);

	repository.initialize();

	try (final RepositoryConnection connection=repository.getConnection()) {

		System.out.println(connection.prepareBooleanQuery(
			QueryLanguage.SPARQL, "ask {}", "app://test/"
		).evaluate());

	} finally {
		repository.shutDown();
	}
}
```

# Expected Output

```
true
```

# Actual Output

```
 Exception:virtuoso.jdbc4.VirtuosoException: SQ074: Line 3: SP031: SPARQL compiler: Unsupported parameter 'input:graph-base' in 'define'
	at virtuoso.rdf4j.driver.VirtuosoRepositoryConnection.executeSPARQLForBooleanResult(VirtuosoRepositoryConnection.java:1856)
	at virtuoso.rdf4j.driver.VirtuosoRepositoryConnection$3.evaluate(VirtuosoRepositoryConnection.java:459)
…
```

# Notes

- affects all prepare<Type>Query() variants (Boolean, Tuple, Graph) and prepareUpdate();
- works as expected if no `baseURI` parameter is supplied, i.e.:

```java
System.out.println(connection.prepareBooleanQuery(
     QueryLanguage.SPARQL, "ask {}"
).evaluate());
```

**Comment by TallTed** [comment]
Looks like there's a typo (or three) in [the Provider source](https://github.com/openlink/virtuoso-opensource/search?utf8=%E2%9C%93&q=%22input%3Agraph-base%22&type=).

The `'input:graph-base'` parameter there should be `'input:grab-base'`, as [documented](http://vos.openlinksw.com/owiki/wiki/VOS/VirtSpongerLinkedDataHooksIntoSPARQL#INPUT%20Pragmas) and in the [engine source](https://github.com/openlink/virtuoso-opensource/search?utf8=%E2%9C%93&q=%22input%3Agrab-base%22&type=).

We should have a code patch, and rebuilt providers, shortly.

**Comment by TallTed** [comment]
Resolved by 2af7f30

**Comment by knoan** [comment]
Do we have a download link for the updated jar?

**Comment by HughWilliams** [comment]
It is in the git sources as are all the prebuilt jar files  ie https://github.com/openlink/virtuoso-opensource/tree/develop/7/binsrc/rdf4j for the RDFJ Provider ...

**Comment by knoan** [comment]
Got it. Thx
