### ISSUE TITLE
extemely slow query

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#740]
I have a v7.2.4.2 installation with 7,004,173,873 triples (32 core machine with 322GB RAM and 1 TB SSD server RHEL 7.X).

The following query takes seconds (there are about 2 dozen named graphs):
```sparql
select distinct ?g where {graph ?g {?s ?p ?o}}
```
however, this query has yet to complete (http://graphA.com and http://graphB.com both exist)
```sparql
select distinct ?g
from named <http://graphA.com>
from named <http://graphB.com>
{graph ?g {?s ?p ?o}}
```
it seems like it should go quicker.

**Comment by HughWilliams** [comment]
@ebremer: Can you please provide the profile and SPARQL-to-SQL translation for both queries for comparison [as documented](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksAanalyzingSPARQLQuery).

Also, what is the purpose of the second query as on it own it doesn't make sense, but I would assume there is some other query using `from named` you are seeking to use which is giving similar problems?

**Comment by ebremer** [comment]
It was a silly query to understand the nuances of `from` and `from named`.  Remarkably, I've been able to avoid using them until this time when I have a meaningful use case for them.  I initially applied them to a more complex query which also didn't finish.  Stripping it down to something simple, I was trying to figure out if it was my understanding of them or something else.  I will get you the profile and the translation.

**Comment by ebremer** [comment]
I was expecting it to come back fairly quick with the two names of the graphs that are specified in the query.
