### ISSUE TITLE
virtuoso conductor error

### ISSUE THREAD

**Issue by byronwwang** [openlink/virtuoso-opensource#743]
Can anyone help me on this? Thank you in advance.
```
12:39:20 PL LOG: Installing Virtuoso Conductor version 1.00.8777 (DAV)
12:39:20 Checkpoint started
12:39:20 Checkpoint finished, log reused
12:39:20 PL LOG: VAD_INSTALL: Please update server version (FATAL)
12:39:20 PL LOG: Errors where detected during installation of "Virtuoso Conductor".
```

**Comment by TallTed** [comment]
Sorry for not answering sooner...

It looks like you're trying to install a Conductor VAD built for a newer version of Virtuoso (e.g., 8.0) on an older Virtuoso binary (e.g., 7.0).

If you provide the full version string for your Virtuoso binary, we can provide appropriate links/recommendations.

**Comment by TallTed** [comment]
@byronwwang -- To speed things along... 

We provide VADs for all versions of [Enterprise Edition](http://download3.openlinksw.com/index.html?prefix=uda/vad-packages/) and [Open Source Edition (VOS)](http://download3.openlinksw.com/index.html?prefix=uda/vad-vos-packages/).

If you cannot figure out which VAD to download, please do provide the specific version of your Virtuoso binary (the first "paragraph" of output from `virtuoso-iodbc-t -?` or `virtuoso-t -?`), and describe the VAD you want; we can give you the correct filename and/or direct link.

Please let us know if this information resolves your issue.

**Comment by HuuuNan** [comment]
@TallTed Hello，TallTed.
I encountered the same problem，the PL LOG said i should update my server version.But i dont know how to check and update my version of Virtuoso binary.
Use command "virtuoso-iodbc-t -?" or "virtuoso-t -?" to check the version?But cannot find the command "virtuoso".

**Comment by TallTed** [comment]
@HuuuNan - In the Virtuoso installation `/bin/` directory, there should be at least one binary, named `virtuoso-iodbc-t` (for Enterprise Edition) or `virtuoso-t` (for Open Source Edition).

Our installation scripts typically create a symlink from `virtuoso` in the same directory, but this may not be present for you for various reasons.

You can simply adjust the command to include the full path to the binary, as in any of these --

 * `/opt/openlink/virtuoso/bin/virtuoso-iodbc-t -?`
 * `/opt/virtuoso/bin/virtuoso-t -?`
 * `/home/userid/virtuoso/bin/virtuoso-t -?`
 * `./virtuoso-t -?`

The information we're looking for will look something like this --
```
OpenLink Virtuoso Universal Server (Enterprise Edition)
Version 08.01.3307-pthreads as of Apr 24 2018 (c48a21052a)
Compiled for Mac OS X (universal-apple-macosx10.10-32)
Hosted Runtime Environments:  VDB
Copyright (C) 1998-2018 OpenLink Software
```

**Comment by HuuuNan** [comment]
@TallTed 
I am sorry to reply to your message late.I find the reason,I installed the version 6.18 of Virtuoso before and now I solve my problem.Thank you!
