### ISSUE TITLE
Error S0022: SQ200: No column RES_CREATOR on opening Conductor

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#745]
In ea35084579a8b3820cb346941c168b5935840e80 when I go to ```http://localhost:8890/conductor/``` I get:
```
Error S0022
SQ200: No column RES_CREATOR.
```

**Comment by timhaynesopenlink** [comment]
Hi,

This is a known issue. I encountered the same thing yesterday and development are looking into it now. Hoping for a fix soon.

HTH,

~Tim

**Comment by pkleef** [comment]
I pushed a fix to develop/7 that fixes this problem

**Comment by jakubklimek** [comment]
Confirmed
