### ISSUE TITLE
After restart, latest develop loses language tags

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#747]
After update to fa9e8ca8cea6e92bf903fa51e9388402ab0d9b44 from ea35084579a8b3820cb346941c168b5935840e80, all language tags went missing from the database. I had to reload the data to fix it.

**Comment by HughWilliams** [comment]
@jakubklimek: We are going to try and recreate this issue and will let you know the outcome or if additional information is needed ...

**Comment by pkleef** [comment]
@jakubklimek Is it possible to email me some sample data so i can see what combination of types and languages you are using in your data?

**Comment by jakubklimek** [comment]
@pkleef This happend with and instance which had [this dump](http://data.gov.cz/soubor/nkod.trig) loaded. A sample can be seen e.g. in https://data.gov.cz/zdroj/datová-sada/https---data.cssz.cz-api-3-action-package_show-id-kontroly-plneni-povinnosti-zamestnavatelu-v-oblasti-socialniho-zabezpeceni or any other dataset from https://data.gov.cz.

**Comment by pkleef** [comment]
I have attempted to recreate the issue by loading the data from nkod.trig into a fresh database using virtuoso:

    Version 7.2.5-dev.3217-pthreads as of Jun 19 2018 (ea35084)

After that i ran the following small query to check for language tags:

```
SQL> sparql select distinct ?o lang(?o) as ?lang where {?s <http://www.w3.org/ns/dcat#keyword> ?o} limit 10;
o                                                                                 lang
LONG VARCHAR                                                                      LONG VARCHAR
_______________________________________________________________________________

RÚIAN                                                                            cs
současnost                                                                       cs
stav                                                                              cs
CSV                                                                               cs
adresy                                                                            cs
DGN                                                                               cs
Katastrální mapa                                                                cs
SHP                                                                               cs
Obce                                                                              cs
historie                                                                          cs

10 Rows. -- 62 msec.
```
Next i did a proper shutdown and then i started the following virtuoso binary:

    Version 7.2.5-rc1.3217-pthreads as of Jun 19 2018 (fa9e8ca)

and ran the above query again and got the exact same results:

```
SQL> sparql select distinct ?o lang(?o) as ?lang where {?s <http://www.w3.org/ns/dcat#keyword> ?o} limit 10;
o                                                                                 lang
LONG VARCHAR                                                                      LONG VARCHAR
_______________________________________________________________________________

RÚIAN                                                                            cs
současnost                                                                       cs
stav                                                                              cs
CSV                                                                               cs
RÚIAN                                                                            cs
adresy                                                                            cs
DGN                                                                               cs
Katastrální mapa                                                                cs
Katastrální mapa                                                                cs
SHP                                                                               cs

10 Rows. -- 139 msec.

```

Can you give me some SPARQL query you yourself used on this dataset to verify language tags where missing?

**Comment by jakubklimek** [comment]
@pkleef Thanks for trying. Actually now I found one instance which is still on ea35084579a8b3820cb346941c168b5935840e80 and the error is already there - no language tags. According to my git log, the version before that was actually f46a3f7213848499a06109f86a0a86058b10b194. So the sequence was having f46a3f7213848499a06109f86a0a86058b10b194, loading the TriG file, and then upgrading to ea35084579a8b3820cb346941c168b5935840e80. Other instances were probably updated without reloading the data all the way to fa9e8ca8cea6e92bf903fa51e9388402ab0d9b44 with already having the error there.

No special query needed, I simply do (using the sparql endpoint):
```sparql
select distinct ?g where {graph ?g {?s ?p ?o}}
```
and then pick one of the graphs and do
```sparql
select * where { GRAPH <https://nkod.opendata.cz/zdroj/datová-sada/http---atom.cuzk.cz-api-3-action-package_show-id-cz-00025712-cuzk_uhdp_1-20000101> {?s ?p ?o} }
```
where `https://nkod.opendata.cz/zdroj/datová-sada/http---atom.cuzk.cz-api-3-action-package_show-id-cz-00025712-cuzk_uhdp_1-20000101` is the graph url on our ea35084579a8b3820cb346941c168b5935840e80 development instance https://dev.nkod.opendata.cz/sparql.

In the result I see e.g.
```
"https://linked.opendata.cz/zdroj/ekonomický-subjekt/00025712","http://xmlns.com/foaf/0.1/name","Český úřad zeměměřický a katastrální"
```
where originally, it was 
```
"https://linked.opendata.cz/zdroj/ekonomický-subjekt/00025712","http://xmlns.com/foaf/0.1/name","Český úřad zeměměřický a katastrální"@cs
```
like it can be seen in https://data.gov.cz/sparql using:
```sparql
select * where { GRAPH <https://data.gov.cz/zdroj/datová-sada/http---atom.cuzk.cz-api-3-action-package_show-id-cz-00025712-cuzk_ruian-s-za-z_1-z-20180618> {?s ?p ?o} }
```

**Comment by jakubklimek** [comment]
@pkleef Now I tested some more and realized it is not connected to the upgrade process, the issue is much simpler. The newer versions loose language tags simply when restarted.
Data: [data.zip](https://github.com/openlink/virtuoso-opensource/files/2155374/data.5.zip)
When loaded, the language tags are there. Just to be sure, I run `checkpoint;` and stop the virtuoso service. When I run it again, the language tags are gone.
Using this query:
```sparql
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX ds: <https://data.gov.cz/slovník/datové-schránky/>
PREFIX ovm: <https://data.gov.cz/slovník/ovm/>

CONSTRUCT {
?ds a ds:DatováSchránka.
?be ds:datová-schránka ?ds ;
    gr:legalName ?name.
} 
WHERE {
?ds a ds:DatováSchránka ;
    ^ovm:datováSchránka ?be .
OPTIONAL { ?be gr:legalName ?name .}
}
```
on this named graph: `https://data.gov.cz/zdroj/datová-sada/seznam-ovm`

I may be running a tad old init script:
```shell
#! /bin/sh
#
# virtuoso      OpenLink Virtuoso Open-Source Edition
#
#               Written by OpenLink Virtuoso Maintainer
#               <vos.admin@openlinksw.com>
#
# Version:      @(#)virtuoso  6.1.4  25-Mar-2011        vos.admin@openlinksw.com
#

### BEGIN INIT INFO
# Provides:             virtuoso
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Start Virtuoso database server on startup
# Description:          Start and stop the primary instance of Virtuoso running
#       in /var/lib/virtuoso/db/. The first time this runs, it loads the
#       Conductor administrative package.
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
DAEMON=/usr/local/bin/virtuoso-t
NAME=virtuoso
DESC="VOS 7 mvcr2.opendata.cz 8891 DB02 background data"
DBBASE=/data/virtuoso/db02

test -x $DAEMON || exit 0

LOGDIR=/data/virtuoso/db02
PIDFILE=$DBBASE/$NAME.lck
DODTIME=1                   # Time to wait for the server to die, in seconds
                            # If this value is set too low you might not
                            # let some servers to die gracefully and
                            # 'restart' will not work

# Include virtuoso-opensource defaults if available
if [ -f /etc/default/virtuoso-opensource ] ; then
        . /etc/default/virtuoso-opensource
fi

set -e

running_pid()
{
    # Check if a given process pid's cmdline matches a given name
    pid=$1
    name=$2
    [ -z "$pid" ] && return 1
    [ ! -d /proc/$pid ] &&  return 1
    cmd=`cat /proc/$pid/cmdline | tr "\000" "\n"|head -n 1 |cut -d : -f 1`
    # Is this the expected child?
    [ "$cmd" != "$name" ] &&  return 1
    return 0
}

running()
{
# Check if the process is running looking at /proc
# (works for all users)

    # No pidfile, probably no daemon present
    [ ! -f "$PIDFILE" ] && return 1
    # Obtain the pid and check it against the binary name
    . $PIDFILE
    pid="$VIRT_PID"
    running_pid $pid $DAEMON || return 1
    return 0
}

force_stop() {
# Forcefully kill the process
    [ ! -f "$PIDFILE" ] && return
    if running ; then
        kill -15 $pid
        # Is it really dead?
        [ -n "$DODTIME" ] && sleep "$DODTIME"s
        if running ; then
            kill -9 $pid
            [ -n "$DODTIME" ] && sleep "$DODTIME"s
            if running ; then
                echo "Cannot kill $LABEL (pid=$pid)!"
                exit 1
            fi
        fi
    fi
    rm -f $PIDFILE
    return 0
}

case "$1" in
  start)
        echo -n "Starting $DESC: "
        cd "$DBBASE" || exit -1
        $DAEMON -c $NAME +wait
        if running ; then
            echo "$NAME."
        else
            echo " ERROR."
        fi
        ;;
  stop)
        echo -n "Stopping $DESC: "
        cd "$DBBASE" || exit -1
        . ./virtuoso.lck
        if running ; then
            kill $VIRT_PID
        fi
        echo "$NAME."
        ;;
  force-stop)
        echo -n "Forcefully stopping $DESC: "
        force_stop
        if ! running ; then
            echo "$NAME."
        else
            echo " ERROR."
        fi
        ;;
  #reload)
        #
        #       If the daemon can reload its config files on the fly
        #       for example by sending it SIGHUP, do it here.
        #
        #       If the daemon responds to changes in its config file
        #       directly anyway, make this a do-nothing entry.
        #
        # echo "Reloading $DESC configuration files."
        # start-stop-daemon --stop --signal 1 --quiet --pidfile \
        #       /var/run/$NAME.pid --exec $DAEMON
  #;;
  force-reload)
        #
        #       If the "reload" option is implemented, move the "force-reload"
        #       option to the "reload" entry above. If not, "force-reload" is
        #       just the same as "restart" except that it does nothing if the
        #   daemon isn't already running.
        # check wether $DAEMON is running. If so, restart
        start-stop-daemon --stop --test --quiet --pidfile \
                /var/run/$NAME.pid --exec $DAEMON \
        && $0 restart \
        || exit 0
        ;;
  status)
    echo -n "$LABEL is "
    if running ;  then
        echo "running"
    else
        echo " not running."
        exit 1
    fi
    ;;
  *)
        N=/etc/init.d/$NAME
        # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
        echo "Usage: $N {start|stop|restart|force-reload|status|force-stop}" >&2
        exit 1
        ;;
esac

exit 0
```

**Comment by pkleef** [comment]
@jakubklimek I created a new database and used the bulkloader to load that `data (5).ttl` file into the named graph you indicated. However when i try to run your query i get no rows back. 

Can you please check your query to make sure it is correct to be run on the small `data.zip` you provided, so i can focus on the label issue.

**Comment by jakubklimek** [comment]
@pkleef Sorry about that, the data (5).ttl file is actually the output of the query. The input data is this:
[seznam-ovm.zip](https://github.com/openlink/virtuoso-opensource/files/2180730/seznam-ovm.zip)

**Comment by pkleef** [comment]
@jakubklimek  OK. so I  loaded that `.trig` file into the database. Then I ran your SPARQL query (before and after a shutdown) and saved output. In both cases, I see as first triple --

`<https://data.gov.cz/zdroj/ovm/zakla_1446>      <http://purl.org/goodrelations/v1#legalName>    "Z\u00E1kladn\u00ED \u0161kola a Mate\u0159sk\u00E1 \u
0161kola Olomouc, Gork\u00E9ho 39, p\u0159\u00EDsp\u011Bvkov\u00E1 organizace"@cs .`

So clearly I do see labels. 

So I need to know how you determine there are no labels in your output.

Do you run the query from `isql` or from `/sparql`?  What output format do you select?

**Comment by jakubklimek** [comment]
Actually, I see labels too, only before shutdown, they have language tags and after shutdown they do not.
I run the query through `/sparql`, and I see the difference also when browsing using `/fct`. I select Turtle output.

**Comment by jakubklimek** [comment]
OK, restested with a00138aef035f4e20ad532520895fd619012f5cd. I discovered that when I really only load the one file, it works as expected and the language tags are there after restart. The problem was that I was initializing the db using a batch job, which loaded not only the one file, but also [other files](http://mvcr2.opendata.cz/soubor/rdf.zip). After loading them all using the bulk loader and doing the restart, the problem presents itself and the language tags disappear. Could you please test again by loading in addition [these files](http://mvcr2.opendata.cz/soubor/rdf.zip)? They are the [EU MDR NALs](http://publications.europa.eu/mdr/authority/) and the [Eurovoc thesaurus](http://publications.europa.eu/resource/cellar/9f2bd600-ae7b-11e7-837e-01aa75ed71a1.0001.10/DOC_1).

**Comment by pkleef** [comment]
@jakubklimek i cannot download all of the files as some are password protected. Can you contact me on mailto:pkleef@openlinksw.com or skype:pvk715 so we can discuss some details in private.

**Comment by pkleef** [comment]
@jakubklimek I pushed a fix from development that resolves this issue to develop/7.

Your database has language tags; it was just some cache initialization that was missing.  Please rebuild `virtuoso-t`, start with the database we created during our Skype session, and run your query to confirm language tags are then shown in its Turtle output.

**Comment by jakubklimek** [comment]
@pkleef I confirm that now it works as expected.
