### ISSUE TITLE
Develop/7 Branch - Make / Compile Error - odbcsdk - Ubuntu 16.04 

### ISSUE THREAD

**Issue by mediaprophet** [openlink/virtuoso-opensource#751]
"libtool:   error: cannot determine absolute directory name of 'libsrc/odbcsdk/lib'"

Any known solutions? 

log file: http://webcivics.net/config.txt

**Comment by timhaynesopenlink** [comment]
Hi,

Happens for me too. I'll ask development to have a look.

Thanks,

~Tim

**Comment by pkleef** [comment]
I pushed some fixes that should resolve the problem.

After you pulled the latest changes from the develop/7 branch you will need to run the following commands to regenerate the various files needed to build:

```
    $ sh ./autogen.sh
    $ sh ./config.nice
```

Please let me know how this works for you

**Comment by mediaprophet** [comment]
It lives...  

NB: didn't like perl or python - but got it working;  now, Init script needs to be updated...  

will lodge seperate issue.  

cheers.
