### ISSUE TITLE
Compile failure of the release version in Ubuntu 18.04

### ISSUE THREAD

**Issue by jbkoh** [openlink/virtuoso-opensource#754]
Hi,

I got an error message while compiling virtuoso-opensource-7.2.4.2.tar.gz in Ubuntu 18.04
GCC version is 7.3.0

```
In file included from ../../libsrc/odbcsdk/include/iodbcunix.h:79:0,
                 from ../../libsrc/odbcsdk/include/sql.h:87,
                 from odbcinc.h:72,
                 from sqlnode.h:31,
                 from bif_crypto.c:28:
/usr/include/stdlib.h:180:26: note: expected 'const char * restrict' but argument is of type 'boxint {aka long long int}'
 extern unsigned long int strtoul (const char *__restrict __nptr,
```
It's been successful in 16.04, but I don't know why it's happening at 18.04.

I did 
```bash
export CFLGAS="-O2 -m64"
./configre
make
```
I received the above error message during ``make``.

Does anybody have an idea?

Thank you!

**Comment by HughWilliams** [comment]
@jbkoh This is probably the issue with the openssl 1.1 lib in this later Ubuntu version which you can get around by installing the older openssl 1.0 version as indicated in git issue https://github.com/openlink/virtuoso-opensource/issues/730 ...

ie  ``` sudo apt install libssl1.0-dev```

**Comment by jbkoh** [comment]
Okay, thanks it works!
