### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by coolcoolhua** [openlink/virtuoso-opensource#774]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/8847878/44569648-aab57680-a7ad-11e8-9b75-07eb23912e2c.png">
<img width="434" alt="image" src="https://user-images.githubusercontent.com/8847878/44570826-ac813900-a7b1-11e8-9955-ddceec7c82e0.png">

After this time's update, every time I wanna install virtuoso and it just stuck in this step and can't forward for more than 1 hours. What may be the reason?

**Comment by timhaynesopenlink** [comment]
Most common reason is you have a virtuoso-t process lingering from a previous make.

```pkill virtuoso```

There may be other reasons - if it persists, check for logfiles in the `binsrc/yacutia/` directory.

HTH

**Comment by coolcoolhua** [comment]
You are right. It works now. 

Thank you for your answer!
