### ISSUE TITLE
Use isql command load data error.

### ISSUE THREAD

**Issue by HuuuNan** [openlink/virtuoso-opensource#790]
I use isql command `ld_dir_all` to load data, but error:

>Error 42000: [Virtuoso Driver][Virtuoso Server]FA003: Access to '/home/hh/data' is denied due to access control in ini file
>at line 1 of Top-Level:
>ld_dir_all('/home/hh/data','*.*','fb:')

It means I should configure the file `virtuoso.ini`? Can anyone help me, thanks!

**Comment by timhaynesopenlink** [comment]
Hi,
Yes, check the `DirsAllowed=`  directive in `virtuoso.ini`.

HTH
~Tim

**Comment by HughWilliams** [comment]
@HuuuNan  You should see the `DirsAllowed` INI file parameter to allow Virtuoso access to to the `/home/hh/data` directory where the datasets reside and restart Virtuoso, as detailed in the RDF Bulk Loader [Prerequisites](http://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader#Prerequisites) section of the docs ...

**Comment by HuuuNan** [comment]
@timhaynesopenlink @HughWilliams Thanks a lot!
