### ISSUE TITLE
openssl version check delivers incorrect error message

### ISSUE THREAD

**Issue by TallTed** [openlink/virtuoso-opensource#796]
See [this StackOverflow post](https://stackoverflow.com/questions/52969379/virtuoso-open-source-installation-problem/52970734#52970734).

User installed --

    openssl version OpenSSL
    0.9.7i 14 Oct 2005

-- (having misunderstood the "minimum version" list in the README; would have been avoided if #767 were merged), and got this from `make` --

```
checking OpenSSL version... >= 0.9.8e
checking OpenSSL version... 
configure: error: OpenSSL version 1.1.0 or greater is currently not supported.
```

Message should be --

```
configure: error: OpenSSL version 0.9.8d or lower is currently not supported.
```

**Comment by cainesap** [comment]
Hello, I'm attempting to install virtuoso in an anaconda environment on Ubuntu 18.04 LTS.
I've installed OpenSSL 1.0.2t and add the `--enable-openssl` parameter to `./configure` pointing to that binary. 
I get the error `checking OpenSSL version... configure: error: OpenSSL version 0.9.8e or greater is required.`
I understand from the [OpenSSL readme](https://github.com/openlink/virtuoso-opensource/blob/develop/7/README.OpenSSL.md) that I should replace the 1.1 SDK with 1.0 SDK: `sudo apt-get install libssl1.0-dev`
However, I'm not an admin on the server I'm using, and I don't think they'd be keen to do this if it can be avoided. I also can't find a way to install the 1.0 SDK via conda other than via openssl itself. 
Do you think the SDK is the problem? Is there a workaround other than stepping back to 1.0? 
thank you in advance! Andrew

**Comment by TallTed** [comment]
@cainesap - You cannot currently build Virtuoso with the OpenSSL 1.1 SDK; the only options are to install (at least temporarily) the OpenSSL 1.0 SDK on this host, or to build (with the OpenSSL 1.0 SDK) on another host, and bring the compiled components to this deployment host. If you're building from the `stable/7` branch, you could just [download the pre-compiled 7.2.5.1 binary](https://sourceforge.net/projects/virtuoso/files/virtuoso/7.2.5/).

**Comment by pfps** [comment]
It would be nice to have this fixed.   (Isn't OpenSSL 1.0 considered insecure?)

**Comment by HughWilliams** [comment]
OpenSSL 1.0 itself is not considered insecure, it is some of the older TLS 1.0 & 1.1 versions it still supports that are. In Virtuoso we only enable the secure TLS 1.2 version by default with options for users to enable the older TLS versions if such a need arises.

In terms of OpenSSL 1.1 support this is still being worked on and we are planning to have this available in the next stable/7 release.

**Comment by BorderCloud** [comment]
@cainesap I had the same problem. Anaconda installs the version 1.1.1 of OpenSSL and breaks the Virtuoso compilator (configure).
You can downgrad openssl with this command:
`conda install openssl=1.0`
After you can compile Virtuoso.

**Comment by openlink** [comment]
This has been resolved on the develop/7 branch.

Virtuoso now supports OpenSSL versions 0.9.8e through 1.1.1 as well as LibreSSL

**Comment by BorderCloud** [comment]
@openlink maybe it's a good idea to update also the branch stable/7.

**Comment by openlink** [comment]
@BorderCloud @cainesap 

We just released a new stable release:

- https://github.com/openlink/virtuoso-opensource/releases/tag/v7.2.6
- https://github.com/openlink/virtuoso-opensource/tree/stable/7
