### ISSUE TITLE
Limited complexity of SPARQL queries with Virtuoso

### ISSUE THREAD

**Issue by rogargon** [openlink/virtuoso-opensource#799]
Trying the following query with a clean deployment of Virtuoso from tenforce/virtuoso:latest docker image, version: 07.20.3217

I get the error: 
Virtuoso 37000 Error SP031: SPARQL: Internal error: The length of generated SQL text has exceeded 10000 lines of code

There is another open issue related with this error, however in that case it was pointed out that the issue might be related with reloading data to the queried graphs without clearing them before. This is not the case here as there is no data uploaded to the target graphs yet. I get the same error if I upload the proper data.

Therefore, is this query too complicated for Virtuoso to process:

```
PREFIX  schema: <http://schema.org/>
PREFIX  geo:  <http://geo.org/>
PREFIX  cro:  <http://rhizomik.net/ontologies/copyrightonto.owl#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT  ?isAuthorized ?why
FROM <http://rhizomik.net/copyrightly/geo>
FROM <http://rhizomik.net/copyrightly/licensing>
WHERE
  { ?agreement  rdf:type  cro:Agree ;
              cro:what  ?term ;
              cro:when  ?agreementDate
    FILTER ( xsd:dateTime(?agreementDate) <= now() )
    OPTIONAL
      { ?disagreement
                  rdf:type  cro:Disagree ;
                  cro:what  ?term ;
                  cro:when  ?disagreementDate
        FILTER ( xsd:dateTime(?disagreementDate) <= now() )
      }
    BIND(( bound(?agreement) && ( ! bound(?disagreement) ) ) AS ?isAuthorized)
    BIND(if(bound(?disagreement), ?disagreement, ?agreement) AS ?why)
    OPTIONAL
      { ?term  schema:startTime  ?start }
    FILTER ( ( ! bound(?start) ) || ( xsd:dateTime("9999-12-31T23:59:59Z") >= xsd:dateTime(?start) ) )
    OPTIONAL
      { ?term  schema:endTime  ?end }
    FILTER ( ( ! bound(?end) ) || ( xsd:dateTime("9999-12-31T23:59:59Z") <= xsd:dateTime(?end) ) )
    {   { ?term  cro:where  "Spain"}
      UNION
        { ?term     cro:where   ?regionName .
          ?region   rdfs:label  ?regionName .
          ?country  rdfs:label  "Spain" . 
          ?country (schema:containedInPlace)+ ?region
        }
      UNION
        { ?agreement  cro:what  ?term
          FILTER NOT EXISTS { ?term  cro:where  ?blank0 }
        }
    }
    {   { ?term  cro:who  <http://localhost/inVIDUsers/2>}
      UNION
        { ?term  cro:who  <http://localhost/organizations/1>}
      UNION
        { ?term     cro:who          ?organization .
          <http://localhost/inVIDUsers/2>
                    schema:memberOf  ?organization}
      UNION
        { ?agreement  cro:what  ?term
          FILTER NOT EXISTS { ?term  cro:who  ?blank1 }
        }
    }
    {   { ?term  cro:what  <http://localhost/youTubeVideos/AbCDFfhIJKL>}
      UNION
        { ?term  cro:what  <http://localhost/youTubeChannels/UC_IiSo6Pi08hqE-1NN8KvIA>}
      UNION
        { ?term  cro:what  <http://localhost/contentOwners/1>}
      UNION
        { ?agreement  cro:what  ?term
          FILTER NOT EXISTS { ?term  cro:what  ?blank2 }
        }
    }
      { ?term  cro:with  "WWW"}
    UNION
      { ?agreement  cro:what  ?term
        FILTER NOT EXISTS { ?term  cro:with  ?blank3 }
      }
    ?term  rdf:type  cro:MakeAvailable
  }
```

**Comment by TallTed** [comment]
VOS Version 07.20.3217 [dates from 2016-04-25](https://github.com/openlink/virtuoso-opensource/commit/53b08d4aac506b4712ebd6f28207493e5bc96314).

Can you retest your query with a current build of [VOS 7.2.5.1 (stable/7)](https://github.com/openlink/virtuoso-opensource/tree/stable/7) ([prebuilt binary](https://sourceforge.net/projects/virtuoso/files/virtuoso/7.2.5/) is an option here -- you can replace just the `virtuoso-t` in your docker image), [VOS 7.2.6-rc1 (develop/7)](https://github.com/openlink/virtuoso-opensource/tree/develop/7), and/or [Enterprise Edition 8.2 (current)](https://shop.openlinksw.com/license_generator/virtuoso/?serverVersionSelection=8.2)?

Hopefully the first of these resolves the issue for you (and that should persist in the others), but if not, it will help to also know the results with the other two.

**Comment by rogargon** [comment]
OK, thanks. Got confused about version numbering and that this version back from 2016 is the last one available from Docker Hub. Will try to generate and updated Docker version
