### ISSUE TITLE
A large number of queries sometimes return Error 404

### ISSUE THREAD

**Issue by HuuuNan** [openlink/virtuoso-opensource#805]
I use python `urllib` library to request a large number of sparql queries, about 10 million or even more. But sometimes it  will be Interrupted and return `404` error during the query, and the sparql query statement is same: 

    SELECT ?relation FROM <%s> WHERE {<%s> ?relation ?object}

The error as follow:
```
File "../virtuoso.py", line 122, in id_query_out_rel
    json_response = sparql_query(query, query_url)
  File "../virtuoso.py", line 28, in sparql_query
    http_response = request.urlopen(URL, encoded_query).read()
  File "/home/spider/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/spider/anaconda3/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/spider/anaconda3/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/spider/anaconda3/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/spider/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/spider/anaconda3/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: File not found
```

Errors appear randomly during the query，by the way, the speed of a large number of  queries is too slow.
Can someone help me please?

**Comment by TallTed** [comment]
We'll need a lot more information to provide much useful advice.

To start with, are you running these queries against your own Virtuoso instance?

If so, please start by confirming that you've properly [tuned your Virtuoso INI file, such that Virtuoso takes advantage of available memory](http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning).

If you are *not* hitting your own Virtuoso instance, it sounds like you're being an unfriendly user, and may need to throttle your requests, among other adjustments.

In either case, it's likely that there's a better strategy by which to achieve your goal, than running millions of queries.  The more detail you can provide about what you're trying to achieve, the better advice we can provide.

**Comment by timhaynesopenlink** [comment]
Also worth considering:
* What concurrency do you have on the requests?
* What timeout parameters do you have --
  a. in the SPARQL query/URL? 
  b. in the `virtuoso.ini` `[SPARQL]` section?

HTH

**Comment by AlexTo** [comment]
I'm experiencing the same issue. Virtuoso 7.2.5.1 is only loaded with DBPedia (which is not very large). 

NumberOfBuffers      = 2720000
MaxDirtyBuffers         = 2100000

The server has 64 GB memory with 16 cores running Centos 7. I have an app that repeatedly execute SELECT query like 

```
SELECT * WHERE { 
    ?s rdfs:label ?label
   FILTER (?s = <some uri here>)
}
```
And occasionally I have 404 error at `http://virtuoso-server/sparql?query=<query>` but if I copy that url and execute in browser then it is ok. It seems that Virtuoso throttles or rejects the request sometimes. 

Is there any setting related to throttling in Virtuoso for SPARQL endpoint?

Thanks

**Comment by AlexTo** [comment]
@HuuuNan you closed this issue, have you managed to get this issue resolved? thanks

**Comment by HuuuNan** [comment]
@AlexTo I tried to solve it but failed, and I used other method instead of Virtuoso. 
If you can solve this issue, I hope you can share with me. :)

**Comment by AlexTo** [comment]
I ended up adding a "thread.sleep" in my code every 10000 triples read to avoid choking the server and it seems to be ok ;)

**Comment by HuuuNan** [comment]
@AlexTo Checking this [issue](https://github.com/openlink/virtuoso-opensource/issues/299) may help. It seems that you should change the item `CheckpointInterval` from default 60 to 0, to avoid automatical checkpoint process which will cause 404 error.

**Comment by TallTed** [comment]
@HuuuNan @AlexTo -- It is important to note that if you disable the automatic checkpoint as was [suggested above](https://github.com/openlink/virtuoso-opensource/issues/805#issuecomment-1073211809), you *must* take responsibility for periodic manual `checkpoint();` execution, especially after any significant changes to the data you mean to have held in the `virtuoso.db`.

Lacking such a `checkpoint();` execution, your data changes _may_ be lost, or at least require increasingly long "playback" of the growing transaction log(s) (`.trx` file(s)), upon restart.

Related to all this, I recommend that you both review [this article about Virtuoso's Anytime Query feature](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksAnytimeSPARQLQuery) and [this article about timeouts and other limits, as applied on the live, publicly-accessible DBpedia instance](https://community.openlinksw.com/t/dbpedia-usage-report-for-july-2017-through-january-2021/2715).

@HuuuNan -- We did ask a number of questions in response to your initial issue post, but you didn't answer any of them, so we can provide little advice toward solving any issue that remains.  If you are still having the same problem you originally reported, I suggest you reopen this issue and answer our previous questions, so we can provide relevant advice.

**Comment by HuuuNan** [comment]
> 

Thanks a lot for your reply. This issue doesn't occur when I use Virtuoso rencently.

**Comment by HuuuNan** [comment]
> Body

Thanks a lot for your reply. This issue doesn't occur when I use Virtuoso rencently.

**Comment by HuuuNan** [comment]
> @HuuuNan @AlexTo -- It is important to note that if you disable the automatic checkpoint as was [suggested above](https://github.com/openlink/virtuoso-opensource/issues/805#issuecomment-1073211809), you _must_ take responsibility for periodic manual `checkpoint();` execution, especially after any significant changes to the data you mean to have held in the `virtuoso.db`.
> 
> Lacking such a `checkpoint();` execution, your data changes _may_ be lost, or at least require increasingly long "playback" of the growing transaction log(s) (`.trx` file(s)), upon restart.
> 
> Related to all this, I recommend that you both review [this article about Virtuoso's Anytime Query feature](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksAnytimeSPARQLQuery) and [this article about timeouts and other limits, as applied on the live, publicly-accessible DBpedia instance](https://community.openlinksw.com/t/dbpedia-usage-report-for-july-2017-through-january-2021/2715).
> 
> @HuuuNan -- We did ask a number of questions in response to your initial issue post, but you didn't answer any of them, so we can provide little advice toward solving any issue that remains. If you are still having the same problem you originally reported, I suggest you reopen this issue and answer our previous questions, so we can provide relevant advice.

Thanks a lot for your reply. This issue doesn't occur when I use Virtuoso rencently.
