### ISSUE TITLE
load the full freebase dump into Virtuoso

### ISSUE THREAD

**Issue by qshi95** [openlink/virtuoso-opensource#813]
I want to load the full freebase dump (397G with unzipped) into Virtuoso, but it takes tooooo long time. Is it convenient to provide with the virtuoso.db file which has been already compiled? Thanks a lot.

**Comment by TallTed** [comment]
This is now being [pursued through the OpenLink Community site](https://community.openlinksw.com/t/load-the-full-freebase-dump-into-virtuoso/495/7), so I will close this issue.
