### ISSUE TITLE
How to modify max number of query results

### ISSUE THREAD

**Issue by HuuuNan** [openlink/virtuoso-opensource#817]
The max number of my query results is `10000` and I hope it is larger value. I tried to modify `MaxQueryMem`, `VectorSize`, `MaxVectorSize` in `virtuoso.ini`, but the max query number didn't change.

**Comment by HughWilliams** [comment]
In the `[SPARQL]` section of the INI file there is a default `ResultSetMaxRows = 10000` setting which limits the number of results that are returned.  You should increase this limit, or comment it out for unrestricted result set sizes ...

**Comment by HuuuNan** [comment]
thanks a lot!
