### ISSUE TITLE
SHA1 used for ODS API authentication

### ISSUE THREAD

**Issue by sdmonroe** [openlink/virtuoso-opensource#819]
The documentation [here](http://ods.openlinksw.com/wiki/ODS/VirtuosoOdsControllers#Password%20Hash%20Authentication) say SHA1 is used to authenticate to the ODS controller API. Is this still the case? If so, are there plans to update to a more secure algorithm?

**Comment by HughWilliams** [comment]
It is on the roadmap to upgrade the ODS controller authentication to use a more secure algorithm, although it has not been scheduled yet at this time.

**Comment by sdmonroe** [comment]
Perfect, thanks!
