### ISSUE TITLE
(COUNT ( DISTINCT * ) AS ?var) cannot be handled.

### ISSUE THREAD

**Issue by yayamamo** [openlink/virtuoso-opensource#82]
When issuing a query contains the above expression, I got an error as follows:

Virtuoso 37000 Error SP030: SPARQL compiler, line 3: syntax error at '*' before ')'

SPARQL query:
define sql:big-data-const 0 
# output-format:text/html

define sql:signal-void-variables 1 SELECT (COUNT (DISTINCT *) AS ?total) WHERE {?s ?p ?o}

I think this is a valid query as defined in the W3C spec.
http://www.w3.org/TR/sparql11-query/#rAggregate

In addition, if replacing "*" with, for example, "?p", I got a proper result.

**Comment by sebastianthelen** [comment]
We're experiencing a similar issue with Virtuoso 7.1. We're unable to execute any queries containing SELECT (COUNT (DISTINCT *) AS ?c) statements.

Any idea what's going on here?`

**Comment by rumito** [comment]
Yes, indeed this is valid syntax and the query should work. Our development is notified to take a look into...
Thanks for reporting!

Best Regards,
Rumi Kocis

**Comment by HughWilliams** [comment]
Fix for this issue has been made which needs to be verified and added to the develop/7 branch, will notify when available ...

**Comment by ezyk** [comment]
Any news on this issue?

**Comment by HughWilliams** [comment]
The issue with the syntax error has been resolved, although note that Final version of SPARQL 1.1 spec does not allow more than one argument of COUNT(), see grammar production rule:

[127]   Aggregate         ::=     'COUNT' '(' 'DISTINCT'? ( '*' | Expression )
')'

Note single the Expression at the right hand of the rule, not a list of Expressions.
