### ISSUE TITLE
Cannot create webdav folder (for LDP)

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [openlink/virtuoso-opensource#821]
Hi,
Working with

> Virtuoso Open Source Edition (multi threaded)
> Version 07.20.0.3229-threads as of Aug 27 2018 (17c4ba1d5)
> Compiled for Win64 (x86_64-generic-win-64)
> Copyright (C) 1998-2018 OpenLink Software

I'm trying to create a LDP enabled folder like [Example 1: How to enable LDP on a folder/collection](http://vos.openlinksw.com/owiki/wiki/VOS/VirtLDP#Example%201%3A%20How%20to%20enable%20LDP%20on%20a%20folder%2Fcollection) 

I'm getting this errormessage:

> An error has occurred when processing "/conductor/cont_page.vspx" page
> SQL State | 42001
> SQL Message | SR185: Undefined procedure DB.DBA.ACL_VALIDATE.
 
Any suggestions?
Thanks
Gerald

**Comment by HughWilliams** [comment]
I have been able to recreate the `SR185: Undefined procedure DB.DBA.ACL_VALIDATE` error indicated above and have reported to development to investigate into and fix ...

**Comment by HughWilliams** [comment]
Actually the issue is in the Virtuoso Conductor VAD and has been fixed already in the updated VAD available from:

   http://download3.openlinksw.com/uda/vad-vos-packages/7.2/conductor_dav.vad

The version is 1.00.8786 , please download, update your Conductor VAD and confirm it works, such that this issue can be closed ...

**Comment by GeraldGrootRoessink** [comment]
With that dowload I van create a webdav folder. Many thanks.

**Comment by rewindgr** [comment]
Hi there, I am facing the same issue for 
```
OpenLink Virtuoso Universal Server
Version 07.20.3230-pthreads for Linux as of Sep 27 2019
```
develop version 
conductor version `1.00.8806/`

when I am trying to upload a test file for version scheme as presented in 
[Managing Version Support using Conductor UI](http://vos.openlinksw.com/owiki/wiki/VOS/VirtConductorVersions)

```
SQL State	42001
SQL Message	 SR185: Undefined procedure DB.DBA.ACL_VALIDATE.
```

I have logged in as `dba` and I have assigned all SPARQL account roles to `dba`. 

Any clue?

Many thanks in advance.

Nik

**Comment by TallTed** [comment]
@rewindgr - This appears to be a new, though similar, issue. Would you mind starting a new github issue for it? (It will be helpful if you reference this older issue from the new one.)

Please include the full first "paragraph" of output from `virtuoso-t -?`, especially including the git hash, as seen in the initial post here in #821.

**Comment by rewindgr** [comment]
> @rewindgr - This appears to be a new, though similar, issue. Would you mind starting a new github issue for it? (It will be helpful if you reference this older issue from the new one.)
> 
> Please include the full first "paragraph" of output from `virtuoso-t -?`, especially including the git hash, as seen in the initial post here in #821.

Ted because I am rookie here, how can I create the git hash?
Is it something as described here :
https://git-scm.com/book/en/v2/Git-Internals-Git-Objects

Sorry I will be away unfortunately from tomorrow morning until Sunday evening (UTC+3)

Nik
