### ISSUE TITLE
FCT inconsistent response policy

### ISSUE THREAD

**Issue by sdmonroe** [openlink/virtuoso-opensource#825]
To reproduce, please follow these steps:

1. [Go here](http://myopenlink.net/DAV/home/sdmonroe/poc_fct_debug.html#) and enter 'batman'
2. Proxy the traffic
3. Select "Fields" from the "Show Me:" menu
4. In the list, click the folder icon next to "ShortSummary" item. Observe empty result list is returned.
5. Replay the 'view type=list-count' request in your proxy. Observe non-empty results are returned.
 
The client code sends three queries to /fct nearly simultaneously. It's the same query with list-count, properties, and classes view types. When I disable any one of the three (as I did [here](http://myopenlink.net/DAV/home/sdmonroe/poc_fct_debug2.html#)), the results set is non-empty. When all three are enabled, the result-set is empty. Can this be due to a rate-limit? If so, can you please provide any data on how the rate-limit works?

**Comment by sdmonroe** [comment]
Implementing a client-side cache appears to have helped. Resolving this issue for now.

**Comment by sdmonroe** [comment]
The issue persists, even with client-side caching enabled.

**Comment by sdmonroe** [comment]
I did some more testing and did not encounter this issue on dbpedia or LOD server. So far, only myopenlink.com. Still would like to know how server configuration could cause responses to be empty when they should be populated.

**Comment by kidehen** [comment]
@sdmonroe,

Do not use myopenlink.net in this manner. You should be using our [URIBurner ](http://linkeddata.uriburner.com/fct)or [LOD ](http://lod.openlinksw.com/fct)instances.

You can mesh data by sponging data into the URIBurner instance if need be.

**Comment by sdmonroe** [comment]
@kidehen 10-4, I will use LOD and URIBurner going forward.
