### ISSUE TITLE
Filter not being applied on aggregate function

### ISSUE THREAD

**Issue by sdmonroe** [openlink/virtuoso-opensource#827]
I have [this query](http://lod.openlinksw.com/sparql/?default-graph-uri=&query=select+%3Fs4c+as+%3Fc1+count+%28*%29+as+%3Fc2++where++%7B%3Fs1+a+%3Chttp%3A%2F%2Fdbpedia.org%2Fclass%2Fyago%2FWikicatBlack-and-whiteFilms%3E+.+%3Fs1+a+%3Chttp%3A%2F%2Fdbpedia.org%2Fclass%2Fyago%2FWikicatDystopianFilms%3E+.++quad+map+virtrdf%3ADefaultQuadMap+%7B+%3Fs1+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2Fdistributor%3E+%3Fs2+.+%7D+quad+map+virtrdf%3ADefaultQuadMap+%7B+%3Fs3+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2Fdistributor%3E+%3Fs2+.+%7D+filter+%28%3Fs3+%3D+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FGattaca%3E%29+.+quad+map+virtrdf%3ADefaultQuadMap+%7B+%3Fs3+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2Fdirector%3E+%3Fs4+.+%7D+%3Fs4+a+%3Fs4c+.+filter+%28%3Fs4+%3D+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FAndrew_Niccol%3E%29+.+quad+map+virtrdf%3ADefaultQuadMap+%7B+%3Fs2+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2Fabstract%3E+%3Fs5+.+%7D+%7D+group+by+%3Fs4c+order+by+desc+2+limit+30++offset+0&format=text%2Fhtml&timeout=30000&debug=on&run=+Run+Query+), which groups ?s1 by RDF classes, and return the number of instances of each class:

`select ?s4c as ?c1 count (*) as ?c2  where  {?s1 a <http://dbpedia.org/class/yago/WikicatBlack-and-whiteFilms> . ?s1 a <http://dbpedia.org/class/yago/WikicatDystopianFilms> .  quad map virtrdf:DefaultQuadMap { ?s1 <http://dbpedia.org/ontology/distributor> ?s2 . } quad map virtrdf:DefaultQuadMap { ?s3 <http://dbpedia.org/ontology/distributor> ?s2 . } filter (?s3 = <http://dbpedia.org/resource/Gattaca>) . quad map virtrdf:DefaultQuadMap { ?s3 <http://dbpedia.org/ontology/director> ?s4 . } ?s4 a ?s4c . filter (?s4 = <http://dbpedia.org/resource/Andrew_Niccol>) . quad map virtrdf:DefaultQuadMap { ?s2 <http://dbpedia.org/ontology/abstract> ?s5 . } } group by ?s4c order by desc 2 limit 30  offset 0`

As you see, there is a filter on ?s4c that binds it to a URI. Shouldn't that make the query equal to [the below query](http://lod.openlinksw.com/sparql/?default-graph-uri=&query=select+%3Fs1c+as+%3Fc1+count+%28*%29+as+%3Fc2++where++%7B+filter+%28%3Fs1+%3D+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FAndrew_Niccol%3E%29+.+%3Fs1+a+%3Fs1c+.+%7D+group+by+%3Fs1c+order+by+desc+2+limit+30++offset+0&format=text%2Fhtml&timeout=30000&debug=on&run=+Run+Query+)?

`select ?s1c as ?c1 count (*) as ?c2  where  { filter (?s1 = &lt;http://dbpedia.org/resource/Andrew_Niccol&gt;) . ?s1 a ?s1c . } group by ?s1c order by desc 2 limit 30  offset 0`

It's as if the filter on ?s4c isn't being applied by the aggregate function. FYI, both queries were produced by FCT service.

**Comment by TallTed** [comment]
@sdmonroe -- 

Analysis and understanding of codeblocks such as yours is aided by wrapping them in codefences, with some human-friendly whitespace, and using `PREFIX` declarations to aid the human parsing.  The first query then can become --

```sparql
prefix  dbo: <http://dbpedia.org/ontology/>
prefix  dbr: <http://dbpedia.org/resource/>
prefix yago: <http://dbpedia.org/class/yago/>

select      ?s4c as ?c1 
       count (*) as ?c2 
where
 {                                   ?s1 a               yago:WikicatBlack-and-whiteFilms . 
                                     ?s1 a               yago:WikicatDystopianFilms . 
   quad map virtrdf:DefaultQuadMap { ?s1 dbo:distributor ?s2 . } 
   quad map virtrdf:DefaultQuadMap { ?s3 dbo:distributor ?s2 . } 
                            filter ( ?s3 = dbr:Gattaca ) . 
   quad map virtrdf:DefaultQuadMap { ?s3 dbo:director    ?s4 . } 
                                     ?s4 a               ?s4c . 
                            filter ( ?s4 = dbr:Andrew_Niccol ) . 
   quad map virtrdf:DefaultQuadMap { ?s2 dbo:abstract    ?s5 . } 
 } 
group by ?s4c 
order by desc 2 
limit 30 
offset 0
```

When I read through this, I find no binding of `?s4c` to a URI -- that binding is of `?s4`, i.e., -- 
```sparql
filter (?s4 = <http://dbpedia.org/resource/Andrew_Niccol>)
```

Your second query is broken above by the HTML-escaped `&lt;` and `&gt;`.  Repaired (and with a more conventional placement of the `filter` clause below the pattern that binds that variable), I think it's meant to be --

```sparql
select      ?s1c as ?c1 
       count (*) as ?c2 
where
  { ?s1 a ?s1c .
    filter ( ?s1 = <http://dbpedia.org/resource/Andrew_Niccol> ) . 
  } 
group by ?s1c 
order by desc 2 
limit 30 
offset 0
```


Now, to test whether the `FILTER` clauses are being applied, given that here they're basically forcing a single `VALUE` on each of those variables, you could do an absolute replacement of each such variable with that single value --
```sparql
prefix  dbo: <http://dbpedia.org/ontology/>
prefix  dbr: <http://dbpedia.org/resource/>
prefix yago: <http://dbpedia.org/class/yago/>

select      ?s4c as ?c1 
       count (*) as ?c2 
where
 {                                   ?s1               a               yago:WikicatBlack-and-whiteFilms . 
                                     ?s1               a               yago:WikicatDystopianFilms . 
   quad map virtrdf:DefaultQuadMap { ?s1               dbo:distributor ?s2 . } 
   quad map virtrdf:DefaultQuadMap { dbr:Gattaca       dbo:distributor ?s2 . } 
   quad map virtrdf:DefaultQuadMap { dbr:Gattaca       dbo:director    dbr:Andrew_Niccol . } 
                                     dbr:Andrew_Niccol a               ?s4c . 
   quad map virtrdf:DefaultQuadMap { ?s2               dbo:abstract    ?s5 . } 
 } 
group by ?s4c 
order by desc 2 
limit 30 
offset 0
```

Or, you could set those `VALUES` --
```sparql
prefix  dbo: <http://dbpedia.org/ontology/>
prefix  dbr: <http://dbpedia.org/resource/>
prefix yago: <http://dbpedia.org/class/yago/>

select      ?s4c as ?c1 
       count (*) as ?c2 
where
 { VALUES ( ?s3         ?s4               )
     {    ( dbr:Gattaca dbr:Andrew_Niccol )
     }
                                     ?s1 a               yago:WikicatBlack-and-whiteFilms . 
                                     ?s1 a               yago:WikicatDystopianFilms . 
   quad map virtrdf:DefaultQuadMap { ?s1 dbo:distributor ?s2 . } 
   quad map virtrdf:DefaultQuadMap { ?s3 dbo:distributor ?s2 . } 
   quad map virtrdf:DefaultQuadMap { ?s3 dbo:director    ?s4 . } 
                                     ?s4 a               ?s4c . 
   quad map virtrdf:DefaultQuadMap { ?s2 dbo:abstract    ?s5 . } 
 } 
group by ?s4c 
order by desc 2 
limit 30 
offset 0
```

I think part of what's puzzling you is that this query won't get the results I think you're after, which I'm guessing is "how many entities are instances of each class of which `dbr:Andrew_Niccol` is also an instance?"  It would be quite surprising to me if there were exactly 24 (or 1) instances of each class to which `dbr:Andrew_Niccol` belongs!

Here's [a revised query][2] which [gets the results][1] I think you're looking for --
```sparql
PREFIX   dbo:  <http://dbpedia.org/ontology/>
PREFIX   dbr:  <http://dbpedia.org/resource/>
PREFIX  yago:  <http://dbpedia.org/class/yago/>

SELECT ?s4c
       ?instances 
WHERE
  {                                   ?s1 a               yago:WikicatBlack-and-whiteFilms . 
                                      ?s1 a               yago:WikicatDystopianFilms . 
    QUAD MAP virtrdf:DefaultQuadMap { ?s1 dbo:distributor ?s2 . } 
    QUAD MAP virtrdf:DefaultQuadMap { ?s3 dbo:distributor ?s2 . } 
                             FILTER ( ?s3 = dbr:Gattaca ) . 
    QUAD MAP virtrdf:DefaultQuadMap { ?s3 dbo:director    ?s4 . } 
                                      ?s4 a               ?s4c . 
                             FILTER ( ?s4 = dbr:Andrew_Niccol ) . 
    QUAD MAP virtrdf:DefaultQuadMap { ?s2 dbo:abstract    ?s5 . } 
    {
      SELECT                     ?s4c 
             ( COUNT ( ?s4c ) AS ?instances) 
      WHERE
        {
          ?s a ?s4c
        }
      GROUP BY ?s4c
    }
  } 
GROUP BY ?s4c 
ORDER BY DESC 2 
LIMIT 30 
OFFSET 0
```

[1]: http://lod.openlinksw.com/sparql?default-graph-uri=&query=PREFIX+++dbo%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0D%0APREFIX+++dbr%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0D%0APREFIX++yago%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fclass%2Fyago%2F%3E%0D%0A%0D%0ASELECT+%3Fs4c%0D%0A+++++++%3Finstances+%0D%0AWHERE%0D%0A++%7B+++++++++++++++++++++++++++++++++++%3Fs1+a+++++++++++++++yago%3AWikicatBlack-and-whiteFilms+.+%0D%0A++++++++++++++++++++++++++++++++++++++%3Fs1+a+++++++++++++++yago%3AWikicatDystopianFilms+.+%0D%0A++++QUAD+MAP+virtrdf%3ADefaultQuadMap+%7B+%3Fs1+dbo%3Adistributor+%3Fs2+.+%7D+%0D%0A++++QUAD+MAP+virtrdf%3ADefaultQuadMap+%7B+%3Fs3+dbo%3Adistributor+%3Fs2+.+%7D+%0D%0A+++++++++++++++++++++++++++++FILTER+%28+%3Fs3+%3D+dbr%3AGattaca+%29+.+%0D%0A++++QUAD+MAP+virtrdf%3ADefaultQuadMap+%7B+%3Fs3+dbo%3Adirector++++%3Fs4+.+%7D+%0D%0A++++++++++++++++++++++++++++++++++++++%3Fs4+a+++++++++++++++%3Fs4c+.+%0D%0A+++++++++++++++++++++++++++++FILTER+%28+%3Fs4+%3D+dbr%3AAndrew_Niccol+%29+.+%0D%0A++++QUAD+MAP+virtrdf%3ADefaultQuadMap+%7B+%3Fs2+dbo%3Aabstract++++%3Fs5+.+%7D+%0D%0A++++%7B%0D%0A++++++SELECT+++++++++++++++++++++%3Fs4c+%0D%0A+++++++++++++%28+COUNT+%28+%3Fs4c+%29+AS+%3Finstances%29+%0D%0A++++++WHERE%0D%0A++++++++%7B%0D%0A++++++++++%3Fs+a+%3Fs4c%0D%0A++++++++%7D%0D%0A++++++GROUP+BY+%3Fs4c%0D%0A++++%7D%0D%0A++%7D+%0D%0AGROUP+BY+%3Fs4c+%0D%0AORDER+BY+DESC+2+%0D%0ALIMIT+30+%0D%0AOFFSET+0%0D%0A&format=text%2Fhtml&timeout=3000000&debug=on&run=+Run+Query+
[2]: http://lod.openlinksw.com/sparql?default-graph-uri=&query=PREFIX+++dbo%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0D%0APREFIX+++dbr%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0D%0APREFIX++yago%3A++%3Chttp%3A%2F%2Fdbpedia.org%2Fclass%2Fyago%2F%3E%0D%0A%0D%0ASELECT+%3Fs4c%0D%0A+++++++%3Finstances+%0D%0AWHERE%0D%0A++%7B+++++++++++++++++++++++++++++++++++%3Fs1+a+++++++++++++++yago%3AWikicatBlack-and-whiteFilms+.+%0D%0A++++++++++++++++++++++++++++++++++++++%3Fs1+a+++++++++++++++yago%3AWikicatDystopianFilms+.+%0D%0A++++QUAD+MAP+virtrdf%3ADefaultQuadMap+%7B+%3Fs1+dbo%3Adistributor+%3Fs2+.+%7D+%0D%0A++++QUAD+MAP+virtrdf%3ADefaultQuadMap+%7B+%3Fs3+dbo%3Adistributor+%3Fs2+.+%7D+%0D%0A+++++++++++++++++++++++++++++FILTER+%28+%3Fs3+%3D+dbr%3AGattaca+%29+.+%0D%0A++++QUAD+MAP+virtrdf%3ADefaultQuadMap+%7B+%3Fs3+dbo%3Adirector++++%3Fs4+.+%7D+%0D%0A++++++++++++++++++++++++++++++++++++++%3Fs4+a+++++++++++++++%3Fs4c+.+%0D%0A+++++++++++++++++++++++++++++FILTER+%28+%3Fs4+%3D+dbr%3AAndrew_Niccol+%29+.+%0D%0A++++QUAD+MAP+virtrdf%3ADefaultQuadMap+%7B+%3Fs2+dbo%3Aabstract++++%3Fs5+.+%7D+%0D%0A++++%7B%0D%0A++++++SELECT+++++++++++++++++++++%3Fs4c+%0D%0A+++++++++++++%28+COUNT+%28+%3Fs4c+%29+AS+%3Finstances%29+%0D%0A++++++WHERE%0D%0A++++++++%7B%0D%0A++++++++++%3Fs+a+%3Fs4c%0D%0A++++++++%7D%0D%0A++++++GROUP+BY+%3Fs4c%0D%0A++++%7D%0D%0A++%7D+%0D%0AGROUP+BY+%3Fs4c+%0D%0AORDER+BY+DESC+2+%0D%0ALIMIT+30+%0D%0AOFFSET+0%0D%0A&format=text%2Fhtml&timeout=3000000&debug=on&run=+Run+Query+

**Comment by sdmonroe** [comment]
Thank you, Ted. Your points on presentation code are duly noted. I guest the question is, when dbr:Andrew_Niccol is bound as the focus of a FCT query, what should an end-user expect to see, choice a, b or c? I'll post a question to the community site, and vet future issues like this through the forum before posting here.

**Comment by TallTed** [comment]
Well...  

FCT builds *a* query, based on a drill-down by the user -- which drill-down may start at many points, and take many twisty-windy paths to reach the same record(s) in the end.  That query is not generally going to be the most efficient query by which to get to those records -- but having a *working* query from which to start is often the biggest hurdle to working out an *efficient* query.

The FCT presentation of your query may look very different from the SPARQL presentation of the same query.  I just [tried to rebuild your FCT](http://lod.openlinksw.com/fct/facet.vsp?qxml=%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%20%3F%3E%3Cquery%20inference%3D%22%22%20same-as%3D%22%22%20view3%3D%22%22%20s-term%3D%22%22%20c-term%3D%22%22%3E%3Cclass%20iri%3D%22http%3A%2F%2Fdbpedia.org%2Fclass%2Fyago%2FWikicatBlack-and-whiteFilms%22%20%2F%3E%3Cclass%20iri%3D%22http%3A%2F%2Fdbpedia.org%2Fclass%2Fyago%2FWikicatDystopianFilms%22%20%2F%3E%3Cproperty%20iri%3D%22http%3A%2F%2Fdbpedia.org%2Fontology%2Fdistributor%22%3E%3Cproperty-of%20iri%3D%22http%3A%2F%2Fdbpedia.org%2Fontology%2Fdistributor%22%3E%3Cproperty%20iri%3D%22http%3A%2F%2Fdbpedia.org%2Fontology%2Fdirector%22%3E%3Ccond%20type%3D%22eq%22%20xml%3Alang%3D%22%22%20datatype%3D%22uri%22%20neg%3D%22%22%3Ehttp%3A%2F%2Fdbpedia.org%2Fresource%2FAndrew_Niccol%3C%2Fcond%3E%3Cproperty%20iri%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23type%22%3E%3Cview%20type%3D%22list-count%22%20limit%3D%2220%22%20offset%3D%220%22%20%2F%3E%3C%2Fproperty%3E%3C%2Fproperty%3E%3Ccond%20type%3D%22eq%22%20xml%3Alang%3D%22%22%20datatype%3D%22uri%22%20neg%3D%22%22%3Ehttp%3A%2F%2Fdbpedia.org%2Fresource%2FGattaca%3C%2Fcond%3E%3C%2Fproperty-of%3E%3Cproperty%20iri%3D%22http%3A%2F%2Fdbpedia.org%2Fontology%2Fabstract%22%20%2F%3E%3C%2Fproperty%3E%3C%2Fquery%3E), with some luck, but not 100%.  On screen, I see --

>Displaying List of Distinct Entity Names ordered by Count where:
?s1 is a yago:WikicatBlack-and-whiteFilms . Drop
?s1 is a yago:WikicatDystopianFilms . Drop
?s1 http://dbpedia.org/ontology/distributor ?s2 . Drop ?s2
?s3 <http://dbpedia.org/ontology/distributor> ?s2 . Drop ?s3
?s3 http://dbpedia.org/ontology/director ?s4 . Drop ?s4
?s4 == <http://dbpedia.org/resource/Andrew_Niccol> Drop
?s4 rdf:type ?s5 . Drop ?s5
?s3 == <http://dbpedia.org/resource/Gattaca> Drop
?s2 http://dbpedia.org/ontology/abstract ?s6 . Drop ?s6


-- and the SPARQL I get is --
```sparql
 select ?s5 as ?c1 count ( * ) as ?c2 where 
  { 
    select distinct ?s1 ?s2 ?s3 ?s4 ?s5 
    { 
      ?s1 a <http://dbpedia.org/class/yago/WikicatBlack-and-whiteFilms> .
      ?s1 a <http://dbpedia.org/class/yago/WikicatDystopianFilms> .
      quad map virtrdf:DefaultQuadMap 
      { 
        ?s1 <http://dbpedia.org/ontology/distributor> ?s2 .
        
      }
     quad map virtrdf:DefaultQuadMap 
      { 
        ?s3 <http://dbpedia.org/ontology/distributor> ?s2 .
        
      }
     quad map virtrdf:DefaultQuadMap 
      { 
        ?s3 <http://dbpedia.org/ontology/director> ?s4 .
        
      }
     filter ( ?s4 = <http://dbpedia.org/resource/Andrew_Niccol> ) .
      quad map virtrdf:DefaultQuadMap 
      { 
        ?s4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?s5 .
        
      }
     filter ( ?s3 = <http://dbpedia.org/resource/Gattaca> ) .
      quad map virtrdf:DefaultQuadMap 
      { 
        ?s2 <http://dbpedia.org/ontology/abstract> ?s6 .
        
      }
     }
   }
 group by ?s5 order by desc 2 limit 20 offset 0  
```

-- and of course, neither gets to what I thought you were looking for, because the counts *here* are "how many records in the limited set we're now looking at have the thing we're counting?"
