### ISSUE TITLE
Virtuoso 22023 Error SR014: Function ri_name_id needs a string as argument 1, not an arg of type VARBINARY (222)

### ISSUE THREAD

**Issue by bortikb** [openlink/virtuoso-opensource#833]
Hitting this issue with the below query when running a local copy of Freebase hosted using Virtuoso.

> Virtuoso 22023 Error SR014: Function ri_name_id needs a string as argument 1, not an arg of type VARBINARY (222)

```sparql
prefix : <http://rdf.basekb.com/ns/>
SELECT distinct ?p0 WHERE{
?s0 ?p0 :m.09c7w0. 
FILTER (isIRI(?s0) && ?p0 != rdf:type && STRSTARTS(STR(?s0), STR(:))).
}
```
Can you please help ?

**Comment by TallTed** [comment]
To start, please provide the exact version of Virtuoso in use. The first stanza of command-line output of `virtuoso-t -?` or `virtuoso-iodbc-t -?` is usually sufficient.

**Comment by bortikb** [comment]
Here is the output : 

Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.4.2.3217-pthreads as of Aug 22 2018
Compiled for Linux (x86_64-pc-linux-gnu)
Copyright (C) 1998-2016 OpenLink Software

**Comment by TallTed** [comment]
@bortikb - Though your binary was built 2018-08-22 (the `as of` date), the code from which it was built (v 7.2.4.2.3217) [dates from 2016-04-25](https://github.com/openlink/virtuoso-opensource/blob/290abf9f43f6f5e1e118c5420afe1baa05ef1c87/ChangeLog#L2101).  

Please update to a current build from either [`stable/7`](https://github.com/openlink/virtuoso-opensource/commits/stable/7) ([prebuilt 7.2.5.1 binary](https://sourceforge.net/projects/virtuoso/files/virtuoso/7.2.5/)) or (often better) [`develop/7`](https://github.com/openlink/virtuoso-opensource/commits/develop/7) (7.2.6+), and retest.

**Comment by bortikb** [comment]
It works now. Thanks !
