### ISSUE TITLE
Executing dump_one_graph with virtuoso jdbc4 

### ISSUE THREAD

**Issue by vinodreddyb** [openlink/virtuoso-opensource#844]
I was trying to execute the query to dump the particular graph using virtuoso jdbc4 classes. But I am getting  _syntax error at 'dump_one_graph' before '('_.  

Suggest me with any example.

```java
String query = "dump_one_graph ('<http://test1>', 'C:/data', 1000000000)";
try{
			VirtuosoUpdateRequest vqe = VirtuosoUpdateFactory.create (proc, set);

			vqe.exec();
		}catch(Exception e) {
			log.error("Exception occurred: {}", e);
		}
```

**Comment by TallTed** [comment]
What versions of Virtuoso, Java, and the JDBC driver, are you using?  Output of these commands is a good start --

    virtuoso-iodbc-t -?
    virtuoso-t -?
    java -version
    java -jar virtjdbc4.jar
    java -jar virtjdbc4_1.jar
    java -jar virtjdbc4_2.jar

**Comment by smalinin** [comment]
> I was trying to execute the query to dump the particular graph using virtuoso jdbc4 classes. But I am getting _syntax error at 'dump_one_graph' before '('_.
> 
> Suggest me with any example.
> 
> ```java
> String query = "dump_one_graph ('<http://test1>', 'C:/data', 1000000000)";
> try{
> 			VirtuosoUpdateRequest vqe = VirtuosoUpdateFactory.create (proc, set);
> 
> 			vqe.exec();
> 		}catch(Exception e) {
> 			log.error("Exception occurred: {}", e);
> 		}
> ```

The Jena Provider must be used ONLY for executing SPARQL queries.
You tried to execute SQL stored procedure, it must be call via Virtuoso JDBC directly.
