### ISSUE TITLE
virtuoso hangs during startup without showing any error message

### ISSUE THREAD

**Issue by rapw3k** [openlink/virtuoso-opensource#847]
Hi,
I had a problem with virtuoso today.

configuration
----------
I have a large installation of virtuoso, with over 1 billion triples. 
the database file (`virtuoso.db`) is almost 200 GB. 
the transaction file was originally very small (`virtuoso.trx`): ~10Kb
the temp database file is small (`virtuoso-temp.db`): 6.3MB

Virtuoso version: `7.2.4.2`
Database version: `3126`
I dont want to upgrade to `7.2.5.1` because I found some issues with geo-functionality. 
Attached `virtuoso.ini`

problem 
--------
The system was unresponsive (probably after heavy usage), and so I tried restarting the server, i.e., I killed virtuoso process and started the server again. 
However, now virtuoso is not starting at all. 
The main problem is that there is no information in the log (`virtuoso.log`) about any error.
After waiting around 8 hours without any response, I killed the process again, modified `virtuoso.ini` to trace errors and to use also the syslog, i.e., 
```pre
Syslog = 1
TraceOn = errors
```

However, that didnt provide any additional insights of what is going. The process hanged again in the same place (waited over 1 hour).

I tried one more time: 
i) kill the process
ii) renamed the `trx` file so it wont be found during startup
iii) started the server
same issue (after 30 minutes and waiting)

Questions
-----------
* As the log does not give any insights, is there a way to see more details of the startup tasks, e.g., like start in debug mode?
* If i need to make a recovery, which steps should I follow in http://docs.openlinksw.com/virtuoso/backup_recovery/ ? Should I  follow the procedure for rebuilding it, using `-b` or `-D`?

thanks,

The messages in the logs (both virtuoso.log and syslog) after starting the server are:
```pre
00:34:19 { Loading plugin 1: Type `plain', file `wikiv' in `/home/virtuoso/virtuoso/lib/virtuoso/hosting'
00:34:19   FAILED  plugin 1: Unable to locate file }
00:34:19 { Loading plugin 2: Type `plain', file `mediawiki' in `/home/virtuoso/virtuoso/lib/virtuoso/hosting'
00:34:19   FAILED  plugin 2: Unable to locate file }
00:34:19 { Loading plugin 3: Type `plain', file `creolewiki' in `/home/virtuoso/virtuoso/lib/virtuoso/hosting'
00:34:19   FAILED  plugin 3: Unable to locate file }
00:34:19 OpenLink Virtuoso Universal Server
00:34:19 Version 07.20.3217-pthreads for Linux as of Mar 27 2018
00:34:19 uses parts of OpenSSL, PCRE, Html Tidy
00:34:32 Database version 3126
00:34:32 SQL Optimizer enabled (max 1000 layouts)
00:34:33 Compiler unit is timed at 0.000139 msec
```
normally when starting the server, after "`compiler unit is timed at...`", we get something like:
```pre
15:10:07 { Loading plugin 1: Type `plain', file `wikiv' in `/home/virtuoso/virtuoso/lib/virtuoso/hosting'
15:10:07   FAILED  plugin 1: Unable to locate file }
15:10:07 { Loading plugin 2: Type `plain', file `mediawiki' in `/home/virtuoso/virtuoso/lib/virtuoso/hosting'
15:10:07   FAILED  plugin 2: Unable to locate file }
15:10:07 { Loading plugin 3: Type `plain', file `creolewiki' in `/home/virtuoso/virtuoso/lib/virtuoso/hosting'
15:10:07   FAILED  plugin 3: Unable to locate file }
15:10:07 OpenLink Virtuoso Universal Server
15:10:07 Version 07.20.3217-pthreads for Linux as of Mar 27 2018
15:10:07 uses parts of OpenSSL, PCRE, Html Tidy
15:10:16 Database version 3126
15:10:22 Unlinked the temp db file /home/virtuoso/virtuoso/var/lib/virtuoso/db/virtuoso-temp.db as its size (22784MB) was greater than TempDBSize INI (10MB)
15:10:23 SQL Optimizer enabled (max 1000 layouts)
15:10:25 Compiler unit is timed at 0.000150 msec
15:16:44 built-in procedure "ld_dir" overruled by the RDBMS
15:16:44 built-in procedure "rdf_read_dir" overruled by the RDBMS
15:16:44 built-in procedure "ld_dir_all" overruled by the RDBMS
15:16:44 built-in procedure "ld_add" overruled by the RDBMS
15:16:44 built-in procedure "ld_ttlp_flags" overruled by the RDBMS
15:16:44 built-in procedure "ld_file" overruled by the RDBMS
15:16:44 built-in procedure "rdf_load_dir" overruled by the RDBMS
15:16:44 built-in procedure "ld_array" overruled by the RDBMS
15:16:44 built-in procedure "rdf_loader_run" overruled by the RDBMS
15:16:44 built-in procedure "rdf_load_stop" overruled by the RDBMS
15:16:44 built-in procedure "RDF_LOADER_RUN_1" overruled by the RDBMS
15:16:44 built-in procedure "rdf_ld_srv" overruled by the RDBMS
15:16:44 built-in procedure "load_grdf" overruled by the RDBMS
15:16:47 Roll forward started
15:16:47     73 transactions, 6565 bytes replayed (100 %)
15:16:47 Roll forward complete
15:18:00 Checkpoint started
15:18:03 Checkpoint finished, log reused
15:18:03 HTTP/WebDAV server online at 8890
15:18:03 Server online at 1111 (pid 32274)
```
and then server is online.

[virtuoso.ini_trace_errors.txt](https://github.com/openlink/virtuoso-opensource/files/3209687/virtuoso.ini_trace_errors.txt)

**Comment by rapw3k** [comment]
Update:
----------
After more than six hours the server went back online (see below).
However, now I see virtuoso is running much slower than usual.
Any ideas ?
thanks,

```pre
01:09:02 Compiler unit is timed at 0.000141 msec
07:24:46 built-in procedure "ld_dir" overruled by the RDBMS
07:24:46 built-in procedure "rdf_read_dir" overruled by the RDBMS
07:24:46 built-in procedure "ld_dir_all" overruled by the RDBMS
07:24:46 built-in procedure "ld_add" overruled by the RDBMS
07:24:46 built-in procedure "ld_ttlp_flags" overruled by the RDBMS
07:24:46 built-in procedure "ld_file" overruled by the RDBMS
07:24:46 built-in procedure "rdf_load_dir" overruled by the RDBMS
07:24:46 built-in procedure "ld_array" overruled by the RDBMS
07:24:46 built-in procedure "rdf_loader_run" overruled by the RDBMS
07:24:46 built-in procedure "rdf_load_stop" overruled by the RDBMS
07:24:46 built-in procedure "RDF_LOADER_RUN_1" overruled by the RDBMS
07:24:46 built-in procedure "rdf_ld_srv" overruled by the RDBMS
07:24:46 built-in procedure "load_grdf" overruled by the RDBMS
07:24:46 Roll forward started
07:24:46 Roll forward complete
07:24:49 Checkpoint started
07:24:52 Checkpoint finished, log reused
07:24:52 HTTP/WebDAV server online at 8890
07:24:52 Server online at 1111 (pid 14717)
```

**Comment by TallTed** [comment]
As you've observed, there's little to work from in your log output.  You may get some additional detail by launching with `+foreground` (`-f`); please note that the `stdout`/`stderr` output this delivers may not all be reflected in the `virtuoso.log` or `syslog`.

You could certainly try a rebuild as described in [Database Recovery](http://docs.openlinksw.com/virtuoso/backup_recovery/#vdbrecovery). I would recommend first trying [Diagnosing and Recovering a Damaged Database File](http://docs.openlinksw.com/virtuoso/backup_recovery/#diagnosingrepairing), and if that doesn't resolve the issue, proceeding to [Crash Recovery When The Normal Crash Recovery Fails](http://docs.openlinksw.com/virtuoso/backup_recovery/#xcrashrecovery).

Beyond that -- have you tested the [development version of 7.2.6](https://sourceforge.net/projects/virtuoso/files/virtuoso/7.2.6-dev/), which includes [significant fixes of the geo-functionality](https://github.com/openlink/virtuoso-opensource/blob/develop/7/README.GeoSPARQL.md), among [other improvements](https://github.com/openlink/virtuoso-opensource/commits/develop/7)?  This update is strongly recommended for all users of earlier 7.x versions.

**Comment by rapw3k** [comment]
Dear @TallTed 
after the initial reboot that took hours, when everything was slower, I tried rebooting with normal procedure. This time, the reboot took normal time (few minutes) and after this, operation went back to normal speed I would say.
In any case, thanks for the option -f hint. It will come handy, and for the pointers to recover database if sometime (hope not) it will get damaged.
I will surely test the development version 7.2.6, specially because of the geo-fixes. 
Thanks
