### ISSUE TITLE
R2RML support

### ISSUE THREAD

**Issue by rapw3k** [openlink/virtuoso-opensource#851]
Hi,
I was trying to find the latest R2RML VAD for virtuoso 7.2.x. I was only able to find for version 8.3 (commercial) [1], and version 6.3 [2]. Is there anywhere I can find it, or are any of these compatible?

Regarding R2RML support, does it support external/remote databases? Which type ? e.g., postgresql, mysql?

Regarding materialization or on the fly generation, I understand both options are possible, but didnt find concrete information about this. Can you give me some concrete pointers?

thanks

[1] https://www.openlinksw.com/describe/?url=http%3A%2F%2Fvirtuoso.openlinksw.com%2Fdata%2Fturtle%2Fapplications%2Fapplications.ttl%23R2RMLVad&invfp=IFP_OFF&sas=SAME_AS_OFF&sid=59167 
[2] http://opldownload.s3.amazonaws.com/uda/vad-packages/6.3/virtuoso/rdb2rdf_dav.vad

**Comment by TallTed** [comment]
Latest builds of all dot-version-specific VAD packages are available for both [Enterprise/Commercial Edition](http://download3.openlinksw.com/index.html?prefix=uda/vad-packages/) and [VOS (Open Source Edition)](http://download3.openlinksw.com/index.html?prefix=uda/vad-vos-packages/).

(Any links you've saved that target `http://opldownload.s3.amazonaws.com/...` should be updated to target `http://download3.openlinksw.com/index.html?prefix=...`)

The Enterprise Edition of Virtuoso supports [R2RML](http://vos.openlinksw.com/owiki/wiki/VOS/VirtR2RML) of any ODBC-accessible (or JDBC-accessible, via our ODBC-to-JDBC Bridge Driver) external/remote database, as well as any Virtuoso-hosted SQL/relational data.  This includes remote instances of Virtuoso, MySQL, PostgreSQL, Oracle, DB2, Informix, Ingres, Progress/OpenEdge, Sybase, Microsoft SQL Server, and many more.

VOS (Open Source Edition) does not support ODBC connections to external/remote databases, so does not support R2RML over such.  (Any data loaded into the local Virtuoso SQL tables may still be exposed through *local* Linked Data Views and/or R2RML.)

Dynamic R2RML, part of our "Linked Data Views" functionality, is generally recommended, as this does not require data replication.  That said, once such a view is set up, you can persist the data to one or more RDF graphs.  Specifics of achieving such persistence will vary.

**Comment by rapw3k** [comment]
thanks @TallTed  for the information, everything is clear
