### ISSUE TITLE
fct: Error 07S01 SR180: Extra arguments to DB.DBA.b3s_render_ses_params

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#852]
When clicking on "document(s)" in Virtuoso fct to display named graphs from which the current view takes triples, I get:
```
Error 07S01
SR180: Extra arguments to DB.DBA.b3s_render_ses_params, takes only 1
```
![image](https://user-images.githubusercontent.com/718827/59326298-69636880-8ce6-11e9-877b-8c1d13f61035.png)

Commit 0d6ea10596b168bde1324a83112c68ad1a9a615f, fct version ```Faceted Search & Find service v1.16.100```

**Comment by HughWilliams** [comment]
I have been able to recreate this error and reported to development to fix ...

**Comment by HughWilliams** [comment]
@jakubklimek: A fix for this issue has been [added to the develop/7 branch](https://github.com/openlink/virtuoso-opensource/commit/4494d36d1104e2a6dc86a377dceee37505299d42).

Please build new FCT VAD and test to verify fix ...

**Comment by jakubklimek** [comment]
Yes, works for me in 1.16.101

**Comment by HughWilliams** [comment]
Great, will close this issue ...
