### ISSUE TITLE
Geospatial features namespaces

### ISSUE THREAD

**Issue by rapw3k** [openlink/virtuoso-opensource#864]
Hi,
I want to test latest update 7.2.6, particularly because of the new/improved geopspatial features and support. As far as I understand this version uses the standard geospaql as namespace. My question is if the previous bif:function is still supported. My question is because I have some existing applications using such functions.
thanks,
Raul

**Comment by HughWilliams** [comment]
All the old geospatial function remain in place, with new GeoSPARQL equivalents added in the latest builds, which typically map to the original `bif` geospatial functions where applicable. The [Virtuoso Geospatial Enhancements documentation](http://vos.openlinksw.com/owiki/wiki/VOS/VirtGeoSPARQLEnhancementDocs) is still valid ...

**Comment by rapw3k** [comment]
great, thanks!
