### ISSUE TITLE
bulk loading 800 million quadruples

### ISSUE THREAD

**Issue by jheinecke** [openlink/virtuoso-opensource#871]
Hi,

I'm trying to load 800 millions quadruples into virtuoso (develop/7, version 07.20.320) and after having loaded 400 millions virtuoso nearly stops working (<10% CPU)

My Linux box as 64GB, in `virtuoso.ini` I put
```pre
NumberOfBuffers = 272000
MaxDirtyBuffers  = 200000
```
(values proposes for 32G). I also activated striping
```pre
[Database]
Striping = 1

[Striping]
Segment1 = 50G, db-seg1.db
Segment2 = 50G, db-seg2.db
Segment3 = 50G, db-seg3.db
Segment4 = 50G, db-seg4.db
Segment5 = 50G, db-seg5.db
```

When I started the server, these segment files have been successfully initialised, there are still 325G available.  My machine is not running anything else.

To load the quadruples, I split them into 40 files in TRiG format, each with 20 million quads.

each file is loaded with
`isql 1111 dba dba exec="DB.DBA.TTLP_MT(file_to_string_output('all_01.trig'), '', 'http://example.com/DAV/jh', 256);"`

While in the beginning everything is working fine (loading a single takes between 5 and 10 minutes) from the 24th file onwards, CPU drops to below 10%. There is however no swapping. The machine is simply idle.

So my question is, why doesn't continue with 300% CPU as it did before?
any ideas/hints?
Thanks a lot
Johannes

**Comment by TallTed** [comment]
While this doesn't address your question directly, my first thought is to wonder why you're not using the [Bulk Loading Scripts](http://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader)?

Relatedly, since you appear to be loading one file at a time in sequence, are you running a [`checkpoint();`](http://docs.openlinksw.com/virtuoso/checkpoint/) between files?

Also note that the striping features are not going to bring you much benefit unless you have multiple disks, each on their own controller, and write one segment per disk.

**Comment by jheinecke** [comment]
Good point for the Bulk Loading Scripts: I failed to get them running for files in TRiG format :-(
I forgot to run checkpoint() after each files. May this be a reason for a slowdown? The virtuoso.log file tells me that checkpoints have been started and finished, though.

**Comment by TallTed** [comment]
There are many possible reasons for the slowdown you've described.

Can you reveal your `virtuoso.ini` and `virtuoso.log` files?  (Best to attach as files, rather than posting as text.)

It may be worth starting with a focus on the Bulk Loading Scripts, as these *should* work for the TriG files.  Were any error messages delivered when you tried this?

**Comment by jheinecke** [comment]
I reran the bulk loading scripts I created a global.graph file with an IRI (which shouldn't be used, since all quadrupels have their graph). I then run (using isql)
``
ld_dir('path/', 'all_*.trig', 'http://default.graph.fr/');
select * from DB.DBA.load_list;
rdf_loader_run();
``
(on a totally empty virtuoso, without striping). `all*.trig` are 41 files of 20 million quadrupels.
After a certain time, the virtuoso.db file has 60GB (looks OK), but the server crashes after 8 mesages like `Write wait on column page 3196590. Waits should be on the index leaf page, except when col page is held for read by background write`. The isql process also stops when the server crashes (obviously). I do not know how many of the 41 files have been loaded, I guess about 30. Since when I load only 5 of these files (manually using `DB.DBA.TTLP_MT`), I get about 10GB.

Here are the log/ini files.
[virtuoso.ini.txt](https://github.com/openlink/virtuoso-opensource/files/3616635/virtuoso.ini.txt)
[virtuoso.log.txt](https://github.com/openlink/virtuoso-opensource/files/3616653/virtuoso.log.txt)
Do you see any bad configuration options? I only changed `NumberOfBuffers/MaxDirtyBuffers` and the directory of the virtuoso.* files

**Comment by TallTed** [comment]
Can you please provide the full version string details for your instance?  This would be the first "paragraph" of output from `virtuoso-t -?` -- especially including the git hash, along the lines of --
```pre
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.6-rc1.3230-pthreads as of Nov 30 2018 (5cf82cfcf)
Compiled for Darwin (x86_64-apple-darwin14.5.0)
Copyright (C) 1998-2018 OpenLink Software
```

Please also indicate whether you built Virtuoso and any installed VADs yourself, or downloaded pre-built binary and/or VADs (and if so, from where).

-----

The checkpoints in the fresh `virtuoso.log` were part of the new-instance database initialization process. Note that they all occurred in the first ten seconds of the server's run. Checkpoints are disabled for the duration of a bulk-load, so a crash during that load followed by discard of the `.trx` file leaves you where you were at the last checkpoint.

Toward figuring out what's going wrong for you, given that these 41 files can be loaded gradually, I'll suggest that you try bulk-loading 5 files at a time, and run a checkpoint after each set of 5, before proceeding to the next set.

If you hit a set that fails, don't run a checkpoint following the crash or other error; instead, stop the instance, discard the `.trx` file, restart the instance, and try loading those five files one-by-one, again with checkpoints after each.

If these individual files now load successfully, proceed to the next set of five. If one file fails, again, stop the instance, discard the `.trx` file, restart the instance, and proceed to the next single file; when you've done this with all five single files in this set, then proceed to the next set of five.

The end result may be a completely successful load, in which case we'd like to get a copy of all 41 TriG files for local testing, if possible.

The end result may be that loading some individual file(s) results in a crash — while the others all load successfully.  In this case, we'd like to get a copy of the triggering file(s), and *may* need the others as well.

**Comment by jheinecke** [comment]
I git-cloned the develop/7 Version on september 9th. `virtuoso -?` gives me the following

```Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.6-rc1.3230-pthreads as of Sep  9 2019 (e2a413e)
Compiled for Linux (x86_64-pc-linux-gnu)
Copyright (C) 1998-2019 OpenLink Software
```
I compiled my self (Ubuntu 16.04 with standard tools like make, gcc etc) and installed it with `make install`, I guess all VADs which exists have been created in this way, I didn't modify anything.

The TRiG files are in fact one triple per graph, since I want to avoid reification, but need to add properties to triples, like  
```
ns:G1 { ns:X ns:isPresident ns:US }
ns:G2 { ns:G1 ns:starts ns:2017 }
```
I just started the import as you propose on a fresh virtuoso data directory (I deleted all but the `.ini` file).

**Comment by TallTed** [comment]
If I understand correctly, your TriG files can be broken down further -- such that if you find specific files that trigger the crash among the 41, you can break those triggering files into smaller pieces, and narrow down the trigger, possibly even to some specific quad(s).  That would certainly make it easier to provide us with the problematic data, and should make it easier for us to figure out what's happening, if you're willing/able to go through this process.

**Comment by jheinecke** [comment]
I git-cloned the develop/7 Version on september 9th. `virtuoso -?` gives me the following

```Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.6-rc1.3230-pthreads as of Sep  9 2019 (e2a413e)
Compiled for Linux (x86_64-pc-linux-gnu)
Copyright (C) 1998-2019 OpenLink Software
```
I compiled my self (Ubuntu 16.04 with standard tools like make, gcc etc) and installed it with `make install`, I guess all VADs which exists have been created in this way, I didn't modify anything.

The TRiG files are in fact one triple per graph, since I want to avoid reification, but need to add properties to triples, like  
```
ns:G1 { ns:X ns:isPresident ns:US }
ns:G2 { ns:G1 ns:starts ns:2017 }
```
I successfully imported all 41 files as you propose on a fresh virtuoso data directory (I deleted all but the `.ini` file).

the final result looks good (5 files of 20 million quads each take an hour). The server crashed after 30 files (out of memory issue ?, the machine has 64GB and 32 CPUs, it is not used by anything else for the time being, The configuration uses the values proposed for a 32GB machine). Before the server crashed the process had 55GB resident memory in use. After the crash I deleted the `.trx` file and restarted the server. After startup the server used only 12GB. (which after loading the remaining 11 files went up again to 37GB). So it looks like restarting the server after checkpoints make things better!

At times I see a `Monitor: CPU% is low while there are large numbers of runnable threads` during loading. In general, loading time per 20 million quads went up with the size of the `virtuoso.db` file (from 7minutes per 20 million quads to about 12 minutes). Since my disk is not an SSD, I'm not too much surprised by this, though.

**Comment by TallTed** [comment]
I'm glad to hear you got the whole data set loaded! Certainly, SSD storage would make a big difference to the speed of load, and of checkpoint.

The memory settings in the INI file are about keeping active data in memory. Other activities -- including bulk loads -- may increase memory consumption, typically temporarily. It does indeed sound like you hit an OOM issue during this load.

We generally recommend a minimum of 10 bytes RAM per quad in the store. Depending on compressibility of data, you may require a higher average. The minimum works out to about 8GB for your 800M quads, so you should generally find things work quite well with Virtuoso set for 32GB, though this depends somewhat on the queries you'll be processing.

Would you consider this issue resolved?

**Comment by jheinecke** [comment]
Thank you very much for your precious help! I think my problem is solved. 
Just on last question: After running `checkpoint` I observed a certain memory consumption. After having stopped and restarted the server without any other action done, l observed a much smaller memory usage. Does virtuoso keep memory allocated for future use?

**Comment by TallTed** [comment]
Virtuoso keeps as much data in memory as it can, based on the `NumberOfBuffers`, `MaxDirtyBuffers`, and various other settings in the INI file.  This is standard for most database engines, as "warm" state response to queries much faster than "cold", because disk reads are virtually always slower than RAM reads, even with SSDs.

[This article](https://medium.com/virtuoso-blog/database-working-set-control-functions-ec71ca9fee72) will tell you some more about working with the database working set.

**Comment by Invincibled** [comment]
@jheinecke 

hi, I'm a developer , we are currently considering using the Virtuoso Open Source Version.

However, we also need to enable Striping, so I would like to ask, what is your main basis for dividing the 5 segments, and what do you think about the performance of this division?

If you have other suggestions, or best practices, or recommended configurations, I would like to share them with you. Thank you very much.

Looking forward to your reply. Thank you.

**Comment by jheinecke** [comment]
@Invincibled 
Hi, I cannot really remember why I chose 5 segments, I just needed to have the 800M quads read into virtuoso in a reasonable time (which worked at the end). I'm afraid I cannot you help much further, since I was happy with the solution at the time

**Comment by TallTed** [comment]
@jheinecke @Invincibled 

Fast bulk loading does not necessarily call for striping -- and striping may even cause significant slowdown if all stripes are on a single device, whether HDD or SDD, or if multiple devices share one controller, among other contributing factors.

For best results, we typically recommend using our bulk load tools, with one bulk load process per CPU/thread, up to half the available CPUs/threads.  For example, see this discussion of [loading Wikidata into a Virtuoso instance](https://community.openlinksw.com/t/loading-wikidata-into-virtuoso-open-source-or-enterprise-edition/2717/3).
