### ISSUE TITLE
What is the purpose of the default graphs, and is it safe to remove them? 

### ISSUE THREAD

**Issue by ekulno** [openlink/virtuoso-opensource#876]
When starting a virtuoso service, some graphs are loaded by default:

 - http://www.openlinksw.com/schemas/virtrdf#
 - http://www.w3.org/ns/ldp#
 - `<localhost>/sparql`
 - `<localhost>/DAV/`
 - http://www.w3.org/2002/07/owl#

This is inconvenient since it causes common simple queries for getting for example the triple count of my data to be complicated, as i have to modify the query to specifically exclude these graphs. 

I tried to remove these graphs (by removing all graphs with `DELETE FROM DB.DBA.RDF_QUAD ;` before adding my own data) and it doesn't seem to have any obvious ill effect. However I am worried that this might come back to bite me in future if there's any subtle bugs I introduced by removing the graphs. 

As the issue title reads, my questions are:

 1. What is the purpose of these graphs?
 2. Is it safe to remove them?

**Comment by timhaynesopenlink** [comment]
Hi,

I wouldn't remove them - some of them come in handy whilst navigating DAV. 

A better way around might be to declare your own store: see
http://docs.openlinksw.com/virtuoso/rdfviewconfiguringrdfstorages/

HTH

**Comment by ekulno** [comment]
Thank you for the quick reply. I only use Virtuoso as a SPARQL endpoint. I don't use DAV. Is there any chance that removing the graphs would cause any erroneous SPARQL responses or cause the endpoint to crash, etc? If I understand correctly declaring a separate store would also hide away the graphs when querying the endpoint, but I would prefer to remove them completely to save resources where I can. Unless this would introduce any risk of bugs that would affect the performance, uptime, or correctness of my endpoint.

**Comment by imitko** [comment]
my 2c : one should  never remove the system graphs. Make endpoint secure, do not grant update to insecure connections, use ACLs to protect the private data.
