### ISSUE TITLE
GeoSpatial URI causing error

### ISSUE THREAD

**Issue by m-gzawi** [openlink/virtuoso-opensource#881]
## Insert:

`SPARQL INSERT INTO GRAPH <ex3> { <http://www.wikidata.org/entity/Q31> <http://www.wikidata.org/prop/direct/P1334> "Point(10.328 44.801472222222)"^^<http://www.opengis.net/ont/geosparql#wktLiteral> . };`

## Query:

`SPARQL SELECT DISTINCT ?o WHERE {<http://www.wikidata.org/entity/Q31> <http://www.wikidata.org/prop/direct/P1334> ?o  };`

## Result: 

`"Point(10.328 44.801472222222)"^^Virtuoso 22023 Error SR645: NT serialization of RDF data has got NULL instead of an URI`

**Comment by HughWilliams** [comment]
What Virtuoso open source version and git id are you using as testing against the latest develop/7 branch I don't have such problems:

```
$ virtuoso-t -?
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.6-rc1.3230-pthreads as of Oct 14 2019 (0e746c7ab)
```

```
SQL> SPARQL INSERT INTO GRAPH <http://example.org> { <http://www.wikidata.org/entity/Q31> <http://www.wikidata.org/prop/direct/P1333> "Point(5.4726111111111 49.497111111111)"^^<http://www.opengis.net/ont/geosparql#wktLiteral>  };

Done. -- 32 msec.
SQL> SPARQL SELECT DISTINCT ?o WHERE {<http://www.wikidata.org/entity/Q31> <http://www.wikidata.org/prop/direct/P1333> ?o };
o
LONG VARCHAR
_______________________________________________________________________________

POINT(5.4726111111111 49.497111111111)

1 Rows. -- 11 msec.
SQL>
```

**Comment by m-gzawi** [comment]
Hi HughWilliams, 
Thanks for the answer.

$ virtuoso-t -?
Version 6.1.6.3127-pthreads as of Feb  6 2018

I have tested with 7.2 and it works. Cheers.
