### ISSUE TITLE
 VAD file checksum mismatch (42VAD)

### ISSUE THREAD

**Issue by plegault3397** [openlink/virtuoso-opensource#887]
I just pulled the latest version and I'm getting the error:
 VAD_INSTALL: VAD file checksum mismatch (42VAD)
09:49:41 PL LOG: Errors were detected during installation of "/share/virtuoso/vad/conductor_dav.vad".
I have tried several times and no luck.
Any help is appreciated;
Thank you

**Comment by TallTed** [comment]
@plegault3397 - Can you be more explicit about the steps you've taken?

Did you pull the latest source, build from it locally, and then encounter this error on startup?

Or did you download a pre-built Virtuoso binary and/or VAD archive?

The more detail you can provide, the more relevant advice we can provide.

Generally speaking -- we need to know the exact version of Virtuoso you're running (the first "paragraph" of output from `virtuoso-t -?` or `virtuoso-iodbc-t -?` is usually best).  Assuming you downloaded a pre-built VAD archive, we also need the URI for that download.

**Comment by plegault3397** [comment]
I downloaded it from here. I di get it to work finally
