### ISSUE TITLE
I'm getting  Error parsing XML result:No memory Response :

### ISSUE THREAD

**Issue by plegault3397** [openlink/virtuoso-opensource#889]
Error endpoint: http://server.com/sparql
Error http_response_code: 200
Error message: Error parsing XML result:No memory Response :
I downloaded the latest virtuoso-opensource from here today 12/12/2019. version 07.20.3230
I'm using Bordercloud/sparql and trying to extract a csv file.
I set 
MaxSortedTopRows         = 100000
I set the query LIMIT 10000 and get the above error.
I set the query LIMIT 8710 and it works.

**Comment by TallTed** [comment]
Please provide more detail about what you're doing to get this error.

It looks like you're using [BorderCloud/SPARQL](https://github.com/BorderCloud/SPARQL) (not `Boardercloud/sparql`), and seem to be trying to use that to transform a result set delivered as RDF/XML into a CSV file?

BorderCloud/SPARQL is a PHP add-on, and it seems most likely that your PHP (or Apache, if you're running PHP as a plugin) is the thing running out of memory -- which means you'll need to raise this to the Bordercloud folks.

That said, you may prefer to just get a CSV file (or any of many other serializations) directly as output for a SPARQL query against the endpoint.  See --

* [How to output the results of a SPARQL query run against the /sparql endpoint to a file in Virtuoso?](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksGuideSPARQLEndpointQueryResultOutput)
* [Server Response Formats](http://docs.openlinksw.com/virtuoso/rdfsparqlprotocolendpoint/#rdfsupportedmimesofprotocolserver)

**Comment by plegault3397** [comment]
I thought I corrected that typo.
Thanks for your response - I ran the query directly on the virtuoso server and had no issue.
Thanks for your response and information.
