### ISSUE TITLE
errors where detected during installation of "Virtuoso Conductor".

### ISSUE THREAD

**Issue by donttal** [openlink/virtuoso-opensource#890]
But when I access port 8890, there is no option to log in to the database
```
(base) [lihongjing@master database]$ virtuoso-t -fd

                Sat Dec 21 2019
19:57:04 INFO: { Loading plugin 1: Type `plain', file `wikiv' in `../hosting'
19:57:04 INFO:   WikiV version 0.6 from OpenLink Software
19:57:04 INFO:   Support functions for WikiV collaboration tool
19:57:04 ERROR:   FAILED  plugin 1: Loaded plugin requires core functionality not provided by main application }
19:57:04 INFO: { Loading plugin 2: Type `plain', file `mediawiki' in `../hosting'
19:57:04 INFO:   MediaWiki version 0.1 from OpenLink Software
19:57:04 INFO:   Support functions for MediaWiki collaboration tool
19:57:04 ERROR:   FAILED  plugin 2: Loaded plugin requires core functionality not provided by main application }
19:57:04 INFO: { Loading plugin 3: Type `plain', file `creolewiki' in `../hosting'
19:57:04 INFO:   CreoleWiki version 0.1 from OpenLink Software
19:57:04 INFO:   Support functions for CreoleWiki collaboration tool
19:57:04 ERROR:   FAILED  plugin 3: Loaded plugin requires core functionality not provided by main application }
19:57:04 INFO: { Loading plugin 4: Type `plain', file `im' in `../hosting'
19:57:04 INFO:   IM version 0.62 from OpenLink Software
19:57:04 INFO:   Support functions for Image Magick 6.9.9
19:57:04 ERROR:   FAILED  plugin 4: Loaded plugin requires core functionality not provided by main application }
19:57:04 INFO: OpenLink Virtuoso Universal Server
19:57:04 INFO: Version 06.01.3127-pthreads for Linux as of Jun  9 2014
19:57:04 INFO: uses parts of OpenSSL, PCRE, Html Tidy
19:57:04 INFO: Database version 3126
19:57:04 INFO: SQL Optimizer enabled (max 1000 layouts)
19:57:05 INFO: Compiler unit is timed at 0.000651 msec
19:57:06 DEBUG: built-in procedure "repl_undot_name" overruled by the RDBMS
19:57:06 DEBUG: built-in procedure "REPL_FQNAME" overruled by the RDBMS
19:57:06 DEBUG: built-in procedure "REPL_COLTYPE_PS" overruled by the RDBMS
19:57:06 DEBUG: built-in procedure "REPL_COLTYPE" overruled by the RDBMS
19:57:06 INFO: Roll forward started
19:57:06 INFO:     11 transactions, 867 bytes replayed (100 %)
19:57:06 INFO: Roll forward complete
19:57:06 INFO: PL LOG: Installing Virtuoso Conductor version 1.00.8783 (DAV)
19:57:06 INFO: Checkpoint started
19:57:07 INFO: Checkpoint finished, log reused
19:57:07 INFO: PL LOG: VAD_INSTALL: Please update server version (FATAL)
19:57:07 INFO: PL LOG: Errors where detected during installation of "Virtuoso Conductor".
19:57:07 INFO: Checkpoint started
19:57:08 INFO: Checkpoint finished, log reused
19:57:08 INFO: HTTP/WebDAV server online at 8890
19:57:08 INFO: Server online at 1111 (pid 24642)
```

**Comment by HughWilliams** [comment]
Where did you obtain this old  Virtuoso `Version 06.01.3127-pthreads for Linux as of Jun  9 2014` build from and Is there any reason why you are not using the latest Virtuoso 7.2 open source available on [GitHub](https://github.com/openlink/virtuoso-opensource) we would recommend ?

**Comment by donttal** [comment]
> Where did you obtain this old Virtuoso `Version 06.01.3127-pthreads for Linux as of Jun 9 2014` build from and Is there any reason why you are not using the latest Virtuoso 7.2 open source available on [GitHub](https://github.com/openlink/virtuoso-opensource) we would recommend ?

the githun link http://vos.openlinksw.com/owiki/wiki/VOS/
I can't open
And I want to run a project, The download address given by the project author is as follows: 
[link](https://sourceforge.net/projects/virtuoso/files/virtuoso/)
I downloaded it according to the 7.2.5 version inside.

**Comment by donttal** [comment]
> 您`Version 06.01.3127-pthreads for Linux as of Jun 9 2014`是从哪里获得旧版本的Virtuoso的，为什么您不使用我们建议使用的[GitHub上](https://github.com/openlink/virtuoso-opensource)最新的Virtuoso 7.2开源？

I just tried to download 7.2.5 version from the link on GitHub, the error is still the same, why ?

#### GNU/Linux
Built against glibc 2.5, this should work on all more recent glibc versions: [Virtuoso Open-Source 7.2.5 (7.2.5.3229) as of 2018-08-15 installer](https://sourceforge.net/projects/virtuoso/files/virtuoso/7.2.5/virtuoso-opensource.x86_64-generic_glibc25-linux-gnu.tar.gz/download)

**Comment by TallTed** [comment]
@donttal -- I've just downloaded from the last link you posted, and confirmed that the Virtuoso binary therein is indeed `7.2.5.3229` a/k/a `07.20.3229` a/k/a `7.2.5`.

I'm guessing that someone has used the Linux package installer on your machine, and that's how you got the old v6.  You should remove that, and then try to manually install and use the newer 7.2.5.

**Comment by donttal** [comment]
> @donttal-我刚从您发布的最后一个链接下载了该文件，并确认其中的Virtuoso二进制文件确实是`7.2.5.3229`a / k / a `07.20.3229`a / k / a `7.2.5`。
> 
> 我猜想有人在您的计算机上使用过Linux软件包安装程序，这就是您使用旧v6的方式。您应该删除它，然后尝试手动安装和使用较新的7.2.5。

I use the following method to install the virtuoso binary file. And I put the file in the user directory of the server to place the problem of insufficient permissions. When I delete virtuoso, I only delete the folder 

1. Virtuoso installation and deployment

(1) Open source version download address: https://sourceforge.net/projects/virtuoso/files/virtuoso/ Download version 7.25, compiled general version

(2) Unzip it and put it in a version where the current user has all permissions (this can save some problems that may not be sufficient permissions in the future)

(3) Configure the environment variables:

(4) Rename virtuoso.ini.sample in the database folder under virtuoso-openlink to virtuoso.ini. Then start the terminal, cd to the database directory, and enter virtuoso-t -fd to start the service.

(5) Enter http: // localhost: 8890 in the browser to enter the port 8890 web page to open its initial page. Click on the conductor and enter the username and password (both dba) to enter the database service page.

**Comment by HughWilliams** [comment]
What is the screen output of starting the Virtuoso instance in foreground debug mode now ie the output of running `virtuoso-t -fd`  ?

**Comment by donttal** [comment]
## like this
```
(base) [lihongjing@master database]$ ls -lh
总用量 23M
-rw-r--r-- 1 lihongjing hpc  20M 12月 23 23:07 virtuoso.db
-rw-r--r-- 1 lihongjing hpc 6.9K 12月 23 22:59 virtuoso.ini
-rw-r--r-- 1 lihongjing hpc 2.8K 12月 23 23:07 virtuoso.log
-rw-r--r-- 1 lihongjing hpc    0 12月 23 23:02 virtuoso.pxa
-rw-r--r-- 1 lihongjing hpc 2.0M 12月 23 23:02 virtuoso-temp.db
-rw-r--r-- 1 lihongjing hpc    0 12月 23 23:07 virtuoso.trx
(base) [lihongjing@master database]$ virtuoso-t -fd

                Wed Dec 25 2019
10:40:09 INFO: { Loading plugin 1: Type `plain', file `wikiv' in `../hosting'
10:40:09 INFO:   WikiV version 0.6 from OpenLink Software
10:40:09 INFO:   Support functions for WikiV collaboration tool
10:40:09 ERROR:   FAILED  plugin 1: Loaded plugin requires core functionality not provided by main application }
10:40:09 INFO: { Loading plugin 2: Type `plain', file `mediawiki' in `../hosting'
10:40:09 INFO:   MediaWiki version 0.1 from OpenLink Software
10:40:09 INFO:   Support functions for MediaWiki collaboration tool
10:40:09 ERROR:   FAILED  plugin 2: Loaded plugin requires core functionality not provided by main application }
10:40:09 INFO: { Loading plugin 3: Type `plain', file `creolewiki' in `../hosting'
10:40:09 INFO:   CreoleWiki version 0.1 from OpenLink Software
10:40:09 INFO:   Support functions for CreoleWiki collaboration tool
10:40:09 ERROR:   FAILED  plugin 3: Loaded plugin requires core functionality not provided by main application }
10:40:09 INFO: { Loading plugin 4: Type `plain', file `im' in `../hosting'
10:40:09 INFO:   IM version 0.62 from OpenLink Software
10:40:09 INFO:   Support functions for Image Magick 6.9.9
10:40:09 ERROR:   FAILED  plugin 4: Loaded plugin requires core functionality not provided by main application }
10:40:09 INFO: OpenLink Virtuoso Universal Server
10:40:09 INFO: Version 06.01.3127-pthreads for Linux as of Jun  9 2014
10:40:09 INFO: uses parts of OpenSSL, PCRE, Html Tidy
10:40:09 INFO: Database version 3126
10:40:09 INFO: SQL Optimizer enabled (max 1000 layouts)
10:40:10 INFO: Compiler unit is timed at 0.000675 msec
10:40:11 DEBUG: built-in procedure "repl_undot_name" overruled by the RDBMS
10:40:11 DEBUG: built-in procedure "REPL_FQNAME" overruled by the RDBMS
10:40:11 DEBUG: built-in procedure "REPL_COLTYPE_PS" overruled by the RDBMS
10:40:11 DEBUG: built-in procedure "REPL_COLTYPE" overruled by the RDBMS
10:40:11 INFO: Roll forward started
10:40:11 INFO: Roll forward complete
10:40:11 INFO: PL LOG: Installing Virtuoso Conductor version 1.00.8783 (DAV)
10:40:11 INFO: Checkpoint started
10:40:13 INFO: Checkpoint finished, log reused
10:40:13 INFO: PL LOG: VAD_INSTALL: Please update server version (FATAL)
10:40:13 INFO: PL LOG: Errors where detected during installation of "Virtuoso Conductor".
10:40:13 INFO: Checkpoint started
10:40:13 INFO: Checkpoint finished, log reused
10:40:13 INFO: HTTP/WebDAV server online at 8890
10:40:13 INFO: Server online at 1111 (pid 23815)

```

> 现在以前台调试模式启动Virtuoso实例的屏幕输出是什么，即running的输出`virtuoso-t -fd` ？

## like this
```
(base) [lihongjing@master database]$ ls -lh
总用量 23M
-rw-r--r-- 1 lihongjing hpc  20M 12月 23 23:07 virtuoso.db
-rw-r--r-- 1 lihongjing hpc 6.9K 12月 23 22:59 virtuoso.ini
-rw-r--r-- 1 lihongjing hpc 2.8K 12月 23 23:07 virtuoso.log
-rw-r--r-- 1 lihongjing hpc    0 12月 23 23:02 virtuoso.pxa
-rw-r--r-- 1 lihongjing hpc 2.0M 12月 23 23:02 virtuoso-temp.db
-rw-r--r-- 1 lihongjing hpc    0 12月 23 23:07 virtuoso.trx
(base) [lihongjing@master database]$ virtuoso-t -fd

                Wed Dec 25 2019
10:40:09 INFO: { Loading plugin 1: Type `plain', file `wikiv' in `../hosting'
10:40:09 INFO:   WikiV version 0.6 from OpenLink Software
10:40:09 INFO:   Support functions for WikiV collaboration tool
10:40:09 ERROR:   FAILED  plugin 1: Loaded plugin requires core functionality not provided by main application }
10:40:09 INFO: { Loading plugin 2: Type `plain', file `mediawiki' in `../hosting'
10:40:09 INFO:   MediaWiki version 0.1 from OpenLink Software
10:40:09 INFO:   Support functions for MediaWiki collaboration tool
10:40:09 ERROR:   FAILED  plugin 2: Loaded plugin requires core functionality not provided by main application }
10:40:09 INFO: { Loading plugin 3: Type `plain', file `creolewiki' in `../hosting'
10:40:09 INFO:   CreoleWiki version 0.1 from OpenLink Software
10:40:09 INFO:   Support functions for CreoleWiki collaboration tool
10:40:09 ERROR:   FAILED  plugin 3: Loaded plugin requires core functionality not provided by main application }
10:40:09 INFO: { Loading plugin 4: Type `plain', file `im' in `../hosting'
10:40:09 INFO:   IM version 0.62 from OpenLink Software
10:40:09 INFO:   Support functions for Image Magick 6.9.9
10:40:09 ERROR:   FAILED  plugin 4: Loaded plugin requires core functionality not provided by main application }
10:40:09 INFO: OpenLink Virtuoso Universal Server
10:40:09 INFO: Version 06.01.3127-pthreads for Linux as of Jun  9 2014
10:40:09 INFO: uses parts of OpenSSL, PCRE, Html Tidy
10:40:09 INFO: Database version 3126
10:40:09 INFO: SQL Optimizer enabled (max 1000 layouts)
10:40:10 INFO: Compiler unit is timed at 0.000675 msec
10:40:11 DEBUG: built-in procedure "repl_undot_name" overruled by the RDBMS
10:40:11 DEBUG: built-in procedure "REPL_FQNAME" overruled by the RDBMS
10:40:11 DEBUG: built-in procedure "REPL_COLTYPE_PS" overruled by the RDBMS
10:40:11 DEBUG: built-in procedure "REPL_COLTYPE" overruled by the RDBMS
10:40:11 INFO: Roll forward started
10:40:11 INFO: Roll forward complete
10:40:11 INFO: PL LOG: Installing Virtuoso Conductor version 1.00.8783 (DAV)
10:40:11 INFO: Checkpoint started
10:40:13 INFO: Checkpoint finished, log reused
10:40:13 INFO: PL LOG: VAD_INSTALL: Please update server version (FATAL)
10:40:13 INFO: PL LOG: Errors where detected during installation of "Virtuoso Conductor".
10:40:13 INFO: Checkpoint started
10:40:13 INFO: Checkpoint finished, log reused
10:40:13 INFO: HTTP/WebDAV server online at 8890
10:40:13 INFO: Server online at 1111 (pid 23815)

```

**Comment by HughWilliams** [comment]
I thought you replaced the old Virtuoso 6.x binary with a new Virtuoso 7.2 binary ?

But the output you provide show you are still starting the same old version 6.x Virtuoso binary ie `Version 06.01.3127-pthreads for Linux as of Jun  9 2014`  and the same Conductor VAD ie `Installing Virtuoso Conductor version 1.00.8783 (DAV)` ???

Thus were are you copying the new Virtuoso 7.2 binary to, as you clearly are not replacing the old binary ?

If you run the command `which virtuoso-t` than that should show where the `virtuoso-t` is running from and that is what you need to replace with the Virtuoso 7.2 binary and you also want to replace the `conductor_dav.vad` package with the one that comes with the Virtuoso 7.2 binary ...

**Comment by donttal** [comment]
> I thought you replaced the old Virtuoso 6.x binary with a new Virtuoso 7.2 binary?
> 
> But the output you provide show you are still starting the same old version 6.x Virtuoso binary, i.e., `Version 06.01.3127-pthreads for Linux as of Jun 9 2014` and the same Conductor VAD, i.e., `Installing Virtuoso Conductor version 1.00.8783 (DAV)` ???
> 
> Thus where are you copying the new Virtuoso 7.2 binary to, as you clearly are not replacing the old binary?
> 
> If you run the command `which virtuoso-t` than that should show where the `virtuoso-t` is running from, and that is what you need to replace with the Virtuoso 7.2 binary. You also want to replace the `conductor_dav.vad` package with the one that comes with the Virtuoso 7.2 binary ...

As a common user in server, I put `virtuoso-opensource` in `/public/home/lihongjing` and `lihongjing` is my user name. 
I set this in `~/.bashrc`
```
export VIRTUOSO_HOME=/public/home/lihongjing/virtuoso-opensource
export PATH=${VIRTUOSO_HOME}/bin:$PATH
```
And I can not find another version of `virtuoso-opensource` in server.

**Comment by HughWilliams** [comment]
What is the output of running the command `which virtuoso-t` on the the server ?

**Comment by donttal** [comment]
```
(base) [lihongjing@master database]$ which virtuoso-t
/usr/bin/virtuoso-t
```
It seems you are right, so what should I do? Because I do n’t know very well from your previous comments

**Comment by HughWilliams** [comment]
The clearly your statement:

> I set this in `~/.bashrc`
>
> `export VIRTUOSO_HOME=/public/home/lihongjing/virtuoso-opensource`
> `export PATH=${VIRTUOSO_HOME}/bin:$PATH`

Is not actually occurring for some reason. If you run the command `echo $PATH`, what does it report? That should reveal whether `/public/home/lihongjing/virtuoso-opensource/bin` is being placed at the front of `$PATH` such that it is searched first.

Either way, to start the binary you expect to be started, either place the Virtuoso 7.2 `virtuoso-t` binary in `/usr/bin` (replacing the Virtuoso 6 binary); or, rather than depending on the `$PATH` env variable picking up the correct one, just specify the full path and name of the binary to start the Virtuoso database with, i.e. -- 

    /public/home/lihongjing/virtuoso-opensource/bin/virtuoso-t -fd

Note that as stated before, you also need to ensure the Virtuoso 7.2 `conductor_dav.vad` file is being used when starting with the Virtuoso 7.2 binary. The `virtuoso.ini` file will show what `VADInstallDir` is set to, and thus where you should place the VAD.

**Comment by donttal** [comment]
> The clearly your statement:
> 
> > I set this in `~/.bashrc`
> > `export VIRTUOSO_HOME=/public/home/lihongjing/virtuoso-opensource`
> > `export PATH=${VIRTUOSO_HOME}/bin:$PATH`
> 
> Is not actually occurring for some reason. If you run the command `echo $PATH`, what does it report? That should reveal whether `/public/home/lihongjing/virtuoso-opensource/bin` is being placed at the front of `$PATH` such that it is searched first.
> 
> Either way, to start the binary you expect to be started, either place the Virtuoso 7.2 `virtuoso-t` binary in `/usr/bin` (replacing the Virtuoso 6 binary); or, rather than depending on the `$PATH` env variable picking up the correct one, just specify the full path and name of the binary to start the Virtuoso database with, i.e. --
> 
> ```
> /public/home/lihongjing/virtuoso-opensource/bin/virtuoso-t -fd
> ```
> 
> Note that as stated before, you also need to ensure the Virtuoso 7.2 `conductor_dav.vad` file is being used when starting with the Virtuoso 7.2 binary. The `virtuoso.ini` file will show what `VADInstallDir` is set to, and thus where you should place the VAD.

I told the server administrator that the server updated the version later, now I t
run  virtuoso-t -fd
```
(base) [lihongjing@node10 database]$ virtuoso-t -fd

                Wed Jan 01 2020
21:42:02 INFO: { Loading plugin 1: Type `plain', file `wikiv' in `../hosting'
21:42:03 INFO:   WikiV version 0.6 from OpenLink Software
21:42:03 INFO:   Support functions for WikiV collaboration tool
21:42:03 INFO:   SUCCESS plugin 1: loaded from ../hosting/wikiv.so }
21:42:03 INFO: { Loading plugin 2: Type `plain', file `mediawiki' in `../hosting'
21:42:03 INFO:   MediaWiki version 0.1 from OpenLink Software
21:42:03 INFO:   Support functions for MediaWiki collaboration tool
21:42:03 INFO:   SUCCESS plugin 2: loaded from ../hosting/mediawiki.so }
21:42:03 INFO: { Loading plugin 3: Type `plain', file `creolewiki' in `../hosting'
21:42:03 INFO:   CreoleWiki version 0.1 from OpenLink Software
21:42:03 INFO:   Support functions for CreoleWiki collaboration tool
21:42:03 INFO:   SUCCESS plugin 3: loaded from ../hosting/creolewiki.so }
21:42:03 INFO: { Loading plugin 4: Type `plain', file `im' in `../hosting'
21:42:04 INFO:   IM version 0.62 from OpenLink Software
21:42:04 INFO:   Support functions for Image Magick 6.9.9
21:42:04 INFO:   SUCCESS plugin 4: loaded from ../hosting/im.so }
21:42:04 INFO: OpenLink Virtuoso Universal Server
21:42:04 INFO: Version 07.20.3229-pthreads for Linux as of Aug 15 2018
21:42:04 INFO: uses parts of OpenSSL, PCRE, Html Tidy
21:42:04 INFO: SQL Optimizer enabled (max 1000 layouts)
21:42:04 INFO: Compiler unit is timed at 0.000400 msec
21:42:14 INFO: Checkpoint started
21:42:15 INFO: Roll forward started
21:42:15 INFO: Roll forward complete
21:42:15 INFO: Checkpoint started
21:42:15 INFO: Checkpoint finished, log reused
21:42:15 INFO: Checkpoint started
21:42:15 INFO: Checkpoint finished, log reused
21:42:24 INFO: Checkpoint started
21:42:25 INFO: Checkpoint finished, log reused
21:42:28 INFO: Checkpoint started
21:42:31 INFO: Checkpoint finished, log reused
21:42:36 INFO: Checkpoint started
21:42:46 INFO: Checkpoint finished, log reused
21:42:48 INFO: PL LOG: Installing Virtuoso Conductor version 1.00.8783 (DAV)
21:42:48 INFO: PL LOG: Installing with dependencies Virtuoso Conductor version 1.00.8783/2018-08-15 20:02 (DAV)
21:42:48 INFO: Checkpoint started
21:42:50 INFO: Checkpoint finished, log reused
21:42:54 INFO: Checkpoint started
21:42:54 INFO: Checkpoint finished, log reused
21:42:54 INFO: PL LOG: Installation with dependencies complete
21:42:54 INFO: Checkpoint started
21:42:54 INFO: Checkpoint finished, log reused
21:42:54 INFO: HTTP/WebDAV server online at 8890
21:42:54 INFO: Server online at 1111 (pid 103369)

```
Does the output mean that the database is fully operational?

**Comment by HughWilliams** [comment]
Yes ...
