### ISSUE TITLE
304 caching issue

### ISSUE THREAD

**Issue by FlorianTolk** [openlink/virtuoso-opensource#892]
I am hosting a very basic test page (just a hello world right now) as recently my webpage stopped running.

When I sign into the `http://baseUrl` (that should send me to the base index.html page) I am just getting a redirect, and then a 404 looking for ./favicon

When I go to my `http://baseUrl/conductor` however, I am getting the admin page. Is this  a known error? If so, how do I resolve this?

Thanks in advance!

**Comment by HughWilliams** [comment]
I have no idea what you are seeking to do or logging into on `http://baseUrl` that is giving this apparent 404 error ?

I assume based on the `http://baseUrl/conductor` URL referred to you are using Virtuoso, in which case `http://baseUrl/` should take you to the Virtuoso home page which does not require any login to access it. Thus, have you in some way been customising your Virtuoso instance, possibly changing its root (`/`) virtual directory web page to load some other service or application?

Please provide details on what you are doing and how you got there from a base Virtuoso installation ...

**Comment by FlorianTolk** [comment]
In the `virtuoso.ini` file, I changed the `[HTTPServer]` settings, so that the root directory takes me to my own index page, as so:
```
[HTTPServer]
ServerPort                  = 80
ServerRoot                  = /var/www/html
MaxClientConnections        = 10
DavRoot                     = DAV
EnabledDavVSP               = 0
HTTPProxyEnabled            = 0
TempASPXDir                 = 0
DefaultMailServer           = localhost:25
ServerThreads               = 10
MaxKeepAlives               = 10
KeepAliveTimeout            = 10
MaxCachedProxyConnections   = 10
ProxyConnectionCacheTimeout = 15
HTTPThreadSize              = 280000
HttpPrintWarningsInOutput   = 0
Charset                     = UTF-8
HTTPLogFile                 = /var/log/http.log
MaintenancePage             = atomic.html
EnabledGzipContent          = 1
```

After running `sudo virtuoso-t +debug +configfile [PathToIniFile]` it works for one user to view the home page, and then it no longer serves my `index.html` page, just throws a `404` error.

**Comment by FlorianTolk** [comment]
My step by step process from vanilla Ubuntu 16.04 is:

```
$ sudo apt-get update && sudo apt-get upgrade -y
$ sudo apt-get install autoconf dpkg-dev build-essential autoconf automake libtool flex bison gperf gawk m4 make odbcinst libxml2-dev libssl-dev libreadline-dev openssl libssl-dev git
$ mkdir -p ~/VOS7_sources/
$ cd ~/VOS7_sources/
$ git clone git://github.com/openlink/virtuoso-opensource.git
$ cd virtuoso-opensource
$ git checkout develop/7
$ sudo ./autogen.sh
```
Then I configure the installation to the path `/usr/local/virtuoso`, rename the tool `isql` to `isql-v` to avoid conflicts with the unixodbc existing `isql`. I also install VAD packages and turn on debugging.

```
$ ./configure --prefix=/usr/local/ --with-readline --program-transform-name="s/isql/isql-v/" --with-layout=Debian --with-debug --enable-rdfmappers-vad --enable-conductor-vad --enable-rdb2rdf-vad --enable-fct-vad --enable-isparql-vad --enable-cartridges-vad  --enable-maintainer-mode
$ sudo nice make
$ sudo make install
```
I then `vim /usr/local/var/lib/virtuoso-opensource-7/db/virtuoso.ini` to set the `HTTPServer` information to the previously listed settings, and place my `index.html` file into the `/var/www/html` directory before continuing

```
$ cd /usr/local/bin
$ sudo virtuoso-t +debug +configfile /usr/local/var/lib/virtuoso-opensource-7/db/virtuoso.ini
```

The new "homepage" is currently just a very basic hello world html file to test my Virtuoso settings, and as stated previously, works for exactly 1 user, 1 time.

In case it makes any difference: this server has been run on an AWS t2 small and t3 small server, with the same issue.

**Comment by FlorianTolk** [comment]
Here are the logs from the first, second, and third machine to try to connect afterwards

First attempt - All Good
```
104.183.195.113 - - [07/Jan/2020:18:04:52 +0000] "GET / HTTP/1.1" 200 21952 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
104.183.195.113 - - [07/Jan/2020:18:04:52 +0000] "GET /assets/css/main_ver2.css?v=5.8.2019.2 HTTP/1.1" 200 16316 "http://3.90.141.247/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
104.183.195.113 - - [07/Jan/2020:18:04:52 +0000] "GET /assets/js/jquery.dropotron.min.js HTTP/1.1" 200 5106 "http://3.90.141.247/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
104.183.195.113 - - [07/Jan/2020:18:04:52 +0000] "GET /assets/js/skel-viewport.min.js HTTP/1.1" 200 1177 "http://3.90.141.247/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
104.183.195.113 - - [07/Jan/2020:18:04:52 +0000] "GET /assets/js/skel.min.js HTTP/1.1" 200 9085 "http://3.90.141.247/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
104.183.195.113 - - [07/Jan/2020:18:04:52 +0000] "GET /assets/js/util.js HTTP/1.1" 200 12433 "http://3.90.141.247/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
104.183.195.113 - - [07/Jan/2020:18:04:52 +0000] "GET /assets/js/jquery.min.js HTTP/1.1" 200 95957 "http://3.90.141.247/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
104.183.195.113 - - [07/Jan/2020:18:04:52 +0000] "GET /images/ADL_Logo_145px.png HTTP/1.1" 200 18538 "http://3.90.141.247/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
104.183.195.113 - - [07/Jan/2020:18:04:52 +0000] "GET /assets/css/font-awesome.min.css HTTP/1.1" 200 29063 "http://3.90.141.247/assets/css/main_ver2.css?v=5.8.2019.2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
```

Second and Third Attempt - Error
```
104.183.195.113 - - [07/Jan/2020:18:04:56 +0000] "GET / HTTP/1.1" 304 0 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
104.183.195.113 - - [07/Jan/2020:18:04:56 +0000] "GET /favicon.ico HTTP/1.1" 404 216 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"

104.183.195.113 - - [07/Jan/2020:18:05:13 +0000] "GET /favicon.ico HTTP/1.1" 404 216 "http://BaseURL/" "Mozilla/5.0 (Linux; Android 10; Pixel 2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Mobile Safari/537.36"
104.183.195.113 - - [07/Jan/2020:18:05:15 +0000] "GET / HTTP/1.1" 304 0 "" "Mozilla/5.0 (Linux; Android 10; Pixel 2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Mobile Safari/537.36"
```

So it looks like the 404 on the favicon is a red herring, but instead the 304 is the issue.

It looks like for some reason the server believes the data is already cached, so it's not sharing anything, causing a blank page to appear instead of the expected HTML page. Changing the title to reflect that.

**Comment by FlorianTolk** [comment]
Also, a verbose curl from the server will return with the html code, but a verbose curl from any other machine will run like this:
```
* STATE: INIT => CONNECT handle 0x20048138; line 1034 (connection #-5000)
* Rebuilt URL to: 3.90.141.247/
* Added connection 0. The cache now contains 1 members
*   Trying 3.90.141.247...
* STATE: CONNECT => WAITCONNECT handle 0x20048138; line 1087 (connection #0)
* Connected to 3.90.141.247 (3.90.141.247) port 80 (#0)
* STATE: WAITCONNECT => DO handle 0x20048138; line 1229 (connection #0)
> GET / HTTP/1.1
> User-Agent: Mozilla/5.0 (Windows; U; MSIE 9.0; WIndows NT 9.0; en-US))
> Host:  [URL]
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x20048138; line 1314 (connection #0)
* STATE: DO_DONE => WAITPERFORM handle 0x20048138; line 1441 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x20048138; line 1454 (connection #0)
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< ETag: "219521578064970d1546d731a9f30cc80127d57142a482b"
< Last-Modified: Fri, 03 Jan 2020 15:22:50 GMT
< Date: Tue, 07 Jan 2020 20:55:45 GMT
* Server Virtuoso/07.20.3230 (Linux) x86_64-pc-linux-gnu is not blacklisted
< Server: Virtuoso/07.20.3230 (Linux) x86_64-pc-linux-gnu
< Age: 734
< X-Cache: HIT from mAC17C8CC06F3
< X-Cache-Lookup: HIT from mAC17C8CC06F3:3128
< Via: 1.1 mAC17C8CC06F3 (squid/3.5.28)
< Connection: close
<
* Excess found in a non pipelined read: excess = 3771 url = / (zero-length body)
* STATE: PERFORM => DONE handle 0x20048138; line 1626 (connection #0)
* Closing connection 0
* The cache now contains 0 members
* Expire cleared
```

**Comment by TallTed** [comment]
I'm trying to understand your full description...

It's clear that machine2 (request2) and machine3 (request3) do not receive the expected page, after machine1 (request1) does receive the expected page. What happens if **machine1** issues request4 (or request2 or request3) for that same page?

It's hard to compare things when we only have one of the things being compared.  Therefore, can we see the verbose `curl` on the successful machine1's request1? (We probably don't need to see the HTML itself, so you can elide that.)

Also, is there anything interesting showing up in `/var/log/http.log` or `/usr/local/var/lib/virtuoso-opensource-7/db/virtuoso.log`?

**Comment by FlorianTolk** [comment]
When machine1 runs another request (after clearing the browser's cache) you get the exact same 304 error. In the above example, request 2 was done by machine 1.

The above logs were from `/var/log/http.log` and `/usr/local/var/lib/virtuoso-opensource-7/db/virtuoso.log` doesn't show anything out of the ordinary either:
```
                Tue Jan 07 2020
18:03:25 INFO: { Loading plugin 1: Type `plain', file `wikiv' in `/usr/local/lib/virtuoso-opensource-7/hosting'
18:03:25 INFO:   WikiV version 0.6 from OpenLink Software
18:03:25 INFO:   Support functions for WikiV collaboration tool
18:03:25 INFO:   SUCCESS plugin 1: loaded from /usr/local/lib/virtuoso-opensource-7/hosting/wikiv.so }
18:03:25 INFO: { Loading plugin 2: Type `plain', file `mediawiki' in `/usr/local/lib/virtuoso-opensource-7/hosting'
18:03:25 INFO:   MediaWiki version 0.1 from OpenLink Software
18:03:25 INFO:   Support functions for MediaWiki collaboration tool
18:03:25 INFO:   SUCCESS plugin 2: loaded from /usr/local/lib/virtuoso-opensource-7/hosting/mediawiki.so }
18:03:25 INFO: { Loading plugin 3: Type `plain', file `creolewiki' in `/usr/local/lib/virtuoso-opensource-7/hosting'
18:03:25 INFO:   CreoleWiki version 0.1 from OpenLink Software
18:03:25 INFO:   Support functions for CreoleWiki collaboration tool
18:03:25 INFO:   SUCCESS plugin 3: loaded from /usr/local/lib/virtuoso-opensource-7/hosting/creolewiki.so }
18:03:25 INFO: { Loading plugin 10: Type `plain', file `shapefileio' in `/usr/local/lib/virtuoso-opensource-7/hosting'
18:03:25 INFO:   ShapefileIO version 0.1virt71 from OpenLink Software
18:03:25 INFO:   Shapefile support based on Frank Warmerdam's Shapelib
18:03:25 INFO:   SUCCESS plugin 10: loaded from /usr/local/lib/virtuoso-opensource-7/hosting/shapefileio.so }
18:03:25 DEBUG: Initializing PRNG
18:03:25 INFO: OpenLink Virtuoso Universal Server
18:03:25 INFO: Version 07.20.3230-pthreads for Linux as of Jan  7 2020
18:03:25 INFO: uses parts of OpenSSL, PCRE, Html Tidy
18:03:25 INFO: SQL Optimizer enabled (max 1000 layouts)
18:03:26 INFO: Compiler unit is timed at 0.000901 msec
18:03:30 INFO: Checkpoint started
18:03:30 INFO: Roll forward started
18:03:30 INFO: Roll forward complete
18:03:30 INFO: Checkpoint started
18:03:30 INFO: Checkpoint finished, log reused
18:03:30 INFO: Checkpoint started
18:03:30 INFO: Checkpoint finished, log reused
18:03:30 INFO: Checkpoint started
18:03:30 INFO: Checkpoint finished, log reused
18:03:31 INFO: Checkpoint started
18:03:31 INFO: Checkpoint finished, log reused
18:03:31 INFO: Checkpoint started
18:03:31 INFO: Checkpoint finished, log reused
18:03:31 INFO: PL LOG: Installing Virtuoso Conductor version 1.00.8810 (DAV)
18:03:31 INFO: PL LOG: Installing with dependencies Virtuoso Conductor version 1.00.8810/2020-01-07 18:00 (DAV)
18:03:31 INFO: Checkpoint started
18:03:31 INFO: Checkpoint finished, log reused
18:03:34 INFO: Checkpoint started
18:03:34 INFO: Checkpoint finished, log reused
18:03:34 INFO: PL LOG: Installation with dependencies complete
18:03:34 INFO: Checkpoint started
18:03:34 INFO: Checkpoint finished, log reused
18:03:35 INFO: HTTP/WebDAV server online at 80
18:03:35 INFO: Server online at 1111 (pid 26741)
19:03:36 INFO: Checkpoint started
19:03:36 INFO: Checkpoint finished, log reused
```

**Comment by FlorianTolk** [comment]
A verbose curl from the server to itself looks like expected:
```
* Rebuilt URL to: localhost/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 21952
< Content-Type: text/html; charset=UTF-8
< ETag: "219521578064970d1546d731a9f30cc80127d57142a482b"
< Last-Modified: Fri, 03 Jan 2020 15:22:50 GMT
< Date: Wed, 08 Jan 2020 12:00:01 GMT
< Server: Virtuoso/07.20.3230 (Linux) x86_64-pc-linux-gnu  
< Connection: Keep-Alive
<
[HTML Page]
* Connection #0 to host localhost left intact
```

**Comment by vbhayden** [comment]
Morning team,

To clarify, the problem is that the Virtuoso server seems to send back an empty response for some pages that have already been queried.  I don't know much about Virtuoso at all and was adamant that this was probably a mistake on Florian's part and some weird issue with browser caching, but it really does seem to be on the server side.

The service in question is **[http://xapi.vocab.pub/](http://xapi.vocab.pub/)**.  If you browse there and hard refresh, then subsequent requests give an empty response.  You can even check this with Python:

```
>>> res = rq.get("http://xapi.vocab.pub?id=4") 
>>> len(res.text)
21948
>>> res = rq.get("http://xapi.vocab.pub?id=4") 
>>> len(res.text)
0
>>> res = rq.get("http://xapi.vocab.pub?id=5") 
>>> len(res.text)
21948
>>> res = rq.get("http://xapi.vocab.pub?id=5") 
>>> len(res.text)
0
```

The behavior isn't quite uniform though.  Something like **[the Verbs page](http://54.157.35.203/verbs/)** will present the same behavior but seems to always respond with query arguments in the browser (always returning for `?id=`).  That endpoint will respond differently when queried from Python though, behaving identically to the homepage:

```
>>> res = rq.get("http://xapi.vocab.pub/verbs?id=200") 
>>> len(res.text)
7927
>>> res = rq.get("http://xapi.vocab.pub/verbs?id=200") 
>>> len(res.text)
0
>>> res = rq.get("http://xapi.vocab.pub/verbs?id=300") 
>>> len(res.text)
7927
>>> res = rq.get("http://xapi.vocab.pub/verbs?id=300")
>>> len(res.text)
0
```

It seems like Virtuoso is trying to optimize its response times by anticipating and working in concert with browser caches.  Regardless of what's causing it, is this a familiar situation to anyone and, if so, how do we get around it?

Thanks,
-Trey

**Comment by TallTed** [comment]
@imitko @timhaynesopenlink @pkleef @openlink 

Please have a look at this...

**Comment by vbhayden** [comment]
Looked into it a bit more this morning.  

The behavior doesn't seem to be coming from Virtuoso directly but in response to the `Last-Modified` header.  From the **[/libsrc/Wi/http.c source](https://github.com/openlink/virtuoso-opensource/blob/master/libsrc/Wi/http.c#L2811)**, this header is explicitly embedded in each http response based on the file's metadata.  

As the responses all have the following additional headers that aren't coming from Virtuoso:
```
'X-Cache': 'HIT from some-addr',
'X-Cache-Lookup': 'HIT from some-addr:number',
'Via': '1.1 some-addr (squid/3.5.28)'
```
So, it seems that our traffic is being proxied by a Squid instance which needs to be configured to stop aggressively caching requests based on `Last-Modified`. 

Unless there's a way to remove that header in the Virtuoso config, then I think this can be closed as the cited behavior isn't really a result of the server's behavior.  Thanks for your patience, team.

-Trey

**Comment by TallTed** [comment]
@FlorianTolk - I think @vbhayden [has it right](https://github.com/openlink/virtuoso-opensource/issues/892#issuecomment-573102573). Please let us know whether you concur with closing this.

**Comment by FlorianTolk** [comment]
I believe so as well, closing now.
