### ISSUE TITLE
Common Table Expressions

### ISSUE THREAD

**Issue by mwallnoefer** [openlink/virtuoso-opensource#896]
I am wondering if Virtuoso will add support for the nowadays very common `WITH [RECURSIVE]` queries.

**Comment by HughWilliams** [comment]
There is no immediate intention to support `WITH [RECURSIVE]`. Is there a specific use case you are seeking a solution using this type of query? 

`WITH RECURSIVE` seems to be related to [Transitivity Option](http://docs.openlinksw.com/virtuoso/transitivityinsql/) which Virtuoso does support. We maybe able to recreate some of the `WITH RECURSIVE` examples using the Transitive Option.

**Comment by mwallnoefer** [comment]
Alright. This could indeed be mentioned somewhere in the docs, e.g. _Virtuoso does not support the CTEs (Common Table Expressions) but instead provides recursive queries over the proprietary Transitivity Option_.
