### ISSUE TITLE
Updatable views

### ISSUE THREAD

**Issue by mwallnoefer** [openlink/virtuoso-opensource#901]
Many DBMS (PostgreSQL, MySQL, on SQLite over triggers) nowadays support views which get editable if some circumstances are met (usually built on one single table, no joins, no aggregates). Checking the docs [CREATE VIEW](http://docs.openlinksw.com/virtuoso/createview/) does not seem that Virtuoso implements this. Does there exist any plan to do so?

**Comment by HughWilliams** [comment]
Updatable Views are support using triggers as detailed in the Virtuoso [Triggers on Views](http://docs.openlinksw.com/virtuoso/triggers_on_views/) documentation ...

**Comment by mwallnoefer** [comment]
Ah, thanks, so it works the same like in SQLite.
