### ISSUE TITLE
Fail to start a service due to "Failed to start listening at SQL port '1111'"

### ISSUE THREAD

**Issue by CbcWestwolf** [openlink/virtuoso-opensource#904]
Hi,

With the guidance of [this page](http://vos.openlinksw.com/owiki/wiki/VOS/VOSUsageWindows#Basic%20Installation), I have 
1. installed the [Virtuoso_OpenSource_Server_7.20.x64.exe](https://github.com/openlink/virtuoso-opensource/releases) on my win10 **C:\Program Files\OpenLink Software\Virtuoso OpenSource 7.20**
2. installed the [64-bit Microsoft Visual C++ 2012 Redistributable Package (x86_64)](http://www.microsoft.com/en-us/download/details.aspx?id=30679#)
3. created a new system environment variable called `VIRTUOSO_HOME` with the path `C:\Program Files\OpenLink Software\Virtuoso OpenSource 7.20`; added `;%VIRTUOSO_HOME%/bin;%VIRTUOSO_HOME%/lib` to the `PATH`

After steps above, `virtuoso-t -?` was able to output something, so I wanted to start a new service:
1. cd %VIRTUOSO_HOME%/database
2. virtuoso-t +service create +instance “New Instance Name” +configfile virtuoso.ini
3. virtuoso-t +instance “New Instance Name” +service start

But `virtuoso-t +service list` still output:
> New Instance Name    Stopped

So I view virtuoso.log as followed:
> 17:21:11 { Loading plugin 1: Type `plain', file `wikiv' in `../hosting'
17:21:11   WikiV version 0.6 from OpenLink Software
17:21:11   Support functions for WikiV collaboration tool
17:21:11   SUCCESS plugin 1: loaded from ..\hosting\wikiv.dll }
17:21:11 { Loading plugin 2: Type `plain', file `mediawiki' in `../hosting'
17:21:11   MediaWiki version 0.1 from OpenLink Software
17:21:11   Support functions for MediaWiki collaboration tool
17:21:11   SUCCESS plugin 2: loaded from ..\hosting\mediawiki.dll }
17:21:11 { Loading plugin 3: Type `plain', file `creolewiki' in `../hosting'
17:21:11   CreoleWiki version 0.1 from OpenLink Software
17:21:11   Support functions for CreoleWiki collaboration tool
17:21:11   SUCCESS plugin 3: loaded from ..\hosting\creolewiki.dll }
17:21:11 { Loading plugin 4: Type `plain', file `im' in `../hosting'
17:21:11   IM version 0.6 from OpenLink Software
17:21:11   Support functions for Image Magick 6.9.9
17:21:11   SUCCESS plugin 4: loaded from ..\hosting\im.dll }
17:21:11 { Loading plugin 5: Type `plain', file `wbxml2' in `../hosting'
17:21:11   WBXML2 version 0.9 from OpenLink Software
17:21:11   Support functions for WBXML2 0.9.2 Library
17:21:11   SUCCESS plugin 5: loaded from ..\hosting\wbxml2.dll }
17:21:11 OpenLink Virtuoso Universal Server
17:21:11 Version 07.20.3217-threads for Win64 as of Sep  6 2017
17:21:11 uses parts of OpenSSL, PCRE, Html Tidy
17:21:11 Database version 3126
17:21:11 SQL Optimizer enabled (max 1000 layouts)
17:21:12 Compiler unit is timed at 0.000112 msec
17:21:12 Roll forward started
17:21:12 Roll forward complete
17:21:13 Checkpoint started
17:21:13 Checkpoint finished, log reused
17:21:13 Failed to start listening at SQL port '1111'
17:21:13 Server exiting

I searched *Failed to start listening at SQL port '1111'* on Google and [this issue](https://github.com/openlink/virtuoso-opensource/issues/624) but got few helps, so I would to look for help that how can I fix it?

Thanks!

**Comment by HughWilliams** [comment]
If Virtuoso fails to listen on port 1111 then that is an indication that the port is already in use by another process, which most probably is another Virtuoso instance started on the machine you are not aware of. Thus I would suggest using the Windows "Task Manager" program to see if any other Virtuoso executables are running.

Or their maybe some other process running that is using port 1111, which you would need to determine. The command "netstat -a | grep 1111" should show if port 1111 is already in use.

**Comment by CbcWestwolf** [comment]
> If Virtuoso fails to listen on port 1111 then that is an indication that the port is already in use by another process, which most probably is another Virtuoso instance started on the machine you are not aware of. Thus I would suggest using the Windows "Task Manager" program to see if any other Virtuoso executables are running.
> 
> Or their maybe some other process running that is using port 1111, which you would need to determine. The command "netstat -a | grep 1111" should show if port 1111 is already in use.

Thanks for your reply!

But I tried `netstat -aon|findstr "1111"` which outputs nothing. And I tried again after reboot but got the same log. What could I try next?

BTW, maybe change another port can help? Besides editing `ServerPort` in `virtuoso.ini`, what else should I do if I want to use another port?

Thank you!

**Comment by HughWilliams** [comment]
If you rebooted and still cannot bind to port 1111 then it must be in use by another process. Note the registered /etc/services service-name for port 1111 is "lmsocialserver" thus you should check if that name is in use with netstat also.

You can also try changing the port to another like 1112 and the `ServerPort` param in the `[Parameters]` section of the INI file is all you have to change.

Should you still have issue please provide a complete copy of the `virtuoso.ini` file for review ...

**Comment by CbcWestwolf** [comment]
> If you rebooted and still cannot bind to port 1111 then it must be in use by another process. Note the registered /etc/services service-name for port 1111 is "lmsocialserver" thus you should check if that name is in use with netstat also.
> 
> You can also try changing the port to another like 1112 and the `ServerPort` param in the `[Parameters]` section of the INI file is all you have to change.
> 
> Should you still have issue please provide a complete copy of the `virtuoso.ini` file for review ...

Although changing the port to `1112` can't help, port `1234` helps and the status can be running now! Thanks for your patience and help!
