### ISSUE TITLE
Failed to connect to localhost:8890

### ISSUE THREAD

**Issue by gaofengning** [openlink/virtuoso-opensource#906]
Hi

I have made my service running successfully, but still can't connect to localhost:8890.

 I view virtuoso.log as followed:

> 19:31:22 { Loading plugin 1: Type `plain', file `wikiv' in `../hosting'
> 19:31:22   WikiV version 0.6 from OpenLink Software
> 19:31:22   Support functions for WikiV collaboration tool
> 19:31:22   SUCCESS plugin 1: loaded from ..\hosting\wikiv.dll }
> 19:31:22 { Loading plugin 2: Type `plain', file `mediawiki' in `../hosting'
> 19:31:22   MediaWiki version 0.1 from OpenLink Software
> 19:31:22   Support functions for MediaWiki collaboration tool
> 19:31:22   SUCCESS plugin 2: loaded from ..\hosting\mediawiki.dll }
> 19:31:22 { Loading plugin 3: Type `plain', file `creolewiki' in `../hosting'
> 19:31:22   CreoleWiki version 0.1 from OpenLink Software
> 19:31:22   Support functions for CreoleWiki collaboration tool
> 19:31:22   SUCCESS plugin 3: loaded from ..\hosting\creolewiki.dll }
> 19:31:22 { Loading plugin 4: Type `plain', file `im' in `../hosting'
> 19:31:23   IM version 0.6 from OpenLink Software
> 19:31:23   Support functions for Image Magick 6.6.7
> 19:31:23   SUCCESS plugin 4: loaded from ..\hosting\im.dll }
> 19:31:23 { Loading plugin 5: Type `plain', file `wbxml2' in `../hosting'
> 19:31:23   WBXML2 version 0.9 from OpenLink Software
> 19:31:23   Support functions for WBXML2 0.10.7 Library
> 19:31:23   SUCCESS plugin 5: loaded from ..\hosting\wbxml2.dll }
> 19:31:23 OpenLink Virtuoso Universal Server
> 19:31:23 Version 07.20.3217-threads for Win64 as of Apr 25 2016
> 19:31:23 uses parts of OpenSSL, PCRE, Html Tidy
> 19:31:23 Database version 3126
> 19:31:23 SQL Optimizer enabled (max 1000 layouts)
> 19:31:24 Compiler unit is timed at 0.000184 msec
> 19:31:34 Roll forward started
> 19:31:34 Roll forward complete
> 19:31:53 Checkpoint started
> 19:31:53 Checkpoint finished, log reused
> 19:31:53 * Monitor: High disk read (1)
> 19:31:53 HTTP/WebDAV server online at 8890
> 19:31:53 Server online at 1111 (pid 9792)

I have searched for the solution to it but get few helps, so  I would like to look for help that how can I fix it?

**Comment by HughWilliams** [comment]
Hi

At the beginning of your "virtuoso.log" file was the Virtuoso Conductor [VAD](http://docs.openlinksw.com/virtuoso/vaddistr/) listed as being successfully installed as the 404 error would indicate it was not. If not then you should be able to manually install the Conductor with the command `vad_install ('../vad/conductor_dav.vad', 0);` using the isql command line tool, assuming the `conductor_dav.vad` file exists in the `vad` folder for your Virtuoso installation directory. Note you can also obtain a list of installed VADs with the command `vad_list_packages();`.

**Comment by gaofengning** [comment]
> Hi

> At the beginning of your "virtuoso.log" file was the Virtuoso Conductor VAD listed as being successfully installed as the 404 error would indicate it was not. If not then you should be able to manually install the Conductor with the command vad_install ('../vad/conductor_dav.vad', 0); using the isql command line tool, assuming the conductor_dav.vad file exists in the vad folder for your Virtuoso installation directory. Note you can also obtain a list of installed VADs with the command vad_list_packages();.

Thanks for your reply!

Conductor_dav.vad has already existed in the vad folder. I can use the isql command line tool successfully. So I installed conductor again in case for some errors. But I still can't connect to localhost:8890 by my browser.

Is there anything other that can lead to this problem?

Thank you!

**Comment by gaofengning** [comment]
I change the ServerPort from 8890 to another one, and I can connect to localhost successfully! It seems that the port 8890 has been used although I don't konw how it happend.

Sorry to bother you for a long time. Thanks again for you help!

**Comment by HughWilliams** [comment]
Great glad to hear you have resolved the issue, will close this git issue now ...
