### ISSUE TITLE
urlopen error [Errno 111] Connection refused

### ISSUE THREAD

**Issue by chenQ1114** [openlink/virtuoso-opensource#907]
Hi 

I have installed virtuoso and loaded freebase data to graph in the virtuoso. But, when I search the query via url="http://localhost:8890/sparql/"， I got such error in the server below. Though the comment "netstat -ntlp"， the local address 0.0.0.0:8890 with 24431/virtuoso-t PID could be found in the list. Is there any monitor in the virtuoso to check the local host server has been closed or opened?

Traceback (most recent call last):
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "freebase_query.py", line 285, in <module>
    print(one_hop_query("John Lennon", "New York City"))
  File "freebase_query.py", line 149, in one_hop_query
    json_response = sparql_query(query, query_url)
  File "freebase_query.py", line 29, in sparql_query
    http_response = request.urlopen(URL, encoded_query).read()
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/mwp141/anaconda3/envs/chenML/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by HughWilliams** [comment]
Can you connect to `http://localhost:8890` from a web browser or with the curl command `curl -IL http://localhost:8890` ?

If you check the `virtuoso.log` file on startup it should show the Virtuoso has successfully started with on SQL port 1111 and HTTP port 8890 of the form:

```
22:08:42 { Loading plugin 1: Type `plain', file `wikiv' in `../hosting'
22:08:42   WikiV version 0.6 from OpenLink Software
22:08:42   Support functions for WikiV collaboration tool
22:08:42   SUCCESS plugin 1: loaded from ../hosting/wikiv.so }
22:08:42 { Loading plugin 2: Type `plain', file `mediawiki' in `../hosting'
22:08:42   MediaWiki version 0.1 from OpenLink Software
22:08:42   Support functions for MediaWiki collaboration tool
22:08:42   SUCCESS plugin 2: loaded from ../hosting/mediawiki.so }
22:08:42 { Loading plugin 3: Type `plain', file `creolewiki' in `../hosting'
22:08:42   CreoleWiki version 0.1 from OpenLink Software
22:08:42   Support functions for CreoleWiki collaboration tool
22:08:42   SUCCESS plugin 3: loaded from ../hosting/creolewiki.so }
22:08:42 { Loading plugin 4: Type `plain', file `im' in `../hosting'
22:08:43   IM version 0.63 from OpenLink Software
22:08:43   Support functions for Image Magick 6.9.10
22:08:43   SUCCESS plugin 4: loaded from ../hosting/im.so }
22:08:43 { Loading plugin 5: Type `plain', file `wbxml2' in `../hosting'
22:08:43   WBXML2 version 0.9 from OpenLink Software
22:08:43   Support functions for WBXML2 0.9.2 Library
22:08:43   SUCCESS plugin 5: loaded from ../hosting/wbxml2.so }
22:08:43 { Loading plugin 6: Type `attach', file `libphp5.so' in `../hosting'
22:08:43   SUCCESS plugin 6: loaded from ../hosting/libphp5.so }
22:08:43 { Loading plugin 7: Type `Hosting', file `hosting_php.so' in `../hosting'
22:08:43   Hosting version 3315 from OpenLink Software
22:08:43   PHP engine version 5.6.40
22:08:45   SUCCESS plugin 7: loaded from ../hosting/hosting_php.so }
22:08:45 { Loading plugin 8: Type `plain', file `qrcode' in `../hosting'
22:08:45   QRcode version 0.1 from OpenLink Software
22:08:45   Support functions for ISO/IEC 18004:2006, using QR Code encoder (C) 2006 Kentaro Fukuchi <fukichi@megaui.net>
22:08:45   SUCCESS plugin 8: loaded from ../hosting/qrcode.so }
22:08:45 { Loading plugin 10: Type `plain', file `proj4' in `../hosting'
22:08:45   plain version 1.0.3316 from OpenLink Software
22:08:45   Cartographic Projections support based on Frank Warmerdam's proj4 library
22:08:45   SUCCESS plugin 10: loaded from ../hosting/proj4.so }
22:08:45 { Loading plugin 11: Type `plain', file `geos' in `../hosting'
22:08:45   plain version 1.1.3316 from OpenLink Software
22:08:45   GEOS plugin based on Geometry Engine Open Source library from Open Source Geospatial Foundation
22:08:45   SUCCESS plugin 11: loaded from ../hosting/geos.so }
22:08:45 { Loading plugin 12: Type `plain', file `shapefileio' in `../hosting'
22:08:45   ShapefileIO version 0.1virt71 from OpenLink Software
22:08:45   Shapefile support based on Frank Warmerdam's Shapelib
22:08:45   SUCCESS plugin 12: loaded from ../hosting/shapefileio.so }
22:08:45 OpenLink Virtuoso Universal Server
22:08:45 Version 08.03.3316-pthreads for Mac OS X as of Mar  6 2020
22:08:45 uses OpenSSL 1.0.2s  28 May 2019
22:08:45 uses parts of PCRE, Html Tidy
22:08:45 Database version 3126
22:08:45 Unlinked the temp db file virtuoso-temp.db as its size (12MB) was greater than TempDBSize INI (10MB)
22:08:45 SQL Optimizer enabled (max 1000 layouts)
22:08:47 Compiler unit is timed at 0.000108 msec
22:08:48 built-in procedure "EXEC_STMT" overruled by the RDBMS
22:08:49 built-in procedure "WS.WS.SYS_DAV_RES_RES_CONTENT_HOOK" overruled by the RDBMS
22:08:49 built-in procedure "WS.WS.SYS_DAV_RES_RES_CONTENT_INDEX_HOOK" overruled by the RDBMS
22:08:51 Roll forward started
22:08:51 Roll forward complete
22:08:53 Checkpoint started
22:08:53 Checkpoint finished, log reused
22:08:55 HTTP/WebDAV server online at 8890
22:08:55 Server online at 1111 (pid 40857)
```

Also, can you make a Virtuoso "isql" connection to the SQL port 1111 which would also prove Virtuoso is running.

**Comment by chenQ1114** [comment]
Thanks!

As I changed the ServerPort to 1234, the virtuoso.log file shows the show
the Virtuoso has successfully started with on SQL port 1111 and HTTP port
8890 of the same form with yours except the Server online at 1234.
And I could get the report wih the curl command curl -IL
http://localhost:8890 or curl -IL http://localhost:8890/

Here are the reports:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0
  0  4703    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 4703
Content-Type: text/html; charset=UTF-8
ETag: "47031586161509d1546d731a9f30cc80127d57142a482b"
Last-Modified: Mon, 06 Apr 2020 08:25:09 GMT
Date: Sun, 12 Apr 2020 23:51:08 GMT
Server: Virtuoso/07.20.3230 (Linux) x86_64-unknown-linux-gnu
Connection: Keep-Alive

  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0
  0 11867    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0
HTTP/1.1 200 OK
Server: Virtuoso/07.20.3230 (Linux) x86_64-unknown-linux-gnu
Connection: Keep-Alive
Date: Mon, 13 Apr 2020 00:02:19 GMT
Accept-Ranges: bytes
Content-Type: text/html; charset=UTF-8
Content-Length: 11867

It seems that the server could connect to the localhost port 8890. But,
when I check the search query from loaded freebase rdf data with the
following code, I can not get the result from loaded graph and could not
find anything.
Maybe there are still some problem with the process of loading data to
virtuoso or my code?

Here is the command to load the data into virtuoso:
isql 1234 dba dba exec="Id_dir_all('pwd/test_dict','*','gb_1g');"
isql 1234 dbq dba exec="rdf_loader_run();"
isql 1234 dba dba exec="checkpoint;"

And a toy code to check the search processing:

    query = '''
    select ?s_mid
    from <%s>
    where {
    {?s_mid <http://rdf.freebase.com/ns/type.object.name> "%s"@en.}
    union
    {?s_mid <http://rdf.freebase.com/ns/common.topic.alias> "%s"@en.}
    }
    ''' % ("gb_1g", "Justin Bieber", "Justin Bieber")

    params = {
        "default-graph": '',
        "should-sponge": 'soft',
        "query": query.encode('utf8'),
        "debug": 'on',
        "timeout": '1000000000',
        "format": format,
        "save": 'display',
        "fname": ''
    }

    encoded_query = parse.urlencode(params).encode('utf-8')
    http_response = request.urlopen("http://localhost:8890/sparql/",
encoded_query).read()
    json_response = json.loads(http_response.decode('utf-8'))

    if len(json_response['results']['bindings']):
         # print(json_response['results']['bindings'])
         return True
    else:
         return False

HughWilliams <notifications@github.com> 于2020年4月13日周一 上午6:13写道：

**Comment by chenQ1114** [comment]
I fixed it! Now, I could search the query via virtuoso. Thank you for your
help.

Chen Qiu <qiuchen1114@gmail.com> 于2020年4月13日周一 上午8:26写道：
