### ISSUE TITLE
Make can't find list_lex_props.sh 

### ISSUE THREAD

**Issue by distobj** [openlink/virtuoso-opensource#91]
Just tried a build from git, following the instructions (on Linux Mint 14 x64). make complained saying it couldn't find list_lex_props.sh. Adding libsrc/Wi to my PATH fixed it, but wasn't sure what you'd want the permanent fix to look like.

**Comment by openlink** [comment]
I pushed a fix into develop/6 and develop/7 that does not require the current directory (.) in the PATH.
