### ISSUE TITLE
Slow ld_dir_all in isql performance

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#913]
I'm trying to bulk upload 867,021 ttl files in virtuoso.  It's taken two hours to register 627,729 of them using ld_dir_all (it's still going).  Should it take this long to just register this many files BEFORE rdf_loader_run() is even executed?  Server has 128GB ram and 64 cores and the buffers/max dirty is set as per user guide.

**Comment by ebremer** [comment]
using Version 7.2.6-rc1.3230-pthreads as of Apr 21 2020 on Ubuntu 18

**Comment by imitko** [comment]
Please specify what is the TTL directory file structure? Also what type of disk, I/O stats during ld_dir_all() execution, so we can check what is going on.

**Comment by ebremer** [comment]
It's a flat directory so ld_dir would have been suffice, but I used ld_dir_all instead.  It's a VM running Ubuntu 18 with a 10G network connection to a NetApp storage system using SATA.  The system is doing nothing else and one core is running at 100% to handle the ttl registration.  I do not see alot of IO activity and appears to be registering at 20-30 files a second.

**Comment by ebremer** [comment]
a ls -l | wc -l on the aforementioned folder only takes 7 seconds to yield the 867,021 count.

**Comment by ebremer** [comment]
After a few more hours, I shut virtuoso down, executed "delete from DB.DBA.load_list;" and reloaded the files.  When I ran the ld_dir_all command this time, it took 10 seconds.

**Comment by ebremer** [comment]
I'm not sure what happened, but I am going to close this issue for now.
