### ISSUE TITLE
Recurring messages in log on parallel bulk load

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#914]
The following messages are showing up during a parallel bulk load but data does appear to be loading.  Are these messages something to worry about?  Below on my server specs.

13:16:48 * Monitor: Many lock waits
13:17:04 * Monitor: Locks are held for a long time
13:19:08 * Monitor: Locks are held for a long time
13:19:10 * Monitor: Many lock waits
13:21:11 * Monitor: Many lock waits
13:21:11 * Monitor: Locks are held for a long time
13:23:15 * Monitor: Locks are held for a long time
13:23:23 * Monitor: Many lock waits

867,021 ttl files (small files 300-500 triples) being loaded with 20 threads (64 core machine) with 128GB ram.
Version 7.2.6-rc1.3230-pthreads as of Apr 21 2020
Ubuntu 18 VM with 10GB connection to Netapp storage with SATA drives.

virtuoso.ini:
[Database]
DatabaseFile       = /data/virtuoso/var/lib/virtuoso/db/virtuoso.db
ErrorLogFile       = /data/virtuoso/var/lib/virtuoso/db/virtuoso.log
LockFile           = /data/virtuoso/var/lib/virtuoso/db/virtuoso.lck
TransactionFile    = /data/virtuoso/var/lib/virtuoso/db/virtuoso.trx
xa_persistent_file = /data/virtuoso/var/lib/virtuoso/db/virtuoso.pxa
ErrorLogLevel      = 7
FileExtend         = 122000
MaxCheckpointRemap = 1200000
Striping           = 0
TempStorage        = TempDatabase

[TempDatabase]
DatabaseFile       = /data/virtuoso/var/lib/virtuoso/db/virtuoso-temp.db
TransactionFile    = /data/virtuoso/var/lib/virtuoso/db/virtuoso-temp.trx
MaxCheckpointRemap = 2000
Striping           = 0

;
;  Server parameters
;
[Parameters]
ServerPort               = 1111
LiteMode                 = 0
DisableUnixSocket        = 1
DisableTcpSocket         = 0
;SSLServerPort			= 2111
;SSLCertificate			= cert.pem
;SSLPrivateKey			= pk.pem
;X509ClientVerify		= 0
;X509ClientVerifyDepth		= 0
;X509ClientVerifyCAFile		= ca.pem
MaxClientConnections     = 10
CheckpointInterval       = 1440
O_DIRECT                 = 1
CaseMode                 = 2
MaxStaticCursorRows      = 5000
CheckpointAuditTrail     = 0
AllowOSCalls             = 0
SchedulerInterval        = 10
DirsAllowed              = ., /data/virtuoso/share/virtuoso/vad, /usr/share/proj, /data/rdf, /data01/ebremer
ThreadCleanupInterval    = 0
ThreadThreshold          = 10
ResourcesCleanupInterval = 0
FreeTextBatchSize        = 100000
SingleCPU                = 0
VADInstallDir            = /data/virtuoso/share/virtuoso/vad/
PrefixResultNames        = 0
RdfFreeTextRulesSize     = 100
IndexTreeMaps            = 256
MaxMemPoolSize           = 200000000
PrefixResultNames        = 0
MacSpotlight             = 0
IndexTreeMaps            = 64
MaxQueryMem              = 5G	; memory allocated to query processor
VectorSize               = 10000	; initial parallel query vector (array of query operations) size
MaxVectorSize            = 1000000	; query vector size threshold.
AdjustVectorSize         = 1	; need to experiment with this
ThreadsPerQuery          = 64
AsyncQueueMaxThreads     = 128
NumberOfBuffers          = 10880000
MaxDirtyBuffers          = 8000000

;
;;
;; Note the default settings will take very little memory
;; but will not result in very good performance
;;
;;NumberOfBuffers          = 10000
;;MaxDirtyBuffers          = 6000
[HTTPServer]
ServerPort                  = 8890
ServerRoot                  = /data/virtuoso/var/lib/virtuoso/vsp
MaxClientConnections        = 10
DavRoot                     = DAV
EnabledDavVSP               = 0
HTTPProxyEnabled            = 0
TempASPXDir                 = 0
DefaultMailServer           = localhost:25
ServerThreads               = 10
MaxKeepAlives               = 10
KeepAliveTimeout            = 10
MaxCachedProxyConnections   = 10
ProxyConnectionCacheTimeout = 15
HTTPThreadSize              = 280000
HttpPrintWarningsInOutput   = 0
Charset                     = UTF-8
HTTPLogFile                 = logs/http07052020.log
MaintenancePage             = atomic.html
EnabledGzipContent          = 1

[AutoRepair]
BadParentLinks = 0

[Client]
SQL_PREFETCH_ROWS  = 100
SQL_PREFETCH_BYTES = 16000
SQL_QUERY_TIMEOUT  = 0
SQL_TXN_TIMEOUT    = 0
;SQL_NO_CHAR_C_ESCAPE		= 1
;SQL_UTF8_EXECS			= 0
;SQL_NO_SYSTEM_TABLES		= 0
;SQL_BINARY_TIMESTAMP		= 1
;SQL_ENCRYPTION_ON_PASSWORD	= -1

[VDB]
ArrayOptimization           = 0
NumArrayParameters          = 10
VDBDisconnectTimeout        = 1000
KeepConnectionOnFixedThread = 0

[Replication]
ServerName   = db-STRIX
ServerEnable = 1
QueueMax     = 50000

;
;  Striping setup
;
;  These parameters have only effect when Striping is set to 1 in the
;  [Database] section, in which case the DatabaseFile parameter is ignored.
;
;  With striping, the database is spawned across multiple segments
;  where each segment can have multiple stripes.
;
;  Format of the lines below:
;    Segment<number> = <size>, <stripe file name> [, <stripe file name> .. ]
;
;  <number> must be ordered from 1 up.
;
;  The <size> is the total size of the segment which is equally divided
;  across all stripes forming  the segment. Its specification can be in
;  gigabytes (g), megabytes (m), kilobytes (k) or in database blocks
;  (b, the default)
;
;  Note that the segment size must be a multiple of the database page size
;  which is currently 8k. Also, the segment size must be divisible by the
;  number of stripe files forming  the segment.
;
;  The example below creates a 200 meg database striped on two segments
;  with two stripes of 50 meg and one of 100 meg.
;
;  You can always add more segments to the configuration, but once
;  added, do not change the setup.
;
[Striping]
Segment1 = 100M, db-seg1-1.db, db-seg1-2.db
Segment2 = 100M, db-seg2-1.db
;...
;[TempStriping]
;Segment1			= 100M, db-seg1-1.db, db-seg1-2.db
;Segment2			= 100M, db-seg2-1.db
;...
;[Ucms]
;UcmPath			= <path>
;Ucm1				= <file>
;Ucm2				= <file>
;...

[Zero Config]
ServerName = virtuoso (STRIX)
;ServerDSN			= ZDSN
;SSLServerName			=
;SSLServerDSN			=

[Mono]
;MONO_TRACE			= Off
;MONO_PATH			= <path_here>
;MONO_ROOT			= <path_here>
;MONO_CFG_DIR			= <path_here>
;virtclr.dll			=

[URIQA]
DynamicLocal = 0
DefaultHost  = localhost:8890

[SPARQL]
;ExternalQuerySource		= 1
;ExternalXsltSource 		= 1
;DefaultGraph      		= http://localhost:8890/dataspace
;ImmutableGraphs    		= http://localhost:8890/dataspace
ResultSetMaxRows           = 10000
MaxQueryCostEstimationTime = 3600	; in seconds
MaxQueryExecutionTime      = 3600	; in seconds
DefaultQuery               = select distinct ?g where {graph ?g {?s ?p ?o}}
DeferInferenceRulesInit    = 0	; controls inference rules loading
;PingService       		= http://rpc.pingthesemanticweb.com/

[Plugins]
LoadPath = /data/virtuoso/lib/virtuoso/hosting
Load1    = plain, wikiv
Load2    = plain, mediawiki
Load3    = plain, creolewiki
;Load4			= plain, im
;Load5		= plain, wbxml2
;Load6			= attach, libphp5.so
;Load7			= Hosting, hosting_php.so
;Load8		= plain, proj4
;Load9			= plain, geos
Load10   = plain, shapefileio
;Load11			= plain, hslookup
;Load12		= Hosting,hosting_perl.so
;Load13		= Hosting,hosting_python.so
;Load14		= Hosting,hosting_ruby.so
;Load15				= msdtc,msdtc_sample

**Comment by HughWilliams** [comment]
@ebremer Those messages can generally be ignored as they are more warnings of inevitable  locks occurring when the server is bulk loading under heavy load and platform utilisation.

The key is what sort of load rates are being achieved which can be done by installing and running the [LDMeter](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksGuideLDMeterUtility) scripts which enable the monitoring of the triple loads roads over the duration of the load. 

The `status('');` command should also be running to ensure the server is not running out of buffers. You mentioned SATA drives were being used for the dataset file storage, is this also what is being used for the Virtuoso database file  (/data/virtuoso/var/lib/virtuoso/db/virtuoso.db) ? As generally we recommend fast storage like SSD or optical drives for the database storage for best performance. As if you run out of buffers and the database has to start swapping to disk this will significantly degrade performance using SATA type drives that do not have fast disk access times.

If the 800K files have a max size of about 500 triples , then that equates to about 500 million triples which a 128GB RAM system should be able to support quite readily with Virtuoso 7.

**Comment by ebremer** [comment]
It looks then as if everything is going as fast as it can.  Unfortunately, the new SSD array has not arrived yet, so, I'm stuck with SATA at the moment.  
status(''); gives me:
Database Status:
  File size 782237696, 95488 pages, 28156 free.
  10880000 buffers, 67215 used, 65214 dirty 0 wired down, repl age 0 0 w. io 102 w/crsr.
  Disk Usage: 68 reads avg 0 msec, 0% r 0% w last  41 s, 2500 writes flush      59.23 MB/s,
    0 read ahead, batch = 0.  Autocompact 291 in 219 out, 24% saved.
Gate:  0 2nd in reads, 0 gate write waits, 0 in while read 0 busy scrap.
Log = /data/virtuoso/var/lib/virtuoso/db/virtuoso.trx, 138737244 bytes
2052 pages have been changed since last backup (in checkpoint state)
Current backup timestamp: 0x0000-0x00-0x00
Last backup date: unknown
Clients: 11 connects, max 11 concurrent
RPC: 40 calls, 11 pending, 11 max until now, 0 queued, 0 burst reads (0%), 0 second 44M large, 79M max
Checkpoint Remap 38 pages, 0 mapped back. 4 s atomic time.
    DB master 95488 total 28156 free 38 remap 10 mapped back
   temp  256 total 251 free

Lock Status: 0 deadlocks of which 0 2r1w, 13325 waits,
   Currently 11 threads running 9 threads waiting 0 threads in vdb.
Pending:

23 Rows. -- 222 msec.

**Comment by imitko** [comment]
Please use `FDsPerFile` INI files setting, for better performance can be 4. Also If you have more than one HDD can use striping for Database files.

**Comment by ebremer** [comment]
@imitko I saw this setting at http://docs.openlinksw.com/virtuoso/dbadm/.  "This parameter only effects databases that use striping." - which I am not.  Will the 4 value still be of benefit?

**Comment by ebremer** [comment]
@imitko  I made the change to FDsPerFile =4 and it made a substantial difference!  I was doing about 3,200 triples/sec before and now the performance has increased to 159,113 triples/sec.  Same machine, 22 loaders.
