### ISSUE TITLE
configure: error: OpenSSL version 1.1.0 or greater is currently not supported

### ISSUE THREAD

**Issue by leilafedd** [openlink/virtuoso-opensource#920]
Hello,
i am trying to install virtuoso 7.2.5.1 from github source (since no debian packages are available for version 7).  for that i follow you [guide for Building from Upstream Source](http://vos.openlinksw.com/owiki/wiki/VOS/VOSDebianNotes).
when running `./configure` ..., I get this error message:
`configure: error: OpenSSL version 1.1.0 or greater is currently not supported`
based on [README.OpenSSL](https://github.com/openlink/virtuoso-opensource/blob/fix/TallTed-20190723-README.OpenSSL.md/README.OpenSSL.md): "Virtuoso can be compiled against OpenSSL 0.9.8i up to OpenSSL v1.0.2p", so i installed OpenSSL v1.0.2p following this [guide](https://www.howtoforge.com/tutorial/how-to-install-openssl-from-source-on-linux/).
(Since `sudo apt-get install libssl1.0-dev` says that the package is not available).

checking the actual installed version gives `openssl version > OpenSSL 1.0.2p  14 Aug 2018`

But i tried again and i still face the same error `configure: error: OpenSSL version 1.1.0 or greater is currently not supported`

Could you please help me figuring this out, i really do not know what to do next? (using packages was much simple, but only available for old version)

Thank you very much

**Comment by leilafedd** [comment]
Hi,
i reinstalled OpenSSL v1.0.2p and now i get this error : 
`checking usability of the OpenSSL header files and library in /usr... configure: error: bad. Check config.log for details` 

Could you please help me figuring this out (i try to install on Debian GNU/Linux 10)?

**Comment by leilafedd** [comment]
Hello,
running `sudo apt-get install libssl-dev` also does not help (already installed)
config.log error snippet:

***********************************************************
configure:13614: checking usability of the OpenSSL header files and library in /usr
configure:13666: gcc -o conftest -g -O2  -DOPENSSL_NO_KRB5   conftest.c  -lssl -lcrypto >&5
In file included from /usr/include/openssl/evp.h:66,
                 from /usr/include/openssl/x509.h:73,
                 from conftest.c:147:
/usr/include/x86_64-linux-gnu/openssl/opensslconf.h:20:3: error: #error OPENSSL_ALGORITHM_DEFINES no longer supported
 #error OPENSSL_ALGORITHM_DEFINES no longer supported
   ^~~~~
conftest.c: In function 'main':
conftest.c:174:23: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
     ssl_server_method = SSLv23_client_method();
                       ^
configure:13666: $? = 1
configure: program exited with status 1
configure: failed program was:

***********************************************************
Could you please help me figuring this out ?

**Comment by HughWilliams** [comment]
Please refer to issue #915 which details how to build Virtuoso with OpenSSL 1.1+  or other versions ...

**Comment by leilafedd** [comment]
I switched to `OpenSSL 1.1.1c` , cloned the git repo : `git clone https://github.com/openlink/virtuoso-opensource.git` and followed the steps in issue #915 . 
It has worked !
Thank you for your support .
