### ISSUE TITLE
Virtuoso crashes on startup when configuring for 67% usage on 1TB RAM server

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#923]
When adjusting  `NumberOfBuffers` (2/3 of System RAM) and `MaxDirtyBuffers` (3/4 of `NumberOfBuffers`) and using 8192 bytes per buffer, a new `virtuoso` startup will crash out before completing startup.  Adjusting to 50% instead of 67% worked.  The server is dedicated to Virtuoso

* Version 07.20.3229-pthreads for Linux as of May 26 2020  
* Azure Ubuntu 18
* 1TB RAM, 64 cores

**Comment by ebremer** [comment]
Crashed after a few minutes when trying to load 7 billion triples with 10 loaders

**Comment by HughWilliams** [comment]
@ebremer: Can you please try the suggestion in [git issue #742](https://github.com/openlink/virtuoso-opensource/issues/742#issuecomment-528871495) to work around this crash? It sounds as if you may be hitting the same problem ...

**Comment by ebremer** [comment]
Seems to be the same problem as I can start it up with 67% of the 1TB for buffers.  Thanks @HughWilliams !

**Comment by HughWilliams** [comment]
Glad to hear that resolved the problem, we are seeking to make a permanent fix of this issue ...

**Comment by ebremer** [comment]
I was doing a fresh install on a new server:

Azure Ubuntu 24
1TB RAM, 64 cores

I re-tested.  This same issue exists.
```
OpenLink Virtuoso Interactive SQL (Virtuoso)
Version 07.20.3240 as of Apr 22 2025
Type HELP; for help and EXIT; to exit.
Connected to OpenLink Virtuoso
Driver: 07.20.3240 OpenLink Virtuoso ODBC Driver
```
Good news, fix https://github.com/openlink/virtuoso-opensource/issues/742#issuecomment-528871495 still works :-)

**Comment by HughWilliams** [comment]
Yes, a solution of this problem is still to be devised, with the workaround in https://github.com/openlink/virtuoso-opensource/issues/742#issuecomment-528871495 still having to be used at this point. I shall nudge development regarding to schedule to revisit and devise a fix for this.
