### ISSUE TITLE
build freezing at VAD Sticker vad_fs.xml creation... VAD Sticker vad_dav.xml creation...

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#930]
server -  64 cores.  1TB RAM
Ubuntu 20 all updates

fresh clone of `develop/7` as of today

everything smooth until:
```
VAD Sticker vad_fs.xml creation...
VAD Sticker vad_dav.xml creation...
```
it's been hanging there for 20 minutes.....

**Comment by timhaynesopenlink** [comment]
Hi
By far the most common reason for this is another virtuoso process running
somewhere. Kill it and redo the build.

HTH,

~Tim

**Comment by ebremer** [comment]
You were correct.  Thank you!
