### ISSUE TITLE
import owl into virtuoso openlink universal server

### ISSUE THREAD

**Issue by akouvivien** [openlink/virtuoso-opensource#938]
How to import an owl ontology into virtuoso openlink universal server 7.2

**Comment by TallTed** [comment]
The most common method is to use the [Bulk Loader](http://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader).

If that doesn't serve your purpose, please start a thread on our Community Forum to get assistance.  Issues here on Github are best confined to bug reports and the like.

Please do let us know if the Bulk Loader is sufficient to resolve your question.

**Comment by openlink** [comment]
You can either use the [Bulk Loader](http://vos.openlinksw.com/owiki/wiki/VOS/VirtBulkRDFLoader) or the [`RDF_LOAD_RDFXML()`](http://docs.openlinksw.com/virtuoso/fn_rdf_load_rdfxml/) function.
