### ISSUE TITLE
Cannot make develop/6

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#94]
Even when I apply the fix mentioned here https://github.com/openlink/virtuoso-opensource/issues/91 I still cannot make develop/6 (9c09d6465c363ad69121ac7f4a7896222192d9cb)

<pre><code>uname_const_decl.c: In function 'uname_const_decl_init':
uname_const_decl.c:249:6: error: 'uname_bif_c_sp_contains' undeclared (first use
uname_const_decl.c:249:6: note: each undeclared identifier is reported only once
uname_const_decl.c:250:6: error: 'uname_bif_c_sp_intersects' undeclared (first u
make[3]: *** [libwi_la-uname_const_decl.lo] Error 1
</code></pre>

**Comment by HughWilliams** [comment]
I have been able to recreate as well building from the develop/6 archive and development  are aware of an preparing a fix for it ...

**Comment by openlink** [comment]
This is fixed in the latest develop/6 branch
