### ISSUE TITLE
New Release or appropriate Commit

### ISSUE THREAD

**Issue by GrazingScientist** [openlink/virtuoso-opensource#947]
Would it be possible to make either a new stable release for this repo or at least mention a commit in the documentation that would provide a "stable" virtuoso.

Would be greatly appreciated. Thanks a lot! :)

**Comment by GrazingScientist** [comment]
Can someone from the team find the time to make a recommondation on this? Thanks! :)

**Comment by AlexTo** [comment]
Same question, this seems to be a quite active project judging from the number and timeline of commits, yet there is no stable release after 3 years :D 
If possible could someone advise on when do we expect a new release?
Thanks

**Comment by openlink** [comment]
We have scheduled a new `stable release` within the next 2 weeks.

Note that the Virtuoso Open Source release gets most of its patches directly from our commercial versions. This means that the bulk of the code has been tested extensively in-house; on our public endpoints such as our Corporate web sites, URIBurner, DBpedia, etc.; as well as by our commercial and open source partners before it gets merged into the `virtuoso-opensource` archive.

The benefit for our open source community is that most of the time our `develop` branch is already pretty stable.

**Comment by openlink** [comment]
We have just released a new version of Virtuoso v7.2.6 on the stable/7 branch.

https://github.com/openlink/virtuoso-opensource/releases/tag/v7.2.6
