### ISSUE TITLE
Invalid Token - Virtuoso 7.2 + OAuth

### ISSUE THREAD

**Issue by ThomasThelen** [openlink/virtuoso-opensource#952]
While following [this](http://vos.openlinksw.com/owiki/wiki/VOS/VirtOAuthSPARQL) guide from OpenLink, I ran across some trouble authenticating a query. I don't believe I've done anything incorrect here, so I'm suspect that the guide is incorrect or that there may be a bug somewhere. Any hints are appreciated.

### To Reproduce
To reproduce this, use the attached Dockerfile, which copies the included `ods_framework_dav.vad` into Virtuoso's dav folder.
Alternatively, install Virtuoso 7.2.0, download [ods_framework_dav.vad](http://download3.openlinksw.com/uda/vad-vos-packages/7.2/ods_framework_dav.vad), and place it somewhere that Virtuoso has access to. Then, install it.

For reference, here are my installed packages

<img width="1516" alt="Screen Shot 2021-03-22 at 4 49 17 PM" src="https://user-images.githubusercontent.com/9289652/112072501-30992a00-8b2f-11eb-945d-59d47d5b4f4e.png">

Then, follow the guide linked at the top starting at step 2.

Create the user account, which should look like,

<img width="1233" alt="Screen Shot 2021-03-22 at 4 48 50 PM" src="https://user-images.githubusercontent.com/9289652/112072541-4e668f00-8b2f-11eb-90c5-88ae1c2d05bf.png">

Then, generate an OAuth token

<img width="1680" alt="Screen Shot 2021-03-22 at 4 55 43 PM" src="https://user-images.githubusercontent.com/9289652/112072660-8b328600-8b2f-11eb-8eb3-6ff42bd03872.png">

Proceed to run the example query,

<img width="1680" alt="Screen Shot 2021-03-22 at 4 57 13 PM" src="https://user-images.githubusercontent.com/9289652/112072716-ad2c0880-8b2f-11eb-88d8-f36f34e9e1bc.png">

But then run across the following error,

<img width="1680" alt="Screen Shot 2021-03-22 at 4 46 16 PM" src="https://user-images.githubusercontent.com/9289652/112072747-bae18e00-8b2f-11eb-8672-12af2dc3f89b.png">

[virtuoso.zip](https://github.com/openlink/virtuoso-opensource/files/6185935/virtuoso.zip)

**Comment by HughWilliams** [comment]
You appear to be using the "tenforce" docker container, I would recommend using the OpenLink official [Virtuoso Open Source docker container](https://hub.docker.com/r/openlink/virtuoso-opensource-7/) image, being the latest offering we would seek to support, etc.

**Comment by ThomasThelen** [comment]
Great point. I've remade the docker deployment using the `openlink/virtuoso-opensource-7` and refactored the COPY directive to match the plugin directory from the openlink distribution and attached it to this comment. I was able to reproduce the behavior described in my initial comment.

I can see that the vad installed correctly from the `virtuoso.log` file,

```
15:29:55 HTTP/WebDAV server online at 8890
15:29:55 Server online at 1111 (pid 1)
15:30:40 PL LOG: Installing ODS Framework version 1.89.47/2018-12-10 20:23 (DAV)
15:30:40 Checkpoint started
```

[virtuoso.zip](https://github.com/openlink/virtuoso-opensource/files/6190826/virtuoso.zip)

**Comment by HughWilliams** [comment]
Testing, this problem also occurs with the latest Virtuoso 7 Open Source [git develop/7](https://github.com/openlink/virtuoso-opensource/tree/develop/7) branch. The OAuth functionality moved to the new [Virtuoso Authentication Layer](http://docs.openlinksw.com/valdocs/index.html)(VAL) some time ago. VAL is a Commercial Edition only feature, and has not really been maintained in Open Source. Thus if you are seeking to use OAuth and other such authentication protocols, you should consider obtaining a Commercial license ...

**Comment by kidehen** [comment]
>> Great point. I've remade the docker deployment using the `openlink/virtuoso-opensource-7` and refactored the COPY directive to match the plugin directory from the openlink distribution and attached it to this comment. I was able to reproduce the behavior described in my initial comment.
>> 
>> I can see that the vad installed correctly from the `virtuoso.log` file,
>> 
>> ```
>> 15:29:55 HTTP/WebDAV server online at 8890
>> 15:29:55 Server online at 1111 (pid 1)
>> 15:30:40 PL LOG: Installing ODS Framework version 1.89.47/2018-12-10 20:23 (DAV)
>> 15:30:40 Checkpoint started
>> ```
>> 
>> [virtuoso.zip](https://github.com/openlink/virtuoso-opensource/files/6190826/virtuoso.zip)


> Testing, this problem also occurs with the latest Virtuoso 7 Open Source [git develop/7](https://github.com/openlink/virtuoso-opensource/tree/develop/7) branch. The OAuth functionality moved to the new [Virtuoso Authentication Layer](http://docs.openlinksw.com/valdocs/index.html)(VAL) some time ago. VAL is a Commercial Edition only feature, and has not really been maintained in Open Source. Thus if you are seeking to use OAuth and other such authentication protocols, you should consider obtaining a Commercial license ...

Clarification:

The issue here is prioritization. We've put a lot of effort into a commercial edition Virtuoso Authentication Layer (VAL) which virtualizes authentication across a cocktail of protocols. 

We are happy for community members to contribute fixes to VOS while we work through our internal priorities -- which may also include revisiting this issue.

**Comment by ThomasThelen** [comment]
Awesome I appreciate the help here! I'm not sure what the state of #814 is; for anyone else that wishes to do authentication on VOS and runs across this issue- I did some testing and found that the [SQL Account digest authentication](http://vos.openlinksw.com/owiki/wiki/VOS/VirtSPARQLProtectSQLDigestAuthentication) is functioning as expected.

**Comment by openlink** [comment]
The issue with OAuth tokens has been resolved in the latest `ods_framework.vad` we just released as part of v7.2.6

https://github.com/openlink/virtuoso-opensource/releases/tag/v7.2.6

I pushed a new Docker image to https://hub.docker.com/repository/docker/openlink/virtuoso-opensource-7

**Comment by TallTed** [comment]
Hi, @ThomasThelen -- It would be much appreciated if you have the opportunity and can take the time to test the new build, and confirm whether the OAuth issue is resolved thereby for you.

**Comment by ThomasThelen** [comment]
I appreciate the time put into looking at this issue! I retested with the latest docker image, using the following docker command.
`docker run -p 8890:8890 -p 1111:1111 -e DBA_PASSWORD=dba openlink/virtuoso-opensource-7:7.2.6-r10-g5a27710-alpine`.

I installed the VAD with the properties shown below, which is also attached in the zip file in my initial message.

<img width="1680" alt="Screen Shot 2021-06-23 at 9 55 45 AM" src="https://user-images.githubusercontent.com/9289652/123137979-6b01b400-d409-11eb-9ae9-22a865213e88.png">


I was sure to update all of the packages, note that they're all the latest version.

<img width="1680" alt="Screen Shot 2021-06-23 at 10 08 37 AM" src="https://user-images.githubusercontent.com/9289652/123139480-1b23ec80-d40b-11eb-9405-1d23101c35d7.png">

The account was created with the following properties,

<img width="1144" alt="Screen Shot 2021-06-23 at 9 54 43 AM" src="https://user-images.githubusercontent.com/9289652/123138787-49ed9300-d40a-11eb-8340-eacd738cd815.png">

I created an oauth key without issue,
<img width="935" alt="Screen Shot 2021-06-23 at 9 56 08 AM" src="https://user-images.githubusercontent.com/9289652/123138847-5c67cc80-d40a-11eb-9c2e-e860c9c4943b.png">

But when attempting to run my SELECT, I received the same invalid token
<img width="1680" alt="Screen Shot 2021-06-23 at 9 56 23 AM" src="https://user-images.githubusercontent.com/9289652/123138843-5bcf3600-d40a-11eb-9632-1abc59a590da.png">

I _also_ tested with `openlink/virtuoso-opensource-7:latest` and ran into the same behaviour.


I'm assuming that it's an issue with the `ods_framework.vad` that I'm using; according to the conductor I'm using the latest version. But if someone can point me to a direct link to the vad file I can retest it.

**Comment by TallTed** [comment]
@ThomasThelen — Please note that the "New Version" column is populated from the contents of the Virtuoso-local VADs directory as compared with the "Installed Version" column, which is populated from the VADs that have been installed in the active DB.  The "Not available" value does not indicate that you are running the latest version available for pre-built download nor build-from-source; only that a newer version is "not available" *locally*, i.e., in the active `/vads/` directory, typically parallel to the Virtuoso binary.

I suggest that you download a [fresh set of VAD archives for your VOS 7.2 binary](http://download3.openlinksw.com/index.html?prefix=uda/vad-vos-packages/7.2/) as we uploaded yesterday, which includes an updated build of the `ods_framework.vad` — `1.89.49/ 2021-06-22` — which you can also still get from the same download link as you used originally — which no longer delivers the build you now have installed — or take a closer look at what the updated docker image contains before you downgrade its installed VAD(s).

**Comment by ThomasThelen** [comment]
Thanks @TallTed that was it! Screenshot below of the response from a successful SPARQL query run through the OAUTH end point, using the instructions in the documentation with the fresh set of VADS. Thanks again for spending time on this issue!

<img width="1680" alt="Screen Shot 2021-06-23 at 12 41 29 PM" src="https://user-images.githubusercontent.com/9289652/123158283-701e2d80-d420-11eb-886d-024da7515a64.png">
