### ISSUE TITLE
select distinct ?g where {graph ?g {?s ?p ?o}}

### ISSUE THREAD

**Issue by ebremer** [openlink/virtuoso-opensource#953]
The query:
`select distinct ?g where {graph ?g {?s ?p ?o}}`
on a triple store with about 600GB RAM (64 cores/ubuntu 18) and a 15 billion triple store with about two dozen graphs never completes >24 hours and still running.  However, this query:

`select distinct ?g count(*) where {graph ?g {?s ?p ?o}} group by ?g order by ?g`

runs in about 10 minutes

`select count(*) where {graph ?g {?s ?p ?o}}`  -->> runs in 1 minutes

Running develop branch:
```
09:32:06 OpenLink Virtuoso Universal Server
09:32:06 Version 07.20.3231-pthreads for Linux as of Mar 22 2021
09:32:06 uses OpenSSL 1.0.2n  7 Dec 2017
```

**Comment by TallTed** [comment]
This appears to pick up from #924.

Please confirm that I'm correctly understanding your first paragraph, that you're testing on a single Virtuoso instance holding about 15 billion triples in about 24 named graphs, on a machine with about 600 GB RAM and 64 processor cores running Ubuntu 18?

Please provide the values of `NumberOfBuffers` and `MaxDirtyBuffers` from your active `virtuoso.ini`, along with output of the following Linux command: 
```
/sbin/sysctl vm.swappiness
```

**Comment by ebremer** [comment]
Correct.  Actual system RAM is 688GB.

NumberOfBuffers            = 56607998
MaxDirtyBuffers            = 42455999

vm.swappiness = 60

The system is dedicated to the Virtuoso instance.

**Comment by ebremer** [comment]
changed swappiness to 10.  Re-testing now.

**Comment by ebremer** [comment]
It didn't hurt the two quicker queries but the `select distinct ?g where {graph ?g {?s ?p ?o}}` is still running.

**Comment by TallTed** [comment]
I am wondering whether something odd happened during your data load and/or index building, as the default indexes should lead to this query running quite quickly.

Checking for, and recovering from, the most common index issues is discussed in [How to Fix Broken Index on RDF QUAD Store](http://vos.openlinksw.com/owiki/wiki/VOS/VirtFixBrokenQuadStoreIndex).

**Comment by jakubklimek** [comment]
@TallTed I am experiencing this issue on all my Virtuoso instances as well. They are considerably smaller, so the query eventually finishes, but it runs for a long time, utilizing the server to its maximum, as if no index is being utilized and all the quads are being scanned. Therefore, this is probably not a data load issue.

**Comment by ebremer** [comment]
@TallTed I'm doing the checks as per what you sent me.  The first two match:
```
select count (*) from rdf_quad table option (index rdf_quad); 
select count (*) from rdf_quad table option (index rdf_quad_pogs)
```
but the next one is hanging.  I'm watching to see if it finishes anytime soon.  @jakubklimek my issue may be data, but, we'll see.

**Comment by TallTed** [comment]
@jakubklimek - You may be right. That said, the sanity checks described in the [article linked above](http://vos.openlinksw.com/owiki/wiki/VOS/VirtFixBrokenQuadStoreIndex) are worthwhile to run periodically on any DB to confirm that the indexes and the overall DB are healthy -- and getting that confirmation about your smaller instances will help eliminate this as a possibility for you, if not for @ebremer.

**Comment by HughWilliams** [comment]
@ebremer: Can you try with the iSQL query `SPARQL SELECT DISTINCT ?g  WHERE  {  GRAPH ?g {?s a ?t} }`? This is another form of SPARQL query for [listing all graph in Virtuoso](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksGuideAllGraphs), and should run a lot faster.  The `select distinct ?g where {graph ?g {?s ?p ?o}}` is known to take a long time as I have seen it before, as it actually calls the `DB.DBA.SPARQL_SELECT_KNOWN_GRAPHS();` function referenced in the "list all graphs" document, under the covers, and seems to have become suboptimal over time. You can see this if you use the `explain()` function to obtain a [query compilation plan](https://github.com/openlink/virtuoso-opensource/issues/953).

**Comment by TallTed** [comment]
Just for quick comparison... I ran the three queries on [our live VOS Demo instance](https://vos.demo.openlinksw.com/sparql), and they all returned virtually instantly. This instance is a little behind the code that @ebremer is running, and certainly doesn't hold as much data, but does provide a touchpoint.

1. [`select count(*) where {graph ?g {?s ?p ?o}}`](https://vos.demo.openlinksw.com/sparql?default-graph-uri=&query=select+count%28*%29+where+%7Bgraph+%3Fg+%7B%3Fs+%3Fp+%3Fo%7D%7D&format=text%2Fhtml&timeout=30000000&debug=on&run=+Run+Query+) — `0m0.487s`
2. [`select distinct ?g count(*) where {graph ?g {?s ?p ?o}} group by ?g order by ?g`](https://vos.demo.openlinksw.com/sparql?default-graph-uri=&query=select+distinct+%3Fg+count%28*%29+where+%7Bgraph+%3Fg+%7B%3Fs+%3Fp+%3Fo%7D%7D+group+by+%3Fg+order+by+%3Fg%0D%0A%0D%0A&format=text%2Fhtml&timeout=30000000&debug=on&run=+Run+Query+) — `0m0.717s`
3. [`select distinct ?g where {graph ?g {?s ?p ?o}}`](https://vos.demo.openlinksw.com/sparql?default-graph-uri=&query=select+distinct+%3Fg+where+%7Bgraph+%3Fg+%7B%3Fs+%3Fp+%3Fo%7D%7D%0D%0A&format=text%2Fhtml&timeout=30000000&debug=on&run=+Run+Query+) — `0m2.147s`

(I ran each query through `time curl -LI {url}`; the times above are the `real` durations reported.)

**Comment by ebremer** [comment]
@HughWilliams @TallTed willl try after I finish "How to Fix Broken Index on RDF QUAD Store".

**Comment by ebremer** [comment]
@HughWilliams @TallTed 
`select count (*) from rdf_quad table option (index rdf_quad);`
`select count (*) from rdf_quad table option (index rdf_quad_pogs);`
each returned 15,386,439,517 after 40.7 seconds.  
However, it's hung on `select count (*) from rdf_quad table option (index rdf_quad_sp);`

**Comment by TallTed** [comment]
@ebremer - That definitely sounds like a corruption of some sort. I would try the other two `select count` queries from that block in the article, to see both whether they succeed or hang, and whether their counts are the same as the first two queries.

The database integrity check comes next, and then backup-and-restore and/or index rebuild(s), depending on these results.

**Comment by ebremer** [comment]
I went with a
```
drop index rdf_quad_sp;
CREATE DISTINCT NO PRIMARY KEY REF COLUMN INDEX RDF_QUAD_SP  ON DB.DBA.RDF_QUAD (S, P) PARTITION (S int (0hexffff00));
```
it will take a while.  After it finishes, I will test and then try them all again.

**Comment by ebremer** [comment]
@TallTed @HughWilliams the database rebuild didn't work.  I was able to use dump_one_graph and export all of my data.  From there I started fresh and was able to restore the data and things appear to be working well.  Thank you for your help!
