### ISSUE TITLE
Inference with Virtuoso

### ISSUE THREAD

**Issue by nleguillarme** [openlink/virtuoso-opensource#967]
Hi, I am testing the inference capabilities of Virtuoso.

I have an OWL ontology which defines some concepts using class equivalency axioms, for instance :
```
equivalentClass(Bacterivore, eats some (Bacteria or Archea)
```

I load this ontology in Virtuoso with its own named graph IRI, let's say 
```
http://localhost:8890/stwo
```
and create a new rule set using 
```
rdfs_rule_set("http://localhost:8890/stwo", "http://localhost:8890/stwo")
```

Then, I have a `.nq` file containing a minimal example
```
_:4048 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/CARO_0001010>.
_:4048 <http://purl.obolibrary.org/obo/BCO_0000087> <http://purl.obolibrary.org/obo/NCBITaxon_30073>.
_:4048 <http://purl.obolibrary.org/obo/RO_0002470> _:4049.
_:4049 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/NCBITaxon_2>.
```

In particular, `obo:NCBITaxon_2 = Bacteria` and `obo:RO_0002470 = eats`.

I load these triples in the default graph `http://localhost:8890/DAV`
and I execute a query with inference enabled, using 
```
define input:inference "http://localhost:8890/stwo"
```

Although some `subClassOf` relationships are correctly inferred, the fact that the node `_:4048` is a `bacterivore` is not inferred.

Is Virtuoso capable of handling this type of inference? Am I doing something wrong?

Edit: I read from [that tutorial](https://bigdataieee.org/BigData2019/files/Tutorial6.pdf) that Virtuoso only handles RDFS++, I guess this explains why the 'is a bacterivore' triple is not inferred.

**Comment by TallTed** [comment]
I do not believe the author of [that tutorial](https://bigdataieee.org/BigData2019/files/Tutorial6.pdf) consulted with us when producing that document.  At a quick scan, some of the specifics found therein don't seem correct to me.

To your specific question -- it is correct that custom reasoning of this sort is not supported in VOS, Virtuoso Open Source Edition.  VOS supports a limited subset of OWL, as [discussed here](https://community.openlinksw.com/t/what-flavors-of-reasoning-are-supported-in-vos/2488/3?u=tallted).

For such custom reasoning, you will need VEE, the Enterprise (a/k/a Commercial, a/k/a Closed Source) Edition.  Licenses for VEE deployment currently [start at $499.99](https://virtuoso.openlinksw.com/offers) -- and you can [get a FREE 30-day trial license](https://shop.openlinksw.com/license_generator/) to start your testing immediately.  (Refreshed trial licenses may be made available if you provide justification to your sales rep.)

**Comment by nleguillarme** [comment]
Hi @TallTed, thank you for this clarification.

**Comment by TallTed** [comment]
I'll close this issue now. Bugs, patches, and the like are fine to raise or submit here. Questions about Virtuoso usage, features, etc., are probably better raised on [our Community Forum](http://community.openlinksw.com/).
