### ISSUE TITLE
Problems with FCT after update to 7.2.6

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#968]
After update to 7.2.6 (621ef0713bb2e674e5bf599d1a05ee3bcefa3338) I am unable to use FCT.
- Accessing https://dev.nkod.opendata.cz/fct/ times out
- using [/describe](https://dev.nkod.opendata.cz/describe/?uri=https://data.gov.cz/zdroj/datové-sady/45249130/CENIA/c8fafdf59046690fc5d1f1508402dfc3) gives `Error 42000 SR186:SECURITY: No permission to execute procedure DB.DBA.fct_cctr with user ID 107, group ID 107`

**Comment by openlink** [comment]
I will check

**Comment by openlink** [comment]
As a workaround, run the following command via isql:

```
grant execute on fct_cctr to SPARQL_SELECT;
```

**Comment by openlink** [comment]
make a hotfix patch, so stable/7 and develop/7 have this patch
