### ISSUE TITLE
Allow UPDATE in ```openlink/virtuoso-opensource-7```

### ISSUE THREAD

**Issue by ccolonna** [openlink/virtuoso-opensource#970]
How to allow UPDATE in virtuoso docker image?

 Trying to run:

```CREATE SILENT GRAPH <example:graph_1>```

I get:

```Virtuoso 42000 Error SR186:SECURITY: No permission to execute procedure DB.DBA.SPARUL_CREATE with user ID 107, group ID 107```

**Comment by TallTed** [comment]
First thing, please note that all of this applies to all Virtuoso instances; none of it is specific to the Docker image, nor to VOS (Virtuoso Open Source).  Also, none of it is new.

Assuming you're trying to do this through the `/sparql` endpoint, the short, _"just make it work!"_ answer is to execute the following through iSQL or similar, while logged in as `dba` or other super-privileged SQL user --
```
grant execute on DB.DBA.SPARUL_CREATE to SPARQL
```

Note that this and similar `grant` commands may pose security risks, as they may open portions of the Virtuoso instance to actions by anonymous remote users.  The articles below are likely to be helpful to keep things secure:

* [Safeguarding your Virtuoso-hosted SPARQL Endpoint](http://vos.openlinksw.com/owiki/wiki/VOS/VirtSPARQLEndpointProtection)
* [Securing your SPARQL Endpoint via OAuth](http://vos.openlinksw.com/owiki/wiki/VOS/VirtOAuthSPARQL)
* [Securing your SPARQL Endpoint via WebID](http://vos.openlinksw.com/owiki/wiki/VOS/VirtSPARQLSecurityWebID)

**Comment by ccolonna** [comment]
Thank you @TallTed for fast reply it worked like a charm:

For anyone else precise syntax is:

```
grant execute on "DB"."DBA"."SPARUL_CREATE" to "SPARQL" ;
```

isn't there any option i can grant full r/w automatic permission to any user with docker environment variables or param? I'm using [https://hub.docker.com/r/openlink/virtuoso-opensource-7](virtuoso_opensource_7) 

> Note that this and similar `grant` commands may pose security risks

Thanks for warning, this is for a local setup not exposed to the open world!

**Comment by TallTed** [comment]
I don't know enough about docker to answer this question usefully.

Possibly @pkleef @timhaynesopenlink @openlink @HughWilliams can assist?

**Comment by HughWilliams** [comment]
There are no docker environment variables that can be set to control user access to the SPARQL endpoint or other such resources. Thus you would need to login via the Virtuoso Conductor or "isql" to set or grant such permissions to users if required.

**Comment by ccolonna** [comment]
Thank you @HughWilliams , you clarified my doubts. You can close the issue if you want!
