### ISSUE TITLE
Issues with SPARQL variables containing unicode characters

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#973]
When I run a SPARQL SELECT query in Virtuoso's SPARQL endpoint web service, where the result table's column names are the variable names, and those variable names contain unicode characters (common e.g. in Czechia), there are various issues.
Tested e.g. on https://dbpedia.org/sparql:
```sparql
select distinct ?ažý where {?ažý a ?Concept}
LIMIT 1
```
results in the column being named `aÅ¾Ã½` instead of `ažý`.

When the variable name starts with a unicode character like
```sparql
select distinct ?žčřžý where {?žčřžý a ?Concept}
LIMIT 1
```

I get
```
Virtuoso 37000 Error SP030: SPARQL compiler, line 0: Bad character 'Å' (0xc5) in SPARQL expression at 'Å'

SPARQL query:
#output-format:text/html
define sql:signal-unconnected-variables 1
define sql:signal-void-variables 1
define input:default-graph-uri <http://dbpedia.org>
select distinct ?Å¾ÄÅ™Å¾Ã½ where {?Å¾ÄÅ™Å¾Ã½ a ?Concept}
LIMIT 1
```

**Comment by pkleef** [comment]
Example: https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=select%20distinct%20%3F%C5%BE%C4%8D%C5%99%C5%BE%C3%BD%20where%20%7B%3F%C5%BE%C4%8D%C5%99%C5%BE%C3%BD%20a%20%3FConcept%7D%0ALIMIT%201

**Comment by TallTed** [comment]
The above is an [example where the variable starts with a Unicode character](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=select%20distinct%20%3F%C5%BE%C4%8D%C5%99%C5%BE%C3%BD%20where%20%7B%3F%C5%BE%C4%8D%C5%99%C5%BE%C3%BD%20a%20%3FConcept%7D%0ALIMIT%201).

This is an [example where the variable starts with an ASCII character and has a couple of following Unicode characters](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&qtxt=select+distinct+%3Fa%C5%BE%C3%BD+where+%7B%3Fa%C5%BE%C3%BD+a+%3FConcept%7D%0D%0ALIMIT+1%0D%0A&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on).
