### ISSUE TITLE
Wrong behaviour of SQL WHERE

### ISSUE THREAD

**Issue by galgonek** [openlink/virtuoso-opensource#974]
While working on a study comparing different approaches to query the neXtProt dataset, I have observed that Virtuoso returns wrong results in some cases.

If I create the table —

```
create table test (
    id              varchar not null,
    pos_start  integer,
    pos_end    integer,
    PRIMARY KEY(id)
);

insert into test values ('ID1', NULL, NULL);
insert into test values ('ID2', 10, 20);
```

— then the SQL query —

`select id from test where 0 < (pos_end - pos_start) and 100 > (pos_end - pos_start);`

— returns an empty result. However, `'ID2'` should be returned.

**Comment by openlink** [comment]
Our development team will review this issue and report back as soon as posible.

**Comment by TallTed** [comment]
@galgonek -- Does your closure of this issue signal that it's been resolved according to your testing of current builds?

**Comment by galgonek** [comment]
@TallTed -- Yes, I tested the current build and the issue seems to be fixed. Thank you.
