### ISSUE TITLE
Quad Storage or IRI class fails: Virtuoso 22023 Error SR008

### ISSUE THREAD

**Issue by abondoa** [openlink/virtuoso-opensource#98]
For all my IRI classes with more than one argument I get an error when querying instances of the given IRI class for an explicit IRI. The query:

```
define input:storage <http://extbi.cs.aau.dk/mappings/quad_storage/default>

prefix mrk: <http://extbi.cs.aau.dk/ontologies/agriculture#> 

select *
where {?S mrk:markkortid ?markkortid.
?S ?P ?O .
FILTER(?markkortid="191430") }
```

Leads to the following error:

```
Virtuoso 22023 Error SR008: Function sprintf needs an integer as argument 2, not an arg of type VARCHAR (182)

SPARQL query:
define sql:big-data-const 0 
#output-format:text/html
define input:storage 

prefix mrk:  

select *
where {?S mrk:markkortid ?markkortid.
?S ?P ?O .
FILTER(?markkortid="191430") }
```

The IRI class is defined as:

```
create iri class mrkmap:field_iri
"http://extbi.cs.aau.dk/data/agriculture/field#%U_%U"
    (in markkortid varchar not null, in marknr varchar) .
```

Additionally I have tried:

```
create iri class mrkmap:field_iri
"http://extbi.cs.aau.dk/data/agriculture/field#%s_%s"
    (in markkortid varchar not null, in marknr varchar) .
```

and

```
create iri class mrkmap:field_iri
"http://extbi.cs.aau.dk/data/agriculture/field#%d_%s"
    (in markkortid integer not null, in marknr varchar) .
```

but to no avail.

I have also googled around - finally ending here - without finding any help.

Any fix or help is welcome. Thanks.

**Comment by indeyets** [comment]
looks like you're using "stable" release. can you verify this with latest version from git? because I believe this bug is already fixed in develop/6 and develop/7

**Comment by abondoa** [comment]
I am using stable.

I had a lot of trouble building develop/7 on windows, so I have decided to make a work around. I will have views wrapping the tables used in the mapping. These views will contain primary keys constructed from concatenating the two attributes. This will allow me to make all the IRI classes as single argument functions, which seems to work fine.

I will write back when I know whether it works.

Thank you for your response @indeyets.

**Comment by abondoa** [comment]
The trick with using views works quite well - although not being very elegant.

We are simply concatenating the attributes which needs to be part of the IRI as follows:

```
SELECT concat(CONVERT(varchar,ansnr),'_',marknr) as id ...
```

**Comment by openlink** [comment]
This fix is part of the upcoming VOS 7 release. 

As always we will be providing prebuilt binaries for Windows 64 bit from:

http://sourceforge.net/projects/virtuoso/files/virtuoso/
