### ISSUE TITLE
Virtuoso Service disruption

### ISSUE THREAD

**Issue by Invincibled** [openlink/virtuoso-opensource#987]
Hi,
Virtuoso had a service interruption while I was importing using `RDF_loader_run ()`， The error message is as follows, There are no obvious errors in the log.
```pre
*** Error 08S01: [Virtuoso Driver]CL065: Lost connection to server
at line 0 of Top-Level:
rdf_loader_run()
```

My virtuoso.ini configuration remains the default, except for the following two configurations:
```pre
NumberOfBuffers          = 5450000
MaxDirtyBuffers          = 4000000
```

**Comment by TallTed** [comment]
Duplicate of #986
