### ISSUE TITLE
virtuoso deployment in production

### ISSUE THREAD

**Issue by Invincibled** [openlink/virtuoso-opensource#989]
Hi， 

We intend to deploy virtuoso Open Source Version in production, however, we do not know best practices.

1. If we enable striping, how many stripings should we divide into and how should we configure the size of each striping?

2. How do we configure Striping I/O queues and how are these appropriate (e.g., how many)?

3. Do temporary databases need striping? How to configure it if necessary?

4. What is the default transaction level? How to configure, is appropriate?

5. Index: How to configure. If sparQL query efficiency is low, how to determine whether there is an index problem?

looking forward to your reply , thank you.

**Comment by TallTed** [comment]
These questions may be better suited to the [OpenLink Community Forum](https://community.openlinksw.com/) for several reasons, not least being that their answers are not specific to the Open Source Edition.

That said, I will provide brief answers here.

First thing -- in the past, many filesystems limited individual file sizes to 2GB or smaller. This was a good reason to stripe a logically larger DB across multiple such physical files -- albeit at an overall performance penalty, especially when multiple stripes were on a single disk, whether or not the there were multiple filesystem volumes on that disk.  These file size limits no longer typically apply, so striping is of less value or necessity.

> 1. If we enable striping, how many stripings should we divide into and how should we configure the size of each striping?

As discussed in [the TPCC Benchmarking guidelines](http://docs.openlinksw.com/virtuoso/tpcctuningparams4users/) —

> Striping should be used if there are multiple independent disks, one stripe per physically independent volume. Each stripe should have its own I/O queue. If there is a RAID, then striping is less beneficial. Also one should have multiple handles per files, see [`FDSPerFile` in the configuration file](http://docs.openlinksw.com/virtuoso/dbadm/#ini_parameters_fdsperfile).

SSDs are strongly recommended if available in suitable sizes, especially but not only if the data will generally be loaded once, changed minimally, and read multiply.  You will find some benefit of spreading even a smaller logical DB across multiple stripes, with one stripe per SDD and with each SDD on its own controller.

As you asked and were answered previously, configured stripe file sizes only apply to their initialization; they will grow if and as needed for the loaded data, so there's not a lot of value in careful calculation of those initial sizes.

> 2. How do we configure Striping I/O queues and how are these appropriate (e.g., how many)?

As noted above, "Each stripe should have its own I/O queue."  This is typically handled simply by having one stripe and one controller per SDD.

> 3. Do temporary databases need striping? How to configure it if necessary?

As [discussed in the manual](http://docs.openlinksw.com/virtuoso/dbadm/#ini_striping) --

> Striping can be useful for the temporary objects database if large hash join temporary spaces or such are expected. This is enabled by the Striping setting in the Temp Database section of the ini file. The stripes will be declared in the TempStriping section.

The details of the configuration are just as for the main database.

> 4. What is the default transaction level? How to configure, is appropriate?

If I am understanding your question correctly, and you are actually asking about transaction _isolation,_ this is [discussed in the manual](http://docs.openlinksw.com/virtuoso/isolation/).

The default is REPEATABLE READ.  All isolation levels are supported, and are configured in the usual ways (as documented at the link above).

> 5. Index: How to configure. If sparQL query efficiency is low, how to determine whether there is an index problem?

RDF indexes are [preconfigured as 2 full and 3 partial indexes](http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning#RDF%20Index%20Scheme).  These are sufficient and performant for most usage scenarios.  "Index problems" do not typically manifest as "low SPARQL query efficiency", but as explicit errors of various kinds.  Rebuilding these indexes is [discussed here](http://vos.openlinksw.com/owiki/wiki/VOS/VirtFixBrokenQuadStoreIndex).

You can dig into [`EXPLAIN()` reports for your SPARQL queries](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksAnalyzingSPARQLQuery), also made available through the simple checkbox on the recently revised SPARQL query form, though these are often less easily parsed by users than by Virtuoso developers, who will typically assist if you bring the `EXPLAIN()` output here or to the Community Forum.


Please let me know if this answer is sufficient to consider this issue closed.

**Comment by Invincibled** [comment]
Hi

Yes, your response has been very helpful, however perhaps we need to find best practices in practice that match our own.

I'll check out the community and maybe ask more details.

Thank you very much.
