### ISSUE TITLE
Docker image with virtuoso and loaded data

### ISSUE THREAD

**Issue by ccolonna** [openlink/virtuoso-opensource#995]
Good morning I need to create a Docker image / container exposing a sparql endpoint, with a KG I have, serialized as `.ttl` and `.owl` files.

Do you have any guide or tutorial to do this ?
Do you think is possible to load triples in `.ttl`, `.owl` fiels in an automated way without opening the web panel ?

**Comment by HughWilliams** [comment]
This is possible with our latest Docker images I am advised, although not documented yet, so we are going to produce and publish details on how this can be done on our [community forum](https://community.openlinksw.com), and I shall notify you with link when it is complete ...

**Comment by ccolonna** [comment]
That's a great news! Looking forward to see that!

**Comment by KonradHoeffner** [comment]
@ccolonna: If you need that functionality now before the documentation is out, you can accomplish this with the tenforce/virtuoso container by mounting your .ttl files into `/data/toLoad`. I don't know if .owl works too, maybe you need to convert it.

You can also try https://github.com/Dockerizing/virtuoso-import-docker, it is a bit older but it has some special functionality, like continuous updates from a git repository. It is also based on the tenforce container.

I plan to  switch to the official OpenLink container, once the documentation is out though.

**Comment by KonradHoeffner** [comment]
@HughWilliams: Is there a rough estimate of when this will be implemented? I looked into the community forum but didn't find it on first glance.

**Comment by HughWilliams** [comment]
@KonradHoeffner: This work is still in progress, checking with the development as to when it will be completed ...

**Comment by alpae** [comment]
Same here, would love to see how this should be best done with the official docker image. until then, we're stuck with https://github.com/tenforce/docker-virtuoso. We would prefer though to go with the official image

**Comment by TallTed** [comment]
@HughWilliams @pkleef @openlink -- Any ETA on this documentation for Virtuoso Docker image?

**Comment by KonradHoeffner** [comment]
Is there any update on this? I looked at the following sources but didn't find information on how to load the data on startup:

* https://community.openlinksw.com/t/virtuoso-open-source-7-2-7-release-notes/3143
* https://community.openlinksw.com/t/virtuoso-enterprise-edition-docker-quick-start-guide/285
* https://community.openlinksw.com/t/virtuoso-enterprise-edition-docker-reference-guide/286

I would like to switch from tenforce/docker-virtuoso to openlink/virtuoso-opensource-7:7.2.7 but the automatic configuration is critical for us.

**Comment by pkleef** [comment]
The latest version of  our [`openlink/virtuoso-closedsource-8`](https://hub.docker.com/r/openlink/virtuoso-closedsource-8) and [`openlink/virtuoso-opensource-7`](https://hub.docker.com/r/openlink/virtuoso-opensource-7) docker images contain support for running a combination of shell (.sh) and Virtuoso PL (.sql) scripts as part of the initialization of the database before it goes `online`.

This feature allows you to either mount a directory with your scripts to the `/initdb.d` directory inside the docker image during its creation, or copy your scripts into the `/initdb.d` directory when you prefer to build your own clone of our docker images.

We published a [bulk load example on Github](https://github.com/openlink/vos-docker-bulkload-example) to show how this feature works.

We also added the following section to our [Virtuoso Docker - Reference Guide](https://community.openlinksw.com/t/virtuoso-enterprise-edition-docker-reference-guide/286) as well as to the Overview page of our Docker images.

## `/initdb.d`

This directory can contain a mix of shell (.sh) and Virtuoso PL (.sql) scripts that can perform functions such as:

  * Installing additional Ubuntu packages
  * Loading data from remote locations such as Amazon S3 buckets, Google Drive, or other locations
  * Bulk loading data into the Virtuoso database
  * Installing additional `VAD` packages into the database
  * Adding new Virtuoso users
  * Granting permissions to Virtuoso users
  * Regenerating free-text indexes or other initial data

The scripts are run only once, during the initial database creation; subsequent restarts of the docker image will not cause these script to be re-run.

The scripts are run in alphabetical order, so we suggest starting the script names with sequence numbers, so the ordering is explicit and obvious.

For security purposes, Virtuoso will run the `.sql` scripts in a special mode, and will not respond to connections on its SQL (`1111`) and/or HTTP (`8890`) ports.

At the end of each `.sql` script, Virtuoso automatically performs a `checkpoint`, to make sure the changes are fully written back to the database. This is very important for scripts that use the bulk loader function `rdf_loader_run()` or manually change the ACID mode of the database for any reason.

After all the initialization scripts have run to completion, Virtuoso will be started normally, and start listening to requests on its SQL (`1111`) and HTTP (`8890`) ports.
